/**
 * Question Bank — Mathematics, Class 6, Chapter 8: Decimals
 *
 * 78 curated questions — types: concept(20), ncert(24), competency(20), previous-year(14)
 * Board: Both | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Decimals and Place Value              — 26 q
 *   t2 Comparing Decimals                    — 26 q
 *   t3 Addition and Subtraction of Decimals  — 26 q
 *
 * Key concept nodes:
 *   mth:6:ch08:decimal-place-value      — tenths (1/10), hundredths (1/100), thousandths (1/1000)
 *   mth:6:ch08:decimal-as-fraction      — 0.3 = 3/10; 0.07 = 7/100; 0.005 = 5/1000
 *   mth:6:ch08:decimal-notation         — writing decimals in expanded form and standard form
 *   mth:6:ch08:expanded-form-decimal    — e.g. 4.372 = 4 + 3/10 + 7/100 + 2/1000
 *   mth:6:ch08:comparing-decimals       — compare digit by digit starting from the left (integer part first)
 *   mth:6:ch08:decimal-on-number-line   — locate decimal between two consecutive integers
 *   mth:6:ch08:decimal-between-integers — tenths divide each unit interval into 10 equal parts
 *   mth:6:ch08:decimal-addition         — align decimal points; add column by column; carry
 *   mth:6:ch08:decimal-subtraction      — align decimal points; subtract; borrow if needed
 *   mth:6:ch08:decimal-word-problem     — money, length, mass expressed in decimals
 *
 * v1 2026-07-06
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH08_DECIMALS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Decimals and Place Value
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-6-ch08-con-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is a decimal number? Identify the place value of each digit in 25.364.",
    answer: "A decimal number has two parts separated by a decimal point: the whole number part (left of point) and the decimal part (right of point). In 25.364: 2 → tens (20); 5 → ones (5); 3 → tenths (3/10); 6 → hundredths (6/100); 4 → thousandths (4/1000).",
    steps: [
      { stepNumber: 1, title: "Identify whole part", explanation: "25: 2 is tens, 5 is ones." },
      { stepNumber: 2, title: "Identify decimal part", explanation: "3 is tenths, 6 is hundredths, 4 is thousandths.", result: "Place values listed." },
    ],
    hint: "After the decimal point: first digit = tenths, second = hundredths, third = thousandths.",
    keyConcepts: ["decimal place value", "tenths", "hundredths", "thousandths"],
    conceptsCovered: ["mth:6:ch08:decimal-place-value"],
    prerequisites: [],
    commonErrors: ["Confusing tenths (0.1) with tens (10) — they are on opposite sides of the decimal point"],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Convert to fractions: (a) 0.7  (b) 0.05  (c) 0.003  (d) 0.47.",
    answer: "(a) 0.7 = 7/10. (b) 0.05 = 5/100 = 1/20. (c) 0.003 = 3/1000. (d) 0.47 = 47/100. The denominator is determined by the number of decimal places: 1 place → /10; 2 places → /100; 3 places → /1000.",
    steps: [
      { stepNumber: 1, title: "Count decimal places", explanation: "(a) 1 place → 7/10. (b) 2 places → 5/100. (c) 3 places → 3/1000. (d) 2 places → 47/100." },
      { stepNumber: 2, title: "Results", explanation: "7/10; 1/20; 3/1000; 47/100.", result: "7/10; 5/100; 3/1000; 47/100." },
    ],
    hint: "Count decimal places, then the denominator is 10/100/1000 accordingly.",
    keyConcepts: ["decimal to fraction", "place value denominators"],
    conceptsCovered: ["mth:6:ch08:decimal-as-fraction"],
    prerequisites: [],
    commonErrors: ["Writing 0.05 = 5/10 — there are 2 decimal places so denominator is 100, not 10"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Convert to decimals: (a) 3/10  (b) 57/100  (c) 9/1000  (d) 4 + 5/10 + 2/100.",
    answer: "(a) 0.3. (b) 0.57. (c) 0.009. (d) 4 + 0.5 + 0.02 = 4.52.",
    steps: [
      { stepNumber: 1, title: "Apply place value", explanation: "(a) 3 tenths = 0.3. (b) 57 hundredths = 0.57. (c) 9 thousandths = 0.009." },
      { stepNumber: 2, title: "(d) expanded form", explanation: "4+5/10+2/100=4+0.5+0.02=4.52.", result: "0.3; 0.57; 0.009; 4.52." },
    ],
    hint: "Place value position tells you how many zeros the denominator has.",
    keyConcepts: ["fraction to decimal", "expanded form"],
    conceptsCovered: ["mth:6:ch08:decimal-notation"],
    prerequisites: [],
    commonErrors: ["Writing 9/1000 = 0.09 instead of 0.009 (needs 3 decimal places)"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Write in expanded form: (a) 7.38  (b) 12.405.",
    answer: "(a) 7.38 = 7 + 3/10 + 8/100. Or: 7 + 0.3 + 0.08. (b) 12.405 = 10 + 2 + 4/10 + 0/100 + 5/1000 = 10+2+0.4+0+0.005.",
    steps: [
      { stepNumber: 1, title: "(a) 7.38", explanation: "7 ones + 3 tenths + 8 hundredths = 7+0.3+0.08." },
      { stepNumber: 2, title: "(b) 12.405", explanation: "1 ten + 2 ones + 4 tenths + 0 hundredths + 5 thousandths = 10+2+0.4+0+0.005.", result: "Expanded forms written." },
    ],
    hint: "Assign each digit to its place value and write as sum.",
    keyConcepts: ["expanded form", "place value"],
    conceptsCovered: ["mth:6:ch08:expanded-form-decimal"],
    prerequisites: ["mth:6:ch08:decimal-place-value"],
    commonErrors: ["Omitting the zero placeholder for '0 hundredths' in 12.405"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: 4.50 = 4.5. Justify using place value.",
    answer: "True. 4.50 = 4 + 5/10 + 0/100 = 4 + 5/10 = 4.5. The trailing zero after 5 in the hundredths place adds nothing to the value (0 hundredths = 0). So 4.50 and 4.5 represent the same number. Adding or removing trailing zeros after the last non-zero digit in the decimal part does not change the value.",
    steps: [
      { stepNumber: 1, title: "Expand 4.50", explanation: "4+5/10+0/100 = 4+5/10 = 4.5." },
      { stepNumber: 2, title: "Conclusion", explanation: "Trailing zero adds 0 — no change in value.", result: "TRUE — 4.50 = 4.5." },
    ],
    hint: "Trailing zeros after the decimal point don't change value.",
    keyConcepts: ["trailing zeros", "decimal equivalence"],
    conceptsCovered: ["mth:6:ch08:decimal-place-value"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A measurement is 6 cm 4 mm. Write this in centimetres as a decimal. Also write 2 m 35 cm as metres in decimal.",
    answer: "6 cm 4 mm: 1 mm = 0.1 cm. 4 mm = 0.4 cm. Total = 6.4 cm. 2 m 35 cm: 1 cm = 0.01 m. 35 cm = 0.35 m. Total = 2.35 m.",
    steps: [
      { stepNumber: 1, title: "6 cm 4 mm", explanation: "4 mm = 4/10 cm = 0.4 cm → 6.4 cm." },
      { stepNumber: 2, title: "2 m 35 cm", explanation: "35 cm = 35/100 m = 0.35 m → 2.35 m.", result: "6.4 cm; 2.35 m." },
    ],
    hint: "1 mm = 0.1 cm; 1 cm = 0.01 m.",
    keyConcepts: ["units and decimals", "measurement conversion"],
    conceptsCovered: ["mth:6:ch08:decimal-as-fraction"],
    prerequisites: [],
    commonErrors: ["Writing 6 cm 4 mm = 6.04 cm — 4 mm = 0.4 cm (1 decimal place), not 0.04"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Write the decimal whose: hundreds digit is 3, tens digit is 0, ones digit is 7, tenths digit is 2, hundredths digit is 4.",
    answer: "Hundreds: 3 → 300. Tens: 0 → 0. Ones: 7 → 7. Tenths: 2 → 0.2. Hundredths: 4 → 0.04. Decimal = 300 + 0 + 7 + 0.2 + 0.04 = 307.24.",
    steps: [
      { stepNumber: 1, title: "Build whole part", explanation: "300 + 0 + 7 = 307." },
      { stepNumber: 2, title: "Build decimal part", explanation: "0.2 + 0.04 = 0.24. Full number = 307.24.", result: "307.24." },
    ],
    hint: "Build the number by placing each digit in its position.",
    keyConcepts: ["place value assembly", "decimal from place value specification"],
    conceptsCovered: ["mth:6:ch08:decimal-notation"],
    prerequisites: ["mth:6:ch08:decimal-place-value"],
    commonErrors: ["Reversing whole and decimal parts"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) 1 cm = ________ m.  (b) 1 m = ________ km.  (c) 1 g = ________ kg.",
    answer: "(a) 0.01 m. (b) 0.001 km. (c) 0.001 kg. These show how smaller units express as decimal fractions of larger units.",
    steps: [
      { stepNumber: 1, title: "Apply conversions", explanation: "1 cm = 1/100 m = 0.01 m. 1 m = 1/1000 km = 0.001 km. 1 g = 1/1000 kg = 0.001 kg." },
      { stepNumber: 2, title: "Fill blanks", explanation: "0.01; 0.001; 0.001.", result: "0.01 m; 0.001 km; 0.001 kg." },
    ],
    hint: "100 cm = 1 m; 1000 m = 1 km; 1000 g = 1 kg.",
    keyConcepts: ["unit conversions", "decimal fractions"],
    conceptsCovered: ["mth:6:ch08:decimal-as-fraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write as decimals: (a) 7 kg 250 g  (b) 3 km 450 m  (c) ₹15 and 75 paise.",
    answer: "(a) 250 g = 0.250 kg = 0.25 kg → 7.25 kg. (b) 450 m = 0.450 km = 0.45 km → 3.45 km. (c) 75 paise = 0.75 rupees → ₹15.75.",
    steps: [
      { stepNumber: 1, title: "Convert smaller units", explanation: "(a) 250/1000=0.25 kg. (b) 450/1000=0.45 km. (c) 75/100=0.75 rupees." },
      { stepNumber: 2, title: "Add to whole unit", explanation: "(a) 7.25 kg. (b) 3.45 km. (c) ₹15.75.", result: "7.25 kg; 3.45 km; ₹15.75." },
    ],
    hint: "1000 g = 1 kg; 1000 m = 1 km; 100 paise = 1 rupee.",
    keyConcepts: ["measurement decimals", "unit conversion"],
    conceptsCovered: ["mth:6:ch08:decimal-notation"],
    prerequisites: [],
    commonErrors: ["Writing 7 kg 250 g = 7.250 kg without simplifying trailing zero — technically fine but 7.25 is preferred"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "What is the place value of 5 in each: (a) 15.3  (b) 0.54  (c) 3.052?",
    answer: "(a) 5 is in the ones place → value = 5. (b) 5 is in the tenths place → value = 5/10 = 0.5. (c) 5 is in the thousandths place → value = 5/1000 = 0.005.",
    steps: [
      { stepNumber: 1, title: "Locate 5 in each number", explanation: "(a) 15.3: 5 is ones. (b) 0.54: 5 is first digit after decimal = tenths. (c) 3.052: 5 is third decimal digit = thousandths." },
      { stepNumber: 2, title: "State place values", explanation: "5, 0.5, 0.005.", result: "(a)5, (b)0.5, (c)0.005." },
    ],
    hint: "Count the position of 5 from the decimal point.",
    keyConcepts: ["place value of digit", "different positions"],
    conceptsCovered: ["mth:6:ch08:decimal-place-value"],
    prerequisites: [],
    commonErrors: ["Saying 5 in 0.54 = 50 (treating it as tens) — it's in tenths = 0.5"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) 0.1 = ________ /10.  (b) 0.04 = 4/________.  (c) 0.007 = 7/________.",
    answer: "(a) 1/10. (b) 4/100. (c) 7/1000.",
    steps: [
      { stepNumber: 1, title: "Match digits to denominators", explanation: "(a) tenths: 1/10. (b) hundredths: 4/100. (c) thousandths: 7/1000." },
      { stepNumber: 2, title: "Fill", explanation: "1; 100; 1000.", result: "1; 100; 1000." },
    ],
    hint: "Count decimal places to determine denominator.",
    keyConcepts: ["decimal as fraction", "place value denominators"],
    conceptsCovered: ["mth:6:ch08:decimal-as-fraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Write the expanded form and the decimal: (a) 3×1 + 2×(1/10) + 5×(1/100)  (b) 8×10 + 4×1 + 1×(1/10) + 9×(1/1000).",
    answer: "(a) 3 + 0.2 + 0.05 = 3.25. (b) 80 + 4 + 0.1 + 0.009 = 84.109.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "3+0.2+0.05=3.25." },
      { stepNumber: 2, title: "(b)", explanation: "80+4+0.1+0+0.009=84.109 (zero in hundredths).", result: "(a)3.25. (b)84.109." },
    ],
    hint: "Add each component; be careful about the zero in the hundredths place for (b).",
    keyConcepts: ["expanded form to decimal", "place value"],
    conceptsCovered: ["mth:6:ch08:expanded-form-decimal"],
    prerequisites: [],
    commonErrors: ["(b) writing 84.19 and skipping the zero hundredths placeholder"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Convert to metres: (a) 56 mm  (b) 3 km 200 m 40 cm  (c) 2750 cm.",
    answer: "(a) 56 mm: 10 mm=1 cm; 100 cm=1 m → 56 mm=5.6 cm=0.056 m. (b) 3 km 200 m 40 cm: 3 km=3000 m; 200 m; 40 cm=0.40 m. Total=3000+200+0.40=3200.40 m. (c) 2750 cm = 2750/100 m = 27.50 m.",
    steps: [
      { stepNumber: 1, title: "(a) mm to m", explanation: "1 m=1000 mm. 56/1000=0.056 m." },
      { stepNumber: 2, title: "(b) mixed to m", explanation: "3×1000+200+40/100=3200.40 m." },
      { stepNumber: 3, title: "(c) cm to m", explanation: "2750/100=27.5 m.", result: "(a)0.056 m (b)3200.40 m (c)27.5 m." },
    ],
    hint: "Convert everything to metres: 1 m=100 cm=1000 mm=0.001 km.",
    keyConcepts: ["unit conversions", "decimals in measurement"],
    conceptsCovered: ["mth:6:ch08:decimal-notation"],
    prerequisites: [],
    commonErrors: ["(a) writing 56 mm = 5.6 m instead of 0.056 m"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Write three decimals that lie between 4 and 5. Also write three decimals between 3.4 and 3.5.",
    answer: "Between 4 and 5 (tenths): 4.1, 4.5, 4.9 (many possible). Between 3.4 and 3.5 (hundredths): 3.41, 3.45, 3.49 (many possible). Between any two consecutive tenths there are 9 hundredths: 3.41, 3.42, …, 3.49.",
    steps: [
      { stepNumber: 1, title: "Between 4 and 5", explanation: "Any decimal with 4 in ones place and non-zero tenths: 4.1, 4.5, 4.9." },
      { stepNumber: 2, title: "Between 3.4 and 3.5", explanation: "Use hundredths: 3.41, 3.45, 3.49.", result: "Examples given." },
    ],
    hint: "Between 4 and 5: use tenths. Between 3.4 and 3.5: use hundredths.",
    keyConcepts: ["decimals between decimals", "density of decimals"],
    conceptsCovered: ["mth:6:ch08:decimal-place-value"],
    prerequisites: [],
    commonErrors: ["Confusing tenths (1/10) with hundredths (1/100) place value positions"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A shopkeeper has 3 kg 45 g of dal, 1.4 kg of rice, and 0.375 kg of sugar. Write all in kg as decimals. Which is heaviest?",
    answer: "Dal: 3 kg 45 g = 3 + 45/1000 = 3.045 kg. Rice: 1.4 kg. Sugar: 0.375 kg. Compare: 3.045 > 1.4 > 0.375. Heaviest = dal (3.045 kg).",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "3 kg 45 g = 3.045 kg (45/1000=0.045)." },
      { stepNumber: 2, title: "Compare", explanation: "3.045 > 1.4 > 0.375 → dal is heaviest.", result: "Dal (3.045 kg) is heaviest." },
    ],
    hint: "1 g = 0.001 kg. 45 g = 0.045 kg, not 0.45.",
    keyConcepts: ["mass conversion to decimal", "comparison"],
    conceptsCovered: ["mth:6:ch08:decimal-as-fraction"],
    prerequisites: [],
    commonErrors: ["Writing 3 kg 45 g = 3.45 kg — 45 g = 0.045 kg, not 0.45 kg"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Rohan scored 8.7 out of 10, Sana scored 8.67 out of 10, Tina scored 8.07 out of 10. Rank them from highest to lowest. Explain your comparison.",
    answer: "Compare: 8.7 = 8.70; 8.67; 8.07. Align: ones = 8 for all. Tenths: 7 > 6 > 0. So 8.7 > 8.67 > 8.07. Rank: Rohan > Sana > Tina.",
    steps: [
      { stepNumber: 1, title: "Align decimal places", explanation: "8.70, 8.67, 8.07 — compare tenths: 7>6>0." },
      { stepNumber: 2, title: "Rank", explanation: "8.70 > 8.67 > 8.07 → Rohan, Sana, Tina.", result: "Rohan > Sana > Tina." },
    ],
    hint: "Compare digit by digit: ones first, then tenths, then hundredths.",
    keyConcepts: ["decimal comparison", "ranking decimals"],
    conceptsCovered: ["mth:6:ch08:decimal-notation"],
    prerequisites: [],
    commonErrors: ["Saying 8.67 > 8.7 because 67 > 7 — must compare place by place, not as whole numbers"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "evaluate",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A recipe needs 0.75 kg flour. Your bag has 500 g. Do you have enough? By how many grams do you have extra or are you short?",
    answer: "0.75 kg = 750 g. You have 500 g. 500 < 750, so you do NOT have enough. Short by 750 – 500 = 250 g.",
    steps: [
      { stepNumber: 1, title: "Convert 0.75 kg to grams", explanation: "0.75 × 1000 = 750 g." },
      { stepNumber: 2, title: "Compare", explanation: "500 < 750. Short by 250 g.", result: "Short by 250 g." },
    ],
    hint: "Convert to the same unit before comparing.",
    keyConcepts: ["decimal unit conversion", "comparison", "real-world"],
    conceptsCovered: ["mth:6:ch08:expanded-form-decimal"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A dumbbell is labelled '2.5 kg'. Express this in: (a) grams (b) milligrams.",
    answer: "(a) 2.5 kg = 2.5 × 1000 = 2500 g. (b) 2.5 kg = 2500 g = 2500 × 1000 mg = 2,500,000 mg = 2.5 × 10⁶ mg.",
    steps: [
      { stepNumber: 1, title: "kg to g", explanation: "2.5 × 1000 = 2500 g." },
      { stepNumber: 2, title: "g to mg", explanation: "2500 × 1000 = 2,500,000 mg.", result: "2500 g; 2,500,000 mg." },
    ],
    hint: "1 kg = 1000 g; 1 g = 1000 mg.",
    keyConcepts: ["mass conversions", "decimals in science"],
    conceptsCovered: ["mth:6:ch08:decimal-place-value"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "competency", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Fill in: (a) 8 paise = ₹________. (b) ₹7.05 = ₹7 and ________ paise. (c) 125 paise = ₹________.",
    answer: "(a) 8/100 = ₹0.08. (b) ₹7.05 → 0.05 = 5/100 = 5 paise. (c) 125/100 = ₹1.25.",
    steps: [
      { stepNumber: 1, title: "(a) and (c)", explanation: "(a) 8/100=₹0.08. (c) 125/100=₹1.25." },
      { stepNumber: 2, title: "(b)", explanation: "₹7.05: 0.05=5 paise.", result: "₹0.08; 5 paise; ₹1.25." },
    ],
    hint: "100 paise = ₹1. So 1 paise = ₹0.01.",
    keyConcepts: ["money decimals", "rupees and paise"],
    conceptsCovered: ["mth:6:ch08:decimal-as-fraction"],
    prerequisites: [],
    commonErrors: ["Writing 8 paise = ₹0.8 — 1 paise = ₹0.01, not ₹0.1"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "remember",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Write the smallest 4-digit decimal number with exactly 2 decimal places using digits 1, 3, 5, 7 (each once). Also write the largest.",
    answer: "4-digit decimal with 2 decimal places means format: XY.ZW where X,Y,Z,W are each of 1,3,5,7 once. Smallest: smallest integer part = 13, smallest decimal part = 5,7 → 13.57. Verify smaller options: 1_.__ < 13.__ uses digit 1 in tens, but then smallest 2-digit integer part = 13. So smallest = 13.57. Largest: largest integer part = 75, largest decimal part = __ → 75.31. Check: 73.__ < 75.__ → 75.31 is largest.",
    steps: [
      { stepNumber: 1, title: "Smallest", explanation: "Put smallest digits in integer part: 13. Remaining for decimal: 5,7 (smaller first): 13.57." },
      { stepNumber: 2, title: "Largest", explanation: "Put largest in integer: 75. Remaining: 3,1 (larger first): 75.31.", result: "Smallest: 13.57. Largest: 75.31." },
    ],
    hint: "Format is __.__. Put smallest digits in the most significant positions for smallest number.",
    keyConcepts: ["decimal number formation", "place value ordering"],
    conceptsCovered: ["mth:6:ch08:decimal-notation"],
    prerequisites: [],
    commonErrors: ["Misidentifying which digit is in the tenths vs hundredths place"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "evaluate",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write as decimals: (a) Three and four tenths.  (b) Twenty-five hundredths.  (c) Two hundred five thousandths.",
    answer: "(a) 3.4. (b) 0.25. (c) 0.205.",
    steps: [
      { stepNumber: 1, title: "Translate words to digits", explanation: "(a) 3 and 4/10=3.4. (b) 25/100=0.25. (c) 205/1000=0.205." },
      { stepNumber: 2, title: "Write", explanation: "3.4; 0.25; 0.205.", result: "3.4; 0.25; 0.205." },
    ],
    hint: "Tenths → 1 decimal place; hundredths → 2; thousandths → 3.",
    keyConcepts: ["words to decimal notation"],
    conceptsCovered: ["mth:6:ch08:decimal-place-value"],
    prerequisites: [],
    commonErrors: ["Writing 0.205 as 0.25 — 'two hundred five thousandths' has a zero in the hundredths place"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Express 4/5 and 3/8 as decimals.",
    answer: "4/5: multiply by 2/2 to get 8/10 = 0.8. 3/8: multiply by 125/125 to get 375/1000 = 0.375.",
    steps: [
      { stepNumber: 1, title: "4/5 to decimal", explanation: "4/5 = 8/10 = 0.8." },
      { stepNumber: 2, title: "3/8 to decimal", explanation: "3/8 = 375/1000 = 0.375.", result: "0.8; 0.375." },
    ],
    hint: "Convert denominator to a power of 10 by multiplication.",
    keyConcepts: ["fraction to decimal conversion"],
    conceptsCovered: ["mth:6:ch08:decimal-as-fraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) 2.8 = 2 + ________ /10.  (b) 5.032 = 5 + 0/10 + 3/100 + ________/1000.",
    answer: "(a) 8. (b) 2.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "2.8: tenths digit = 8 → 8/10." },
      { stepNumber: 2, title: "(b)", explanation: "5.032: thousandths digit = 2 → 2/1000.", result: "8; 2." },
    ],
    hint: "Read the digit at each place value position.",
    keyConcepts: ["expanded form", "place value digits"],
    conceptsCovered: ["mth:6:ch08:expanded-form-decimal"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A rod is 1 m 25 cm 4 mm long. Express this in metres as a decimal.",
    answer: "1 m = 1 m. 25 cm = 25/100 m = 0.25 m. 4 mm = 4/1000 m = 0.004 m. Total = 1 + 0.25 + 0.004 = 1.254 m.",
    steps: [
      { stepNumber: 1, title: "Convert each unit", explanation: "1 m + 0.25 m + 0.004 m." },
      { stepNumber: 2, title: "Add", explanation: "1.254 m.", result: "1.254 m." },
    ],
    hint: "1 cm = 0.01 m; 1 mm = 0.001 m.",
    keyConcepts: ["mixed unit to decimal", "metre conversion"],
    conceptsCovered: ["mth:6:ch08:decimal-notation"],
    prerequisites: [],
    commonErrors: ["Writing 1.254 as 1.25 + 4 = 1.29 — must add decimals properly"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Name the place value of the underlined digit: (a) 3.4_8_  (b) 1_2_.7  (c) 0.0_5_2.",
    answer: "(a) 8 is in the hundredths place (2nd decimal digit). (b) 2 is in the ones place. (c) 5 is in the thousandths place (3rd decimal digit... wait: 0.052 → 0 is tenths, 5 is hundredths, 2 is thousandths. So 5 is hundredths).",
    steps: [
      { stepNumber: 1, title: "Locate each digit", explanation: "(a) 3.48: 8 = hundredths. (b) 12.7: 2 = ones. (c) 0.052: 5 = hundredths." },
      { stepNumber: 2, title: "Name place", explanation: "hundredths; ones; hundredths.", result: "(a) hundredths. (b) ones. (c) hundredths." },
    ],
    hint: "After decimal: 1st = tenths, 2nd = hundredths, 3rd = thousandths.",
    keyConcepts: ["place value naming"],
    conceptsCovered: ["mth:6:ch08:decimal-place-value"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t1", topicName: "Decimals and Place Value",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write 253.047 in words.",
    answer: "Two hundred and fifty-three and forty-seven thousandths. Or: 253 point 0 4 7. Expanded: 253.047 = 253 + 0/10 + 4/100 + 7/1000 = two hundred fifty-three and forty-seven thousandths.",
    steps: [
      { stepNumber: 1, title: "Whole part", explanation: "253 = two hundred fifty-three." },
      { stepNumber: 2, title: "Decimal part", explanation: ".047 = 47 thousandths (note zero in tenths).", result: "Two hundred fifty-three and forty-seven thousandths." },
    ],
    hint: "Decimal part: count all three places together — 047 = 47 thousandths.",
    keyConcepts: ["decimal in words", "place value"],
    conceptsCovered: ["mth:6:ch08:expanded-form-decimal"],
    prerequisites: [],
    commonErrors: ["Writing 'forty-seven hundredths' instead of 'forty-seven thousandths'"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Comparing Decimals
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-6-ch08-con-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Explain the rule for comparing two decimal numbers. Compare 0.8 and 0.75.",
    answer: "Rule: (1) Compare whole number parts first. If equal, (2) compare digit by digit from tenths place rightward. Add trailing zeros to make equal decimal places if needed. Comparing 0.8 and 0.75: write 0.80 and 0.75. Whole parts equal (0). Tenths: 8 > 7. So 0.80 > 0.75, i.e., 0.8 > 0.75.",
    steps: [
      { stepNumber: 1, title: "State the rule", explanation: "Compare whole parts; then tenths; then hundredths; etc." },
      { stepNumber: 2, title: "Apply to 0.8 vs 0.75", explanation: "0.80 vs 0.75: tenths 8>7 → 0.8 > 0.75.", result: "0.8 > 0.75." },
    ],
    hint: "Add trailing zero: 0.8 = 0.80. Then compare digit by digit.",
    keyConcepts: ["comparing decimals", "digit-by-digit rule"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: ["Saying 0.75 > 0.8 because 75 > 8 (treating decimal parts as whole numbers)"],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Arrange in ascending order: 2.3, 2.03, 2.33, 2.003.",
    answer: "Add trailing zeros to get same decimal places: 2.300, 2.030, 2.330, 2.003. Whole part = 2 for all. Tenths: 3, 0, 3, 0. Sort: 2.003 (tenths=0, then hundredths=0, thousandths=3) < 2.030 (tenths=0, hundredths=3) < 2.300 (tenths=3, hundredths=0) < 2.330 (tenths=3, hundredths=3). Ascending: 2.003, 2.03, 2.3, 2.33.",
    steps: [
      { stepNumber: 1, title: "Equalise decimal places", explanation: "All to 3 places: 2.300, 2.030, 2.330, 2.003." },
      { stepNumber: 2, title: "Compare", explanation: "003 < 030 < 300 < 330 → 2.003 < 2.03 < 2.3 < 2.33.", result: "2.003, 2.03, 2.3, 2.33." },
    ],
    hint: "Make all decimals have the same number of places by adding zeros, then compare.",
    keyConcepts: ["ascending order of decimals", "equalized decimal places"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: ["Thinking 2.3 < 2.03 because 3 < 03 — must align decimal places"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Mark the following on a number line (between 0 and 2): 0.5, 1.0, 1.5, 1.8, 0.2.",
    answer: "Divide each unit (0–1 and 1–2) into 10 equal parts. Each small division = 0.1. Positions: 0.2 → 2nd mark after 0; 0.5 → 5th mark (midpoint of 0–1); 1.0 → exactly at 1; 1.5 → midpoint of 1–2; 1.8 → 8th mark after 1. Order: 0.2 < 0.5 < 1.0 < 1.5 < 1.8.",
    steps: [
      { stepNumber: 1, title: "Set up number line", explanation: "10 divisions per unit → each = 0.1." },
      { stepNumber: 2, title: "Plot points", explanation: "0.2=2nd, 0.5=5th, 1.0=10th, 1.5=15th, 1.8=18th.", result: "Points plotted in order: 0.2, 0.5, 1.0, 1.5, 1.8." },
    ],
    hint: "Divide each unit into 10 equal parts; each part = 0.1.",
    keyConcepts: ["number line for decimals", "tenths on number line"],
    conceptsCovered: ["mth:6:ch08:decimal-on-number-line"],
    prerequisites: [],
    commonErrors: ["Placing 1.8 closer to 2 than to 1.5 without accurate counting"],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: 3.009 > 3.1. Justify.",
    answer: "False. 3.009 < 3.1. Compare: Whole part = 3 for both. Tenths: 3.009 has 0 tenths; 3.1 has 1 tenth. 0 < 1 → 3.009 < 3.1. The trap is that 009 looks like a large number after the decimal, but we compare place by place: tenths 0 < 1.",
    steps: [
      { stepNumber: 1, title: "Compare tenths digits", explanation: "3.009: tenths=0. 3.1: tenths=1. 0<1." },
      { stepNumber: 2, title: "Conclude", explanation: "3.009 < 3.1. FALSE.", result: "FALSE — 3.009 < 3.1." },
    ],
    hint: "Compare tenths digit first: 3.009 has tenths=0, while 3.1 has tenths=1.",
    keyConcepts: ["comparing decimals", "tenths comparison"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: ["Thinking 3.009 > 3.1 because '009' appears larger than '1' as a number"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Write two decimal numbers between 0.5 and 0.6.",
    answer: "Between 0.5 and 0.6 (tenths already fixed at 5 and 6): use hundredths. 0.50 < 0.51 < 0.52 ... < 0.59 < 0.60. Any two from 0.51, 0.52, …, 0.59. For example: 0.52 and 0.57.",
    steps: [
      { stepNumber: 1, title: "Extend to hundredths", explanation: "0.5=0.50; 0.6=0.60. Numbers between: 0.51, 0.52, …, 0.59." },
      { stepNumber: 2, title: "Pick two", explanation: "0.52 and 0.57 (many valid answers).", result: "E.g., 0.52 and 0.57." },
    ],
    hint: "Use hundredths: between 0.50 and 0.60 there are 9 hundredths values.",
    keyConcepts: ["decimals between decimals", "hundredths"],
    conceptsCovered: ["mth:6:ch08:decimal-between-integers"],
    prerequisites: [],
    commonErrors: ["Saying there is no decimal between 0.5 and 0.6 — infinitely many exist"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Which is greater: 0.7 or 7/8? Show your working.",
    answer: "Convert to compare: 7/8 = 0.875 (8×125=1000; 7×125=875; so 7/8=875/1000=0.875). Alternatively: 0.7 = 7/10 = 700/1000. Compare 700/1000 vs 875/1000: 700 < 875 → 7/10 < 7/8. So 7/8 > 0.7.",
    steps: [
      { stepNumber: 1, title: "Convert 7/8 to decimal", explanation: "7/8=0.875." },
      { stepNumber: 2, title: "Compare", explanation: "0.875 > 0.700 → 7/8 > 0.7.", result: "7/8 > 0.7." },
    ],
    hint: "Convert the fraction to a decimal, then compare.",
    keyConcepts: ["fraction vs decimal comparison", "conversion"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: ["Saying 0.7 > 7/8 because 7 is close to 8 — must compute 7/8 = 0.875"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in using > or <: (a) 1.9 __ 1.09  (b) 0.7 __ 0.70  (c) 10.001 __ 10.01.",
    answer: "(a) 1.9 > 1.09 (tenths: 9>0). (b) 0.7 = 0.70 (same value; use =). (c) 10.001 < 10.01 (hundredths: 0<1).",
    steps: [
      { stepNumber: 1, title: "Align decimal places", explanation: "(a) 1.90 vs 1.09: tenths 9>0. (b) 0.70=0.70. (c) 10.001 vs 10.010: hundredths 0<1." },
      { stepNumber: 2, title: "Fill blanks", explanation: "(a)> (b)= (c)<.", result: ">; =; <." },
    ],
    hint: "Make equal decimal places, then compare place by place.",
    keyConcepts: ["decimal comparison symbols"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: ["(a) saying 1.9 < 1.09 because 1.09 has more digits after the decimal"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Arrange in descending order: 0.3, 0.03, 3.0, 0.003, 0.33.",
    answer: "Write with equal places: 3.000, 0.330, 0.300, 0.030, 0.003. Descending (largest first): 3.000 > 0.330 > 0.300 > 0.030 > 0.003. Order: 3.0, 0.33, 0.3, 0.03, 0.003.",
    steps: [
      { stepNumber: 1, title: "Equalize to 3 decimal places", explanation: "3.000; 0.330; 0.300; 0.030; 0.003." },
      { stepNumber: 2, title: "Sort descending", explanation: "3.000>0.330>0.300>0.030>0.003.", result: "3.0, 0.33, 0.3, 0.03, 0.003." },
    ],
    hint: "Write all to 3 decimal places, then sort the 3-digit decimal parts in reverse.",
    keyConcepts: ["descending order", "decimal comparison"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Between which two consecutive whole numbers does each lie: (a) 4.7  (b) 0.3  (c) 12.05?",
    answer: "(a) 4 < 4.7 < 5. (b) 0 < 0.3 < 1. (c) 12 < 12.05 < 13.",
    steps: [
      { stepNumber: 1, title: "Identify whole part", explanation: "(a) 4. (b) 0. (c) 12." },
      { stepNumber: 2, title: "State range", explanation: "Number lies between its whole part and whole part + 1.", result: "4 and 5; 0 and 1; 12 and 13." },
    ],
    hint: "The whole number part tells you which two consecutive whole numbers surround it.",
    keyConcepts: ["locating decimals between integers", "number line"],
    conceptsCovered: ["mth:6:ch08:decimal-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the greatest and smallest from: 0.9, 0.099, 0.909, 0.009, 0.99.",
    answer: "Align to 3 decimal places: 0.900, 0.099, 0.909, 0.009, 0.990. Compare: 0.990 > 0.909 > 0.900 > 0.099 > 0.009. Greatest = 0.99. Smallest = 0.009.",
    steps: [
      { stepNumber: 1, title: "Align all to 3 places", explanation: "0.900, 0.099, 0.909, 0.009, 0.990." },
      { stepNumber: 2, title: "Order", explanation: "0.990>0.909>0.900>0.099>0.009. Greatest=0.99, Smallest=0.009.", result: "Greatest: 0.99. Smallest: 0.009." },
    ],
    hint: "Pad with zeros to get 3 decimal places for easy comparison.",
    keyConcepts: ["greatest and smallest decimal"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: ["Treating 0.9 < 0.099 because '099' seems larger"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Four students in a 100-metre race finish in times: 14.3 s, 14.03 s, 14.30 s, 14.003 s. Who wins (shortest time)? Rank all four.",
    answer: "Align: 14.300, 14.030, 14.300, 14.003. Note 14.3 = 14.30 = 14.300; so two students share the same time! Compare: 14.003 < 14.030 < 14.300 (= 14.3 = 14.30). Rank: 1st: 14.003 s, 2nd: 14.03 s, 3rd (tied): 14.3 s and 14.30 s (same time).",
    steps: [
      { stepNumber: 1, title: "Align to 3 places", explanation: "14.300, 14.030, 14.300, 14.003." },
      { stepNumber: 2, title: "Sort ascending (fastest = smallest)", explanation: "14.003 < 14.030 < 14.300 = 14.300.", result: "Winner: 14.003 s. Then 14.03 s. Then 14.3 s and 14.30 s (tied)." },
    ],
    hint: "Shortest time = winner in a race. 14.3 = 14.30 = same time.",
    keyConcepts: ["decimal in timing", "recognising equal decimals", "real-world"],
    conceptsCovered: ["mth:6:ch08:decimal-on-number-line"],
    prerequisites: [],
    commonErrors: ["Not recognising that 14.3 = 14.30 (trailing zero)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the decimal that is one-tenth more and one-tenth less than each: (a) 4.5  (b) 2.9  (c) 7.0.",
    answer: "(a) One-tenth more: 4.5+0.1=4.6. One-tenth less: 4.5–0.1=4.4. (b) More: 2.9+0.1=3.0. Less: 2.9–0.1=2.8. (c) More: 7.0+0.1=7.1. Less: 7.0–0.1=6.9.",
    steps: [
      { stepNumber: 1, title: "Add and subtract 0.1", explanation: "(a)4.6, 4.4. (b)3.0, 2.8. (c)7.1, 6.9." },
      { stepNumber: 2, title: "Note (b)", explanation: "2.9+0.1=3.0 — crosses to next whole number.", result: "See above." },
    ],
    hint: "Add or subtract 0.1 (one-tenth) to each decimal.",
    keyConcepts: ["incrementing decimals by 0.1"],
    conceptsCovered: ["mth:6:ch08:decimal-between-integers"],
    prerequisites: [],
    commonErrors: ["(b) saying 2.9+0.1=2.10 — correct is 3.0"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) The smallest decimal number with 2 decimal places greater than 5 is ________. (b) The largest decimal number with 1 decimal place less than 3 is ________.",
    answer: "(a) 5.01. (b) 2.9.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "Just above 5 with 2 dp: 5.01." },
      { stepNumber: 2, title: "(b)", explanation: "Just below 3 with 1 dp: 2.9 (since 3.0 minus one-tenth = 2.9).", result: "5.01; 2.9." },
    ],
    hint: "For (a): just add 0.01 to 5. For (b): subtract 0.1 from 3.",
    keyConcepts: ["nearest decimal", "decimal comparison"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "evaluate",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Write all tenths between 4 and 5. How many are there?",
    answer: "Tenths between 4 and 5 (exclusive): 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9. That is 9 tenths.",
    steps: [
      { stepNumber: 1, title: "List", explanation: "4.1 through 4.9." },
      { stepNumber: 2, title: "Count", explanation: "9 values.", result: "9 tenths between 4 and 5." },
    ],
    hint: "Each unit interval on the number line is divided into 10 equal tenths.",
    keyConcepts: ["tenths on number line", "counting decimals"],
    conceptsCovered: ["mth:6:ch08:decimal-on-number-line"],
    prerequisites: [],
    commonErrors: ["Including 4.0 and 5.0 and counting 11 — exclusive means don't include endpoints"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A petrol pump charges ₹105.78 per litre of petrol and ₹94.56 per litre of diesel. (a) Which fuel is more expensive? (b) By how much?",
    answer: "(a) 105.78 > 94.56 → Petrol is more expensive. (b) Difference = 105.78 – 94.56 = 11.22. Petrol is ₹11.22 per litre more expensive than diesel.",
    steps: [
      { stepNumber: 1, title: "Compare", explanation: "105.78 > 94.56 (whole part 105 > 94). Petrol more expensive." },
      { stepNumber: 2, title: "Find difference", explanation: "105.78 – 94.56 = 11.22.", result: "Petrol; ₹11.22 more expensive." },
    ],
    hint: "Compare whole number parts first; then compute the difference.",
    keyConcepts: ["decimal comparison", "decimal subtraction", "real-world"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: ["Comparing decimal digits without aligning decimal points and place values first"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Heights of five plants: 12.3 cm, 12.03 cm, 12.30 cm, 12.003 cm, 12.33 cm. Which is tallest? Which are equal in height?",
    answer: "Align to 3 dp: 12.300, 12.030, 12.300, 12.003, 12.330. Equal heights: 12.3 = 12.30 = 12.300 (same plant height — first and third plants are equal). Ordering: 12.330 > 12.300 = 12.300 > 12.030 > 12.003. Tallest = 12.33 cm.",
    steps: [
      { stepNumber: 1, title: "Align", explanation: "12.300, 12.030, 12.300, 12.003, 12.330." },
      { stepNumber: 2, title: "Find tallest and equal", explanation: "12.330 tallest. 12.300=12.300: plants 1 and 3 are equal.", result: "Tallest: 12.33 cm. Equal: 12.3 and 12.30." },
    ],
    hint: "Add trailing zeros to standardize, then compare.",
    keyConcepts: ["comparing measurements", "equal decimals with trailing zeros"],
    conceptsCovered: ["mth:6:ch08:decimal-between-integers"],
    prerequisites: [],
    commonErrors: ["Confusing which two consecutive integers the decimal lies between"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A length is given as 0.25 m. Write it in cm and mm. Then write two measurements in cm that are larger than 25 cm but smaller than 26 cm.",
    answer: "0.25 m = 25 cm = 250 mm. Two measurements in cm between 25 and 26: 25.5 cm and 25.8 cm (many valid answers).",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "0.25 m = 25 cm (×100). 25 cm = 250 mm (×10)." },
      { stepNumber: 2, title: "Between 25 and 26 cm", explanation: "E.g., 25.5 and 25.8.", result: "25 cm, 250 mm; e.g. 25.5 cm and 25.8 cm." },
    ],
    hint: "Between any two consecutive whole cm, there are many decimal cm values.",
    keyConcepts: ["unit conversion", "decimals between integers"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "competency", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Fill in using <, =, or >: (a) 1.5 km __ 1500 m.  (b) 0.75 m __ 750 mm.  (c) 2.45 kg __ 2450 g.",
    answer: "(a) 1.5 km = 1500 m (1 km=1000 m; 1.5×1000=1500). So =. (b) 0.75 m = 75 cm = 750 mm. So =. (c) 2.45 kg = 2450 g. So =.",
    steps: [
      { stepNumber: 1, title: "Convert left side", explanation: "(a)1500 m=(a)✓; (b)750 mm=✓; (c)2450 g=✓." },
      { stepNumber: 2, title: "Compare", explanation: "All equal.", result: "=; =; =." },
    ],
    hint: "Convert to the same unit, then compare.",
    keyConcepts: ["unit conversions with decimals"],
    conceptsCovered: ["mth:6:ch08:decimal-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Arrange in ascending order: 1.08, 1.8, 1.008, 1.80.",
    answer: "Align: 1.080, 1.800, 1.008, 1.800. Note 1.8 = 1.80 (same). Order: 1.008 < 1.080 < 1.800 (=1.8=1.80). Ascending: 1.008, 1.08, 1.8, 1.80.",
    steps: [
      { stepNumber: 1, title: "Align to 3 dp", explanation: "1.080; 1.800; 1.008; 1.800." },
      { stepNumber: 2, title: "Sort and note equal pair", explanation: "1.008<1.080<1.800=1.800.", result: "1.008, 1.08, 1.8 (=1.80)." },
    ],
    hint: "1.8 = 1.80. After adding zeros: compare 1.008 vs 1.080 vs 1.800.",
    keyConcepts: ["ascending order", "trailing zeros"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t2", topicName: "Comparing Decimals",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) 0.5 __ 0.50.  (b) 3.6 __ 3.60 __ 3.600.  (c) 7.4 __ 7.45 __ 7.5.",
    answer: "(a) = (trailing zero). (b) = and = (all equal). (c) 7.4 < 7.45 < 7.5.",
    steps: [
      { stepNumber: 1, title: "(a) and (b)", explanation: "Trailing zeros don't change value: 0.5=0.50; 3.6=3.60=3.600." },
      { stepNumber: 2, title: "(c)", explanation: "7.40 < 7.45 < 7.50. Use < and <.", result: "=; = and =; < and <." },
    ],
    hint: "Trailing zeros on the right of decimals don't change value.",
    keyConcepts: ["trailing zeros", "decimal comparison"],
    conceptsCovered: ["mth:6:ch08:comparing-decimals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t3 — Addition and Subtraction of Decimals
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-6-ch08-con-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is the key rule for adding or subtracting decimal numbers? Add 5.43 + 2.8.",
    answer: "Key rule: ALIGN THE DECIMAL POINTS. Write numbers one below the other with decimal points in a column. Add trailing zeros if needed. Then add column by column, right to left, carrying as needed. 5.43 + 2.80: 3+0=3; 4+8=12 write 2 carry 1; 5+2+1=8. Answer: 8.23.",
    steps: [
      { stepNumber: 1, title: "Align decimal points", explanation: "5.43 + 2.80 (write 2.80 for 2.8)." },
      { stepNumber: 2, title: "Add column by column", explanation: "0.03+0.00=0.03; 0.4+0.8=1.2 (carry); 5+2+1=8. Answer: 8.23.", result: "8.23." },
    ],
    hint: "The most important rule: line up the decimal points before adding.",
    keyConcepts: ["decimal addition", "aligning decimal points"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: ["Not aligning decimal points — e.g., writing 5.43+28 instead of 5.43+2.80"],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Subtract: 8.7 – 3.25.",
    answer: "Align: 8.70 – 3.25. Hundredths: 0–5 → borrow: 10–5=5; Tenths: 7–1(borrowed)–2=4; Ones: 8–3=5. Answer: 5.45.",
    steps: [
      { stepNumber: 1, title: "Write 8.7 as 8.70", explanation: "Align: 8.70 – 3.25." },
      { stepNumber: 2, title: "Subtract with borrowing", explanation: "Hundredths: borrow → 5. Tenths: 6–2=4. Ones: 8–3=5. → 5.45.", result: "5.45." },
    ],
    hint: "Write 8.7 as 8.70, then subtract column by column. Borrow when needed.",
    keyConcepts: ["decimal subtraction", "borrowing"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: ["Subtracting without borrowing: writing 8.70–3.25 = 5.45 but making error at hundredths: 0–5 needs borrowing"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Compute: (a) 4.37 + 2.9 + 0.08  (b) 12.04 – 5.6.",
    answer: "(a) Align: 4.37+2.90+0.08 = 7.35. (b) 12.04–5.60=6.44.",
    steps: [
      { stepNumber: 1, title: "(a) align and add", explanation: "4.37+2.90+0.08: hundredths 7+0+8=15(carry1); tenths 3+9+0+1=13(carry1); ones 4+2+0+1=7. Sum=7.35." },
      { stepNumber: 2, title: "(b) subtract", explanation: "12.04–5.60: hundredths 4–0=4; tenths 0–6→borrow→10–6=4, ones 2–1(borrowed)–5→borrow→12–1–5=6, tens 1–1=0. Hmm: 12.04–5.60: let me redo. Tenths: 0–6→borrow: 10–6=4, ones 2–1(borrow)=1, but wait: ones after borrow from tens: 1 → 1–5 → borrow from tens: 11–5=6. Tens 1–1(borrow)=0. So 12.04–5.60=6.44.", result: "(a)7.35. (b)6.44." },
    ],
    hint: "Align decimal points, add trailing zeros for equal decimal places.",
    keyConcepts: ["decimal arithmetic", "multi-digit decimals"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: ["Not aligning decimals properly in (a) which has different decimal places"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-017",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Ravi has ₹50. He spends ₹12.75 on snacks and ₹18.50 on stationery. How much does he have left?",
    answer: "Total spent = 12.75 + 18.50 = 31.25. Left = 50.00 – 31.25 = 18.75. Ravi has ₹18.75 left.",
    steps: [
      { stepNumber: 1, title: "Total spent", explanation: "12.75+18.50=31.25." },
      { stepNumber: 2, title: "Amount left", explanation: "50.00–31.25=18.75.", result: "₹18.75." },
    ],
    hint: "Add expenses first, then subtract from total.",
    keyConcepts: ["decimal money arithmetic", "word problem"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: ["mth:6:ch08:decimal-addition"],
    commonErrors: ["Subtracting both amounts separately: 50–12.75=37.25; 37.25–18.50=18.75 — actually same answer!"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-018",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: 0.4 + 0.04 + 0.004 = 0.444. Justify.",
    answer: "True. 0.4 = 0.400; 0.04 = 0.040; 0.004 = 0.004. Sum = 0.400+0.040+0.004 = 0.444. The pattern shows each successive term fills the next decimal place. This is because 0.4+0.04+0.004 = 4/10 + 4/100 + 4/1000 = 400/1000 + 40/1000 + 4/1000 = 444/1000 = 0.444.",
    steps: [
      { stepNumber: 1, title: "Align and add", explanation: "0.400+0.040+0.004=0.444." },
      { stepNumber: 2, title: "Verify with fractions", explanation: "4/10+4/100+4/1000=444/1000=0.444 ✓.", result: "TRUE." },
    ],
    hint: "Align decimal points: 0.4=0.400; 0.04=0.040; 0.004. Then add.",
    keyConcepts: ["decimal addition pattern", "place value"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.INTERESTING],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-con-019",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Three pieces of wire measure 2.75 m, 1.8 m, and 0.95 m. If joined end to end, is the total length more or less than 6 m? By how much?",
    answer: "Total = 2.75+1.80+0.95. Align: 2.75+1.80+0.95. Hundredths: 5+0+5=10(write 0 carry 1). Tenths: 7+8+9+1=25(write 5 carry 2). Ones: 2+1+0+2=5. Total = 5.50 m. Compare: 5.50 < 6. Short by 6.00–5.50=0.50 m.",
    steps: [
      { stepNumber: 1, title: "Add the three lengths", explanation: "2.75+1.80+0.95=5.50 m." },
      { stepNumber: 2, title: "Compare to 6 m", explanation: "5.50 < 6. Difference = 0.50 m.", result: "5.50 m total; 0.50 m short of 6 m." },
    ],
    hint: "Add all three, then subtract from 6.",
    keyConcepts: ["adding three decimals", "comparison to target"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: ["Computing 2.75+1.8+0.95=5.50 as 5.48 (addition error)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: (a) 3.5 + 2.45  (b) 6.07 + 2.3 + 1.05.",
    answer: "(a) 3.50+2.45=5.95. (b) 6.07+2.30+1.05=9.42.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "3.50+2.45: hundredths 0+5=5; tenths 5+4=9; ones 3+2=5. = 5.95." },
      { stepNumber: 2, title: "(b)", explanation: "6.07+2.30+1.05: hundredths 7+0+5=12(carry1); tenths 0+3+0+1=4; ones 6+2+1=9. = 9.42.", result: "(a)5.95. (b)9.42." },
    ],
    hint: "Align decimal points; add trailing zeros.",
    keyConcepts: ["decimal addition"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-017",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "evaluate",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Subtract: (a) 7.25 – 4.8  (b) 10 – 3.67.",
    answer: "(a) 7.25–4.80=2.45. (b) 10.00–3.67=6.33.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "7.25–4.80: hundredths 5–0=5; tenths 2–8→borrow: 12–8=4, ones 7–1–4=2. = 2.45." },
      { stepNumber: 2, title: "(b)", explanation: "10.00–3.67: Start from right: 0–7 borrow; 10–7=3; 0–1(borrow)–6→borrow: 10–1–6=3; 10(borrowed from tens)–1–3=6; tens 0–1(borrow from hundreds... 10.00 → ones=0, tens=1): 9–1(borrow)–0=9 no wait. Let me re-compute: 10.00–3.67. Write 10.00–3.67: hundredths: 0–7→borrow→10–7=3; tenths: 0–1(b)–6→borrow→10–7=3; ones: 0–1(b)–3→borrow→10–4=6; tens: 1–1(b)=0. Result: 6.33.", result: "(a)2.45. (b)6.33." },
    ],
    hint: "Write 10 as 10.00. Then subtract with borrowing.",
    keyConcepts: ["decimal subtraction", "borrowing from whole number"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: ["(b) common error: 10–3.67≠6.43 — requires careful borrowing"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-018",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Anu covers a distance of 4.8 km on foot and 7.35 km by bus. How much total distance does she cover? If her home is 12 km from school, how much is left?",
    answer: "Total = 4.80+7.35=12.15 km. Remaining = 12.00–12.15 = –0.15 km. Wait — 12.15 > 12.00. She has already exceeded 12 km. She has gone 0.15 km MORE than the school distance. Actually: she covered 12.15 km, school is 12 km, so she's gone 0.15 km past the school.",
    steps: [
      { stepNumber: 1, title: "Total distance", explanation: "4.80+7.35=12.15 km." },
      { stepNumber: 2, title: "Vs school distance 12 km", explanation: "12.15–12.00=0.15 km past school. She has exceeded.", result: "Total: 12.15 km; she passed school by 0.15 km." },
    ],
    hint: "Add the two distances. If total > 12, she's gone past school.",
    keyConcepts: ["decimal addition word problem", "comparison to target"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-019",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the value of: 3.4 + 2.07 – 1.3 – 0.57.",
    answer: "Compute step by step: 3.40+2.07=5.47. 5.47–1.30=4.17. 4.17–0.57=3.60. Answer: 3.6.",
    steps: [
      { stepNumber: 1, title: "Add first two", explanation: "3.40+2.07=5.47." },
      { stepNumber: 2, title: "Subtract last two", explanation: "5.47–1.30=4.17; 4.17–0.57=3.60.", result: "3.6." },
    ],
    hint: "Compute left to right, keeping decimal points aligned at each step.",
    keyConcepts: ["combined addition subtraction", "multi-step decimal"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: ["Not aligning decimal points before subtracting, leading to digit-level errors"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-020",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Mohan weighs 58.4 kg. His friend Kiran weighs 4.75 kg less than Mohan. What is Kiran's weight?",
    answer: "Kiran's weight = 58.40 – 4.75 = 53.65 kg.",
    steps: [
      { stepNumber: 1, title: "Set up subtraction", explanation: "58.40 – 4.75." },
      { stepNumber: 2, title: "Compute", explanation: "Hundredths: 0–5→borrow→10–5=5. Tenths: 4–1–7→borrow→14–8=6. Ones: 8–1–4=3. Tens: 5–0=5. Result: 53.65.", result: "53.65 kg." },
    ],
    hint: "Write 58.4 as 58.40 for alignment, then subtract.",
    keyConcepts: ["decimal subtraction", "word problem"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: ["Using the wrong operation or forgetting to check units after computing"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-021",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) 2.3 + ________ = 5.  (b) ________ – 1.4 = 3.6.  (c) 0.9 + 0.9 = ________.",
    answer: "(a) 5–2.3=2.7. (b) 3.6+1.4=5. (c) 1.8.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "n=5–2.3=2.7." },
      { stepNumber: 2, title: "(b) and (c)", explanation: "(b) n=3.6+1.4=5. (c) 0.9+0.9=1.8.", result: "2.7; 5; 1.8." },
    ],
    hint: "Rearrange each equation to isolate the unknown.",
    keyConcepts: ["decimal equations", "missing value"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-022",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A book costs ₹85.50, a pen costs ₹12.75, and an eraser costs ₹3.25. What is the total cost? If you pay ₹200, what change do you receive?",
    answer: "Total = 85.50+12.75+3.25=101.50. Change = 200.00–101.50=98.50. You receive ₹98.50 change.",
    steps: [
      { stepNumber: 1, title: "Add costs", explanation: "85.50+12.75+3.25=101.50." },
      { stepNumber: 2, title: "Change", explanation: "200.00–101.50=98.50.", result: "Total: ₹101.50. Change: ₹98.50." },
    ],
    hint: "Add all costs first, then subtract from ₹200.",
    keyConcepts: ["decimal addition", "money", "real-world"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-023",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A runner's lap times are: 54.23 s, 53.9 s, 55.1 s, 54.05 s. Find total time for all four laps.",
    answer: "Align: 54.23+53.90+55.10+54.05. Hundredths: 3+0+0+5=8. Tenths: 2+9+1+0=12(carry1). Ones: 4+3+5+4+1=17(carry1). Tens: 5+5+5+5+1=21. Total=217.28 s.",
    steps: [
      { stepNumber: 1, title: "Align to 2 decimal places", explanation: "53.9→53.90; 55.1→55.10." },
      { stepNumber: 2, title: "Add column by column", explanation: "54.23+53.90+55.10+54.05=217.28 s.", result: "217.28 s." },
    ],
    hint: "Add trailing zeros so all have 2 decimal places, then add.",
    keyConcepts: ["adding multiple decimals", "sports timing"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: ["Misaligning decimal points when adding, causing incorrect place-value addition"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-nce-024",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The perimeter of a rectangle is needed. Its length is 4.5 cm and width is 2.75 cm. Find the perimeter.",
    answer: "Perimeter = 2(length + width) = 2(4.5+2.75) = 2×7.25 = 14.5 cm.",
    steps: [
      { stepNumber: 1, title: "Add length and width", explanation: "4.50+2.75=7.25 cm." },
      { stepNumber: 2, title: "Multiply by 2", explanation: "2×7.25=14.50=14.5 cm.", result: "14.5 cm." },
    ],
    hint: "Perimeter of rectangle = 2(l + w).",
    keyConcepts: ["perimeter with decimals", "decimal arithmetic"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Seema wants to buy items costing ₹35.75, ₹42.5, and ₹8.99. She has ₹80. Can she afford all three? How much short or extra?",
    answer: "Total cost = 35.75+42.50+8.99=87.24. She has ₹80. 80 < 87.24. She is SHORT by 87.24–80.00=₹7.24.",
    steps: [
      { stepNumber: 1, title: "Add costs", explanation: "35.75+42.50+8.99=87.24." },
      { stepNumber: 2, title: "Compare to ₹80", explanation: "80<87.24. Short by 7.24.", result: "Cannot afford; short by ₹7.24." },
    ],
    hint: "Add all costs; compare to ₹80; find the shortfall.",
    keyConcepts: ["decimal addition", "money", "comparison"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: ["Using the wrong operation or forgetting to check units after computing"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Pipe A is 5.75 m long. Pipe B is 0.8 m shorter than A. Pipe C is 1.25 m longer than B. What is the total length of all three pipes?",
    answer: "A = 5.75 m. B = 5.75–0.80 = 4.95 m. C = 4.95+1.25 = 6.20 m. Total = 5.75+4.95+6.20=16.90 m.",
    steps: [
      { stepNumber: 1, title: "Find B and C", explanation: "B=5.75–0.80=4.95; C=4.95+1.25=6.20." },
      { stepNumber: 2, title: "Total", explanation: "5.75+4.95+6.20=16.90 m.", result: "Total = 16.9 m." },
    ],
    hint: "Find each pipe length step by step, then add all three.",
    keyConcepts: ["multi-step decimal word problem"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: ["Misaligning decimal points when adding, causing incorrect place-value addition"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A tailor needs 2.5 m of cloth for a shirt and 1.75 m for trousers. He has a cloth roll of 5 m. How much cloth remains after making both?",
    answer: "Used = 2.5+1.75 = 4.25 m. Remaining = 5.00–4.25 = 0.75 m.",
    steps: [
      { stepNumber: 1, title: "Used", explanation: "2.50+1.75=4.25 m." },
      { stepNumber: 2, title: "Remaining", explanation: "5.00–4.25=0.75 m.", result: "0.75 m remaining." },
    ],
    hint: "Add the cloth used, then subtract from 5 m.",
    keyConcepts: ["decimal subtraction", "real-world word problem"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Fill in: (a) 6.5 + ________ = 10.  (b) 9 – ________ = 4.35.  (c) 1.4 + 2.6 = ________.",
    answer: "(a) 10–6.5=3.5. (b) 9–4.35=4.65. (c) 1.4+2.6=4.0=4.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "n=10–6.5=3.5." },
      { stepNumber: 2, title: "(b) and (c)", explanation: "(b) n=9–4.35=4.65. (c) 4.0=4.", result: "3.5; 4.65; 4." },
    ],
    hint: "Rearrange to isolate the unknown.",
    keyConcepts: ["missing value in decimal equation"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a 200 m relay, four runners ran 50 m each: times 6.5 s, 6.78 s, 7.02 s, 6.9 s. Total time? If world record is 27.11 s, how far off were they?",
    answer: "Total = 6.50+6.78+7.02+6.90 = 27.20 s. World record = 27.11 s. Difference = 27.20–27.11=0.09 s. They were 0.09 s slower than the world record.",
    steps: [
      { stepNumber: 1, title: "Sum of times", explanation: "6.50+6.78+7.02+6.90=27.20 s." },
      { stepNumber: 2, title: "Vs world record", explanation: "27.20–27.11=0.09 s slower.", result: "27.20 s; 0.09 s behind world record." },
    ],
    hint: "Add all times, then compare with 27.11 s.",
    keyConcepts: ["decimal addition", "decimal subtraction", "sports context"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: ["Misaligning decimal points when adding, causing incorrect place-value addition"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A bucket can hold 10 litres. It has 4.5 L of water. You add 3.75 L more. Is it full? If not, how much more water can it hold?",
    answer: "Current water = 4.5+3.75=8.25 L. Capacity = 10 L. Not full. Space remaining = 10.00–8.25=1.75 L.",
    steps: [
      { stepNumber: 1, title: "Total water", explanation: "4.50+3.75=8.25 L." },
      { stepNumber: 2, title: "Space remaining", explanation: "10.00–8.25=1.75 L.", result: "Not full; 1.75 L more can fit." },
    ],
    hint: "Add current + added water, then subtract from capacity.",
    keyConcepts: ["decimal addition and subtraction", "capacity problem"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-017",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "remember",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Aruna records her height every year: Age 10: 1.32 m; Age 11: 1.38 m; Age 12: 1.45 m. What is the total growth from age 10 to 12? What was the average annual growth?",
    answer: "Total growth = 1.45–1.32=0.13 m. Average annual growth = 0.13÷2=0.065 m per year. (Or in cm: 13 cm total; 6.5 cm per year.)",
    steps: [
      { stepNumber: 1, title: "Total growth", explanation: "1.45–1.32=0.13 m = 13 cm." },
      { stepNumber: 2, title: "Annual average", explanation: "0.13÷2=0.065 m = 6.5 cm per year.", result: "Total growth: 0.13 m. Average: 0.065 m/year." },
    ],
    hint: "Total growth = final – initial. Annual average = total ÷ number of years.",
    keyConcepts: ["decimal subtraction", "average", "real-world growth"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: ["Using the wrong operation or forgetting to check units after computing"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-018",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Fill in: (a) 0.75 + 0.25 = ________. (b) 1.5 – 0.5 = ________. (c) 0.9 + 0.1 = ________.",
    answer: "(a) 1.00 = 1. (b) 1.0 = 1. (c) 1.0 = 1. All three sums equal 1 whole.",
    steps: [
      { stepNumber: 1, title: "Add/subtract", explanation: "(a) 0.75+0.25=1. (b) 1.5–0.5=1. (c) 0.9+0.1=1." },
      { stepNumber: 2, title: "Note pattern", explanation: "Each pair of complementary decimals sums to 1.", result: "1; 1; 1." },
    ],
    hint: "Complementary decimals — pairs that add to 1.",
    keyConcepts: ["complementary decimals", "sum to 1"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-019",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The temperature at 6 AM was –2.5°C. By noon it rose by 8.3°C. By 6 PM it fell by 3.7°C. What was the temperature at 6 PM?",
    answer: "6 AM: –2.5°C. Noon: –2.5+8.3=5.8°C. 6 PM: 5.8–3.7=2.1°C.",
    steps: [
      { stepNumber: 1, title: "Noon temperature", explanation: "–2.5+8.3=5.8°C." },
      { stepNumber: 2, title: "6 PM temperature", explanation: "5.8–3.7=2.1°C.", result: "2.1°C at 6 PM." },
    ],
    hint: "Track temperature step by step: negative start + rise = positive; then subtract fall.",
    keyConcepts: ["decimal arithmetic with negative start", "temperature change"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: ["Computing –2.5+8.3 = 5.8 but then 5.8–3.7=2.1 — common error: saying 5.8–3.7=2.9"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-cmp-020",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "understand",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A school garden has a rectangular patch of length 8.4 m and width 3.6 m. A path of width 0.5 m runs around the outside. What is the total length of fencing needed to enclose the outer rectangle?",
    answer: "Outer rectangle: length = 8.4+2×0.5=8.4+1.0=9.4 m. Width = 3.6+2×0.5=3.6+1.0=4.6 m. Perimeter = 2(9.4+4.6)=2×14.0=28.0 m.",
    steps: [
      { stepNumber: 1, title: "Outer dimensions", explanation: "L=8.4+1.0=9.4; W=3.6+1.0=4.6." },
      { stepNumber: 2, title: "Perimeter", explanation: "2(9.4+4.6)=2×14=28 m.", result: "28 m of fencing." },
    ],
    hint: "Add path width to both sides of each dimension. Then compute perimeter.",
    keyConcepts: ["decimal arithmetic in geometry", "perimeter with path"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: ["Adding path only once per dimension instead of twice (both sides)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: 35.4 + 8.07 + 0.5.",
    answer: "Align: 35.40+8.07+0.50=43.97.",
    steps: [
      { stepNumber: 1, title: "Equalise places", explanation: "35.40; 8.07; 0.50." },
      { stepNumber: 2, title: "Add", explanation: "Hundredths: 0+7+0=7. Tenths: 4+0+5=9. Ones: 5+8+0=13(carry1). Tens: 3+1=4. → 43.97.", result: "43.97." },
    ],
    hint: "Write all with 2 decimal places, then add column by column.",
    keyConcepts: ["decimal addition"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Subtract 7.685 from 15.4.",
    answer: "15.400 – 7.685 = 7.715.",
    steps: [
      { stepNumber: 1, title: "Write 15.4 as 15.400", explanation: "Align: 15.400 – 7.685." },
      { stepNumber: 2, title: "Subtract with borrowing", explanation: "Thousandths: 0–5→borrow: 10–5=5. Hundredths: 0–1(b)–8→borrow: 10–9=1. Tenths: 4–1(b)–6→borrow: 14–7=7. Ones: 5–1(b)–7→borrow: 15–8=7? Wait: let me recalculate: 15.400–7.685. Thousandths: 0–5: borrow→10–5=5. Hundredths: 0–1(borrow)=–1–8: borrow→10–9=1. Tenths: 4–1(borrow)=3–6: borrow→13–6=7. Ones: 5–1(borrow)=4–7: borrow→14–7=7. Tens: 1–1(borrow)=0. Result: 7.715.", result: "7.715." },
    ],
    hint: "Write 15.4 as 15.400, then carefully subtract with borrowing.",
    keyConcepts: ["decimal subtraction", "borrowing"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: ["Errors in carrying through multiple borrowings"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A piece of ribbon is 12 m long. Three pieces of lengths 2.4 m, 3.75 m, and 1.8 m are cut. How much ribbon remains?",
    answer: "Cut = 2.40+3.75+1.80=7.95 m. Remaining = 12.00–7.95=4.05 m.",
    steps: [
      { stepNumber: 1, title: "Sum of cuts", explanation: "2.40+3.75+1.80=7.95 m." },
      { stepNumber: 2, title: "Remaining", explanation: "12.00–7.95=4.05 m.", result: "4.05 m." },
    ],
    hint: "Add lengths cut, then subtract from 12 m.",
    keyConcepts: ["decimal word problem", "subtraction"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Priya has ₹156.75. She spends ₹89.45. How much does she have left?",
    answer: "156.75 – 89.45 = 67.30. She has ₹67.30 left.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "156.75 – 89.45." },
      { stepNumber: 2, title: "Subtract", explanation: "Hundredths: 5–5=0. Tenths: 7–4=3. Ones: 6–9→borrow: 16–9=7; Tens: 5–1–8→borrow: 15–9=6; Hundreds 1–1=0. → 67.30.", result: "₹67.30." },
    ],
    hint: "Align and subtract carefully, borrowing when needed.",
    keyConcepts: ["money subtraction", "decimal"],
    conceptsCovered: ["mth:6:ch08:decimal-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 4,
    question: "The mass of a bag of wheat is 25.5 kg. A bag of rice is 3.75 kg heavier. What is the mass of the rice bag? What is the combined mass?",
    answer: "Rice = 25.5+3.75=29.25 kg. Combined = 25.5+29.25=54.75 kg.",
    steps: [
      { stepNumber: 1, title: "Rice bag mass", explanation: "25.50+3.75=29.25 kg." },
      { stepNumber: 2, title: "Combined", explanation: "25.50+29.25=54.75 kg.", result: "Rice: 29.25 kg. Combined: 54.75 kg." },
    ],
    hint: "Add 3.75 to find rice mass; then add both for combined.",
    keyConcepts: ["decimal addition", "word problem"],
    conceptsCovered: ["mth:6:ch08:decimal-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch08-pyq-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Decimals",
    topicId: "t3", topicName: "Addition and Subtraction of Decimals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "remember",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find n: (a) n + 3.7 = 9.05  (b) 5.6 – n = 1.75.",
    answer: "(a) n = 9.05–3.70 = 5.35. (b) n = 5.60–1.75 = 3.85.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "n = 9.05–3.70=5.35." },
      { stepNumber: 2, title: "(b)", explanation: "n = 5.60–1.75=3.85.", result: "(a) 5.35. (b) 3.85." },
    ],
    hint: "Rearrange each equation to find n.",
    keyConcepts: ["decimal equations", "solving for unknown"],
    conceptsCovered: ["mth:6:ch08:decimal-word-problem"],
    prerequisites: [],
    commonErrors: ["Using the wrong operation or forgetting to check units after computing"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

];
