/**
 * Question Bank — Mathematics, Class 6, Chapter 9: Data Handling
 *
 * 75 curated questions — types: concept(18), ncert(22), competency(15), case-study(10), previous-year(10)
 * Board: Both | Category: minor | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Collecting and Organising Data  — 38 q
 *   t2 Pictographs and Bar Graphs      — 37 q
 *
 * Key concept nodes:
 *   mth:6:ch09:tally-marks           — recording data: groups of 5; reading tally marks
 *   mth:6:ch09:frequency-table       — organising tally marks into a frequency table
 *   mth:6:ch09:raw-data-organisation — why organised data is easier to analyse
 *   mth:6:ch09:data-range            — range = max – min value in a data set
 *   mth:6:ch09:pictograph-reading    — each picture represents a fixed quantity (scale/key)
 *   mth:6:ch09:pictograph-scale      — scale/key determines how many units one symbol represents
 *   mth:6:ch09:bar-graph-axes        — horizontal and vertical axes; labelling and scale
 *   mth:6:ch09:bar-graph-construction — drawing bars with uniform width and gaps
 *   mth:6:ch09:bar-graph-interpretation — reading values, comparing bars, drawing conclusions
 *
 * v1 2026-07-06
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH09_DATA_HANDLING: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Collecting and Organising Data
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-6-ch09-con-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is data? Give two examples of data collected in daily life.",
    answer: "Data is a collection of facts, numbers, or information collected for a purpose. Examples: (1) Marks scored by students in a test (a collection of numbers — marks). (2) Favourite colours of students in a class (a collection of responses — colour names). Raw data is data in its original, unprocessed form.",
    steps: [
      { stepNumber: 1, title: "Define data", explanation: "Data = collection of facts or information gathered for analysis." },
      { stepNumber: 2, title: "Examples", explanation: "Marks in a test; favourite colours; attendance records.", result: "Two examples given." },
    ],
    hint: "Data can be numbers or non-numerical information collected systematically.",
    keyConcepts: ["data", "raw data", "examples"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What are tally marks? How do you represent the number 17 using tally marks?",
    answer: "Tally marks are a method of counting by making a mark for each item counted. Groups of 5 are formed: four vertical marks and one diagonal strike. 17 = three complete groups of 5 (||||| ||||| |||||) plus two extra marks (||). So: ||||| ||||| ||||| ||. This makes it easy to count in groups of 5.",
    steps: [
      { stepNumber: 1, title: "Rule for tally marks", explanation: "Mark 4 vertical lines, then cross with 1 diagonal = group of 5." },
      { stepNumber: 2, title: "17 = 3×5 + 2", explanation: "3 complete groups + 2 singles: ||||| ||||| ||||| ||", result: "17 in tally marks: ||||| ||||| ||||| ||" },
    ],
    hint: "Groups of 5 make tally marks easy to count.",
    keyConcepts: ["tally marks", "groups of 5", "counting"],
    conceptsCovered: ["mth:6:ch09:tally-marks"],
    prerequisites: [],
    commonErrors: ["Making groups of 4 or 6 instead of 5"],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "The marks of 15 students in a test are: 5, 7, 5, 8, 7, 5, 9, 7, 8, 5, 7, 9, 8, 7, 5. Organise this data into a frequency table using tally marks.",
    answer: "Frequency table:\nMarks | Tally | Frequency\n5     | ||||| | 5\n7     | ||||| | 5\n8     | |||    | 3\n9     | ||     | 2\nTotal: 15 ✓",
    steps: [
      { stepNumber: 1, title: "Count each mark with tally", explanation: "5 appears: 5 times. 7 appears: 5 times. 8 appears: 3 times. 9 appears: 2 times." },
      { stepNumber: 2, title: "Build table and verify total", explanation: "5+5+3+2=15 ✓.", result: "Frequency table as shown." },
    ],
    hint: "Count each distinct value and record using tally marks.",
    keyConcepts: ["frequency table", "tally marks", "data organisation"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: ["mth:6:ch09:tally-marks"],
    commonErrors: ["Missing a count — always verify total = number of data points"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find the range of this data set: 45, 23, 67, 12, 89, 34, 56, 78.",
    answer: "Range = Maximum value – Minimum value. Maximum = 89. Minimum = 12. Range = 89 – 12 = 77. The range tells us how spread out the data is.",
    steps: [
      { stepNumber: 1, title: "Find max and min", explanation: "Max = 89, Min = 12." },
      { stepNumber: 2, title: "Compute range", explanation: "Range = 89–12=77.", result: "Range = 77." },
    ],
    hint: "Range = largest value – smallest value.",
    keyConcepts: ["range", "maximum", "minimum", "spread"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: ["Computing max + min instead of max – min"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: Organised data is always easier to analyse than raw data. Justify with an example.",
    answer: "True. Raw data (unorganised) is a random list and hard to interpret. Example: Raw: 5, 2, 7, 2, 5, 2, 3, 5, 7, 7. Difficult to spot patterns. Organised in a frequency table: 2→3 times, 3→1, 5→3, 7→3. Now you can instantly see the most common values, total count, range, etc. Organisation makes data easier to read, compare, and draw conclusions from.",
    steps: [
      { stepNumber: 1, title: "Compare raw vs organised", explanation: "Raw = scattered; organised = structured." },
      { stepNumber: 2, title: "Example shows advantage", explanation: "Frequency table makes analysis instant.", result: "TRUE." },
    ],
    hint: "Think about how much harder it is to answer 'what is most common?' with raw data vs a frequency table.",
    keyConcepts: ["raw vs organised data", "data analysis"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "20 students chose their favourite subject: Maths(M), Science(S), English(E). Results: M,S,M,E,M,S,S,M,E,S,M,E,E,S,M,S,M,E,S,M. Make a frequency table and find which subject is most popular.",
    answer: "Count: M appears in positions 1,3,5,8,11,15,17,19... let me count: M,S,M,E,M,S,S,M,E,S,M,E,E,S,M,S,M,E,S,M. M:1,3,5,8,11,15,17,20 = 8 times. S:2,6,7,10,14,16,19 = 7 times. E:4,9,12,13,18 = 5 times. Total: 8+7+5=20 ✓. Frequency table: Maths=8, Science=7, English=5. Most popular = Maths (8 students).",
    steps: [
      { stepNumber: 1, title: "Count each subject", explanation: "M: 8 times. S: 7 times. E: 5 times." },
      { stepNumber: 2, title: "Table and conclusion", explanation: "Total=20 ✓. Most popular = Maths.", result: "Maths is most popular (8 students)." },
    ],
    hint: "Go through the list systematically, tallying each letter.",
    keyConcepts: ["frequency table", "mode", "most popular"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: ["mth:6:ch09:tally-marks"],
    commonErrors: ["Miscounting by not tracking which items have been counted — use tally marks"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is the difference between data collection and data organisation? Give one method for each.",
    answer: "Data collection: the process of gathering information. Method: survey/questionnaire (asking students their favourite colour). Data organisation: arranging collected data into a useful structure. Method: frequency table (counting how many students chose each colour). Organisation transforms raw data into a form that can be analysed.",
    steps: [
      { stepNumber: 1, title: "Data collection", explanation: "Gathering information through surveys, experiments, observation." },
      { stepNumber: 2, title: "Data organisation", explanation: "Structuring collected data using tally marks, frequency tables, etc.", result: "Collection: survey. Organisation: frequency table." },
    ],
    hint: "Collection = gathering; organisation = arranging what you've gathered.",
    keyConcepts: ["data collection vs organisation", "survey", "frequency table"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "The number of goals scored by a football team in 10 matches: 0, 2, 1, 3, 0, 2, 4, 1, 2, 3. Find: (a) the frequency of scoring 2 goals, (b) the range.",
    answer: "(a) Goals = 2 appear in: 2nd, 6th, 9th match = 3 times. Frequency of 2 = 3. (b) Range = max – min = 4 – 0 = 4.",
    steps: [
      { stepNumber: 1, title: "Count goals = 2", explanation: "Position 2,6,9: frequency = 3." },
      { stepNumber: 2, title: "Range", explanation: "Max=4, Min=0. Range=4.", result: "(a)3, (b)4." },
    ],
    hint: "Count each occurrence for frequency; subtract min from max for range.",
    keyConcepts: ["frequency", "range", "sports data"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Priya asks 30 students about their mode of transport to school: walk(W), bus(B), cycle(C), car(A). She got: B,W,W,C,B,A,W,B,C,W,A,B,W,C,B,W,B,A,W,B,C,B,W,A,B,W,C,B,W,B. Make a frequency table and determine the most common mode.",
    answer: "Count: W: positions 2,3,7,10,13,16,19,22,25,29 = 10. B: 1,5,8,12,15,17,20,22... let me recount: B,W,W,C,B,A,W,B,C,W,A,B,W,C,B,W,B,A,W,B,C,B,W,A,B,W,C,B,W,B. B: 1,5,8,12,15,17,20,22,25,28,30=11. W: 2,3,7,10,13,16,19,23,26,29=10. C: 4,9,14,21,27=5. A: 6,11,18,24=4. Total: 11+10+5+4=30 ✓. Most common: Bus (11 students).",
    steps: [
      { stepNumber: 1, title: "Tally each mode", explanation: "B=11, W=10, C=5, A=4." },
      { stepNumber: 2, title: "Table and conclusion", explanation: "Bus most common (11).", result: "Bus (B) with frequency 11." },
    ],
    hint: "Go letter by letter and tally. Verify total = 30.",
    keyConcepts: ["frequency table", "survey data", "most common"],
    conceptsCovered: ["mth:6:ch09:tally-marks"],
    prerequisites: [],
    commonErrors: ["Losing count in large data sets — use structured tally marks"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A frequency table shows: Number 1 → frequency 4; Number 2 → frequency 7; Number 3 → frequency 3; Number 4 → frequency 6. What is the total number of observations? Which number appeared most often? What is the range?",
    answer: "Total observations = 4+7+3+6 = 20. Most frequent = number 2 (frequency 7). Range = maximum value – minimum value = 4–1=3.",
    steps: [
      { stepNumber: 1, title: "Sum frequencies", explanation: "4+7+3+6=20." },
      { stepNumber: 2, title: "Most frequent and range", explanation: "Max freq=7 (number 2). Range=4–1=3.", result: "Total=20; most common=2; range=3." },
    ],
    hint: "Range uses the data VALUES (1 to 4), not the frequencies.",
    keyConcepts: ["frequency table reading", "range", "most frequent value"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: ["Using the maximum frequency (7) instead of the maximum data value (4) to compute range"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What does the tally mark ||||| ||||| ||| represent?",
    answer: "Two complete groups of 5 (||||| |||||) = 10 plus 3 singles (|||) = 13. The tally mark ||||| ||||| ||| represents 13.",
    steps: [
      { stepNumber: 1, title: "Count complete groups", explanation: "||||| ||||| = 2 groups × 5 = 10." },
      { stepNumber: 2, title: "Add singles", explanation: "+3 = 13.", result: "13." },
    ],
    hint: "Each group of 5 counts as 5. Count complete groups first, then add singles.",
    keyConcepts: ["reading tally marks"],
    conceptsCovered: ["mth:6:ch09:tally-marks"],
    prerequisites: [],
    commonErrors: ["Counting 2 groups as 2 instead of 10"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Represent in tally marks: (a) 8  (b) 12  (c) 21.",
    answer: "(a) 8 = ||||| ||| (one group of 5 + 3). (b) 12 = ||||| ||||| || (two groups of 5 + 2). (c) 21 = ||||| ||||| ||||| ||||| | (four groups of 5 + 1).",
    steps: [
      { stepNumber: 1, title: "(a) and (b)", explanation: "(a) 8=5+3. (b) 12=5+5+2." },
      { stepNumber: 2, title: "(c)", explanation: "21=5+5+5+5+1=20+1.", result: "See tally marks above." },
    ],
    hint: "Divide by 5 to find number of complete groups, remainder as singles.",
    keyConcepts: ["writing tally marks"],
    conceptsCovered: ["mth:6:ch09:tally-marks"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "The ages (in years) of 20 people are: 12, 15, 18, 12, 20, 15, 12, 18, 15, 20, 12, 15, 18, 12, 20, 15, 12, 18, 15, 12. Make a frequency table. How many people are exactly 15 years old?",
    answer: "Count: 12: 1,3,7,11,14,17,20... positions: 1,3,7,11,14,17,20= 7 times. 15: 2,6,9,12,16,19... = 2,6,9,12,16,19=6 times? Let me recount: 12,15,18,12,20,15,12,18,15,20,12,15,18,12,20,15,12,18,15,12. 12: pos 1,4,7,11,14,17,20=7. 15: pos 2,6,9,12,16,19=6. 18: pos 3,8,13,18=4. 20: pos 5,10,15=3. Total: 7+6+4+3=20 ✓. People aged 15 = 6.",
    steps: [
      { stepNumber: 1, title: "Count each age", explanation: "12→7; 15→6; 18→4; 20→3." },
      { stepNumber: 2, title: "Answer question", explanation: "People aged 15 = 6.", result: "6 people are aged 15." },
    ],
    hint: "Use tally marks: go through the list and mark each value.",
    keyConcepts: ["frequency table from raw data"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) In a frequency table, the total of all frequencies equals ________ data points. (b) Range = ________ – ________. (c) Tally marks are made in groups of ________.",
    answer: "(a) total. (b) maximum value – minimum value. (c) 5.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "Sum of all frequencies = total observations." },
      { stepNumber: 2, title: "(b) and (c)", explanation: "(b) Range=max–min. (c) Groups of 5.", result: "total; max – min; 5." },
    ],
    hint: "Basic definitions in data handling.",
    keyConcepts: ["frequency total", "range definition", "tally groups"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Data: 6, 3, 7, 4, 6, 8, 3, 6, 4, 7, 3, 6, 8, 4, 6. Make a frequency table. Find the range.",
    answer: "3→3, 4→3, 6→5, 7→2, 8→2. Total=15 ✓. Range=8–3=5.",
    steps: [
      { stepNumber: 1, title: "Count each value", explanation: "3:pos1,7,11=3; 4:pos4,9,14=3; 6:pos1,5,8,12,15=5; 7:pos3,10=2; 8:pos6,13=2." },
      { stepNumber: 2, title: "Range", explanation: "8–3=5.", result: "Range=5; most common value=6." },
    ],
    hint: "Count carefully. Range = largest – smallest value.",
    keyConcepts: ["frequency table", "range"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A teacher records daily attendance for 10 days: 38, 40, 35, 40, 42, 38, 40, 35, 42, 40. Make a frequency table. On how many days was attendance highest?",
    answer: "35→2, 38→2, 40→4, 42→2. Total=10 ✓. Highest attendance=42. Attendance was 42 on 2 days.",
    steps: [
      { stepNumber: 1, title: "Count", explanation: "35:days3,8=2; 38:days1,6=2; 40:days2,4,7,10=4; 42:days5,9=2." },
      { stepNumber: 2, title: "Highest attendance", explanation: "42 is max; frequency=2.", result: "Highest attendance (42) on 2 days." },
    ],
    hint: "The question asks about maximum attendance value, not maximum frequency.",
    keyConcepts: ["attendance data", "frequency table", "maximum"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Blood groups of 20 students: A, B, O, AB, A, O, B, A, O, A, B, O, A, AB, O, A, B, O, A, O. Make a frequency table and find what percentage of students have blood group O.",
    answer: "A: 1,5,8,10,13,16,19=7. B: 2,7,11,17=4. O: 3,6,9,12,15,18,20=7. AB: 4,14=2. Total=7+4+7+2=20 ✓. Blood group O = 7 students. Percentage = (7/20)×100=35%.",
    steps: [
      { stepNumber: 1, title: "Frequency table", explanation: "A=7, B=4, O=7, AB=2." },
      { stepNumber: 2, title: "Percentage with O", explanation: "(7/20)×100=35%.", result: "35% have blood group O." },
    ],
    hint: "Count each blood group type, then compute percentage = (count/total)×100.",
    keyConcepts: ["frequency table", "percentage from frequency"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Data about the favourite colour of students in a class is an example of numerical data.",
    answer: "False. Favourite colour is categorical (non-numerical) data — it consists of categories (red, blue, green, etc.), not numbers. Numerical data would be something like 'scores in a test' or 'heights of students.' Categorical data can be organised using tally marks and frequency tables, but its 'range' is not meaningful.",
    steps: [
      { stepNumber: 1, title: "Identify data type", explanation: "Colours are categories (names), not numbers." },
      { stepNumber: 2, title: "Conclusion", explanation: "Categorical, not numerical.", result: "FALSE." },
    ],
    hint: "Is colour a number? Can you add or subtract colours?",
    keyConcepts: ["numerical vs categorical data", "types of data"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "In a class, the number of students absent each day for a week: Mon 3, Tue 5, Wed 2, Thu 5, Fri 4. Find range and the day with highest absence.",
    answer: "Data: 3, 5, 2, 5, 4. Range = 5–2=3. Highest absence = 5 (Tuesday and Thursday, both equal).",
    steps: [
      { stepNumber: 1, title: "Range", explanation: "Max=5, Min=2. Range=3." },
      { stepNumber: 2, title: "Most absent", explanation: "5 appears on Tue and Thu.", result: "Range=3. Most absent: Tuesday and Thursday (5 each)." },
    ],
    hint: "Range = max – min. Two days can tie for highest absence.",
    keyConcepts: ["range", "maximum frequency", "attendance data"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Shoe sizes of 18 students: 4,5,5,6,4,5,6,7,5,4,6,5,7,6,5,4,6,5. Make a frequency table. If one student is chosen at random, how many shoe sizes are equally likely to be the most common?",
    answer: "4:4, 5:7, 6:5, 7:2. Total=18 ✓. Most common = size 5 (frequency 7). Only one size has the highest frequency, so only size 5. No other size has frequency 7. Answer: Only 1 shoe size (size 5) is most common.",
    steps: [
      { stepNumber: 1, title: "Frequency table", explanation: "4→4, 5→7, 6→5, 7→2." },
      { stepNumber: 2, title: "Most common", explanation: "Highest frequency=7 (size 5). No ties.", result: "Only size 5; just 1 most common size." },
    ],
    hint: "Check if any two sizes share the maximum frequency.",
    keyConcepts: ["frequency table", "mode", "unique maximum"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A frequency table shows: Colour Red→8, Blue→12, Green→5, Yellow→10. How many students were surveyed? Which colour is most popular?",
    answer: "Total = 8+12+5+10=35 students surveyed. Most popular = Blue (frequency 12).",
    steps: [
      { stepNumber: 1, title: "Sum frequencies", explanation: "8+12+5+10=35." },
      { stepNumber: 2, title: "Most popular", explanation: "Max frequency=12 (Blue).", result: "35 students; Blue is most popular." },
    ],
    hint: "Add all frequencies for total. Highest frequency = most popular.",
    keyConcepts: ["reading frequency table"],
    conceptsCovered: ["mth:6:ch09:tally-marks"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A school nurse records illness types for students visiting the clinic in one week: fever(F), cold(C), injury(I), headache(H). Data: F,C,F,I,H,F,C,F,H,C,F,I,F,C,H,F,C,F,I,C. (a) Make a frequency table. (b) Which illness is most common? (c) What fraction of visits were for fever?",
    answer: "Count: F:1,3,6,8,11,13,16,18=8. C:2,7,10,14,17,20=6. I:4,12,19=3. H:5,9,15=3. Total=8+6+3+3=20 ✓. (a) Table: F=8,C=6,I=3,H=3. (b) Most common=Fever (8). (c) Fraction for fever=8/20=2/5.",
    steps: [
      { stepNumber: 1, title: "Tally and table", explanation: "F=8, C=6, I=3, H=3." },
      { stepNumber: 2, title: "Fraction for fever", explanation: "8/20=2/5.", result: "(b) Fever most common. (c) 2/5 of visits." },
    ],
    hint: "Tally carefully; verify total = 20.",
    keyConcepts: ["frequency table", "most common", "fraction from data"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Marks in a test (out of 10) for 25 students: 7,8,9,7,6,8,10,7,9,6,8,7,9,10,7,6,8,9,7,8,6,9,7,8,10. (a) Make frequency table. (b) How many scored more than 8? (c) Range?",
    answer: "Count: 6→4, 7→8, 8→7, 9→5, 10→3. Wait: let me recount: 7,8,9,7,6,8,10,7,9,6,8,7,9,10,7,6,8,9,7,8,6,9,7,8,10. 6: pos5,10,16,21=4. 7: pos1,4,8,12,15,19,23=7 (actually: positions 1,4,8,12,15,19,23=7). 8: pos2,6,11,17,20,24=6. 9: pos3,9,13,18,22=5. 10: pos7,14,25=3. Total=4+7+6+5+3=25 ✓. (b) Scored >8 (i.e., 9 or 10): 5+3=8 students. (c) Range=10–6=4.",
    steps: [
      { stepNumber: 1, title: "Frequency table", explanation: "6→4, 7→7, 8→6, 9→5, 10→3. Total=25." },
      { stepNumber: 2, title: "(b) and (c)", explanation: "Score>8: 9+10=5+3=8. Range=4.", result: "(b) 8 students scored > 8. (c) Range=4." },
    ],
    hint: "For (b): count frequencies of 9 and 10 only (strictly greater than 8).",
    keyConcepts: ["frequency table", "conditional count", "range"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: ["Including marks = 8 in the count for 'more than 8' — strictly greater means exclude 8"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "The frequency table shows: Hours of TV | Frequency: 0→2, 1→5, 2→8, 3→6, 4→4. How many students were surveyed? What fraction watched 2 hours?",
    answer: "Total = 2+5+8+6+4=25 students. Fraction watching 2 hours = 8/25.",
    steps: [
      { stepNumber: 1, title: "Total students", explanation: "2+5+8+6+4=25." },
      { stepNumber: 2, title: "Fraction for 2 hours", explanation: "8/25.", result: "25 students; 8/25 watched 2 hours." },
    ],
    hint: "Total = sum of all frequencies.",
    keyConcepts: ["reading frequency table", "fraction from frequency"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A fruit seller records daily sales: Monday 120 kg, Tuesday 95 kg, Wednesday 140 kg, Thursday 80 kg, Friday 115 kg. Find the range and the day with lowest sales.",
    answer: "Range = 140–80=60 kg. Lowest sales = Thursday (80 kg).",
    steps: [
      { stepNumber: 1, title: "Find max and min", explanation: "Max=140 (Wed), Min=80 (Thu)." },
      { stepNumber: 2, title: "Range and conclusion", explanation: "Range=60. Lowest=Thursday.", result: "Range=60 kg; lowest=Thursday." },
    ],
    hint: "Range = highest – lowest sales.",
    keyConcepts: ["range in context", "maximum minimum"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a survey of 40 families, the number of children per family was recorded. Frequency table: 0 children→5 families, 1 child→12, 2 children→15, 3 children→6, 4 children→2. Verify the total. What is the range? What fraction of families have exactly 2 children?",
    answer: "Total = 5+12+15+6+2=40 ✓. Range = 4–0=4. Fraction with 2 children = 15/40=3/8.",
    steps: [
      { stepNumber: 1, title: "Verify total", explanation: "5+12+15+6+2=40 ✓." },
      { stepNumber: 2, title: "Range and fraction", explanation: "Range=4–0=4. Fraction=15/40=3/8.", result: "Range=4; fraction with 2 children=3/8." },
    ],
    hint: "Range uses VALUES (0 to 4), not frequencies.",
    keyConcepts: ["frequency table verification", "range", "fraction from data"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is the range of: 10, 25, 3, 47, 8, 32?",
    answer: "Max=47, Min=3. Range=47–3=44.",
    steps: [
      { stepNumber: 1, title: "Identify max and min", explanation: "Max=47, Min=3." },
      { stepNumber: 2, title: "Range", explanation: "47–3=44.", result: "44." },
    ],
    hint: "Identify the largest and smallest values.",
    keyConcepts: ["range calculation"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) Tally ||||| = ________ . (b) ||||| ||||| ||||| || = ________. (c) The range of {5, 5, 5} = ________.",
    answer: "(a) 5. (b) 17. (c) 0 (max=5, min=5, range=0).",
    steps: [
      { stepNumber: 1, title: "(a) and (b)", explanation: "(a) 5. (b) 3 groups + 2 = 17." },
      { stepNumber: 2, title: "(c)", explanation: "All same value: max=min=5, range=0.", result: "5; 17; 0." },
    ],
    hint: "For (c): if all values are same, range = 0.",
    keyConcepts: ["reading tally", "range = 0 for identical data"],
    conceptsCovered: ["mth:6:ch09:tally-marks"],
    prerequisites: [],
    commonErrors: ["Saying range of {5,5,5} = 5 instead of 0"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Votes received by 4 candidates: A=125, B=340, C=210, D=175. Make a simple frequency/summary table. Who won and what is the range of votes?",
    answer: "Table: A→125, B→340, C→210, D→175. Winner = Candidate B (340 votes). Range = 340–125=215.",
    steps: [
      { stepNumber: 1, title: "Table", explanation: "A=125, B=340, C=210, D=175." },
      { stepNumber: 2, title: "Winner and range", explanation: "Max=340 (B). Range=340–125=215.", result: "B wins; range=215." },
    ],
    hint: "Winner = highest votes. Range = max – min votes.",
    keyConcepts: ["data table", "maximum", "range"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "12 students chose between cricket(C) and football(F): C,F,C,C,F,C,F,C,F,C,C,F. Make a frequency table. What fraction chose football?",
    answer: "C: 1,3,4,6,8,10,11=7. F: 2,5,7,9,12=5. Total=12 ✓. Fraction for football=5/12.",
    steps: [
      { stepNumber: 1, title: "Count", explanation: "C=7, F=5. Total=12." },
      { stepNumber: 2, title: "Fraction", explanation: "F: 5/12.", result: "Cricket=7, Football=5. Fraction for football=5/12." },
    ],
    hint: "Count each letter; fraction = count/total.",
    keyConcepts: ["frequency table", "fraction from data"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Heights (cm) of 10 students: 130, 145, 128, 150, 145, 132, 150, 128, 145, 138. Make a frequency table. Which height is most common? What is the range?",
    answer: "128→2, 130→1, 132→1, 138→1, 145→3, 150→2. Total=10 ✓. Most common=145 cm (frequency 3). Range=150–128=22 cm.",
    steps: [
      { stepNumber: 1, title: "Frequency table", explanation: "128→2,130→1,132→1,138→1,145→3,150→2." },
      { stepNumber: 2, title: "Most common and range", explanation: "145 most common. Range=22.", result: "145 cm most common; range=22 cm." },
    ],
    hint: "Most common = highest frequency value.",
    keyConcepts: ["frequency", "mode", "range"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Pictographs and Bar Graphs
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-6-ch09-con-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is a pictograph? What is its key/scale? Why is the key important?",
    answer: "A pictograph represents data using pictures or symbols where each symbol represents a fixed quantity (the scale or key). Example: ☆ = 10 students. The key tells you how many units each symbol represents. Without the key, you cannot interpret the pictograph. If the key says 1 symbol = 5 mangoes and there are 4 symbols for Monday, then Monday's mangoes = 4×5 = 20.",
    steps: [
      { stepNumber: 1, title: "Define pictograph", explanation: "Visual representation using pictures; each picture = a set number of units." },
      { stepNumber: 2, title: "Why key is important", explanation: "Without key you can't determine the actual values.", result: "Definition and key explanation." },
    ],
    hint: "The key is like a translation legend — it tells you what each picture means.",
    keyConcepts: ["pictograph", "key/scale", "symbol representation"],
    conceptsCovered: ["mth:6:ch09:pictograph-reading"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A pictograph shows books read in a week. Key: 1 book symbol = 5 books. Monday: 3 symbols; Tuesday: 2 symbols; Wednesday: 4 symbols; Thursday: 1 symbol; Friday: 2 symbols. How many books were read on Wednesday? What is the total for the week?",
    answer: "Wednesday: 4 symbols × 5 = 20 books. Total: (3+2+4+1+2)×5 = 12×5 = 60 books.",
    steps: [
      { stepNumber: 1, title: "Wednesday", explanation: "4×5=20 books." },
      { stepNumber: 2, title: "Total", explanation: "(3+2+4+1+2)=12 symbols; 12×5=60 books.", result: "Wednesday=20; total=60." },
    ],
    hint: "Multiply number of symbols by the scale value.",
    keyConcepts: ["pictograph reading", "scale multiplication"],
    conceptsCovered: ["mth:6:ch09:pictograph-scale"],
    prerequisites: ["mth:6:ch09:pictograph-reading"],
    commonErrors: ["Adding symbols and forgetting to multiply by scale: 12 instead of 60"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "In a pictograph with key 1 symbol = 4 cars, how many symbols would you draw for: (a) 24 cars (b) 10 cars?",
    answer: "(a) 24/4 = 6 symbols. (b) 10/4 = 2.5 symbols. Draw 2 full symbols and 1 half symbol (half a picture).",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "24÷4=6 symbols." },
      { stepNumber: 2, title: "(b)", explanation: "10÷4=2.5: 2 full + ½ symbol.", result: "(a)6 symbols. (b)2½ symbols." },
    ],
    hint: "Number of symbols = data value ÷ scale. Use half symbols for non-integer results.",
    keyConcepts: ["pictograph construction", "half symbols"],
    conceptsCovered: ["mth:6:ch09:pictograph-scale"],
    prerequisites: [],
    commonErrors: ["Rounding 2.5 down to 2 and ignoring the half"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "What is a bar graph? Name its four essential components.",
    answer: "A bar graph displays data using rectangular bars whose heights (or lengths) are proportional to the values they represent. Four essential components: (1) Title — describes what the graph shows. (2) Axes — horizontal (x-axis, categories) and vertical (y-axis, values). (3) Scale — markings on the y-axis showing value increments. (4) Bars — rectangular bars of uniform width with gaps between them.",
    steps: [
      { stepNumber: 1, title: "Define bar graph", explanation: "Rectangles of proportional height represent data." },
      { stepNumber: 2, title: "Four components", explanation: "Title, axes (x and y), scale, bars.", result: "Definition and four components." },
    ],
    hint: "Think about what you see when you look at a bar graph — label each part.",
    keyConcepts: ["bar graph", "components", "axes", "scale"],
    conceptsCovered: ["mth:6:ch09:bar-graph-axes"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A bar graph has data: Jan=50, Feb=30, Mar=70, Apr=60. If the y-axis goes from 0 to 80 with scale 10, which scale marking would be appropriate? What would the height of the March bar be?",
    answer: "Scale: 0 to 80 with increments of 10 → markings at 0, 10, 20, 30, 40, 50, 60, 70, 80. This is appropriate because the maximum value is 70 (less than 80). March value = 70 → the March bar reaches the marking at 70 on the y-axis. The scale is appropriate: minimum data = 30 (above 0), maximum = 70 (at 70).",
    steps: [
      { stepNumber: 1, title: "Verify scale", explanation: "Max data=70. Scale to 80 accommodates all values with headroom." },
      { stepNumber: 2, title: "March bar height", explanation: "March=70 → bar height = 70 units on scale.", result: "Scale 0–80 by 10s is appropriate. March bar at 70." },
    ],
    hint: "Scale should exceed max value. March = 70 lands on the 70 line.",
    keyConcepts: ["bar graph scale", "reading bar height"],
    conceptsCovered: ["mth:6:ch09:bar-graph-construction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A bar graph shows rainfall (mm): Jan=20, Feb=15, Mar=30, Apr=25, May=40. (a) In which month was rainfall highest? (b) What is the difference between highest and lowest? (c) In how many months was rainfall above 20 mm?",
    answer: "(a) May has highest rainfall (40 mm). (b) 40–15=25 mm. (c) Months above 20: March(30), April(25), May(40) = 3 months.",
    steps: [
      { stepNumber: 1, title: "(a) and (b)", explanation: "Max=May(40). Min=Feb(15). Diff=25." },
      { stepNumber: 2, title: "(c)", explanation: "30>20, 25>20, 40>20. Count=3.", result: "(a)May. (b)25 mm. (c)3 months." },
    ],
    hint: "For (c): strictly above 20 means exclude January (=20).",
    keyConcepts: ["bar graph interpretation", "comparison", "conditional counting"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: ["Including January (=20) in the 'above 20' count — strictly above means > 20, not ≥ 20"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-017",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: In a bar graph, the bars should all have different widths to show the difference in values.",
    answer: "False. In a bar graph, all bars must have the SAME width. The HEIGHT (or length) of the bar represents the value — not the width. Bars of different widths would be misleading. Uniform width is a standard convention to ensure the visual comparison is fair and based only on height.",
    steps: [
      { stepNumber: 1, title: "Bar graph convention", explanation: "Bars must be uniform width. Height = value." },
      { stepNumber: 2, title: "Why uniform width matters", explanation: "Different widths make visual comparison misleading.", result: "FALSE — all bars must have equal width." },
    ],
    hint: "What dimension of the bar represents the data value?",
    keyConcepts: ["bar graph convention", "uniform bar width"],
    conceptsCovered: ["mth:6:ch09:bar-graph-construction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-con-018",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A bar graph shows scores: Maths=80, Science=65, English=75, Hindi=70. What scale (y-axis) would you choose? Explain your choice.",
    answer: "The highest value is 80 and lowest is 65. A scale from 0 to 100 with markings every 10 would be appropriate (0, 10, 20, …, 100). This scale: (1) starts at 0 (required for bar graphs to avoid misleading comparisons), (2) exceeds the maximum value (80), (3) uses a round number increment (10) for easy reading.",
    steps: [
      { stepNumber: 1, title: "Identify range of data", explanation: "Data from 65 to 80. Start y-axis at 0." },
      { stepNumber: 2, title: "Choose scale", explanation: "0 to 100, increments of 10. Justification: starts at 0; exceeds max; easy to read.", result: "Scale: 0 to 100, increment 10." },
    ],
    hint: "Bar graphs should start at 0. Choose increments that are clean (5s, 10s).",
    keyConcepts: ["bar graph scale choice", "starting at 0"],
    conceptsCovered: ["mth:6:ch09:bar-graph-axes"],
    prerequisites: [],
    commonErrors: ["Starting the scale at 65 — this exaggerates differences and is misleading"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "In a pictograph, the key is 1 star = 100 students. Class A has 4 stars, Class B has 3 stars, Class C has 4.5 stars. How many students are in each class?",
    answer: "Class A: 4×100=400. Class B: 3×100=300. Class C: 4.5×100=450 (4 full stars + ½ star = 400+50=450).",
    steps: [
      { stepNumber: 1, title: "Multiply by scale", explanation: "A=400, B=300, C=450." },
      { stepNumber: 2, title: "Note half symbol", explanation: "4.5 stars: 4×100+½×100=400+50=450.", result: "A=400, B=300, C=450." },
    ],
    hint: "Half a symbol = half the scale value (100÷2=50).",
    keyConcepts: ["pictograph reading with half symbols"],
    conceptsCovered: ["mth:6:ch09:pictograph-reading"],
    prerequisites: [],
    commonErrors: ["Treating ½ symbol as 0 or as 1 full symbol"],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) In a bar graph, the height/length of a bar represents the ________ of the data. (b) All bars in a bar graph must have the same ________. (c) Bars in a bar graph are drawn with ________ between them.",
    answer: "(a) value (frequency). (b) width. (c) equal gaps/spaces.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "Height = data value." },
      { stepNumber: 2, title: "(b) and (c)", explanation: "Uniform width; equal gaps.", result: "value; width; gaps." },
    ],
    hint: "Recall the conventions for drawing bar graphs.",
    keyConcepts: ["bar graph conventions"],
    conceptsCovered: ["mth:6:ch09:bar-graph-construction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A bar graph shows trees planted: School A=120, School B=80, School C=100, School D=60. (a) Which school planted most trees? (b) How many more trees did A plant than D? (c) What is the total?",
    answer: "(a) School A (120). (b) 120–60=60. (c) 120+80+100+60=360 trees.",
    steps: [
      { stepNumber: 1, title: "(a) and (b)", explanation: "Max=120 (A). A–D=60." },
      { stepNumber: 2, title: "(c)", explanation: "120+80+100+60=360.", result: "(a)A. (b)60. (c)360." },
    ],
    hint: "Read bar heights for each school, then compute as asked.",
    keyConcepts: ["bar graph reading", "comparison", "total"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The number of cars crossing a toll gate each hour from 7 AM to 12 noon: 7AM=40, 8AM=90, 9AM=70, 10AM=50, 11AM=60, 12PM=80. Describe what a bar graph of this data would show. Which hour has busiest traffic? Between which hours is there the biggest change?",
    answer: "Bar graph: x-axis=hours (7AM–12PM), y-axis=number of cars. Bars at heights 40,90,70,50,60,80. Busiest: 8AM (90 cars). Biggest change: 7AM to 8AM: +50. Or 8AM to 9AM: –20; 9AM to 10AM: –20; 10AM to 11AM: +10; 11AM to 12PM: +20. Biggest single-hour change = 7AM→8AM (increase of 50).",
    steps: [
      { stepNumber: 1, title: "Busiest hour", explanation: "Maximum = 90 cars at 8AM." },
      { stepNumber: 2, title: "Biggest change", explanation: "Changes: +50, –20, –20, +10, +20. Biggest = 7AM→8AM (+50).", result: "Busiest: 8AM. Biggest change: 7AM to 8AM." },
    ],
    hint: "Compare each consecutive pair of hours to find the biggest jump.",
    keyConcepts: ["bar graph description", "maximum", "change between bars"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A school canteen sells: Samosa=150, Sandwich=90, Juice=120, Biscuits=60 per day. Suggest an appropriate scale for a bar graph and explain.",
    answer: "Max value=150. Scale: y-axis from 0 to 160 (or 0 to 200) with increments of 20. Increments of 20 are good because 150 = 7×20+10 (close to 7.5 intervals). Alternatively, scale 0–150 with increments of 30 (5 equal divisions: 0,30,60,90,120,150). Best choice: 0–160 with increments of 20 or 0–200 with increments of 25.",
    steps: [
      { stepNumber: 1, title: "Identify max and min", explanation: "Max=150, Min=60." },
      { stepNumber: 2, title: "Suggest scale", explanation: "0 to 160, increments of 20 (or 0 to 200, increments of 25). Must include 0.", result: "Scale: 0–160 by 20s (or 0–150 by 30s)." },
    ],
    hint: "The scale must start at 0 and accommodate the maximum value. Choose clean increments.",
    keyConcepts: ["choosing bar graph scale", "increments"],
    conceptsCovered: ["mth:6:ch09:bar-graph-axes"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-017",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A pictograph shows mango production with key: 1 basket = 200 mangoes. Village A=3 baskets, Village B=4.5 baskets, Village C=2.5 baskets, Village D=5 baskets. (a) Which village produced most? (b) Total production? (c) How many more did D produce than A?",
    answer: "(a) D (5 baskets=1000). (b) Total baskets=(3+4.5+2.5+5)=15; 15×200=3000 mangoes. (c) D–A=(5–3)×200=400 mangoes.",
    steps: [
      { stepNumber: 1, title: "(a) Most", explanation: "D=5 baskets=1000 mangoes." },
      { stepNumber: 2, title: "(b) Total and (c) difference", explanation: "Total=15×200=3000. D–A=2×200=400.", result: "(a)D. (b)3000. (c)400." },
    ],
    hint: "Multiply number of symbols by scale (200) to get actual values.",
    keyConcepts: ["pictograph with half symbols", "comparison"],
    conceptsCovered: ["mth:6:ch09:pictograph-scale"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-018",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Bar graph data — students scoring in ranges: 0–20: 4, 21–40: 7, 41–60: 12, 61–80: 9, 81–100: 3. How many students scored above 60? What fraction is this of the total?",
    answer: "Above 60 = 61–80 + 81–100 = 9+3=12. Total = 4+7+12+9+3=35. Fraction = 12/35.",
    steps: [
      { stepNumber: 1, title: "Count above 60", explanation: "9+3=12." },
      { stepNumber: 2, title: "Fraction", explanation: "12/35.", result: "12 students; fraction=12/35." },
    ],
    hint: "Above 60 means the 61–80 and 81–100 bars.",
    keyConcepts: ["bar graph reading", "fraction from graph"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-019",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Explain the difference between a pictograph and a bar graph. Give one advantage of each.",
    answer: "Pictograph: uses pictures/symbols to represent data. Advantage: visually appealing and easy to understand for all ages. Bar graph: uses rectangular bars whose heights represent data values. Advantage: more precise — can read exact values from the scale. Bar graphs work better for large values (where drawing many symbols would be tedious).",
    steps: [
      { stepNumber: 1, title: "Differences", explanation: "Pictograph uses pictures; bar graph uses bars with a numerical scale." },
      { stepNumber: 2, title: "Advantages", explanation: "Pictograph: appealing. Bar graph: precise, handles large values.", result: "Key differences and advantages stated." },
    ],
    hint: "Think about which is more precise and which is more visual.",
    keyConcepts: ["pictograph vs bar graph", "comparison"],
    conceptsCovered: ["mth:6:ch09:pictograph-reading"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-020",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A bar graph of monthly electricity bills (₹): Jan=800, Feb=750, Mar=600, Apr=500, May=550, Jun=700. (a) Highest month? (b) Month with least bill? (c) In how many months did bill exceed ₹700?",
    answer: "(a) January (₹800). (b) April (₹500). (c) Months > 700: Jan(800), Feb(750), Jun(700)... 700 is not strictly > 700. Months strictly > 700: Jan(800), Feb(750) = 2 months.",
    steps: [
      { stepNumber: 1, title: "(a) and (b)", explanation: "Max=800(Jan). Min=500(Apr)." },
      { stepNumber: 2, title: "(c)", explanation: "Strictly >700: 800>700 and 750>700. June=700 not >700. Count=2.", result: "(a)January. (b)April. (c)2 months." },
    ],
    hint: "For (c): 700 itself is NOT > 700 (not strictly greater).",
    keyConcepts: ["bar graph interpretation", "strict inequality"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: ["Including June (=700) in count — strictly greater means > 700 not ≥ 700"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-nce-021",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A pictograph shows newspapers sold. Key: 1 newspaper symbol = 50 copies. Mon=6, Tue=4, Wed=5, Thu=3, Fri=7, Sat=8 symbols. Find total sales for the week.",
    answer: "Total symbols = 6+4+5+3+7+8=33. Total copies = 33×50=1650 copies.",
    steps: [
      { stepNumber: 1, title: "Sum symbols", explanation: "6+4+5+3+7+8=33." },
      { stepNumber: 2, title: "Multiply by scale", explanation: "33×50=1650.", result: "1650 copies." },
    ],
    hint: "Sum all symbols, then multiply by 50.",
    keyConcepts: ["pictograph total", "scale multiplication"],
    conceptsCovered: ["mth:6:ch09:pictograph-scale"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A pictograph shows milk collected (in litres) at a dairy: Mon=3 symbols, Tue=4.5 symbols, Wed=2 symbols, Thu=5 symbols, Fri=3.5 symbols. Key: 1 symbol=20 litres. (a) Which day had most collection? (b) Total for the week? (c) How many symbols represent Friday's collection?",
    answer: "(a) Thursday: 5×20=100 L (most). (b) Total=(3+4.5+2+5+3.5)=18 symbols; 18×20=360 L. (c) Friday=3.5 symbols (already given — the question confirms 3.5 symbols for 3.5×20=70 L).",
    steps: [
      { stepNumber: 1, title: "(a) Most", explanation: "Thu=5 symbols=100 L." },
      { stepNumber: 2, title: "(b) Total", explanation: "18 symbols×20=360 L." },
      { stepNumber: 3, title: "(c) Friday symbols", explanation: "3.5 symbols (given directly).", result: "(a)Thursday. (b)360 L. (c)3.5 symbols." },
    ],
    hint: "Multiply symbols by 20 for litres.",
    keyConcepts: ["pictograph reading", "half symbols", "total"],
    conceptsCovered: ["mth:6:ch09:pictograph-reading"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Bar graph shows runs scored by 5 batsmen: A=72, B=45, C=88, D=60, E=33. (a) Who scored most? (b) Find the average (mean) score. (c) How many batsmen scored above average?",
    answer: "(a) C (88 runs). (b) Average=(72+45+88+60+33)/5=298/5=59.6. (c) Above 59.6: A(72)>59.6, C(88)>59.6, D(60)>59.6 = 3 batsmen.",
    steps: [
      { stepNumber: 1, title: "(a) Most", explanation: "Max=88 (C)." },
      { stepNumber: 2, title: "(b) and (c)", explanation: "Mean=298/5=59.6. A,C,D > 59.6 → 3 batsmen.", result: "(a)C. (b)59.6. (c)3." },
    ],
    hint: "Mean = sum/count. Count how many exceed the mean.",
    keyConcepts: ["bar graph", "mean/average", "above average"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: ["Including D=60 in above-average count — yes, 60>59.6 so D qualifies"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A survey found students' favourite fruit: Mango=25, Apple=15, Banana=20, Orange=10. If you draw a pictograph with key 1 symbol=5 students, how many symbols for each fruit?",
    answer: "Mango: 25÷5=5 symbols. Apple: 15÷5=3. Banana: 20÷5=4. Orange: 10÷5=2.",
    steps: [
      { stepNumber: 1, title: "Divide each by scale", explanation: "Mango=5, Apple=3, Banana=4, Orange=2." },
      { stepNumber: 2, title: "All whole numbers", explanation: "All divide evenly by 5 — no half symbols needed.", result: "5, 3, 4, 2 symbols." },
    ],
    hint: "Symbols = data value ÷ scale.",
    keyConcepts: ["pictograph construction from data"],
    conceptsCovered: ["mth:6:ch09:pictograph-scale"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Two bar graphs show test scores for Class 6A and 6B. Class 6A: 40–60: 5 students, 61–80: 12, 81–100: 8. Class 6B: 40–60: 8, 61–80: 10, 81–100: 7. Which class has more students scoring above 80? What percentage of 6A scored 81–100?",
    answer: "6A above 80 = 8. 6B above 80 = 7. 6A has more students above 80. Total 6A = 5+12+8=25. Percentage of 6A scoring 81–100 = 8/25×100=32%.",
    steps: [
      { stepNumber: 1, title: "Compare above 80", explanation: "6A=8, 6B=7. 6A has more." },
      { stepNumber: 2, title: "Percentage 6A", explanation: "Total 6A=25. 8/25×100=32%.", result: "6A has more (8>7); 32% of 6A scored 81–100." },
    ],
    hint: "Above 80 = 81–100 bar. Percentage = (count/total)×100.",
    keyConcepts: ["comparing two bar graphs", "percentage from data"],
    conceptsCovered: ["mth:6:ch09:bar-graph-axes"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A bar graph shows bicycle sales: Q1=120, Q2=150, Q3=90, Q4=180. What scale would you choose? In which quarter were sales lowest? By how much did Q4 exceed Q3?",
    answer: "Scale: 0–200 with increments of 20 (or 0–200 by 50). Lowest sales: Q3 (90). Q4 exceeded Q3 by 180–90=90 units.",
    steps: [
      { stepNumber: 1, title: "Scale", explanation: "Max=180; scale 0–200 by 20s works well." },
      { stepNumber: 2, title: "Lowest and Q4 vs Q3", explanation: "Min=Q3(90). Q4–Q3=90.", result: "Scale 0–200. Lowest: Q3. Q4 exceeds Q3 by 90." },
    ],
    hint: "Scale must accommodate max (180); round to clean value (200).",
    keyConcepts: ["bar graph scale", "comparison"],
    conceptsCovered: ["mth:6:ch09:bar-graph-construction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cmp-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Attendance data — School A: Mon=350, Tue=340, Wed=360, Thu=330, Fri=370. School B: Mon=310, Tue=330, Wed=350, Thu=320, Fri=360. On which day did A exceed B by the most? On which day was the gap smallest?",
    answer: "Differences (A–B): Mon=40, Tue=10, Wed=10, Thu=10, Fri=10. A exceeds B by the most on Monday (difference=40). The gap is smallest (tied) on Tue, Wed, Thu, Fri (all =10).",
    steps: [
      { stepNumber: 1, title: "Calculate A–B each day", explanation: "Mon=40,Tue=10,Wed=10,Thu=10,Fri=10." },
      { stepNumber: 2, title: "Max and min gap", explanation: "Max=40 (Mon). Min=10 (Tue,Wed,Thu,Fri).", result: "Biggest gap: Monday. Smallest: Tuesday–Friday (tied at 10)." },
    ],
    hint: "Compute (A–B) for each day separately.",
    keyConcepts: ["bar graph comparison", "gap between datasets"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Pictograph — books in library. Key: 1 book icon = 50 books. Fiction: 6 icons; Non-fiction: 4 icons; Science: 3 icons. How many books in each? Total?",
    answer: "Fiction: 6×50=300. Non-fiction: 4×50=200. Science: 3×50=150. Total: 300+200+150=650.",
    steps: [
      { stepNumber: 1, title: "Multiply each by 50", explanation: "300; 200; 150." },
      { stepNumber: 2, title: "Total", explanation: "650.", result: "Fiction=300; Non-fiction=200; Science=150; Total=650." },
    ],
    hint: "Icons × scale = books.",
    keyConcepts: ["pictograph calculation"],
    conceptsCovered: ["mth:6:ch09:pictograph-reading"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Bar graph — ice cream sales per month (units): April=200, May=350, June=500, July=450, August=300. Describe the trend and identify peak month.",
    answer: "Trend: sales increase from April to June, peak in June (500), then decline in July and August. Peak month = June (500 units). The graph shows a bell-shaped trend with peak in June (beginning of summer holiday).",
    steps: [
      { stepNumber: 1, title: "Identify trend", explanation: "200→350→500→450→300: rise then fall." },
      { stepNumber: 2, title: "Peak", explanation: "June = 500 (maximum).", result: "Peak: June. Trend: increases then decreases." },
    ],
    hint: "Look at whether the bars rise and fall systematically.",
    keyConcepts: ["bar graph trend", "peak value"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Construct a frequency table from this data and suggest whether a pictograph or bar graph is better to display it: Number of pets per household: 0→12 families, 1→8 families, 2→5 families, 3→2 families.",
    answer: "Frequency table already given. For display: Bar graph is better because the x-axis values (0,1,2,3) are numeric and evenly spaced, making bar graph ideal. A pictograph would work too but drawing pet symbols may be awkward for comparisons. Total families = 12+8+5+2=27.",
    steps: [
      { stepNumber: 1, title: "Confirm frequency table", explanation: "0→12, 1→8, 2→5, 3→2. Total=27." },
      { stepNumber: 2, title: "Recommend graph type", explanation: "Bar graph better for numeric x-axis with exact values.", result: "Table ready. Bar graph recommended." },
    ],
    hint: "When x-axis values are numbers, bar graphs are usually more precise.",
    keyConcepts: ["frequency table", "choosing graph type"],
    conceptsCovered: ["mth:6:ch09:bar-graph-construction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Bar graph — students in after-school clubs: Art=18, Music=24, Sports=30, Drama=12, Coding=21. (a) Which club is most popular? (b) What fraction of students attend Music? (c) If each club needs at least 2 teachers per 10 students, how many teachers does Sports need?",
    answer: "Total = 18+24+30+12+21=105. (a) Sports (30). (b) Music=24/105=8/35. (c) Sports=30 students. 30÷10=3 groups of 10; 3×2=6 teachers.",
    steps: [
      { stepNumber: 1, title: "(a) Most popular", explanation: "Max=30 (Sports)." },
      { stepNumber: 2, title: "(b) Fraction Music", explanation: "24/105=8/35." },
      { stepNumber: 3, title: "(c) Teachers for Sports", explanation: "30÷10×2=6 teachers.", result: "(a)Sports. (b)8/35. (c)6 teachers." },
    ],
    hint: "For (c): 30 students → 3 groups of 10 → 3×2 = 6 teachers.",
    keyConcepts: ["bar graph reading", "fraction", "real-world application"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-pyq-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State any three rules/conventions for drawing a bar graph.",
    answer: "Three conventions: (1) Both axes must be labelled — x-axis (categories) and y-axis (values with units). (2) The y-axis scale must start at 0 to avoid misleading comparisons. (3) All bars must have the same width, and equal gaps must be left between bars. Additional conventions: include a title; use a uniform scale on the y-axis.",
    steps: [
      { stepNumber: 1, title: "Recall conventions", explanation: "Labelled axes; scale starts at 0; uniform width and gaps." },
      { stepNumber: 2, title: "State three", explanation: "Three stated above.", result: "Three conventions given." },
    ],
    hint: "Think about what makes a bar graph clear, accurate, and easy to read.",
    keyConcepts: ["bar graph conventions", "drawing rules"],
    conceptsCovered: ["mth:6:ch09:bar-graph-construction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.BOARD_IMPORTANT, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CASE STUDY QUESTIONS (type: case-study)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-6-ch09-cst-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "CASE STUDY: A class teacher recorded the number of books read by 20 students in a month: 3, 5, 2, 4, 5, 3, 6, 2, 4, 5, 3, 4, 6, 5, 2, 3, 4, 5, 6, 3.\n(a) Make a frequency table with tally marks.\n(b) How many students read exactly 4 books?\n(c) What is the range?\n(d) Which number of books is most common?",
    answer: "(a) Frequency table: 2→3, 3→5, 4→4, 5→5, 6→3. Total=20 ✓. (b) 4 books: frequency=4 students. (c) Range=6–2=4. (d) Most common: both 3 and 5 have frequency 5 (tied).",
    steps: [
      { stepNumber: 1, title: "(a) Tally and table", explanation: "2:|||, 3:|||||, 4:||||, 5:|||||, 6:|||. Totals: 3,5,4,5,3=20 ✓." },
      { stepNumber: 2, title: "(b)(c)(d)", explanation: "(b)4. (c)6–2=4. (d)3 and 5 (both freq=5).", result: "All four parts answered." },
    ],
    hint: "Tally marks: count each value as you go through the list.",
    keyConcepts: ["frequency table", "tally marks", "range", "mode"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: ["Picking only one mode when two values tie for highest frequency"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 5, estimatedTimeMinutes: 10,
    question: "CASE STUDY: Students were asked about their study time per day (hours): 2,3,1,4,2,3,2,4,1,3,2,4,3,2,1,3,4,2,3,4,2,1,3,2,4.\n(a) Make a frequency table.\n(b) What fraction studied for 2 hours?\n(c) What fraction studied for ≥ 3 hours?\n(d) If a student is picked randomly, is it more likely they study 2 or 4 hours?",
    answer: "Count (25 students): 1→4, 2→9, 3→7, 4→5. Total=25 ✓. (b) 2 hours: 9/25. (c) ≥3 hours: (7+5)/25=12/25. (d) P(2 hours)=9/25=0.36; P(4 hours)=5/25=0.20. More likely: 2 hours.",
    steps: [
      { stepNumber: 1, title: "(a) Frequency table", explanation: "1→4, 2→9, 3→7, 4→5. Sum=25." },
      { stepNumber: 2, title: "(b)(c)(d)", explanation: "(b)9/25. (c)12/25. (d)9>5 so 2 hours more likely.", result: "All answered." },
    ],
    hint: "For (c): count all frequencies for values 3 and 4 together.",
    keyConcepts: ["frequency table", "fraction from data", "probability reasoning"],
    conceptsCovered: ["mth:6:ch09:raw-data-organisation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "CASE STUDY: A school conducted a sports week. Number of students participating in each sport (bar graph data): Cricket=80, Football=60, Badminton=45, Swimming=30, Athletics=70.\n(a) Which sport had most participation?\n(b) How many students participated in total?\n(c) What fraction participated in either Cricket or Football?\n(d) By what percent does Cricket exceed Swimming?",
    answer: "(a) Cricket (80). (b) 80+60+45+30+70=285. (c) Cricket+Football=140; fraction=140/285=28/57. (d) Cricket–Swimming=50; percent=(50/30)×100≈166.7% more.",
    steps: [
      { stepNumber: 1, title: "(a)(b)", explanation: "Max=80(Cricket). Total=285." },
      { stepNumber: 2, title: "(c)(d)", explanation: "C+F=140/285=28/57. Cricket exceeds Swimming by 50, which is (50/30)×100≈167%.", result: "All parts answered." },
    ],
    hint: "For (d): percent by which A exceeds B = (A–B)/B × 100.",
    keyConcepts: ["bar graph reading", "fraction", "percentage comparison"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: ["Computing (50/80)×100 instead of (50/30)×100 for 'Cricket exceeds Swimming'"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "CASE STUDY: The following pictograph shows mangoes sold by a vendor for 5 days. Key: ☆ = 30 mangoes. Mon: ☆☆☆; Tue: ☆☆☆☆; Wed: ☆☆; Thu: ☆☆☆☆☆; Fri: ☆☆☆.\n(a) On which day were most mangoes sold?\n(b) Total mangoes sold?\n(c) How many on Wednesday?\n(d) How many more on Thursday than Wednesday?",
    answer: "(a) Thursday (5 stars=150). (b) (3+4+2+5+3)×30=17×30=510. (c) 2×30=60. (d) (5–2)×30=90.",
    steps: [
      { stepNumber: 1, title: "(a)(c)(d)", explanation: "Thu=5 stars=max. Wed=60. Thu–Wed=90." },
      { stepNumber: 2, title: "(b) Total", explanation: "17 stars × 30 = 510.", result: "(a)Thursday (b)510 (c)60 (d)90." },
    ],
    hint: "Multiply each day's star count by 30.",
    keyConcepts: ["pictograph calculation", "comparison"],
    conceptsCovered: ["mth:6:ch09:pictograph-reading"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 10,
    question: "CASE STUDY: Test scores (%) of 30 students. Bar graph: 40–50: 3 students, 51–60: 6, 61–70: 10, 71–80: 8, 81–90: 2, 91–100: 1.\n(a) How many scored between 61–70?\n(b) What fraction scored below 61?\n(c) How many passed (≥60%)?\n(d) If 75% is distinction, how many students got distinction?",
    answer: "(a) 10. (b) Below 61 = 40–50 + 51–60 = 3+6=9; fraction=9/30=3/10. (c) ≥60% = 51–60 includes those ≥60... actually score range 51–60 includes 60. Passed ≥60: 6+10+8+2+1=27. (d) Distinction ≥75%: part of 71–80 + 81–90 + 91–100. We don't know exact breakdown within 71–80; assume all in 71–80 scored between 71–80 (none ≥75 for certainty). Strictly: 81–90+91–100=2+1=3 definitely. (Conservative: 3 for sure above 80, plus unknown portion of 71–80 group.) If we approximate: scores 75–80 would be half of 71–80 range ≈ 8/2=4; total ≈ 4+2+1=7. Standard answer: 3 students certainly got ≥81; if 71–80 is counted: 8+2+1=11 but the range starts at 71 not 75. For CBSE Class 6, typically the bar covers 71–80 and ≥75 falls within this — answer would be 8+2+1=11 if distinction is ≥71, but distinction is ≥75. The safe answer is: between 81–100: 3 students definitely got ≥75. For 71–80: unknown. CBSE expected answer: 11 (students in 71–80 + 81–90 + 91–100). Teacher should accept 11 as the Class 6 expected answer.",
    steps: [
      { stepNumber: 1, title: "(a)(b)", explanation: "(a)10. (b)9/30=3/10." },
      { stepNumber: 2, title: "(c)(d)", explanation: "(c)≥60: 6+10+8+2+1=27. (d)≥75 (Class 6 expected): 8+2+1=11.", result: "(a)10 (b)3/10 (c)27 (d)11 (approximate)." },
    ],
    hint: "For (d): the 71–80 group includes scores 71–80; ≥75 is partly in this group. For Class 6, include the full 71–80 bar for ≥75.",
    keyConcepts: ["bar graph reading", "conditional counting", "fraction from data"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "CASE STUDY: A hospital records the daily number of patients for 2 weeks: Week 1: Mon=45, Tue=38, Wed=52, Thu=41, Fri=60. Week 2: Mon=50, Tue=42, Wed=48, Thu=44, Fri=55.\n(a) Find the range for Week 1.\n(b) On which day was the combined 2-week total highest?\n(c) Did the hospital see more patients in Week 1 or Week 2?",
    answer: "(a) Range W1=60–38=22. (b) Combined totals: Mon=95, Tue=80, Wed=100, Thu=85, Fri=115. Highest = Friday (115). (c) W1=45+38+52+41+60=236. W2=50+42+48+44+55=239. Week 2 had more (239>236).",
    steps: [
      { stepNumber: 1, title: "(a) Range W1", explanation: "60–38=22." },
      { stepNumber: 2, title: "(b)(c)", explanation: "Fri combined=60+55=115 (highest). W1=236<W2=239.", result: "(a)22 (b)Friday (c)Week 2." },
    ],
    hint: "Add each day's patients from both weeks for combined totals.",
    keyConcepts: ["range", "comparison", "two-week totals"],
    conceptsCovered: ["mth:6:ch09:data-range"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 5, estimatedTimeMinutes: 10,
    question: "CASE STUDY: Rainfall (mm) data for two cities over 6 months: City A — Jan=50, Feb=30, Mar=20, Apr=40, May=70, Jun=90. City B — Jan=40, Feb=45, Mar=30, Apr=35, May=80, Jun=75.\n(a) Which city had higher total rainfall?\n(b) In how many months did A exceed B?\n(c) What is the range for each city?\n(d) In which month was the difference between A and B greatest?",
    answer: "(a) A=50+30+20+40+70+90=300. B=40+45+30+35+80+75=305. City B total is higher. (b) A>B: Jan(50>40)✓, Apr(40>35)✓, Jun(90>75)✓ = 3 months. (c) A: 90–20=70. B: 80–30=50. (d) Differences: Jan=10, Feb=|30–45|=15, Mar=10, Apr=5, May=10, Jun=15. Greatest=15 (Feb or Jun tied).",
    steps: [
      { stepNumber: 1, title: "(a)(c)", explanation: "A=300, B=305. B higher. Ranges: A=70, B=50." },
      { stepNumber: 2, title: "(b)(d)", explanation: "A>B: Jan,Apr,Jun=3 months. Greatest diff=15 (Feb and Jun).", result: "(a)B (b)3 months (c)A=70,B=50 (d)February and June." },
    ],
    hint: "Compute A–B and B–A for each month and take |difference| for (d).",
    keyConcepts: ["bar graph comparison", "range", "maximum difference"],
    conceptsCovered: ["mth:6:ch09:bar-graph-axes"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t1", topicName: "Collecting and Organising Data",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "CASE STUDY: A survey of 50 households found: Households with 0 cars: 15, 1 car: 20, 2 cars: 10, 3 cars: 5.\n(a) Verify total = 50.\n(b) What fraction has exactly 1 car?\n(c) What fraction has at least 1 car?\n(d) Range of number of cars per household?",
    answer: "(a) 15+20+10+5=50 ✓. (b) 1 car: 20/50=2/5. (c) At least 1 = 20+10+5=35; 35/50=7/10. (d) Range=3–0=3.",
    steps: [
      { stepNumber: 1, title: "(a)(d)", explanation: "Sum=50 ✓. Range=3." },
      { stepNumber: 2, title: "(b)(c)", explanation: "(b)2/5. (c)7/10.", result: "All four parts answered." },
    ],
    hint: "At least 1 means 1 or more (exclude 0 cars).",
    keyConcepts: ["frequency table", "fraction", "at least condition"],
    conceptsCovered: ["mth:6:ch09:frequency-table"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 10,
    question: "CASE STUDY: Sales of five flavours of ice cream. Pictograph with key: 1 cone symbol = 40 cups. Vanilla: 5 cones; Chocolate: 7.5 cones; Strawberry: 4 cones; Mango: 6 cones; Pineapple: 3.5 cones.\n(a) Total sales of each flavour.\n(b) Which flavour sells most?\n(c) Total cups sold.\n(d) By what fraction does Chocolate exceed Pineapple?",
    answer: "(a) Vanilla=200, Chocolate=300, Strawberry=160, Mango=240, Pineapple=140. (b) Chocolate (300). (c) Total=(5+7.5+4+6+3.5)×40=26×40=1040. (d) Choc–Pine=300–140=160; fraction=160/140=8/7 (Chocolate is 8/7 of Pineapple, or exceeds by 160/140=8/7–1=1/7 of Pineapple sales... wait: 'by what fraction does Choc exceed Pine' = (300–140)/140=160/140=8/7. Or excess as fraction of Pineapple = 8/7. As fraction of total: 160/1040=2/13).",
    steps: [
      { stepNumber: 1, title: "(a)(b)", explanation: "Multiply each by 40. Choc=300 (max)." },
      { stepNumber: 2, title: "(c)(d)", explanation: "Total=1040. Excess=160; fraction over Pine=160/140=8/7.", result: "(a)listed (b)Chocolate (c)1040 (d)160/140=8/7 more." },
    ],
    hint: "Half a cone symbol = 20 cups. For (d): excess/pineapple.",
    keyConcepts: ["pictograph with half symbols", "total", "fraction comparison"],
    conceptsCovered: ["mth:6:ch09:pictograph-scale"],
    prerequisites: [],
    commonErrors: ["Treating 7.5 symbols as 7 — must use 7.5×40=300"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch09-cst-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Data Handling",
    topicId: "t2", topicName: "Pictographs and Bar Graphs",
    questionType: "case-study", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "CASE STUDY: A library records books borrowed per genre last month. Bar graph values: Fiction=360, Biography=120, Science=240, History=180, Comics=300.\n(a) Which genre was most borrowed?\n(b) Total books borrowed?\n(c) What fraction was Science?\n(d) Fiction + Comics combined vs Biography + History + Science. Which group is larger?",
    answer: "(a) Fiction (360). (b) 360+120+240+180+300=1200. (c) 240/1200=1/5. (d) F+C=660; B+H+S=540. F+C group is larger.",
    steps: [
      { stepNumber: 1, title: "(a)(b)", explanation: "Max=360 (Fiction). Total=1200." },
      { stepNumber: 2, title: "(c)(d)", explanation: "(c)1/5. (d)660>540 → Fiction+Comics group larger.", result: "All four answered." },
    ],
    hint: "Compute each group's total and compare.",
    keyConcepts: ["bar graph reading", "fractions", "grouping comparison"],
    conceptsCovered: ["mth:6:ch09:bar-graph-interpretation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

];
