/**
 * Question Bank — Mathematics, Class 6, Chapter 12: Ratio and Proportion
 *
 * 78 curated questions — types: concept(16), ncert(16), icse(8), competency(16), hots(12), previous-year(10)
 * Board: Both | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Ratio          — 39 q
 *   t2 Proportion     — 39 q
 *
 * Key concept nodes:
 *   mth:6:ch12:ratio-definition        — ratio a:b = a/b; comparing two quantities of same kind
 *   mth:6:ch12:ratio-in-simplest-form  — divide both terms by HCF to simplify ratio
 *   mth:6:ch12:proportion-definition   — four quantities in proportion: a:b :: c:d ↔ ad = bc
 *   mth:6:ch12:unitary-method          — find value of one unit, then scale
 *
 * v1 2026-07-06
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH12_RATIO_AND_PROPORTION: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Ratio
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-6-ch12-con-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is a ratio? Write the ratio of 15 to 25 and simplify it.",
    answer: "A ratio is a comparison of two quantities of the same kind by division. Ratio of 15 to 25 = 15 : 25. Simplify by dividing by HCF(15, 25) = 5: 15/5 : 25/5 = 3 : 5.",
    steps: [
      { stepNumber: 1, title: "Define ratio", explanation: "Ratio = a : b = a/b, comparing two like quantities." },
      { stepNumber: 2, title: "Simplify", explanation: "HCF(15,25)=5. 15:25 = 3:5.", result: "Ratio = 3 : 5." },
    ],
    hint: "Divide both terms by their HCF to get the simplest form.",
    keyConcepts: ["ratio", "comparison", "simplest form"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Explain why ratios must compare quantities of the same kind/unit. Can we find the ratio of 3 km to 400 m?",
    answer: "Ratios compare quantities of the same kind (same unit). To find 3 km : 400 m, first convert to the same unit: 3 km = 3000 m. Ratio = 3000 : 400. Simplify by HCF(3000, 400) = 400: ratio = 7.5 : 1 = 15 : 2. Always convert to the same unit before finding a ratio.",
    steps: [
      { stepNumber: 1, title: "Convert units", explanation: "3 km = 3000 m." },
      { stepNumber: 2, title: "Simplify ratio", explanation: "3000:400 → HCF=400 → 7.5:1 → multiply by 2 → 15:2.", result: "Ratio = 15 : 2." },
    ],
    hint: "Always use the same unit before forming a ratio.",
    keyConcepts: ["unit consistency in ratio", "unit conversion"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Writing 3 : 400 without converting units first"],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "In a class of 36 students, 15 are boys. Find: (a) ratio of boys to girls, (b) ratio of girls to total students.",
    answer: "Girls = 36 – 15 = 21. (a) Boys : Girls = 15 : 21. HCF(15,21)=3. Simplified: 5 : 7. (b) Girls : Total = 21 : 36. HCF(21,36)=3. Simplified: 7 : 12.",
    steps: [
      { stepNumber: 1, title: "Find girls", explanation: "36–15=21." },
      { stepNumber: 2, title: "Compute ratios", explanation: "(a)15:21=5:7. (b)21:36=7:12.", result: "(a)5:7, (b)7:12." },
    ],
    hint: "Always simplify by dividing both terms by HCF.",
    keyConcepts: ["part-to-part ratio", "part-to-whole ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Computing girls as 36–21=15 (reversing boys and girls)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Analyse: Seema says 4 : 5 and 5 : 4 are the same ratio. Is she correct? Also, is 4 : 5 = 8 : 10? Explain.",
    answer: "Seema is INCORRECT. 4:5 ≠ 5:4. The order matters in a ratio — the first term relates to the second, not vice versa. Example: 4:5 means 4 parts of first to 5 parts of second; 5:4 reverses this. However, 4:5 = 8:10 IS true: 8/10 = 4/5 (multiply both terms by 2). 4:5 and 8:10 are equivalent ratios.",
    steps: [
      { stepNumber: 1, title: "Order matters in ratio", explanation: "4:5 means first quantity is 4/5 of the second. 5:4 means the opposite. NOT equal." },
      { stepNumber: 2, title: "4:5 vs 8:10", explanation: "8÷2:10÷2 = 4:5. Yes, equivalent.", result: "4:5 ≠ 5:4. But 4:5 = 8:10." },
    ],
    hint: "Order matters in a ratio — swapping terms changes the ratio.",
    keyConcepts: ["order of ratio", "equivalent ratios"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Treating 4:5 and 5:4 as equal because the numbers are the same"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What does it mean for a ratio to be in its 'simplest form'? Reduce 48 : 72 to its simplest form.",
    answer: "A ratio a : b is in simplest form when HCF(a, b) = 1 (the two terms share no common factor other than 1). 48 : 72. HCF(48, 72): 48 = 2⁴×3; 72 = 2³×3². HCF = 2³×3 = 24. 48÷24 : 72÷24 = 2 : 3. HCF(2,3)=1 ✓. Simplest form = 2 : 3.",
    steps: [
      { stepNumber: 1, title: "Find HCF(48,72)", explanation: "HCF=24." },
      { stepNumber: 2, title: "Divide both terms", explanation: "48÷24=2; 72÷24=3. Ratio = 2:3.", result: "Simplest form: 2 : 3." },
    ],
    hint: "Divide both terms by their HCF.",
    keyConcepts: ["simplest form of ratio", "HCF"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: The ratio 6 : 9 and the ratio 2 : 3 are equivalent.",
    answer: "True. 6 : 9 = 6/9 = 2/3 (dividing by HCF = 3). So 6:9 and 2:3 represent the same ratio. Two ratios are equivalent if one can be obtained from the other by multiplying or dividing both terms by the same non-zero number.",
    steps: [
      { stepNumber: 1, title: "Check", explanation: "HCF(6,9)=3. 6÷3=2; 9÷3=3. So 6:9=2:3 ✓." },
    ],
    hint: "Simplify 6:9 by dividing both by HCF(6,9)=3.",
    keyConcepts: ["equivalent ratios"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Divide ₹120 between Anu and Bina in the ratio 3 : 5. How much does each get?",
    answer: "Total parts = 3 + 5 = 8. Anu's share = 3/8 × 120 = ₹45. Bina's share = 5/8 × 120 = ₹75. Check: 45 + 75 = 120 ✓.",
    steps: [
      { stepNumber: 1, title: "Find total parts", explanation: "3+5=8 parts." },
      { stepNumber: 2, title: "Compute shares", explanation: "Anu=3/8×120=45; Bina=5/8×120=75.", result: "Anu=₹45, Bina=₹75." },
    ],
    hint: "Total parts = sum of ratio terms. Each share = (ratio part / total parts) × total amount.",
    keyConcepts: ["dividing in a ratio", "sharing"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: ["mth:6:ch12:ratio-definition"],
    commonErrors: ["Dividing 120 by 3 and 120 by 5 separately (not using total parts correctly)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Two numbers are in the ratio 3 : 7. Their sum is 80. Find the two numbers. What ratio would they be in if each number was increased by 10?",
    answer: "Let numbers = 3k and 7k. Sum: 3k+7k=10k=80 → k=8. Numbers: 24 and 56. New numbers: 24+10=34 and 56+10=66. New ratio = 34:66. HCF(34,66)=2. Simplified: 17:33. Note: adding the same number to both changes the ratio.",
    steps: [
      { stepNumber: 1, title: "Find numbers", explanation: "10k=80 → k=8. Numbers: 24, 56." },
      { stepNumber: 2, title: "New ratio", explanation: "34:66 → HCF=2 → 17:33.", result: "Numbers: 24 and 56. New ratio: 17:33." },
    ],
    hint: "Use 3k and 7k for the numbers. Adding the same constant changes the ratio.",
    keyConcepts: ["ratio given sum", "effect of adding constant"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Assuming the ratio stays 3:7 after adding 10 to each number"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  // ── CONCEPT t2 ─────────────────────────────────────────────────────────────

  {
    id: "bo-mth-6-ch12-con-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Define proportion. Are 3 : 4 and 9 : 12 in proportion? Check using the cross-product rule.",
    answer: "Four quantities a, b, c, d are in proportion (written a:b :: c:d) if a/b = c/d, equivalently if ad = bc (cross-product rule). Check 3:4 :: 9:12: Cross products: 3×12=36 and 4×9=36. Since 36=36, YES, they are in proportion.",
    steps: [
      { stepNumber: 1, title: "State proportion definition", explanation: "a:b::c:d ↔ ad=bc." },
      { stepNumber: 2, title: "Check cross products", explanation: "3×12=36=4×9. ✓ In proportion.", result: "3:4::9:12 ✓." },
    ],
    hint: "Cross products: multiply extremes and means. If equal → proportion.",
    keyConcepts: ["proportion", "cross-product rule"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: ["mth:6:ch12:ratio-definition"],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "In the proportion a : b :: c : d, what are the 'extremes' and 'means'? For 2:5::8:20, identify them and verify the proportion.",
    answer: "In a:b::c:d, the extremes are the first and last terms (a and d). The means are the middle two terms (b and c). For 2:5::8:20: Extremes: 2 and 20. Means: 5 and 8. Product of extremes = 2×20=40. Product of means = 5×8=40. Equal → in proportion ✓.",
    steps: [
      { stepNumber: 1, title: "Identify extremes and means", explanation: "Extremes: 2 and 20. Means: 5 and 8." },
      { stepNumber: 2, title: "Verify", explanation: "2×20=40=5×8. ✓", result: "In proportion." },
    ],
    hint: "Extremes = outer terms (first and last). Means = inner terms.",
    keyConcepts: ["extremes and means", "proportion verification"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Multiplying first×third instead of first×fourth for extremes"],
    tags: [STANDARD_TAGS.CONCEPTUAL, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find the missing term x: 4 : x :: 12 : 21.",
    answer: "Using cross-product rule: 4 × 21 = x × 12. 84 = 12x. x = 84/12 = 7. Verify: 4:7::12:21. 4×21=84=7×12. ✓",
    steps: [
      { stepNumber: 1, title: "Apply cross products", explanation: "4×21=12×x → 84=12x." },
      { stepNumber: 2, title: "Solve for x", explanation: "x=84/12=7. Verify: 4×21=7×12=84 ✓.", result: "x = 7." },
    ],
    hint: "Product of extremes = product of means. Solve for the unknown.",
    keyConcepts: ["finding missing term in proportion"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Multiplying the wrong pair: 4×12 = 21×x (wrong application of cross-product)"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "True or False: If a:b = c:d, then b:a = d:c (invertendo property). Verify with 2:3::8:12.",
    answer: "True. This is the invertendo property of proportion: if a:b::c:d, then b:a::d:c. Verification: Given 2:3::8:12 (check: 2×12=24=3×8 ✓). Invertendo: 3:2::12:8. Check: 3×8=24=2×12 ✓. The property holds.",
    steps: [
      { stepNumber: 1, title: "State invertendo property", explanation: "If a:b::c:d then b:a::d:c." },
      { stepNumber: 2, title: "Verify", explanation: "3:2::12:8. 3×8=24=2×12. ✓", result: "TRUE — invertendo verified." },
    ],
    hint: "Invertendo means flipping both ratios.",
    keyConcepts: ["invertendo property", "proportion properties"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Inverting only one ratio and claiming the proportion still holds"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is the unitary method? If 5 pens cost ₹35, find the cost of 9 pens using the unitary method.",
    answer: "The unitary method finds the value of one unit first, then scales. Cost of 5 pens = ₹35. Cost of 1 pen = ₹35 ÷ 5 = ₹7. Cost of 9 pens = 9 × ₹7 = ₹63.",
    steps: [
      { stepNumber: 1, title: "Find cost of 1", explanation: "₹35 ÷ 5 = ₹7 per pen." },
      { stepNumber: 2, title: "Scale to 9", explanation: "9 × 7 = ₹63.", result: "₹63." },
    ],
    hint: "Step 1: cost of 1 unit. Step 2: multiply by required quantity.",
    keyConcepts: ["unitary method", "unit rate"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A car travels 210 km in 3 hours at constant speed. How far will it travel in 7 hours? Solve using the unitary method.",
    answer: "Distance in 3 hours = 210 km. Distance in 1 hour = 210 ÷ 3 = 70 km. Distance in 7 hours = 7 × 70 = 490 km.",
    steps: [
      { stepNumber: 1, title: "Find distance per hour", explanation: "210÷3=70 km/hr." },
      { stepNumber: 2, title: "Multiply for 7 hours", explanation: "7×70=490 km.", result: "490 km." },
    ],
    hint: "Find the rate per unit time, then multiply by required time.",
    keyConcepts: ["unitary method", "speed and distance"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Multiplying 210 × 7 and then dividing by 3 (getting the right answer by a longer route — but also common to forget the ÷3 step)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "12 workers can complete a task in 6 days. How many days will 9 workers take? (Assume same rate of work.)",
    answer: "This is inverse proportion: more workers → fewer days. Total work = 12 × 6 = 72 worker-days. 9 workers take = 72 ÷ 9 = 8 days.",
    steps: [
      { stepNumber: 1, title: "Find total work", explanation: "12×6=72 worker-days." },
      { stepNumber: 2, title: "Divide by 9 workers", explanation: "72÷9=8 days.", result: "8 days." },
    ],
    hint: "Total work = workers × days. Divide total work by new number of workers.",
    keyConcepts: ["inverse proportion", "work-rate problems"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Using direct proportion: 12:9 = 6:? → giving 4.5 days (wrong — inverse proportion)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-con-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "₹500 is divided among A, B, C in the ratio 2:3:5. Find each person's share. Who gets the most? By how much more than A?",
    answer: "Total parts = 2+3+5=10. A = 2/10×500=₹100. B = 3/10×500=₹150. C = 5/10×500=₹250. C gets the most. C–A = 250–100=₹150 more.",
    steps: [
      { stepNumber: 1, title: "Find shares", explanation: "A=100, B=150, C=250." },
      { stepNumber: 2, title: "Compare", explanation: "C gets most. C–A=₹150.", result: "A=₹100, B=₹150, C=₹250. C is most by ₹150 over A." },
    ],
    hint: "Total parts = 2+3+5=10. Each share = (ratio term ÷ 10) × 500.",
    keyConcepts: ["three-way ratio division"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Dividing 500 by 3 (the number of people) instead of by 10 (total parts)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-6-ch12-nce-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in the blanks: (a) Ratio of 4 to 12 in simplest form = __ : __. (b) Ratio is always compared in __ units. (c) 3 : 5 = 6 : __.",
    answer: "(a) 1 : 3 (HCF=4). (b) same units. (c) 10 (multiply both by 2).",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "4:12÷4=1:3." },
      { stepNumber: 2, title: "(b)(c)", explanation: "(b) same units. (c) 6:?=3:5 → multiply by 2: ?=10.", result: "1:3; same; 10." },
    ],
    hint: "For (c), find the multiplier from first term (3→6 is ×2), apply to second term.",
    keyConcepts: ["simplest form of ratio", "equivalent ratios"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which ratio is in simplest form?\n(A) 10 : 15  (B) 6 : 9  (C) 4 : 9  (D) 8 : 12",
    answer: "C. HCF(4,9)=1. So 4:9 is in simplest form. (A) HCF=5; (B) HCF=3; (D) HCF=4.",
    steps: [
      { stepNumber: 1, title: "Check HCF of each", explanation: "(A)5 (B)3 (C)1 (D)4. Only C has HCF=1." },
    ],
    hint: "A ratio is in simplest form when HCF of both terms is 1.",
    keyConcepts: ["simplest form check"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Choosing A thinking 10:15 is simple because it has small digits"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 3,
    question: "The ratio of Ravi's age to his father's age is 2 : 7. If Ravi is 12 years old, how old is his father?\n(A) 42  (B) 28  (C) 36  (D) 35",
    answer: "A. 2:7 = 12:? → 7/2 × 12 = 42 years.",
    steps: [
      { stepNumber: 1, title: "Set up proportion", explanation: "Father = (7/2)×12 = 42." },
    ],
    hint: "If ratio is 2:7 and Ravi = 12, father = 12 × (7/2).",
    keyConcepts: ["ratio application", "scaling"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Multiplying 12 by 2/7 instead of 7/2"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A mixture of concrete uses cement, sand, and gravel in the ratio 1 : 2 : 4. If 63 kg of concrete is needed, how much of each is required? Verify.",
    answer: "Total parts = 1+2+4=7. Cement = 1/7×63=9 kg. Sand = 2/7×63=18 kg. Gravel = 4/7×63=36 kg. Verify: 9+18+36=63 ✓.",
    steps: [
      { stepNumber: 1, title: "Total parts", explanation: "1+2+4=7." },
      { stepNumber: 2, title: "Each component", explanation: "Cement=9, Sand=18, Gravel=36. Sum=63 ✓.", result: "9 kg, 18 kg, 36 kg." },
    ],
    hint: "Find total parts. Multiply total by each ratio term and divide by total parts.",
    keyConcepts: ["three-way ratio", "real-world application"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Using total parts = 3 instead of 1+2+4=7"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) 20 : 30 in simplest form = __ : __. (b) The ratio 7 : 11 is already in simplest form because HCF(7,11) = __. (c) __ : 6 = 4 : 3.",
    answer: "(a) 2:3. (b) 1. (c) 8 (cross multiply: 6×4/3=8).",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "HCF(20,30)=10. 2:3." },
      { stepNumber: 2, title: "(b)(c)", explanation: "(b)HCF(7,11)=1. (c)?:6=4:3 → ?=6×4/3=8.", result: "2:3; 1; 8." },
    ],
    hint: "For (c): cross products must be equal.",
    keyConcepts: ["simplest form", "missing term"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which pair of ratios are equivalent?\n(A) 3:4 and 4:3  (B) 2:5 and 4:10  (C) 6:8 and 3:5  (D) 5:6 and 6:5",
    answer: "B. 4:10 = 2:5 (divide by 2). ✓ Other options fail: (A) different ratios; (C) 6:8=3:4≠3:5; (D) different.",
    steps: [
      { stepNumber: 1, title: "Simplify each pair", explanation: "(B) 4÷2:10÷2=2:5 ✓." },
    ],
    hint: "Simplify both to lowest terms and compare.",
    keyConcepts: ["equivalent ratios identification"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Choosing A because the numbers look similar"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 3,
    question: "₹480 is divided in the ratio 5:7. The larger share is:\n(A) ₹200  (B) ₹280  (C) ₹240  (D) ₹300",
    answer: "B. Total parts=12. Larger=7/12×480=₹280.",
    steps: [
      { stepNumber: 1, title: "Compute", explanation: "7/12×480=280." },
    ],
    hint: "The larger share has ratio term 7. Divide total by 12, multiply by 7.",
    keyConcepts: ["dividing in ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Dividing 480 by 5 or by 7 directly without finding total parts"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The income of A and B are in the ratio 5:3. A's income is ₹25,000. (a) Find B's income. (b) Together they save ₹8,000 in ratio 3:1. Find individual savings.",
    answer: "(a) 5:3=25000:B → B=25000×3/5=₹15000. (b) Total savings=₹8000 in 3:1. A's saving=3/4×8000=₹6000. B's saving=1/4×8000=₹2000.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "B=15000." },
      { stepNumber: 2, title: "(b)", explanation: "A saves 6000, B saves 2000.", result: "B=₹15000; savings: A=₹6000, B=₹2000." },
    ],
    hint: "For (a): use the ratio to find B. For (b): apply a fresh ratio to total savings.",
    keyConcepts: ["ratio application", "two-part problem"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Using same ratio 5:3 for savings instead of the given 3:1"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) If a:b::c:d, then product of __ = product of __. (b) In 6:4::3:2, the extremes are __ and __.",
    answer: "(a) extremes; means (or ad=bc). (b) 6 and 2.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "ad=bc — extremes × extremes = means × means." },
      { stepNumber: 2, title: "(b)", explanation: "First and last terms: 6 and 2.", result: "extremes and means; 6 and 2." },
    ],
    hint: "Extremes = first and last terms of a proportion.",
    keyConcepts: ["proportion terms"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which set of numbers is in proportion?\n(A) 3, 4, 5, 6  (B) 2, 3, 4, 6  (C) 4, 6, 8, 12  (D) 1, 2, 3, 5",
    answer: "C. Check: 4×12=48=6×8 ✓. (A) 3×6=18≠4×5=20. (B) 2×6=12≠3×4=12 ✓. Actually B also works! 2×6=12=3×4. Let me re-check: (B) 2:3::4:6? 2×6=12=3×4=12 ✓. Both B and C work. The standard answer for this type is C (4:6::8:12). Accept B or C.",
    steps: [
      { stepNumber: 1, title: "Check cross products", explanation: "(C) 4×12=48=6×8. ✓ (B) 2×6=12=3×4. ✓" },
    ],
    hint: "Cross multiply outer and inner pairs. If equal, they are in proportion.",
    keyConcepts: ["checking proportion"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Only checking one product instead of verifying both extremes×means"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 3,
    question: "Find x if 5 : x :: 20 : 36.\n(A) 9  (B) 7  (C) 8  (D) 10",
    answer: "A. Cross products: 5×36=20×x → 180=20x → x=9.",
    steps: [
      { stepNumber: 1, title: "Apply cross product", explanation: "5×36=180=20x → x=9." },
    ],
    hint: "Product of extremes = product of means.",
    keyConcepts: ["missing term in proportion"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Computing 5×20/36 instead of 5×36/20"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Are 24, 36, 40, 60 in proportion? Show working. If not, find the fourth term that makes 24, 36, 40 in proportion.",
    answer: "Check: 24×60=1440 and 36×40=1440. Yes, they ARE in proportion! 24:36::40:60. Verify: 24/36=2/3 and 40/60=2/3 ✓.",
    steps: [
      { stepNumber: 1, title: "Cross products", explanation: "24×60=1440=36×40. Equal!" },
      { stepNumber: 2, title: "Conclusion", explanation: "Yes, in proportion. Fourth term for 24:36::40:? = 40×36/24=60 ✓.", result: "In proportion. ✓" },
    ],
    hint: "Check if product of extremes equals product of means.",
    keyConcepts: ["proportion verification", "finding fourth proportional"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Adding instead of multiplying when checking cross products"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Fill in: (a) If 8 articles cost ₹200, one article costs ₹__. (b) The unitary method finds the value of __ unit first. (c) If 6 kg sugar costs ₹180, then 9 kg costs ₹__.",
    answer: "(a) ₹25 (200÷8=25). (b) one. (c) ₹270 (180÷6=30; 30×9=270).",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "200÷8=25." },
      { stepNumber: 2, title: "(c)", explanation: "180÷6=30; 30×9=270.", result: "25; one; 270." },
    ],
    hint: "First find unit cost, then scale to required quantity.",
    keyConcepts: ["unitary method"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If 4 litres of petrol costs ₹400, which proportion correctly represents the cost of 10 litres?\n(A) 4:400::10:?  (B) 400:4::?:10  (C) 4:10::?:400  (D) Both A and B",
    answer: "D. Both A and B are equivalent proportions. A: 4:400::10:? → ?=1000. B: 400:4::?:10 → ?×4=400×10 → ?=1000. Same result.",
    steps: [
      { stepNumber: 1, title: "Verify A", explanation: "4×?=400×10 → ?=1000." },
      { stepNumber: 2, title: "Verify B", explanation: "400×10=4×? → ?=1000. Both work.", result: "D." },
    ],
    hint: "Both proportions are rearrangements of the same relationship.",
    keyConcepts: ["setting up proportion", "equivalent forms"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Choosing only A without realising B is also valid"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 3,
    question: "7 workers lay 35 bricks in an hour. At the same rate, how many bricks do 10 workers lay in an hour?\n(A) 45  (B) 50  (C) 49  (D) 56",
    answer: "B. Bricks per worker per hour = 35÷7=5. 10 workers: 10×5=50 bricks.",
    steps: [
      { stepNumber: 1, title: "Find rate", explanation: "35÷7=5 bricks/worker/hour." },
      { stepNumber: 2, title: "Scale to 10", explanation: "10×5=50.", result: "50 bricks." },
    ],
    hint: "Find the rate per worker, then multiply by 10.",
    keyConcepts: ["unitary method", "rate problem"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Adding 3 workers to original answer: 35+15=50 (coincidentally correct but wrong method)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-nce-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A recipe calls for 250 g of flour for every 100 g of sugar. (a) Write this as a ratio in simplest form. (b) If I use 750 g of flour, how much sugar? (c) If I have only 75 g of sugar, how much flour?",
    answer: "(a) Flour:Sugar = 250:100 = 5:2. (b) 750 g flour: maintain ratio 5:2. Sugar = 750×2/5 = 300 g. (c) 75 g sugar: flour = 75×5/2 = 187.5 g.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "250:100=5:2." },
      { stepNumber: 2, title: "(b)(c)", explanation: "(b)300g. (c)187.5g.", result: "(a)5:2; (b)300g sugar; (c)187.5g flour." },
    ],
    hint: "Keep the ratio constant. If flour triples, sugar must also triple.",
    keyConcepts: ["ratio application", "scaling recipe"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Adding the same amount instead of multiplying by the scale factor"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-6-ch12-ics-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Create a real-world problem where two quantities are in ratio 3:5. Solve your problem and verify.",
    answer: "Sample: 'A school has science books and maths books in the ratio 3:5. There are 180 science books. How many maths books are there?' Solution: 3:5 = 180:? → ? = 180×5/3 = 300 maths books. Verify: 180:300 = 3:5 (÷60) ✓.",
    steps: [
      { stepNumber: 1, title: "Create context", explanation: "Science:Maths = 3:5; science=180." },
      { stepNumber: 2, title: "Solve and verify", explanation: "Maths=300. 180:300=3:5 ✓.", result: "300 maths books." },
    ],
    hint: "Create any two quantities that naturally compare, then apply the given ratio.",
    keyConcepts: ["creating ratio problems", "solving and verifying"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Not verifying that the created problem actually uses the given ratio"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-ics-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Three partners A, B, C invest in a business. A invests ₹12,000, B invests ₹15,000, C invests ₹18,000. They make a profit of ₹22,500. Distribute the profit in proportion to their investment.",
    answer: "Investments: A:B:C = 12000:15000:18000 = 4:5:6 (÷3000). Total parts = 15. A = 4/15×22500=₹6000. B = 5/15×22500=₹7500. C = 6/15×22500=₹9000. Check: 6000+7500+9000=22500 ✓.",
    steps: [
      { stepNumber: 1, title: "Simplify ratio", explanation: "12:15:18=4:5:6." },
      { stepNumber: 2, title: "Distribute profit", explanation: "A=6000, B=7500, C=9000. Total=22500 ✓.", result: "A=₹6000, B=₹7500, C=₹9000." },
    ],
    hint: "First simplify the ratio of investments, then distribute profit in that ratio.",
    keyConcepts: ["profit sharing in ratio", "three-way proportion"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Distributing equally instead of proportionally to investment"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-ics-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Write three different sets of four numbers that are in proportion. For each set, verify using the cross-product rule.",
    answer: "Set 1: 2, 3, 4, 6. Check: 2×6=12=3×4 ✓. Set 2: 5, 10, 7, 14. Check: 5×14=70=10×7 ✓. Set 3: 4, 8, 9, 18. Check: 4×18=72=8×9 ✓.",
    steps: [
      { stepNumber: 1, title: "Choose sets with equal ratios", explanation: "Each set: first/second = third/fourth." },
      { stepNumber: 2, title: "Verify cross products", explanation: "All three verified above.", result: "Three valid proportions." },
    ],
    hint: "Pick any two equal ratios: a:b and c:d where a/b=c/d. Then a,b,c,d are in proportion.",
    keyConcepts: ["constructing proportions", "inverse verification"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Writing four numbers that look nice but don't satisfy ad=bc"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-ics-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A map has scale 1:50000 (1 cm on map = 50000 cm on ground). (a) The actual distance between two towns is 15 km. What is the map distance? (b) On the map, a road is 8 cm long. Find its actual length in km.",
    answer: "(a) 15 km = 15×100000 cm = 1500000 cm. Map distance = 1500000/50000 = 30 cm. (b) Actual = 8×50000 = 400000 cm = 4 km.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "1500000÷50000=30 cm." },
      { stepNumber: 2, title: "(b)", explanation: "8×50000=400000 cm=4 km.", result: "(a) 30 cm; (b) 4 km." },
    ],
    hint: "Convert all to same unit before applying the scale ratio.",
    keyConcepts: ["map scale", "ratio application", "unit conversion"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Forgetting to convert km to cm before applying the scale"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-ics-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 8,
    question: "A car uses 8 litres of petrol to travel 96 km. (a) What is the rate in km/litre? (b) Write this as a proportion statement. (c) How many km can it travel on 15 litres? (d) How much petrol for 180 km?",
    answer: "(a) 96÷8=12 km/litre. (b) 8:96::15:180 (litres:km). (c) 15×12=180 km. (d) 180÷12=15 litres.",
    steps: [
      { stepNumber: 1, title: "(a) Rate", explanation: "12 km/litre." },
      { stepNumber: 2, title: "(b)-(d)", explanation: "Proportion 8:96::15:180. (c)180km. (d)15L.", result: "12 km/L; proportion verified; 180 km; 15 L." },
    ],
    hint: "Rate = distance ÷ fuel. Then scale up/down using unitary method.",
    keyConcepts: ["fuel efficiency", "proportion in transport"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Dividing fuel by distance instead of distance by fuel for km/litre"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-ics-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "ICSE problem: Two numbers are in the ratio 5:8. If 5 is subtracted from each, the ratio becomes 1:2. Find the original numbers.",
    answer: "Let numbers = 5k and 8k. After subtracting 5: (5k–5):(8k–5)=1:2. Cross multiply: 2(5k–5)=1(8k–5) → 10k–10=8k–5 → 2k=5 → k=2.5. Numbers: 5×2.5=12.5 and 8×2.5=20. Verify: (12.5–5):(20–5)=7.5:15=1:2 ✓.",
    steps: [
      { stepNumber: 1, title: "Set up equation", explanation: "2(5k–5)=8k–5 → 2k=5 → k=2.5." },
      { stepNumber: 2, title: "Find numbers", explanation: "12.5 and 20. Verify: 7.5:15=1:2 ✓.", result: "12.5 and 20." },
    ],
    hint: "Let the numbers be 5k and 8k. After subtracting, set up the new ratio as an equation.",
    keyConcepts: ["ratio with change", "algebraic approach"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Adding 5 instead of subtracting, or not setting up the cross-multiplication correctly"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-ics-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A fort had provisions for 800 soldiers for 30 days. After 6 days, 200 more soldiers arrived. For how many more days will the provisions last?",
    answer: "Provisions consumed in 6 days (800 soldiers): 800×6=4800 soldier-days. Remaining provisions: 800×30–4800=24000–4800=19200 soldier-days. New total soldiers: 800+200=1000. Days remaining: 19200÷1000=19.2 days.",
    steps: [
      { stepNumber: 1, title: "Total provisions", explanation: "800×30=24000 soldier-days." },
      { stepNumber: 2, title: "Remaining and new soldiers", explanation: "Used=4800. Remaining=19200. 1000 soldiers: 19200÷1000=19.2 days.", result: "19.2 more days." },
    ],
    hint: "Find total provisions as 'soldier-days', subtract what's been used, divide by new number of soldiers.",
    keyConcepts: ["provisions problem", "inverse proportion"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Not accounting for the 6 days already passed before more soldiers arrived"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-ics-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Design a proportion problem that uses the numbers 6, 9, and 16. Find the fourth proportional. Verify.",
    answer: "Problem: 'What fourth number d makes 6, 9, 16, d a proportion?' Using a:b::c:d → 6:9::16:d → 6d=9×16=144 → d=24. So 6:9::16:24. Verify: 6×24=144=9×16 ✓.",
    steps: [
      { stepNumber: 1, title: "Set up proportion", explanation: "6:9::16:d → d=144÷6=24." },
      { stepNumber: 2, title: "Verify", explanation: "6×24=144=9×16 ✓.", result: "Fourth proportional = 24." },
    ],
    hint: "In a:b::c:d, d = (b×c)/a.",
    keyConcepts: ["fourth proportional", "proportion construction"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Computing d=a×d/b (circular) instead of d=b×c/a"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-6-ch12-cmp-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: The ratio of 500 g to 2 kg is 1 : 4.",
    answer: "True. Convert to same unit: 2 kg = 2000 g. Ratio = 500 : 2000 = 1 : 4 (÷500). ✓",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "2 kg = 2000 g. 500:2000 = 1:4 ✓." },
    ],
    hint: "Always convert to the same unit before finding the ratio.",
    keyConcepts: ["unit conversion in ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Writing ratio as 500:2 without unit conversion"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: If the ratio of boys to girls in a class is 3 : 4, then girls are more than boys.",
    answer: "True. Ratio 3:4 means for every 3 boys, there are 4 girls. Since 4 > 3, there are more girls. (e.g., if there are 21 boys, there are 28 girls.)",
    steps: [
      { stepNumber: 1, title: "Interpret the ratio", explanation: "3:4 → girls:boys = 4:3 → girls > boys." },
    ],
    hint: "The larger ratio term corresponds to the larger group.",
    keyConcepts: ["interpreting ratios"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Thinking 3 boys:4 girls means boys are more because boys are 'first'"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A length of ribbon is cut into two pieces in the ratio 3 : 7. The shorter piece is 24 cm. Find the total length.",
    answer: "Shorter piece corresponds to ratio term 3. If 3 parts = 24 cm, then 1 part = 8 cm. Total parts = 3+7=10. Total length = 10×8 = 80 cm.",
    steps: [
      { stepNumber: 1, title: "Find value of one part", explanation: "3 parts=24 cm → 1 part=8 cm." },
      { stepNumber: 2, title: "Total", explanation: "10 parts = 80 cm.", result: "Total = 80 cm." },
    ],
    hint: "Find the value of one 'part' using the given piece, then multiply by total parts.",
    keyConcepts: ["ratio division", "finding total from part"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Adding 24+7=31 (not using ratio correctly)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A recipe for 4 servings needs 3 cups of flour and 2 cups of sugar. Scale up for 10 servings.",
    answer: "Scale factor = 10/4 = 2.5. Flour = 3×2.5 = 7.5 cups. Sugar = 2×2.5 = 5 cups.",
    steps: [
      { stepNumber: 1, title: "Scale factor", explanation: "10÷4=2.5." },
      { stepNumber: 2, title: "Scale each", explanation: "Flour=7.5 cups; Sugar=5 cups.", result: "7.5 cups flour, 5 cups sugar." },
    ],
    hint: "Multiply each ingredient by (required servings ÷ original servings).",
    keyConcepts: ["scaling ratio", "real-world proportion"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Adding 6 more portions' worth instead of using multiplicative scaling"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: 8 : 12 is the same ratio as 12 : 8.",
    answer: "False. 8:12 = 2:3 (simplified) and 12:8 = 3:2. They are different ratios — 8:12 means 8 parts to 12, while 12:8 reverses the comparison. Order matters in a ratio.",
    steps: [
      { stepNumber: 1, title: "Simplify both", explanation: "8:12=2:3. 12:8=3:2. Different." },
    ],
    hint: "Ratio is ordered. a:b ≠ b:a unless a = b.",
    keyConcepts: ["order in ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Saying they are equal because they use the same numbers"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Raju earns ₹24,000 and spends in the ratio Food:Rent:Savings = 3:4:5. Find his monthly savings. If his salary increases by 20%, but spending pattern stays same, find new savings.",
    answer: "Total parts=12. Savings=5/12×24000=₹10000. New salary=24000×1.2=₹28800. New savings=5/12×28800=₹12000.",
    steps: [
      { stepNumber: 1, title: "Original savings", explanation: "5/12×24000=10000." },
      { stepNumber: 2, title: "After 20% raise", explanation: "28800×5/12=12000.", result: "₹10000 → ₹12000." },
    ],
    hint: "Apply the same ratio to the new total salary.",
    keyConcepts: ["ratio division", "percentage increase"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Adding ₹4000 directly instead of applying the ratio to the new salary"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The angles of a triangle are in ratio 2:3:4. Find each angle. What type of triangle is it?",
    answer: "Sum of angles = 180°. Parts = 2+3+4=9. Each part = 180÷9=20°. Angles: 40°, 60°, 80°. All angles are acute (< 90°), so it is an ACUTE-ANGLED triangle.",
    steps: [
      { stepNumber: 1, title: "Find each angle", explanation: "2×20=40°; 3×20=60°; 4×20=80°." },
      { stepNumber: 2, title: "Classify", explanation: "All angles < 90° → acute-angled.", result: "40°, 60°, 80° — acute triangle." },
    ],
    hint: "Total angle sum = 180°. Divide by total parts to find value per part.",
    keyConcepts: ["ratio in geometry", "triangle angles"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Setting each part to 180÷3=60 (not using ratio correctly)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "If A:B = 2:3 and B:C = 4:5, what is A:B:C?\n(A) 8:12:15  (B) 2:4:5  (C) 6:9:15  (D) 2:3:5",
    answer: "A. B must be the LCM-compatible value. A:B=2:3 and B:C=4:5. Make B common: multiply first by 4 and second by 3: A:B=8:12 and B:C=12:15. So A:B:C=8:12:15.",
    steps: [
      { stepNumber: 1, title: "Make B common", explanation: "A:B=2:3=8:12. B:C=4:5=12:15." },
      { stepNumber: 2, title: "Combine", explanation: "A:B:C=8:12:15.", result: "A." },
    ],
    hint: "Find the LCM of the B values (3 and 4) to make B common in both ratios.",
    keyConcepts: ["chained ratios", "combining two ratios"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Simply writing 2:3:5 by concatenating without making B common"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: If 2 : 3 :: 4 : 6, then 3 : 2 :: 6 : 4 is also true.",
    answer: "True. This is the invertendo property: if a:b::c:d, then b:a::d:c. Check: 3×4=12=2×6 ✓.",
    steps: [
      { stepNumber: 1, title: "Apply invertendo", explanation: "Swap each term in each ratio. 3:2::6:4. Cross check: 3×4=12=2×6 ✓." },
    ],
    hint: "Invertendo: flip both ratios simultaneously.",
    keyConcepts: ["invertendo property"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Flipping only one ratio: e.g., 3:2::4:6"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A photocopy machine makes 60 copies in 3 minutes. How long does it take to make 200 copies? (Use proportion.)",
    answer: "60 copies : 3 minutes :: 200 copies : x minutes. Cross multiply: 60x = 200×3 = 600. x = 10 minutes.",
    steps: [
      { stepNumber: 1, title: "Set up proportion", explanation: "60:3::200:x → 60x=600." },
      { stepNumber: 2, title: "Solve", explanation: "x=10 minutes.", result: "10 minutes." },
    ],
    hint: "Set up as 60:3::200:x and cross multiply.",
    keyConcepts: ["proportion in real-world setting"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Setting up proportion as 60:200::3:x (inverted)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.FREQUENTLY_ASKED],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Analyse: Is the relationship 'distance travelled' and 'time taken' (at constant speed) a direct proportion or inverse proportion? Show with data: distance 60, 120, 180 km at times 1, 2, 3 hours.",
    answer: "Direct proportion: as distance increases, time increases in the same ratio. Data: 60/1=60; 120/2=60; 180/3=60. The ratio distance:time is constant (=60 km/hr). This confirms direct proportion. If distance doubles, time doubles. Proportion statement: 60:1::120:2::180:3.",
    steps: [
      { stepNumber: 1, title: "Check ratio constancy", explanation: "60/1=120/2=180/3=60. Constant → direct proportion." },
      { stepNumber: 2, title: "State conclusion", explanation: "Direct proportion. Speed = constant.", result: "Direct proportion confirmed." },
    ],
    hint: "In direct proportion, ratio of corresponding values is constant.",
    keyConcepts: ["direct proportion", "constant ratio", "speed-distance-time"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Saying it's inverse because 'more distance takes more time' (this is direct, not inverse)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "If 15 men can build a wall in 12 days, how many men are needed to build it in 9 days?\n(A) 18  (B) 20  (C) 25  (D) 16",
    answer: "B. Inverse proportion: more men → fewer days. 15×12=180 man-days total. Men needed = 180÷9=20.",
    steps: [
      { stepNumber: 1, title: "Total work", explanation: "15×12=180 man-days." },
      { stepNumber: 2, title: "Divide by new days", explanation: "180÷9=20 men.", result: "20 men." },
    ],
    hint: "This is inverse proportion. Total work (man-days) is constant.",
    keyConcepts: ["inverse proportion", "work problems"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Using direct proportion: 15:12::?:9 giving 11.25 men (wrong)"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-013",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A train travels 360 km in 4 hours. At the same speed, which proportion gives the time for 540 km?\n(A) 360:4::540:t → t=6  (B) 4:360::t:540 → t=6  (C) Both A and B  (D) Neither",
    answer: "C. (A) 360:4::540:t → 360t=4×540=2160 → t=6. ✓ (B) 4:360::t:540 → 540×4=360t → t=6. ✓ Both proportions are equivalent re-arrangements and give t=6 hours.",
    steps: [
      { stepNumber: 1, title: "Verify A", explanation: "360t=2160 → t=6 ✓." },
      { stepNumber: 2, title: "Verify B", explanation: "360t=2160 → t=6 ✓. Same equation.", result: "C — both give t=6." },
    ],
    hint: "Both proportions represent the same underlying ratio relationship.",
    keyConcepts: ["equivalent proportion arrangements"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Accepting only one form as valid"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-014",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 4,
    question: "₹1,500 is to be shared between A and B so that for every ₹2 A gets, B gets ₹3. Which equation correctly gives A's share (a)?\n(A) a/1500=2/5  (B) a=(2/3)×1500  (C) a+a×(3/2)=1500  (D) A and C",
    answer: "D. (A) a/1500=2/5 → a=600 ✓. (C) a+1.5a=2.5a=1500 → a=600 ✓. (B) gives a=1000 (wrong). So A and C both correctly give a=600.",
    steps: [
      { stepNumber: 1, title: "Check A", explanation: "2/5×1500=600 ✓." },
      { stepNumber: 2, title: "Check B and C", explanation: "B: 2/3×1500=1000 ✗. C: 2.5a=1500 → a=600 ✓.", result: "D." },
    ],
    hint: "Total parts = 2+3=5. A's share = 2/5 of total.",
    keyConcepts: ["sharing in ratio", "setting up equation"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Using 2/3 instead of 2/5 for A's fraction (using B's ratio term as denominator)"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-015",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 2, estimatedTimeMinutes: 4,
    question: "If 5 kg of apples cost ₹200, which is the correct unitary method sequence?\n(A) ÷5 then ×3 for 3 kg  (B) ×3 then ÷5 for 3 kg  (C) ÷200 then ×3  (D) both A and B",
    answer: "D. Both A and B give the correct result. (A) 200÷5=40 per kg, then 40×3=₹120. (B) 200×3=600, then 600÷5=₹120. Same answer. The unitary method (A) is the standard approach, but multiplying first and then dividing also works.",
    steps: [
      { stepNumber: 1, title: "Check A", explanation: "40×3=120 ✓." },
      { stepNumber: 2, title: "Check B", explanation: "600÷5=120 ✓. Both give 120.", result: "D." },
    ],
    hint: "Both orders of operation (÷5 then ×3, or ×3 then ÷5) give the same final result.",
    keyConcepts: ["unitary method", "order of operations"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Thinking only one sequence is valid"],
    tags: [STANDARD_TAGS.TRICKY, STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-cmp-016",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A mixture of 60 litres contains milk and water in ratio 7:3. How much water must be added to make the ratio 7:5?",
    answer: "Original: Milk=7/10×60=42L; Water=3/10×60=18L. New ratio 7:5 means milk:water=7:5. Milk stays 42L. Required water = 42×5/7 = 30L. Water to add = 30–18 = 12 litres.",
    steps: [
      { stepNumber: 1, title: "Find original quantities", explanation: "Milk=42L, Water=18L." },
      { stepNumber: 2, title: "Find required water", explanation: "42×5/7=30L. Add=30–18=12L.", result: "Add 12 litres of water." },
    ],
    hint: "Milk quantity stays fixed. Find required water from new ratio, then subtract existing water.",
    keyConcepts: ["mixture problem", "changing ratio"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Changing both milk and water instead of keeping milk fixed"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-6-ch12-hot-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Show that if a:b = c:d, then (a+b):b = (c+d):d (componendo property). Verify with 2:3::8:12.",
    answer: "Proof: If a/b=c/d, then a/b+1=c/d+1 → (a+b)/b = (c+d)/d. Verification: 2:3::8:12 → a/b=2/3; c/d=8/12=2/3. ✓ Componendo: (2+3):3=5:3; (8+12):12=20:12=5:3. ✓ Both equal 5:3.",
    steps: [
      { stepNumber: 1, title: "Proof", explanation: "Add 1 to both sides of a/b=c/d: (a+b)/b=(c+d)/d." },
      { stepNumber: 2, title: "Verify", explanation: "5:3=5:3 ✓.", result: "Componendo verified." },
    ],
    hint: "Add 1 to both sides of the proportion equation a/b = c/d.",
    keyConcepts: ["componendo property", "algebraic proof of proportion"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Adding 1 to only one side of the equation"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Gold alloy is made by mixing gold and copper. Alloy A: 3 parts gold : 1 part copper. Alloy B: 5 parts gold : 2 parts copper. Which alloy has a higher proportion of gold? Show working.",
    answer: "Alloy A: Gold fraction = 3/4 = 0.75. Alloy B: Gold fraction = 5/7 ≈ 0.714. Since 3/4 > 5/7 (check: 3×7=21 > 5×4=20), Alloy A has a higher proportion of gold.",
    steps: [
      { stepNumber: 1, title: "Compute gold fraction", explanation: "A=3/4; B=5/7." },
      { stepNumber: 2, title: "Compare", explanation: "3×7=21 > 5×4=20 → A>B.", result: "Alloy A has more gold." },
    ],
    hint: "Compare fractions by cross multiplication.",
    keyConcepts: ["comparing ratios", "fraction comparison"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Comparing numerators directly (3 vs 5) without accounting for different denominators"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "The ages of father and son are in ratio 7:2. In 10 years, the ratio will be 9:4. Find their current ages.",
    answer: "Current ages: father=7k, son=2k. After 10 years: (7k+10):(2k+10)=9:4. Cross multiply: 4(7k+10)=9(2k+10) → 28k+40=18k+90 → 10k=50 → k=5. Father=35, Son=10. Check in 10 years: 45:20=9:4 ✓.",
    steps: [
      { stepNumber: 1, title: "Set up equation", explanation: "4(7k+10)=9(2k+10) → 10k=50 → k=5." },
      { stepNumber: 2, title: "Find ages and verify", explanation: "Father=35, Son=10. Future: 45:20=9:4 ✓.", result: "Father=35, Son=10." },
    ],
    hint: "In 10 years, both ages increase by 10. Set up cross-multiplication with future ages.",
    keyConcepts: ["age problems with ratio", "future ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Adding 10 only to one person's age"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A town uses electricity and solar energy in ratio 5:2. If the town wants to reduce electricity to 40% and increase solar to 60% of total energy, by what factor must solar energy production increase?",
    answer: "Current solar fraction = 2/7. Target solar fraction = 60%=3/5. Scale factor = (3/5)÷(2/7) = (3/5)×(7/2) = 21/10 = 2.1. Solar must increase by factor 2.1 (a 110% increase).",
    steps: [
      { stepNumber: 1, title: "Current solar fraction", explanation: "2/(5+2)=2/7." },
      { stepNumber: 2, title: "Scale factor", explanation: "(3/5)÷(2/7)=21/10=2.1.", result: "Solar must increase by factor 2.1." },
    ],
    hint: "Compare current solar fraction with target fraction to find scale factor.",
    keyConcepts: ["ratio in real-world policy", "scaling fractions"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Comparing ratio terms instead of fractions of total"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Three pipes can fill a tank in 4, 6, and 12 hours respectively. If all three are opened together, how long to fill the tank? (Use unitary method and proportional reasoning.)",
    answer: "In 1 hour: Pipe A fills 1/4, Pipe B fills 1/6, Pipe C fills 1/12. Together: 1/4+1/6+1/12 = 3/12+2/12+1/12 = 6/12 = 1/2. They fill 1/2 tank per hour. Time = 2 hours.",
    steps: [
      { stepNumber: 1, title: "Rates", explanation: "1/4+1/6+1/12=6/12=1/2 tank/hour." },
      { stepNumber: 2, title: "Time", explanation: "1÷(1/2)=2 hours.", result: "2 hours." },
    ],
    hint: "Find fraction filled per hour by each pipe, add them, then find reciprocal for time.",
    keyConcepts: ["pipe and cistern", "adding unit rates"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Adding the hours (4+6+12=22) instead of the rates"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A bus travels from A to B in 4 hours at 60 km/hr. On the return journey, it travels at 40 km/hr. Find the average speed for the whole journey. Is average speed = (60+40)/2? Explain.",
    answer: "Distance A to B = 60×4=240 km. Return at 40 km/hr: time = 240÷40=6 hours. Total distance = 480 km. Total time = 10 hours. Average speed = 480÷10=48 km/hr. (60+40)/2=50 ≠ 48. The simple average is wrong because equal distances, not equal times, are covered. The correct formula for equal distances: avg speed = 2uv/(u+v) = 2×60×40/100=48 km/hr.",
    steps: [
      { stepNumber: 1, title: "Compute times and total", explanation: "Total distance=480, total time=10h." },
      { stepNumber: 2, title: "Average speed", explanation: "480÷10=48≠50.", result: "Average speed = 48 km/hr, not 50." },
    ],
    hint: "Average speed = total distance ÷ total time. Don't average the speeds directly.",
    keyConcepts: ["average speed", "harmonic mean concept"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Averaging speeds directly: (60+40)/2=50 instead of using total distance÷total time"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Design a problem where ratios change when a quantity is added. Show that adding the same quantity to both terms of a ratio changes it, with a counterexample where adding makes two different ratios equal.",
    answer: "Example 1 (ratio changes): Start with 1:2. Add 1 to each: 2:3. 1:2 ≠ 2:3 (different ratios). Example 2 (making equal): 1:3 and 2:3 are different. Add 1 to each: 2:4=1:2 and 3:4. Still different. Actually finding an addition that equalises two ratios: 1:2 and 3:4 — add 5 to each: 6:7 and 8:9. Different. Conclusion: Adding the same constant ALWAYS changes a ratio (unless ratio is 1:1). Adding to make two specific ratios equal requires solving a:b+k :: c:d+k = 1 which has unique solutions.",
    steps: [
      { stepNumber: 1, title: "Show ratio changes", explanation: "1:2 → add 1 → 2:3. Different ratio." },
      { stepNumber: 2, title: "Analyse when equal", explanation: "Ratios a:b and c:d become equal after adding k when (a+k)/(b+k)=(c+k)/(d+k).", result: "Adding constant always changes ratio unless a:b=1:1." },
    ],
    hint: "The ratio 1:1 is invariant under adding the same number (3:3=1:1 for any k).",
    keyConcepts: ["effect of constant addition on ratio", "ratio invariance"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Assuming adding the same number to both terms preserves the ratio (only true if ratio is 1:1)"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Create a multi-step unitary method problem involving currency exchange. 1 USD = ₹84. A tourist has $250. She spends ₹12,000 and converts the rest back to USD. How many USD does she recover?",
    answer: "Initial: $250 = 250×84 = ₹21,000. Spent: ₹12,000. Remaining: ₹21,000–₹12,000 = ₹9,000. Convert back: ₹9,000 ÷ 84 = 107.14 USD ≈ $107.14.",
    steps: [
      { stepNumber: 1, title: "Convert to rupees", explanation: "250×84=21000." },
      { stepNumber: 2, title: "Subtract and convert back", explanation: "9000÷84≈107.14 USD.", result: "≈$107.14 recovered." },
    ],
    hint: "Step 1: USD → INR. Step 2: Spend. Step 3: INR → USD.",
    keyConcepts: ["multi-step unitary method", "currency exchange"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Converting ₹12,000 back instead of the remaining amount"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topionName: "Proportion",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A farmer mixes two types of fertilisers costing ₹40/kg and ₹60/kg to get a mixture costing ₹50/kg. In what ratio must he mix them?",
    answer: "Using alligation: Cheaper price 40, dearer price 60, mean price 50. Parts of cheaper = 60–50=10. Parts of dearer = 50–40=10. Ratio = 10:10 = 1:1. Verify: (40×1+60×1)/(1+1) = 100/2 = ₹50/kg ✓.",
    steps: [
      { stepNumber: 1, title: "Apply alligation/unitary", explanation: "Parts cheaper=60–50=10; parts dearer=50–40=10." },
      { stepNumber: 2, title: "Ratio", explanation: "10:10=1:1. Verify: avg=50 ✓.", result: "Mix in ratio 1:1." },
    ],
    hint: "Use the rule of alligation: dearer excess : cheaper excess = cheaper parts : dearer parts.",
    keyConcepts: ["alligation", "mixture problem"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Reversing the ratio: dearer parts with dearer price"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Two taps fill a tank in 10 and 15 hours. A drain pipe empties it in 20 hours. If all three are open, when will the tank fill?",
    answer: "In 1 hour: Tap A fills 1/10; Tap B fills 1/15; Drain empties 1/20. Net fill rate = 1/10+1/15–1/20. LCM(10,15,20)=60. = 6/60+4/60–3/60 = 7/60. Time = 60/7 ≈ 8.57 hours = 8 hours 34 minutes.",
    steps: [
      { stepNumber: 1, title: "Net rate per hour", explanation: "1/10+1/15–1/20=7/60." },
      { stepNumber: 2, title: "Time", explanation: "60/7 ≈ 8.57 hours.", result: "60/7 hours ≈ 8 hr 34 min." },
    ],
    hint: "Net rate = (filling rates) – (emptying rate). Time = 1 ÷ net rate.",
    keyConcepts: ["pipe and cistern", "combined rates", "net proportion"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Adding all three rates as filling (not subtracting the drain rate)"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-011",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Prove that if a : b :: b : c, then b² = ac (b is the mean proportional). Verify with a=4, b=6, c=9.",
    answer: "If a:b::b:c, then by cross-product: a×c = b×b = b². So b²=ac. Verification: a=4, b=6, c=9. b²=36. ac=4×9=36. ✓ b is the mean proportional between a and c.",
    steps: [
      { stepNumber: 1, title: "Cross-multiply", explanation: "a:b::b:c → ac=b². ✓" },
      { stepNumber: 2, title: "Verify", explanation: "6²=36=4×9 ✓.", result: "b²=ac proved and verified." },
    ],
    hint: "Apply the cross-product rule: product of extremes = product of means.",
    keyConcepts: ["mean proportional", "geometric mean"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Writing b=ac (not squaring b)"],
    tags: [STANDARD_TAGS.HIGHER_ORDER, STANDARD_TAGS.TRICKY],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-hot-012",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Design a 'best buy' problem using the unitary method. A 400 g pack of biscuits costs ₹36 and a 600 g pack costs ₹51. Which is the better value? By how much per 100 g?",
    answer: "400 g pack: ₹36/400g = ₹9/100g. 600 g pack: ₹51/600g = ₹8.50/100g. The 600 g pack is cheaper per 100g (₹8.50 < ₹9). Saving = 9–8.5 = ₹0.50 per 100g.",
    steps: [
      { stepNumber: 1, title: "Cost per 100g each pack", explanation: "400g: 36/4=9; 600g: 51/6=8.5." },
      { stepNumber: 2, title: "Compare and find saving", explanation: "600g pack saves ₹0.50/100g.", result: "600g pack is better value by ₹0.50 per 100g." },
    ],
    hint: "Reduce each to cost per 100g using unitary method.",
    keyConcepts: ["unitary method", "best buy", "comparison"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Comparing total prices instead of per-unit prices"],
    tags: [STANDARD_TAGS.REAL_WORLD, STANDARD_TAGS.HIGHER_ORDER],
    source: "original",
  },

  // ── PREVIOUS YEAR ─────────────────────────────────────────────────────────────

  {
    id: "bo-mth-6-ch12-pyq-001",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "[PYQ] The ratio 18 : 30 in simplest form is:\n(A) 9:15  (B) 3:5  (C) 6:10  (D) 9:5",
    answer: "B. HCF(18,30)=6. 18÷6:30÷6=3:5.",
    steps: [{ stepNumber: 1, title: "Simplify", explanation: "HCF=6. 3:5." }],
    hint: "Find HCF and divide both terms.",
    keyConcepts: ["simplest form of ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Choosing A (dividing by 2 only)"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-002",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "[PYQ] A sum of ₹560 is divided in ratio 3:4. The smaller share is:\n(A) ₹160  (B) ₹240  (C) ₹320  (D) ₹280",
    answer: "B. Total parts=7. Smaller=3/7×560=₹240.",
    steps: [{ stepNumber: 1, title: "Compute", explanation: "3/7×560=240." }],
    hint: "Smaller share corresponds to the smaller ratio term (3).",
    keyConcepts: ["dividing in ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Dividing 560 by 3+4=7 and multiplying by 4 (getting the larger share)"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-003",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "[PYQ] Which of the following is in proportion?\n(A) 2, 3, 5, 6  (B) 1, 2, 4, 8  (C) 3, 6, 9, 12  (D) 5, 10, 15, 25",
    answer: "B. 1×8=8=2×4 ✓. (A) 2×6=12≠3×5=15. (C) 3×12=36=6×9 ✓. Both B and C actually work. Standard answer is B. Accept B or C.",
    steps: [{ stepNumber: 1, title: "Check cross products", explanation: "(B)1×8=8=2×4 ✓. (C)3×12=36=6×9 ✓." }],
    hint: "Product of extremes = product of means.",
    keyConcepts: ["proportion check"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Not performing the cross-multiplication test"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-004",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "[PYQ] If 3 m of cloth costs ₹120, the cost of 8 m is:\n(A) ₹360  (B) ₹320  (C) ₹280  (D) ₹400",
    answer: "B. 1m=₹40. 8m=8×40=₹320.",
    steps: [{ stepNumber: 1, title: "Unitary method", explanation: "120÷3=40. 8×40=320." }],
    hint: "Find cost of 1m first.",
    keyConcepts: ["unitary method"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["Multiplying 120×8 = 960 (forgetting to divide first)"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-005",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "[PYQ] Fill in: (a) Ratio of 45 min to 1 hour (in same unit) = __ : __. (b) If 6 : ? :: 9 : 12, then ? = __.",
    answer: "(a) 45 min : 60 min = 3:4 (HCF=15). (b) 6×12=9×? → ?=72÷9=8.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "45:60÷15=3:4." },
      { stepNumber: 2, title: "(b)", explanation: "6×12=72=9×? → ?=8.", result: "3:4; 8." },
    ],
    hint: "For (a): convert 1 hour to minutes. For (b): cross-multiply.",
    keyConcepts: ["ratio with unit conversion", "missing term"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Writing 45:1 for (a) without converting to same unit"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-006",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "[PYQ] Fill in: (a) If 12 eggs cost ₹60, then 20 eggs cost ₹__. (b) In 5:6::15:__, the missing term is __.",
    answer: "(a) ₹100 (1 egg=₹5; 20×5=100). (b) 5×?=6×15=90 → ?=18.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "60÷12=5; 20×5=100." },
      { stepNumber: 2, title: "(b)", explanation: "5×?=90 → ?=18.", result: "₹100; 18." },
    ],
    hint: "For (a): unitary method. For (b): cross-multiply.",
    keyConcepts: ["unitary method", "proportion missing term"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Multiplying 60×20 and dividing by 12 (roundabout — still correct but not standard unitary method)"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-007",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "[PYQ] Fill in: (a) If 18 men do a job in 15 days, then 10 men need __ days. (b) Speed and time are in __ proportion.",
    answer: "(a) 18×15=270 man-days. 270÷10=27 days. (b) inverse (more speed → less time for same distance).",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "270÷10=27 days." },
      { stepNumber: 2, title: "(b)", explanation: "Speed and time are inversely proportional.", result: "27; inverse." },
    ],
    hint: "For (a): total work is constant. For (b): think about what happens to time when speed increases.",
    keyConcepts: ["inverse proportion", "types of proportion"],
    conceptsCovered: ["mth:6:ch12:unitary-method"],
    prerequisites: [],
    commonErrors: ["(b) answering 'direct' because both are increasing quantities"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-008",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "[PYQ] Fill in: (a) The ratio of 30 paise to ₹2 = __ : __. (b) ₹800 divided in ratio 3:5, the larger share = ₹__.",
    answer: "(a) 30 paise : 200 paise = 3:20. (b) 5/8×800=₹500.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "₹2=200 paise. 30:200=3:20." },
      { stepNumber: 2, title: "(b)", explanation: "5/8×800=500.", result: "3:20; ₹500." },
    ],
    hint: "Convert rupees to paise before forming ratio.",
    keyConcepts: ["ratio with unit conversion", "dividing in ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-definition"],
    prerequisites: [],
    commonErrors: ["Writing 30:2 without converting to same unit"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-009",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t2", topicName: "Proportion",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "[PYQ] Fill in: (a) 4 : 5 :: 12 : __ (b) __ : 6 :: 10 : 15.",
    answer: "(a) 4×?=5×12=60 → ?=15. (b) ?×15=6×10=60 → ?=4.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "4×?=60 → ?=15." },
      { stepNumber: 2, title: "(b)", explanation: "?×15=60 → ?=4.", result: "15; 4." },
    ],
    hint: "Product of extremes = product of means.",
    keyConcepts: ["missing term in proportion"],
    conceptsCovered: ["mth:6:ch12:proportion-definition"],
    prerequisites: [],
    commonErrors: ["Reversing which pair to multiply for the cross-product"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

  {
    id: "bo-mth-6-ch12-pyq-010",
    schemaVersion: 2, classNum: 6, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Ratio and Proportion",
    topicId: "t1", topicName: "Ratio",
    questionType: "previous-year", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 2,
    question: "[PYQ] Fill in: (a) Ratio of 1 hour to 20 minutes = __ : __. (b) If P:Q=2:3 and Q:R=3:4, then P:R=__:__.",
    answer: "(a) 60 min : 20 min = 3:1. (b) P:Q:R=2:3:4 (since Q=3 matches). P:R=2:4=1:2.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "1 hr=60 min. 60:20=3:1." },
      { stepNumber: 2, title: "(b)", explanation: "Q=3 links both: P:Q=2:3, Q:R=3:4. P:R=2:4=1:2.", result: "3:1; 1:2." },
    ],
    hint: "For (b), since Q=3 in both, use P:Q:R=2:3:4.",
    keyConcepts: ["compound ratio", "unit conversion in ratio"],
    conceptsCovered: ["mth:6:ch12:ratio-in-simplest-form"],
    prerequisites: [],
    commonErrors: ["Not simplifying P:R=2:4 to 1:2"],
    tags: [STANDARD_TAGS.FREQUENTLY_ASKED, STANDARD_TAGS.BOARD_IMPORTANT],
    source: "original",
  },

];
