/**
 * Generate canonical chapter registry for browser/frontend consumption.
 *
 * Reads the single maintained source (canonicalCurriculum.ts / INTERNAL_TO_CANONICAL)
 * and writes two outputs:
 *
 *   1. artifacts/homework-hero/src/data/questions/canonicalChapterRegistry.gen.ts
 *      — Browser-safe TypeScript module; imported by v2adapter.ts and other
 *        frontend consumers. DO NOT edit this file manually.
 *
 *   2. curriculum/generated/canonical-registry-checksum.json
 *      — Compact JSON used by curriculumGateway.ts (F11) to detect stale output.
 *
 * Usage:
 *   pnpm --filter @workspace/scripts run generate-canonical-registry
 *
 * Must be run after every change to scripts/src/canonicalCurriculum.ts.
 */

import { writeFileSync } from "fs";
import { resolve }       from "path";
import { createHash }    from "crypto";
import { getRawRegistryEntries } from "./canonicalCurriculum";

const ROOT        = resolve(import.meta.dirname, "../../");
const FRONTEND_OUT = resolve(ROOT, "artifacts/homework-hero/src/data/questions/canonicalChapterRegistry.gen.ts");
const CHECKSUM_OUT = resolve(ROOT, "curriculum/generated/canonical-registry-checksum.json");

function run(): void {
  const entries = getRawRegistryEntries();

  // Deterministic sort for stable output (and stable checksum).
  entries.sort((a, b) => a.internalId.localeCompare(b.internalId));

  // ── Checksum — computed from the compact 4-field form stored in the JSON ──
  // The gateway re-derives the same compact form; both must match exactly.
  const compactEntries = entries.map(e => ({
    internalId:         e.internalId,
    canonicalChapterId: e.canonicalChapterId,
    status:             e.status,
    displayOrder:       e.displayOrder,
  }));
  const checksum = createHash("sha256").update(JSON.stringify(compactEntries)).digest("hex").slice(0, 16);

  // ── Build TypeScript file content ──────────────────────────────────────────
  const lines: string[] = [
    `// @generated — DO NOT EDIT MANUALLY.`,
    `// Source of truth: scripts/src/canonicalCurriculum.ts`,
    `// Regenerate    : pnpm --filter @workspace/scripts run generate-canonical-registry`,
    `// Checksum      : ${checksum}`,
    ``,
    `import type { CurriculumStatus } from "./types";`,
    ``,
    `export interface CanonicalRegistryEntry {`,
    `  /** Official NCERT/board book code. null when SOURCE_UNRESOLVED or SOURCE_PENDING. */`,
    `  canonicalChapterId: string | null;`,
    `  curriculumStatus:   CurriculumStatus;`,
    `  subjectId:          string;`,
    `  classId:            number;`,
    `  boardId:            string;`,
    `  /** Student-facing 1-based ordinal position within the subject group. */`,
    `  displayOrder:       number;`,
    `}`,
    ``,
    `/**`,
    ` * Canonical chapter registry — the single browser-safe source of canonical IDs.`,
    ` * Generated from scripts/src/canonicalCurriculum.ts. DO NOT add entries here.`,
    ` */`,
    `export const CANONICAL_CHAPTER_REGISTRY: Readonly<Record<string, CanonicalRegistryEntry>> = {`,
  ];

  for (const e of entries) {
    const cid = e.canonicalChapterId === null ? "null" : `"${e.canonicalChapterId}"`;
    lines.push(
      `  "${e.internalId}": { canonicalChapterId: ${cid}, curriculumStatus: "${e.status}", subjectId: "${e.subjectId}", classId: ${e.classId}, boardId: "${e.boardId}", displayOrder: ${e.displayOrder} },`,
    );
  }

  lines.push(`} as const;`);
  lines.push(``);
  lines.push(`/** Look up the canonical registry entry for a question-bank internal chapter ID. */`);
  lines.push(`export function lookupCanonical(internalId: string): CanonicalRegistryEntry | undefined {`);
  lines.push(`  return CANONICAL_CHAPTER_REGISTRY[internalId];`);
  lines.push(`}`);
  lines.push(``);

  // ── CLASS9_DISPLAY_ORDER — single source of chapter ordering for Class 9 ──
  // Replaces manually maintained SCIENCE_DISPLAY_ORDER_CLASS9 and
  // MATHS_DISPLAY_ORDER_CLASS9 in questionService.ts.
  lines.push(`/**`);
  lines.push(` * Student-facing display order for all Class 9 chapters.`);
  lines.push(` * Maps internalId → 1-based ordinal position within its subject group.`);
  lines.push(` * Generated from scripts/src/canonicalCurriculum.ts. DO NOT edit manually.`);
  lines.push(` */`);
  lines.push(`export const CLASS9_DISPLAY_ORDER: Readonly<Record<string, number>> = {`);

  // Emit only Class 9 ACTIVE entries — SOURCE_UNRESOLVED chapters are excluded
  // from the student-facing display sequence, sorted by subjectId then displayOrder.
  const class9 = entries
    .filter(e => e.classId === 9 && e.boardId === "CBSE" && e.status === "ACTIVE")
    .sort((a, b) => a.subjectId.localeCompare(b.subjectId) || a.displayOrder - b.displayOrder);

  for (const e of class9) {
    lines.push(`  "${e.internalId}": ${e.displayOrder},`);
  }

  lines.push(`} as const;`);
  lines.push(``); // trailing newline

  writeFileSync(FRONTEND_OUT, lines.join("\n"), "utf8");
  console.log(`✓ Wrote ${FRONTEND_OUT.replace(ROOT + "/", "")}`);

  // ── Checksum file ──────────────────────────────────────────────────────────
  const checksumData = {
    _comment:   "Generated by scripts/src/generateCanonicalRegistry.ts — DO NOT EDIT.",
    checksum,
    entryCount: entries.length,
    entries:    entries.map(e => ({
      internalId:         e.internalId,
      canonicalChapterId: e.canonicalChapterId,
      status:             e.status,
      displayOrder:       e.displayOrder,
    })),
  };
  writeFileSync(CHECKSUM_OUT, JSON.stringify(checksumData, null, 2) + "\n", "utf8");
  console.log(`✓ Wrote ${CHECKSUM_OUT.replace(ROOT + "/", "")}`);
  console.log(`  Checksum : ${checksum}`);
  console.log(`  Entries  : ${entries.length}`);
}

run();
