/**
 * DailyFocus — "Today's Focus" card for the Home page.
 *
 * Shows the top 3 AI-recommended topics for the day with:
 *   • Priority rank badge (1 / 2 / 3)
 *   • Subject colour chip
 *   • Recommended difficulty tier
 *   • Human-readable reason
 *   • Mastery progress bar
 *
 * Recommendations are generated by useAdaptiveLearning and updated daily.
 */

import { Link } from "wouter";
import { SUBJECTS } from "@/data/subjects";
import { useAdaptiveLearning } from "@/hooks/useAdaptiveLearning";
import type { DailyRecommendation, RecommendedTier } from "@/hooks/useAdaptiveLearning";

// ─── Style maps ───────────────────────────────────────────────────────────────

const TIER_STYLE: Record<RecommendedTier, string> = {
  Easy:      "bg-emerald-50 text-emerald-700 border-emerald-200",
  Medium:    "bg-amber-50   text-amber-700   border-amber-200",
  Hard:      "bg-red-50     text-red-700     border-red-200",
  Challenge: "bg-purple-50  text-purple-700  border-purple-200",
};

const TIER_LABEL: Record<RecommendedTier, string> = {
  Easy:      "Easy",
  Medium:    "Medium",
  Hard:      "Hard",
  Challenge: "⚡ Challenge",
};

const PRIORITY_STYLE = [
  { badge: "bg-red-100 text-red-600",      bar: "bg-red-400",     border: "border-l-red-400"    },
  { badge: "bg-amber-100 text-amber-600",  bar: "bg-amber-400",   border: "border-l-amber-400"  },
  { badge: "bg-indigo-100 text-indigo-600", bar: "bg-indigo-400", border: "border-l-indigo-400" },
];

// ─── Sub-components ───────────────────────────────────────────────────────────

function SubjectChip({ subject }: { subject: string }) {
  const cfg = SUBJECTS[subject as keyof typeof SUBJECTS];
  if (!cfg) return null;
  return (
    <span
      className="inline-flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full border"
      style={{ backgroundColor: cfg.light, color: cfg.color, borderColor: cfg.border }}
    >
      {cfg.icon} {subject}
    </span>
  );
}

function RecommendationRow({
  rec,
  index,
}: {
  rec:   DailyRecommendation;
  index: number;
}) {
  const style = PRIORITY_STYLE[index];

  return (
    <Link href="/practice">
      <div
        className={`flex items-center gap-3 px-4 py-3.5 border-l-4 hover:bg-slate-50 active:bg-slate-100 transition-colors cursor-pointer ${style.border}`}
      >
        {/* Priority badge */}
        <div
          className={`w-7 h-7 rounded-full flex items-center justify-center text-xs font-black flex-shrink-0 ${style.badge}`}
        >
          {index + 1}
        </div>

        {/* Main content */}
        <div className="flex-1 min-w-0">
          {/* Chips */}
          <div className="flex items-center gap-1.5 flex-wrap mb-1">
            <SubjectChip subject={rec.subject} />
            <span className={`text-[10px] font-semibold px-2 py-0.5 rounded-full border ${TIER_STYLE[rec.recommendedDifficulty]}`}>
              {TIER_LABEL[rec.recommendedDifficulty]}
            </span>
          </div>

          {/* Topic name */}
          <p className="text-sm font-bold text-slate-800 truncate leading-tight">
            {rec.topic}
          </p>

          {/* Reason */}
          <p className="text-[10px] text-slate-400 mt-0.5 leading-tight">
            {rec.reason}
          </p>

          {/* Mastery bar */}
          <div className="mt-2 flex items-center gap-2">
            <div className="flex-1 h-1.5 bg-slate-100 rounded-full overflow-hidden">
              <div
                className={`h-full rounded-full transition-all duration-700 ${style.bar}`}
                style={{ width: `${rec.masteryScore}%` }}
              />
            </div>
            <span className="text-[10px] font-bold text-slate-500 flex-shrink-0 tabular-nums">
              {rec.masteryScore}%
            </span>
          </div>
        </div>

        {/* Arrow */}
        <svg
          className="w-4 h-4 text-slate-300 flex-shrink-0"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          strokeWidth={2}
        >
          <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
        </svg>
      </div>
    </Link>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────

export default function DailyFocus() {
  const { recommendations } = useAdaptiveLearning();

  const dateLabel = new Date().toLocaleDateString("en-GB", {
    weekday: "short",
    month:   "short",
    day:     "numeric",
  });

  return (
    <div className="bg-white rounded-2xl border border-slate-200 overflow-hidden shadow-sm">

      {/* Header */}
      <div className="px-4 pt-4 pb-3 border-b border-slate-100 flex items-center justify-between">
        <div>
          <h2 className="text-sm font-bold text-slate-800">Today's Focus</h2>
          <p className="text-[11px] text-slate-400 mt-0.5">
            AI-powered · Adaptive · Updates daily
          </p>
        </div>
        <span className="text-[10px] font-medium text-slate-500 bg-slate-100 px-2.5 py-1 rounded-full">
          {dateLabel}
        </span>
      </div>

      {/* Recommendations or onboarding */}
      {recommendations.length > 0 ? (
        <div className="divide-y divide-slate-50">
          {recommendations.map((rec, i) => (
            <RecommendationRow key={`${rec.subject}-${rec.topic}`} rec={rec} index={i} />
          ))}
        </div>
      ) : (
        /* ── Onboarding empty state ── */
        <div className="px-5 py-7 text-center">
          <div className="w-12 h-12 rounded-full bg-indigo-50 border border-indigo-200 flex items-center justify-center mx-auto mb-3">
            <span className="text-xl leading-none">✦</span>
          </div>
          <p className="text-sm font-bold text-slate-700 mb-1">
            No recommendations yet
          </p>
          <p className="text-xs text-slate-400 leading-relaxed mb-4 max-w-xs mx-auto">
            Answer at least 2 questions per topic in Practice to unlock
            personalised AI-powered daily focus areas.
          </p>
          <Link href="/practice">
            <button className="px-5 py-2 rounded-xl bg-indigo-600 text-white text-xs font-semibold shadow-sm active:scale-95 transition-all">
              Start Practising →
            </button>
          </Link>
        </div>
      )}
    </div>
  );
}
