// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 4: Simple Equations
 * GENERATED PROOF FILE — offline deterministic generator.
 *
 * Generator : scripts/src/generateMathQuestionProof.ts
 * Command   : pnpm --filter @workspace/scripts run generate-proof
 *
 * 10 questions — 4 Easy / 4 Medium / 2 Hard
 * Topics: t1 Setting Up Equations (6 q) | t2 Solving and Verifying (4 q)
 * Templates used:
 *   T1 Direct Solve     (gen-001, gen-002, gen-005, gen-006) — ax [+/-] b = c
 *   T2 Word-to-Equation (gen-003, gen-004, gen-007, gen-008) — verbal → equation → solve
 *   T3 MCQ Verification (gen-009, gen-010)                   — identify correct solution
 *
 * Safe variation capacity: T1 ≈ 200+, T2 ≈ 150+, T3 ≈ 40+ per chapter.
 * DO NOT hand-edit. Re-run the generator to modify.
 */

import type { QuestionV2 } from "../../../types";

export const CH04_SIMPLE_EQUATIONS_GENERATED_PROOF: QuestionV2[] = [

  {
    id: "bo-mth-7-ch04-gen-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve for x: x + 7 = 15",
    answer: "x = 8. Verification: LHS = 8 + 7 = 15 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "State the equation", explanation: "Given equation: x + 7 = 15" },
      { stepNumber: 2, title: "Move the constant", explanation: "Subtract 7 from both sides: x = 15 − 7 = 8" },
      { stepNumber: 3, title: "Isolate x", explanation: "x is already isolated: x = 8" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 8: LHS = 8 + 7 = 15 = 15 = RHS ✓" },
    ],
    hint: "Use the balance method: apply the same operation to both sides to isolate x.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the operation to only one side of the equation instead of both."],
    tags: ["computational", "ncert-direct", "class7", "ch04", "solve-equation", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve for x: 3x = 21",
    answer: "x = 7. Verification: LHS = 3 × 7 = 21 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "State the equation", explanation: "Given equation: 3x = 21" },
      { stepNumber: 2, title: "Move the constant", explanation: "Equation is already 3x = 21. Proceed to divide." },
      { stepNumber: 3, title: "Isolate x", explanation: "Divide both sides by 3: x = 21 ÷ 3 = 7" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 7: LHS = 3 × 7 = 21 = 21 = RHS ✓" },
    ],
    hint: "Use the balance method: apply the same operation to both sides to isolate x.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the operation to only one side of the equation instead of both."],
    tags: ["computational", "ncert-direct", "class7", "ch04", "solve-equation", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "8 more than a number is 20. Find the number.",
    answer: "The number is 12. (Equation used: n + 8 = 20, solved to get n = 12.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: n + 8 = 20" },
      { stepNumber: 3, title: "Solve", explanation: "Subtract 8 from both sides: n = 20 − 8 = 12" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute n = 12: 12 + 8 = 20 = 20 ✓" },
    ],
    hint: "First name the unknown as n, write the equation from the sentence, then solve it.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation — misidentifying which quantity is unknown.", "Forgetting to verify the answer in the original word statement."],
    tags: ["conceptual", "real-life", "class7", "ch04", "word-problem", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A number decreased by 6 equals 10. Find the number.",
    answer: "The number is 16. (Equation used: n − 6 = 10, solved to get n = 16.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: n − 6 = 10" },
      { stepNumber: 3, title: "Solve", explanation: "Add 6 to both sides: n = 10 + 6 = 16" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute n = 16: 16 − 6 = 10 = 10 ✓" },
    ],
    hint: "First name the unknown as n, write the equation from the sentence, then solve it.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation — misidentifying which quantity is unknown.", "Forgetting to verify the answer in the original word statement."],
    tags: ["conceptual", "real-life", "class7", "ch04", "word-problem", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 5,
    question: "Solve for x: 2x + 5 = 17",
    answer: "x = 6. Verification: LHS = 2(6) + 5 = 17 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "State the equation", explanation: "Given equation: 2x + 5 = 17" },
      { stepNumber: 2, title: "Move the constant", explanation: "Subtract 5 from both sides: 2x = 17 − 5 = 12" },
      { stepNumber: 3, title: "Isolate x", explanation: "Divide both sides by 2: x = 12 ÷ 2 = 6" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 6: LHS = 2(6) + 5 = 17 = 17 = RHS ✓" },
    ],
    hint: "Use the balance method: apply the same operation to both sides to isolate x.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the operation to only one side of the equation instead of both."],
    tags: ["computational", "ncert-direct", "class7", "ch04", "solve-equation", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 5,
    question: "Solve for x: 3x − 4 = 14",
    answer: "x = 6. Verification: LHS = 3(6) − 4 = 14 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "State the equation", explanation: "Given equation: 3x − 4 = 14" },
      { stepNumber: 2, title: "Move the constant", explanation: "Add 4 to both sides: 3x = 14 + 4 = 18" },
      { stepNumber: 3, title: "Isolate x", explanation: "Divide both sides by 3: x = 18 ÷ 3 = 6" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 6: LHS = 3(6) − 4 = 14 = 14 = RHS ✓" },
    ],
    hint: "Use the balance method: apply the same operation to both sides to isolate x.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the operation to only one side of the equation instead of both."],
    tags: ["computational", "ncert-direct", "class7", "ch04", "solve-equation", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 6,
    question: "Twice a number, increased by 3, equals 19. Find the number.",
    answer: "The number is 8. (Equation used: 2n + 3 = 19, solved to get n = 8.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: 2n + 3 = 19" },
      { stepNumber: 3, title: "Move the constant", explanation: "Subtract 3 from both sides: 2n = 19 − 3 = 16" },
      { stepNumber: 4, title: "Divide to find n", explanation: "Divide both sides by 2: n = 16 ÷ 2 = 8" },
      { stepNumber: 5, title: "Verify", explanation: "Substitute n = 8: 2(8) + 3 = 16 + 3 = 19 = 19 ✓" },
    ],
    hint: "First name the unknown as n, write the equation from the sentence, then solve it.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation — misidentifying which quantity is unknown.", "Forgetting to verify the answer in the original word statement."],
    tags: ["conceptual", "real-life", "class7", "ch04", "word-problem", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 6,
    question: "Three times a number, decreased by 7, equals 11. Find the number.",
    answer: "The number is 6. (Equation used: 3n − 7 = 11, solved to get n = 6.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: 3n − 7 = 11" },
      { stepNumber: 3, title: "Move the constant", explanation: "Add 7 to both sides: 3n = 11 + 7 = 18" },
      { stepNumber: 4, title: "Divide to find n", explanation: "Divide both sides by 3: n = 18 ÷ 3 = 6" },
      { stepNumber: 5, title: "Verify", explanation: "Substitute n = 6: 3(6) − 7 = 18 − 7 = 11 = 11 ✓" },
    ],
    hint: "First name the unknown as n, write the equation from the sentence, then solve it.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation — misidentifying which quantity is unknown.", "Forgetting to verify the answer in the original word statement."],
    tags: ["conceptual", "real-life", "class7", "ch04", "word-problem", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 1, estimatedTimeMinutes: 6,
    question: "Which value of x satisfies the equation 4x − 6 = 2x + 8?",
    options: ["x = 5", "x = 6", "x = 7", "x = 8"],
    answer: "Correct answer: (C) x = 7",
    steps: [
      { stepNumber: 1, title: "Collect x-terms on one side", explanation: "Subtract 2x from both sides: 4x − 2x − 6 = 8, giving 2x − 6 = 8." },
      { stepNumber: 2, title: "Move constant to RHS", explanation: "Add 6 to both sides: 2x = 8 + 6 = 14." },
      { stepNumber: 3, title: "Divide both sides by 2", explanation: "x = 14 ÷ 2 = 7." },
      { stepNumber: 4, title: "Verify", explanation: "LHS = 4(7) − 6 = 22; RHS = 2(7) + 8 = 22. LHS = RHS ✓" },
      { stepNumber: 5, title: "Check distractors", explanation: "x=5: LHS=14, RHS=18 ✗. x=6: LHS=18, RHS=20 ✗. x=8: LHS=26, RHS=24 ✗." },
    ],
    hint: "Move all x-terms to one side and all numbers to the other, then divide.",
    keyConcepts: ["variables on both sides", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:transposition", "mth:7:ch04:verification", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition"],
    commonErrors: ["Subtracting 6 from the RHS instead of adding it when moving the constant.", "Guessing x = 8 because it is the largest option — always verify by substitution."],
    tags: ["board-important", "computational", "class7", "ch04", "MCQ-solve", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 1, estimatedTimeMinutes: 6,
    question: "The sum of three consecutive integers is 54. What is the smallest of the three integers?",
    options: ["15", "16", "17", "18"],
    answer: "Correct answer: (C) 17",
    steps: [
      { stepNumber: 1, title: "Assign variables", explanation: "Let the three consecutive integers be n, n + 1, and n + 2." },
      { stepNumber: 2, title: "Form the equation", explanation: "n + (n + 1) + (n + 2) = 54, which simplifies to 3n + 3 = 54." },
      { stepNumber: 3, title: "Solve for n", explanation: "Subtract 3: 3n = 51. Divide by 3: n = 17." },
      { stepNumber: 4, title: "Verify", explanation: "17 + 18 + 19 = 54 ✓. The smallest integer is 17." },
      { stepNumber: 5, title: "Eliminate distractors", explanation: "n=15: 15+16+17=48 ✗. n=16: 16+17+18=51 ✗. n=18: 18+19+20=57 ✗." },
    ],
    hint: "Name the smallest integer n. The next two are n+1 and n+2. Write their sum equal to 54.",
    keyConcepts: ["consecutive integers", "equation formation", "solving equations"],
    conceptsCovered: ["mth:7:ch04:word-problem-to-equation", "mth:7:ch04:equation-from-statement", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition"],
    commonErrors: ["Using n, n+2, n+4 (even gap) instead of n, n+1, n+2 for consecutive integers.", "Choosing 18 by dividing 54 ÷ 3 = 18 — this gives the middle integer, not the smallest."],
    tags: ["board-important", "computational", "class7", "ch04", "MCQ-solve", "generated-proof"],
    source: "original",
  },

];
