// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 4: Simple Equations
 * GENERATED QUALITY PILOT — offline deterministic generator.
 *
 * Generator : scripts/src/generateMathQuestionProof.ts
 * Command   : pnpm --filter @workspace/scripts run generate-proof
 *
 * 25 questions — 10 Easy / 10 Medium / 5 Hard
 * Topics: t1 Setting Up Equations | t2 Solving and Verifying
 *
 * Blueprint families (max 5 per family, ≥ 8 families):
 *   B1 Direct Solve           gen-001, 002, 005, 006        4 q  Easy×2, Medium×2
 *   B2 Word-to-Equation       gen-003, 004, 007, 008        4 q  Easy×2, Medium×2
 *   B3 MCQ Verification       gen-009, 010                  2 q  Hard×2
 *   B4 Error Spotting         gen-011, 012, 013             3 q  Easy, Medium, Hard
 *   B5 Equation-to-Verbal     gen-014, 015, 016             3 q  Easy, Medium, Hard
 *   B6 Fill Missing Value     gen-017, 018, 019             3 q  Easy×2, Medium
 *   B7 Daily-Life Application gen-020, 021, 022             3 q  Medium×2, Hard
 *   B8 True/False             gen-023, 024, 025             3 q  Easy×2, Medium
 *
 * Format distribution: ShortAnswer×12, MCQ×7, FillInTheBlanks×3, TrueOrFalse×3
 * Bloom's: understand×4, apply×11, analyse×4, evaluate×6
 *
 * Original 10 IDs (gen-001..gen-010) preserved. Blueprint tags added to metadata.
 * DO NOT hand-edit. Re-run the generator to modify.
 */

import type { QuestionV2 } from "../../../types";

export const CH04_SIMPLE_EQUATIONS_GENERATED_PROOF: QuestionV2[] = [

  {
    id: "bo-mth-7-ch04-gen-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve for x: x + 7 = 15",
    answer: "x = 8. Verification: LHS = 8 + 7 = 15 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "Write the equation", explanation: "Given: x + 7 = 15" },
      { stepNumber: 2, title: "Isolate the x-term", explanation: "Subtract 7 from both sides: x = 15 − 7 = 8" },
      { stepNumber: 3, title: "Find x", explanation: "x is already isolated: x = 8" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 8: LHS = 8 + 7 = 15 = 15 = RHS ✓" },
    ],
    hint: "Identify which operation connects x and the number, then reverse it on both sides.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the inverse operation to only one side instead of both sides.", "Forgetting to verify the solution by substituting back."],
    tags: ["blueprint-B1-direct-solve", "computational", "ncert-direct", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve for x: 3x = 21",
    answer: "x = 7. Verification: LHS = 3 × 7 = 21 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "Write the equation", explanation: "Given: 3x = 21" },
      { stepNumber: 2, title: "Isolate the x-term", explanation: "The equation is already 3x = 21. Proceed to divide." },
      { stepNumber: 3, title: "Find x", explanation: "Divide both sides by 3: x = 21 ÷ 3 = 7" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 7: LHS = 3 × 7 = 21 = 21 = RHS ✓" },
    ],
    hint: "First move the constant (none) away from the x-term, then divide by the coefficient of x.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the inverse operation to only one side instead of both sides.", "Forgetting to verify the solution by substituting back."],
    tags: ["blueprint-B1-direct-solve", "computational", "ncert-direct", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "8 more than a number is 20. Find the number.",
    answer: "The number is 12. (Equation: n + 8 = 20, solved to get n = 12.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: n + 8 = 20" },
      { stepNumber: 3, title: "Solve", explanation: "Subtract 8 from both sides: n = 20 − 8 = 12" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute n = 12: 12 + 8 = 20 = 20 ✓" },
    ],
    hint: "Name the unknown n, write the addition or subtraction equation it satisfies, then undo that operation.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation by misreading which operation the sentence describes.", "Forgetting to verify the answer back in the original sentence."],
    tags: ["blueprint-B2-word-to-equation", "conceptual", "real-life", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A number decreased by 6 equals 10. Find the number.",
    answer: "The number is 16. (Equation: n − 6 = 10, solved to get n = 16.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: n − 6 = 10" },
      { stepNumber: 3, title: "Solve", explanation: "Add 6 to both sides: n = 10 + 6 = 16" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute n = 16: 16 − 6 = 10 = 10 ✓" },
    ],
    hint: "Name the unknown n, write the addition or subtraction equation it satisfies, then undo that operation.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation by misreading which operation the sentence describes.", "Forgetting to verify the answer back in the original sentence."],
    tags: ["blueprint-B2-word-to-equation", "conceptual", "real-life", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 5,
    question: "Solve for x: 2x + 5 = 17",
    answer: "x = 6. Verification: LHS = 2(6) + 5 = 17 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "Write the equation", explanation: "Given: 2x + 5 = 17" },
      { stepNumber: 2, title: "Isolate the x-term", explanation: "Subtract 5 from both sides: 2x = 17 − 5 = 12" },
      { stepNumber: 3, title: "Find x", explanation: "Divide both sides by 2: x = 12 ÷ 2 = 6" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 6: LHS = 2(6) + 5 = 17 = 17 = RHS ✓" },
    ],
    hint: "First move the constant (5) away from the x-term, then divide by the coefficient of x.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the inverse operation to only one side instead of both sides.", "Forgetting to verify the solution by substituting back."],
    tags: ["blueprint-B1-direct-solve", "computational", "ncert-direct", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 5,
    question: "Solve for x: 3x − 4 = 14",
    answer: "x = 6. Verification: LHS = 3(6) − 4 = 14 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "Write the equation", explanation: "Given: 3x − 4 = 14" },
      { stepNumber: 2, title: "Isolate the x-term", explanation: "Add 4 to both sides: 3x = 14 + 4 = 18" },
      { stepNumber: 3, title: "Find x", explanation: "Divide both sides by 3: x = 18 ÷ 3 = 6" },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 6: LHS = 3(6) − 4 = 14 = 14 = RHS ✓" },
    ],
    hint: "First move the constant (4) away from the x-term, then divide by the coefficient of x.",
    keyConcepts: ["solving equations", "balance method", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Applying the inverse operation to only one side instead of both sides.", "Forgetting to verify the solution by substituting back."],
    tags: ["blueprint-B1-direct-solve", "computational", "ncert-direct", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 6,
    question: "Twice a number, increased by 3, equals 19. Find the number.",
    answer: "The number is 8. (Equation: 2n + 3 = 19, solved to get n = 8.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: 2n + 3 = 19" },
      { stepNumber: 3, title: "Move the constant", explanation: "Subtract 3 from both sides: 2n = 19 − 3 = 16" },
      { stepNumber: 4, title: "Divide to find n", explanation: "Divide both sides by 2: n = 16 ÷ 2 = 8" },
      { stepNumber: 5, title: "Verify", explanation: "Substitute n = 8: 2(8) + 3 = 16 + 3 = 19 = 19 ✓" },
    ],
    hint: "Name the unknown n. Translate the sentence into an equation using n. Then undo the constant first, and divide last.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation by misreading which operation the sentence describes.", "Forgetting to verify the answer back in the original sentence."],
    tags: ["blueprint-B2-word-to-equation", "conceptual", "real-life", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 6,
    question: "Three times a number, decreased by 7, equals 11. Find the number.",
    answer: "The number is 6. (Equation: 3n − 7 = 11, solved to get n = 6.)",
    steps: [
      { stepNumber: 1, title: "Assign a variable", explanation: "Let the unknown number be n." },
      { stepNumber: 2, title: "Form the equation", explanation: "Translating the statement: 3n − 7 = 11" },
      { stepNumber: 3, title: "Move the constant", explanation: "Add 7 to both sides: 3n = 11 + 7 = 18" },
      { stepNumber: 4, title: "Divide to find n", explanation: "Divide both sides by 3: n = 18 ÷ 3 = 6" },
      { stepNumber: 5, title: "Verify", explanation: "Substitute n = 6: 3(6) − 7 = 18 − 7 = 11 = 11 ✓" },
    ],
    hint: "Name the unknown n. Translate the sentence into an equation using n. Then undo the constant first, and divide last.",
    keyConcepts: ["word problems", "equation formation", "balance method"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Setting up the wrong equation by misreading which operation the sentence describes.", "Forgetting to verify the answer back in the original sentence."],
    tags: ["blueprint-B2-word-to-equation", "conceptual", "real-life", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 1, estimatedTimeMinutes: 7,
    question: "Which value of x satisfies the equation 4x − 6 = 2x + 8?",
    options: ["x = 5", "x = 6", "x = 7", "x = 8"],
    answer: "Correct answer: (C) x = 7",
    steps: [
      { stepNumber: 1, title: "Collect x-terms on one side", explanation: "Subtract 2x from both sides: 4x − 2x − 6 = 8, giving 2x − 6 = 8." },
      { stepNumber: 2, title: "Move constant to RHS", explanation: "Add 6 to both sides: 2x = 8 + 6 = 14." },
      { stepNumber: 3, title: "Divide both sides by 2", explanation: "x = 14 ÷ 2 = 7." },
      { stepNumber: 4, title: "Verify", explanation: "LHS = 4(7) − 6 = 22; RHS = 2(7) + 8 = 22. LHS = RHS ✓" },
      { stepNumber: 5, title: "Eliminate distractors", explanation: "x=5: LHS=14, RHS=18 ✗. x=6: LHS=18, RHS=20 ✗. x=8: LHS=26, RHS=24 ✗." },
    ],
    hint: "Move all x-terms to one side and all constants to the other, then divide.",
    examTip: "Equations with the variable on both sides are a standard 1-mark MCQ in Class 7 and 8 boards.",
    keyConcepts: ["variables on both sides", "transposition", "verification"],
    conceptsCovered: ["mth:7:ch04:transposition", "mth:7:ch04:verification", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition"],
    commonErrors: ["Subtracting 6 from RHS instead of adding — moving a negative term becomes addition.", "Guessing x = 8 (the largest option) without verifying by substitution."],
    tags: ["blueprint-B3-mcq-verification", "board-important", "computational", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 1, estimatedTimeMinutes: 7,
    question: "The sum of three consecutive integers is 54. What is the smallest of the three integers?",
    options: ["15", "16", "17", "18"],
    answer: "Correct answer: (C) 17",
    steps: [
      { stepNumber: 1, title: "Assign variables", explanation: "Let the three consecutive integers be n, n + 1, and n + 2." },
      { stepNumber: 2, title: "Form the equation", explanation: "n + (n + 1) + (n + 2) = 54, which simplifies to 3n + 3 = 54." },
      { stepNumber: 3, title: "Solve for n", explanation: "Subtract 3: 3n = 51. Divide by 3: n = 17." },
      { stepNumber: 4, title: "Verify", explanation: "17 + 18 + 19 = 54 ✓. The smallest integer is 17." },
      { stepNumber: 5, title: "Eliminate distractors", explanation: "n=15: 48 ✗. n=16: 51 ✗. n=18: 57 ✗." },
    ],
    hint: "Name the smallest integer n. The next two are n+1 and n+2. Write their sum equal to 54.",
    examTip: "Consecutive-integer word problems are a classic board-exam MCQ. The trap option is 54÷3 = 18, which gives the middle integer.",
    keyConcepts: ["consecutive integers", "equation formation", "solving equations"],
    conceptsCovered: ["mth:7:ch04:word-problem-to-equation", "mth:7:ch04:equation-from-statement", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:balance-method", "mth:7:ch04:transposition"],
    commonErrors: ["Using n, n+2, n+4 instead of n, n+1, n+2 — those are consecutive ODD integers.", "Choosing 18 by computing 54 ÷ 3 — that gives the middle integer, not the smallest."],
    tags: ["blueprint-B3-mcq-verification", "board-important", "computational", "class7", "ch04", "generated-proof"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 4,
    question: "A student solved x + 5 = 12 and wrote: x = 12 + 5 = 17. What is wrong with this working?",
    options: ["Should subtract 5 from both sides: x = 12 − 5 = 7", "Should multiply both sides by 5", "Should add 5 to the LHS only", "Nothing — x = 17 is correct"],
    answer: "Correct answer: (A) Should subtract 5 from both sides: x = 12 − 5 = 7",
    steps: [
      { stepNumber: 1, title: "Identify the error", explanation: "The student added 5 to the RHS (12 + 5) instead of subtracting it. The rule: move a term to the other side by reversing its sign." },
      { stepNumber: 2, title: "Correct method", explanation: "Subtract 5 from both sides: x + 5 − 5 = 12 − 5, giving x = 7." },
      { stepNumber: 3, title: "Verify correct answer", explanation: "Substitute x = 7: LHS = 7 + 5 = 12 = RHS ✓" },
      { stepNumber: 4, title: "Why distractors fail", explanation: "(B) Multiplying changes the equation entirely. (C) You must apply the same operation to BOTH sides. (D) If x = 17, then 17 + 5 = 22 ≠ 12." },
    ],
    hint: "When you move a number across the equals sign, its sign reverses: + becomes −.",
    keyConcepts: ["balance method", "error identification", "verification"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Adding the constant to the RHS instead of subtracting it when isolating x."],
    tags: ["blueprint-B4-error-spotting", "class7", "ch04", "generated-proof", "MCQ-error-spotting"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 5,
    question: "A student solved 2x + 4 = 16 and got 2x = 16 + 4 = 20, then x = 10. Where is the error and what is the correct answer?",
    options: ["Should subtract 4 (not add): 2x = 16 − 4 = 12, giving x = 6", "Should divide by 4 in the last step, not by 2", "Should multiply both sides by 4 first", "No error — x = 10 is correct"],
    answer: "Correct answer: (A) Should subtract 4 (not add): 2x = 16 − 4 = 12, giving x = 6",
    steps: [
      { stepNumber: 1, title: "Identify the error", explanation: "The +4 was moved to the RHS as +4 (added), but moving +4 across the equals sign turns it into −4." },
      { stepNumber: 2, title: "Correct step 1", explanation: "Subtract 4 from both sides: 2x = 16 − 4 = 12." },
      { stepNumber: 3, title: "Correct step 2", explanation: "Divide both sides by 2: x = 12 ÷ 2 = 6." },
      { stepNumber: 4, title: "Verify", explanation: "Substitute x = 6: 2(6) + 4 = 12 + 4 = 16 = RHS ✓" },
    ],
    hint: "Transposition rule: +4 on the LHS becomes −4 on the RHS.",
    hint2: "Always substitute your answer back. If 2(10) + 4 = 24 ≠ 16, the answer is wrong.",
    examTip: "Identifying a wrong transposition step is a common 1-mark competency question in Class 7 assessments.",
    keyConcepts: ["transposition", "error identification", "two-step equations"],
    conceptsCovered: ["mth:7:ch04:transposition", "mth:7:ch04:balance-method", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:balance-method"],
    commonErrors: ["Transposing a positive constant as positive — it must become negative when moved.", "Not verifying the answer after solving."],
    tags: ["blueprint-B4-error-spotting", "class7", "ch04", "generated-proof", "MCQ-error-spotting"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 5,
    question: "A student translated the statement 'Twice a number plus 5 equals 21' as the equation 2 + 5n = 21. Which equation is correct?",
    options: ["2n + 5 = 21", "2n − 5 = 21", "n + 5 = 21", "2 + 5n = 21 — the student is correct"],
    answer: "Correct answer: (A) 2n + 5 = 21",
    steps: [
      { stepNumber: 1, title: "Parse 'twice a number'", explanation: "'Twice a number' means 2 × n = 2n. The student wrote 2 alone (a constant), not 2n (twice the unknown)." },
      { stepNumber: 2, title: "Parse 'plus 5'", explanation: "'Plus 5' adds 5 to 2n, giving 2n + 5." },
      { stepNumber: 3, title: "Form correct equation", explanation: "'Equals 21' gives: 2n + 5 = 21." },
      { stepNumber: 4, title: "Verify by solving", explanation: "2n = 16, n = 8. Check: 2(8) + 5 = 21 ✓" },
      { stepNumber: 5, title: "Why the student is wrong", explanation: "In 2 + 5n = 21, the 5 is the coefficient of n and 2 is a constant — this says '5 times a number plus 2 = 21', which is a different statement." },
    ],
    hint: "'Twice a number' always means 2n (2 multiplied by the unknown), not 2 by itself.",
    hint2: "Translate one word-group at a time: (twice a number) → 2n; (plus 5) → + 5; (equals 21) → = 21.",
    examTip: "Translating a verbal statement to an equation is a standard 1–2 mark question in CBSE competency papers. Parse each phrase independently.",
    keyConcepts: ["equation formation", "translating statements", "error identification"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Swapping the roles of coefficient and constant when translating verbal descriptions.", "Writing 2 alone instead of 2n for 'twice a number'."],
    tags: ["blueprint-B4-error-spotting", "class7", "ch04", "generated-proof", "MCQ-error-spotting"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 3,
    question: "Which of the following statements is best described by the equation n + 4 = 13?",
    options: ["4 more than a number equals 13", "A number equals 4 more than 13", "13 less than a number equals 4", "4 times a number equals 13"],
    answer: "Correct answer: (A) 4 more than a number equals 13",
    steps: [
      { stepNumber: 1, title: "Read the equation", explanation: "n + 4 = 13 means: (unknown number n) + 4 = 13." },
      { stepNumber: 2, title: "Translate n + 4", explanation: "'n + 4' = 4 added to n = '4 more than a number'." },
      { stepNumber: 3, title: "Translate = 13", explanation: "'= 13' means 'equals 13'." },
      { stepNumber: 4, title: "Eliminate distractors", explanation: "(B) would give n = 17, not n + 4 = 13. (C) would be n − 13 = 4. (D) would be 4n = 13." },
    ],
    hint: "Read the equation piece by piece: n is the unknown, + 4 means 'more than', = 13 means 'equals 13'.",
    keyConcepts: ["equation translation", "verbal representation", "equation formation"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:variable-vs-constant"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Reading n + 4 as 'a number equals 4 more' — the = sign is further right, between the expression and 13."],
    tags: ["blueprint-B5-equation-to-verbal", "class7", "ch04", "generated-proof", "MCQ-verbal"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 4,
    question: "Which verbal statement correctly describes the equation 3n − 2 = 10?",
    options: ["Two less than three times a number equals 10", "Three less than twice a number equals 10", "Two more than three times a number equals 10", "Three times a number equals two more than 10"],
    answer: "Correct answer: (A) Two less than three times a number equals 10",
    steps: [
      { stepNumber: 1, title: "Identify 3n", explanation: "'3n' = three times the unknown number n." },
      { stepNumber: 2, title: "Identify − 2", explanation: "'3n − 2' = three times n, decreased by 2, i.e. 'two less than three times n'." },
      { stepNumber: 3, title: "Identify = 10", explanation: "'= 10' means 'equals 10'." },
      { stepNumber: 4, title: "Eliminate distractors", explanation: "(B) would be 2n − 3 = 10. (C) would be 3n + 2 = 10. (D) would be 3n = 12, which gives the same solution but is a different equation form." },
    ],
    hint: "'3n − 2' reads as 'two less than three times a number' — subtraction on the variable-side means 'less than'.",
    hint2: "Check by solving: 3n = 12, n = 4. Then verify: 3(4) − 2 = 10 ✓",
    examTip: "Equations-to-words questions appear in CBSE competency papers. A common trap is swapping 'less than' and 'more than' (options A and C here).",
    keyConcepts: ["equation translation", "coefficient", "subtraction in verbal form"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Translating − 2 as 'two more than' rather than 'two less than'."],
    tags: ["blueprint-B5-equation-to-verbal", "class7", "ch04", "generated-proof", "MCQ-verbal"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 7,
    question: "Write a verbal statement for the equation 5n + 3 = 23. Then solve the equation to find the value of n.",
    answer: "Verbal: 'Five times a number, increased by 3, equals 23.' Solving: 5n = 20, so n = 4.",
    steps: [
      { stepNumber: 1, title: "Translate 5n", explanation: "'5n' means 'five times an unknown number n'." },
      { stepNumber: 2, title: "Translate + 3", explanation: "'5n + 3' means 'five times a number, increased by 3'." },
      { stepNumber: 3, title: "Translate = 23", explanation: "'= 23' means 'equals 23'. Full verbal statement: 'Five times a number, increased by 3, equals 23.'" },
      { stepNumber: 4, title: "Solve: move constant", explanation: "Subtract 3 from both sides: 5n = 23 − 3 = 20." },
      { stepNumber: 5, title: "Solve: find n", explanation: "Divide both sides by 5: n = 20 ÷ 5 = 4." },
      { stepNumber: 6, title: "Verify", explanation: "Substitute n = 4: 5(4) + 3 = 20 + 3 = 23 = RHS ✓" },
    ],
    hint: "Translate each part separately: (5n) → '5 times a number'; (+3) → 'increased by 3'; (=23) → 'equals 23'.",
    hint2: "After writing the verbal form, solve the original equation using the two-step method.",
    examTip: "Combined translation + solve questions test Bloom's 'evaluate' level and are worth 3 marks in Class 7 assessments.",
    keyConcepts: ["equation translation", "two-step equations", "verbal representation"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:balance-method", "mth:7:ch04:transposition"],
    prerequisites: ["mth:7:ch04:variable-vs-constant", "mth:7:ch04:balance-method"],
    commonErrors: ["Writing the verbal statement after solving, rather than directly from the equation.", "Translating +3 as 'increased by 3n' instead of by a constant."],
    tags: ["blueprint-B5-equation-to-verbal", "class7", "ch04", "generated-proof", "combined-task"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-017",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "In the equation x + ___ = 17, if x = 9, the missing number is ___.",
    answer: "8",
    steps: [
      { stepNumber: 1, title: "Substitute the known value", explanation: "Replace x with 9: 9 + ___ = 17." },
      { stepNumber: 2, title: "Find the missing number", explanation: "___ = 17 − 9 = 8." },
      { stepNumber: 3, title: "Verify", explanation: "Check: 9 + 8 = 17 ✓" },
    ],
    hint: "Substitute x = 9 into the equation, then find what must be added to 9 to reach 17.",
    keyConcepts: ["substitution", "solving equations", "verification"],
    conceptsCovered: ["mth:7:ch04:verification", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Adding 9 and 17 instead of finding the difference: 9 + 17 = 26 ≠ correct."],
    tags: ["blueprint-B6-fill-missing-value", "class7", "ch04", "generated-proof", "fill-in-the-blank"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-018",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "FillInTheBlanks",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The equation 4x = 28 gives x = ___.",
    answer: "7",
    steps: [
      { stepNumber: 1, title: "Identify the operation", explanation: "4x means 4 times x. To undo multiplication, divide." },
      { stepNumber: 2, title: "Divide both sides by 4", explanation: "x = 28 ÷ 4 = 7." },
      { stepNumber: 3, title: "Verify", explanation: "Check: 4 × 7 = 28 ✓" },
    ],
    hint: "What do you divide by to cancel the 4 in '4x'?",
    keyConcepts: ["division operation", "solving equations", "inverse operations"],
    conceptsCovered: ["mth:7:ch04:balance-method", "mth:7:ch04:verification"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Subtracting 4 from 28 (28 − 4 = 24) instead of dividing."],
    tags: ["blueprint-B6-fill-missing-value", "class7", "ch04", "generated-proof", "fill-in-the-blank"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-019",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "competency", questionFormat: "FillInTheBlanks",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 4,
    question: "In the equation 3n − ___ = 10, if n = 5, the missing number is ___.",
    answer: "5",
    steps: [
      { stepNumber: 1, title: "Substitute n = 5", explanation: "Replace n with 5: 3(5) − ___ = 10." },
      { stepNumber: 2, title: "Simplify", explanation: "15 − ___ = 10." },
      { stepNumber: 3, title: "Find the missing number", explanation: "___ = 15 − 10 = 5." },
      { stepNumber: 4, title: "Verify", explanation: "Check: 3(5) − 5 = 15 − 5 = 10 ✓" },
    ],
    hint: "First compute 3 × 5 = 15, then decide what must be subtracted from 15 to get 10.",
    hint2: "Work backwards: if 15 − ? = 10, then ? = 15 − 10.",
    examTip: "Finding a missing constant tests 'working backwards' — a key Class 7 problem-solving skill.",
    keyConcepts: ["substitution", "working backwards", "verification"],
    conceptsCovered: ["mth:7:ch04:verification", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant", "mth:7:ch04:balance-method"],
    commonErrors: ["Substituting n = 5 into the missing-number slot instead of into n."],
    tags: ["blueprint-B6-fill-missing-value", "class7", "ch04", "generated-proof", "fill-in-the-blank"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-020",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 5,
    question: "A bookshop sells pens at ₹5 each. Meera buys some pens and pays a total of ₹45. Set up an equation and find how many pens she bought.",
    answer: "Meera bought 9 pens. (Let n = number of pens. Equation: 5n = 45 → n = 9.)",
    steps: [
      { stepNumber: 1, title: "Define the variable", explanation: "Let n = the number of pens Meera bought." },
      { stepNumber: 2, title: "Form the equation", explanation: "Cost of n pens at ₹5 each = 5n. Total paid = ₹45. Equation: 5n = 45." },
      { stepNumber: 3, title: "Solve", explanation: "Divide both sides by 5: n = 45 ÷ 5 = 9." },
      { stepNumber: 4, title: "Verify and state", explanation: "Check: 5 × 9 = ₹45 ✓. Meera bought 9 pens." },
    ],
    hint: "Total cost = price per pen × number of pens. Set this equal to ₹45.",
    hint2: "Name the unknown first, then write a multiplication equation.",
    examTip: "Direct proportion word problems (cost × quantity = total) are the most common Class 7 application of equations.",
    keyConcepts: ["forming equations", "multiplication equations", "real-world application"],
    conceptsCovered: ["mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Dividing 45 by 5 mentally without forming the equation — the question asks for the equation.", "Writing n = 5 × 45 = 225 by multiplying instead of dividing."],
    tags: ["blueprint-B7-daily-life-application", "class7", "ch04", "generated-proof", "real-life", "word-problem"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-021",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 5,
    question: "Ravi had some marbles. After giving 8 to his friend, he had 15 left. Set up an equation and find how many marbles Ravi started with.",
    answer: "Ravi started with 23 marbles. (Let n = initial count. Equation: n − 8 = 15 → n = 23.)",
    steps: [
      { stepNumber: 1, title: "Define the variable", explanation: "Let n = the number of marbles Ravi started with." },
      { stepNumber: 2, title: "Form the equation", explanation: "After giving away 8: n − 8 = 15." },
      { stepNumber: 3, title: "Solve", explanation: "Add 8 to both sides: n = 15 + 8 = 23." },
      { stepNumber: 4, title: "Verify and state", explanation: "Check: 23 − 8 = 15 ✓. Ravi started with 23 marbles." },
    ],
    hint: "Starting amount minus given-away amount equals remaining amount.",
    hint2: "If you subtract 8 and get 15, you must add 8 to 15 to find what you started with.",
    examTip: "Subtraction word problems are common. Carefully identify what is known (15 left, gave away 8) and what is unknown (starting count).",
    keyConcepts: ["forming equations", "subtraction equations", "real-world application"],
    conceptsCovered: ["mth:7:ch04:word-problem-to-equation", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Subtracting 15 − 8 = 7 directly, ignoring that 8 was already taken away.", "Writing 8 − n = 15 (reversing the subtraction)."],
    tags: ["blueprint-B7-daily-life-application", "class7", "ch04", "generated-proof", "real-life", "word-problem"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-022",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 8,
    question: "In a class, the number of girls is 7 more than twice the number of boys. The total number of students is 49. Find the number of boys.",
    answer: "There are 14 boys. (Let b = boys, girls = 2b + 7. Equation: b + 2b + 7 = 49 → 3b = 42 → b = 14.)",
    steps: [
      { stepNumber: 1, title: "Define variable", explanation: "Let b = number of boys." },
      { stepNumber: 2, title: "Express girls in terms of b", explanation: "Girls = 7 more than twice the boys = 2b + 7." },
      { stepNumber: 3, title: "Form the equation", explanation: "Total = boys + girls: b + (2b + 7) = 49, giving 3b + 7 = 49." },
      { stepNumber: 4, title: "Solve", explanation: "Subtract 7: 3b = 42. Divide by 3: b = 14." },
      { stepNumber: 5, title: "Verify", explanation: "Boys = 14, Girls = 2(14) + 7 = 35. Total = 14 + 35 = 49 ✓" },
    ],
    hint: "Express the number of girls using b (the number of boys), then add boys + girls = 49.",
    hint2: "After forming 3b + 7 = 49, solve in two steps: first subtract 7, then divide by 3.",
    examTip: "Two-condition word problems that reduce to a single equation with one variable are 3-mark questions in Class 7–8 board papers. Always verify both conditions.",
    keyConcepts: ["multi-condition problems", "expressing one quantity in terms of another", "two-step equations"],
    conceptsCovered: ["mth:7:ch04:word-problem-to-equation", "mth:7:ch04:equation-from-statement", "mth:7:ch04:balance-method", "mth:7:ch04:transposition"],
    prerequisites: ["mth:7:ch04:variable-vs-constant", "mth:7:ch04:balance-method"],
    commonErrors: ["Writing girls = 2 + 7b instead of 2b + 7.", "Forgetting to add both boys and girls and setting just boys = 49."],
    tags: ["blueprint-B7-daily-life-application", "class7", "ch04", "generated-proof", "real-life", "word-problem", "hots"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-023",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "evaluate",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: x = 6 is a solution of the equation 2x + 3 = 15. Justify your answer.",
    answer: "True. Substituting x = 6: 2(6) + 3 = 12 + 3 = 15 = RHS ✓",
    steps: [
      { stepNumber: 1, title: "Substitute x = 6 into the LHS", explanation: "LHS = 2(6) + 3." },
      { stepNumber: 2, title: "Compute", explanation: "2 × 6 = 12; 12 + 3 = 15." },
      { stepNumber: 3, title: "Compare", explanation: "LHS = 15 = RHS ✓. So x = 6 satisfies the equation. The statement is TRUE." },
    ],
    hint: "Substitute x = 6 into the left-hand side and check whether you get 15.",
    keyConcepts: ["verification", "substitution", "solution of an equation"],
    conceptsCovered: ["mth:7:ch04:verification", "mth:7:ch04:balance-method"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Saying True without showing the substitution — justification is worth 1 mark."],
    tags: ["blueprint-B8-true-false", "class7", "ch04", "generated-proof", "true-false", "verification"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-024",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t2", topicName: "Solving and Verifying",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "evaluate",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: x = 4 is a solution of the equation 3x − 7 = 8. Justify your answer.",
    answer: "False. Substituting x = 4: 3(4) − 7 = 12 − 7 = 5 ≠ 8. The correct solution is x = 5.",
    steps: [
      { stepNumber: 1, title: "Substitute x = 4 into the LHS", explanation: "LHS = 3(4) − 7." },
      { stepNumber: 2, title: "Compute", explanation: "3 × 4 = 12; 12 − 7 = 5." },
      { stepNumber: 3, title: "Compare", explanation: "LHS = 5 ≠ 8 = RHS. So x = 4 does NOT satisfy the equation. The statement is FALSE." },
      { stepNumber: 4, title: "Find the correct solution", explanation: "3x = 8 + 7 = 15, x = 5. Check: 3(5) − 7 = 8 ✓" },
    ],
    hint: "Always substitute and compute before deciding True or False — do not guess.",
    keyConcepts: ["verification", "substitution", "solution of an equation"],
    conceptsCovered: ["mth:7:ch04:verification", "mth:7:ch04:transposition"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Guessing True because 4 is close to 5.", "Not computing fully: stopping at 3 × 4 = 12 without subtracting 7."],
    tags: ["blueprint-B8-true-false", "class7", "ch04", "generated-proof", "true-false", "verification"],
    source: "original",
  },

  {
    id: "bo-mth-7-ch04-gen-025",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch04", chapterName: "Simple Equations",
    topicId: "t1", topicName: "Setting Up Equations",
    questionType: "competency", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "evaluate",
    marks: 2, estimatedTimeMinutes: 4,
    question: "True or False: The equation for the statement 'the sum of a number and its double is 18' is n + 2n = 18. Justify your answer.",
    answer: "True. Let n be the number; its double is 2n. Sum = n + 2n = 3n = 18, giving n = 6. Check: 6 + 12 = 18 ✓",
    steps: [
      { stepNumber: 1, title: "Identify the unknown", explanation: "Let n be the number." },
      { stepNumber: 2, title: "Express 'its double'", explanation: "Double of n = 2n." },
      { stepNumber: 3, title: "Write 'their sum'", explanation: "Sum = n + 2n." },
      { stepNumber: 4, title: "Form the equation", explanation: "'Sum equals 18' gives n + 2n = 18. The equation matches. Statement is TRUE." },
      { stepNumber: 5, title: "Solve to confirm", explanation: "3n = 18, n = 6. Check: n + 2n = 6 + 12 = 18 ✓" },
    ],
    hint: "'Its double' means 2 times the same number, so double of n = 2n (not n + 2).",
    hint2: "Simplify n + 2n = 3n. Then 3n = 18 gives n = 6.",
    examTip: "True/False on equation formation tests whether you can correctly identify the equation — a 2-mark question where the justification earns the second mark.",
    keyConcepts: ["equation formation", "verbal representation", "simplification"],
    conceptsCovered: ["mth:7:ch04:equation-from-statement", "mth:7:ch04:word-problem-to-equation"],
    prerequisites: ["mth:7:ch04:variable-vs-constant"],
    commonErrors: ["Writing n + 2 = 18 thinking 'double' means adding 2.", "Forgetting to simplify n + 2n to 3n before solving."],
    tags: ["blueprint-B8-true-false", "class7", "ch04", "generated-proof", "true-false", "equation-formation"],
    source: "original",
  },

];
