// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 8: Comparing Quantities
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Percentages, Ratios, and Fractions — 37 q
 *   t2 Profit, Loss, and Simple Interest   — 38 q
 *
 * Concept nodes:
 *   mth:7:ch08:percentage-fraction-conversion
 *   mth:7:ch08:percentage-application
 *   mth:7:ch08:profit-loss-definition
 *   mth:7:ch08:profit-percent
 *   mth:7:ch08:selling-price-formula
 *   mth:7:ch08:simple-interest-formula
 *   mth:7:ch08:principal-rate-time
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH08_COMPARING_QUANTITIES: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Percentages, Ratios, and Fractions
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-con-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: 'Percent' means 'per hundred', so 45% means 45 out of 100.",
    answer: "True. The word 'percent' comes from Latin 'per centum' meaning 'by the hundred'. So 45% = 45/100 = 0.45.",
    steps: [{ stepNumber: 1, title: "Meaning of percent", explanation: "Per hundred. 45% = 45/100." }],
    hint: "Think 'per century' = per 100.",
    keyConcepts: ["percent", "per hundred"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "percent-definition"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Convert: (a) 3/4 to percent  (b) 120% to fraction in lowest terms.",
    answer: "(a) 3/4 × 100 = 75%. (b) 120/100 = 6/5.",
    steps: [
      { stepNumber: 1, title: "Fraction to percent", explanation: "Multiply by 100: 3/4 × 100 = 75%." },
      { stepNumber: 2, title: "Percent to fraction", explanation: "120/100 = 12/10 = 6/5.", result: "(a) 75%  (b) 6/5" },
    ],
    hint: "Percent → fraction: divide by 100. Fraction → percent: multiply by 100.",
    keyConcepts: ["fraction-percent conversion"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "conversion"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: To find x% of a number N, we compute (x/100) × N.",
    answer: "True. x% of N = (x/100) × N. Example: 20% of 150 = (20/100) × 150 = 30.",
    steps: [{ stepNumber: 1, title: "Formula", explanation: "x% of N = xN/100." }],
    hint: "Percent means divide by 100.",
    keyConcepts: ["percentage of a number"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "percentage-formula"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What percentage of 80 is 56?",
    answer: "(56/80) × 100 = 70%.",
    steps: [{ stepNumber: 1, title: "Formula", explanation: "(part/whole)×100 = (56/80)×100=70%.", result: "70%" }],
    hint: "Percentage = (part/whole) × 100.",
    keyConcepts: ["finding percentage", "ratio to percent"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "find-percentage"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A class has 40 students. 60% are girls. How many boys are there?",
    answer: "Girls = 60% of 40 = 24. Boys = 40 − 24 = 16.",
    steps: [
      { stepNumber: 1, title: "Girls", explanation: "60/100 × 40 = 24." },
      { stepNumber: 2, title: "Boys", explanation: "40 − 24 = 16.", result: "16 boys" },
    ],
    hint: "Find girls first, then subtract from total.",
    keyConcepts: ["percentage application", "complement"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "class-problem"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: An increase of 25% followed by a decrease of 25% returns to the original value.",
    answer: "False. If the original = 100, after 25% increase = 125. Then 25% decrease of 125 = 125 × 0.75 = 93.75 ≠ 100. The net effect is a 6.25% decrease.",
    steps: [
      { stepNumber: 1, title: "Increase", explanation: "100 × 1.25 = 125." },
      { stepNumber: 2, title: "Decrease", explanation: "125 × 0.75 = 93.75 ≠ 100. Net loss = 6.25%." },
    ],
    hint: "Percentages are applied to different bases.",
    keyConcepts: ["successive percentage change", "net effect"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "successive-percent"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-nce-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find: (a) 15% of 250  (b) 8% of 625  [NCERT Ex 8.1]",
    answer: "(a) 15/100 × 250 = 37.5  (b) 8/100 × 625 = 50.",
    steps: [
      { stepNumber: 1, title: "Part (a)", explanation: "15/100 × 250 = 37.5." },
      { stepNumber: 2, title: "Part (b)", explanation: "8/100 × 625 = 50.", result: "37.5 and 50" },
    ],
    hint: "Multiply by the fraction form of the percent.",
    keyConcepts: ["percentage of a number"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "NCERT-Ex8.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Convert to decimal: (a) 35%  (b) 7.5%  [NCERT Ex 8.1]",
    answer: "(a) 35/100 = 0.35  (b) 7.5/100 = 0.075.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "35/100=0.35." },
      { stepNumber: 2, title: "(b)", explanation: "7.5/100=0.075.", result: "0.35 and 0.075" },
    ],
    hint: "Divide by 100.",
    keyConcepts: ["percent to decimal"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "NCERT-Ex8.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Out of 500 students, 120 prefer cricket, 200 prefer football, and the rest prefer other sports. What percentage prefer other sports?  [NCERT Ex 8.1]",
    answer: "Other = 500 − 120 − 200 = 180. Percentage = 180/500 × 100 = 36%.",
    steps: [
      { stepNumber: 1, title: "Other students", explanation: "500−120−200=180." },
      { stepNumber: 2, title: "Percentage", explanation: "180/500×100=36%.", result: "36%" },
    ],
    hint: "Find 'others' by subtraction, then convert to percent.",
    keyConcepts: ["finding percentage", "real-life application"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "sports-survey"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A school cricket team has 25 students. 8 are selected for the final team. What percentage is not selected?  [NCERT Ex 8.1]",
    answer: "Not selected = 25 − 8 = 17. Percentage = 17/25 × 100 = 68%.",
    steps: [
      { stepNumber: 1, title: "Not selected", explanation: "25−8=17." },
      { stepNumber: 2, title: "Percentage", explanation: "17/25×100=68%.", result: "68%" },
    ],
    hint: "Find unselected count, then calculate percent.",
    keyConcepts: ["percentage", "real-life context"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "cricket-selection"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A number when increased by 10% becomes 132. Find the original number.  [NCERT Ex 8.2]",
    answer: "Original × 1.10 = 132 → Original = 132/1.10 = 120.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Let original = x. x + 10%x = 1.1x = 132." },
      { stepNumber: 2, title: "Solve", explanation: "x = 132/1.1 = 120.", result: "120" },
    ],
    hint: "Increased value = original × (1 + rate/100).",
    keyConcepts: ["reverse percentage", "finding original value"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "reverse-percent"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Convert the ratio 3:5 to percentage.  [NCERT Ex 8.1]",
    answer: "3:5 means 3 out of (3+5) = 8 total. 3/8 × 100 = 37.5%.",
    steps: [
      { stepNumber: 1, title: "Convert ratio to fraction", explanation: "3:(3+5)=3/8." },
      { stepNumber: 2, title: "To percent", explanation: "3/8×100=37.5%.", result: "37.5%" },
    ],
    hint: "Ratio a:b → fraction a/(a+b) → multiply by 100.",
    keyConcepts: ["ratio to percentage"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [{ error: "Using 3/5 instead of 3/8", correction: "3:5 means 3 out of 8 total parts, not 3 out of 5." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "ratio-to-percent"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Chalk contains calcium, carbon, and oxygen in ratio 10:3:12. Find the percentage of carbon in chalk.  [NCERT Ex 8.1]",
    answer: "Total parts = 10+3+12=25. Carbon = 3/25 × 100 = 12%.",
    steps: [
      { stepNumber: 1, title: "Total parts", explanation: "10+3+12=25." },
      { stepNumber: 2, title: "Carbon %", explanation: "3/25×100=12%.", result: "12%" },
    ],
    hint: "Find total parts, then compute fraction for carbon.",
    keyConcepts: ["ratio to percent", "chemistry context"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "chalk-composition"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The price of a bicycle was ₹3,500. It was sold for ₹2,800. Find the percentage decrease.  [NCERT Ex 8.2]",
    answer: "Decrease = 3500−2800=700. % decrease = 700/3500×100=20%.",
    steps: [
      { stepNumber: 1, title: "Decrease", explanation: "3500−2800=700." },
      { stepNumber: 2, title: "% decrease", explanation: "700/3500×100=20%.", result: "20% decrease" },
    ],
    hint: "% change = (change/original) × 100.",
    keyConcepts: ["percentage decrease"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "percentage-decrease"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Raju scored 450 out of 500 marks. What is his percentage?  [NCERT Ex 8.1]",
    answer: "450/500 × 100 = 90%.",
    steps: [{ stepNumber: 1, title: "Percentage", explanation: "450/500×100=90%.", result: "90%" }],
    hint: "(Scored/Total) × 100.",
    keyConcepts: ["percentage calculation", "marks"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "marks-percentage"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-ics-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A shopkeeper has 540 kg of rice. He sells 45% of it. How many kg remain? What is the ratio of sold to remaining?",
    answer: "Sold = 45% of 540 = 243 kg. Remaining = 297 kg. Ratio = 243:297 = 9:11.",
    steps: [
      { stepNumber: 1, title: "Sold", explanation: "45/100×540=243 kg." },
      { stepNumber: 2, title: "Remaining", explanation: "540−243=297 kg." },
      { stepNumber: 3, title: "Ratio", explanation: "243:297 = 9:11 (divide by 27).", result: "297 kg; ratio 9:11" },
    ],
    hint: "Simplify ratio by finding GCD.",
    keyConcepts: ["percentage", "ratio", "real-life"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch08", "rice-problem"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch08-ics-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In an election, 60,000 votes were cast. Candidate A got 45% and Candidate B got 35%. The rest were invalid. How many votes did each get? How many were invalid?",
    answer: "A = 45% of 60000 = 27000. B = 35% of 60000 = 21000. Invalid = 60000−27000−21000 = 12000.",
    steps: [
      { stepNumber: 1, title: "A's votes", explanation: "0.45×60000=27000." },
      { stepNumber: 2, title: "B's votes", explanation: "0.35×60000=21000." },
      { stepNumber: 3, title: "Invalid", explanation: "60000−48000=12000.", result: "A=27000, B=21000, Invalid=12000" },
    ],
    hint: "Compute each percentage separately.",
    keyConcepts: ["percentage application", "election context"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch08", "election"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch08-ics-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A phone was bought for ₹15,000 and sold for ₹18,750. What is the percentage gain?",
    answer: "Gain = 18750−15000=3750. % gain = 3750/15000×100=25%.",
    steps: [
      { stepNumber: 1, title: "Gain", explanation: "18750−15000=3750." },
      { stepNumber: 2, title: "% gain", explanation: "3750/15000×100=25%.", result: "25%" },
    ],
    hint: "% gain = (gain/CP) × 100.",
    keyConcepts: ["percentage gain"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch08", "gain-percent"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch08-ics-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Three types of tea are mixed in ratio 2:3:5. The prices per kg are ₹60, ₹80, and ₹100. Find the average price per kg of the mixture.",
    answer: "Total parts = 10. Weighted price = (2×60+3×80+5×100)/10 = (120+240+500)/10 = 860/10 = ₹86 per kg.",
    steps: [
      { stepNumber: 1, title: "Weighted sum", explanation: "2(60)+3(80)+5(100)=120+240+500=860." },
      { stepNumber: 2, title: "Average", explanation: "860/10=₹86.", result: "₹86 per kg" },
    ],
    hint: "Weighted average = sum of (ratio × price) / total ratio.",
    keyConcepts: ["weighted average", "mixture problem"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch08", "mixture-average"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-cmp-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "25% of 200 is:",
    options: ["25", "50", "75", "100"],
    answer: "50",
    steps: [{ stepNumber: 1, title: "Calculate", explanation: "25/100×200=50." }],
    hint: "25% = 1/4.",
    keyConcepts: ["percentage of a number"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "MCQ-percent"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 2,
    question: "A shirt costs ₹800. After a 15% discount, what is the selling price?",
    options: ["₹120", "₹680", "₹720", "₹760"],
    answer: "₹680",
    steps: [{ stepNumber: 1, title: "Discount", explanation: "Discount=15%×800=120. SP=800−120=₹680." }],
    hint: "SP = original price − discount amount.",
    keyConcepts: ["discount", "selling price"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "discount-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A factory produces 2400 items a day. If production increases by 12.5%, how many items are produced now?",
    answer: "Increase = 12.5% of 2400 = 300. New production = 2400+300=2700.",
    steps: [
      { stepNumber: 1, title: "Increase", explanation: "12.5/100×2400=300." },
      { stepNumber: 2, title: "New total", explanation: "2700.", result: "2700 items" },
    ],
    hint: "Add the increase to original.",
    keyConcepts: ["percentage increase", "production context"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "production"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 10,
    question: "During a sale, Store A offers 20% off on ₹1200, and Store B offers 30% off on ₹1500 for the same product. (a) What is the final price at each store? (b) Which store offers the better deal? (c) By what percent is one price less than the other?",
    answer: "(a) Store A: 1200×0.80=₹960. Store B: 1500×0.70=₹1050. (b) Store A is cheaper. (c) (1050−960)/1050×100≈8.57% cheaper at A.",
    steps: [
      { stepNumber: 1, title: "Store A", explanation: "1200−240=₹960." },
      { stepNumber: 2, title: "Store B", explanation: "1500−450=₹1050." },
      { stepNumber: 3, title: "Comparison", explanation: "960<1050. A is cheaper by 90/1050×100≈8.57%.", result: "A=₹960; B=₹1050; A cheaper by ~8.57%" },
    ],
    hint: "Calculate final prices first, then compare.",
    keyConcepts: ["discount", "comparison", "case study"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "sale-comparison"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If 40% of x = 80, what is x?",
    options: ["100", "150", "200", "250"],
    answer: "200",
    steps: [{ stepNumber: 1, title: "Solve", explanation: "0.4x=80 → x=200." }],
    hint: "Divide both sides by 0.4.",
    keyConcepts: ["reverse percentage"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "find-x"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A student scored 72 out of 90 in Maths and 65 out of 80 in Science. In which subject did the student perform better?",
    answer: "Maths: 72/90×100=80%. Science: 65/80×100=81.25%. Science performance was better.",
    steps: [
      { stepNumber: 1, title: "Maths %", explanation: "80%." },
      { stepNumber: 2, title: "Science %", explanation: "81.25%." },
      { stepNumber: 3, title: "Compare", explanation: "Science > Maths.", result: "Science" },
    ],
    hint: "Convert to percentages to compare fairly.",
    keyConcepts: ["comparing percentages", "performance analysis"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "compare-scores"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A tank is 60% full of water. After adding 240 litres, it is 80% full. Find the total capacity of the tank.",
    answer: "Let capacity = C. 0.60C + 240 = 0.80C → 240 = 0.20C → C = 1200 litres.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "0.6C+240=0.8C → 0.2C=240 → C=1200." },
      { stepNumber: 2, title: "Answer", explanation: "Capacity = 1200 litres.", result: "1200 litres" },
    ],
    hint: "Difference in percentage × capacity = added amount.",
    keyConcepts: ["percentage equation", "capacity problem"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "tank-capacity"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which is the greatest: 2/5, 40%, or 0.45?",
    options: ["2/5", "40%", "0.45", "All equal"],
    answer: "0.45",
    steps: [{ stepNumber: 1, title: "Convert all to decimals", explanation: "2/5=0.40; 40%=0.40; 0.45. Greatest = 0.45." }],
    hint: "Convert all to decimals for easy comparison.",
    keyConcepts: ["comparing fractions, decimals, percentages"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "comparison-MCQ"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-hot-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A price is increased by 20% and then decreased by 20%. Show that the final price is NOT the original price and find the net % change.",
    answer: "Let original = P. After 20% increase: 1.2P. After 20% decrease: 1.2P × 0.8 = 0.96P. Net change = −4% (a decrease of 4%).",
    steps: [
      { stepNumber: 1, title: "After increase", explanation: "P × 1.2 = 1.2P." },
      { stepNumber: 2, title: "After decrease", explanation: "1.2P × 0.8 = 0.96P." },
      { stepNumber: 3, title: "Net change", explanation: "(0.96P−P)/P×100=−4%. Net decrease 4%.", result: "Net −4%" },
    ],
    hint: "Percentages apply to different bases at each step.",
    keyConcepts: ["successive percentage changes", "net effect"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking +20% and −20% cancel", correction: "They apply to different bases; net effect is −4%." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "successive-change"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "City A has population 5,00,000 growing at 4% per year. City B has population 3,00,000 growing at 8% per year. After how many years will City B's population exceed City A's?",
    answer: "After 1 year: A=520000, B=324000. After 2 yr: A=540800, B=349920. After 10 yr: A=5,00,000×1.04¹⁰≈7,40,122; B=3,00,000×1.08¹⁰≈6,47,677. A>B. Approx: A=B when 5×1.04ⁿ=3×1.08ⁿ → (1.08/1.04)ⁿ=5/3 → n×ln(1.0385)=ln(1.667) → n≈13.5 years. After 14 years B exceeds A.",
    steps: [
      { stepNumber: 1, title: "Growth equations", explanation: "A_n=500000×1.04ⁿ; B_n=300000×1.08ⁿ." },
      { stepNumber: 2, title: "Set equal", explanation: "5×1.04ⁿ=3×1.08ⁿ → (1.08/1.04)ⁿ=5/3." },
      { stepNumber: 3, title: "Approximate", explanation: "n≈13.5. After 14 years.", result: "~14 years" },
    ],
    hint: "Set growth equations equal and solve for n.",
    keyConcepts: ["exponential growth", "population comparison"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [{ error: "Using simple growth instead of compound", correction: "Population growth is compounded annually." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "population-growth"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 8,
    question: "Design a problem where the answer to 'What percentage is A of B?' is 150%. Verify your problem.",
    answer: "Example: A = 75, B = 50. 75/50×100=150%. Interpretation: A is 50% MORE than B, or equivalently, A is 1.5 times B. Verification: 75/50=1.5=150%. ✓",
    steps: [
      { stepNumber: 1, title: "Design", explanation: "Choose A=75, B=50. A/B=1.5=150%." },
      { stepNumber: 2, title: "Verify", explanation: "75/50×100=150%. ✓" },
    ],
    hint: "150% means A > B; A = 1.5 × B.",
    keyConcepts: ["percentage > 100", "creating problems"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking percentage cannot exceed 100", correction: "Percentages can exceed 100% when comparing different quantities." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "design-150-percent"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A school has 800 students. The percentage of students who pass Maths is 75% and who pass Science is 80%. At least 60% pass both. Find the maximum percentage that could fail both subjects.",
    answer: "Using inclusion-exclusion: P(M∪S)=P(M)+P(S)−P(M∩S)=75+80−60=95%. So at most 5% fail both. Maximum failing both = 5%.",
    steps: [
      { stepNumber: 1, title: "Inclusion-exclusion", explanation: "P(M∪S)=75+80−60=95%." },
      { stepNumber: 2, title: "Fail both", explanation: "100−95=5%.", result: "At most 5%" },
    ],
    hint: "Use: P(A∪B) = P(A)+P(B)−P(A∩B).",
    keyConcepts: ["inclusion-exclusion", "set-based percentage"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "inclusion-exclusion"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 8,
    question: "Ramesh's salary increased by 10% each year for 2 years. By what single percentage did his salary increase overall? Is it exactly 20%?",
    answer: "Let original = 100. After year 1: 110. After year 2: 110 × 1.10 = 121. Total increase = 21%. It is NOT exactly 20% because the second 10% is applied to the already-increased salary.",
    steps: [
      { stepNumber: 1, title: "Year 1", explanation: "100 × 1.1 = 110." },
      { stepNumber: 2, title: "Year 2", explanation: "110 × 1.1 = 121." },
      { stepNumber: 3, title: "Net increase", explanation: "21%, not 20%.", result: "21%" },
    ],
    hint: "The second 10% is computed on the new salary, not the original.",
    keyConcepts: ["compound percentage increase"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [{ error: "Adding percentages: 10%+10%=20%", correction: "Successive percentage changes compound; total = 21%." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "compound-increase"],
    source: "hots",
  },

  // ── PREVIOUS YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-pyq-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 35% of 420.  [CBSE 2019]",
    answer: "35/100 × 420 = 147.",
    steps: [{ stepNumber: 1, title: "Calculate", explanation: "0.35×420=147.", result: "147" }],
    hint: "Multiply by 35/100.",
    keyConcepts: ["percentage of a number"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In an exam, 600 students appeared and 480 passed. What percentage passed? What percentage failed?  [SA-I 2020]",
    answer: "Pass% = 480/600×100=80%. Fail% = 20%.",
    steps: [
      { stepNumber: 1, title: "Pass%", explanation: "480/600×100=80%." },
      { stepNumber: 2, title: "Fail%", explanation: "100−80=20%.", result: "80% passed; 20% failed" },
    ],
    hint: "Pass% + Fail% = 100%.",
    keyConcepts: ["pass/fail percentage"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A watch worth ₹2400 was sold at a loss of 15%. Find the selling price.  [CBSE 2021]",
    answer: "Loss = 15% of 2400=360. SP=2400−360=₹2040.",
    steps: [
      { stepNumber: 1, title: "Loss amount", explanation: "0.15×2400=360." },
      { stepNumber: 2, title: "SP", explanation: "2400−360=₹2040.", result: "₹2040" },
    ],
    hint: "SP = CP − Loss = CP(1 − loss%).",
    keyConcepts: ["selling price", "loss calculation"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The population of a town was 40,000. It increased by 5% in the first year and decreased by 4% in the second year. Find the population after 2 years.  [CBSE 2022]",
    answer: "After year 1: 40000×1.05=42000. After year 2: 42000×0.96=40320.",
    steps: [
      { stepNumber: 1, title: "Year 1", explanation: "40000×1.05=42000." },
      { stepNumber: 2, title: "Year 2", explanation: "42000×0.96=40320.", result: "40320" },
    ],
    hint: "Apply each year's change to the result of the previous year.",
    keyConcepts: ["successive percentage changes", "population"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "What number increased by 30% gives 260?  [SA-I 2021]",
    answer: "x × 1.30 = 260 → x = 260/1.30 = 200.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "1.3x=260 → x=200.", result: "200" },
    ],
    hint: "Divide the result by (1 + rate/100).",
    keyConcepts: ["reverse percentage"],
    conceptsCovered: ["mth:7:ch08:percentage-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "SA2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentages, Ratios, and Fractions",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Convert 5/8 to percentage.  [CBSE 2020]",
    answer: "5/8 × 100 = 62.5%.",
    steps: [{ stepNumber: 1, title: "Multiply by 100", explanation: "5/8×100=62.5%.", result: "62.5%" }],
    hint: "Multiply fraction by 100.",
    keyConcepts: ["fraction to percent"],
    conceptsCovered: ["mth:7:ch08:percentage-fraction-conversion"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2020"],
    source: "previous-year",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Profit, Loss, and Simple Interest
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-con-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Profit = Selling Price − Cost Price, and Loss = Cost Price − Selling Price.",
    answer: "True. When SP > CP: Profit = SP − CP. When CP > SP: Loss = CP − SP.",
    steps: [
      { stepNumber: 1, title: "Profit condition", explanation: "If SP > CP, we gain: Profit = SP−CP." },
      { stepNumber: 2, title: "Loss condition", explanation: "If CP > SP, we lose: Loss = CP−SP." },
    ],
    hint: "Think of profit as positive and loss as negative.",
    keyConcepts: ["profit", "loss", "cost price", "selling price"],
    conceptsCovered: ["mth:7:ch08:profit-loss-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "profit-loss-definition"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the formulas for: (a) Profit %  (b) Loss %  (c) SP when profit % is given.",
    answer: "(a) Profit% = (Profit/CP)×100  (b) Loss% = (Loss/CP)×100  (c) SP = CP × (1 + Profit%/100).",
    steps: [
      { stepNumber: 1, title: "Formulas", explanation: "All percentages are calculated on Cost Price (CP)." },
    ],
    hint: "Profit/Loss % is always on CP.",
    keyConcepts: ["profit percent", "loss percent", "SP formula"],
    conceptsCovered: ["mth:7:ch08:profit-percent", "mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "PL-formulas"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Simple Interest = (P × R × T) / 100, where P = Principal, R = Rate % per annum, T = Time in years.",
    answer: "True. SI = PRT/100 is the fundamental formula for simple interest.",
    steps: [{ stepNumber: 1, title: "SI formula", explanation: "SI = PRT/100." }],
    hint: "P, R, T all go in the numerator; 100 in denominator.",
    keyConcepts: ["simple interest formula"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "SI-formula"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A person buys a table for ₹1,200 and sells it for ₹1,500. Find the profit and profit percentage.",
    answer: "Profit = 1500−1200=₹300. Profit% = 300/1200×100=25%.",
    steps: [
      { stepNumber: 1, title: "Profit", explanation: "SP−CP=300." },
      { stepNumber: 2, title: "Profit%", explanation: "300/1200×100=25%.", result: "₹300; 25%" },
    ],
    hint: "Profit% is always on Cost Price.",
    keyConcepts: ["profit calculation", "profit percent"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "profit-example"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: If a shopkeeper marks up the price by 20% and then offers a discount of 20%, he neither gains nor loses.",
    answer: "False. Markup of 20% on CP = 1.2 CP. Discount of 20% on marked price = 0.8 × 1.2CP = 0.96CP. Since SP = 0.96 CP < CP, there is a loss of 4%.",
    steps: [
      { stepNumber: 1, title: "Marked price", explanation: "MP = CP × 1.2." },
      { stepNumber: 2, title: "After 20% discount", explanation: "SP = MP × 0.8 = 1.2 × 0.8 × CP = 0.96CP." },
      { stepNumber: 3, title: "Result", explanation: "SP < CP → 4% loss." },
    ],
    hint: "Percentages apply to different bases.",
    keyConcepts: ["markup and discount", "net profit/loss"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "markup-discount"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch08-con-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is the Amount (A) in simple interest? Write the formula.",
    answer: "Amount = Principal + Simple Interest. A = P + SI = P + PRT/100 = P(1 + RT/100).",
    steps: [{ stepNumber: 1, title: "Amount formula", explanation: "A = P + SI = P(1 + RT/100)." }],
    hint: "Amount includes both principal and interest.",
    keyConcepts: ["amount", "principal + interest"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "amount-formula"],
    source: "concept",
  },

  // ── NCERT (t2) ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-nce-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A bought a book for ₹160 and sold for ₹192. Find profit %.  [NCERT Ex 8.3]",
    answer: "Profit = 32. Profit% = 32/160×100=20%.",
    steps: [
      { stepNumber: 1, title: "Profit", explanation: "192−160=32." },
      { stepNumber: 2, title: "Profit%", explanation: "32/160×100=20%.", result: "20%" },
    ],
    hint: "Profit% = (profit/CP)×100.",
    keyConcepts: ["profit percent"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Meera bought a sari for ₹1,250 and sold it for ₹1,000. Find the loss %.  [NCERT Ex 8.3]",
    answer: "Loss=250. Loss%=250/1250×100=20%.",
    steps: [
      { stepNumber: 1, title: "Loss", explanation: "CP−SP=250." },
      { stepNumber: 2, title: "Loss%", explanation: "250/1250×100=20%.", result: "20%" },
    ],
    hint: "Loss% = (Loss/CP)×100.",
    keyConcepts: ["loss percent"],
    conceptsCovered: ["mth:7:ch08:profit-loss-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the SP if CP = ₹8,000 and profit% = 12.5%.  [NCERT Ex 8.3]",
    answer: "Profit = 12.5% of 8000 = 1000. SP = 8000+1000=₹9000.",
    steps: [
      { stepNumber: 1, title: "Profit amount", explanation: "0.125×8000=1000." },
      { stepNumber: 2, title: "SP", explanation: "8000+1000=9000.", result: "₹9000" },
    ],
    hint: "SP = CP + Profit.",
    keyConcepts: ["selling price", "profit"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find SI on ₹7,200 at 10% per annum for 2 years. Also find the total Amount.  [NCERT Ex 8.4]",
    answer: "SI = 7200×10×2/100=1440. Amount = 7200+1440=₹8640.",
    steps: [
      { stepNumber: 1, title: "SI", explanation: "SI=PRT/100=7200×10×2/100=1440." },
      { stepNumber: 2, title: "Amount", explanation: "7200+1440=8640.", result: "SI=₹1440; A=₹8640" },
    ],
    hint: "SI = PRT/100, then A = P + SI.",
    keyConcepts: ["simple interest", "amount"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "NCERT-Ex8.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In how many years will ₹5000 double itself at 10% SI per annum?  [NCERT Ex 8.4]",
    answer: "SI needed = 5000. SI = PRT/100 → 5000 = 5000×10×T/100 → 5000 = 500T → T = 10 years.",
    steps: [
      { stepNumber: 1, title: "SI to double", explanation: "SI = P = 5000." },
      { stepNumber: 2, title: "Find T", explanation: "5000×10×T/100=5000 → T=10 years.", result: "10 years" },
    ],
    hint: "To double, SI must equal the principal.",
    keyConcepts: ["finding time", "doubling principal"],
    conceptsCovered: ["mth:7:ch08:principal-rate-time"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "doubling-SI"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A shopkeeper buys 80 articles for ₹2,400 and sells each at ₹35. Find the profit or loss %.  [NCERT Ex 8.3]",
    answer: "CP per article = 2400/80=₹30. SP = ₹35. Profit = 5 per article. Profit% = 5/30×100=16.67%.",
    steps: [
      { stepNumber: 1, title: "CP per article", explanation: "2400/80=30." },
      { stepNumber: 2, title: "Profit per article", explanation: "35−30=5." },
      { stepNumber: 3, title: "Profit%", explanation: "5/30×100=16.67%.", result: "16.67% profit" },
    ],
    hint: "Find CP per article first.",
    keyConcepts: ["per-unit profit", "profit percent"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "per-unit-profit"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Find the rate at which ₹3600 gives SI of ₹1080 in 3 years.  [NCERT Ex 8.4]",
    answer: "SI=PRT/100 → 1080=3600×R×3/100 → 1080=108R → R=10% per annum.",
    steps: [
      { stepNumber: 1, title: "Apply formula", explanation: "1080=3600×R×3/100=108R → R=10%.", result: "R=10%" },
    ],
    hint: "Rearrange SI formula: R = SI×100/(P×T).",
    keyConcepts: ["finding rate", "simple interest"],
    conceptsCovered: ["mth:7:ch08:principal-rate-time"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "find-rate"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-017",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A dealer sold a TV for ₹25,850 at 6% profit. Find the CP.  [NCERT Ex 8.3]",
    answer: "SP = CP × 1.06 = 25850 → CP = 25850/1.06 = ₹24,387 (approx). Exact: CP = 25850×100/106 = ₹24387.74.",
    steps: [
      { stepNumber: 1, title: "CP formula", explanation: "CP = SP×100/(100+profit%) = 25850×100/106 ≈ ₹24388.", result: "≈₹24,388" },
    ],
    hint: "CP = SP × 100/(100 + profit%).",
    keyConcepts: ["finding CP from SP and profit%"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [{ error: "Subtracting 6% of SP instead of working backwards", correction: "CP = SP×100/(100+P%)." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "find-CP"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch08-nce-018",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Rani borrowed ₹12,500 at 12% per annum for 3 years from a bank. She lent it to a friend at 14% per annum. How much did she earn in 3 years?  [NCERT Ex 8.4]",
    answer: "SI paid = 12500×12×3/100=4500. SI received = 12500×14×3/100=5250. Net gain = 5250−4500=₹750.",
    steps: [
      { stepNumber: 1, title: "SI paid to bank", explanation: "12500×12×3/100=4500." },
      { stepNumber: 2, title: "SI received from friend", explanation: "12500×14×3/100=5250." },
      { stepNumber: 3, title: "Net gain", explanation: "5250−4500=750.", result: "₹750" },
    ],
    hint: "Calculate SI for both transactions and find the difference.",
    keyConcepts: ["simple interest", "arbitrage", "net gain"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch08", "SI-arbitrage"],
    source: "ncert",
  },

  // ── ICSE (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-ics-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A shopkeeper marks goods at 40% above cost price and allows 25% discount. Find his profit or loss percent.",
    answer: "Let CP=100. MP=140. Discount=25%×140=35. SP=140−35=105. Profit=5%. Profit% = 5%.",
    steps: [
      { stepNumber: 1, title: "Marked Price", explanation: "MP=100+40%=140." },
      { stepNumber: 2, title: "SP after discount", explanation: "SP=140×0.75=105." },
      { stepNumber: 3, title: "Profit%", explanation: "Profit=5 on CP=100 → 5%.", result: "5% profit" },
    ],
    hint: "Use CP=100 as the base for easy calculation.",
    keyConcepts: ["markup", "discount", "net profit"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch08", "markup-discount-icse"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch08-ics-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "What principal will amount to ₹16,000 in 5 years at 8% SI per annum?",
    answer: "A = P(1+RT/100) → 16000 = P(1+0.08×5) = 1.4P → P = 16000/1.4 = ₹11,428.57 ≈ ₹11,429.",
    steps: [
      { stepNumber: 1, title: "Amount formula", explanation: "A=P+PRT/100=P(1+40/100)=1.4P=16000." },
      { stepNumber: 2, title: "P", explanation: "P=16000/1.4≈11429.", result: "₹11,429" },
    ],
    hint: "A = P(1 + RT/100).",
    keyConcepts: ["finding principal", "amount formula"],
    conceptsCovered: ["mth:7:ch08:principal-rate-time"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch08", "find-principal"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch08-ics-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A trader sold two articles at ₹2400 each. On one he gained 20% and on the other he lost 20%. Find his overall profit or loss percentage.",
    answer: "Article 1 (gain 20%): CP = 2400/1.2=₹2000. Article 2 (loss 20%): CP = 2400/0.8=₹3000. Total CP=5000. Total SP=4800. Loss=200. Loss%=200/5000×100=4%.",
    steps: [
      { stepNumber: 1, title: "CP of article 1", explanation: "2400/1.2=2000." },
      { stepNumber: 2, title: "CP of article 2", explanation: "2400/0.8=3000." },
      { stepNumber: 3, title: "Overall", explanation: "CP=5000, SP=4800, Loss=200, Loss%=4%.", result: "4% loss" },
    ],
    hint: "Always compute CP from SP and % to find actual figures.",
    keyConcepts: ["two-article problem", "overall loss"],
    conceptsCovered: ["mth:7:ch08:profit-loss-definition"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking gains cancel losses", correction: "The two CPs are different, so the loss exceeds the gain in absolute terms." }],
    tags: ["icse", "class7", "ch08", "two-article-loss"],
    source: "icse",
  },

  // ── COMPETENCY (t2) ──────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-cmp-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "A pen costing ₹50 is sold for ₹65. What is the profit percentage?",
    options: ["15%", "20%", "25%", "30%"],
    answer: "30%",
    steps: [{ stepNumber: 1, title: "Profit%", explanation: "15/50×100=30%." }],
    hint: "Profit% = (SP−CP)/CP × 100.",
    keyConcepts: ["profit percent"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "MCQ-profit"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simple Interest on ₹4000 for 3 years at 5% per annum is:",
    options: ["₹200", "₹400", "₹600", "₹800"],
    answer: "₹600",
    steps: [{ stepNumber: 1, title: "SI", explanation: "4000×5×3/100=600." }],
    hint: "SI = PRT/100.",
    keyConcepts: ["simple interest"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "MCQ-SI"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Ramesh borrowed ₹10,000 from a bank at 9% SI and lent ₹5000 to a friend at 12% SI (both for 2 years). Find his net gain.",
    answer: "SI paid = 10000×9×2/100=1800. SI received = 5000×12×2/100=1200. Net = 1200−1800=−600. Net loss of ₹600.",
    steps: [
      { stepNumber: 1, title: "SI paid", explanation: "1800." },
      { stepNumber: 2, title: "SI received", explanation: "1200." },
      { stepNumber: 3, title: "Net", explanation: "1200−1800=−600. Loss of ₹600.", result: "₹600 net loss" },
    ],
    hint: "He pays interest on the full ₹10,000 but earns on only ₹5,000.",
    keyConcepts: ["net interest", "borrowing and lending"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [{ error: "Comparing rates without amounts", correction: "Compute actual SI in rupees for each transaction." }],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "net-SI"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 10,
    question: "A shopkeeper buys mangoes at ₹20 per kg. He mixes good and rotten mangoes and sells all at ₹24 per kg. 10% of the mangoes are rotten and unsellable. If he buys 100 kg, does he make a profit? Find profit/loss%.",
    answer: "CP for 100 kg = ₹2000. Sellable mangoes = 90 kg. Revenue = 90×24=₹2160. Profit=2160−2000=₹160. Profit%=160/2000×100=8%.",
    steps: [
      { stepNumber: 1, title: "CP", explanation: "100×20=₹2000." },
      { stepNumber: 2, title: "Sellable", explanation: "90 kg at ₹24 → 2160." },
      { stepNumber: 3, title: "Profit%", explanation: "160/2000×100=8%.", result: "8% profit" },
    ],
    hint: "Only sellable mangoes generate revenue.",
    keyConcepts: ["spoilage problem", "effective profit"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [{ error: "Computing profit on sellable kg only", correction: "CP is for all 100 kg; revenue from 90 kg." }],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "mango-spoilage"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "At what rate of SI will ₹8000 amount to ₹9000 in 2.5 years?",
    options: ["4%", "5%", "6%", "7%"],
    answer: "5%",
    steps: [{ stepNumber: 1, title: "Find R", explanation: "SI=1000; 1000=8000×R×2.5/100=200R → R=5%." }],
    hint: "SI = A − P, then use SI = PRT/100.",
    keyConcepts: ["finding rate", "simple interest"],
    conceptsCovered: ["mth:7:ch08:principal-rate-time"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "find-rate-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A television set was marked at ₹18,000. A customer bought it after a 12% discount. She then paid 5% GST on the discounted price. How much did she pay in total?",
    answer: "Discounted price = 18000×0.88=₹15840. GST=5%×15840=₹792. Total=15840+792=₹16632.",
    steps: [
      { stepNumber: 1, title: "After discount", explanation: "18000×0.88=15840." },
      { stepNumber: 2, title: "GST", explanation: "0.05×15840=792." },
      { stepNumber: 3, title: "Total", explanation: "16632.", result: "₹16,632" },
    ],
    hint: "GST is applied on the discounted price.",
    keyConcepts: ["discount", "GST", "total price"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [{ error: "Applying GST on original price", correction: "GST is applied after discount." }],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "GST-discount"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Reema deposited ₹5000 in a bank at 6% SI for 18 months. Find the interest earned.",
    answer: "T = 18 months = 1.5 years. SI = 5000×6×1.5/100 = ₹450.",
    steps: [
      { stepNumber: 1, title: "Convert time", explanation: "18 months = 1.5 years." },
      { stepNumber: 2, title: "SI", explanation: "5000×6×1.5/100=450.", result: "₹450" },
    ],
    hint: "Convert months to years before applying the formula.",
    keyConcepts: ["simple interest", "time conversion"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [{ error: "Using T=18 without converting to years", correction: "18 months = 18/12 = 1.5 years." }],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "SI-months"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch08-cmp-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A merchant buys 200 eggs at ₹6 each. 20 are broken and discarded. He sells the rest at ₹8 each. Find profit/loss% and whether it makes sense to continue this business.",
    answer: "CP=200×6=₹1200. Sellable=180 eggs. Revenue=180×8=₹1440. Profit=240. Profit%=240/1200×100=20%. Yes, a 20% profit margin is reasonable to continue.",
    steps: [
      { stepNumber: 1, title: "CP", explanation: "1200." },
      { stepNumber: 2, title: "Revenue", explanation: "180×8=1440." },
      { stepNumber: 3, title: "Profit%", explanation: "20%.", result: "20% profit; business viable" },
    ],
    hint: "Account for broken eggs when computing revenue.",
    keyConcepts: ["spoilage", "profit analysis", "business reasoning"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch08", "egg-business"],
    source: "competency",
  },

  // ── HOTS (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-hot-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A trader sells two articles. On the first, he gains 15% and on the second he loses 15%. Both articles are sold at ₹1,955 each. Find the total profit or loss.",
    answer: "CP₁=1955/1.15=₹1700. CP₂=1955/0.85=₹2300. Total CP=4000. Total SP=3910. Loss=90. Loss%=90/4000×100=2.25%.",
    steps: [
      { stepNumber: 1, title: "CP₁", explanation: "1955/1.15=1700." },
      { stepNumber: 2, title: "CP₂", explanation: "1955/0.85=2300." },
      { stepNumber: 3, title: "Loss%", explanation: "Loss=90 on 4000 → 2.25%.", result: "2.25% loss" },
    ],
    hint: "The overall result when selling at equal SPs with equal % gain/loss is always a loss.",
    keyConcepts: ["equal SP, equal % problem", "overall loss"],
    conceptsCovered: ["mth:7:ch08:profit-loss-definition"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking gains cancel losses since they're equal percentages", correction: "With equal SPs, the CP₂ > CP₁, causing a net loss." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "equal-percent-gain-loss"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "At what profit % should a product be sold so that after giving a 10% discount on the marked price, the profit on cost price is still 8%?",
    answer: "Let CP=100. For 8% profit: SP=108. Discount=10% of MP → SP=0.9×MP=108 → MP=120. So the product must be marked at 20% above CP. The answer: mark 20% above CP, give 10% discount → 8% profit on CP.",
    steps: [
      { stepNumber: 1, title: "Required SP", explanation: "SP=108 (8% profit on CP=100)." },
      { stepNumber: 2, title: "Find MP", explanation: "0.9×MP=108 → MP=120." },
      { stepNumber: 3, title: "Markup%", explanation: "MP=120 on CP=100 → 20% markup.", result: "Mark 20% above CP" },
    ],
    hint: "Work backwards from the desired SP.",
    keyConcepts: ["markup and discount", "desired profit"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "markup-hots"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 10,
    question: "Design a loan scheme: a principal of ₹P, a rate of R%, and time T years such that the SI is exactly 50% of the principal. Show three different valid combinations of R and T.",
    answer: "SI = 50% of P → SI/P = 1/2 → RT/100 = 1/2 → RT = 50. Valid combinations: (1) R=5%, T=10 years; (2) R=10%, T=5 years; (3) R=25%, T=2 years. All satisfy RT=50.",
    steps: [
      { stepNumber: 1, title: "Condition", explanation: "SI=P/2 → PRT/100=P/2 → RT=50." },
      { stepNumber: 2, title: "Combinations", explanation: "R=5,T=10; R=10,T=5; R=25,T=2." },
    ],
    hint: "SI = P/2 → RT = 50. Find pairs (R, T).",
    keyConcepts: ["SI = 50% principal", "multiple combinations"],
    conceptsCovered: ["mth:7:ch08:principal-rate-time"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "design-SI-scheme"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A milkman buys milk at ₹25/litre. He adds water (cost zero) and sells 25% more quantity at ₹24/litre. Find his profit %.",
    answer: "Buy 100 L at ₹25 → CP=2500. Sell 125 L at ₹24 → Revenue=3000. Profit=500. Profit%=500/2500×100=20%.",
    steps: [
      { stepNumber: 1, title: "CP", explanation: "100L×₹25=₹2500." },
      { stepNumber: 2, title: "Revenue", explanation: "125L×₹24=₹3000." },
      { stepNumber: 3, title: "Profit%", explanation: "500/2500×100=20%.", result: "20%" },
    ],
    hint: "Adulteration increases volume at no extra cost.",
    keyConcepts: ["adulteration profit", "effective profit"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "adulteration-profit"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch08-hot-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 12,
    question: "A person invests ₹20,000: 40% at 6% SI and 60% at 8% SI for 3 years. Another person invests all ₹20,000 at 7% SI for 3 years. Who earns more interest and by how much?",
    answer: "Person 1: SI₁=8000×6×3/100=1440; SI₂=12000×8×3/100=2880. Total=4320. Person 2: SI=20000×7×3/100=4200. Person 1 earns ₹120 more.",
    steps: [
      { stepNumber: 1, title: "Person 1", explanation: "8000×0.06×3=1440; 12000×0.08×3=2880. Total=4320." },
      { stepNumber: 2, title: "Person 2", explanation: "20000×0.07×3=4200." },
      { stepNumber: 3, title: "Difference", explanation: "4320−4200=120. P1 earns ₹120 more.", result: "Person 1 by ₹120" },
    ],
    hint: "Calculate SI separately for each tranche of Person 1.",
    keyConcepts: ["split investment", "comparison of SI"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch08", "split-investment"],
    source: "hots",
  },

  // ── PREVIOUS YEAR (t2) ───────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch08-pyq-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A book costs ₹240 and is sold at 10% profit. Find the SP.  [CBSE 2019]",
    answer: "SP=240×1.10=₹264.",
    steps: [{ stepNumber: 1, title: "SP", explanation: "240×1.1=264.", result: "₹264" }],
    hint: "SP = CP × (1 + profit/100).",
    keyConcepts: ["selling price with profit"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the SI on ₹5000 at 8% per annum for 3 years.  [SA-I 2020]",
    answer: "SI=5000×8×3/100=₹1200.",
    steps: [{ stepNumber: 1, title: "SI", explanation: "1200.", result: "₹1200" }],
    hint: "SI=PRT/100.",
    keyConcepts: ["simple interest"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A radio was bought for ₹1400 and sold at a loss of 5%. Find the SP.  [CBSE 2021]",
    answer: "SP=1400×0.95=₹1330.",
    steps: [{ stepNumber: 1, title: "SP", explanation: "1400×0.95=1330.", result: "₹1330" }],
    hint: "SP = CP × (1 − loss/100).",
    keyConcepts: ["selling price with loss"],
    conceptsCovered: ["mth:7:ch08:selling-price-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A sum amounts to ₹7,260 in 2 years at 10% SI. Find the sum.  [CBSE 2022]",
    answer: "A=P(1+RT/100)=P(1+0.2)=1.2P=7260 → P=₹6050.",
    steps: [
      { stepNumber: 1, title: "Amount formula", explanation: "1.2P=7260 → P=6050.", result: "₹6050" },
    ],
    hint: "A = P(1 + RT/100).",
    keyConcepts: ["finding principal from amount"],
    conceptsCovered: ["mth:7:ch08:principal-rate-time"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A shopkeeper bought 150 oranges at ₹2 each and sold 100 at ₹3 and the remaining at ₹1 each. Find his profit or loss %.  [ICSE 2021]",
    answer: "CP=150×2=₹300. Revenue=100×3+50×1=300+50=₹350. Profit=50. Profit%=50/300×100=16.67%.",
    steps: [
      { stepNumber: 1, title: "CP", explanation: "300." },
      { stepNumber: 2, title: "Revenue", explanation: "350." },
      { stepNumber: 3, title: "Profit%", explanation: "50/300×100=16.67%.", result: "16.67% profit" },
    ],
    hint: "Compute total revenue from two different SP values.",
    keyConcepts: ["multiple selling prices", "overall profit"],
    conceptsCovered: ["mth:7:ch08:profit-percent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "ICSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch08-pyq-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Profit, Loss, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 5, estimatedTimeMinutes: 8,
    question: "A man borrowed ₹20,000 at 12% per annum SI. He repaid ₹8,000 after 2 years. Find the outstanding amount after the repayment, and the total interest he would pay if he clears the remaining amount 3 years later.  [CBSE 2022]",
    answer: "SI on 20000 for 2 yr = 20000×12×2/100=4800. Amount after 2 yr=24800. After paying 8000: outstanding=16800. SI on 16800 for 3 yr=16800×12×3/100=6048. Total paid=8000+16800+6048=₹30848.",
    steps: [
      { stepNumber: 1, title: "Amount after 2 yr", explanation: "20000+4800=24800." },
      { stepNumber: 2, title: "Outstanding", explanation: "24800−8000=16800." },
      { stepNumber: 3, title: "Further SI", explanation: "16800×0.12×3=6048." },
      { stepNumber: 4, title: "Total paid", explanation: "8000+16800+6048=30848.", result: "₹30,848" },
    ],
    hint: "Deduct payment from outstanding amount, then compute SI on new principal.",
    keyConcepts: ["partial repayment", "outstanding principal"],
    conceptsCovered: ["mth:7:ch08:simple-interest-formula"],
    prerequisites: [],
    commonErrors: [{ error: "Computing SI on the original principal for all 5 years", correction: "After repayment, the new principal is the outstanding balance." }],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch08", "CBSE2022", "partial-repayment"],
    source: "previous-year",
  },

];
