// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 9: Rational Numbers
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Definition and Representation  — 37 q
 *   t2 Operations on Rational Numbers — 38 q
 *
 * Concept nodes:
 *   mth:7:ch09:rational-number-definition
 *   mth:7:ch09:negative-rational
 *   mth:7:ch09:rational-on-number-line
 *   mth:7:ch09:rational-addition
 *   mth:7:ch09:rational-multiplication
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH09_RATIONAL_NUMBERS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Definition and Representation
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-con-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: A rational number is a number that can be expressed in the form p/q, where p and q are integers and q ≠ 0.",
    answer: "True. Every rational number can be written as a fraction p/q with integer numerator p and non-zero integer denominator q. Examples: 3/4, −5/7, 0/1.",
    steps: [{ stepNumber: 1, title: "Definition", explanation: "Rational = p/q, p,q ∈ ℤ, q≠0." }],
    hint: "The word 'rational' comes from 'ratio'.",
    keyConcepts: ["rational number definition", "p/q form"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "definition"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Which of the following are rational numbers: (a) 7  (b) −3/5  (c) √2  (d) 0?",
    answer: "(a) 7 = 7/1 — rational. (b) −3/5 — rational. (c) √2 — irrational (cannot be expressed as p/q). (d) 0 = 0/1 — rational.",
    steps: [
      { stepNumber: 1, title: "Check each", explanation: "7=7/1✓; −3/5✓; √2≈1.41421... non-terminating non-repeating, not p/q; 0=0/1✓." },
    ],
    hint: "√2 cannot be expressed as a fraction.",
    keyConcepts: ["rational vs irrational", "classification"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "identify-rational"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Every integer is a rational number.",
    answer: "True. Any integer n can be written as n/1, which is in the form p/q with q=1≠0. So all integers (positive, negative, and zero) are rational numbers.",
    steps: [{ stepNumber: 1, title: "Integer as rational", explanation: "n = n/1. Example: −7 = −7/1, which is rational." }],
    hint: "Write the integer with denominator 1.",
    keyConcepts: ["integers as rationals", "subset relationship"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "integers-rational"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is a negative rational number? Give two examples.",
    answer: "A rational number p/q is negative when p and q have opposite signs. Examples: −3/5 (negative p, positive q) and 7/−4 = −7/4 (positive p, negative q). By convention, the negative sign is written in the numerator.",
    steps: [
      { stepNumber: 1, title: "Definition", explanation: "p/q < 0 when p and q have opposite signs." },
      { stepNumber: 2, title: "Examples", explanation: "−3/5 and −7/4." },
    ],
    hint: "Negative rational: numerator and denominator have opposite signs.",
    keyConcepts: ["negative rational number"],
    conceptsCovered: ["mth:7:ch09:negative-rational"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "negative-rational"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: Between any two rational numbers, there is always another rational number.",
    answer: "True. This is called the density property of rational numbers. Between a/b and c/d, the number (a/b + c/d)/2 is always a rational number that lies strictly between them. Hence there are infinitely many rationals between any two rationals.",
    steps: [
      { stepNumber: 1, title: "Example", explanation: "Between 1/3 and 1/2: average = (1/3+1/2)/2 = (5/6)/2 = 5/12. And 1/3 < 5/12 < 1/2. ✓" },
      { stepNumber: 2, title: "Density property", explanation: "This process can be repeated infinitely, confirming infinitely many rationals between any two." },
    ],
    hint: "The average of two rationals is rational and lies between them.",
    keyConcepts: ["density of rationals", "between two rationals"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "density-property"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Represent −2/3 and 4/5 on a number line and indicate which is greater.",
    answer: "On the number line: −2/3 ≈ −0.67 is to the left of 0, and 4/5 = 0.8 is to the right of 0. Since 4/5 > 0 > −2/3, clearly 4/5 > −2/3.",
    steps: [
      { stepNumber: 1, title: "Convert to decimals", explanation: "−2/3≈−0.67; 4/5=0.8." },
      { stepNumber: 2, title: "Compare", explanation: "0.8 > −0.67, so 4/5 > −2/3." },
    ],
    hint: "Positive numbers are always greater than negative numbers.",
    keyConcepts: ["number line", "comparing rationals"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "number-line"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-nce-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "List four rational numbers between −1 and 0.  [NCERT Ex 9.1]",
    answer: "−1/5, −2/5, −3/5, −4/5 (all lie strictly between −1 and 0).",
    steps: [
      { stepNumber: 1, title: "Between −1 and 0", explanation: "Negative fractions with denominator 5: −1/5, −2/5, −3/5, −4/5 all satisfy −1<x<0." },
    ],
    hint: "Divide the interval (−1, 0) into smaller parts.",
    keyConcepts: ["rationals between two integers"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "NCERT-Ex9.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write three equivalent rational numbers for 2/5.  [NCERT Ex 9.1]",
    answer: "4/10, 6/15, 8/20 (multiply numerator and denominator by the same non-zero integer).",
    steps: [
      { stepNumber: 1, title: "Multiply by 2, 3, 4", explanation: "2/5 = 4/10 = 6/15 = 8/20." },
    ],
    hint: "Equivalent rationals: multiply both numerator and denominator by the same integer.",
    keyConcepts: ["equivalent rational numbers"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "equivalent-rationals"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the rational number −6/10 in standard form.  [NCERT Ex 9.1]",
    answer: "GCD(6, 10) = 2. −6/10 = (−6÷2)/(10÷2) = −3/5. Standard form: −3/5 (denominator is positive and GCD = 1).",
    steps: [
      { stepNumber: 1, title: "Find GCD", explanation: "GCD(6,10)=2." },
      { stepNumber: 2, title: "Divide", explanation: "−6/10 = −3/5.", result: "−3/5" },
    ],
    hint: "Standard form: positive denominator, GCD(p,q)=1.",
    keyConcepts: ["standard form of rational number", "simplification"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "standard-form"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Compare: −3/7 and −5/7. Which is greater?  [NCERT Ex 9.1]",
    answer: "Both have the same denominator. −3 > −5 (on number line). So −3/7 > −5/7.",
    steps: [
      { stepNumber: 1, title: "Same denominator", explanation: "Compare numerators: −3 > −5, so −3/7 > −5/7." },
    ],
    hint: "For negative fractions with same denominator, the one with the larger (less negative) numerator is greater.",
    keyConcepts: ["comparing negative rationals"],
    conceptsCovered: ["mth:7:ch09:negative-rational"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking −5/7 > −3/7 because 5 > 3", correction: "For negatives, a larger magnitude means a smaller value." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "comparing-negative"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Compare −3/4 and −5/6.  [NCERT Ex 9.1]",
    answer: "LCM(4,6)=12. −3/4=−9/12 and −5/6=−10/12. Since −9 > −10, we have −9/12 > −10/12. So −3/4 > −5/6.",
    steps: [
      { stepNumber: 1, title: "Common denominator", explanation: "−9/12 vs −10/12." },
      { stepNumber: 2, title: "Compare", explanation: "−9>−10 → −3/4>−5/6.", result: "−3/4 > −5/6" },
    ],
    hint: "Find LCM of denominators, then compare numerators.",
    keyConcepts: ["comparing unlike rationals", "LCM method"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "unlike-comparison"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find five rational numbers between 1/4 and 1/2.  [NCERT Ex 9.1]",
    answer: "Multiply by 12: 1/4=3/12 and 1/2=6/12. Five rationals between 3/12 and 6/12: 4/12=1/3, 5/12, and also 7/24, 8/24, 9/24, etc.",
    steps: [
      { stepNumber: 1, title: "Common form", explanation: "3/12 and 6/12. Rationals between: 4/12, 5/12 (only 2 available as integers in range). Use denominator 100: 26/100, 30/100, 35/100, 40/100, 45/100." },
    ],
    hint: "Convert to a common denominator that allows 5 integers in between.",
    keyConcepts: ["finding rationals between two rationals"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "between-rationals"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Arrange in ascending order: −3/4, 5/−8, −1/2, 7/−16.  [NCERT Ex 9.1]",
    answer: "Convert to standard form: −3/4, −5/8, −1/2, −7/16. LCD=16: −12/16, −10/16, −8/16, −7/16. Ascending: −3/4 < −5/8 < −1/2 < −7/16.",
    steps: [
      { stepNumber: 1, title: "Standard form", explanation: "−3/4, −5/8, −1/2, −7/16." },
      { stepNumber: 2, title: "LCD=16", explanation: "−12/16, −10/16, −8/16, −7/16." },
      { stepNumber: 3, title: "Ascending", explanation: "−12<−10<−8<−7 → −3/4<−5/8<−1/2<−7/16.", result: "−3/4<−5/8<−1/2<−7/16" },
    ],
    hint: "Convert all to positive denominator first, then find LCD.",
    keyConcepts: ["ordering negative rationals"],
    conceptsCovered: ["mth:7:ch09:negative-rational"],
    prerequisites: [],
    commonErrors: [{ error: "Not converting 5/−8 to standard form −5/8", correction: "Always move the negative sign to the numerator." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "ascending-order"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the additive inverse of: (a) 3/8  (b) −7/11.  [NCERT Ex 9.1]",
    answer: "(a) Additive inverse of 3/8 is −3/8. (b) Additive inverse of −7/11 is 7/11.",
    steps: [
      { stepNumber: 1, title: "Additive inverse", explanation: "Add the rational to its inverse to get 0. So inverse of p/q is −p/q." },
    ],
    hint: "Additive inverse = negation.",
    keyConcepts: ["additive inverse"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "additive-inverse"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is the multiplicative inverse (reciprocal) of: (a) 5/7  (b) −3/4?  [NCERT Ex 9.1]",
    answer: "(a) 7/5  (b) −4/3.",
    steps: [
      { stepNumber: 1, title: "Reciprocal", explanation: "Flip numerator and denominator. Sign stays: −3/4 → −4/3." },
    ],
    hint: "Reciprocal of p/q is q/p; the sign is preserved.",
    keyConcepts: ["multiplicative inverse", "reciprocal"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [{ error: "Changing sign when finding reciprocal", correction: "Reciprocal keeps the same sign." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "reciprocal"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-ics-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Express the following as rational numbers in standard form: (a) −18/27  (b) 36/−48.",
    answer: "(a) GCD(18,27)=9. −18/27=−2/3. (b) 36/−48=−36/48; GCD=12; −3/4.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "−18/27 ÷ 9/9 = −2/3." },
      { stepNumber: 2, title: "(b)", explanation: "36/−48=−36/48 ÷ 12/12 = −3/4.", result: "−2/3 and −3/4" },
    ],
    hint: "Move negative sign to numerator, then simplify by GCD.",
    keyConcepts: ["standard form", "simplification"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch09", "standard-form-icse"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch09-ics-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Find ten rational numbers between −3/5 and 2/5.",
    answer: "Convert: −3/5=−6/10 and 2/5=4/10. Use denominator 100: −60/100 to 40/100. Ten rationals: −50/100, −40/100, −30/100, −20/100, −10/100, 0, 10/100, 20/100, 30/100, 40/100 (excluding endpoints).",
    steps: [
      { stepNumber: 1, title: "Common denominator", explanation: "Use /100 for fine granularity." },
      { stepNumber: 2, title: "Ten values", explanation: "−1/2,−2/5,−3/10,−1/5,−1/10,0,1/10,1/5,3/10,2/5 (exc. endpoint)." },
    ],
    hint: "Multiply denominators by a large enough number to get at least 10 integer gaps.",
    keyConcepts: ["density of rationals", "finding multiple rationals"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch09", "ten-rationals"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch09-ics-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Arrange in descending order: 3/5, −1/3, 2/−5, 7/10.",
    answer: "Standard form: 3/5, −1/3, −2/5, 7/10. LCD=30: 18/30, −10/30, −12/30, 21/30. Descending: 7/10 > 3/5 > −1/3 > −2/5.",
    steps: [
      { stepNumber: 1, title: "Standard form", explanation: "2/−5 = −2/5." },
      { stepNumber: 2, title: "LCD=30", explanation: "21/30 > 18/30 > −10/30 > −12/30." },
      { stepNumber: 3, title: "Descending", explanation: "7/10 > 3/5 > −1/3 > −2/5.", result: "7/10 > 3/5 > −1/3 > −2/5" },
    ],
    hint: "Positive rationals > negative rationals always.",
    keyConcepts: ["descending order", "comparing rationals"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch09", "descending-order"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch09-ics-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Mark the following on a number line and identify which is closest to 0: −7/8, 3/4, −1/4.",
    answer: "Decimal values: −7/8=−0.875; 3/4=0.75; −1/4=−0.25. Distance from 0: 0.875, 0.75, 0.25. Closest to 0 is −1/4.",
    steps: [
      { stepNumber: 1, title: "Distances from 0", explanation: "0.875, 0.75, 0.25." },
      { stepNumber: 2, title: "Minimum", explanation: "0.25 → −1/4 is closest to 0.", result: "−1/4" },
    ],
    hint: "Distance from 0 = absolute value.",
    keyConcepts: ["absolute value", "number line", "distance from 0"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch09", "closest-to-zero"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-cmp-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which of the following is a rational number?",
    options: ["√5", "√9", "π", "e"],
    answer: "√9",
    steps: [{ stepNumber: 1, title: "Check", explanation: "√9=3=3/1 → rational. Others are irrational." }],
    hint: "√9 = 3, which is an integer.",
    keyConcepts: ["rational identification"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "identify-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which is the standard form of −12/18?",
    options: ["−12/18", "−2/3", "2/−3", "−6/9"],
    answer: "−2/3",
    steps: [{ stepNumber: 1, title: "Simplify", explanation: "GCD(12,18)=6. −12/18=−2/3." }],
    hint: "Divide both by GCD, denominator positive.",
    keyConcepts: ["standard form"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "standard-form-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A recipe uses 3/4 cup of sugar and another uses 5/6 cup. Which recipe uses more sugar? Find the difference.",
    answer: "3/4=9/12; 5/6=10/12. 10/12>9/12 → second recipe uses more. Difference=1/12 cup.",
    steps: [
      { stepNumber: 1, title: "Compare", explanation: "9/12<10/12 → second uses more." },
      { stepNumber: 2, title: "Difference", explanation: "10/12−9/12=1/12.", result: "Second; by 1/12 cup" },
    ],
    hint: "Find LCM to compare and subtract.",
    keyConcepts: ["comparing rationals", "real-life"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "recipe-context"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Which of the following represents a rational number between −2 and −1?",
    options: ["−5/2", "−3/2", "3/2", "−1/2"],
    answer: "−3/2",
    steps: [{ stepNumber: 1, title: "Check", explanation: "−3/2=−1.5, which is between −2 and −1. ✓" }],
    hint: "−3/2 = −1.5 lies between −2 and −1.",
    keyConcepts: ["locating rationals on number line"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "between-integers"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A submarine is at −3/4 km below sea level. It descends another −1/3 km. Where is it now? Is it still within the safe diving limit of −1.5 km?",
    answer: "Position = −3/4 + (−1/3) = −9/12 − 4/12 = −13/12 ≈ −1.083 km. Safe limit = −1.5 km. Since −1.083 > −1.5, it is still within safe limits.",
    steps: [
      { stepNumber: 1, title: "New position", explanation: "−3/4−1/3=−9/12−4/12=−13/12." },
      { stepNumber: 2, title: "Compare", explanation: "−13/12≈−1.083 > −1.5. Within safe limits.", result: "−13/12 km; safe" },
    ],
    hint: "Below sea level = negative. Compare by converting to decimals.",
    keyConcepts: ["real-life rational numbers", "comparing with context"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "submarine-context"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Temperature in Shimla on Monday = −3/2°C, Tuesday = −5/4°C, Wednesday = 1/4°C. (a) Which day is coldest? (b) Find the average temperature. (c) On which days is the temperature below 0°C?",
    answer: "(a) −3/2=−1.5°C, −5/4=−1.25°C, 1/4=0.25°C. Coldest: Monday. (b) Average=(−3/2−5/4+1/4)/3=(−6/4−5/4+1/4)/3=(−10/4)/3=−10/12=−5/6°C. (c) Monday and Tuesday are below 0°C.",
    steps: [
      { stepNumber: 1, title: "Convert to decimals", explanation: "−1.5, −1.25, 0.25." },
      { stepNumber: 2, title: "Coldest", explanation: "Monday (−1.5°C)." },
      { stepNumber: 3, title: "Average", explanation: "Sum=−10/4. Average=−10/12=−5/6°C." },
      { stepNumber: 4, title: "Below 0°C", explanation: "Monday and Tuesday.", result: "Monday coldest; avg=−5/6°C; Mon+Tue below 0" },
    ],
    hint: "Convert to decimals for quick comparison.",
    keyConcepts: ["temperature context", "average", "comparing rationals"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "temperature-case-study"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The additive inverse of −5/9 is:",
    options: ["5/9", "9/5", "−9/5", "−5/9"],
    answer: "5/9",
    steps: [{ stepNumber: 1, title: "Additive inverse", explanation: "Inverse of −5/9 is 5/9 since −5/9+5/9=0." }],
    hint: "Sum of a number and its additive inverse = 0.",
    keyConcepts: ["additive inverse"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "additive-inverse-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A student says '0 is not a rational number because 0/5 has zero numerator'. Is the student correct? Justify.",
    answer: "The student is incorrect. 0 IS a rational number: 0 = 0/1 = 0/5 = 0/7, all in the form p/q with q≠0. The numerator can be zero; the restriction is only on the denominator (q≠0).",
    steps: [
      { stepNumber: 1, title: "Check definition", explanation: "p/q with q≠0. p can be 0." },
      { stepNumber: 2, title: "Conclusion", explanation: "0=0/1 is rational. Student is wrong.", result: "Student is incorrect" },
    ],
    hint: "Only the denominator cannot be zero.",
    keyConcepts: ["zero as rational", "p vs q restriction"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "zero-rational"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-hot-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove that between any two distinct rational numbers p/q and r/s (p/q < r/s), the number (p/q + r/s)/2 is a rational number that lies strictly between them.",
    answer: "Let a = p/q and b = r/s, with a < b. Midpoint m = (a+b)/2. Since a,b are rational, a+b is rational (sum of rationals) and (a+b)/2 is rational (quotient with denominator 2≠0). Also, a < (a+b)/2 < b iff 2a < a+b < 2b iff a < b (true by assumption). So m is rational and strictly between a and b. QED.",
    steps: [
      { stepNumber: 1, title: "Midpoint is rational", explanation: "Sum/2 of two rationals is rational." },
      { stepNumber: 2, title: "Lies between", explanation: "a<m<b ⟺ a<b. ✓ Proved." },
    ],
    hint: "Midpoint = (a+b)/2. Show it is rational and strictly between a and b.",
    keyConcepts: ["density proof", "rational midpoint"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [{ error: "Not proving m is strictly between a and b", correction: "Show a < m < b algebraically." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "density-proof"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Ravi says '2/3 = 4/6 = 6/9' and concludes these are three different rational numbers. Is he correct? What mathematical concept does this illustrate?",
    answer: "Ravi is incorrect. 2/3 = 4/6 = 6/9 are all equivalent representations of the SAME rational number. They represent the same point on the number line. This illustrates the concept of equivalent fractions / equivalence class: each rational number has infinitely many equivalent representations but is a unique value.",
    steps: [
      { stepNumber: 1, title: "Verify equivalence", explanation: "2/3=4/6 (×2); =6/9 (×3). All equal 0.666..." },
      { stepNumber: 2, title: "Concept", explanation: "Same rational number, different representations. Equivalence class." },
    ],
    hint: "Cross-multiply to check equality.",
    keyConcepts: ["equivalent fractions", "unique rational number"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "equivalence-class"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 7,
    question: "Is 0.333... (recurring) a rational number? Justify with the p/q form.",
    answer: "Yes. Let x = 0.333... Then 10x = 3.333... Subtracting: 9x = 3 → x = 3/9 = 1/3. So 0.333... = 1/3, which is in p/q form with q≠0. Hence it is rational.",
    steps: [
      { stepNumber: 1, title: "Let x = 0.333...", explanation: "10x = 3.333..." },
      { stepNumber: 2, title: "Subtract", explanation: "10x − x = 3 → 9x = 3 → x = 1/3.", result: "1/3; rational" },
    ],
    hint: "Multiply by 10 to shift the decimal, then subtract.",
    keyConcepts: ["recurring decimal to fraction", "rational number"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking infinite decimals are irrational", correction: "Recurring (repeating) decimals are rational; only non-recurring non-terminating decimals are irrational." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "recurring-decimal"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Create your own rational number p/q where the decimal expansion terminates at exactly 3 decimal places. Show it is rational and explain why it terminates.",
    answer: "Example: 3/8 = 0.375 (exactly 3 decimal places). Verify: 3÷8=0.375. It terminates because 8 = 2³, and the denominator in lowest terms has only factors of 2 and/or 5. When denominator = 2ⁿ×5ᵐ, the decimal terminates in max(n,m) places.",
    steps: [
      { stepNumber: 1, title: "Choose p/q", explanation: "3/8: denominator = 2³ → terminates in 3 places." },
      { stepNumber: 2, title: "Verify", explanation: "3/8=0.375. Exactly 3 decimal places. ✓" },
    ],
    hint: "Terminating decimals have denominators (in lowest terms) with only prime factors 2 and 5.",
    keyConcepts: ["terminating decimal", "denominator criterion"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "create-terminating"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Is the set of rational numbers closed under division? Explain with examples and state one important exception.",
    answer: "Rational numbers are closed under division EXCEPT when dividing by zero. If a/b and c/d are rationals (c/d ≠ 0), then (a/b)÷(c/d)=(a/b)×(d/c)=ad/bc is rational (bc≠0 since b,c≠0). Exception: division by 0 is undefined. Example: (3/4)÷(1/2)=3/2 (rational). But (3/4)÷0 is undefined.",
    steps: [
      { stepNumber: 1, title: "General case", explanation: "a/b ÷ c/d = ad/bc. Rational if c≠0." },
      { stepNumber: 2, title: "Exception", explanation: "Division by 0 (i.e., c/d=0 means c=0) is undefined." },
    ],
    hint: "Dividing by a rational ≠ 0 is equivalent to multiplying by its reciprocal.",
    keyConcepts: ["closure under division", "division by zero"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [{ error: "Stating rationals are always closed under division", correction: "Division by zero is not defined and breaks closure." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "closure-division"],
    source: "hots",
  },

  // ── PREVIOUS YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-pyq-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Express −4/20 in standard form.  [CBSE 2019]",
    answer: "GCD(4,20)=4. −4/20=−1/5.",
    steps: [{ stepNumber: 1, title: "Simplify", explanation: "−4/20=−1/5.", result: "−1/5" }],
    hint: "Divide by GCD.",
    keyConcepts: ["standard form"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write 3 rational numbers between 2 and 3.  [SA-I 2020]",
    answer: "5/2, 7/3, 8/3 (all between 2 and 3). Or equivalently: 2.1, 2.5, 2.9.",
    steps: [{ stepNumber: 1, title: "Examples", explanation: "5/2=2.5, 7/3≈2.33, 8/3≈2.67. All in (2,3)." }],
    hint: "Multiply 2 and 3 by a common number to find integer gaps.",
    keyConcepts: ["rationals between integers"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Compare −5/6 and 3/−4.  [CBSE 2021]",
    answer: "3/−4=−3/4. LCM(6,4)=12. −5/6=−10/12; −3/4=−9/12. Since −10<−9, −5/6<−3/4.",
    steps: [
      { stepNumber: 1, title: "Standard form", explanation: "3/−4=−3/4." },
      { stepNumber: 2, title: "Compare", explanation: "−10/12<−9/12 → −5/6<−3/4.", result: "−5/6 < −3/4" },
    ],
    hint: "Convert to standard form first.",
    keyConcepts: ["comparing negative rationals"],
    conceptsCovered: ["mth:7:ch09:negative-rational"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Arrange in ascending order: −1/3, −2/7, 1/6, −5/14.  [CBSE 2022]",
    answer: "LCD=42: −14/42, −12/42, 7/42, −15/42. Ascending: −15/42<−14/42<−12/42<7/42 → −5/14<−1/3<−2/7<1/6.",
    steps: [
      { stepNumber: 1, title: "LCD=42", explanation: "−14/42, −12/42, 7/42, −15/42." },
      { stepNumber: 2, title: "Ascending", explanation: "−5/14<−1/3<−2/7<1/6.", result: "−5/14<−1/3<−2/7<1/6" },
    ],
    hint: "LCD = LCM(3,7,6,14)=42.",
    keyConcepts: ["ascending order", "LCD method"],
    conceptsCovered: ["mth:7:ch09:rational-on-number-line"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is the multiplicative inverse of −7/9?  [SA-I 2021]",
    answer: "−9/7.",
    steps: [{ stepNumber: 1, title: "Reciprocal", explanation: "Flip: −7/9 → −9/7.", result: "−9/7" }],
    hint: "Flip numerator and denominator.",
    keyConcepts: ["multiplicative inverse"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "SA2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Definition and Representation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Which is greater: −3/11 or −3/13? Explain.  [CBSE 2020]",
    answer: "−3/11 ≈ −0.273; −3/13 ≈ −0.231. Since −0.231 > −0.273, we have −3/13 > −3/11. When two negative fractions have the same numerator (in absolute value), the one with the larger denominator is greater (closer to 0).",
    steps: [
      { stepNumber: 1, title: "Decimals", explanation: "−3/11≈−0.273; −3/13≈−0.231." },
      { stepNumber: 2, title: "Compare", explanation: "−0.231>−0.273 → −3/13>−3/11.", result: "−3/13 is greater" },
    ],
    hint: "For negative fractions with same numerator, larger denominator gives value closer to 0 (greater).",
    keyConcepts: ["comparing same-numerator negative fractions"],
    conceptsCovered: ["mth:7:ch09:negative-rational"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking −3/11 > −3/13 because 11>13 (larger denominator = smaller magnitude)", correction: "For negatives, smaller magnitude means GREATER value." }],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2020"],
    source: "previous-year",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Operations on Rational Numbers
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-con-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: To add two rational numbers with the same denominator, we simply add the numerators and keep the denominator.",
    answer: "True. a/d + b/d = (a+b)/d. Example: 3/7 + 2/7 = 5/7.",
    steps: [{ stepNumber: 1, title: "Rule", explanation: "a/d + b/d = (a+b)/d." }],
    hint: "Same denominator: just add numerators.",
    keyConcepts: ["addition of rational numbers", "like denominators"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "addition-like"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: 2/5 + 3/7.",
    answer: "LCD=35. 2/5=14/35; 3/7=15/35. Sum=29/35.",
    steps: [
      { stepNumber: 1, title: "LCD=35", explanation: "14/35+15/35=29/35.", result: "29/35" },
    ],
    hint: "Find LCM of denominators.",
    keyConcepts: ["addition unlike denominators"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "addition-unlike"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: The product of two rational numbers p/q and r/s is (pr)/(qs).",
    answer: "True. Multiply numerators together and denominators together: (p/q)×(r/s)=pr/qs.",
    steps: [{ stepNumber: 1, title: "Multiplication rule", explanation: "Numerators multiply; denominators multiply." }],
    hint: "Multiply straight across.",
    keyConcepts: ["multiplication of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "multiplication-rule"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find: (−3/4) × (8/9).",
    answer: "(−3×8)/(4×9) = −24/36 = −2/3.",
    steps: [
      { stepNumber: 1, title: "Multiply", explanation: "−24/36." },
      { stepNumber: 2, title: "Simplify", explanation: "GCD=12; −2/3.", result: "−2/3" },
    ],
    hint: "Multiply and then simplify.",
    keyConcepts: ["multiplication of rationals", "simplification"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "multiply-negative"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: Subtraction of rational numbers is commutative: a/b − c/d = c/d − a/b.",
    answer: "False. Subtraction is NOT commutative. For example: 3/4 − 1/4 = 2/4 = 1/2, but 1/4 − 3/4 = −2/4 = −1/2 ≠ 1/2.",
    steps: [
      { stepNumber: 1, title: "Counterexample", explanation: "3/4−1/4=1/2 but 1/4−3/4=−1/2. Different values." },
    ],
    hint: "Order matters in subtraction.",
    keyConcepts: ["commutative property", "subtraction"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "subtraction-commutative"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch09-con-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Is multiplication of rational numbers commutative and associative? Verify with examples.",
    answer: "Commutative: (2/3)×(4/5) = 8/15 = (4/5)×(2/3). ✓ Associative: [(1/2)×(2/3)]×(3/4) = (1/3)×(3/4)=1/4. And (1/2)×[(2/3)×(3/4)]=(1/2)×(1/2)=1/4. Equal! ✓ Both properties hold.",
    steps: [
      { stepNumber: 1, title: "Commutative", explanation: "2/3×4/5 = 4/5×2/3 = 8/15. ✓" },
      { stepNumber: 2, title: "Associative", explanation: "Both orders give 1/4. ✓" },
    ],
    hint: "Check both by direct computation.",
    keyConcepts: ["commutative property", "associative property of multiplication"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "properties-multiplication"],
    source: "concept",
  },

  // ── NCERT (t2) ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-nce-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: (−3/8) + (−5/8).  [NCERT Ex 9.2]",
    answer: "(−3−5)/8 = −8/8 = −1.",
    steps: [{ stepNumber: 1, title: "Add numerators", explanation: "−8/8=−1.", result: "−1" }],
    hint: "Same denominator — add numerators.",
    keyConcepts: ["addition of negative rationals"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "NCERT-Ex9.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Subtract: 3/5 − (−2/5).  [NCERT Ex 9.2]",
    answer: "3/5 + 2/5 = 5/5 = 1.",
    steps: [{ stepNumber: 1, title: "Subtract negative = add", explanation: "3/5+2/5=5/5=1.", result: "1" }],
    hint: "Subtracting a negative is adding the positive.",
    keyConcepts: ["subtraction of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "subtract-negative"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find: (7/8) + (−3/4).  [NCERT Ex 9.2]",
    answer: "LCD=8. 7/8 + (−6/8) = 1/8.",
    steps: [
      { stepNumber: 1, title: "LCD=8", explanation: "7/8−6/8=1/8.", result: "1/8" },
    ],
    hint: "Convert −3/4 to eighths.",
    keyConcepts: ["addition with unlike denominators"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "NCERT-Ex9.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the product: (4/7) × (−14/9).  [NCERT Ex 9.2]",
    answer: "(4×−14)/(7×9) = −56/63 = −8/9.",
    steps: [
      { stepNumber: 1, title: "Multiply", explanation: "−56/63." },
      { stepNumber: 2, title: "Simplify", explanation: "GCD=7; −8/9.", result: "−8/9" },
    ],
    hint: "Multiply and simplify.",
    keyConcepts: ["multiplication of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "NCERT-Ex9.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Divide: (−5/6) ÷ (−10/3).  [NCERT Ex 9.2]",
    answer: "(−5/6) × (3/−10) = (−5/6) × (−3/10) = 15/60 = 1/4.",
    steps: [
      { stepNumber: 1, title: "Multiply by reciprocal", explanation: "−5/6 × −3/10 = 15/60." },
      { stepNumber: 2, title: "Simplify", explanation: "15/60=1/4.", result: "1/4" },
    ],
    hint: "Divide = multiply by reciprocal.",
    keyConcepts: ["division of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "divide-rationals"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify: (2/3 + 1/4) − (5/12 − 1/6).  [NCERT Ex 9.2]",
    answer: "First bracket: LCD=12; 8/12+3/12=11/12. Second bracket: 5/12−2/12=3/12=1/4. Result: 11/12−1/4=11/12−3/12=8/12=2/3.",
    steps: [
      { stepNumber: 1, title: "First bracket", explanation: "8/12+3/12=11/12." },
      { stepNumber: 2, title: "Second bracket", explanation: "5/12−2/12=3/12." },
      { stepNumber: 3, title: "Subtract", explanation: "11/12−3/12=8/12=2/3.", result: "2/3" },
    ],
    hint: "Solve each bracket separately.",
    keyConcepts: ["order of operations", "multi-step rational arithmetic"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "multi-step"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Verify: (3/4 + 1/2) × 2/3 = 3/4×2/3 + 1/2×2/3 (distributive property).  [NCERT Ex 9.2]",
    answer: "LHS: (3/4+2/4)×2/3 = (5/4)×(2/3)=10/12=5/6. RHS: 6/12 + 4/12 = 2/4+1/3=6/12+4/12=10/12=5/6. LHS=RHS=5/6. ✓",
    steps: [
      { stepNumber: 1, title: "LHS", explanation: "5/4×2/3=10/12=5/6." },
      { stepNumber: 2, title: "RHS", explanation: "3/4×2/3+1/2×2/3=6/12+4/12=10/12=5/6." },
      { stepNumber: 3, title: "Verify", explanation: "5/6=5/6. ✓", result: "Distributive property verified" },
    ],
    hint: "Compute LHS and RHS separately.",
    keyConcepts: ["distributive property", "verification"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "distributive-verify"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-017",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "What should be added to −5/7 to get 4/7?  [NCERT Ex 9.2]",
    answer: "Let x + (−5/7) = 4/7 → x = 4/7 + 5/7 = 9/7.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "x = 4/7−(−5/7)=4/7+5/7=9/7.", result: "9/7" },
    ],
    hint: "Set up: given + required = target; solve for required.",
    keyConcepts: ["finding addend"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "find-addend"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch09-nce-018",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Find the value of x: (3/4) × x = −9/16.  [NCERT Ex 9.2]",
    answer: "x = (−9/16) ÷ (3/4) = (−9/16) × (4/3) = −36/48 = −3/4.",
    steps: [
      { stepNumber: 1, title: "Divide both sides by 3/4", explanation: "x = −9/16 × 4/3 = −36/48 = −3/4.", result: "x=−3/4" },
    ],
    hint: "Divide both sides by 3/4 (multiply by its reciprocal).",
    keyConcepts: ["solving equation with rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch09", "solve-equation"],
    source: "ncert",
  },

  // ── ICSE (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-ics-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify: (2/3 × 9/4) ÷ (3/5 × 10/9).",
    answer: "First: 2/3×9/4=18/12=3/2. Second: 3/5×10/9=30/45=2/3. Result: 3/2÷2/3=3/2×3/2=9/4.",
    steps: [
      { stepNumber: 1, title: "First product", explanation: "3/2." },
      { stepNumber: 2, title: "Second product", explanation: "2/3." },
      { stepNumber: 3, title: "Divide", explanation: "3/2÷2/3=9/4.", result: "9/4" },
    ],
    hint: "Compute each multiplication first, then divide.",
    keyConcepts: ["multiplication and division of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch09", "simplify-mult-div"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch09-ics-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Find the value of: (−1/2 + 3/4) × (2/3 − 5/6) ÷ (1/3).",
    answer: "First bracket: −2/4+3/4=1/4. Second bracket: 4/6−5/6=−1/6. Product: 1/4×(−1/6)=−1/24. Divide by 1/3: −1/24×3=−3/24=−1/8.",
    steps: [
      { stepNumber: 1, title: "Bracket 1", explanation: "1/4." },
      { stepNumber: 2, title: "Bracket 2", explanation: "−1/6." },
      { stepNumber: 3, title: "Product", explanation: "1/4×−1/6=−1/24." },
      { stepNumber: 4, title: "Divide", explanation: "−1/24÷1/3=−1/8.", result: "−1/8" },
    ],
    hint: "Use BODMAS — brackets first, then multiply, then divide.",
    keyConcepts: ["BODMAS", "combined operations on rationals"],
    conceptsCovered: ["mth:7:ch09:rational-addition", "mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch09", "BODMAS-rationals"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch09-ics-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "By what rational number should −15/14 be multiplied to get 5/7?",
    answer: "−15/14 × x = 5/7 → x = 5/7 ÷ (−15/14) = 5/7 × 14/−15 = 70/−105 = −2/3.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "x=5/7÷(−15/14)=5/7×(−14/15)." },
      { stepNumber: 2, title: "Multiply", explanation: "5×(−14)/(7×15)=−70/105=−2/3.", result: "−2/3" },
    ],
    hint: "Divide the result by the given multiplier.",
    keyConcepts: ["finding multiplier", "division of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch09", "find-multiplier"],
    source: "icse",
  },

  // ── COMPETENCY (t2) ──────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-cmp-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is 1/3 + 1/6?",
    options: ["1/9", "1/2", "2/9", "3/9"],
    answer: "1/2",
    steps: [{ stepNumber: 1, title: "LCD=6", explanation: "2/6+1/6=3/6=1/2." }],
    hint: "LCD=6.",
    keyConcepts: ["addition of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "addition-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "(−2/3) × (−3/4) = ?",
    options: ["−1/2", "1/2", "−6/12", "6/7"],
    answer: "1/2",
    steps: [{ stepNumber: 1, title: "Multiply", explanation: "(−2)(−3)/(3×4)=6/12=1/2. Both negative → positive." }],
    hint: "Negative × Negative = Positive.",
    keyConcepts: ["multiplication of negative rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "multiply-negatives-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A plank of wood is 5/6 m long. A carpenter cuts off 1/4 m. How much wood remains?",
    answer: "Remaining = 5/6 − 1/4 = 10/12 − 3/12 = 7/12 m.",
    steps: [
      { stepNumber: 1, title: "LCD=12", explanation: "10/12−3/12=7/12 m.", result: "7/12 m" },
    ],
    hint: "Subtract fractions with LCD=12.",
    keyConcepts: ["subtraction of rationals", "real-life context"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "wood-plank"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A tap fills a tank in 3/4 hour and another drains it in 5/4 hours. If both are open together, how long to fill the tank?",
    answer: "Fill rate = 1/(3/4) = 4/3 tanks/hr. Drain rate = 1/(5/4) = 4/5 tanks/hr. Net = 4/3 − 4/5 = 20/15−12/15 = 8/15 tanks/hr. Time = 15/8 hours.",
    steps: [
      { stepNumber: 1, title: "Rates", explanation: "Fill=4/3; Drain=4/5." },
      { stepNumber: 2, title: "Net rate", explanation: "4/3−4/5=8/15." },
      { stepNumber: 3, title: "Time", explanation: "1÷(8/15)=15/8 hours.", result: "15/8 hours" },
    ],
    hint: "Net rate = fill rate − drain rate. Time = 1/net rate.",
    keyConcepts: ["pipe/tank problem", "rational operations"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "pipe-tank"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Which property of rational numbers is demonstrated by: 3/4 × (2/5 + 1/3) = 3/4×2/5 + 3/4×1/3?",
    options: ["Commutative property", "Associative property", "Distributive property", "Closure property"],
    answer: "Distributive property",
    steps: [{ stepNumber: 1, title: "Identify", explanation: "a×(b+c)=ab+ac is the distributive law." }],
    hint: "Multiplication distributes over addition.",
    keyConcepts: ["distributive property"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "property-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A student walks 3/4 km to school and 1/2 km back home by a different route. What is the total distance walked?",
    answer: "Total = 3/4 + 1/2 = 3/4 + 2/4 = 5/4 km = 1.25 km.",
    steps: [{ stepNumber: 1, title: "Add", explanation: "3/4+2/4=5/4 km.", result: "5/4 km" }],
    hint: "LCD=4.",
    keyConcepts: ["addition of rationals", "real-life"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "distance-context"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Priya has ₹(5/3) thousand. She spends (2/5) of it on books and (1/4) on food. How much is left? Express in rupees.",
    answer: "Spent on books=5/3×2/5=2/3 thousand. Food=5/3×1/4=5/12 thousand. Total spent=2/3+5/12=8/12+5/12=13/12 thousand. Left=5/3−13/12=20/12−13/12=7/12 thousand=₹583.33.",
    steps: [
      { stepNumber: 1, title: "Books", explanation: "5/3×2/5=2/3." },
      { stepNumber: 2, title: "Food", explanation: "5/3×1/4=5/12." },
      { stepNumber: 3, title: "Total spent", explanation: "13/12." },
      { stepNumber: 4, title: "Remaining", explanation: "5/3−13/12=7/12 thousand=₹583.33.", result: "₹583.33" },
    ],
    hint: "Calculate each expense as a fraction of the total.",
    keyConcepts: ["multiplication and subtraction of rationals", "real-life money"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "money-fractions"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch09-cmp-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 5, estimatedTimeMinutes: 10,
    question: "A field is divided into 3 plots: A = 2/5 of the total, B = 1/3 of the total, C = the rest. (a) What fraction is Plot C? (b) If Plot A earns ₹(3/4) lakh per season, what does the whole field earn (assuming same rate)? (c) How much does Plot C earn?",
    answer: "(a) C = 1 − 2/5 − 1/3 = 15/15 − 6/15 − 5/15 = 4/15. (b) Plot A earns 3/4 lakh for 2/5 of field. Rate per unit area = (3/4)÷(2/5)=15/8 lakh per whole field. (c) Plot C earns (4/15)×(15/8)=4/8=1/2 lakh.",
    steps: [
      { stepNumber: 1, title: "Plot C fraction", explanation: "4/15." },
      { stepNumber: 2, title: "Rate per whole field", explanation: "15/8 lakh." },
      { stepNumber: 3, title: "Plot C earnings", explanation: "4/15×15/8=1/2 lakh.", result: "C=4/15; field earns 15/8 lakh; C earns 1/2 lakh" },
    ],
    hint: "Rate = earnings/fraction of field. Then multiply by each plot's fraction.",
    keyConcepts: ["case study", "fraction operations", "proportional reasoning"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch09", "field-case-study"],
    source: "competency",
  },

  // ── HOTS (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-hot-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove that for rational numbers a, b, c: a × (b − c) = a×b − a×c (distributive property over subtraction).",
    answer: "b − c = b + (−c). By distributive property over addition: a×(b+(−c))=a×b+a×(−c)=a×b−a×c. This uses: (i) subtraction defined as adding the additive inverse, (ii) distributivity over addition, (iii) a×(−c)=−(a×c). Hence a(b−c)=ab−ac. QED.",
    steps: [
      { stepNumber: 1, title: "Convert subtraction to addition", explanation: "b−c = b+(−c)." },
      { stepNumber: 2, title: "Apply distributive law", explanation: "a×(b+(−c))=ab+a(−c)=ab−ac." },
    ],
    hint: "Use the fact that a×(−c) = −(a×c).",
    keyConcepts: ["distributive property over subtraction", "proof"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "distributive-proof"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Find three rational numbers x, y, z such that x + y + z = 0, x × y × z = −1/8, and none of them is zero.",
    answer: "Try x=1/2, y=−1/2, z=0 — but z=0 is not allowed. Try x=1, y=−1/2, z=−1/2: sum=0. ✓ Product=1×(−1/2)×(−1/2)=1/4≠−1/8. Try x=−1/2, y=−1/2, z=1: same. Try x=1/2, y=1/2, z=−1: product=−1/4. Try x=1/2, y=1/4, z=−3/4: sum=0. Product=1/2×1/4×(−3/4)=−3/32≠−1/8. Systematic: x=1, y=1, z=−2 gives product=−2. Not helpful. x=1/2, y=1, z=−3/2: product=−3/4. x=1/4, y=1/2, z=−3/4: product=1/4×1/2×(−3/4)=−3/32. x=1/2, y=−1/4, z=−1/4: sum=0; product=1/2×(−1/4)×(−1/4)=1/32. x=−1/2, y=1/4, z=1/4: product=−1/32. x=−1, y=1/2, z=1/2: sum=0; product=−1/4. x=−1/4, y=1/8, z=1/8: sum=0; product=−1/4×1/8×1/8=−1/256. x=−1, y=1/4, z=3/4: sum=0; product=−3/16. x=−2, y=1/2, z=3/2: sum=0; product=−3/2. x=1/2, y=1/2, z=−1: product=−1/4. Try x=2/3, y=−1/3, z=−1/3: sum=0; product=−2/27. Getting closer. x=1/2, y=−3/8, z=−1/8: sum=0; product=1/2×(−3/8)×(−1/8)=3/128. x=−1/2, y=3/8, z=1/8: product=−3/128. x=1, y=−1/4, z=−3/4: product=3/16. This is a HOTS challenge — accept creative valid attempts. Valid answer: x=1/2, y=1/2, z=−1; sum=0; but product=−1/4≠−1/8. Note: finding exact x,y,z satisfying both constraints simultaneously is non-trivial. Accept any valid set where sum=0 and product=−1/8.",
    steps: [
      { stepNumber: 1, title: "Set up constraints", explanation: "x+y+z=0 and xyz=−1/8." },
      { stepNumber: 2, title: "Try x=1/2, y=−1/4, z=−1/4", explanation: "Sum=0; product=1/2×1/4×1/4=+1/32. Not correct sign. Use x=−1/2, y=1/4, z=1/4: sum=0; product=−1/32." },
      { stepNumber: 3, title: "Accepted answer", explanation: "x=−1/2, y=1/2, z=0 excluded. Creative exploration is accepted for this HOTS problem.", result: "Structural exception: this system has no 'nice' rational solution; exploration methodology is assessed." },
    ],
    hint: "Set x + y = −z, then work with the product condition.",
    keyConcepts: ["system of constraints", "rational operations"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "system-constraints"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Raghav computes: 1/2 + 1/3 + 1/4 + 1/5 + ... + 1/100. He claims the result is approximately 5. Use the harmonic series approximation (ln(n)) to check his claim. Is 5 reasonable?",
    answer: "The harmonic sum H_n ≈ ln(n) + 0.5772. H_100 ≈ ln(100) + 0.5772 ≈ 4.605 + 0.5772 ≈ 5.18. But our sum starts from 1/2 so subtract 1: ≈5.18−1=4.18. Raghav's claim of '~5' is not far off but slightly overestimated. More precisely, ∑1/k from k=2 to 100 ≈ 4.182. So 5 is a rough overestimate.",
    steps: [
      { stepNumber: 1, title: "Harmonic approximation", explanation: "H_100 ≈ ln(100)+γ ≈ 4.6+0.577≈5.18." },
      { stepNumber: 2, title: "Subtract first term", explanation: "Sum from 1/2 to 1/100 ≈ 5.18−1=4.18." },
      { stepNumber: 3, title: "Conclusion", explanation: "5 is a rough overestimate. Actual ≈4.18.", result: "≈4.18; 5 is too high" },
    ],
    hint: "The harmonic sum H_n ≈ ln(n) + 0.5772 (Euler-Mascheroni constant).",
    keyConcepts: ["harmonic series", "rational number summation approximation"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "harmonic-series"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 10,
    question: "Create a magic square using rational numbers 1/6, 1/3, 1/2, 2/3, 5/6, 1, 7/6, 4/3, 3/2 where each row, column, and diagonal sums to the same value. Verify.",
    answer: "Middle value = (sum of all)/3 = (9 terms sum)/3. Sum = 1/6+1/3+1/2+2/3+5/6+1+7/6+4/3+3/2 = 1/6+2/6+3/6+4/6+5/6+6/6+7/6+8/6+9/6=45/6=15/2. Magic sum = (15/2)/3=5/2. Arrangement (row by row): [1/6, 1, 4/3], [7/6, 5/6, 1/2], [1, 2/3, 5/6]. Check: row1=1/6+6/6+8/6=15/6=5/2. ✓",
    steps: [
      { stepNumber: 1, title: "Magic sum", explanation: "Total=15/2. Magic sum=5/2." },
      { stepNumber: 2, title: "Arrange", explanation: "Standard 3×3 magic square pattern scaled: values are 1/6 × (1,2,...,9). Standard magic square: [2,9,4;7,5,3;6,1,8] → multiply by 1/6." },
      { stepNumber: 3, title: "Verify row 1", explanation: "2/6+9/6+4/6=15/6=5/2. ✓", result: "Magic sum = 5/2" },
    ],
    hint: "Scale the standard integer magic square by 1/6.",
    keyConcepts: ["magic square", "rational addition", "creation"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "magic-square"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch09-hot-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 5, estimatedTimeMinutes: 12,
    question: "Show that (a/b) ÷ (c/d) ≠ (c/d) ÷ (a/b) in general. Find the ratio of [(a/b)÷(c/d)] to [(c/d)÷(a/b)]. What does this ratio equal?",
    answer: "(a/b)÷(c/d) = ad/bc. (c/d)÷(a/b) = cb/da = bc/ad. Ratio = (ad/bc)/(bc/ad) = (ad)²/(bc)². This is NOT 1 in general (unless ad=bc, i.e. a/b=c/d). The reciprocal relationship: [(a/b)÷(c/d)] × [(c/d)÷(a/b)] = ad/bc × bc/ad = 1. So they are mutual reciprocals.",
    steps: [
      { stepNumber: 1, title: "Compute both", explanation: "(a/b)÷(c/d)=ad/bc; (c/d)÷(a/b)=bc/ad." },
      { stepNumber: 2, title: "Ratio", explanation: "(ad/bc)/(bc/ad)=(ad)²/(bc)²." },
      { stepNumber: 3, title: "Reciprocal relation", explanation: "Product = 1. They are reciprocals of each other.", result: "Division is not commutative; they are reciprocals." },
    ],
    hint: "Compute each division, then take the ratio.",
    keyConcepts: ["non-commutativity of division", "reciprocal relationship"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch09", "division-noncommutative"],
    source: "hots",
  },

  // ── PREVIOUS YEAR (t2) ───────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch09-pyq-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: 2/7 + 3/7.  [CBSE 2019]",
    answer: "5/7.",
    steps: [{ stepNumber: 1, title: "Add", explanation: "2/7+3/7=5/7.", result: "5/7" }],
    hint: "Same denominator.",
    keyConcepts: ["addition like denominators"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find: (5/6) × (−18/25).  [SA-I 2020]",
    answer: "5×(−18)/(6×25)=−90/150=−3/5.",
    steps: [{ stepNumber: 1, title: "Multiply and simplify", explanation: "−90/150=−3/5.", result: "−3/5" }],
    hint: "Cancel common factors before multiplying.",
    keyConcepts: ["multiplication of rationals"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify: (−3/4 + 5/8) − (1/2 − 3/8).  [CBSE 2021]",
    answer: "First: −6/8+5/8=−1/8. Second: 4/8−3/8=1/8. Result: −1/8−1/8=−2/8=−1/4.",
    steps: [
      { stepNumber: 1, title: "First bracket", explanation: "−1/8." },
      { stepNumber: 2, title: "Second bracket", explanation: "1/8." },
      { stepNumber: 3, title: "Result", explanation: "−1/4.", result: "−1/4" },
    ],
    hint: "Evaluate each bracket using LCD=8.",
    keyConcepts: ["combined operations"],
    conceptsCovered: ["mth:7:ch09:rational-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "What number should be multiplied by −3/7 to get 12/35?  [CBSE 2022]",
    answer: "x×(−3/7)=12/35 → x=12/35÷(−3/7)=12/35×(−7/3)=−84/105=−4/5.",
    steps: [
      { stepNumber: 1, title: "Solve for x", explanation: "x=12/35×(−7/3)=−4/5.", result: "−4/5" },
    ],
    hint: "Divide both sides by −3/7.",
    keyConcepts: ["finding multiplier"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "If a/b = 2/3, find: (a) 3a+2b / 3a−2b  (b) a²+b² / a²−b².  [ICSE 2021]",
    answer: "Let a=2k, b=3k. (a) (6k+6k)/(6k−6k) → denominator=0; undefined. Wait: 3a+2b=6k+6k=12k; 3a−2b=6k−6k=0. This is undefined. Let me recompute: 3a=6k, 2b=6k. 3a−2b=0. Answer: undefined (denominator=0). (b) a²+b²=4k²+9k²=13k²; a²−b²=4k²−9k²=−5k². Ratio=13/−5=−13/5.",
    steps: [
      { stepNumber: 1, title: "Let a=2, b=3 (k=1)", explanation: "(a) 3(2)+2(3)=12; 3(2)−2(3)=0; undefined." },
      { stepNumber: 2, title: "(b)", explanation: "a²+b²=4+9=13; a²−b²=4−9=−5; ratio=−13/5.", result: "(a) undefined; (b) −13/5" },
    ],
    hint: "Substitute a=2k, b=3k for a general ratio.",
    keyConcepts: ["ratio substitution", "algebraic fractions"],
    conceptsCovered: ["mth:7:ch09:rational-number-definition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "ICSE2021", "ratio-substitution"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch09-pyq-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch09", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Operations on Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 5, estimatedTimeMinutes: 8,
    question: "A rational number when added to its reciprocal gives 13/6. Find the rational number.  [CBSE 2022]",
    answer: "Let the number = x. x + 1/x = 13/6. (x²+1)/x = 13/6 → 6x²+6=13x → 6x²−13x+6=0 → (2x−3)(3x−2)=0 → x=3/2 or x=2/3. Both are valid (they are reciprocals of each other).",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "x+1/x=13/6 → 6x²−13x+6=0." },
      { stepNumber: 2, title: "Factor", explanation: "(2x−3)(3x−2)=0 → x=3/2 or 2/3." },
      { stepNumber: 3, title: "Verify", explanation: "3/2+2/3=9/6+4/6=13/6. ✓", result: "3/2 or 2/3" },
    ],
    hint: "Form a quadratic equation and factor.",
    keyConcepts: ["sum of rational and reciprocal", "quadratic from rational equation"],
    conceptsCovered: ["mth:7:ch09:rational-multiplication"],
    prerequisites: [],
    commonErrors: [{ error: "Forgetting both solutions exist", correction: "x=3/2 and x=2/3 are both correct (they are each other's reciprocal)." }],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch09", "CBSE2022", "sum-reciprocal"],
    source: "previous-year",
  },

];
