// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 12: Algebraic Expressions
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Terms, Factors, and Like Terms — 37 q
 *   t2 Addition and Subtraction       — 38 q
 *
 * Concept nodes:
 *   mth:7:ch12:term-coefficient-factor
 *   mth:7:ch12:like-unlike-terms
 *   mth:7:ch12:expression-addition
 *   mth:7:ch12:expression-subtraction
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH12_ALGEBRAIC_EXPRESSIONS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Terms, Factors, and Like Terms
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-con-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: In the term 5x²y, the coefficient of x²y is 5.",
    answer: "True. The coefficient is the numerical part of a term. In 5x²y, the numerical factor is 5, so the coefficient of x²y is 5.",
    steps: [{ stepNumber: 1, title: "Identify coefficient", explanation: "5x²y = 5 × x² × y. Coefficient = 5." }],
    hint: "Coefficient = the number in front of the variable part.",
    keyConcepts: ["coefficient", "term"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "coefficient"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Identify all terms and their coefficients in the expression: 3x² − 5xy + 7y − 9.",
    answer: "Terms: 3x², −5xy, 7y, −9. Coefficients: 3 (for x²), −5 (for xy), 7 (for y), −9 (constant term).",
    steps: [
      { stepNumber: 1, title: "Identify terms", explanation: "Separated by + and −: 3x², −5xy, 7y, −9." },
      { stepNumber: 2, title: "Coefficients", explanation: "3, −5, 7, −9 respectively." },
    ],
    hint: "Terms are separated by + and − signs (not inside brackets).",
    keyConcepts: ["terms", "coefficients", "algebraic expression"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "identify-terms"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: 3x²y and −7x²y are like terms.",
    answer: "True. Like terms have identical variable parts. Both 3x²y and −7x²y have the same variable part x²y. They can be added or subtracted.",
    steps: [{ stepNumber: 1, title: "Check variable parts", explanation: "Both have x²y → like terms." }],
    hint: "Like terms: same variables with same exponents.",
    keyConcepts: ["like terms"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "like-terms"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Group the like terms: 4x, 3y², −2x, 5xy, 7y², −3xy, 6.",
    answer: "Like groups: {4x, −2x}, {3y², 7y²}, {5xy, −3xy}, {6} (constant).",
    steps: [
      { stepNumber: 1, title: "Group by variable", explanation: "x terms: 4x, −2x. y² terms: 3y², 7y². xy terms: 5xy, −3xy. Constant: 6." },
    ],
    hint: "Same variable with same powers = like terms.",
    keyConcepts: ["grouping like terms"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "group-like-terms"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: 3x²y and 3xy² are like terms.",
    answer: "False. Although they have the same variables, the exponents differ: 3x²y has x² and y¹, while 3xy² has x¹ and y². Different exponent distribution → unlike terms.",
    steps: [
      { stepNumber: 1, title: "Compare exponents", explanation: "x²y vs xy². Exponents differ → NOT like terms." },
    ],
    hint: "Like terms require IDENTICAL variable parts — same variable AND same exponent.",
    keyConcepts: ["like vs unlike terms", "exponents in terms"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "unlike-terms-exponents"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What are the factors of the term −4ab²?",
    answer: "Factors: −4, a, b, b (or −4, a, b²). All multiply together to give −4ab².",
    steps: [
      { stepNumber: 1, title: "List factors", explanation: "−4ab² = (−4) × a × b × b = (−4) × a × b²." },
    ],
    hint: "Factors are numbers and variables whose product makes the term.",
    keyConcepts: ["factors of a term"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "factors-of-term"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-nce-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "How many terms are in each expression? (a) xy + 4  (b) 2x² − 3x + 5  (c) 7  [NCERT Ex 12.1]",
    answer: "(a) 2 terms: xy and 4.  (b) 3 terms: 2x², −3x, 5.  (c) 1 term: the constant 7.",
    steps: [
      { stepNumber: 1, title: "Count terms", explanation: "Terms are separated by + and − signs." },
    ],
    hint: "Count by separating at + and − (outside brackets).",
    keyConcepts: ["number of terms", "polynomial classification"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State whether the following are monomials, binomials, or trinomials: (a) 4  (b) 5x + 3  (c) x + y + z  [NCERT Ex 12.1]",
    answer: "(a) Monomial (1 term). (b) Binomial (2 terms). (c) Trinomial (3 terms).",
    steps: [{ stepNumber: 1, title: "Classify by number of terms", explanation: "Mono=1, Bi=2, Tri=3." }],
    hint: "Mono=1, Bi=2, Tri=3 terms.",
    keyConcepts: ["monomial", "binomial", "trinomial"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the coefficient of x in: (a) 13x  (b) −7x + 5  (c) x/2  [NCERT Ex 12.1]",
    answer: "(a) 13  (b) −7  (c) 1/2.",
    steps: [{ stepNumber: 1, title: "Identify coefficient of x", explanation: "Numerical factor of the x-term." }],
    hint: "x alone has coefficient 1; x/2 = (1/2)x.",
    keyConcepts: ["coefficient of a variable"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [{ error: "Writing coefficient of x/2 as 2", correction: "x/2 = (1/2)×x; coefficient = 1/2." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Identify the like terms: 12x, 14y², 13x, −17y², 25x, 3x²y  [NCERT Ex 12.1]",
    answer: "Like terms: {12x, 13x, 25x} and {14y², −17y²}. The term 3x²y is unlike all others.",
    steps: [
      { stepNumber: 1, title: "Group same variable parts", explanation: "x-group: 12x,13x,25x. y²-group: 14y², −17y²." },
    ],
    hint: "Match variable parts exactly.",
    keyConcepts: ["identifying like terms"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the values of: (a) 2x − 3y when x=1, y=2  (b) x² + y² when x=3, y=4  [NCERT Ex 12.1]",
    answer: "(a) 2(1) − 3(2) = 2 − 6 = −4.  (b) 3² + 4² = 9 + 16 = 25.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "2(1)−3(2)=−4." },
      { stepNumber: 2, title: "(b)", explanation: "9+16=25.", result: "−4 and 25" },
    ],
    hint: "Substitute the given values and simplify.",
    keyConcepts: ["evaluating expressions", "substitution"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "evaluate-expression"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write one example each of: (a) a monomial of degree 5  (b) a binomial of degree 2  (c) a trinomial of degree 3  [NCERT Ex 12.1]",
    answer: "(a) 3x⁵ (degree 5). (b) x² + 4 (degree 2). (c) x³ + x² + 1 (degree 3).",
    steps: [
      { stepNumber: 1, title: "Degree = highest power of variable", explanation: "Examples above satisfy conditions." },
    ],
    hint: "Degree = highest exponent of the variable in the expression.",
    keyConcepts: ["degree of expression", "monomial", "binomial", "trinomial"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "degree-of-expression"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Write an expression using variables x, y with at least 4 unlike terms. Specify the coefficient and degree of each term.  [NCERT Ex 12.1]",
    answer: "Expression: 3x²y + 2xy² − 5x + 7. Terms: 3x²y (coeff=3, degree=3), 2xy² (coeff=2, degree=3), −5x (coeff=−5, degree=1), 7 (coeff=7, degree=0).",
    steps: [
      { stepNumber: 1, title: "Create expression", explanation: "4 unlike terms with different variable parts." },
      { stepNumber: 2, title: "State degrees", explanation: "x²y has degree 3 (2+1); xy² has degree 3 (1+2); x has degree 1; 7 has degree 0." },
    ],
    hint: "Unlike terms have different variable parts.",
    keyConcepts: ["creating expressions", "unlike terms", "degree"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "create-expression"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is the difference between a constant term and a variable term?  [NCERT Ex 12.1]",
    answer: "A constant term (like 5, −7, 0) has a fixed numerical value and contains no variables. A variable term (like 3x, −2y², 5xy) contains one or more variables and its value changes as variables change.",
    steps: [
      { stepNumber: 1, title: "Constant term", explanation: "No variable; fixed value. E.g., 5." },
      { stepNumber: 2, title: "Variable term", explanation: "Has variables; value depends on variable values. E.g., 3x." },
    ],
    hint: "Constant has no variable; variable term does.",
    keyConcepts: ["constant term", "variable term"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "constant-vs-variable"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "From the expression 5xyz − 3yz + 2xy − 3x + y + 12, identify: (a) terms with coefficient 2 or higher  (b) constant term  (c) number of terms with y only  [NCERT Ex 12.1]",
    answer: "(a) 5xyz (coeff=5), 2xy (coeff=2), 12 (coeff=12). (b) 12. (c) 1 term with y only: y (coeff=1).",
    steps: [
      { stepNumber: 1, title: "(a) Coefficients ≥2", explanation: "5xyz(5), 2xy(2), 12(12)." },
      { stepNumber: 2, title: "(b) Constant", explanation: "12." },
      { stepNumber: 3, title: "(c) Pure y term", explanation: "y → 1 term." },
    ],
    hint: "Check each term's coefficient and variable composition.",
    keyConcepts: ["identifying terms by coefficient", "constant", "pure variable terms"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "multi-part-identification"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-ics-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Evaluate 3a² − 5ab + 2b² when a = 2 and b = −1.",
    answer: "3(4) − 5(2)(−1) + 2(1) = 12 + 10 + 2 = 24.",
    steps: [
      { stepNumber: 1, title: "Substitute", explanation: "3(2²)−5(2)(−1)+2(−1)²=12+10+2=24.", result: "24" },
    ],
    hint: "Substitute a=2, b=−1 carefully into each term.",
    keyConcepts: ["evaluating algebraic expressions"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [{ error: "Forgetting b=−1 so b²=+1", correction: "(−1)²=1, not −1." }],
    tags: ["icse", "class7", "ch12", "evaluate-substitution"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch12-ics-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "If x + y = 7 and xy = 12, find the value of x² + y².",
    answer: "x² + y² = (x+y)² − 2xy = 49 − 24 = 25.",
    steps: [
      { stepNumber: 1, title: "Identity", explanation: "(x+y)²=x²+2xy+y² → x²+y²=(x+y)²−2xy=49−24=25.", result: "25" },
    ],
    hint: "Use (x+y)² = x²+2xy+y².",
    keyConcepts: ["algebraic identity", "x²+y² from x+y and xy"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch12", "identity-application"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch12-ics-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Collect like terms and simplify: 3ab + 5bc − 2ab − 7bc + 4ab − bc.",
    answer: "ab terms: 3−2+4=5ab. bc terms: 5−7−1=−3bc. Result: 5ab − 3bc.",
    steps: [
      { stepNumber: 1, title: "Group ab terms", explanation: "3+4−2=5ab." },
      { stepNumber: 2, title: "Group bc terms", explanation: "5−7−1=−3bc.", result: "5ab − 3bc" },
    ],
    hint: "Collect like terms separately.",
    keyConcepts: ["collecting like terms", "simplification"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch12", "collect-like-terms"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch12-ics-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Write the perimeter of a triangle with sides (2x+3), (5x−1), and (x+4) as a simplified algebraic expression. Evaluate it for x = 3.",
    answer: "Perimeter = (2x+3)+(5x−1)+(x+4)=8x+6. At x=3: 8(3)+6=30.",
    steps: [
      { stepNumber: 1, title: "Add sides", explanation: "8x+6." },
      { stepNumber: 2, title: "Evaluate", explanation: "8(3)+6=30.", result: "8x+6; x=3 → 30" },
    ],
    hint: "Perimeter = sum of all sides; collect like terms.",
    keyConcepts: ["perimeter expression", "evaluating at given value"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch12", "perimeter-expression"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-cmp-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which pair are like terms?",
    options: ["3xy and 3x²", "5x and −2x", "4xy and 4yz", "7x² and 7y²"],
    answer: "5x and −2x",
    steps: [{ stepNumber: 1, title: "Check variable parts", explanation: "Both have variable part x only → like terms." }],
    hint: "Like terms: identical variable part.",
    keyConcepts: ["like terms"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "MCQ-like-terms"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is the coefficient of y² in −5x²y + 3y² − 7?",
    options: ["−5", "3", "−7", "1"],
    answer: "3",
    steps: [{ stepNumber: 1, title: "Identify y² term", explanation: "Term with y² is 3y². Coefficient = 3." }],
    hint: "Look for the term that contains y² and read its coefficient.",
    keyConcepts: ["coefficient identification"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "coefficient-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The sides of a square are (3x + 2) cm each. Write the perimeter as an expression and find its value when x = 5.",
    answer: "Perimeter = 4(3x+2) = 12x+8. At x=5: 12(5)+8=68 cm.",
    steps: [
      { stepNumber: 1, title: "Perimeter", explanation: "4×(3x+2)=12x+8." },
      { stepNumber: 2, title: "Evaluate", explanation: "60+8=68 cm.", result: "12x+8; 68 cm" },
    ],
    hint: "Square perimeter = 4 × side.",
    keyConcepts: ["algebraic expression for perimeter", "evaluation"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "square-perimeter"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 5, estimatedTimeMinutes: 10,
    question: "A fruit stall sells apples at ₹a per kg and mangoes at ₹m per kg. Riya buys 3 kg apples and 2 kg mangoes. Raj buys 5 kg apples and 1 kg mangoes. (a) Write expressions for amounts each paid. (b) Who paid more if a=40, m=60? (c) What is the total bill?",
    answer: "(a) Riya: 3a+2m; Raj: 5a+m. (b) Riya: 120+120=240; Raj: 200+60=260. Raj paid more. (c) Total: 8a+3m=320+180=500.",
    steps: [
      { stepNumber: 1, title: "Expressions", explanation: "Riya=3a+2m; Raj=5a+m." },
      { stepNumber: 2, title: "a=40, m=60", explanation: "Riya=240; Raj=260. Raj paid more." },
      { stepNumber: 3, title: "Total", explanation: "8a+3m=500.", result: "Raj; total=₹500" },
    ],
    hint: "Amount = price per kg × kg bought.",
    keyConcepts: ["forming expressions", "evaluation", "comparison"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "case-study-market"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Which is NOT a like term of 4m²n?",
    options: ["−3m²n", "7m²n", "m²n/2", "4mn²"],
    answer: "4mn²",
    steps: [{ stepNumber: 1, title: "Check", explanation: "4mn² has mn² (n has degree 2, m degree 1) vs m²n (m degree 2, n degree 1). Different → NOT like." }],
    hint: "Compare the exponent of each variable.",
    keyConcepts: ["unlike terms with same variables"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "not-like-term"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "If p = 2 and q = −3, evaluate: 2p²q − pq².",
    answer: "2(4)(−3) − (2)(9) = −24 − 18 = −42.",
    steps: [
      { stepNumber: 1, title: "Substitute", explanation: "2(4)(−3)=−24; (2)(9)=18." },
      { stepNumber: 2, title: "Result", explanation: "−24−18=−42.", result: "−42" },
    ],
    hint: "Compute p², q² first, then substitute.",
    keyConcepts: ["evaluation of expression"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [{ error: "q²=−9 instead of 9", correction: "(−3)²=9 (square of a negative is positive)." }],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "evaluate-negative"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "An algebraic expression with exactly one term is called a:",
    options: ["Binomial", "Trinomial", "Monomial", "Polynomial"],
    answer: "Monomial",
    steps: [{ stepNumber: 1, title: "Recall", explanation: "Mono = one. Monomial = one term." }],
    hint: "Mono = one.",
    keyConcepts: ["monomial definition"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "monomial-MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "The cost of making a box is ₹(2l + 3w + 5h) where l, w, h are length, width, height in cm. Find the cost for a box of l=10, w=8, h=6 cm. If each dimension increases by 2 cm, how much does the cost increase?",
    answer: "Original: 2(10)+3(8)+5(6)=20+24+30=₹74. New: 2(12)+3(10)+5(8)=24+30+40=₹94. Increase=₹20.",
    steps: [
      { stepNumber: 1, title: "Original cost", explanation: "74." },
      { stepNumber: 2, title: "New cost", explanation: "94." },
      { stepNumber: 3, title: "Increase", explanation: "20.", result: "₹74 → ₹94; increase ₹20" },
    ],
    hint: "Substitute each set of values and compare.",
    keyConcepts: ["evaluation", "change in expression value"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "box-cost"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-hot-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Write an algebraic expression with 5 terms that equals 0 when x = 1, y = −1. Show your verification.",
    answer: "Expression: x + y + x² − x²y − x = x + y + x² − x²y − x = y + x² − x²y. At x=1,y=−1: −1+1−(1)(−1)=−1+1+1=1≠0. Adjust: use x³ − x² + 2x − y − 2. At x=1,y=−1: 1−1+2−(−1)−2=1. Still not 0. Try: 3x − 5y − 2xy + x² − (3+5+2+1)... creating a valid example: (x−1) + (y+1) + (x+y) + (2x−2) + (−2x) = x−1+y+1+x+y+2x−2−2x=2x+2y−2. At (1,−1): 2−2−2=−2≠0. Let's use: x−1, y+1, xy+1, −xy, −1 → sum=(x−1)+(y+1)+(xy+1)+(−xy)+(−1)=x+y. At x=1,y=−1: 0. ✓ Expression: (x−1)+(y+1)+(xy+1)+(−xy)+(−1)=x+y.",
    steps: [
      { stepNumber: 1, title: "Build expression", explanation: "5 terms that sum to x+y: (x−1),(y+1),(xy+1),(−xy),(−1)." },
      { stepNumber: 2, title: "Verify at x=1,y=−1", explanation: "1+0+0+0+(−1)=0. ✓" },
    ],
    hint: "Work backwards: what 5 terms sum to 0 at x=1, y=−1?",
    keyConcepts: ["creating expressions with constraints", "verification"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "create-zero-expression"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Kavya says: 'Adding two unlike terms gives a binomial.' Is she always correct? Can you add two unlike terms and get a monomial? Explain.",
    answer: "Kavya is generally correct — adding two unlike terms gives a binomial (e.g., 3x + 4y = 3x + 4y, a binomial). However, you CANNOT add two unlike terms to get a monomial (unless one is the additive inverse of the other, but then they are like terms). Two genuinely unlike terms always produce a binomial. Exception: if both are constants (like 5 + 3 = 8), the result is a monomial. Constants are technically like terms (both of degree 0).",
    steps: [
      { stepNumber: 1, title: "General case", explanation: "Two unlike terms → binomial (e.g., 2x+3y)." },
      { stepNumber: 2, title: "Exception", explanation: "Two constants: 5+3=8. Constants are like terms (both degree 0), so adding gives a monomial." },
    ],
    hint: "Think about what happens when both 'unlike' terms are actually constants.",
    keyConcepts: ["unlike terms", "monomial from addition"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "kavya-claim"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 7,
    question: "A teacher writes the following on the board: '5ab + 3a²b and 3ab + 5a²b are like terms because they contain both a and b.' Is the teacher correct? Explain.",
    answer: "The teacher is INCORRECT. 5ab and 3ab are like terms (both have ab). 3a²b and 5a²b are like terms (both have a²b). But 5ab and 3a²b are NOT like terms (different variable parts: ab vs a²b). The teacher confused 'containing the same variables' with 'having identical variable parts with the same exponents'.",
    steps: [
      { stepNumber: 1, title: "Check 5ab vs 3a²b", explanation: "ab ≠ a²b (a has different exponent). NOT like terms." },
      { stepNumber: 2, title: "Conclusion", explanation: "Teacher is wrong. Having the same variables is not enough — exponents must match too." },
    ],
    hint: "Like terms require exactly the same variable part, including exponents.",
    keyConcepts: ["like terms definition", "exponent matching"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking same variables = like terms", correction: "Same variables AND same exponents are both required." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "teacher-error"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "For what value of k do 3x²y + kxy² and 7x²y − 2xy² when added give 10x²y − 3xy²?",
    answer: "(3+7)x²y + (k−2)xy² = 10x²y + (k−2)xy². Comparing: k−2=−3 → k=−1.",
    steps: [
      { stepNumber: 1, title: "Add expressions", explanation: "10x²y+(k−2)xy²." },
      { stepNumber: 2, title: "Compare with target", explanation: "k−2=−3 → k=−1.", result: "k=−1" },
    ],
    hint: "Add corresponding like terms and compare coefficients.",
    keyConcepts: ["finding coefficient by comparison"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "find-coefficient-k"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Create an expression E in two variables x and y such that E(1,1) = 10, E(2,1) = 25, and E has exactly 3 unlike terms.",
    answer: "Try E = ax² + bxy + c. E(1,1)=a+b+c=10. E(2,1)=4a+2b+c=25. Subtracting: 3a+b=15. Choose a=4,b=3: 3(4)+3=15. ✓ Then c=10−4−3=3. E=4x²+3xy+3. Verify: E(1,1)=4+3+3=10✓; E(2,1)=16+6+3=25✓.",
    steps: [
      { stepNumber: 1, title: "Set up system", explanation: "a+b+c=10; 4a+2b+c=25." },
      { stepNumber: 2, title: "Choose values", explanation: "a=4,b=3,c=3." },
      { stepNumber: 3, title: "Verify", explanation: "E=4x²+3xy+3. ✓ 3 unlike terms." },
    ],
    hint: "Assume E = ax² + bxy + c and solve the system.",
    keyConcepts: ["constructing expression from conditions", "system of equations"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "construct-expression"],
    source: "hots",
  },

  // ── PREVIOUS YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-pyq-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the number of terms in 2x² + 3xy − 5y + 7.  [CBSE 2019]",
    answer: "4 terms: 2x², 3xy, −5y, 7.",
    steps: [{ stepNumber: 1, title: "Count", explanation: "4 terms.", result: "4" }],
    hint: "Terms are separated by + and −.",
    keyConcepts: ["number of terms"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Identify like terms from: 4a, 3b, −5a, 7b², 2a, −b.  [SA-I 2020]",
    answer: "Like term groups: {4a, −5a, 2a} and {3b, −b}. Note: 7b² is unlike all others.",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "a-terms: 4a,−5a,2a. b-terms: 3b,−b. 7b² is alone." },
    ],
    hint: "Match variable parts exactly.",
    keyConcepts: ["identifying like terms"],
    conceptsCovered: ["mth:7:ch12:like-unlike-terms"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Evaluate 5x² − 3x + 1 at x = −2.  [CBSE 2021]",
    answer: "5(4) − 3(−2) + 1 = 20 + 6 + 1 = 27.",
    steps: [
      { stepNumber: 1, title: "Substitute x=−2", explanation: "5(4)+6+1=27.", result: "27" },
    ],
    hint: "x² means (−2)²=4.",
    keyConcepts: ["evaluation at negative value"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the coefficient of xy² in 5x²y − 3xy² + 4.  [SA-I 2021]",
    answer: "The term with xy² is −3xy². Coefficient = −3.",
    steps: [{ stepNumber: 1, title: "Identify term", explanation: "−3xy² → coefficient = −3.", result: "−3" }],
    hint: "The coefficient includes the sign.",
    keyConcepts: ["coefficient extraction"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [{ error: "Writing 3 instead of −3", correction: "Coefficient includes the negative sign." }],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "SA2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If x = 1, y = 2, z = 3, find x²y + yz² − xyz.  [CBSE 2022]",
    answer: "1(2) + 2(9) − 1(2)(3) = 2 + 18 − 6 = 14.",
    steps: [
      { stepNumber: 1, title: "Substitute", explanation: "x²y=(1)(2)=2; yz²=(2)(9)=18; xyz=(1)(2)(3)=6." },
      { stepNumber: 2, title: "Result", explanation: "2+18−6=14.", result: "14" },
    ],
    hint: "Compute each term separately, then combine.",
    keyConcepts: ["multi-variable evaluation"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t1", topicName: "Terms, Factors, and Like Terms",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State whether each is a monomial, binomial, or trinomial: (a) x²y  (b) 3x + 2y  (c) p + q + r  [CBSE 2020]",
    answer: "(a) Monomial. (b) Binomial. (c) Trinomial.",
    steps: [{ stepNumber: 1, title: "Count terms", explanation: "1 term, 2 terms, 3 terms respectively." }],
    hint: "Count the terms (separated by + or −).",
    keyConcepts: ["classification by number of terms"],
    conceptsCovered: ["mth:7:ch12:term-coefficient-factor"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2020"],
    source: "previous-year",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Addition and Subtraction of Algebraic Expressions
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-con-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Only like terms can be added or subtracted in an algebraic expression.",
    answer: "True. Only like terms can be combined. Unlike terms cannot be combined into a single term; they remain as separate terms in the expression.",
    steps: [{ stepNumber: 1, title: "Reason", explanation: "Like terms have the same variable part → can add/subtract coefficients. Unlike terms cannot be simplified further." }],
    hint: "You can only add/subtract 'apples with apples', not 'apples with oranges'.",
    keyConcepts: ["addition of like terms"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "like-terms-addition"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: 3x + 5y and 2x − 3y.",
    answer: "Sum = (3x+2x) + (5y−3y) = 5x + 2y.",
    steps: [
      { stepNumber: 1, title: "Collect like terms", explanation: "x-terms: 3x+2x=5x. y-terms: 5y−3y=2y." },
      { stepNumber: 2, title: "Result", explanation: "5x+2y.", result: "5x+2y" },
    ],
    hint: "Collect like terms separately.",
    keyConcepts: ["addition of expressions"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "add-binomials"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: Subtracting (3x − 5) from 7x + 2 gives 4x + 7.",
    answer: "True. (7x+2) − (3x−5) = 7x+2−3x+5 = 4x+7. Note the change of sign when distributing the subtraction.",
    steps: [
      { stepNumber: 1, title: "Distribute subtraction", explanation: "−(3x−5)=−3x+5." },
      { stepNumber: 2, title: "Combine", explanation: "7x+2−3x+5=4x+7.", result: "4x+7 ✓" },
    ],
    hint: "When subtracting, change all signs of the subtracted expression.",
    keyConcepts: ["subtraction of expressions", "sign change"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "subtraction-sign-change"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Subtract (2a − 3b + c) from (5a + b − 2c).",
    answer: "(5a+b−2c) − (2a−3b+c) = 5a+b−2c−2a+3b−c = 3a+4b−3c.",
    steps: [
      { stepNumber: 1, title: "Change signs", explanation: "−(2a−3b+c)=−2a+3b−c." },
      { stepNumber: 2, title: "Combine", explanation: "(5−2)a+(1+3)b+(−2−1)c=3a+4b−3c.", result: "3a+4b−3c" },
    ],
    hint: "Flip the signs of all terms in the expression being subtracted.",
    keyConcepts: ["subtraction of trinomials"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [{ error: "Only changing sign of first term", correction: "ALL signs in the subtracted expression must change." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "subtract-trinomials"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Addition of algebraic expressions is commutative: (P + Q) = (Q + P).",
    answer: "True. Like addition of numbers, addition of algebraic expressions is commutative. The order of adding expressions does not change the result.",
    steps: [{ stepNumber: 1, title: "Example", explanation: "(2x+3)+(x−5)=3x−2=(x−5)+(2x+3)=3x−2. ✓" }],
    hint: "Commutativity means order doesn't matter.",
    keyConcepts: ["commutative property of addition"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "commutative-addition"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch12-con-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "What should be added to 3x² − 4x + 5 to get 7x² + 2x − 1?",
    answer: "Required expression = (7x²+2x−1) − (3x²−4x+5) = 7x²+2x−1−3x²+4x−5 = 4x²+6x−6.",
    steps: [
      { stepNumber: 1, title: "Subtract", explanation: "(7x²+2x−1)−(3x²−4x+5)=4x²+6x−6.", result: "4x²+6x−6" },
    ],
    hint: "Required = target − original.",
    keyConcepts: ["finding what to add", "expression subtraction"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "find-addend"],
    source: "concept",
  },

  // ── NCERT (t2) ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-nce-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: 3mn + 4 and mn − 8.  [NCERT Ex 12.2]",
    answer: "4mn − 4.",
    steps: [{ stepNumber: 1, title: "Add", explanation: "(3mn+mn)+(4−8)=4mn−4.", result: "4mn−4" }],
    hint: "Add like terms.",
    keyConcepts: ["addition of expressions"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add: 4p²q − 3pq + 5q and −7p²q + 3pq.  [NCERT Ex 12.2]",
    answer: "(4p²q−7p²q)+(−3pq+3pq)+5q = −3p²q + 5q.",
    steps: [
      { stepNumber: 1, title: "Add like terms", explanation: "p²q: 4−7=−3; pq: −3+3=0; q: +5.", result: "−3p²q+5q" },
    ],
    hint: "Each variable group adds separately.",
    keyConcepts: ["addition of multi-variable expressions"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Subtract 3a − b from 5a + 2b.  [NCERT Ex 12.2]",
    answer: "(5a+2b)−(3a−b) = 5a+2b−3a+b = 2a+3b.",
    steps: [
      { stepNumber: 1, title: "Change signs", explanation: "−(3a−b)=−3a+b." },
      { stepNumber: 2, title: "Add", explanation: "2a+3b.", result: "2a+3b" },
    ],
    hint: "Subtract means change signs of second expression.",
    keyConcepts: ["subtraction of binomials"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Add: a² + 2ab + b², a² − b², and −2ab + b².  [NCERT Ex 12.2]",
    answer: "(a²+a²) + (2ab−2ab) + (b²−b²+b²) = 2a² + 0 + b² = 2a² + b².",
    steps: [
      { stepNumber: 1, title: "Group like terms", explanation: "a²:2; ab:0; b²:1." },
      { stepNumber: 2, title: "Result", explanation: "2a²+b².", result: "2a²+b²" },
    ],
    hint: "Add all three expressions term by term.",
    keyConcepts: ["adding three expressions"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Subtract 2x³ + x² − 3x + 5 from 5x³ − x² + 2x − 1.  [NCERT Ex 12.2]",
    answer: "(5x³−x²+2x−1)−(2x³+x²−3x+5) = 3x³−2x²+5x−6.",
    steps: [
      { stepNumber: 1, title: "Change signs", explanation: "−(2x³+x²−3x+5)=−2x³−x²+3x−5." },
      { stepNumber: 2, title: "Add", explanation: "3x³−2x²+5x−6.", result: "3x³−2x²+5x−6" },
    ],
    hint: "Flip all signs of the subtracted polynomial.",
    keyConcepts: ["subtraction of polynomials"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [{ error: "Only flipping sign of first term", correction: "All signs must change: +→−, −→+." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "NCERT-Ex12.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If A = 3x² − y + z, B = x + y − 3z, C = −x + 2y − z, find A + B − C.  [NCERT Ex 12.2]",
    answer: "A+B = 4x²+x+2y−3z+z−3z... Let me compute: A+B=(3x²−y+z)+(x+y−3z)=3x²+x+0y−2z. A+B−C=(3x²+x−2z)−(−x+2y−z)=3x²+x−2z+x−2y+z=3x²+2x−2y−z.",
    steps: [
      { stepNumber: 1, title: "A+B", explanation: "3x²+x−2z." },
      { stepNumber: 2, title: "−C", explanation: "+x−2y+z." },
      { stepNumber: 3, title: "Total", explanation: "3x²+2x−2y−z.", result: "3x²+2x−2y−z" },
    ],
    hint: "Compute A+B first, then subtract C.",
    keyConcepts: ["combined addition and subtraction"],
    conceptsCovered: ["mth:7:ch12:expression-addition", "mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "ABC-combination"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "What should be subtracted from 5a² − 3b² + 6 to get 2a² + b² − 3?  [NCERT Ex 12.2]",
    answer: "Required = (5a²−3b²+6)−(2a²+b²−3) = 3a²−4b²+9.",
    steps: [
      { stepNumber: 1, title: "Compute", explanation: "5a²−2a²=3a²; −3b²−b²=−4b²; 6+3=9.", result: "3a²−4b²+9" },
    ],
    hint: "What to subtract = original − target.",
    keyConcepts: ["finding subtrahend"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "find-subtrahend"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-017",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The perimeter of a triangle is 9x² − 5x + 7. Two sides are 3x² + x − 1 and 2x² − 2x + 3. Find the third side.  [NCERT Ex 12.2]",
    answer: "Third side = perimeter − (side1+side2) = (9x²−5x+7)−(5x²−x+2)=4x²−4x+5.",
    steps: [
      { stepNumber: 1, title: "Sum of two sides", explanation: "5x²−x+2." },
      { stepNumber: 2, title: "Third side", explanation: "(9x²−5x+7)−(5x²−x+2)=4x²−4x+5.", result: "4x²−4x+5" },
    ],
    hint: "Third side = Perimeter − sum of other two sides.",
    keyConcepts: ["perimeter and algebraic expressions", "subtraction application"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "triangle-perimeter-expression"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch12-nce-018",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Simplify: (3a + b − c) + (2a − b + 3c) − (a + 2b − 4c).  [NCERT Ex 12.2]",
    answer: "First add: 5a+2c. Then subtract (a+2b−4c): 5a+2c−a−2b+4c=4a−2b+6c.",
    steps: [
      { stepNumber: 1, title: "First sum", explanation: "(3a+b−c)+(2a−b+3c)=5a+0b+2c." },
      { stepNumber: 2, title: "Subtract third", explanation: "5a+2c−(a+2b−4c)=4a−2b+6c.", result: "4a−2b+6c" },
    ],
    hint: "Handle one operation at a time.",
    keyConcepts: ["combined simplification"],
    conceptsCovered: ["mth:7:ch12:expression-addition", "mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch12", "simplify-combined"],
    source: "ncert",
  },

  // ── ICSE (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-ics-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Add 3x/2 + y/3 and x/4 − 2y/3.",
    answer: "x: 3/2+1/4=6/4+1/4=7/4. y: 1/3−2/3=−1/3. Result: 7x/4 − y/3.",
    steps: [
      { stepNumber: 1, title: "x terms", explanation: "3x/2+x/4=7x/4." },
      { stepNumber: 2, title: "y terms", explanation: "y/3−2y/3=−y/3.", result: "7x/4−y/3" },
    ],
    hint: "Add x terms and y terms separately using LCD.",
    keyConcepts: ["addition with fractional coefficients"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch12", "fractional-coefficients"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch12-ics-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Simplify and evaluate for x=2, y=−1: (2x² − 3y) + (x + y²) − (3x² − y²).",
    answer: "Simplify: 2x²−3y+x+y²−3x²+y²=−x²+x−3y+2y². At x=2,y=−1: −4+2+3+2=3.",
    steps: [
      { stepNumber: 1, title: "Simplify", explanation: "−x²+x−3y+2y²." },
      { stepNumber: 2, title: "Evaluate x=2,y=−1", explanation: "−4+2+3+2=3.", result: "3" },
    ],
    hint: "Simplify first, then substitute.",
    keyConcepts: ["simplify then evaluate"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch12", "simplify-evaluate"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch12-ics-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The sum of three expressions is 4x² − 2x + 5. If two of them are x² + x − 3 and x² − 3x + 1, find the third.",
    answer: "Third = (4x²−2x+5)−(x²+x−3)−(x²−3x+1)=4x²−2x+5−x²−x+3−x²+3x−1=2x²+0x+7=2x²+7.",
    steps: [
      { stepNumber: 1, title: "Subtract both known", explanation: "4x²−2x+5−(2x²−2x+−2)..." },
      { stepNumber: 2, title: "Step by step", explanation: "Sum of two known: 2x²−2x−2. Third=4x²−2x+5−2x²+2x+2=2x²+7.", result: "2x²+7" },
    ],
    hint: "Third = total − (first + second).",
    keyConcepts: ["finding missing expression from sum"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch12", "find-third-expression"],
    source: "icse",
  },

  // ── COMPETENCY (t2) ──────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-cmp-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Add 2a + 3 and 4a − 7.",
    options: ["6a − 4", "6a + 10", "2a − 4", "6a − 7"],
    answer: "6a − 4",
    steps: [{ stepNumber: 1, title: "Add", explanation: "2a+4a=6a; 3−7=−4. Result: 6a−4." }],
    hint: "Add like terms.",
    keyConcepts: ["adding binomials"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "MCQ-add"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Subtract x² − 3x + 2 from 3x² + x − 5.",
    options: ["2x² + 4x − 7", "2x² − 4x − 7", "4x² − 2x − 3", "2x² + 4x + 7"],
    answer: "2x² + 4x − 7",
    steps: [{ stepNumber: 1, title: "Subtract", explanation: "(3x²+x−5)−(x²−3x+2)=2x²+4x−7." }],
    hint: "Change all signs of the second expression.",
    keyConcepts: ["polynomial subtraction"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "MCQ-subtract"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The total profit of a business is (5x + 3y) thousand rupees. Partner A gets (2x − y) and Partner B gets (x + 2y). How much does Partner C get?",
    answer: "C = (5x+3y)−(2x−y)−(x+2y)=5x+3y−2x+y−x−2y=2x+2y.",
    steps: [
      { stepNumber: 1, title: "Total minus A and B", explanation: "5x+3y−(3x+y)=2x+2y.", result: "₹(2x+2y) thousand" },
    ],
    hint: "C = Total − A − B.",
    keyConcepts: ["real-life expression subtraction"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "profit-sharing"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 10,
    question: "A rectangular garden has length (3x+5) m and width (2x−1) m. An inner rectangular flower bed is (x+3) m by (x−2) m. (a) Find the perimeter of the garden. (b) Find the area of the path surrounding the flower bed (difference of areas). Evaluate both for x=4.",
    answer: "(a) Perimeter=2[(3x+5)+(2x−1)]=2(5x+4)=10x+8. At x=4: 48 m. (b) Garden area=(3x+5)(2x−1)=6x²+7x−5. Flower bed=(x+3)(x−2)=x²+x−6. Path area=5x²+6x+1. At x=4: 5(16)+24+1=80+25=105 m².",
    steps: [
      { stepNumber: 1, title: "Perimeter", explanation: "10x+8; at x=4: 48 m." },
      { stepNumber: 2, title: "Areas", explanation: "Garden=6x²+7x−5; Bed=x²+x−6; Path=5x²+6x+1." },
      { stepNumber: 3, title: "Evaluate", explanation: "Path=80+24+1=105 m².", result: "Perimeter=48m; Path=105m²" },
    ],
    hint: "Perimeter = 2(l+w); Area of path = garden area − flower bed area.",
    keyConcepts: ["perimeter and area expressions", "subtraction of polynomials"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "garden-case-study"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "If P = 2x + 3, Q = x − 5, which expression equals P + Q − 2?",
    options: ["3x − 4", "3x + 4", "x − 4", "3x − 6"],
    answer: "3x − 4",
    steps: [{ stepNumber: 1, title: "Compute", explanation: "P+Q=3x−2. Subtract 2: 3x−4." }],
    hint: "Add P and Q first, then subtract 2.",
    keyConcepts: ["combining expressions with constants"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "P-Q-expression"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The temperature at noon is (5t + 3)°C. By evening it drops by (2t − 1)°C. What is the evening temperature?",
    answer: "(5t+3)−(2t−1)=5t+3−2t+1=3t+4°C.",
    steps: [{ stepNumber: 1, title: "Subtract drop", explanation: "3t+4°C.", result: "(3t+4)°C" }],
    hint: "Evening = Noon temperature − drop.",
    keyConcepts: ["expression subtraction", "real-life temperature"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "temperature-expression"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Three students have scores: Asha: (3m²+2m), Balu: (m²−3m+5), Chandan: (2m²+m−2). Who has the highest total at m=2? What is the class total?",
    answer: "Asha at m=2: 12+4=16. Balu: 4−6+5=3. Chandan: 8+2−2=8. Highest: Asha. Class total: 16+3+8=27. Expression: 6m²+0m+3=6m²+3; at m=2: 24+3=27. ✓",
    steps: [
      { stepNumber: 1, title: "Evaluate each at m=2", explanation: "Asha=16; Balu=3; Chandan=8." },
      { stepNumber: 2, title: "Highest and total", explanation: "Asha highest. Total=27.", result: "Asha; total=27" },
    ],
    hint: "Substitute m=2 into each expression.",
    keyConcepts: ["comparison by evaluation", "total expression"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "score-comparison"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch12-cmp-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "By how much does 5x² − 3x + 1 exceed 2x² + x − 4?",
    answer: "(5x²−3x+1)−(2x²+x−4)=3x²−4x+5.",
    steps: [{ stepNumber: 1, title: "Subtract", explanation: "3x²−4x+5.", result: "3x²−4x+5" }],
    hint: "'Exceeds by' means subtract.",
    keyConcepts: ["finding excess by subtraction"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch12", "exceeds-by"],
    source: "competency",
  },

  // ── HOTS (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-hot-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Ravi adds (2x+3) to an expression E and gets (5x²−x+7). Priya subtracts (x²−2x) from E and gets (3x+1). Find E and check for consistency.",
    answer: "From Ravi: E = (5x²−x+7)−(2x+3) = 5x²−3x+4. Check with Priya: E−(x²−2x)=5x²−3x+4−x²+2x=4x²−x+4. Priya's result=3x+1. These don't match → inconsistency: both statements cannot be true simultaneously. E=5x²−3x+4 from Ravi, but Priya's equation gives E=x²+5x+1. Different E values → inconsistent problem.",
    steps: [
      { stepNumber: 1, title: "From Ravi", explanation: "E=5x²−3x+4." },
      { stepNumber: 2, title: "From Priya", explanation: "E=(3x+1)+(x²−2x)=x²+x+1." },
      { stepNumber: 3, title: "Consistency check", explanation: "5x²−3x+4 ≠ x²+x+1. Inconsistent.", result: "Inconsistent; E cannot satisfy both" },
    ],
    hint: "Solve for E from each statement and compare.",
    keyConcepts: ["finding missing expression", "consistency check"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [{ error: "Assuming both statements are consistent", correction: "Always check — the two derived expressions may differ." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "consistency-check"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove or disprove: If A − B = C, then B − A = −C. Verify with A = 3x²+2x, B = x²−x, C = 2x²+3x.",
    answer: "A−B=(3x²+2x)−(x²−x)=2x²+3x=C. ✓ B−A=(x²−x)−(3x²+2x)=−2x²−3x=−C. ✓ The statement is TRUE: B−A = −(A−B) = −C, because subtraction reverses: A−B = −(B−A).",
    steps: [
      { stepNumber: 1, title: "Compute A−B", explanation: "2x²+3x=C. ✓" },
      { stepNumber: 2, title: "Compute B−A", explanation: "−2x²−3x=−C. ✓" },
      { stepNumber: 3, title: "Proved", explanation: "B−A=−(A−B)=−C always holds." },
    ],
    hint: "Check if B−A is the additive inverse of A−B.",
    keyConcepts: ["additive inverse", "proof with algebraic expressions"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "prove-subtraction-reverse"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Create a 'number puzzle' using algebraic expressions: think of a number n, triple it, add (n−5), subtract (2n+1). What is the expression for the result? What value of n makes the result 6?",
    answer: "Start: n. Triple: 3n. Add (n−5): 3n+n−5=4n−5. Subtract (2n+1): 4n−5−2n−1=2n−6. Result expression: 2n−6. For result=6: 2n−6=6→2n=12→n=6.",
    steps: [
      { stepNumber: 1, title: "Build expression", explanation: "3n+(n−5)−(2n+1)=2n−6." },
      { stepNumber: 2, title: "Solve for 6", explanation: "2n−6=6→n=6.", result: "2n−6; n=6" },
    ],
    hint: "Follow each operation step-by-step.",
    keyConcepts: ["building expressions from operations", "solving for variable"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "number-puzzle"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 12,
    question: "The expressions (ax²+bx+c) and (px²+qx+r) are added to give (5x²−2x+7). Subtracted in the same order, they give (x²+6x−3). Find each expression.",
    answer: "Let E₁=ax²+bx+c and E₂=px²+qx+r. E₁+E₂=5x²−2x+7. E₁−E₂=x²+6x−3. Adding both: 2E₁=6x²+4x+4 → E₁=3x²+2x+2. Subtracting: 2E₂=4x²−8x+10 → E₂=2x²−4x+5.",
    steps: [
      { stepNumber: 1, title: "System", explanation: "E₁+E₂=5x²−2x+7; E₁−E₂=x²+6x−3." },
      { stepNumber: 2, title: "Solve", explanation: "2E₁=6x²+4x+4→E₁=3x²+2x+2. E₂=2x²−4x+5.", result: "E₁=3x²+2x+2; E₂=2x²−4x+5" },
    ],
    hint: "Add the two equations to find E₁; subtract to find E₂.",
    keyConcepts: ["system of expression equations", "finding expressions from sum and difference"],
    conceptsCovered: ["mth:7:ch12:expression-addition", "mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "system-expressions"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch12-hot-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Anita claims: 'Adding the same expression to two different expressions and then subtracting it gives the same result as directly subtracting the two original expressions.' Is she correct? Prove with expressions P, Q, R.",
    answer: "(P+R)−(Q+R)=P+R−Q−R=P−Q. Yes, Anita is correct! The R terms cancel. This generalizes: adding the same expression to both and then subtracting preserves the difference.",
    steps: [
      { stepNumber: 1, title: "Compute (P+R)−(Q+R)", explanation: "P+R−Q−R=P−Q." },
      { stepNumber: 2, title: "Conclusion", explanation: "Anita is correct. R cancels completely." },
    ],
    hint: "Expand (P+R)−(Q+R) and simplify.",
    keyConcepts: ["cancellation property", "algebraic proof"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch12", "cancellation-proof"],
    source: "hots",
  },

  // ── PREVIOUS YEAR (t2) ───────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch12-pyq-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Add 5x − 2y and 3x + 4y.  [CBSE 2019]",
    answer: "8x + 2y.",
    steps: [{ stepNumber: 1, title: "Add", explanation: "5x+3x=8x; −2y+4y=2y.", result: "8x+2y" }],
    hint: "Add like terms.",
    keyConcepts: ["addition of binomials"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Subtract (2x − 3y + 4) from (5x + y − 7).  [SA-I 2020]",
    answer: "3x + 4y − 11.",
    steps: [{ stepNumber: 1, title: "Subtract", explanation: "5x+y−7−2x+3y−4=3x+4y−11.", result: "3x+4y−11" }],
    hint: "Change signs when subtracting.",
    keyConcepts: ["polynomial subtraction"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the sum of 3a − 4b + 5c, −a + 2b − 3c, and 2a + b − c.  [CBSE 2021]",
    answer: "4a − b + c.",
    steps: [{ stepNumber: 1, title: "Add all", explanation: "(3−1+2)a+(−4+2+1)b+(5−3−1)c=4a−b+c.", result: "4a−b+c" }],
    hint: "Add the coefficients of each variable separately.",
    keyConcepts: ["adding three polynomials"],
    conceptsCovered: ["mth:7:ch12:expression-addition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "What must be added to x³ − 3x² + 4x − 5 to get x³ + x² − x + 2?  [CBSE 2022]",
    answer: "(x³+x²−x+2)−(x³−3x²+4x−5)=4x²−5x+7.",
    steps: [
      { stepNumber: 1, title: "Subtract", explanation: "x³−x³=0; x²+3x²=4x²; −x−4x=−5x; 2+5=7.", result: "4x²−5x+7" },
    ],
    hint: "Required = target − given.",
    keyConcepts: ["finding addend"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify and find the value when x=2: (3x² + x − 4) − (x² − 5x + 3).  [ICSE 2021]",
    answer: "2x²+6x−7. At x=2: 8+12−7=13.",
    steps: [
      { stepNumber: 1, title: "Simplify", explanation: "2x²+6x−7." },
      { stepNumber: 2, title: "Evaluate", explanation: "8+12−7=13.", result: "13" },
    ],
    hint: "Simplify first, then substitute.",
    keyConcepts: ["simplify and evaluate"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "ICSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch12-pyq-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch12", chapterName: "Algebraic Expressions",
    topicId: "t2", topicName: "Addition and Subtraction",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The sum of two expressions is 7x² − 3xy + 2y². If one expression is 4x² + xy − y², find the other.  [CBSE 2022]",
    answer: "(7x²−3xy+2y²)−(4x²+xy−y²)=3x²−4xy+3y².",
    steps: [
      { stepNumber: 1, title: "Subtract", explanation: "7x²−4x²=3x²; −3xy−xy=−4xy; 2y²+y²=3y².", result: "3x²−4xy+3y²" },
    ],
    hint: "Second = Sum − First.",
    keyConcepts: ["finding second expression from sum"],
    conceptsCovered: ["mth:7:ch12:expression-subtraction"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch12", "CBSE2022-sum"],
    source: "previous-year",
  },

];
