// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 13: Exponents and Powers
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Laws of Exponents           — 37 q
 *   t2 Scientific Notation         — 38 q
 *
 * Concept nodes:
 *   mth:7:ch13:product-rule
 *   mth:7:ch13:quotient-rule
 *   mth:7:ch13:power-rule
 *   mth:7:ch13:zero-exponent
 *   mth:7:ch13:scientific-notation
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH13_EXPONENTS_AND_POWERS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Laws of Exponents
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-con-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: aᵐ × aⁿ = aᵐ⁺ⁿ (product rule of exponents).",
    answer: "True. When multiplying two powers with the same base, we add the exponents. Example: 2³ × 2⁴ = 2⁷ = 128.",
    steps: [{ stepNumber: 1, title: "Product rule", explanation: "aᵐ × aⁿ = a^(m+n). Same base → add exponents." }],
    hint: "Multiplying powers of the same base: add exponents.",
    keyConcepts: ["product rule", "exponent addition"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "product-rule"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State the quotient rule of exponents and give an example.",
    answer: "Quotient rule: aᵐ ÷ aⁿ = aᵐ⁻ⁿ (where a ≠ 0). When dividing powers of the same base, subtract the exponents. Example: 3⁷ ÷ 3⁴ = 3³ = 27.",
    steps: [
      { stepNumber: 1, title: "Quotient rule", explanation: "aᵐ ÷ aⁿ = a^(m−n)." },
      { stepNumber: 2, title: "Example", explanation: "3⁷÷3⁴=3³=27." },
    ],
    hint: "Dividing same base: subtract exponents.",
    keyConcepts: ["quotient rule"],
    conceptsCovered: ["mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "quotient-rule"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: (aᵐ)ⁿ = aᵐⁿ (power of a power rule).",
    answer: "True. When raising a power to another power, multiply the exponents. Example: (2³)⁴ = 2¹² = 4096.",
    steps: [{ stepNumber: 1, title: "Power rule", explanation: "(aᵐ)ⁿ = a^(m×n). Multiply exponents." }],
    hint: "Power of a power: multiply exponents.",
    keyConcepts: ["power rule"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "power-rule"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is a⁰ for any non-zero a? Explain why.",
    answer: "a⁰ = 1 for any a ≠ 0. Reason: using the quotient rule, aⁿ ÷ aⁿ = a^(n−n) = a⁰. But also aⁿ ÷ aⁿ = 1. Therefore a⁰ = 1.",
    steps: [
      { stepNumber: 1, title: "Proof", explanation: "aⁿ/aⁿ = a^(n−n) = a⁰ and aⁿ/aⁿ = 1. So a⁰ = 1." },
    ],
    hint: "Use the quotient rule: aⁿ/aⁿ = a⁰ = 1.",
    keyConcepts: ["zero exponent", "a⁰ = 1"],
    conceptsCovered: ["mth:7:ch13:zero-exponent"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking a⁰ = 0", correction: "a⁰ = 1 for any non-zero a. Only 0⁰ is undefined." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "zero-exponent"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: (ab)ⁿ = aⁿbⁿ.",
    answer: "True. The power distributes over multiplication: (ab)ⁿ = aⁿbⁿ. Example: (2×3)⁴ = 6⁴ = 1296 = 2⁴ × 3⁴ = 16 × 81 = 1296. ✓",
    steps: [
      { stepNumber: 1, title: "Rule", explanation: "(ab)ⁿ = aⁿbⁿ." },
      { stepNumber: 2, title: "Verify", explanation: "(2×3)⁴=6⁴=1296=16×81=1296. ✓" },
    ],
    hint: "Power distributes over products.",
    keyConcepts: ["power of a product"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "power-product"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simplify using laws of exponents: (a) 5³ × 5⁴  (b) 7⁸ ÷ 7³  (c) (3²)⁵.",
    answer: "(a) 5⁷  (b) 7⁵  (c) 3¹⁰.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "5^(3+4)=5⁷." },
      { stepNumber: 2, title: "(b)", explanation: "7^(8−3)=7⁵." },
      { stepNumber: 3, title: "(c)", explanation: "3^(2×5)=3¹⁰.", result: "5⁷, 7⁵, 3¹⁰" },
    ],
    hint: "Apply product, quotient, power rules respectively.",
    keyConcepts: ["applying exponent laws"],
    conceptsCovered: ["mth:7:ch13:product-rule", "mth:7:ch13:quotient-rule", "mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "apply-laws"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-nce-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the value: (a) 2¹⁰  (b) 3⁴  (c) 5³  [NCERT Ex 13.1]",
    answer: "(a) 1024  (b) 81  (c) 125.",
    steps: [
      { stepNumber: 1, title: "Calculate", explanation: "2¹⁰=1024; 3⁴=81; 5³=125." },
    ],
    hint: "Multiply the base by itself the given number of times.",
    keyConcepts: ["evaluating powers"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Express using exponents: (a) 8 × 8 × 8 × 8  (b) t × t × t  (c) b × b × b × b × b  [NCERT Ex 13.1]",
    answer: "(a) 8⁴  (b) t³  (c) b⁵.",
    steps: [{ stepNumber: 1, title: "Count and write", explanation: "4 eights = 8⁴; 3 t's = t³; 5 b's = b⁵." }],
    hint: "Count how many times the base is multiplied.",
    keyConcepts: ["exponential notation"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simplify: (a) 2³ × 2⁵  (b) 3² × 3⁴ × 3²  [NCERT Ex 13.2]",
    answer: "(a) 2⁸=256  (b) 3⁸=6561.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "2^(3+5)=2⁸=256." },
      { stepNumber: 2, title: "(b)", explanation: "3^(2+4+2)=3⁸=6561.", result: "256 and 6561" },
    ],
    hint: "Add exponents when bases are the same.",
    keyConcepts: ["product rule"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simplify and express as a single power: 7⁶ ÷ 7²  [NCERT Ex 13.2]",
    answer: "7^(6−2) = 7⁴ = 2401.",
    steps: [{ stepNumber: 1, title: "Quotient rule", explanation: "7^4=2401.", result: "7⁴" }],
    hint: "Subtract exponents when dividing same base.",
    keyConcepts: ["quotient rule"],
    conceptsCovered: ["mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify: (2³)⁴ ÷ 2⁷  [NCERT Ex 13.2]",
    answer: "(2³)⁴=2¹². 2¹²÷2⁷=2⁵=32.",
    steps: [
      { stepNumber: 1, title: "Power rule", explanation: "(2³)⁴=2¹²." },
      { stepNumber: 2, title: "Quotient", explanation: "2¹²÷2⁷=2⁵=32.", result: "32" },
    ],
    hint: "Power rule first, then quotient rule.",
    keyConcepts: ["combined laws"],
    conceptsCovered: ["mth:7:ch13:power-rule", "mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Evaluate: (3 × 5)² ÷ (3 × 5)  [NCERT Ex 13.2]",
    answer: "(3×5)² ÷ (3×5)¹ = (3×5)^(2−1) = (3×5)¹ = 15.",
    steps: [
      { stepNumber: 1, title: "Use quotient rule on (15)", explanation: "15²÷15=15^(2−1)=15.", result: "15" },
    ],
    hint: "Treat (3×5) as a single base.",
    keyConcepts: ["quotient rule with product base"],
    conceptsCovered: ["mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify: (2⁵ × 3²) ÷ (2² × 3)  [NCERT Ex 13.2]",
    answer: "2^(5−2) × 3^(2−1) = 2³ × 3¹ = 8 × 3 = 24.",
    steps: [
      { stepNumber: 1, title: "Separate bases", explanation: "2⁵/2²=2³; 3²/3=3¹." },
      { stepNumber: 2, title: "Multiply", explanation: "8×3=24.", result: "24" },
    ],
    hint: "Apply quotient rule to each base separately.",
    keyConcepts: ["quotient rule with multiple bases"],
    conceptsCovered: ["mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the value of: (a) 5⁰  (b) (−7)⁰  (c) (1/2)⁰  [NCERT Ex 13.2]",
    answer: "(a) 1  (b) 1  (c) 1. Any non-zero number raised to power 0 equals 1.",
    steps: [{ stepNumber: 1, title: "Zero exponent rule", explanation: "a⁰=1 for all a≠0." }],
    hint: "a⁰ = 1 for any non-zero a.",
    keyConcepts: ["zero exponent"],
    conceptsCovered: ["mth:7:ch13:zero-exponent"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking (−7)⁰=−1 or 0", correction: "Any non-zero number to the power 0 is 1." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Simplify: [2² × (5³ × 2⁵)] ÷ [5⁵ × 2⁴]  [NCERT Ex 13.2]",
    answer: "= [2^(2+5) × 5³] ÷ [5⁵ × 2⁴] = [2⁷ × 5³] ÷ [5⁵ × 2⁴] = 2^(7−4) × 5^(3−5) = 2³ × 5^(−2) = 8/25.",
    steps: [
      { stepNumber: 1, title: "Numerator", explanation: "2⁷×5³." },
      { stepNumber: 2, title: "Apply quotient", explanation: "2³×5^(−2)=8/25.", result: "8/25" },
    ],
    hint: "Combine all 2's and 5's separately using product and quotient rules.",
    keyConcepts: ["combined exponent laws"],
    conceptsCovered: ["mth:7:ch13:product-rule", "mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "complex-simplification"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-ics-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If 2ˣ = 32, find x. Then simplify 2ˣ × 2³ ÷ 2².",
    answer: "2⁵=32 → x=5. 2⁵×2³÷2²=2^(5+3−2)=2⁶=64.",
    steps: [
      { stepNumber: 1, title: "Find x", explanation: "2⁵=32 → x=5." },
      { stepNumber: 2, title: "Simplify", explanation: "2^6=64.", result: "x=5; 64" },
    ],
    hint: "Write 32 as a power of 2.",
    keyConcepts: ["solving exponential equation", "applying laws"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch13", "solve-exponential"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch13-ics-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Simplify: (4ˣ × 16) ÷ (8 × 4^(x−1)).",
    answer: "4ˣ×16÷(8×4^(x−1))=4ˣ×4²÷(2³×4^(x−1))=4^(x+2)÷(2³×4^(x−1)). Convert to base 2: 2^(2x+4)÷(2³×2^(2x−2))=2^(2x+4−3−2x+2)=2³=8.",
    steps: [
      { stepNumber: 1, title: "Convert 16=4², 8=2³", explanation: "4ˣ×4²÷(2³×4^(x−1))." },
      { stepNumber: 2, title: "Convert 4=2²", explanation: "2^(2x+4)÷2^(3+2x−2)=2^3=8.", result: "8" },
    ],
    hint: "Convert all to the same base (2).",
    keyConcepts: ["converting to common base", "simplification"],
    conceptsCovered: ["mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch13", "common-base"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch13-ics-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find n: (2⁵ ÷ 2²)² = 2ⁿ.",
    answer: "(2⁵÷2²)²=(2³)²=2⁶. So n=6.",
    steps: [
      { stepNumber: 1, title: "Inside bracket", explanation: "2⁵÷2²=2³." },
      { stepNumber: 2, title: "Power rule", explanation: "(2³)²=2⁶. n=6.", result: "n=6" },
    ],
    hint: "Apply quotient rule inside brackets first.",
    keyConcepts: ["finding unknown exponent"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch13", "find-n"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch13-ics-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Prove that 5^(n+2) − 5^n = 24 × 5^n.",
    answer: "LHS: 5^(n+2)−5^n=5^n×5²−5^n=5^n(25−1)=5^n×24=24×5^n=RHS. ✓",
    steps: [
      { stepNumber: 1, title: "Factor out 5^n", explanation: "5^n(5²−1)=5^n(24)=24×5^n." },
    ],
    hint: "Factor out 5^n from both terms.",
    keyConcepts: ["exponential proof", "factoring"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch13", "exponential-proof"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-cmp-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "2³ × 2⁴ = ?",
    options: ["2⁷", "4⁷", "2¹²", "6⁷"],
    answer: "2⁷",
    steps: [{ stepNumber: 1, title: "Product rule", explanation: "2^(3+4)=2⁷." }],
    hint: "Same base: add exponents.",
    keyConcepts: ["product rule"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "MCQ-product"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "10⁶ ÷ 10² = ?",
    options: ["10⁸", "10⁴", "10³", "10¹²"],
    answer: "10⁴",
    steps: [{ stepNumber: 1, title: "Quotient rule", explanation: "10^(6−2)=10⁴." }],
    hint: "Same base: subtract exponents.",
    keyConcepts: ["quotient rule"],
    conceptsCovered: ["mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "MCQ-quotient"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A bacteria doubles every hour. If you start with 1 bacterium, how many are there after 10 hours? Express as a power of 2.",
    answer: "After 10 hours: 2¹⁰ = 1024 bacteria.",
    steps: [
      { stepNumber: 1, title: "Doubling = 2x per hour", explanation: "After n hours: 2ⁿ." },
      { stepNumber: 2, title: "After 10 hours", explanation: "2¹⁰=1024.", result: "1024 bacteria" },
    ],
    hint: "Doubling n times = 2ⁿ.",
    keyConcepts: ["exponential growth", "powers of 2"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "bacteria-growth"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 5, estimatedTimeMinutes: 10,
    question: "India's population is approximately 1.4 × 10⁹. Each person drinks about 2 litres of water per day. (a) Find the total litres consumed per day (as a power of 10). (b) If each litre is stored in a 1 cm × 1 cm × 1 cm cube (1 mL), how many cubic centimetres is the daily water? (c) Express the answer in scientific notation.",
    answer: "(a) 1.4×10⁹ × 2 = 2.8×10⁹ litres/day. (b) 1 litre = 1000 cm³ = 10³ cm³. Total = 2.8×10⁹ × 10³ = 2.8×10¹² cm³. (c) 2.8×10¹² cm³ = scientific notation already.",
    steps: [
      { stepNumber: 1, title: "Total litres", explanation: "2.8×10⁹ L." },
      { stepNumber: 2, title: "Convert to cm³", explanation: "×10³=2.8×10¹² cm³." },
      { stepNumber: 3, title: "Scientific notation", explanation: "2.8×10¹².", result: "2.8×10¹² cm³" },
    ],
    hint: "1 litre = 1000 cm³ = 10³ cm³.",
    keyConcepts: ["scientific notation", "real-world powers"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "water-consumption"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Which of the following equals 2⁶?",
    options: ["4² × 2²", "(2³)²", "2 × 2⁵", "All of these"],
    answer: "All of these",
    steps: [{ stepNumber: 1, title: "Check all", explanation: "4²×2²=2⁴×2²=2⁶✓; (2³)²=2⁶✓; 2×2⁵=2⁶✓." }],
    hint: "Convert all to powers of 2.",
    keyConcepts: ["multiple representations"],
    conceptsCovered: ["mth:7:ch13:product-rule", "mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "multiple-representations"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A computer processes 2¹⁰ operations per second. How many operations in 2⁵ seconds? How many hours to do 2³⁰ operations?",
    answer: "In 2⁵ seconds: 2¹⁰×2⁵=2¹⁵=32768 operations. For 2³⁰: time=2³⁰÷2¹⁰=2²⁰ seconds≈1,048,576 sec≈12.1 days.",
    steps: [
      { stepNumber: 1, title: "Operations in 2⁵ sec", explanation: "2¹⁰×2⁵=2¹⁵." },
      { stepNumber: 2, title: "Time for 2³⁰", explanation: "2³⁰/2¹⁰=2²⁰ sec≈291 hours≈12 days.", result: "2¹⁵; ≈12 days" },
    ],
    hint: "Operations = rate × time. Time = total / rate.",
    keyConcepts: ["rate problems with powers", "large numbers"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "computer-operations"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The value of 7⁰ + 8⁰ + 9⁰ is:",
    options: ["0", "1", "3", "24"],
    answer: "3",
    steps: [{ stepNumber: 1, title: "Zero exponent", explanation: "7⁰=1; 8⁰=1; 9⁰=1. Sum=3." }],
    hint: "Any non-zero number to the power 0 = 1.",
    keyConcepts: ["zero exponent", "sum"],
    conceptsCovered: ["mth:7:ch13:zero-exponent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "zero-exponent-sum"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The area of a square is 5⁸ cm². Find the side length and express as a power.",
    answer: "Area = side². 5⁸=(side)² → side=5⁴=625 cm.",
    steps: [
      { stepNumber: 1, title: "Side = √Area", explanation: "√(5⁸)=5⁴=625 cm.", result: "5⁴=625 cm" },
    ],
    hint: "√(aⁿ)=a^(n/2).",
    keyConcepts: ["area and side as powers"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "square-area-side"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-hot-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Without calculating exact values, determine which is larger: 2³⁰ or 3²⁰. Show your reasoning.",
    answer: "2³⁰ = (2³)¹⁰ = 8¹⁰. 3²⁰ = (3²)¹⁰ = 9¹⁰. Since 9 > 8, we have 9¹⁰ > 8¹⁰, so 3²⁰ > 2³⁰.",
    steps: [
      { stepNumber: 1, title: "Express as same power of 10", explanation: "2³⁰=8¹⁰; 3²⁰=9¹⁰." },
      { stepNumber: 2, title: "Compare bases", explanation: "9>8 → 9¹⁰>8¹⁰ → 3²⁰>2³⁰.", result: "3²⁰ is larger" },
    ],
    hint: "Try to express both with the same exponent (10).",
    keyConcepts: ["comparing powers", "creative exponent manipulation"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking 2³⁰ > 3²⁰ because 30 > 20", correction: "Must compare bases raised to equal powers." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "compare-powers"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Meera says 2³ × 3³ = 6⁶. Rajan says 2³ × 3³ = 6³. Who is correct and why?",
    answer: "Rajan is correct. 2³ × 3³ = (2×3)³ = 6³ = 216. The rule is (ab)ⁿ = aⁿbⁿ, or equivalently aⁿ×bⁿ=(ab)ⁿ. Meera incorrectly added exponents (which applies only when the BASE is the same, e.g., 2³×2⁵=2⁸). Here the bases are different (2 and 3), so we CANNOT add exponents.",
    steps: [
      { stepNumber: 1, title: "Apply correct rule", explanation: "2³×3³=(2×3)³=6³=216." },
      { stepNumber: 2, title: "Check Meera", explanation: "6⁶=46656≠216. Meera is wrong." },
    ],
    hint: "aⁿ×bⁿ=(ab)ⁿ, not a^(n+n).",
    keyConcepts: ["power of product rule", "common error identification"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [{ error: "Adding exponents when bases differ", correction: "Add exponents only when the bases are identical." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "meera-rajan"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Create a puzzle: 'I am a 3-digit number. I equal 2 raised to some power. I am also a perfect square. What am I?'",
    answer: "Powers of 2: 2¹=2, 2²=4, ..., 2⁷=128 (3 digits), 2⁸=256 (3 digits), 2⁹=512 (3 digits). Perfect squares among 3-digit powers of 2: 256=2⁸=(2⁴)²=16²=4⁴. Answer: 256. It is 2⁸, a 3-digit number, and a perfect square (16²).",
    steps: [
      { stepNumber: 1, title: "3-digit powers of 2", explanation: "2⁷=128, 2⁸=256, 2⁹=512." },
      { stepNumber: 2, title: "Perfect square", explanation: "256=16²✓; 128 and 512 are not perfect squares." },
    ],
    hint: "List 3-digit powers of 2, then check which are perfect squares.",
    keyConcepts: ["powers of 2", "perfect squares", "creative problem"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "puzzle-power-square"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Show that 2¹⁰⁰ > 10³⁰ without computing exact values.",
    answer: "2¹⁰ = 1024 > 10³ = 1000. So 2¹⁰ > 10³. Raise both to the 10th power: (2¹⁰)¹⁰ > (10³)¹⁰ → 2¹⁰⁰ > 10³⁰. QED.",
    steps: [
      { stepNumber: 1, title: "Key comparison", explanation: "2¹⁰=1024>1000=10³." },
      { stepNumber: 2, title: "Raise to power 10", explanation: "(2¹⁰)¹⁰>(10³)¹⁰ → 2¹⁰⁰>10³⁰.", result: "2¹⁰⁰>10³⁰" },
    ],
    hint: "Compare 2¹⁰ and 10³ first.",
    keyConcepts: ["exponential inequality", "power rule application"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "exponential-inequality"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Find all integers n such that n² = 2ⁿ. Explain the solution method.",
    answer: "Try integers: n=1: 1≠2. n=2: 4=4=2². ✓ n=4: 16=16=2⁴. ✓ n=−2: 1/4 ≠ 4. n=0: 0≠1. n=3: 9≠8. n=16: 256 vs 2¹⁶=65536. So only n=2 and n=4 among positive integers satisfy n²=2ⁿ.",
    steps: [
      { stepNumber: 1, title: "Check n=2", explanation: "4=4. ✓" },
      { stepNumber: 2, title: "Check n=4", explanation: "16=16. ✓" },
      { stepNumber: 3, title: "Check others", explanation: "n=0,1,3,5,...don't work.", result: "n=2 and n=4" },
    ],
    hint: "Test small positive integer values systematically.",
    keyConcepts: ["exponential equation", "systematic checking"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [{ error: "Missing n=4", correction: "4²=16=2⁴. Both n=2 and n=4 are solutions." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "n-squared-equals-2n"],
    source: "hots",
  },

  // ── PREVIOUS YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-pyq-001",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simplify: 3⁵ × 3³ ÷ 3⁶.  [CBSE 2019]",
    answer: "3^(5+3−6)=3²=9.",
    steps: [{ stepNumber: 1, title: "Apply laws", explanation: "3²=9.", result: "9" }],
    hint: "Add numerator exponents, subtract denominator.",
    keyConcepts: ["combined laws"],
    conceptsCovered: ["mth:7:ch13:product-rule", "mth:7:ch13:quotient-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-002",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is the value of (11⁵ ÷ 11⁵)?  [SA-I 2020]",
    answer: "11^(5−5) = 11⁰ = 1.",
    steps: [{ stepNumber: 1, title: "Quotient rule", explanation: "11⁰=1.", result: "1" }],
    hint: "a÷a=1, and also a^(n−n)=a⁰=1.",
    keyConcepts: ["zero exponent"],
    conceptsCovered: ["mth:7:ch13:zero-exponent"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-003",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find x: 3^x = 243.  [CBSE 2021]",
    answer: "243 = 3⁵. So x = 5.",
    steps: [{ stepNumber: 1, title: "Express 243 as power of 3", explanation: "3⁵=243 → x=5.", result: "x=5" }],
    hint: "Write 243 as a power of 3.",
    keyConcepts: ["solving exponential equation"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-004",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify: [(2⁵ × 2⁴) ÷ 2⁶]².  [CBSE 2022]",
    answer: "(2^(5+4−6))²=(2³)²=2⁶=64.",
    steps: [
      { stepNumber: 1, title: "Inside bracket", explanation: "2^(9−6)=2³." },
      { stepNumber: 2, title: "Square", explanation: "(2³)²=2⁶=64.", result: "64" },
    ],
    hint: "Apply laws inside brackets first.",
    keyConcepts: ["combined exponent laws"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Express 1024 as a power of 2. Also express it as a power of 4 and as a power of 32.  [ICSE 2021]",
    answer: "1024 = 2¹⁰ = 4⁵ = 32². Verify: 4⁵=1024✓; 32²=1024✓.",
    steps: [
      { stepNumber: 1, title: "Power of 2", explanation: "2¹⁰=1024." },
      { stepNumber: 2, title: "Power of 4", explanation: "4=2², so 4⁵=2¹⁰=1024." },
      { stepNumber: 3, title: "Power of 32", explanation: "32=2⁵, so 32²=2¹⁰=1024.", result: "2¹⁰=4⁵=32²=1024" },
    ],
    hint: "Express 4 and 32 as powers of 2 first.",
    keyConcepts: ["multiple bases for same number"],
    conceptsCovered: ["mth:7:ch13:power-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "ICSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t1", topicName: "Laws of Exponents",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Using prime factorization, express 360000 as a product of powers of prime numbers.  [CBSE 2020]",
    answer: "360000=36×10000=36×10⁴=6²×10⁴=(2×3)²×(2×5)⁴=2²×3²×2⁴×5⁴=2⁶×3²×5⁴.",
    steps: [
      { stepNumber: 1, title: "Factor", explanation: "360000=2⁶×3²×5⁴." },
    ],
    hint: "Factor step by step: 360000=36×10000.",
    keyConcepts: ["prime factorization", "expressing as powers"],
    conceptsCovered: ["mth:7:ch13:product-rule"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2020"],
    source: "previous-year",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Scientific Notation
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-con-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: A number in scientific notation is written as m × 10ⁿ where 1 ≤ m < 10.",
    answer: "True. In standard scientific notation, the coefficient m satisfies 1 ≤ m < 10, and n is an integer. Example: 4.56 × 10⁷.",
    steps: [{ stepNumber: 1, title: "Scientific notation form", explanation: "m×10ⁿ, 1≤m<10, n∈ℤ." }],
    hint: "The coefficient is always between 1 (inclusive) and 10 (exclusive).",
    keyConcepts: ["scientific notation definition"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "scientific-notation-def"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Express in scientific notation: (a) 4,700,000  (b) 0.00023.",
    answer: "(a) 4.7 × 10⁶  (b) 2.3 × 10⁻⁴.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "Move decimal 6 places left: 4.7×10⁶." },
      { stepNumber: 2, title: "(b)", explanation: "Move decimal 4 places right: 2.3×10⁻⁴.", result: "4.7×10⁶; 2.3×10⁻⁴" },
    ],
    hint: "Large number: positive exponent. Small decimal: negative exponent.",
    keyConcepts: ["converting to scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "convert-scientific"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "True or False: 34.5 × 10⁴ is in standard scientific notation.",
    answer: "False. The coefficient 34.5 does not satisfy 1 ≤ m < 10. To convert: 34.5 × 10⁴ = 3.45 × 10⁵.",
    steps: [
      { stepNumber: 1, title: "Check coefficient", explanation: "34.5 ≥ 10 → NOT in standard form." },
      { stepNumber: 2, title: "Correct form", explanation: "3.45×10⁵.", result: "FALSE; correct form = 3.45×10⁵" },
    ],
    hint: "Coefficient must be ≥1 and <10.",
    keyConcepts: ["standard scientific notation check"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "check-scientific"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Convert from scientific notation: (a) 2.8 × 10⁵  (b) 7.3 × 10⁻³.",
    answer: "(a) 280,000  (b) 0.0073.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "Move decimal 5 places right: 280,000." },
      { stepNumber: 2, title: "(b)", explanation: "Move decimal 3 places left: 0.0073.", result: "280000; 0.0073" },
    ],
    hint: "Positive power: move right. Negative power: move left.",
    keyConcepts: ["converting from scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "expand-scientific"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: The distance from the Earth to the Sun (approximately 150,000,000 km) can be written as 1.5 × 10⁸ km in scientific notation.",
    answer: "True. 150,000,000 = 1.5 × 10⁸. The decimal point moves 8 places left.",
    steps: [{ stepNumber: 1, title: "Convert", explanation: "150,000,000=1.5×10⁸. ✓" }],
    hint: "Count zeros after the first digit.",
    keyConcepts: ["real-world scientific notation", "astronomy"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "earth-sun-distance"],
    source: "concept",
  },

  {
    id: "bo-mth-7-ch13-con-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Compare: 4.3 × 10⁶ and 9.8 × 10⁵. Which is greater?",
    answer: "4.3 × 10⁶ = 4,300,000. 9.8 × 10⁵ = 980,000. 4,300,000 > 980,000. So 4.3 × 10⁶ is greater.",
    steps: [
      { stepNumber: 1, title: "Compare powers of 10", explanation: "10⁶ > 10⁵, so 4.3×10⁶ > 9.8×10⁵." },
    ],
    hint: "First compare the exponents of 10.",
    keyConcepts: ["comparing scientific notation numbers"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [{ error: "Comparing only coefficients (9.8>4.3)", correction: "The power of 10 determines the order of magnitude; 10⁶ >> 10⁵." }],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "compare-scientific"],
    source: "concept",
  },

  // ── NCERT (t2) ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-nce-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write in standard form: (a) 5,00,000  (b) 3,72,00,000  [NCERT Ex 13.3]",
    answer: "(a) 5 × 10⁵  (b) 3.72 × 10⁷.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "5×10⁵." },
      { stepNumber: 2, title: "(b)", explanation: "3,72,00,000=3.72×10⁷.", result: "5×10⁵; 3.72×10⁷" },
    ],
    hint: "Count decimal places moved.",
    keyConcepts: ["converting large numbers to scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Express as ordinary number: (a) 5.2 × 10⁴  (b) 7.0 × 10⁶  [NCERT Ex 13.3]",
    answer: "(a) 52,000  (b) 7,000,000.",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "5.2×10⁴=52000; 7×10⁶=7000000." },
    ],
    hint: "Move decimal right by the exponent value.",
    keyConcepts: ["expanding scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The mass of Earth is approximately 5,970,000,000,000,000,000,000,000 kg. Write in scientific notation.  [NCERT Ex 13.3]",
    answer: "5.97 × 10²⁴ kg.",
    steps: [
      { stepNumber: 1, title: "Count digits", explanation: "5.97 × 10²⁴ kg.", result: "5.97×10²⁴ kg" },
    ],
    hint: "Count the number of zeros after 5.97.",
    keyConcepts: ["scientific notation for very large numbers"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "mass-of-earth"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Express the following using exponents: 56,800,000,000 = 568 × 10?  [NCERT Ex 13.3]",
    answer: "568 × 10⁸. But in scientific notation: 5.68 × 10¹⁰.",
    steps: [
      { stepNumber: 1, title: "56,800,000,000 = 568 × 10⁸", explanation: "Move 8 places → 568×10⁸ or 5.68×10¹⁰." },
    ],
    hint: "Divide by 568, count the remaining zeros.",
    keyConcepts: ["expressing as product with power of 10"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "NCERT-Ex13.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The diameter of a red blood cell is about 0.000007 m. Write in scientific notation.  [NCERT Ex 13.3]",
    answer: "7 × 10⁻⁶ m.",
    steps: [{ stepNumber: 1, title: "Convert", explanation: "0.000007=7×10⁻⁶.", result: "7×10⁻⁶ m" }],
    hint: "Move decimal right 6 places → negative exponent.",
    keyConcepts: ["small number scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "red-blood-cell"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The distance of the Sun from Earth = 1.5 × 10¹¹ m. Speed of light = 3 × 10⁸ m/s. How long does light take to reach Earth from the Sun?  [NCERT Ex 13.3]",
    answer: "Time = distance/speed = (1.5×10¹¹)/(3×10⁸)=0.5×10³=500 seconds ≈ 8.33 minutes.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "1.5/3×10^(11−8)=0.5×10³=500 s." },
      { stepNumber: 2, title: "Convert", explanation: "500/60≈8.33 min.", result: "500 seconds ≈ 8.33 minutes" },
    ],
    hint: "Time = Distance/Speed. Divide the coefficients and subtract exponents.",
    keyConcepts: ["scientific notation arithmetic", "physics application"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "light-travel-time"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Arrange in ascending order: 1.5×10⁴, 8.3×10³, 2.1×10⁴, 7.5×10².  [NCERT Ex 13.3]",
    answer: "7.5×10²=750; 8.3×10³=8300; 1.5×10⁴=15000; 2.1×10⁴=21000. Ascending: 7.5×10² < 8.3×10³ < 1.5×10⁴ < 2.1×10⁴.",
    steps: [
      { stepNumber: 1, title: "Convert or compare", explanation: "750<8300<15000<21000." },
    ],
    hint: "Compare powers first; if equal, compare coefficients.",
    keyConcepts: ["ordering scientific notation numbers"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "ascending-scientific"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-017",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A human body has approximately 37.2 × 10¹² cells. Express properly in scientific notation and find how many 10-cell groups there are.  [NCERT Ex 13.3]",
    answer: "37.2×10¹² = 3.72×10¹³ cells. Groups of 10: 3.72×10¹³÷10=3.72×10¹² groups.",
    steps: [
      { stepNumber: 1, title: "Standard form", explanation: "3.72×10¹³." },
      { stepNumber: 2, title: "Groups of 10", explanation: "3.72×10¹².", result: "3.72×10¹³; groups = 3.72×10¹²" },
    ],
    hint: "To divide by 10, subtract 1 from the exponent.",
    keyConcepts: ["scientific notation arithmetic", "biology context"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "human-cells"],
    source: "ncert",
  },

  {
    id: "bo-mth-7-ch13-nce-018",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "India's GDP is approximately ₹3.36 × 10¹⁴. Population is 1.4 × 10⁹. Find per-capita GDP in scientific notation.  [NCERT Ex 13.3]",
    answer: "Per capita = 3.36×10¹⁴ ÷ 1.4×10⁹ = (3.36/1.4) × 10^(14−9) = 2.4 × 10⁵ = ₹2,40,000.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "3.36/1.4=2.4; 10^(14−9)=10⁵." },
      { stepNumber: 2, title: "Per capita", explanation: "2.4×10⁵=₹2,40,000.", result: "₹2.4×10⁵" },
    ],
    hint: "Divide both coefficient and power of 10 separately.",
    keyConcepts: ["scientific notation division", "GDP application"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class7", "ch13", "GDP-per-capita"],
    source: "ncert",
  },

  // ── ICSE (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-ics-005",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Write the following numbers in scientific notation: (a) 6,02,000,000,000,000,000,000,000 (Avogadro's number approximately)  (b) 0.0000000000000000000000911 (electron mass in grams approximately).",
    answer: "(a) 6.02 × 10²³  (b) 9.11 × 10⁻²⁴ g.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "6.02×10²³." },
      { stepNumber: 2, title: "(b)", explanation: "9.11×10⁻²⁴.", result: "6.02×10²³; 9.11×10⁻²⁴" },
    ],
    hint: "Count decimal places moved in each direction.",
    keyConcepts: ["extreme scientific notation", "real-world constants"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch13", "avogadro-electron"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch13-ics-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The area of Antarctica is about 1.4 × 10⁷ km². There are 8 × 10⁹ people on Earth. If everyone moved to Antarctica, how many km² per person?",
    answer: "Area per person = 1.4×10⁷ ÷ 8×10⁹ = (1.4/8)×10^(7−9) = 0.175×10⁻² = 1.75×10⁻³ km².",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "1.4/8=0.175; 10^(7−9)=10⁻²." },
      { stepNumber: 2, title: "Standard form", explanation: "0.175×10⁻²=1.75×10⁻³ km².", result: "1.75×10⁻³ km²" },
    ],
    hint: "Divide the coefficients and subtract the exponents.",
    keyConcepts: ["scientific notation division", "geography context"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch13", "antarctica"],
    source: "icse",
  },

  {
    id: "bo-mth-7-ch13-ics-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A light year is 9.461 × 10¹² km. The Andromeda galaxy is 2.5 × 10⁶ light years away. Find the distance in km in scientific notation.",
    answer: "Distance = 2.5×10⁶ × 9.461×10¹² = (2.5×9.461)×10^(6+12) = 23.6525×10¹⁸ ≈ 2.365×10¹⁹ km.",
    steps: [
      { stepNumber: 1, title: "Multiply", explanation: "2.5×9.461=23.6525; 10^18." },
      { stepNumber: 2, title: "Standard form", explanation: "2.365×10¹⁹ km.", result: "≈2.365×10¹⁹ km" },
    ],
    hint: "Multiply coefficients and add exponents.",
    keyConcepts: ["scientific notation multiplication", "astronomy"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: ["icse", "class7", "ch13", "andromeda"],
    source: "icse",
  },

  // ── COMPETENCY (t2) ──────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-cmp-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "3.2 × 10⁵ in ordinary form is:",
    options: ["32000", "320000", "3200000", "0.000032"],
    answer: "320000",
    steps: [{ stepNumber: 1, title: "Expand", explanation: "Move decimal 5 places right: 320,000." }],
    hint: "Positive exponent: move right.",
    keyConcepts: ["expanding scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "MCQ-expand"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Which of the following is in correct scientific notation?",
    options: ["24 × 10⁵", "0.5 × 10⁸", "3.14 × 10⁷", "10 × 10⁶"],
    answer: "3.14 × 10⁷",
    steps: [{ stepNumber: 1, title: "Check 1≤m<10", explanation: "Only 3.14 satisfies 1≤3.14<10." }],
    hint: "Coefficient must be between 1 (inclusive) and 10 (exclusive).",
    keyConcepts: ["valid scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "valid-scientific"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A hard disk has capacity 1 TB = 10¹² bytes. A file is 8 × 10⁶ bytes. How many such files can the disk store?",
    answer: "Files = 10¹²/(8×10⁶)=10^(12−6)/8=10⁶/8=125,000 files.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "10¹²÷8×10⁶=10⁶/8=125000.", result: "125,000 files" },
    ],
    hint: "Files = capacity ÷ file size.",
    keyConcepts: ["scientific notation division", "computing context"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "hard-disk"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 10,
    question: "India's external debt is approximately ₹6.2 × 10¹³. Total government revenue is ₹2.5 × 10¹³ per year. (a) How many years of revenue equals the debt? (b) If 10% of revenue goes to debt repayment, how long to repay? (c) Express the debt per Indian citizen (population 1.4×10⁹).",
    answer: "(a) 6.2/2.5×10^(13−13)=2.48 years. (b) 10% revenue=2.5×10¹² per year. 6.2×10¹³÷2.5×10¹²=24.8 years. (c) Debt per citizen=6.2×10¹³÷1.4×10⁹=(6.2/1.4)×10⁴≈4.43×10⁴=₹44,300.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "6.2/2.5=2.48 years." },
      { stepNumber: 2, title: "(b)", explanation: "24.8 years at 10%." },
      { stepNumber: 3, title: "(c)", explanation: "≈₹4.43×10⁴ per person.", result: "2.48yr; 24.8yr; ₹44,300" },
    ],
    hint: "Compute each ratio using scientific notation arithmetic.",
    keyConcepts: ["scientific notation division", "economic context"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "debt-case-study"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-013",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The product of 4 × 10³ and 5 × 10⁴ in scientific notation is:",
    options: ["20 × 10⁷", "2 × 10⁸", "20 × 10¹²", "2 × 10¹²"],
    answer: "2 × 10⁸",
    steps: [{ stepNumber: 1, title: "Multiply", explanation: "4×5=20; 10^(3+4)=10⁷. Result=20×10⁷=2×10⁸." }],
    hint: "Multiply coefficients, add exponents, then adjust to standard form.",
    keyConcepts: ["multiplication in scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [{ error: "Leaving answer as 20×10⁷", correction: "Must convert to standard form: 2×10⁸." }],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "multiply-scientific"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-014",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The speed of sound is approximately 343 m/s. Express in scientific notation.",
    answer: "3.43 × 10² m/s.",
    steps: [{ stepNumber: 1, title: "Convert", explanation: "343=3.43×10².", result: "3.43×10²" }],
    hint: "Move decimal two places left.",
    keyConcepts: ["scientific notation", "physics"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "speed-sound"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-015",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "The human eye can detect light of intensity as low as 10⁻¹⁸ watts and as high as 10⁻³ watts without damage. By what factor is the maximum safe intensity greater than the minimum detectable?",
    answer: "Factor = 10⁻³ ÷ 10⁻¹⁸ = 10^(−3−(−18)) = 10¹⁵. The maximum safe intensity is 10¹⁵ times greater than the minimum detectable.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "10⁻³/10⁻¹⁸=10^(−3+18)=10¹⁵.", result: "10¹⁵" },
    ],
    hint: "Divide by subtracting exponents.",
    keyConcepts: ["scientific notation quotient", "biology context"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [{ error: "Subtracting in wrong order", correction: "−3−(−18)=−3+18=+15." }],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "eye-sensitivity"],
    source: "competency",
  },

  {
    id: "bo-mth-7-ch13-cmp-016",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A single grain of sand weighs about 6.7 × 10⁻⁵ grams. A beach has approximately 7.5 × 10¹⁸ grains of sand. What is the total mass of sand? Express in scientific notation.",
    answer: "Mass = 6.7×10⁻⁵ × 7.5×10¹⁸ = (6.7×7.5)×10^(−5+18)=50.25×10¹³=5.025×10¹⁴ grams.",
    steps: [
      { stepNumber: 1, title: "Multiply", explanation: "6.7×7.5=50.25; 10^13." },
      { stepNumber: 2, title: "Standard form", explanation: "5.025×10¹⁴ grams.", result: "≈5.025×10¹⁴ g" },
    ],
    hint: "Multiply coefficients and add exponents.",
    keyConcepts: ["scientific notation multiplication", "earth science"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class7", "ch13", "beach-sand"],
    source: "competency",
  },

  // ── HOTS (t2) ────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-hot-006",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "If A = 3.6 × 10⁸ and B = 1.2 × 10⁵, find: (a) A × B  (b) A + B  (c) A/B. Express all in scientific notation.",
    answer: "(a) 3.6×1.2×10^(8+5)=4.32×10¹³. (b) A+B≈3.6×10⁸ (B is negligible; precise: 3.600012×10⁸≈3.6×10⁸). (c) 3.6/1.2×10^(8−5)=3×10³.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "4.32×10¹³." },
      { stepNumber: 2, title: "(b)", explanation: "≈3.6×10⁸ (B is tiny relative to A)." },
      { stepNumber: 3, title: "(c)", explanation: "3×10³.", result: "4.32×10¹³; ≈3.6×10⁸; 3×10³" },
    ],
    hint: "For addition, convert to same power of 10.",
    keyConcepts: ["all four operations in scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "all-operations-scientific"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 9,
    question: "The number of atoms in 1 gram of hydrogen is approximately 6 × 10²³. The number of stars in the observable universe is about 10²⁴. Are there more stars in the universe or atoms in 1 gram of hydrogen? By what factor?",
    answer: "Stars: 10²⁴. Atoms in 1g H: 6×10²³. Ratio: 10²⁴/(6×10²³)=10/6≈1.67. There are about 1.67 times more stars in the observable universe than atoms in 1 gram of hydrogen! Stars > atoms by a factor of ~1.67.",
    steps: [
      { stepNumber: 1, title: "Compare", explanation: "10²⁴ vs 6×10²³." },
      { stepNumber: 2, title: "Ratio", explanation: "10²⁴/6×10²³=10/6≈1.67.", result: "Stars more by factor ~1.67" },
    ],
    hint: "Convert both to same power of 10 before comparing.",
    keyConcepts: ["comparison", "scientific notation ratio"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking 10²⁴ >> 6×10²³ without computing ratio", correction: "10²⁴=10×10²³, so ratio is only 10/6≈1.67." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "stars-vs-atoms"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Design a word problem involving scientific notation where the answer is exactly 10⁶. Show your working.",
    answer: "Problem: 'The speed of light is 3×10⁸ m/s. A certain particle moves at 3×10² m/s. How many times slower is the particle?' Solution: 3×10⁸ ÷ 3×10² = 1×10⁶. The particle is exactly 10⁶ times slower.",
    steps: [
      { stepNumber: 1, title: "Design", explanation: "Need A/B=10⁶. Choose A=3×10⁸, B=3×10²." },
      { stepNumber: 2, title: "Verify", explanation: "3×10⁸÷3×10²=10⁶. ✓" },
    ],
    hint: "Work backwards: what two numbers in scientific notation have a ratio of 10⁶?",
    keyConcepts: ["creating scientific notation problems", "reverse engineering"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "create-problem-1e6"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 9,
    question: "Sunita says: 'If I multiply a number by 10⁻³, the number gets very large.' Explain why Sunita is wrong, and give an example showing what actually happens.",
    answer: "Sunita is wrong. Multiplying by 10⁻³ = multiplying by 0.001, which makes the number 1000 times SMALLER. Example: 5×10⁶ × 10⁻³ = 5×10³ = 5000. The number decreased from 5,000,000 to 5,000. The negative exponent means a fraction (10⁻³=1/1000).",
    steps: [
      { stepNumber: 1, title: "10⁻³ is small", explanation: "10⁻³=1/1000=0.001." },
      { stepNumber: 2, title: "Example", explanation: "5×10⁶×10⁻³=5×10³=5000 < 5,000,000." },
    ],
    hint: "Negative exponent = fraction.",
    keyConcepts: ["negative exponent", "misconception correction"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [{ error: "Thinking negative exponent makes number large", correction: "10⁻ⁿ = 1/10ⁿ, a small fraction." }],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "negative-exponent-misconception"],
    source: "hots",
  },

  {
    id: "bo-mth-7-ch13-hot-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 12,
    question: "A computer processes 10⁹ instructions per second. The age of the universe is approximately 4.3 × 10¹⁷ seconds. How many instructions could the computer process in the age of the universe? Is this larger or smaller than the estimated number of atoms in the observable universe (10⁸⁰)?",
    answer: "Instructions = 10⁹ × 4.3×10¹⁷ = 4.3×10²⁶. Atoms in universe ≈ 10⁸⁰. Compare: 4.3×10²⁶ << 10⁸⁰. The number of computer instructions is vastly smaller — by a factor of about 10⁸⁰/4.3×10²⁶ ≈ 2.3×10⁵³.",
    steps: [
      { stepNumber: 1, title: "Instructions", explanation: "10⁹×4.3×10¹⁷=4.3×10²⁶." },
      { stepNumber: 2, title: "Compare with 10⁸⁰", explanation: "4.3×10²⁶ << 10⁸⁰. Smaller by ~10⁵³.", result: "4.3×10²⁶; much smaller than 10⁸⁰" },
    ],
    hint: "Multiply for instructions, then compare using quotient.",
    keyConcepts: ["scientific notation in context", "comparing astronomic numbers"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class7", "ch13", "universe-computer"],
    source: "hots",
  },

  // ── PREVIOUS YEAR (t2) ───────────────────────────────────────────────────────

  {
    id: "bo-mth-7-ch13-pyq-007",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Express 8,54,000 in standard form (scientific notation).  [CBSE 2019]",
    answer: "8.54 × 10⁵.",
    steps: [{ stepNumber: 1, title: "Convert", explanation: "8.54×10⁵.", result: "8.54×10⁵" }],
    hint: "Move decimal 5 places left.",
    keyConcepts: ["scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2019"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-008",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write 4.7 × 10⁻⁴ as an ordinary number.  [SA-I 2020]",
    answer: "0.00047.",
    steps: [{ stepNumber: 1, title: "Expand", explanation: "Move decimal 4 places left: 0.00047.", result: "0.00047" }],
    hint: "Negative exponent: move decimal left.",
    keyConcepts: ["expanding scientific notation"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "SA2020"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-009",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The thickness of a book is 2 cm and the thickness of a page is 0.0001 cm. Express the thickness of each page in scientific notation and find how many pages the book has.  [CBSE 2021]",
    answer: "Page thickness = 1×10⁻⁴ cm. Pages = 2 ÷ 10⁻⁴ = 2 × 10⁴ = 20,000 pages.",
    steps: [
      { stepNumber: 1, title: "Scientific notation", explanation: "0.0001=10⁻⁴ cm." },
      { stepNumber: 2, title: "Pages", explanation: "2/10⁻⁴=2×10⁴=20000.", result: "20000 pages" },
    ],
    hint: "Pages = total thickness ÷ page thickness.",
    keyConcepts: ["scientific notation application", "division"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2021"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-010",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Express 7.5×10¹⁰ ÷ 2.5×10⁷ in scientific notation and verify by expanding.  [CBSE 2022]",
    answer: "7.5/2.5×10^(10−7)=3×10³=3000. Verify: 75,000,000,000÷25,000,000=3000. ✓",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "3×10³=3000." },
      { stepNumber: 2, title: "Verify", explanation: "3000=3000. ✓", result: "3×10³" },
    ],
    hint: "Divide coefficients and subtract exponents.",
    keyConcepts: ["scientific notation division", "verification"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2022"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-011",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "There are approximately 2.5×10⁶ red blood cells per mm³ of blood. A human body has about 5 litres of blood. How many red blood cells are there in total? (1 litre = 10⁶ mm³)  [ICSE 2021]",
    answer: "Blood volume = 5×10⁶ mm³. RBC = 2.5×10⁶ × 5×10⁶ = 12.5×10¹² = 1.25×10¹³.",
    steps: [
      { stepNumber: 1, title: "Convert blood volume", explanation: "5L=5×10⁶ mm³." },
      { stepNumber: 2, title: "Total RBC", explanation: "2.5×10⁶×5×10⁶=12.5×10¹²=1.25×10¹³.", result: "1.25×10¹³" },
    ],
    hint: "Multiply RBC density by total volume.",
    keyConcepts: ["scientific notation multiplication", "biology"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [{ error: "Not converting litres to mm³", correction: "1 litre = 10⁶ mm³; 5 litres = 5×10⁶ mm³." }],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "ICSE2021", "blood-cells"],
    source: "previous-year",
  },

  {
    id: "bo-mth-7-ch13-pyq-012",
    schemaVersion: 2, classNum: 7, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Exponents and Powers",
    topicId: "t2", topicName: "Scientific Notation",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The wavelength of X-rays is approximately 3×10⁻¹⁰ m and visible light is about 5×10⁻⁷ m. How many times is visible light's wavelength greater than X-rays'?  [CBSE 2022]",
    answer: "Ratio = 5×10⁻⁷ ÷ 3×10⁻¹⁰ = (5/3)×10^(−7−(−10)) = (5/3)×10³ ≈ 1.67×10³ = 1667 times.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "(5/3)×10^(−7+10)=(5/3)×10³." },
      { stepNumber: 2, title: "Value", explanation: "≈1667 times.", result: "≈1.67×10³ times" },
    ],
    hint: "Divide the scientific notation values.",
    keyConcepts: ["scientific notation comparison", "physics"],
    conceptsCovered: ["mth:7:ch13:scientific-notation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class7", "ch13", "CBSE2022", "wavelength"],
    source: "previous-year",
  },

];
