// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 14: Symmetry
 *
 * 75 curated questions — difficulty: Easy 40% (30), Medium 40% (30), Hard 20% (15)
 * Board: Both (CBSE + ICSE) | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Line of Symmetry            — 25 q (10E / 10M / 5H)
 *   t2 Rotational Symmetry         — 25 q (10E / 10M / 5H)
 *   t3 Order of Rotational Symmetry and Applications — 25 q (10E / 10M / 5H)
 *
 * v1 2026-07-07 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";

export const CH14_SYMMETRY: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Line of Symmetry  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-7-ch14-001", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is a line of symmetry?", answer:"A line of symmetry is a line that divides a figure into two identical halves that are mirror images of each other. When the figure is folded along this line, both halves match exactly.", steps:[{stepNumber:1,title:"Definition",explanation:"A line of symmetry (also called axis of symmetry) divides a shape into two congruent mirror-image halves."}], hint:"Think of folding a shape so both halves match exactly.", keyConcepts:["line of symmetry","axis of symmetry","mirror image"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-002", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"TrueOrFalse", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"True or False: A square has exactly 2 lines of symmetry.", answer:"False. A square has 4 lines of symmetry — two along diagonals and two along midpoints of opposite sides.", steps:[{stepNumber:1,title:"Square symmetry",explanation:"Square has 4 lines: horizontal midline, vertical midline, and two diagonal lines."}], hint:"Count vertical, horizontal, and diagonal lines of symmetry for a square.", keyConcepts:["square","lines of symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Saying 2",correction:"A square has 4 lines of symmetry, not 2."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-003", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"How many lines of symmetry does an equilateral triangle have?", answer:"3 — one from each vertex to the midpoint of the opposite side.", steps:[{stepNumber:1,title:"Equilateral triangle",explanation:"An equilateral triangle has 3 lines of symmetry, each passing through a vertex and the midpoint of the opposite side."}], hint:"Count the sides of the equilateral triangle.", keyConcepts:["equilateral triangle","lines of symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-004", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Does a scalene triangle have any line of symmetry?", answer:"No. A scalene triangle has no line of symmetry because all three sides are different.", steps:[{stepNumber:1,title:"Scalene triangle",explanation:"Since all sides are unequal, no fold will produce two matching halves."}], hint:"A scalene triangle has all sides of different lengths.", keyConcepts:["scalene triangle","no symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-005", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"How many lines of symmetry does a circle have?", answer:"Infinitely many. Every diameter of a circle is a line of symmetry.", steps:[{stepNumber:1,title:"Circle",explanation:"Any line through the centre of a circle divides it into two equal halves, so there are infinitely many lines of symmetry."}], hint:"Think about how many diameters a circle can have.", keyConcepts:["circle","infinite symmetry","diameter"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-006", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"How many lines of symmetry does a rectangle (non-square) have?", answer:"2 — one horizontal (joining midpoints of longer sides) and one vertical (joining midpoints of shorter sides). Diagonals are NOT lines of symmetry for a rectangle.", steps:[{stepNumber:1,title:"Rectangle",explanation:"A non-square rectangle has 2 lines of symmetry. Its diagonals are not lines of symmetry."}], hint:"Only the lines through midpoints of opposite sides work — not the diagonals.", keyConcepts:["rectangle","2 lines of symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Saying 4",correction:"Rectangle (non-square) has only 2 lines of symmetry, not 4."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-007", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"State the number of lines of symmetry for a regular pentagon.", answer:"5 lines of symmetry — one from each vertex to the midpoint of the opposite side.", steps:[{stepNumber:1,title:"Regular pentagon",explanation:"A regular polygon with n sides has n lines of symmetry. Pentagon: n = 5."}], hint:"For regular polygons: number of lines of symmetry = number of sides.", keyConcepts:["regular pentagon","5 lines"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-008", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"How many lines of symmetry does a regular hexagon have?", answer:"6 lines of symmetry — 3 joining opposite vertices and 3 joining midpoints of opposite sides.", steps:[{stepNumber:1,title:"Regular hexagon",explanation:"n = 6 → 6 lines of symmetry."}], hint:"Regular hexagon has 6 sides → 6 lines of symmetry.", keyConcepts:["regular hexagon","6 lines"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-009", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Which letter of the English alphabet has a horizontal line of symmetry?", answer:"Letters like B, C, D, E, H, I, K, O, X have a horizontal line of symmetry.", steps:[{stepNumber:1,title:"Horizontal symmetry",explanation:"Fold the letter along a horizontal line — the top and bottom must match. B, C, D, E, H, I, K, O, X qualify."}], hint:"Fold the letter left-right along a horizontal line and see if both halves match.", keyConcepts:["horizontal symmetry","alphabets"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-010", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Which letters of the English alphabet have a vertical line of symmetry?", answer:"A, H, I, M, O, T, U, V, W, X, Y have a vertical line of symmetry.", steps:[{stepNumber:1,title:"Vertical symmetry",explanation:"Fold along a vertical line — left and right must match. A, H, I, M, O, T, U, V, W, X, Y qualify."}], hint:"Fold the letter top-to-bottom along a vertical line.", keyConcepts:["vertical symmetry","alphabets"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-011", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"An isosceles triangle has a vertical line of symmetry. Explain why and describe where the line lies.", answer:"The line of symmetry goes from the apex (the unequal vertex) to the midpoint of the base. It is perpendicular to the base and bisects it, dividing the triangle into two congruent right-angled triangles.", steps:[{stepNumber:1,title:"Why symmetric",explanation:"The two equal sides are mirror images of each other across this perpendicular bisector of the base."},{stepNumber:2,title:"Location",explanation:"The axis passes through the apex perpendicularly bisecting the base."}], hint:"The equal sides of an isosceles triangle are symmetric about this line.", keyConcepts:["isosceles triangle","perpendicular bisector","apex"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-012", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A kite-shaped figure has one line of symmetry. Describe its position.", answer:"The line of symmetry of a kite runs along its main diagonal — the one that connects the two vertices where unequal sides meet. It is also the axis that bisects the other diagonal.", steps:[{stepNumber:1,title:"Kite symmetry",explanation:"A kite has one pair of equal adjacent sides on each side of the main diagonal. The main diagonal is the axis of symmetry."}], hint:"A kite has one line of symmetry along its longer diagonal.", keyConcepts:["kite","one line of symmetry","diagonal"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-013", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"understand", marks:2, estimatedTimeMinutes:4, question:"A parallelogram (non-rectangle) has no lines of symmetry. Explain why.", answer:"A parallelogram has opposite sides equal and parallel, but when you try to fold it along any line, the two halves do not match because the angles are not right angles and the diagonals are unequal. Therefore it has no line of symmetry.", steps:[{stepNumber:1,title:"Attempt vertical fold",explanation:"Folding along the vertical midline does not produce matching halves because slanted sides are not mirror images."},{stepNumber:2,title:"Attempt diagonal fold",explanation:"The diagonal divides it into congruent triangles but they are rotations, not reflections — not a line of symmetry."}], hint:"Check whether any fold produces two matching halves for a slanted parallelogram.", keyConcepts:["parallelogram","no symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Thinking diagonals are lines of symmetry",correction:"Diagonals of a non-rectangular parallelogram are not lines of symmetry."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-014", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"How many lines of symmetry does a rhombus have?", answer:"2 — along its two diagonals. The diagonals of a rhombus are perpendicular bisectors of each other and are the only lines of symmetry.", steps:[{stepNumber:1,title:"Rhombus symmetry",explanation:"Folding along either diagonal maps the rhombus onto itself. So there are exactly 2 lines of symmetry."}], hint:"The lines of symmetry of a rhombus are its diagonals.", keyConcepts:["rhombus","2 lines","diagonals"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Confusing with rectangle (which has different symmetry)",correction:"Rhombus: diagonals are the axes. Rectangle: midpoint lines are the axes."}], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-015", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"An arrow pointing right (→) — does it have a line of symmetry? If so, describe it.", answer:"Yes — one horizontal line of symmetry passing through the middle of the arrow from left to right. The top half is a mirror of the bottom half.", steps:[{stepNumber:1,title:"Identify symmetry",explanation:"The arrowhead and shaft are symmetric about the horizontal axis. Fold along the horizontal midline and both halves match."}], hint:"Try folding the arrow along a horizontal line through its middle.", keyConcepts:["arrow","horizontal symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-016", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"State the number of lines of symmetry for a regular octagon.", answer:"8 lines of symmetry — 4 joining opposite vertices and 4 joining midpoints of opposite sides.", steps:[{stepNumber:1,title:"Regular octagon",explanation:"Regular polygon with n sides → n lines of symmetry. n = 8."}], hint:"For regular polygons: lines of symmetry = number of sides.", keyConcepts:["regular octagon","8 lines"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-017", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"A figure has 3 lines of symmetry. Could it be a regular polygon? If yes, which one?", answer:"Yes — an equilateral triangle. A regular polygon with n sides has n lines of symmetry. So 3 lines → equilateral triangle (n = 3).", steps:[{stepNumber:1,title:"Rule",explanation:"Regular n-gon has n lines of symmetry."},{stepNumber:2,title:"n = 3",explanation:"3 lines → equilateral triangle.",result:"Equilateral triangle"}], hint:"Lines of symmetry = number of sides for a regular polygon.", keyConcepts:["equilateral triangle","3 lines","regular polygon"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-018", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:3, estimatedTimeMinutes:5, question:"The letter 'H' has two lines of symmetry. Identify them both.", answer:"(1) Vertical line of symmetry down the centre of the letter. (2) Horizontal line through the middle crossbar. Both halves match on each side of these lines.", steps:[{stepNumber:1,title:"Vertical",explanation:"Left half mirrors right half → vertical axis of symmetry."},{stepNumber:2,title:"Horizontal",explanation:"Top half mirrors bottom half through the crossbar → horizontal axis.",result:"Two lines: vertical and horizontal through centre"}], hint:"Check both vertical and horizontal fold for the letter H.", keyConcepts:["letter H","two lines of symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-019", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"A student says a semicircle has 2 lines of symmetry. Is the student correct?", answer:"No. A semicircle has only 1 line of symmetry — the vertical line through the midpoint of the diameter. The diameter itself is NOT a line of symmetry because the curved top and the flat bottom are not reflections of each other across the diameter.", steps:[{stepNumber:1,title:"The one true axis",explanation:"The perpendicular bisector of the diameter is the only line that creates two matching halves."},{stepNumber:2,title:"Diameter is not an axis",explanation:"Folding along the diameter gives a full circle on top and nothing below — they don't match.",result:"1 line of symmetry, not 2"}], hint:"Try folding a semicircle along the flat edge (diameter) — do both halves match?", keyConcepts:["semicircle","1 line of symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Claiming the diameter is a line of symmetry",correction:"The diameter is not a line of symmetry for a semicircle."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-020", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"understand", marks:2, estimatedTimeMinutes:3, question:"What is the relationship between the line of symmetry and reflection?", answer:"The line of symmetry acts as a mirror: every point of the figure on one side has a corresponding point at the same distance on the other side. This is exactly what reflection does — the line of symmetry is the mirror line.", steps:[{stepNumber:1,title:"Reflection",explanation:"Reflecting a figure across its line of symmetry maps it exactly onto itself."}], hint:"Symmetry and reflection are the same concept in geometry.", keyConcepts:["reflection","mirror line","line of symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-021", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Can a figure have exactly 5 lines of symmetry? Give an example.", answer:"Yes. A regular pentagon has exactly 5 lines of symmetry — one from each vertex to the midpoint of the opposite side. In general, any regular n-gon has exactly n lines of symmetry.", steps:[{stepNumber:1,title:"Rule for regular polygons",explanation:"Regular n-gon → n lines of symmetry."},{stepNumber:2,title:"Example",explanation:"Regular pentagon (n=5) → 5 lines of symmetry.",result:"Yes — regular pentagon"}], hint:"Think of regular polygons and how many lines of symmetry they have.", keyConcepts:["regular pentagon","5 lines of symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-022", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"A rectangle has 2 lines of symmetry but a square has 4. What extra lines does the square have and why?", answer:"The extra two lines for the square are the diagonals. In a rectangle, the diagonals are not lines of symmetry because the two halves produced are not mirror images. In a square, all sides are equal, so folding along either diagonal produces two congruent isosceles right triangles that are mirror images.", steps:[{stepNumber:1,title:"Rectangle diagonals",explanation:"Folding a rectangle along a diagonal gives two right triangles with unequal legs — not mirror images."},{stepNumber:2,title:"Square diagonals",explanation:"All sides equal → both triangles are congruent isosceles right triangles and are reflections.",result:"Square has 2 extra diagonal lines of symmetry"}], hint:"Ask: when you fold along the diagonal, do both halves match for a rectangle vs a square?", keyConcepts:["square vs rectangle","diagonal symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-023", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"create", marks:4, estimatedTimeMinutes:7, question:"Draw a quadrilateral that has exactly one line of symmetry. Name it and describe the line.", answer:"A kite has exactly one line of symmetry — the main diagonal (connecting the two vertices where the unequal pairs of sides meet). A kite has two pairs of equal adjacent sides, and the main diagonal is the only fold that produces matching halves.", steps:[{stepNumber:1,title:"Kite definition",explanation:"Kite: two pairs of equal adjacent sides."},{stepNumber:2,title:"Symmetry",explanation:"Main diagonal is the only line of symmetry.",result:"Kite — one line of symmetry along main diagonal"}], hint:"Think of shapes with only one fold that works.", keyConcepts:["kite","one line","quadrilateral"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-024", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"Complete the pattern: for a regular polygon with n sides, the number of lines of symmetry is ___. Verify for n = 3, 4, 5, 6.", answer:"Number of lines of symmetry = n. Verify: n=3 (equilateral triangle): 3 lines ✓. n=4 (square): 4 lines ✓. n=5 (pentagon): 5 lines ✓. n=6 (hexagon): 6 lines ✓.", steps:[{stepNumber:1,title:"Pattern",explanation:"Regular n-gon → n lines of symmetry."},{stepNumber:2,title:"Verification",explanation:"n=3: 3 lines; n=4: 4 lines; n=5: 5 lines; n=6: 6 lines. All match.",result:"Lines of symmetry = n"}], hint:"How many sides does the polygon have?", keyConcepts:["regular polygon","n lines","pattern"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-025", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t1", topicName:"Line of Symmetry", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"A figure has line symmetry but is not a regular polygon. Give two such examples.", answer:"(1) Isosceles triangle — has 1 line of symmetry but is not a regular polygon (it has an unequal side). (2) Rectangle (non-square) — has 2 lines of symmetry but is not a regular polygon.", steps:[{stepNumber:1,title:"Example 1",explanation:"Isosceles triangle: 1 line of symmetry. Not regular (two sides equal, one different)."},{stepNumber:2,title:"Example 2",explanation:"Rectangle: 2 lines of symmetry. Not regular (angles = 90° but sides unequal).",result:"Isosceles triangle and rectangle"}], hint:"Think of shapes with mirror symmetry that have unequal sides or angles.", keyConcepts:["non-regular with symmetry","isosceles","rectangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Rotational Symmetry  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-7-ch14-026", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is rotational symmetry?", answer:"A figure has rotational symmetry if it looks the same after being rotated by some angle less than 360° about a central point (called the centre of rotation).", steps:[{stepNumber:1,title:"Definition",explanation:"Rotational symmetry means the figure maps onto itself under a rotation by less than a full turn (360°)."}], hint:"Rotate the figure — if it looks identical before completing a full turn, it has rotational symmetry.", keyConcepts:["rotational symmetry","centre of rotation","rotation"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-027", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is the centre of rotation?", answer:"The centre of rotation is the fixed point about which the figure is rotated. The figure appears identical at certain angles of rotation from this point.", steps:[{stepNumber:1,title:"Centre of rotation",explanation:"It is the pivot point — the figure rotates around this fixed central point."}], hint:"Think of a wheel's hub — the hub is the centre of rotation.", keyConcepts:["centre of rotation","pivot point"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-028", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"TrueOrFalse", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"True or False: Every figure has rotational symmetry of order 1 (at 360°).", answer:"True. Any figure rotated by 360° returns to its original position, so every figure has at least order-1 rotational symmetry. However, we typically say a figure has rotational symmetry only if the order is 2 or more.", steps:[{stepNumber:1,title:"360° rotation",explanation:"A full turn always restores any figure. So technically every figure has order 1. Meaningful rotational symmetry means order ≥ 2."}], hint:"360° = full rotation = always returns to original.", keyConcepts:["order 1","360 degrees","trivial rotation"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-029", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Does a square have rotational symmetry? At what angles does it look the same?", answer:"Yes. A square looks the same after rotations of 90°, 180°, 270°, and 360°. Its order of rotational symmetry is 4.", steps:[{stepNumber:1,title:"Square rotation",explanation:"Rotate 90° → same square. 180° → same. 270° → same. 360° → original. Order = 4."}], hint:"How many times in a full 360° rotation does the square look identical?", keyConcepts:["square","rotational symmetry","90°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-030", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"A regular hexagon is rotated about its centre. At what angle does it first look the same?", answer:"60° (= 360° ÷ 6). A regular hexagon has rotational symmetry of order 6, occurring every 60°.", steps:[{stepNumber:1,title:"Angle of rotation",explanation:"Angle = 360° ÷ order = 360° ÷ 6 = 60°."}], hint:"Divide 360° by the number of sides.", keyConcepts:["hexagon","60° rotation","order 6"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-031", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"Does a circle have rotational symmetry? Explain briefly.", answer:"Yes. A circle has rotational symmetry for any angle of rotation about its centre. It looks the same after any rotation, so it has infinite order of rotational symmetry.", steps:[{stepNumber:1,title:"Circle",explanation:"Every rotation about the centre maps the circle onto itself. Infinite order."}], hint:"Think: does a circle ever look different no matter how much you rotate it?", keyConcepts:["circle","infinite rotational symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-032", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"Does a scalene triangle have rotational symmetry (of order ≥ 2)?", answer:"No. A scalene triangle has no rotational symmetry (order < 2). It only returns to its original position after a full 360° rotation.", steps:[{stepNumber:1,title:"Scalene triangle",explanation:"All sides and angles are different, so no partial rotation maps it onto itself."}], hint:"Try rotating a scalene triangle by 120° or any angle less than 360° — does it look the same?", keyConcepts:["scalene triangle","no rotational symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-033", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"An equilateral triangle is rotated about its centre. At what angle does it first look the same? What is its order of rotational symmetry?", answer:"120° (= 360° ÷ 3). Order = 3. The equilateral triangle looks the same at 120°, 240°, and 360°.", steps:[{stepNumber:1,title:"Angle",explanation:"360° ÷ 3 = 120°."},{stepNumber:2,title:"Order",explanation:"Order = 3 (at 120°, 240°, 360°).",result:"120°; order 3"}], hint:"Divide 360° by the number of vertices.", keyConcepts:["equilateral triangle","120°","order 3"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-034", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What is the angle of rotation for a figure with rotational symmetry of order 4?", answer:"360° ÷ 4 = 90°. The figure looks the same every 90°.", steps:[{stepNumber:1,title:"Formula",explanation:"Angle of rotation = 360° ÷ order = 360° ÷ 4 = 90°."}], hint:"Angle = 360° ÷ order.", keyConcepts:["angle of rotation","order 4","formula"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-035", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Does a rectangle (non-square) have rotational symmetry? If yes, state the order.", answer:"Yes — order 2. A rectangle looks the same after rotation by 180° (and 360°). It does NOT look the same after 90°.", steps:[{stepNumber:1,title:"180° rotation",explanation:"Rotating a rectangle 180° about its centre maps it onto itself (length stays length, width stays width)."},{stepNumber:2,title:"Order",explanation:"Order = 2 (at 180° and 360°)."}], hint:"Try rotating the rectangle 180° — does it look the same?", keyConcepts:["rectangle","order 2","180°"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Saying order 4 like a square",correction:"Rectangle has order 2; square has order 4."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-036", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A figure has rotational symmetry of order 5. At what angles does it look the same during one full rotation?", answer:"At 72°, 144°, 216°, 288°, and 360°. (Angle = 360° ÷ 5 = 72°.)", steps:[{stepNumber:1,title:"Angle",explanation:"72°."},{stepNumber:2,title:"Positions",explanation:"72°, 144°, 216°, 288°, 360°.",result:"5 matching positions"}], hint:"Multiply 72° by 1, 2, 3, 4, 5.", keyConcepts:["order 5","72°","rotation positions"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-037", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"State the order of rotational symmetry for the letter 'S'.", answer:"Order 2. The letter S looks the same after 180° rotation about its centre. (It has 180° rotational symmetry.)", steps:[{stepNumber:1,title:"Rotate S by 180°",explanation:"The letter S maps onto itself when rotated 180°.",result:"Order 2"}], hint:"Rotate the letter S upside down — does it look the same?", keyConcepts:["letter S","order 2","180°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-038", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A regular polygon has rotational symmetry of order 8. How many sides does it have?", answer:"8 sides — it is a regular octagon. (For regular polygons, order of rotational symmetry = number of sides.)", steps:[{stepNumber:1,title:"Rule",explanation:"Order of rotational symmetry = n sides for a regular n-gon."},{stepNumber:2,title:"n = 8",explanation:"8-sided polygon = regular octagon.",result:"Regular octagon"}], hint:"For regular polygons: order = number of sides.", keyConcepts:["regular octagon","order 8","regular polygon rule"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-039", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"A fan with 3 identical blades is spinning. What is its order of rotational symmetry and the angle of rotation?", answer:"Order 3; angle = 120°. The fan looks the same every time a blade moves to where the next blade was.", steps:[{stepNumber:1,title:"Order",explanation:"3 identical blades → order 3."},{stepNumber:2,title:"Angle",explanation:"360° ÷ 3 = 120°.",result:"Order 3; angle 120°"}], hint:"How many positions does the fan look identical in one full rotation?", keyConcepts:["real-world rotational symmetry","fan","order 3"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-040", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"The recycling symbol (three arrows forming a triangle) has rotational symmetry. What is its order?", answer:"Order 3. The three equal arrows are 120° apart, so the symbol looks the same after each 120° rotation.", steps:[{stepNumber:1,title:"Identify",explanation:"Three equal sections → order 3, angle 120°."}], hint:"Count how many equal sections the recycling symbol has.", keyConcepts:["real-world","order 3","recycling symbol"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-041", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"Can a figure have line symmetry but no rotational symmetry (of order ≥ 2)? Give an example.", answer:"Yes. An isosceles triangle has 1 line of symmetry but no rotational symmetry of order ≥ 2 (rotating 120° or 240° does not map it onto itself since two sides are equal and one is different). Another example: a kite.", steps:[{stepNumber:1,title:"Isosceles triangle",explanation:"Line symmetry: yes (1 axis). Rotational symmetry: only order 1 (full turn) → no rotational symmetry of order ≥ 2.",result:"Yes — isosceles triangle"}], hint:"Look for shapes with at least one line of symmetry but no rotational symmetry.", keyConcepts:["line vs rotational symmetry","isosceles triangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-042", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Can a figure have rotational symmetry (order ≥ 2) but no line symmetry? Give an example.", answer:"Yes. The letter 'S' has order-2 rotational symmetry (180°) but no line of symmetry. Similarly, a parallelogram (non-rhombus) has order-2 rotational symmetry but no line symmetry.", steps:[{stepNumber:1,title:"Letter S",explanation:"Rotational symmetry: order 2. Line of symmetry: no fold produces matching halves.",result:"Yes — letter S and parallelogram"}], hint:"Look for shapes that spin to look the same but cannot be folded to match.", keyConcepts:["rotational without line symmetry","letter S","parallelogram"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-043", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"A wind turbine has 4 identical blades equally spaced. Find: (a) angle between each blade, (b) order of rotational symmetry, (c) angles during one rotation where it looks the same.", answer:"(a) 360°/4 = 90° between blades. (b) Order 4. (c) Looks the same at 90°, 180°, 270°, 360°.", steps:[{stepNumber:1,title:"Angle between blades",explanation:"360° ÷ 4 = 90°."},{stepNumber:2,title:"Order",explanation:"4 blades → order 4."},{stepNumber:3,title:"Matching positions",explanation:"90°, 180°, 270°, 360°.",result:"Order 4; matching at 90°, 180°, 270°, 360°"}], hint:"4 equal blades → divide 360° by 4.", keyConcepts:["wind turbine","order 4","90°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-044", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"create", marks:4, estimatedTimeMinutes:7, question:"Design a figure that has exactly order-2 rotational symmetry and no line symmetry. Describe it.", answer:"A figure shaped like the letter 'Z' or 'S', or a parallelogram with unequal adjacent sides. These have 180° rotational symmetry (order 2) but cannot be folded to match — no line of symmetry.", steps:[{stepNumber:1,title:"Parallelogram",explanation:"Rotating 180° about centre maps the parallelogram onto itself (order 2)."},{stepNumber:2,title:"No line symmetry",explanation:"No fold produces matching halves for a non-rectangular parallelogram.",result:"Parallelogram or letter Z/S"}], hint:"Think of shapes that look the same when turned 180° but cannot be folded symmetrically.", keyConcepts:["order 2","no line symmetry","design"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-045", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t2", topicName:"Rotational Symmetry", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Compare the rotational symmetry of an equilateral triangle and a regular hexagon. Which has a higher order and smaller angle of rotation?", answer:"Equilateral triangle: order 3, angle 120°. Regular hexagon: order 6, angle 60°. The regular hexagon has higher order (6 > 3) and smaller angle of rotation (60° < 120°).", steps:[{stepNumber:1,title:"Triangle",explanation:"Order 3; 360°÷3=120°."},{stepNumber:2,title:"Hexagon",explanation:"Order 6; 360°÷6=60°."},{stepNumber:3,title:"Comparison",explanation:"Hexagon: higher order, smaller angle.",result:"Hexagon has higher order (6) and smaller angle (60°)"}], hint:"Use the formula: angle = 360° ÷ order.", keyConcepts:["comparison","order 3 vs 6","angle of rotation"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t3 — Order of Rotational Symmetry and Applications  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-7-ch14-046", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is the order of rotational symmetry?", answer:"The order of rotational symmetry is the number of times a figure looks exactly the same during one complete rotation of 360° about its centre (including the final 360° position).", steps:[{stepNumber:1,title:"Definition",explanation:"Count how many times the figure coincides with its original position in one full 360° turn. This count is the order."}], hint:"Count positions where the figure looks identical in one full spin.", keyConcepts:["order of rotational symmetry","definition","count"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-047", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"State the formula connecting the angle of rotation and the order of rotational symmetry.", answer:"Angle of rotation = 360° ÷ order of rotational symmetry.", steps:[{stepNumber:1,title:"Formula",explanation:"If order = n, then angle = 360°/n."}], hint:"Divide a full turn by the order.", keyConcepts:["angle formula","360/n","order"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-048", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"What is the order of rotational symmetry of a regular pentagon? What is its angle of rotation?", answer:"Order 5; angle = 360° ÷ 5 = 72°.", steps:[{stepNumber:1,title:"Pentagon",explanation:"5 sides → order 5 → angle 72°."}], hint:"Regular pentagon: n = 5.", keyConcepts:["regular pentagon","order 5","72°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-049", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"Find the order of rotational symmetry of a figure that looks the same at 45° intervals.", answer:"Order = 360° ÷ 45° = 8.", steps:[{stepNumber:1,title:"Order formula",explanation:"Order = 360° ÷ angle = 360° ÷ 45° = 8."}], hint:"Order = 360° ÷ angle of rotation.", keyConcepts:["order formula","45°","order 8"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-050", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"What is the order of rotational symmetry of a regular hexagon? At what angles does it look the same?", answer:"Order 6. It looks the same at 60°, 120°, 180°, 240°, 300°, 360°.", steps:[{stepNumber:1,title:"Hexagon",explanation:"n=6 → order 6 → angle=60°. Positions: 60°,120°,180°,240°,300°,360°."}], hint:"Regular hexagon has 6 sides.", keyConcepts:["hexagon","order 6","60°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-051", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"A figure has rotational symmetry of order 1. What does this mean?", answer:"It means the figure only returns to its original position after a full 360° rotation. In other words, no partial rotation produces the same figure — it effectively has no meaningful rotational symmetry.", steps:[{stepNumber:1,title:"Order 1",explanation:"Only at 360° does the figure look the same. Order-1 rotational symmetry is trivial and generally means the shape is asymmetric in terms of rotation."}], hint:"Order 1 means only a full rotation works.", keyConcepts:["order 1","no useful rotational symmetry","trivial"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-052", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"State the order of rotational symmetry of a regular polygon with 12 sides (regular 12-gon). What is its angle of rotation?", answer:"Order 12; angle = 360° ÷ 12 = 30°.", steps:[{stepNumber:1,title:"Apply formula",explanation:"Regular 12-gon: order = 12, angle = 30°."}], hint:"n = 12 sides → order = 12.", keyConcepts:["regular 12-gon","order 12","30°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-053", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"A wheel with 8 equally spaced spokes is rotated. What is the smallest angle of rotation that brings it back to looking the same?", answer:"360° ÷ 8 = 45°.", steps:[{stepNumber:1,title:"Spokes",explanation:"8 spokes equally spaced → angle = 360°/8 = 45°."}], hint:"Divide 360° by the number of spokes.", keyConcepts:["wheel","8 spokes","45°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-054", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Does the letter 'Z' have rotational symmetry? What order?", answer:"Yes — order 2. The letter Z looks the same after 180° rotation. It does NOT have line symmetry.", steps:[{stepNumber:1,title:"Letter Z",explanation:"Rotate Z by 180° — it looks the same. Order 2."}], hint:"Rotate the letter Z upside down — does it look like a Z?", keyConcepts:["letter Z","order 2","180°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-055", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A clock's minute hand makes one full rotation per hour. After 15 minutes (90°), 30 minutes (180°), 45 minutes (270°), the clock face with numbers looks the same only at 360°. What does this tell you about the order of rotational symmetry of the numbered clock face?", answer:"The numbered clock face has order 1 (only looks the same at 360°, i.e., after a full turn). The 12 numbers are not evenly arranged by appearance, so partial rotations don't reproduce the same layout.", steps:[{stepNumber:1,title:"Analysis",explanation:"At 90°, 12 is at 3 o'clock position — different. Only 360° restores the original → order 1.",result:"Order 1"}], hint:"Rotate the clock face 90° — does the number layout look the same?", keyConcepts:["clock face","order 1","real-world"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-056", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Complete the table: Shape | Lines of Symmetry | Order of Rotational Symmetry for: (a) equilateral triangle, (b) square, (c) regular hexagon, (d) circle.", answer:"(a) 3 | 3; (b) 4 | 4; (c) 6 | 6; (d) infinite | infinite. For regular polygons, both values equal the number of sides.", steps:[{stepNumber:1,title:"Pattern",explanation:"For regular n-gon: lines of symmetry = n; order of rotation = n. For circle: both are infinite."}], hint:"Lines of symmetry = order of rotational symmetry for all regular polygons.", keyConcepts:["regular polygon","lines = order","table"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-057", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Explain why a regular polygon always has its order of rotational symmetry equal to its number of lines of symmetry.", answer:"For a regular n-gon: (1) It has n lines of symmetry because each line passes through a vertex (or midpoint) and the opposite side/vertex, creating n such axes. (2) It has order-n rotational symmetry because rotating by 360°/n maps it exactly onto itself — each rotation takes one vertex to the position of the next. Since both count the same 'n' worth of regularity, they are equal.", steps:[{stepNumber:1,title:"Lines of symmetry",explanation:"Regular n-gon: n lines."},{stepNumber:2,title:"Rotational order",explanation:"Regular n-gon: order n. Both equal n.",result:"Equal because both reflect the n-fold regularity of the polygon"}], hint:"Both symmetry types reflect the same underlying regularity.", keyConcepts:["regular polygon","n-fold symmetry","explanation"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-058", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A snowflake has 6-fold symmetry. (a) How many lines of symmetry does it have? (b) What is its order of rotational symmetry? (c) What is the angle of rotation?", answer:"(a) 6 lines. (b) Order 6. (c) 60°.", steps:[{stepNumber:1,title:"6-fold",explanation:"6 lines of symmetry, order 6, angle = 360°/6 = 60°.",result:"6 lines; order 6; 60°"}], hint:"6-fold symmetry means n = 6.", keyConcepts:["snowflake","6-fold","real-world"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-059", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"The letter 'N' — does it have line symmetry? Rotational symmetry? What order?", answer:"No line symmetry. Yes, rotational symmetry of order 2 (looks same at 180°). Like the letter Z and S, N is rotationally symmetric but not line-symmetric.", steps:[{stepNumber:1,title:"Line symmetry",explanation:"No fold produces matching halves."},{stepNumber:2,title:"Rotational",explanation:"Rotate 180° — looks the same. Order 2.",result:"No line symmetry; rotational order 2"}], hint:"Try rotating and folding the letter N separately.", keyConcepts:["letter N","order 2","no line symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-060", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A figure has both line symmetry (4 lines) and rotational symmetry. What is the order of rotational symmetry and what figure could it be?", answer:"Order 4. The figure could be a square. A square has 4 lines of symmetry and order-4 rotational symmetry (looks the same every 90°).", steps:[{stepNumber:1,title:"Matching order",explanation:"4 lines of symmetry → order 4 → square.",result:"Square; order 4"}], hint:"For regular polygons, order = number of lines of symmetry.", keyConcepts:["square","4 lines","order 4"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-061", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"A figure has rotational symmetry of order 6. Is it necessarily a regular hexagon? Explain.", answer:"No, not necessarily. Any figure with 6-fold rotational symmetry (looks the same every 60°) has order 6, but it need not be a hexagon. For example, a snowflake, a 6-petal flower, or any figure designed with 6-fold rotational symmetry qualifies, even if it does not have straight sides like a regular hexagon.", steps:[{stepNumber:1,title:"Order 6 condition",explanation:"Looks same at 60°, 120°, 180°, 240°, 300°, 360° — this is the only requirement."},{stepNumber:2,title:"Counter-example",explanation:"A 6-petal flower has order 6 but is not a regular hexagon.",result:"Not necessarily a regular hexagon"}], hint:"Order 6 means 60° rotation symmetry — many different shapes could have this.", keyConcepts:["order 6","not necessarily hexagon","counter-example"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-062", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"Find all capital letters that have both line symmetry AND rotational symmetry of order 2.", answer:"H, I, O, X. These letters have both at least one line of symmetry AND look the same when rotated 180°.", steps:[{stepNumber:1,title:"Filter for 180° rotation",explanation:"Rotate each symmetric letter 180° — only H, I, O, X return to the same look."},{stepNumber:2,title:"Verify line symmetry",explanation:"H, I, O, X all have at least one line of symmetry.",result:"H, I, O, X"}], hint:"First find letters with line symmetry, then check if 180° rotation also works.", keyConcepts:["letters","both symmetries","H I O X"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-063", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Prove that for any regular n-gon, the number of lines of symmetry equals the order of rotational symmetry.", answer:"For a regular n-gon: (1) Lines of symmetry: Each line passes through a vertex and the midpoint of the opposite side (for odd n) or through pairs of opposite vertices/sides (for even n), giving exactly n lines. (2) Rotational symmetry: The minimum rotation that maps the polygon onto itself is 360°/n; doing this n times returns to the start, so the order is n. In both cases, the count is n — they are equal by the underlying n-fold symmetry of the regular polygon.", steps:[{stepNumber:1,title:"Lines",explanation:"n lines in a regular n-gon."},{stepNumber:2,title:"Rotational order",explanation:"Order n in a regular n-gon."},{stepNumber:3,title:"Equal",explanation:"Both equal n → proved.",result:"Lines of symmetry = Order = n"}], hint:"Both symmetries arise from the same underlying n-fold regularity.", keyConcepts:["proof","regular n-gon","n-fold symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-064", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"create", marks:4, estimatedTimeMinutes:7, question:"Design two different figures: one with order-3 rotational symmetry and no line symmetry, and one with both order-3 rotational symmetry and 3 lines of symmetry. Describe each.", answer:"(1) Order-3 rotational symmetry, no line symmetry: A triskelion (three bent arms rotated 120° apart). Rotating by 120° gives the same figure, but no fold produces matching halves. (2) Order-3 rotation AND 3 lines: An equilateral triangle or a 3-petalled flower with symmetric petals. These have both properties.", steps:[{stepNumber:1,title:"Order 3 without line symmetry",explanation:"Triskelion — bent arms create rotational symmetry but not line symmetry."},{stepNumber:2,title:"Order 3 with 3 lines",explanation:"Equilateral triangle — classic example.",result:"Triskelion (no lines); equilateral triangle (3 lines)"}], hint:"Think of pinwheel shapes for rotation without lines.", keyConcepts:["design","triskelion","equilateral triangle","contrast"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-065", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:3, estimatedTimeMinutes:5, question:"Fill in the table for these figures: (a) rhombus, (b) rectangle (non-square), (c) parallelogram (non-rectangle). State: lines of symmetry, order of rotational symmetry.", answer:"(a) Rhombus: 2 lines, order 2. (b) Rectangle: 2 lines, order 2. (c) Parallelogram: 0 lines, order 2.", steps:[{stepNumber:1,title:"Rhombus",explanation:"Diagonals are 2 lines of symmetry. 180° rotation → same. Order 2."},{stepNumber:2,title:"Rectangle",explanation:"2 midpoint lines. 180° rotation → same. Order 2."},{stepNumber:3,title:"Parallelogram",explanation:"No line symmetry (no fold works). But 180° rotation works → order 2.",result:"Rhombus: 2/2; Rectangle: 2/2; Parallelogram: 0/2"}], hint:"Check folding for lines and 180° rotation for order.", keyConcepts:["comparison table","rhombus rectangle parallelogram"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Thinking parallelogram has line symmetry",correction:"Parallelogram has NO line symmetry, only rotational symmetry of order 2."}], tags:[], source:"previous-year" },

  { id:"bo-mth-7-ch14-066", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A figure has 4 lines of symmetry. Must it have rotational symmetry of order 4? Justify.", answer:"Not necessarily if the figure is not a regular polygon. However, for the shapes studied in Class 7, having 4 lines of symmetry strongly implies order-4 rotational symmetry — as seen in the square. In general, if a figure has n ≥ 2 lines of symmetry, it will always have rotational symmetry of order n, because each pair of reflection lines generates a rotation.", steps:[{stepNumber:1,title:"General result",explanation:"Two reflections compose to give a rotation. n reflection lines → order-n rotational symmetry."},{stepNumber:2,title:"Class 7 context",explanation:"Square: 4 lines → order 4. This is the pattern studied here.",result:"Yes — 4 lines of symmetry implies order-4 rotational symmetry"}], hint:"Think about what two reflections combined produce.", keyConcepts:["lines → order","composition of reflections","general principle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-067", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A company logo is a five-pointed star (regular). (a) How many lines of symmetry does it have? (b) What is its order of rotational symmetry? (c) At what angles does it look the same?", answer:"(a) 5 lines of symmetry. (b) Order 5. (c) 72°, 144°, 216°, 288°, 360°.", steps:[{stepNumber:1,title:"Five-pointed star (pentagram)",explanation:"It has 5-fold symmetry: 5 lines of symmetry, order 5, angle = 72°."},{stepNumber:2,title:"Angles",explanation:"72°, 144°, 216°, 288°, 360°.",result:"5 lines; order 5; 72° interval"}], hint:"A regular five-pointed star has 5-fold symmetry.", keyConcepts:["five-pointed star","5-fold","72°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-068", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Identify the type of symmetry (line, rotational, or both) and give the details for: (a) letter T, (b) letter S, (c) letter X.", answer:"(a) T: 1 line of symmetry (vertical), no rotational symmetry of order ≥ 2. (b) S: no line symmetry, rotational symmetry order 2 (180°). (c) X: 4 lines of symmetry (vertical, horizontal, two diagonals), rotational symmetry order 4 (90°).", steps:[{stepNumber:1,title:"Letter T",explanation:"1 vertical line of symmetry. Rotating 180° does not reproduce T."},{stepNumber:2,title:"Letter S",explanation:"No fold works. 180° rotation maps S to S."},{stepNumber:3,title:"Letter X",explanation:"4 lines (vertical, horizontal, two diagonals). Looks same at 90°, 180°, 270°.",result:"T: line only; S: rotational only; X: both"}], hint:"Check each letter for both folding (line) and rotation.", keyConcepts:["letter T S X","both symmetry types"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-069", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"What is the order of rotational symmetry of a rectangle that is 6cm × 4cm? What is the angle?", answer:"Order 2; angle = 180°.", steps:[{stepNumber:1,title:"Rectangle",explanation:"Non-square rectangle: order 2, angle = 360°/2 = 180°."}], hint:"A rectangle always has order 2 rotational symmetry.", keyConcepts:["rectangle","order 2","180°"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-070", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A kaleidoscope shows patterns with 6-fold symmetry. (a) How many lines of symmetry does each pattern have? (b) What is the smallest angle of rotation that reproduces the pattern?", answer:"(a) 6 lines of symmetry. (b) 60°.", steps:[{stepNumber:1,title:"6-fold",explanation:"6 lines and 60° rotation.",result:"6 lines; 60°"}], hint:"6-fold symmetry → n = 6.", keyConcepts:["kaleidoscope","6-fold","real-world"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-071", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"How many lines of symmetry and what order of rotational symmetry does a rhombus have?", answer:"Lines of symmetry: 2 (both diagonals). Order of rotational symmetry: 2 (looks same after 180°).", steps:[{stepNumber:1,title:"Rhombus",explanation:"2 lines of symmetry (diagonals). Rotational order 2 (180°)."}], hint:"For a rhombus, the diagonals are the lines of symmetry.", keyConcepts:["rhombus","2 lines","order 2"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch14-072", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"The Indian national flag's Ashoka Chakra has 24 equally spaced spokes. What is the order of rotational symmetry and the angle of rotation?", answer:"Order 24; angle = 360°/24 = 15°.", steps:[{stepNumber:1,title:"24 spokes",explanation:"Order = 24; angle = 15°.",result:"Order 24; angle 15°"}], hint:"Divide 360° by 24 spokes.", keyConcepts:["Ashoka Chakra","order 24","real-world"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-073", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"A figure has rotational symmetry of order n and exactly n lines of symmetry. Give a general formula for its angle of rotation, and confirm with n = 3, 4, 6.", answer:"Angle = 360°/n. n=3: 120°. n=4: 90°. n=6: 60°. These match equilateral triangle (120°), square (90°), hexagon (60°).", steps:[{stepNumber:1,title:"Formula",explanation:"Angle = 360°/n."},{stepNumber:2,title:"Verify n=3,4,6",explanation:"120°, 90°, 60° respectively. All match known regular polygons.",result:"Angle = 360°/n; confirmed for n=3,4,6"}], hint:"Use angle = 360°/n for each case.", keyConcepts:["formula","360/n","verification"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-074", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Two students disagree: Ananya says a parallelogram has 2 lines of symmetry; Bharat says it has 0. Who is correct and why?", answer:"Bharat is correct. A parallelogram (non-rhombus, non-rectangle) has 0 lines of symmetry. Its diagonals are not lines of symmetry because folding along either diagonal does not produce matching halves — the shape is slanted. (Note: a rhombus and rectangle are special parallelograms that DO have lines of symmetry.)", steps:[{stepNumber:1,title:"Check vertical/horizontal fold",explanation:"A slanted parallelogram fold gives non-matching halves."},{stepNumber:2,title:"Check diagonal fold",explanation:"Also non-matching (diagonals of a general parallelogram are not perpendicular bisectors of each other)."},{stepNumber:3,title:"Conclusion",explanation:"0 lines of symmetry for a general parallelogram.",result:"Bharat is correct — 0 lines of symmetry"}], hint:"Try physically folding a parallelogram shape — do any folds give matching halves?", keyConcepts:["parallelogram","0 lines","debate resolution"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Thinking diagonals are lines of symmetry",correction:"For a general parallelogram, diagonals are not lines of symmetry."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch14-075", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Symmetry", topicId:"t3", topicName:"Order of Rotational Symmetry and Applications", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"A regular polygon has an angle of rotation of 40°. How many sides does it have? How many lines of symmetry does it have?", answer:"Order = 360° ÷ 40° = 9. It is a regular nonagon with 9 sides and 9 lines of symmetry.", steps:[{stepNumber:1,title:"Find order",explanation:"Order = 360°/40° = 9."},{stepNumber:2,title:"Sides and lines",explanation:"Regular 9-gon → 9 sides → 9 lines of symmetry.",result:"9 sides; 9 lines of symmetry"}], hint:"Order = 360° ÷ angle. For a regular n-gon, n = order.", keyConcepts:["angle to sides","order = sides","nonagon"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },
];
