// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 7, Chapter 15: Visualising Solid Shapes
 *
 * 75 curated questions — difficulty: Easy 40% (30), Medium 40% (30), Hard 20% (15)
 * Board: Both (CBSE + ICSE) | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 3D Shapes — Faces, Edges, Vertices     — 25 q (10E / 10M / 5H)
 *   t2 Nets of 3D Shapes                      — 25 q (10E / 10M / 5H)
 *   t3 Drawing and Mapping Solid Shapes       — 25 q (10E / 10M / 5H)
 *
 * v1 2026-07-07 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";

export const CH15_VISUALISING_SOLID_SHAPES: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — 3D Shapes: Faces, Edges, Vertices  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-7-ch15-001", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is the difference between a 2D shape and a 3D shape?", answer:"A 2D (two-dimensional) shape is flat and has only length and breadth (e.g., square, circle). A 3D (three-dimensional) shape has length, breadth, and height — it occupies space (e.g., cube, sphere).", steps:[{stepNumber:1,title:"2D vs 3D",explanation:"2D: flat, two measurements. 3D: solid, three measurements."}], hint:"Does the shape have depth/height?", keyConcepts:["2D","3D","dimensions"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-002", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"How many faces, edges, and vertices does a cube have?", answer:"Cube: 6 faces, 12 edges, 8 vertices.", steps:[{stepNumber:1,title:"Cube properties",explanation:"6 square faces, 12 equal edges, 8 corners (vertices)."}], hint:"Think of a dice.", keyConcepts:["cube","faces edges vertices"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-003", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"How many faces, edges, and vertices does a cuboid have?", answer:"Cuboid: 6 faces, 12 edges, 8 vertices. All faces are rectangles (some pairs are squares in special cases).", steps:[{stepNumber:1,title:"Cuboid",explanation:"Same count as cube: 6F, 12E, 8V but faces are rectangles, not necessarily all equal."}], hint:"A cuboid is a rectangular box shape.", keyConcepts:["cuboid","6 faces","12 edges","8 vertices"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-004", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What are the faces, edges, and vertices of a triangular prism?", answer:"Triangular prism: 5 faces (2 triangular + 3 rectangular), 9 edges, 6 vertices.", steps:[{stepNumber:1,title:"Triangular prism",explanation:"Two triangular ends + three rectangular sides = 5 faces. 6 vertices. 9 edges."}], hint:"A triangular prism looks like a Toblerone box.", keyConcepts:["triangular prism","5 faces","9 edges","6 vertices"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-005", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What are the faces, edges, and vertices of a square pyramid?", answer:"Square pyramid: 5 faces (1 square base + 4 triangular sides), 8 edges, 5 vertices.", steps:[{stepNumber:1,title:"Square pyramid",explanation:"1 square base + 4 triangles = 5 faces. 4 base vertices + 1 apex = 5 vertices. 4 base edges + 4 slant edges = 8 edges."}], hint:"Think of the Egyptian pyramids.", keyConcepts:["square pyramid","5 faces","8 edges","5 vertices"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-006", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Does a sphere have any edges or vertices?", answer:"No. A sphere has no edges and no vertices (corners). It has one curved surface.", steps:[{stepNumber:1,title:"Sphere",explanation:"A sphere is perfectly round — no flat faces, no edges, no vertices. Just one continuous curved surface."}], hint:"Think of a ball — it has no corners or edges.", keyConcepts:["sphere","no edges","no vertices"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Thinking sphere has edges",correction:"A sphere has no edges or vertices, only a curved surface."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-007", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"How many flat faces does a cylinder have?", answer:"2 flat (circular) faces at the top and bottom. It also has 1 curved face.", steps:[{stepNumber:1,title:"Cylinder",explanation:"Top circle + bottom circle = 2 flat faces. Curved side = 1 curved face. Total: 3 faces (2 flat + 1 curved)."}], hint:"Think of a tin can.", keyConcepts:["cylinder","2 flat faces","1 curved face"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-008", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"TrueOrFalse", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"True or False: A cone has two flat faces.", answer:"False. A cone has only one flat face (the circular base) and one curved face.", steps:[{stepNumber:1,title:"Cone",explanation:"1 circular flat base + 1 curved lateral surface. Total: 1 flat face, not 2."}], hint:"Picture an ice cream cone — how many flat parts does it have?", keyConcepts:["cone","1 flat face","curved surface"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Saying 2 flat faces",correction:"Cone has 1 flat face (base) and 1 curved face."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-009", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"Name the 3D shape that has: 5 faces, 9 edges, 6 vertices.", answer:"Triangular prism.", steps:[{stepNumber:1,title:"Match properties",explanation:"5F, 9E, 6V → triangular prism (two triangular faces and three rectangular faces)."}], hint:"Think of a shape with triangular ends.", keyConcepts:["triangular prism","identify from properties"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-010", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"Name the 3D shape that has: 1 curved face, 1 flat circular face, 1 vertex (apex), no edges.", answer:"Cone.", steps:[{stepNumber:1,title:"Match",explanation:"1 curved face + 1 circular base + 1 apex (vertex) + 0 edges → cone."}], hint:"Ice cream cone!", keyConcepts:["cone","identify"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-011", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A triangular pyramid (tetrahedron) has all triangular faces. State its number of faces, edges, and vertices.", answer:"Faces: 4 (all triangles), Edges: 6, Vertices: 4.", steps:[{stepNumber:1,title:"Tetrahedron",explanation:"4 triangular faces, 6 edges, 4 vertices. Like a 3D triangle."}], hint:"A tetrahedron is 4 triangles joined together.", keyConcepts:["tetrahedron","4F 6E 4V"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-012", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"understand", marks:2, estimatedTimeMinutes:3, question:"What is the difference between a prism and a pyramid?", answer:"A prism has two identical parallel bases (polygons) connected by rectangular faces. A pyramid has one polygonal base with triangular faces meeting at a single apex (vertex) at the top.", steps:[{stepNumber:1,title:"Prism",explanation:"Two identical bases + rectangular sides."},{stepNumber:2,title:"Pyramid",explanation:"One base + triangular sides meeting at apex.",result:"Prism: two bases. Pyramid: one base + apex."}], hint:"Think of a Toblerone (prism) vs Egyptian pyramid.", keyConcepts:["prism vs pyramid","bases","apex"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-013", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A pentagonal prism has a pentagon as its base. Find: (a) number of faces, (b) number of edges, (c) number of vertices.", answer:"(a) 7 faces (2 pentagons + 5 rectangles). (b) 15 edges (5 + 5 + 5). (c) 10 vertices.", steps:[{stepNumber:1,title:"Faces",explanation:"2 pentagonal + 5 rectangular = 7."},{stepNumber:2,title:"Edges",explanation:"5 (top) + 5 (bottom) + 5 (vertical) = 15."},{stepNumber:3,title:"Vertices",explanation:"5 top + 5 bottom = 10.",result:"F=7, E=15, V=10"}], hint:"A prism with an n-gon base: F = n+2, E = 3n, V = 2n.", keyConcepts:["pentagonal prism","F E V formula"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-014", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A hexagonal pyramid has a hexagon as its base. Find: (a) faces, (b) edges, (c) vertices.", answer:"(a) 7 faces (1 hexagonal + 6 triangular). (b) 12 edges. (c) 7 vertices.", steps:[{stepNumber:1,title:"Faces",explanation:"1 hexagonal base + 6 triangular sides = 7."},{stepNumber:2,title:"Edges",explanation:"6 (base) + 6 (slant) = 12."},{stepNumber:3,title:"Vertices",explanation:"6 (base) + 1 (apex) = 7.",result:"F=7, E=12, V=7"}], hint:"For n-gon pyramid: F=n+1, E=2n, V=n+1.", keyConcepts:["hexagonal pyramid","F E V"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-015", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"What 3D shape do you get when you roll a rectangular piece of paper into a tube?", answer:"A cylinder (without the circular ends). The rolled paper forms the curved lateral surface of a cylinder.", steps:[{stepNumber:1,title:"Rolling paper",explanation:"A rectangle rolled lengthwise forms a cylindrical tube — the lateral surface of a cylinder."}], hint:"Think of a paper towel tube.", keyConcepts:["cylinder","rolling","lateral surface"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-016", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Compare a cube and cuboid: in what ways are they the same and in what ways are they different?", answer:"Same: both have 6 faces, 12 edges, 8 vertices; all faces are rectangles. Different: in a cube all 6 faces are equal squares and all 12 edges are equal; in a cuboid faces are rectangles and edges can have 3 different lengths.", steps:[{stepNumber:1,title:"Similarities",explanation:"Same F, E, V counts. All faces are quadrilaterals."},{stepNumber:2,title:"Differences",explanation:"Cube: all edges equal; Cuboid: 3 pairs of equal edges.",result:"Same count; different proportions"}], hint:"A cube is a special cuboid.", keyConcepts:["cube vs cuboid","equal edges","special case"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-017", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A brick is a real-world example of which 3D shape? State its number of faces, edges, and vertices.", answer:"A cuboid. Faces: 6, Edges: 12, Vertices: 8.", steps:[{stepNumber:1,title:"Brick = cuboid",explanation:"A brick is a rectangular box → cuboid. 6F, 12E, 8V."}], hint:"What shape is a standard brick?", keyConcepts:["cuboid","real world","brick"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-018", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Fill in the table: For cube (side 4cm) — what are the shapes and sizes of all faces?", answer:"All 6 faces are squares, each 4cm × 4cm.", steps:[{stepNumber:1,title:"Cube faces",explanation:"All 6 faces are congruent squares with side 4cm."}], hint:"A cube has identical square faces.", keyConcepts:["cube faces","squares"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-019", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Name the 3D shape that has: 4 triangular faces, 6 edges, 4 vertices.", answer:"Triangular pyramid (tetrahedron).", steps:[{stepNumber:1,title:"Match",explanation:"4F (all triangles), 6E, 4V → tetrahedron."}], hint:"All faces are triangles — what is that shape?", keyConcepts:["tetrahedron","identify"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-020", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"understand", marks:2, estimatedTimeMinutes:3, question:"Which 3D shape has the same number of faces and vertices?", answer:"A tetrahedron (triangular pyramid): F = 4, V = 4. Also a square pyramid: F = 5, V = 5, and a pentagonal pyramid: F = 6, V = 6. In general, for any n-gon pyramid: F = n+1 and V = n+1, so faces = vertices.", steps:[{stepNumber:1,title:"Pattern for pyramids",explanation:"For any n-gon pyramid: F = n+1, V = n+1 → F = V always.",result:"Any pyramid: F = V"}], hint:"Look for F = V in the table of 3D shapes.", keyConcepts:["F=V","pyramid","pattern"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-021", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:3, estimatedTimeMinutes:5, question:"A shape has 6 vertices and 9 edges. Using the formula F + V = E + 2, find the number of faces.", answer:"F + V = E + 2 → F + 6 = 9 + 2 = 11 → F = 5. The shape has 5 faces (it is a triangular prism).", steps:[{stepNumber:1,title:"Euler's formula",explanation:"F + V = E + 2. Given V=6, E=9: F + 6 = 11 → F = 5.",result:"5 faces (triangular prism)"}], hint:"Use Euler's formula: F + V = E + 2.", keyConcepts:["Euler's formula","F+V=E+2","apply"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-022", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Can a polyhedron have 4 faces, 6 edges, and 5 vertices? Verify using Euler's formula.", answer:"F + V = 4 + 5 = 9, but E + 2 = 6 + 2 = 8. Since 9 ≠ 8, this is NOT a valid polyhedron. Such a shape cannot exist.", steps:[{stepNumber:1,title:"Apply Euler's formula",explanation:"F + V must equal E + 2. Here F+V = 9, E+2 = 8. 9 ≠ 8."},{stepNumber:2,title:"Conclusion",explanation:"Invalid — no such polyhedron can exist.",result:"Not a valid polyhedron"}], hint:"Apply F + V = E + 2 and check if equality holds.", keyConcepts:["Euler's formula","verification","invalid polyhedron"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-023", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"Fill in the missing value: A polyhedron has 8 faces and 12 vertices. Find the number of edges using Euler's formula.", answer:"F + V = E + 2 → 8 + 12 = E + 2 → E = 18.", steps:[{stepNumber:1,title:"Euler's formula",explanation:"8 + 12 = E + 2 → 20 = E + 2 → E = 18.",result:"18 edges"}], hint:"F + V = E + 2 → E = F + V − 2.", keyConcepts:["Euler's formula","find edges","F+V=E+2"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-024", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Verify Euler's formula for a square pyramid and a triangular prism.", answer:"Square pyramid: F=5, V=5, E=8. F+V=10, E+2=10. ✓ Triangular prism: F=5, V=6, E=9. F+V=11, E+2=11. ✓ Euler's formula verified for both.", steps:[{stepNumber:1,title:"Square pyramid",explanation:"5+5=10=8+2. ✓"},{stepNumber:2,title:"Triangular prism",explanation:"5+6=11=9+2. ✓",result:"Both satisfy F+V=E+2"}], hint:"Check F + V = E + 2 for each shape.", keyConcepts:["Euler's formula","verification","two shapes"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-025", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"3D Shapes and Their Properties", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:3, estimatedTimeMinutes:5, question:"State Euler's formula for polyhedra and explain what each symbol means.", answer:"Euler's formula: F + V = E + 2, where F = number of faces, V = number of vertices, E = number of edges. This formula holds for any convex polyhedron (a solid where all faces are flat polygons and all interior angles point inward).", steps:[{stepNumber:1,title:"Formula",explanation:"F + V = E + 2."},{stepNumber:2,title:"Variables",explanation:"F = faces, V = vertices, E = edges."},{stepNumber:3,title:"Scope",explanation:"Valid for any convex polyhedron.",result:"F + V = E + 2"}], hint:"Named after Leonhard Euler.", keyConcepts:["Euler's formula","F V E definition","polyhedron"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Nets of 3D Shapes  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-7-ch15-026", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is a net of a 3D shape?", answer:"A net is a flat (2D) shape that can be folded along its edges to form a 3D solid. It shows all the faces of the solid laid out flat without any overlaps.", steps:[{stepNumber:1,title:"Definition",explanation:"Unfold a 3D shape completely — the resulting flat arrangement is the net. Fold it back → 3D shape."}], hint:"Unbox a cardboard box — the unfolded form is the net.", keyConcepts:["net","2D flat form","fold to 3D"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-027", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"How many faces does the net of a cube have?", answer:"6 faces — a cube has 6 faces, so its net has 6 squares.", steps:[{stepNumber:1,title:"Cube net",explanation:"A cube has 6 square faces. When unfolded, the net shows all 6 squares laid flat."}], hint:"A cube has 6 faces → its net has 6 squares.", keyConcepts:["cube net","6 squares"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-028", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"TrueOrFalse", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"True or False: A cube has only one possible net.", answer:"False. A cube has 11 different valid nets.", steps:[{stepNumber:1,title:"11 nets",explanation:"There are exactly 11 distinct nets for a cube — 11 different ways to unfold 6 squares that can fold back into a cube."}], hint:"Can you think of more than one way to unfold a cube?", keyConcepts:["cube","11 nets","multiple nets"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Thinking only one net exists",correction:"A cube has exactly 11 valid nets."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-029", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What shapes appear in the net of a cylinder?", answer:"Two circles (top and bottom) and one rectangle (the curved surface when unrolled).", steps:[{stepNumber:1,title:"Cylinder net",explanation:"Unroll the curved surface → rectangle. Two circular ends remain as circles."}], hint:"Unroll a tin can — what shapes do you see?", keyConcepts:["cylinder net","two circles","rectangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-030", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"How many shapes are in the net of a square pyramid?", answer:"5 shapes: 1 square (base) and 4 triangles (lateral faces).", steps:[{stepNumber:1,title:"Square pyramid net",explanation:"Square pyramid has 5 faces: 1 square + 4 triangles → net has same 5 shapes."}], hint:"Count the faces of a square pyramid.", keyConcepts:["square pyramid net","1 square 4 triangles"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-031", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"How many rectangles are in the net of a triangular prism?", answer:"3 rectangles (the lateral faces) + 2 triangles (the two bases) = 5 shapes total. The net has 3 rectangles.", steps:[{stepNumber:1,title:"Triangular prism net",explanation:"Triangular prism: 2 triangular bases + 3 rectangular lateral faces → 3 rectangles in net."}], hint:"Count the rectangular sides of a triangular prism.", keyConcepts:["triangular prism net","3 rectangles"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-032", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A net consists of a circle and a triangle (sector). What 3D shape can it form?", answer:"A cone. The circle is the base and the sector (triangle-like curved piece) folds to form the curved lateral surface.", steps:[{stepNumber:1,title:"Cone net",explanation:"Circle (base) + sector (curved surface) → cone."}], hint:"What 3D shape has a circular base and a pointed top?", keyConcepts:["cone net","circle + sector"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-033", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A student draws a net with 6 identical squares. What 3D shape will it form?", answer:"A cube (provided the 6 squares are arranged in one of the 11 valid net configurations).", steps:[{stepNumber:1,title:"6 identical squares",explanation:"6 equal squares in a valid arrangement → cube."}], hint:"What 3D shape has 6 identical square faces?", keyConcepts:["cube net","6 squares"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-034", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"Name a real-life object whose net you have likely seen when buying goods.", answer:"A cardboard box (cuboid). Cereals, shoes, and other boxes come as flat nets that are folded and assembled.", steps:[{stepNumber:1,title:"Cardboard box",explanation:"Unfolded box = net of a cuboid."}], hint:"What do you see when you open up a cereal box completely flat?", keyConcepts:["cuboid net","real world","cardboard box"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-035", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A net has 2 triangles and 3 rectangles. What 3D shape does it form? Name the shape and state its F, E, V.", answer:"Triangular prism: F=5, E=9, V=6.", steps:[{stepNumber:1,title:"Identify",explanation:"2 triangular bases + 3 rectangular lateral faces = triangular prism."},{stepNumber:2,title:"F E V",explanation:"F=5, E=9, V=6.",result:"Triangular prism; F=5, E=9, V=6"}], hint:"Two triangle ends + three rectangle sides.", keyConcepts:["net to shape","triangular prism"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-036", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Can the following arrangement of 6 squares form a valid net for a cube? (Cross shape: 1 centre square, 4 around it, 1 more attached below). Answer Yes or No and explain.", answer:"Yes. The plus/cross shape (4 squares around a centre + 1 below) is one of the 11 valid cube nets. When folded, the 4 side squares fold up to form walls, the centre becomes the bottom, and the 1 square below becomes the top.", steps:[{stepNumber:1,title:"Check validity",explanation:"This cross arrangement is a valid cube net — confirmed by the list of 11 valid nets.",result:"Yes, valid cube net"}], hint:"The plus sign arrangement of 6 squares is a classic cube net.", keyConcepts:["valid cube net","cross shape","folding"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-037", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A cuboid is 5cm × 3cm × 2cm. In the net, what are the dimensions of each pair of rectangular faces?", answer:"Three pairs of faces: (i) 5×3 cm (top and bottom, 2 faces). (ii) 5×2 cm (front and back, 2 faces). (iii) 3×2 cm (left and right, 2 faces).", steps:[{stepNumber:1,title:"Three pairs",explanation:"l×b = 5×3 (×2 faces). l×h = 5×2 (×2 faces). b×h = 3×2 (×2 faces). Total: 6 faces.",result:"Three pairs: 5×3, 5×2, 3×2"}], hint:"Each pair of opposite faces of a cuboid are identical.", keyConcepts:["cuboid net","face dimensions","three pairs"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-038", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"evaluate", marks:2, estimatedTimeMinutes:4, question:"A student draws a net with 4 squares in a row and 1 square on each side of the second square. Will this form a valid cube? Explain.", answer:"Yes — this is another valid cube net (T-shape or similar). When folded: the row of 4 provides the bottom, 2 sides, top, and back; the 2 extra squares form the remaining sides. This is among the 11 valid cube nets.", steps:[{stepNumber:1,title:"Identify net type",explanation:"Row of 4 with 2 extra squares on sides — valid cube net.",result:"Yes, valid cube net"}], hint:"Try mentally folding the squares up one by one.", keyConcepts:["cube net","validation","folding"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-039", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"The net of a shape has 1 rectangle and 2 circles. What 3D shape does it form?", answer:"A cylinder. The rectangle is the lateral (curved) surface when unrolled; the 2 circles are the top and bottom bases.", steps:[{stepNumber:1,title:"Cylinder net",explanation:"Rectangle (lateral surface) + 2 circles (bases) → cylinder."}], hint:"Which 3D shape has two circular ends and one curved side?", keyConcepts:["cylinder net","rectangle + 2 circles"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-040", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Why is a net useful in real life? Give two examples.", answer:"(1) Packaging design: manufacturers design nets of boxes so they can be printed on flat sheets, cut, and folded into boxes efficiently. (2) Architecture: architects use nets to model 3D roof shapes before building. Nets allow visualisation of 3D shapes before construction.", steps:[{stepNumber:1,title:"Packaging",explanation:"Box nets printed and folded → product packaging."},{stepNumber:2,title:"Architecture",explanation:"Roof and structure nets allow pre-building visualisation.",result:"Packaging and architecture"}], hint:"Where do you see flat pieces that fold into 3D objects in everyday life?", keyConcepts:["net applications","packaging","real world"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-041", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A net consists of 4 squares in an L-shape plus 2 more squares. A student claims this will always form a cube. Is the student correct?", answer:"Not always. Not all arrangements of 6 squares form a valid cube net. Only 11 specific arrangements work. An L-shape of 4 + 2 more squares may or may not be a valid net depending on where the extra squares are placed. The student's claim 'always' is incorrect.", steps:[{stepNumber:1,title:"Not all 6-square arrangements work",explanation:"There are many ways to arrange 6 squares, but only 11 are valid cube nets."},{stepNumber:2,title:"Counter-example",explanation:"6 squares all in a straight row cannot fold into a cube.",result:"The student is incorrect — not always"}], hint:"Can 6 squares in a straight line fold into a cube?", keyConcepts:["invalid net","11 valid cube nets","critical thinking"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-042", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"A net of a cuboid measures 8cm × 6cm total area. If the cuboid has dimensions l × b × h, explain whether the total net area equals the total surface area of the cuboid.", answer:"Yes — the net area equals the total surface area. The net shows all faces of the cuboid laid flat without overlap. Total surface area = 2(lb + bh + hl). This is identical to the net area, since the net is just all faces arranged flat.", steps:[{stepNumber:1,title:"Net = all faces flat",explanation:"No overlaps in a valid net."},{stepNumber:2,title:"Net area = TSA",explanation:"Both count the same 6 faces.",result:"Net area = Total Surface Area"}], hint:"The net includes all faces of the solid.", keyConcepts:["net area = TSA","surface area","no overlap"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-043", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"create", marks:4, estimatedTimeMinutes:7, question:"Sketch the net of a triangular prism with equilateral triangle bases (side 4cm) and rectangular height 6cm. Label all dimensions.", answer:"Net: two equilateral triangles (side 4cm) and three rectangles each 4cm × 6cm. Arrangement: the three rectangles in a row (12cm × 6cm strip) with one triangle on top of the middle rectangle and one triangle on the bottom.", steps:[{stepNumber:1,title:"Rectangles",explanation:"Three 4×6 rectangles side by side = 12cm × 6cm strip."},{stepNumber:2,title:"Triangles",explanation:"One equilateral triangle (4cm) above middle rectangle, one below.",result:"Strip of 3 rectangles + 2 equilateral triangles"}], hint:"Lay the 3 rectangular sides flat in a row, then attach the two triangular ends.", keyConcepts:["triangular prism net","sketch","dimensions"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-044", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A 3D shape has a net consisting of 1 square and 4 identical isosceles triangles with their base equal to the square's side. What solid does this form? Verify using Euler's formula.", answer:"Square pyramid. F=5 (1 square + 4 triangles), V=5 (4 base + 1 apex), E=8. F+V = 5+5 = 10 = E+2 = 8+2 = 10. ✓", steps:[{stepNumber:1,title:"Identify shape",explanation:"1 square base + 4 triangular sides → square pyramid."},{stepNumber:2,title:"Euler's formula",explanation:"F+V = 5+5=10 = 8+2 = E+2. ✓",result:"Square pyramid; Euler verified"}], hint:"What solid has one square base and four triangular sides?", keyConcepts:["square pyramid","net identification","Euler verification"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-045", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Nets of 3D Shapes", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"A net of a cube has 6 squares in a 'T' arrangement (3 in a row, 1 on top of each outer square). Is this valid? Explain.", answer:"Yes — a T-shaped or cross-like arrangement with 6 squares can be a valid cube net, depending on the exact placement. If the 3-in-a-row are the spine and the 3 extra squares attach in valid positions (not creating overlaps when folded), it forms a cube. Students should verify by checking that no two faces will occupy the same position when folded.", steps:[{stepNumber:1,title:"Check overlap when folding",explanation:"Start folding from one end — ensure no two squares overlap."},{stepNumber:2,title:"Valid net",explanation:"If no overlap occurs, it is a valid cube net.",result:"Depends on exact arrangement — could be valid"}], hint:"Fold it mentally — do any squares land on top of each other?", keyConcepts:["cube net validity","T shape","folding test"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t3 — Drawing and Mapping Solid Shapes  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-7-ch15-046", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is an oblique sketch of a 3D shape?", answer:"An oblique sketch is a freehand drawing of a 3D solid on a 2D surface where the shape is drawn with depth suggested by slanted (oblique) lines. Measurements are not necessarily to scale but the shape's proportions are suggested.", steps:[{stepNumber:1,title:"Oblique sketch",explanation:"A 2D drawing that gives the illusion of 3D depth using slanted lines for edges going into the background."}], hint:"Imagine drawing a cube on paper showing its depth.", keyConcepts:["oblique sketch","3D on 2D","depth representation"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-047", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is an isometric sketch?", answer:"An isometric sketch is a drawing of a 3D object on isometric dot paper, where all three axes are drawn at 120° to each other. Edges are drawn to scale along these axes, giving a more accurate 3D representation.", steps:[{stepNumber:1,title:"Isometric sketch",explanation:"Drawn on isometric dot paper; three axes at 120°; edges to scale along the axes."}], hint:"Isometric comes from 'equal measure' — edges are drawn to actual scale.", keyConcepts:["isometric sketch","120° axes","to scale"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-048", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What is the difference between an oblique sketch and an isometric sketch?", answer:"Oblique sketch: drawn freely, not to scale, depth suggested by slanted lines. Isometric sketch: drawn on isometric dot paper, to scale, three axes at 120°, more accurate representation of 3D proportions.", steps:[{stepNumber:1,title:"Comparison",explanation:"Oblique = freehand, not to scale. Isometric = to scale on dot paper, 120° axes."}], hint:"Think of oblique as quick sketch; isometric as precise technical drawing.", keyConcepts:["oblique vs isometric","scale","dot paper"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-049", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"On a map, what does the scale 1 cm = 500 m mean?", answer:"1 cm on the map represents 500 m in actual distance. So any distance measured on the map must be multiplied by 500 to get the real-world distance.", steps:[{stepNumber:1,title:"Map scale",explanation:"1 cm on map = 500 m in reality. Multiply map distance by 500 for actual distance."}], hint:"The scale tells you the ratio between map distance and actual distance.", keyConcepts:["map scale","ratio","1:50000"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-050", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"On a map with scale 1 cm = 2 km, two cities are 6 cm apart. What is the actual distance?", answer:"6 × 2 = 12 km.", steps:[{stepNumber:1,title:"Apply scale",explanation:"6 cm × 2 km/cm = 12 km.",result:"12 km"}], hint:"Multiply map distance by the scale factor.", keyConcepts:["map scale","multiply","actual distance"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-051", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"On a map, the scale is 1 cm = 100 m. A road appears as 3.5 cm on the map. What is its actual length?", answer:"3.5 × 100 = 350 m.", steps:[{stepNumber:1,title:"Scale calculation",explanation:"3.5 × 100 = 350 m.",result:"350 m"}], hint:"Multiply map length by scale factor.", keyConcepts:["map scale","actual length"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-052", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A room is 5 m × 4 m. On a scale drawing with 1 cm = 1 m, what are the dimensions of the room on paper?", answer:"5 cm × 4 cm.", steps:[{stepNumber:1,title:"Scale",explanation:"1 cm = 1 m. So 5 m = 5 cm, 4 m = 4 cm.",result:"5 cm × 4 cm"}], hint:"Divide actual dimensions by scale factor.", keyConcepts:["scale drawing","1:1 m","room plan"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-053", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A building is 30 m tall. On a diagram, its height is drawn as 6 cm. What is the scale of the diagram?", answer:"Scale: 1 cm = 5 m (or 1:500).", steps:[{stepNumber:1,title:"Find scale",explanation:"30 m ÷ 6 cm = 5 m/cm. Scale: 1 cm represents 5 m.",result:"1 cm = 5 m"}], hint:"Divide actual height by diagram height.", keyConcepts:["find scale","1 cm = ?","ratio"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-054", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"On a floor plan (map of a room), north is indicated by an arrow. The bedroom is north-east of the living room. What does this mean?", answer:"The bedroom is to the upper-right of the living room on the map — it is in the direction that is 45° between north (up) and east (right).", steps:[{stepNumber:1,title:"North-east direction",explanation:"NE = between north (up) and east (right). Upper-right on a map with north pointing up."}], hint:"North is up, East is right. North-east is between them.", keyConcepts:["direction","north-east","floor plan"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-055", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What is a cross-section of a 3D shape?", answer:"A cross-section is the 2D shape you get when you cut through a 3D solid with a flat plane. For example, cutting a cube perpendicular to one edge gives a square cross-section.", steps:[{stepNumber:1,title:"Cross-section",explanation:"Slice the solid with a flat cut → the shape of the cut surface is the cross-section."}], hint:"Think of slicing bread — each slice face is a cross-section.", keyConcepts:["cross-section","flat cut","2D slice"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-056", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"An oblique sketch of a cube (side 3 cm) is drawn. How many visible edges are there and how many are hidden (shown as dashed lines)?", answer:"Visible: 9 edges (3 on the front face, 3 going back, 3 on the back face visible from angle). Hidden: 3 edges (the three back edges not visible). Total: 12 edges.", steps:[{stepNumber:1,title:"Cube edges",explanation:"12 total edges."},{stepNumber:2,title:"Visible vs hidden",explanation:"In a typical oblique view, 9 are visible and 3 are shown as dashed (hidden).",result:"9 visible, 3 hidden"}], hint:"In an oblique sketch, some edges at the back are hidden.", keyConcepts:["oblique sketch","visible hidden edges","cube"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-057", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"On a map with scale 1 cm = 10 km, find the actual distance if the map distance is 4.5 cm. Also find what map distance represents 75 km.", answer:"Actual: 4.5 × 10 = 45 km. Map distance for 75 km: 75 ÷ 10 = 7.5 cm.", steps:[{stepNumber:1,title:"Actual distance",explanation:"4.5 × 10 = 45 km."},{stepNumber:2,title:"Map for 75 km",explanation:"75 ÷ 10 = 7.5 cm.",result:"45 km; 7.5 cm"}], hint:"Multiply map distance by scale; divide actual by scale for map distance.", keyConcepts:["map scale","both directions"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-058", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A school is shown 2 cm north and 3 cm east of a park on a map with scale 1 cm = 500 m. What are the actual displacements north and east?", answer:"North: 2 × 500 = 1000 m = 1 km. East: 3 × 500 = 1500 m = 1.5 km.", steps:[{stepNumber:1,title:"Scale",explanation:"North: 2×500=1000m. East: 3×500=1500m.",result:"1km north; 1.5km east"}], hint:"Apply scale to each direction separately.", keyConcepts:["map scale","directions","displacement"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-059", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"What cross-section do you get when you cut a cylinder: (a) parallel to the base, (b) perpendicular to the base?", answer:"(a) Parallel to base: circle. (b) Perpendicular to base: rectangle.", steps:[{stepNumber:1,title:"Parallel cut",explanation:"Cutting parallel to circular base gives a circle cross-section."},{stepNumber:2,title:"Perpendicular cut",explanation:"Cutting through the axis (perpendicular to base) gives a rectangle.",result:"(a) circle; (b) rectangle"}], hint:"Think about slicing a can of food in two different ways.", keyConcepts:["cylinder cross-section","circle","rectangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-060", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"What cross-sections can you get from a cube by cutting in different directions?", answer:"(1) Square — when cut parallel to a face. (2) Rectangle — when cut at a slight angle. (3) Triangle — when cut diagonally through a vertex. (4) Regular hexagon — when cut through the midpoints of six edges.", steps:[{stepNumber:1,title:"Different cuts",explanation:"Square (parallel cut), rectangle (angled cut), triangle (vertex cut), hexagon (diagonal midpoint cut)."}], hint:"Try imagining slicing a cube at different angles.", keyConcepts:["cube cross-section","square rectangle triangle hexagon"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-061", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"In a town plan (map), a park covers 4 cm² on paper. If the scale is 1 cm = 50 m, what is the actual area of the park?", answer:"Area scale factor = 50² = 2500. Actual area = 4 × 2500 = 10,000 m² = 1 hectare.", steps:[{stepNumber:1,title:"Area scale",explanation:"Length scale 1:50 → area scale 1:2500."},{stepNumber:2,title:"Actual area",explanation:"4 × 2500 = 10000 m².",result:"10,000 m² = 1 hectare"}], hint:"Area scale = (length scale)². Multiply map area by (scale factor)².", keyConcepts:["area scale","scale squared","hectare"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Multiplying area by 50 instead of 2500",correction:"Area scale = (length scale)² = 50² = 2500."}], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-062", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Draw the floor plan view (top view) of your classroom. What 2D shape does the classroom most likely look like from above?", answer:"A rectangle. Most classrooms are rectangular, so the top view (plan view) is a rectangle. Students should label doors, windows, and furniture positions approximately.", steps:[{stepNumber:1,title:"Top view = floor plan",explanation:"Looking from directly above a rectangular room gives a rectangle."},{stepNumber:2,title:"Labelling",explanation:"Mark door, windows, desks approximately to scale.",result:"Rectangle floor plan"}], hint:"Imagine looking at the room from directly above.", keyConcepts:["floor plan","top view","rectangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-063", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"understand", marks:2, estimatedTimeMinutes:3, question:"Why do map-makers use a scale rather than drawing the actual size?", answer:"Actual-size maps would be impossibly large. A scale allows the map-maker to represent large areas (cities, countries) on manageable paper by reducing all distances by the same ratio. The scale maintains proportions so relative distances and positions are accurate.", steps:[{stepNumber:1,title:"Reason",explanation:"Actual distances are too large to fit on paper. Scale reduces everything proportionally while keeping accuracy."}], hint:"How big would a 1:1 map of India be?", keyConcepts:["scale reason","proportion","reduction"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-064", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"On an isometric sketch of a cuboid (3 units × 2 units × 2 units), how many unit cubes fit inside the cuboid?", answer:"3 × 2 × 2 = 12 unit cubes.", steps:[{stepNumber:1,title:"Volume = unit cubes",explanation:"Volume of cuboid = l × b × h = 3 × 2 × 2 = 12 unit cubes.",result:"12 unit cubes"}], hint:"Volume = length × width × height for a cuboid.", keyConcepts:["unit cubes","volume","isometric"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-065", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"What is the top view, front view, and side view of a cylinder?", answer:"Top view: circle. Front view: rectangle. Side view: rectangle. (From any side, the cylinder looks like a rectangle; from the top or bottom, it looks like a circle.)", steps:[{stepNumber:1,title:"Top view",explanation:"Looking down → circle."},{stepNumber:2,title:"Front/side view",explanation:"Looking from the side → rectangle.",result:"Top: circle; Front/Side: rectangle"}], hint:"Imagine looking at a can of food from the top, front, and side.", keyConcepts:["cylinder views","top front side","circle rectangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-066", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Two cities, A and B, are 180 km apart. On a map, they are 9 cm apart. A third city C is 60 km from A. How far is C from A on the map?", answer:"Scale: 1 cm = 180/9 = 20 km. Map distance for C: 60/20 = 3 cm.", steps:[{stepNumber:1,title:"Find scale",explanation:"1 cm = 180/9 = 20 km."},{stepNumber:2,title:"Map distance for C",explanation:"60 km ÷ 20 km/cm = 3 cm.",result:"C is 3 cm from A on the map"}], hint:"First find the scale, then apply it to find the map distance.", keyConcepts:["find scale then apply","map calculation"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-067", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"What cross-section do you get when you cut a cone: (a) parallel to the base, (b) through the apex and perpendicular to the base, (c) at an angle not through the apex?", answer:"(a) Parallel to base: circle (smaller than base). (b) Through apex, perp. to base: isosceles triangle. (c) At an angle (not through apex): ellipse.", steps:[{stepNumber:1,title:"Parallel cut",explanation:"Circle (conic section)."},{stepNumber:2,title:"Through apex",explanation:"Isosceles triangle."},{stepNumber:3,title:"Angled cut",explanation:"Ellipse (another conic section).",result:"Circle; triangle; ellipse"}], hint:"These are called conic sections — the shapes you get by cutting a cone.", keyConcepts:["cone cross-sections","circle triangle ellipse","conic sections"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-068", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"create", marks:4, estimatedTimeMinutes:7, question:"Design a floor plan (scale 1 cm = 2 m) for a simple house with: living room (6m × 4m), bedroom (4m × 4m), kitchen (3m × 3m). Label each room on the plan.", answer:"Scale: 1 cm = 2 m. Living room: 3 cm × 2 cm. Bedroom: 2 cm × 2 cm. Kitchen: 1.5 cm × 1.5 cm. Arrange these rectangles to share walls as appropriate. Label each rectangle with the room name and real dimensions.", steps:[{stepNumber:1,title:"Convert to map",explanation:"Divide each dimension by 2: LR=3×2cm; BR=2×2cm; K=1.5×1.5cm."},{stepNumber:2,title:"Draw",explanation:"Arrange as adjacent rectangles. Label with room names.",result:"Scaled floor plan with three rooms"}], hint:"Divide actual dimensions by the scale factor (2) to get plan dimensions.", keyConcepts:["floor plan","scale design","room plan"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-069", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"In an oblique sketch of a cube, how does the sketch suggest depth? What are the limitations of this method?", answer:"Depth is suggested by drawing the back edges as shorter and parallel lines (in oblique direction), and by using a consistent oblique angle (usually 45°). Limitations: (1) Distances along oblique edges are distorted — they appear shorter than actual. (2) Angles in the 3D shape are distorted in the 2D drawing. (3) Less accurate than isometric sketching.", steps:[{stepNumber:1,title:"How depth is shown",explanation:"Shorter parallel oblique lines represent edges going away from viewer."},{stepNumber:2,title:"Limitations",explanation:"Distorted angles and lengths; less precise than isometric.",result:"Depth via oblique lines; limited by distortion"}], hint:"Compare what you draw vs what you measure — do the lengths match?", keyConcepts:["oblique sketch depth","limitations","distortion"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-070", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"An artist draws an isometric sketch of a structure made of 4 unit cubes: 3 in a row and 1 on top of the middle cube. How many faces of unit cubes are visible in the sketch? How many are hidden?", answer:"Total cube faces = 4 × 6 = 24. Shared internal faces: 3 pairs at the 3 joints = 6 hidden faces. Extra hidden (bottom faces flat on surface): 4. Visible = 24 − 6 (shared) − 4 (bottoms) = 14 visible faces. (Exact count varies by viewing angle but typically 14 visible, 10 hidden for this arrangement.)", steps:[{stepNumber:1,title:"Total faces",explanation:"4 cubes × 6 faces = 24."},{stepNumber:2,title:"Hidden faces",explanation:"3 internal joints hide 6 faces; 4 bottom faces = 10 hidden."},{stepNumber:3,title:"Visible",explanation:"24 − 10 = 14 visible.",result:"14 visible; 10 hidden"}], hint:"Count shared faces at joints and bottom faces touching the ground.", keyConcepts:["unit cube arrangement","visible hidden faces","counting"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-7-ch15-071", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"What does the front view of a square pyramid look like?", answer:"A triangle (specifically an isosceles triangle). The front view shows the triangular face of the pyramid with the square base appearing as a horizontal line at the bottom.", steps:[{stepNumber:1,title:"Front view",explanation:"Looking at a square pyramid from the front → you see a triangular outline (isosceles triangle).",result:"Isosceles triangle"}], hint:"Look at an Egyptian pyramid from the front — what shape do you see?", keyConcepts:["square pyramid front view","triangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-072", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"What does the top view of a square pyramid look like?", answer:"A square with two diagonals drawn (the apex projects to the centre, showing the square base with the apex point at the centre, connected to each corner).", steps:[{stepNumber:1,title:"Top view",explanation:"Looking directly down at a square pyramid: you see the square base with lines from each corner to the centre (apex).",result:"Square with two diagonals"}], hint:"Imagine looking at a pyramid from a helicopter directly above.", keyConcepts:["square pyramid top view","square with diagonals"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-073", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"What do the top, front, and side views of a sphere look like?", answer:"All three views are circles. A sphere looks like a circle from every direction.", steps:[{stepNumber:1,title:"All views of sphere",explanation:"A sphere is perfectly round — it looks like a circle from any viewpoint (top, front, side, or any angle).",result:"All three views: circle"}], hint:"Is there any direction from which a sphere looks different from a circle?", keyConcepts:["sphere views","all circles"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-074", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"A structure is built with unit cubes as follows: bottom layer has a 2×2 arrangement; top layer has 1 cube in the centre. Draw (describe) the top view and front view.", answer:"Top view: a 2×2 square (the bottom layer outline) with a small square in the centre (the top cube). Front view: a row of 2 unit squares (bottom layer) with 1 unit square on top of the middle gap (centred above).", steps:[{stepNumber:1,title:"Top view",explanation:"Looking down: see the 2×2 base. The top cube is in the centre → small square in centre of 2×2."},{stepNumber:2,title:"Front view",explanation:"Looking from front: see 2 squares wide at bottom, 1 square centred on top.",result:"Top: 2×2 with centre square; Front: 2 wide, 1 on top"}], hint:"Describe what you see from directly above, then directly in front.", keyConcepts:["unit cube structure","top view","front view"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-7-ch15-075", schemaVersion:2, classNum:7, subject:"Mathematics", board:"Both", chapterId:"ch15", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Drawing and Mapping Solid Shapes", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"A cube is painted red on all faces and then cut into 27 equal smaller cubes. How many small cubes have: (a) 3 red faces, (b) 2 red faces, (c) 1 red face, (d) 0 red faces?", answer:"(a) 3 red faces: 8 (corner cubes). (b) 2 red faces: 12 (edge cubes). (c) 1 red face: 6 (face-centre cubes). (d) 0 red faces: 1 (centre cube, completely inside).", steps:[{stepNumber:1,title:"Corner cubes",explanation:"8 corners → 3 red faces each."},{stepNumber:2,title:"Edge cubes",explanation:"12 edges × 1 middle cube per edge = 12 → 2 red faces."},{stepNumber:3,title:"Face cubes",explanation:"6 faces × 1 centre = 6 → 1 red face."},{stepNumber:4,title:"Centre",explanation:"1 completely inside → 0 red faces. Total: 8+12+6+1=27. ✓",result:"8/12/6/1"}], hint:"Think about where each small cube is: corner, edge, face, or interior.", keyConcepts:["painted cube","corner edge face centre","3D reasoning"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },
];
