/**
 * Question Bank — Mathematics, Class 8, Chapter 1: Rational Numbers
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Properties of Rational Numbers — 50 q
 *   t2 Rational Numbers on Number Line — 25 q
 *
 * Concept nodes:
 *   mth:8:ch01:rational-closure
 *   mth:8:ch01:rational-commutativity
 *   mth:8:ch01:rational-associativity
 *   mth:8:ch01:rational-distributivity
 *   mth:8:ch01:density-of-rationals
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH01_RATIONAL_NUMBERS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Properties of Rational Numbers
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch01-con-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: The set of rational numbers is closed under addition.",
    answer: "True. The sum of any two rational numbers is always a rational number. For example, 1/2 + 1/3 = 5/6, which is rational.",
    steps: [{ stepNumber: 1, title: "Closure under addition", explanation: "p/q + r/s = (ps + qr)/qs, which is rational since ps+qr and qs are integers and qs ≠ 0." }],
    hint: "Closure means the result stays within the same number set.",
    keyConcepts: ["closure property", "rational addition"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "closure"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State the commutative property of addition for rational numbers and give one example.",
    answer: "For any two rational numbers a and b: a + b = b + a. Example: 2/3 + 1/4 = 11/12 and 1/4 + 2/3 = 11/12. Both give the same result.",
    steps: [
      { stepNumber: 1, title: "State property", explanation: "a + b = b + a for all rationals a, b." },
      { stepNumber: 2, title: "Example", explanation: "2/3 + 1/4 = 8/12 + 3/12 = 11/12 = 1/4 + 2/3." },
    ],
    hint: "Commutative means order doesn't matter.",
    keyConcepts: ["commutativity", "rational addition"],
    conceptsCovered: ["mth:8:ch01:rational-commutativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "commutativity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Subtraction of rational numbers is commutative.",
    answer: "False. Subtraction is NOT commutative. For example, 1/2 − 1/3 = 1/6, but 1/3 − 1/2 = −1/6. These are not equal.",
    steps: [{ stepNumber: 1, title: "Counter-example", explanation: "1/2 − 1/3 = 1/6 ≠ −1/6 = 1/3 − 1/2." }],
    hint: "Try a specific example to test commutativity of subtraction.",
    keyConcepts: ["commutativity", "subtraction"],
    conceptsCovered: ["mth:8:ch01:rational-commutativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "commutativity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State the associative property of multiplication for rational numbers.",
    answer: "For any rational numbers a, b, c: (a × b) × c = a × (b × c). The grouping of factors does not change the product. Example: (1/2 × 2/3) × 3/4 = 1/4 × 3/4 = 3/16 and 1/2 × (2/3 × 3/4) = 1/2 × 1/2 = 1/4 — wait, both equal 1/4. Let me recalculate: (1/2 × 2/3) × 3/4 = (1/3) × 3/4 = 1/4; 1/2 × (2/3 × 3/4) = 1/2 × 1/2 = 1/4. ✓",
    steps: [
      { stepNumber: 1, title: "State property", explanation: "(a × b) × c = a × (b × c) for all rationals." },
      { stepNumber: 2, title: "Verify with example", explanation: "Both groupings of (1/2)(2/3)(3/4) give 1/4." },
    ],
    hint: "Associative means regrouping doesn't change the answer.",
    keyConcepts: ["associativity", "multiplication"],
    conceptsCovered: ["mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "associativity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Verify the distributive property: 2/3 × (3/4 + 1/4) = (2/3 × 3/4) + (2/3 × 1/4).",
    answer: "LHS: 2/3 × (3/4 + 1/4) = 2/3 × 1 = 2/3. RHS: (2/3 × 3/4) + (2/3 × 1/4) = 6/12 + 2/12 = 8/12 = 2/3. LHS = RHS ✓",
    steps: [
      { stepNumber: 1, title: "Compute LHS", explanation: "3/4 + 1/4 = 4/4 = 1; 2/3 × 1 = 2/3." },
      { stepNumber: 2, title: "Compute RHS", explanation: "2/3 × 3/4 = 6/12 = 1/2; 2/3 × 1/4 = 2/12 = 1/6; 1/2 + 1/6 = 3/6 + 1/6 = 4/6 = 2/3." },
      { stepNumber: 3, title: "Compare", explanation: "2/3 = 2/3 ✓" },
    ],
    hint: "Multiply out both sides separately and then compare.",
    keyConcepts: ["distributive property", "verification"],
    conceptsCovered: ["mth:8:ch01:rational-distributivity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "distributivity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The additive identity for rational numbers is:",
    answer: "0. Adding 0 to any rational number leaves it unchanged: a + 0 = a for all rational a.",
    options: ["A) 1", "B) 0", "C) −1", "D) 1/2"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Identity element", explanation: "Additive identity is 0: a + 0 = 0 + a = a." }],
    hint: "The identity element for addition leaves a number unchanged.",
    keyConcepts: ["additive identity"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "identity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the additive inverse and multiplicative inverse of −5/7.",
    answer: "Additive inverse: 5/7 (since −5/7 + 5/7 = 0). Multiplicative inverse: −7/5 (since −5/7 × −7/5 = 35/35 = 1).",
    steps: [
      { stepNumber: 1, title: "Additive inverse", explanation: "Additive inverse of −5/7 is 5/7." },
      { stepNumber: 2, title: "Multiplicative inverse", explanation: "Flip the fraction and keep the sign: −7/5." },
    ],
    hint: "Additive inverse gives 0 when added; multiplicative inverse gives 1 when multiplied.",
    keyConcepts: ["additive inverse", "multiplicative inverse"],
    conceptsCovered: ["mth:8:ch01:rational-commutativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "inverse"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Division of rational numbers is associative.",
    answer: "False. Division is NOT associative. For example, (8 ÷ 4) ÷ 2 = 2 ÷ 2 = 1, but 8 ÷ (4 ÷ 2) = 8 ÷ 2 = 4. These are not equal.",
    steps: [{ stepNumber: 1, title: "Counter-example", explanation: "(8÷4)÷2 = 1 ≠ 4 = 8÷(4÷2)." }],
    hint: "Try a numeric example with three numbers.",
    keyConcepts: ["associativity", "division"],
    conceptsCovered: ["mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "associativity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Which properties distinguish rational numbers from integers? List at least three properties that rationals have but integers lack.",
    answer: "1. Multiplicative inverse: Every non-zero rational has a multiplicative inverse (e.g., 2/3 has inverse 3/2), but most integers don't (e.g., 2 has no integer inverse). 2. Density: Between any two rationals there is always another rational; integers are discrete. 3. Closure under division: Rationals are closed under division by non-zero rationals; integers are not (3÷2 = 3/2 is not an integer).",
    steps: [
      { stepNumber: 1, title: "Multiplicative inverse", explanation: "2/3 × 3/2 = 1 — works in rationals, fails for most integers." },
      { stepNumber: 2, title: "Density", explanation: "Between 1/2 and 2/3 lies 7/12. No integer exists between 1 and 2." },
      { stepNumber: 3, title: "Division closure", explanation: "3 ÷ 2 = 1.5, not an integer but is a rational." },
    ],
    hint: "Think about what operations close rationals but not integers.",
    keyConcepts: ["properties of rationals", "comparison with integers"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: ["Confusing 'closure under subtraction' — integers ARE closed under subtraction."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "compare"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "FillInTheBlanks",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The multiplicative identity for rational numbers is ___.",
    answer: "1. Multiplying any rational number by 1 gives the number itself: a × 1 = a.",
    steps: [{ stepNumber: 1, title: "Identity", explanation: "a × 1 = 1 × a = a for all rationals a." }],
    hint: "What number leaves any rational unchanged when multiplied?",
    keyConcepts: ["multiplicative identity"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "identity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using distributivity, simplify: 4/5 × 7/3 + 4/5 × (−2/3).",
    answer: "Factor out 4/5: 4/5 × (7/3 + (−2/3)) = 4/5 × 5/3 = 20/15 = 4/3.",
    steps: [
      { stepNumber: 1, title: "Factor", explanation: "4/5 is common: 4/5 × (7/3 − 2/3) = 4/5 × 5/3." },
      { stepNumber: 2, title: "Multiply", explanation: "4/5 × 5/3 = 20/15 = 4/3." },
    ],
    hint: "Look for a common factor before computing.",
    keyConcepts: ["distributivity", "simplification"],
    conceptsCovered: ["mth:8:ch01:rational-distributivity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "distributivity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch01-con-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which property is used when we write: 3/4 × (2/5 + 1/5) = 3/4 × 2/5 + 3/4 × 1/5?",
    answer: "Distributive property of multiplication over addition. The factor 3/4 is distributed to each term inside the bracket.",
    options: ["A) Commutative property", "B) Associative property", "C) Distributive property", "D) Closure property"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Identify", explanation: "a(b + c) = ab + ac is the distributive property." }],
    hint: "One number is multiplied with each term inside the bracket.",
    keyConcepts: ["distributive property"],
    conceptsCovered: ["mth:8:ch01:rational-distributivity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "properties"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch01-nce-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using appropriate property, find: −2/3 × 3/5 + 5/2 − 3/5 × 1/6.",
    answer: "Rearrange: −2/3 × 3/5 − 3/5 × 1/6 + 5/2 = 3/5 × (−2/3 − 1/6) + 5/2 = 3/5 × (−4/6 − 1/6) + 5/2 = 3/5 × (−5/6) + 5/2 = −15/30 + 5/2 = −1/2 + 5/2 = 4/2 = 2.",
    steps: [
      { stepNumber: 1, title: "Group using distributivity", explanation: "Factor out 3/5 from first and third terms." },
      { stepNumber: 2, title: "Simplify bracket", explanation: "−2/3 − 1/6 = −4/6 − 1/6 = −5/6." },
      { stepNumber: 3, title: "Multiply", explanation: "3/5 × (−5/6) = −15/30 = −1/2." },
      { stepNumber: 4, title: "Add", explanation: "−1/2 + 5/2 = 4/2 = 2." },
    ],
    hint: "Look for common factors to apply distributivity.",
    keyConcepts: ["distributivity", "simplification"],
    conceptsCovered: ["mth:8:ch01:rational-distributivity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the additive inverse of each: (i) 2/8  (ii) −5/9  (iii) −6/−5  (iv) 2/(−9).",
    answer: "(i) −2/8 = −1/4.  (ii) 5/9.  (iii) −6/−5 = 6/5, so additive inverse = −6/5.  (iv) 2/(−9) = −2/9, so additive inverse = 2/9.",
    steps: [
      { stepNumber: 1, title: "Rule", explanation: "Additive inverse of p/q is −p/q (change sign)." },
      { stepNumber: 2, title: "Apply", explanation: "Simplify sign first, then negate." },
    ],
    hint: "First simplify any double negatives, then negate.",
    keyConcepts: ["additive inverse"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Verify that −(−x) = x for x = 3/7.",
    answer: "x = 3/7. Additive inverse of x is −3/7. Additive inverse of −3/7 is −(−3/7) = 3/7 = x. ✓",
    steps: [
      { stepNumber: 1, title: "Find additive inverse of x", explanation: "−(3/7) = −3/7." },
      { stepNumber: 2, title: "Find additive inverse of that", explanation: "−(−3/7) = 3/7." },
      { stepNumber: 3, title: "Verify", explanation: "3/7 = x ✓." },
    ],
    hint: "Negating twice returns the original number.",
    keyConcepts: ["double negative", "additive inverse"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Name the property used in each: (a) −1/5 × (−3/7 + 2/5) = (−1/5)(−3/7) + (−1/5)(2/5)  (b) 2/3 + (−3/5 + 5/7) = (2/3 + (−3/5)) + 5/7.",
    answer: "(a) Distributive property of multiplication over addition. (b) Associative property of addition.",
    steps: [
      { stepNumber: 1, title: "(a) Identify", explanation: "a(b + c) = ab + ac — distributive." },
      { stepNumber: 2, title: "(b) Identify", explanation: "a + (b + c) = (a + b) + c — associative." },
    ],
    hint: "In (a) one number multiplies each term; in (b) the grouping changes.",
    keyConcepts: ["distributive property", "associative property"],
    conceptsCovered: ["mth:8:ch01:rational-distributivity", "mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Fill in the blanks: (i) Zero has ___ reciprocal. (ii) The numbers 1 and ___ are their own reciprocals.",
    answer: "(i) Zero has NO reciprocal (1/0 is undefined). (ii) The numbers 1 and −1 are their own reciprocals since 1×1 = 1 and (−1)×(−1) = 1.",
    steps: [
      { stepNumber: 1, title: "(i) Zero", explanation: "1/0 is undefined — no reciprocal." },
      { stepNumber: 2, title: "(ii) Self-reciprocal", explanation: "1/1 = 1 and 1/(−1) = −1." },
    ],
    hint: "Reciprocal of x is 1/x.",
    keyConcepts: ["reciprocal", "multiplicative inverse"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Multiply 6/13 by the reciprocal of −7/16.",
    answer: "Reciprocal of −7/16 is −16/7. Product: 6/13 × (−16/7) = −96/91.",
    steps: [
      { stepNumber: 1, title: "Find reciprocal", explanation: "Reciprocal of −7/16 = −16/7." },
      { stepNumber: 2, title: "Multiply", explanation: "6/13 × (−16/7) = (6 × −16)/(13 × 7) = −96/91." },
    ],
    hint: "The reciprocal of a negative number is also negative.",
    keyConcepts: ["reciprocal", "multiplication"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Is 8/9 the multiplicative inverse of −1⅛? Why or why not?",
    answer: "No. −1⅛ = −9/8. Product: 8/9 × (−9/8) = −72/72 = −1 ≠ 1. The product must be +1 for a multiplicative inverse.",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "−1⅛ = −(8/8 + 1/8) = −9/8." },
      { stepNumber: 2, title: "Multiply", explanation: "8/9 × (−9/8) = −1 ≠ 1." },
      { stepNumber: 3, title: "Conclude", explanation: "Since product = −1, not +1, they are NOT multiplicative inverses." },
    ],
    hint: "Multiplicative inverse requires the product to equal +1.",
    keyConcepts: ["multiplicative inverse", "mixed fractions"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Represent 3/5 and −3/5 on a number line.",
    answer: "Divide the segment [0,1] into 5 equal parts. 3/5 is at the 3rd mark to the right of 0. −3/5 is at the 3rd mark to the left of 0 (mirror image).",
    steps: [
      { stepNumber: 1, title: "Divide unit", explanation: "Mark 0 and 1. Divide into 5 equal parts." },
      { stepNumber: 2, title: "Plot 3/5", explanation: "3/5 is 3 marks right of 0." },
      { stepNumber: 3, title: "Plot −3/5", explanation: "−3/5 is 3 marks left of 0." },
    ],
    hint: "Negative rationals are reflected across 0.",
    keyConcepts: ["number line", "representation"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "number-line"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find five rational numbers between 1 and 2.",
    answer: "Write 1 = 6/6 and 2 = 12/6. Five rationals between them: 7/6, 8/6, 9/6, 10/6, 11/6 (simplify: 7/6, 4/3, 3/2, 5/3, 11/6).",
    steps: [
      { stepNumber: 1, title: "Multiply by 6/6", explanation: "1 = 6/6, 2 = 12/6." },
      { stepNumber: 2, title: "List", explanation: "7/6, 8/6, 9/6, 10/6, 11/6." },
      { stepNumber: 3, title: "Simplify", explanation: "8/6 = 4/3; 9/6 = 3/2; 10/6 = 5/3." },
    ],
    hint: "Convert both numbers to equivalent fractions with a larger denominator.",
    keyConcepts: ["density of rationals", "between rationals"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find three rational numbers between −3 and −2.",
    answer: "−3 = −21/7 and −2 = −14/7. Three rationals: −20/7, −18/7, −16/7. Or equivalently: −11/4, −5/2, −9/4.",
    steps: [
      { stepNumber: 1, title: "Use common denominator", explanation: "−3 = −18/6, −2 = −12/6; pick −17/6, −15/6, −13/6." },
      { stepNumber: 2, title: "Simplify", explanation: "−17/6, −5/2, −13/6." },
    ],
    hint: "Convert to equivalent fractions with larger denominators.",
    keyConcepts: ["density of rationals", "negative rationals"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Tell what property allows you to compute: 1/3 × (6 × 4/3) = (1/3 × 6) × 4/3.",
    answer: "Associative property of multiplication: a × (b × c) = (a × b) × c. The grouping of multiplication can be changed without affecting the product.",
    steps: [{ stepNumber: 1, title: "Identify", explanation: "The grouping changes: (1/3)(6)(4/3) is regrouped — associative property." }],
    hint: "Only the brackets change, not the order or the numbers.",
    keyConcepts: ["associative property"],
    conceptsCovered: ["mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "properties"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Rational numbers are closed under which of the following operations?",
    answer: "Addition, subtraction, and multiplication. Rational numbers are closed under +, −, ×, and ÷ (by non-zero). Option D covers the most complete set.",
    options: ["A) Addition only", "B) Addition and subtraction", "C) Addition, subtraction, multiplication", "D) Addition, subtraction, multiplication, and division by non-zero"],
    correctOption: "D",
    steps: [{ stepNumber: 1, title: "Closure", explanation: "Rationals are closed under +, −, ×, and ÷ (non-zero divisor)." }],
    hint: "Think about which operations always give a rational result.",
    keyConcepts: ["closure property"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "closure"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find ten rational numbers between 3/5 and 3/4.",
    answer: "Convert: 3/5 = 48/80 and 3/4 = 60/80. Ten rationals: 49/80, 50/80, 51/80, 52/80, 53/80, 54/80, 55/80, 56/80, 57/80, 58/80.",
    steps: [
      { stepNumber: 1, title: "Find LCM and scale", explanation: "Multiply numerator and denominator by 20: 3/5 = 60/100, 3/4 = 75/100." },
      { stepNumber: 2, title: "List ten", explanation: "61/100, 62/100, …, 70/100." },
    ],
    hint: "Make the gap large enough to fit 10 integers in between.",
    keyConcepts: ["density of rationals"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Simplify using suitable property: 3/5 × (−2/3) + (−3/5) × (−5/6).",
    answer: "Factor: 3/5 × [−2/3 + (−5/6 × (−1))] — actually rearrange: 3/5 × (−2/3) + (−3/5) × (−5/6). Note that −3/5 = −(3/5). Use distributivity: 3/5 × (−2/3) + 3/5 × (5/6) [since (−3/5)(−5/6) = (3/5)(5/6)] = 3/5 × (−2/3 + 5/6) = 3/5 × (−4/6 + 5/6) = 3/5 × 1/6 = 3/30 = 1/10.",
    steps: [
      { stepNumber: 1, title: "Simplify signs", explanation: "(−3/5)(−5/6) = 15/30 = 1/2 = (3/5)(5/6)." },
      { stepNumber: 2, title: "Factor out 3/5", explanation: "3/5 × (−2/3 + 5/6)." },
      { stepNumber: 3, title: "Bracket", explanation: "−2/3 + 5/6 = −4/6 + 5/6 = 1/6." },
      { stepNumber: 4, title: "Multiply", explanation: "3/5 × 1/6 = 1/10." },
    ],
    hint: "Factor out the common rational coefficient.",
    keyConcepts: ["distributivity", "sign rules"],
    conceptsCovered: ["mth:8:ch01:rational-distributivity"],
    prerequisites: [],
    commonErrors: ["Forgetting that negative × negative = positive before factoring."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Is commutativity applicable to: (a) rational number subtraction? (b) rational number division? Justify with examples.",
    answer: "(a) No. 1/2 − 1/3 = 1/6 ≠ −1/6 = 1/3 − 1/2. (b) No. (2/3) ÷ (1/2) = 4/3 ≠ 3/4 = (1/2) ÷ (2/3).",
    steps: [
      { stepNumber: 1, title: "(a) Subtraction", explanation: "a − b ≠ b − a in general." },
      { stepNumber: 2, title: "(b) Division", explanation: "a ÷ b ≠ b ÷ a in general." },
    ],
    hint: "Try a specific pair of unequal fractions.",
    keyConcepts: ["commutativity", "subtraction", "division"],
    conceptsCovered: ["mth:8:ch01:rational-commutativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Verify associativity of addition for: a = 1/2, b = 2/3, c = −1/6.",
    answer: "LHS: (a + b) + c = (1/2 + 2/3) + (−1/6) = (3/6 + 4/6) − 1/6 = 7/6 − 1/6 = 6/6 = 1. RHS: a + (b + c) = 1/2 + (2/3 − 1/6) = 1/2 + (4/6 − 1/6) = 1/2 + 3/6 = 1/2 + 1/2 = 1. LHS = RHS = 1 ✓",
    steps: [
      { stepNumber: 1, title: "Compute a + b", explanation: "1/2 + 2/3 = 3/6 + 4/6 = 7/6." },
      { stepNumber: 2, title: "LHS", explanation: "7/6 + (−1/6) = 6/6 = 1." },
      { stepNumber: 3, title: "Compute b + c", explanation: "2/3 + (−1/6) = 4/6 − 1/6 = 3/6 = 1/2." },
      { stepNumber: 4, title: "RHS", explanation: "1/2 + 1/2 = 1." },
    ],
    hint: "Compute both sides independently.",
    keyConcepts: ["associativity", "addition"],
    conceptsCovered: ["mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "verification"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-017",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Using mean method, find a rational between 1/4 and 1/2.",
    answer: "Mean = (1/4 + 1/2) ÷ 2 = (1/4 + 2/4) ÷ 2 = (3/4) ÷ 2 = 3/8. So 3/8 lies between 1/4 and 1/2.",
    steps: [
      { stepNumber: 1, title: "Add", explanation: "1/4 + 1/2 = 1/4 + 2/4 = 3/4." },
      { stepNumber: 2, title: "Halve", explanation: "3/4 ÷ 2 = 3/8." },
      { stepNumber: 3, title: "Verify", explanation: "1/4 = 2/8 < 3/8 < 4/8 = 1/2. ✓" },
    ],
    hint: "The mean (average) of two numbers lies between them.",
    keyConcepts: ["mean method", "between rationals"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "NCERT-Ex1.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch01-nce-018",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Is rational number multiplication commutative? Give an example.",
    answer: "Yes. For any rationals a and b: a × b = b × a. Example: 2/3 × 4/5 = 8/15 and 4/5 × 2/3 = 8/15. Order does not affect the product.",
    steps: [{ stepNumber: 1, title: "Example", explanation: "2/3 × 4/5 = 4/5 × 2/3 = 8/15." }],
    hint: "Multiplication of rationals, like integers, is commutative.",
    keyConcepts: ["commutativity", "multiplication"],
    conceptsCovered: ["mth:8:ch01:rational-commutativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch01", "commutativity"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch01-ics-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Arrange in ascending order: −5/6, 7/−9, −3/4, 1/−2.",
    answer: "Convert to common denominator 36: −5/6 = −30/36; 7/(−9) = −28/36; −3/4 = −27/36; 1/(−2) = −18/36. Ascending: −30/36 < −28/36 < −27/36 < −18/36, i.e., −5/6 < −7/9 < −3/4 < −1/2.",
    steps: [
      { stepNumber: 1, title: "Standardise signs", explanation: "7/(−9) = −7/9; 1/(−2) = −1/2." },
      { stepNumber: 2, title: "LCD = 36", explanation: "Convert all: −30/36, −28/36, −27/36, −18/36." },
      { stepNumber: 3, title: "Order", explanation: "Smaller numerator → smaller negative fraction." },
    ],
    hint: "For negative fractions, the one with the larger absolute value is smaller.",
    keyConcepts: ["ordering rationals", "common denominator"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch01", "ordering"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch01-ics-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Simplify: [(3/4 × 16/9) − (5/3 ÷ 10/9)] + [(7/2 − 5/4) × 4/9].",
    answer: "Part 1: 3/4 × 16/9 = 48/36 = 4/3; 5/3 ÷ 10/9 = 5/3 × 9/10 = 45/30 = 3/2. 4/3 − 3/2 = 8/6 − 9/6 = −1/6. Part 2: 7/2 − 5/4 = 14/4 − 5/4 = 9/4; 9/4 × 4/9 = 36/36 = 1. Final: −1/6 + 1 = −1/6 + 6/6 = 5/6.",
    steps: [
      { stepNumber: 1, title: "Bracket 1 multiply", explanation: "3/4 × 16/9 = 4/3." },
      { stepNumber: 2, title: "Bracket 1 divide", explanation: "5/3 ÷ 10/9 = 3/2." },
      { stepNumber: 3, title: "Bracket 1 result", explanation: "4/3 − 3/2 = −1/6." },
      { stepNumber: 4, title: "Bracket 2", explanation: "(7/2 − 5/4) × 4/9 = 9/4 × 4/9 = 1." },
      { stepNumber: 5, title: "Sum", explanation: "−1/6 + 1 = 5/6." },
    ],
    hint: "Evaluate each bracket separately following BODMAS.",
    keyConcepts: ["BODMAS", "rational arithmetic"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: ["Forgetting to invert the divisor when dividing fractions.", "Arithmetic sign errors in subtraction."],
    tags: ["ICSE", "class8", "ch01", "BODMAS"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch01-ics-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Find x: 3/4 + x = 5/8.",
    answer: "x = 5/8 − 3/4 = 5/8 − 6/8 = −1/8.",
    steps: [
      { stepNumber: 1, title: "Isolate x", explanation: "x = 5/8 − 3/4." },
      { stepNumber: 2, title: "Common denominator", explanation: "3/4 = 6/8." },
      { stepNumber: 3, title: "Subtract", explanation: "5/8 − 6/8 = −1/8." },
    ],
    hint: "Transpose 3/4 to the other side.",
    keyConcepts: ["linear equation", "transposition"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch01", "equation"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch01-ics-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Insert three rational numbers between −2 and −1 using the formula method.",
    answer: "Formula: between a and b, use (a + b)/2 repeatedly or equivalent fractions. −2 = −8/4, −1 = −4/4. Three rationals: −7/4, −6/4 = −3/2, −5/4.",
    steps: [
      { stepNumber: 1, title: "Equivalent fractions", explanation: "−2 = −8/4, −1 = −4/4." },
      { stepNumber: 2, title: "Insert", explanation: "−7/4, −6/4, −5/4." },
    ],
    hint: "Multiply denominator to create space for insertions.",
    keyConcepts: ["inserting rationals", "density"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch01", "density"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch01-ics-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Show that rational numbers are dense but integers are not dense (i.e., there is always a rational between two rationals, but not always an integer between two integers).",
    answer: "Density of rationals: between any two rationals p/q and r/s (p/q < r/s), the mean (p/q + r/s)/2 is always a rational between them. Integers not dense: between 1 and 2 there is no integer. Between 2 and 3 there is no integer. The mean of 1 and 2 is 3/2 = 1.5, which is NOT an integer.",
    steps: [
      { stepNumber: 1, title: "Rationals are dense", explanation: "Average of two rationals is always rational and lies between them." },
      { stepNumber: 2, title: "Integers not dense", explanation: "No integer exists between 1 and 2 (next integer after 1 is 2, adjacent)." },
    ],
    hint: "Use the mean of two numbers to show density.",
    keyConcepts: ["density", "integers vs rationals"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: ["Confusing dense with infinite — integers are also infinite but not dense."],
    tags: ["ICSE", "class8", "ch01", "density"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch01-ics-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Evaluate: (2/3 + 1/4) ÷ (2/3 − 1/4).",
    answer: "Numerator: 2/3 + 1/4 = 8/12 + 3/12 = 11/12. Denominator: 2/3 − 1/4 = 8/12 − 3/12 = 5/12. Result: (11/12) ÷ (5/12) = 11/12 × 12/5 = 11/5 = 2⅕.",
    steps: [
      { stepNumber: 1, title: "Numerator", explanation: "8/12 + 3/12 = 11/12." },
      { stepNumber: 2, title: "Denominator", explanation: "8/12 − 3/12 = 5/12." },
      { stepNumber: 3, title: "Divide", explanation: "11/12 × 12/5 = 11/5." },
    ],
    hint: "Compute numerator and denominator of the complex fraction separately.",
    keyConcepts: ["complex fractions", "BODMAS"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch01", "complex-fractions"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch01-ics-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Represent −7/4 on a number line and state between which two integers it lies.",
    answer: "−7/4 = −1¾. It lies between −2 and −1 on the number line, closer to −2. Divide the segment [−2, −1] into 4 equal parts; −7/4 is at the 3rd mark from −2 (or 1st mark from −2).",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "−7/4 = −1 remainder 3, so −1¾." },
      { stepNumber: 2, title: "Locate", explanation: "Between −2 and −1; divide into 4 parts, mark at 3rd division from left (−2)." },
    ],
    hint: "Convert improper fraction to mixed number first.",
    keyConcepts: ["number line", "mixed numbers"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch01", "number-line"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch01-cmp-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "A baker uses 3/4 kg of sugar for one cake. How much sugar is needed for 8 cakes?",
    answer: "6 kg. 3/4 × 8 = 24/4 = 6 kg.",
    options: ["A) 5 kg", "B) 6 kg", "C) 7 kg", "D) 8 kg"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Multiply", explanation: "3/4 × 8 = 24/4 = 6." }],
    hint: "Multiply the fraction by the number of cakes.",
    keyConcepts: ["fraction multiplication", "real-world application"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A tank is 2/3 full. After adding 1/6 of its capacity, what fraction of the tank is now full?",
    answer: "2/3 + 1/6 = 4/6 + 1/6 = 5/6 of the tank is full.",
    steps: [
      { stepNumber: 1, title: "Common denominator", explanation: "2/3 = 4/6." },
      { stepNumber: 2, title: "Add", explanation: "4/6 + 1/6 = 5/6." },
    ],
    hint: "Add the two fractions using a common denominator.",
    keyConcepts: ["fraction addition", "real-world context"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A rope of length 7/2 m is cut into pieces of 1/4 m each. How many pieces are there?",
    answer: "Number of pieces = 7/2 ÷ 1/4 = 7/2 × 4 = 28/2 = 14 pieces.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "7/2 ÷ 1/4 = 7/2 × 4/1 = 28/2 = 14." },
    ],
    hint: "Dividing by a fraction is the same as multiplying by its reciprocal.",
    keyConcepts: ["fraction division", "real-world"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "division"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Riya ran 3/4 km. Siya ran 5/8 km. How much more did Riya run?",
    answer: "1/8 km. 3/4 − 5/8 = 6/8 − 5/8 = 1/8.",
    options: ["A) 1/4 km", "B) 1/8 km", "C) 2/8 km", "D) 1/2 km"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Subtract", explanation: "6/8 − 5/8 = 1/8." }],
    hint: "Convert to common denominator 8 first.",
    keyConcepts: ["fraction subtraction"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "subtraction"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A temperature reading is −3/2 °C. Express this as a mixed number and mark it on a number line.",
    answer: "−3/2 = −1½ °C. On the number line, it lies between −2 and −1, exactly halfway between them (since the denominator is 2).",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "3 ÷ 2 = 1 remainder 1, so −1½." },
      { stepNumber: 2, title: "Locate", explanation: "Between −2 and −1; divide segment into 2 parts; mark at midpoint." },
    ],
    hint: "Mixed number shows which integers it's between.",
    keyConcepts: ["mixed numbers", "number line", "negative rationals"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A field is 5/3 hectares. It is divided equally among 5 farmers. What does each farmer get?",
    answer: "Each farmer gets 5/3 ÷ 5 = 5/3 × 1/5 = 5/15 = 1/3 hectare.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "5/3 ÷ 5 = 5/3 × 1/5 = 5/15 = 1/3." },
    ],
    hint: "Dividing by a whole number: multiply by its reciprocal.",
    keyConcepts: ["fraction division", "equal sharing"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Two students, Aarav and Priya, each claim a different rational number is between 1/3 and 1/2. Aarav says 2/5 and Priya says 5/12. Are both correct?",
    answer: "Check: 1/3 = 4/12, 1/2 = 6/12. Priya's 5/12: 4/12 < 5/12 < 6/12 ✓. Aarav's 2/5: 1/3 = 10/30, 2/5 = 12/30, 1/2 = 15/30. 10/30 < 12/30 < 15/30 ✓. Both are correct!",
    steps: [
      { stepNumber: 1, title: "Check 5/12", explanation: "1/3 = 4/12 < 5/12 < 6/12 = 1/2 ✓." },
      { stepNumber: 2, title: "Check 2/5", explanation: "1/3 ≈ 0.333 < 2/5 = 0.4 < 0.5 = 1/2 ✓." },
      { stepNumber: 3, title: "Conclude", explanation: "Both 5/12 and 2/5 lie between 1/3 and 1/2." },
    ],
    hint: "Convert all to a common denominator to compare.",
    keyConcepts: ["ordering rationals", "density"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "reasoning"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What fraction of a day is 8 hours? Write your answer in standard form.",
    answer: "8/24 = 1/3. One-third of a day is 8 hours.",
    steps: [
      { stepNumber: 1, title: "Set up fraction", explanation: "8 hours out of 24 hours = 8/24." },
      { stepNumber: 2, title: "Simplify", explanation: "GCF of 8 and 24 is 8; 8/24 = 1/3." },
    ],
    hint: "A day has 24 hours.",
    keyConcepts: ["fraction of a quantity", "simplification"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A student multiplies two fractions and gets 1/4. One fraction is 3/8. What is the other? Is the other fraction rational?",
    answer: "Let other fraction = x. 3/8 × x = 1/4 ⟹ x = 1/4 ÷ 3/8 = 1/4 × 8/3 = 8/12 = 2/3. Yes, 2/3 is rational since it is of the form p/q with p=2, q=3 (non-zero integers).",
    steps: [
      { stepNumber: 1, title: "Set up equation", explanation: "3/8 × x = 1/4." },
      { stepNumber: 2, title: "Solve", explanation: "x = 1/4 × 8/3 = 2/3." },
      { stepNumber: 3, title: "Verify rationality", explanation: "2/3: integers 2 and 3, 3 ≠ 0, so rational." },
    ],
    hint: "Divide both sides by 3/8 (same as multiplying by 8/3).",
    keyConcepts: ["inverse operation", "rational number definition"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: ["Confusing multiplication inverse with additive inverse."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "reasoning"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "On a number line, point A is at 2/3 and point B is at 5/6. Find the point exactly midway between A and B.",
    answer: "Midpoint = (2/3 + 5/6) ÷ 2 = (4/6 + 5/6) ÷ 2 = 9/6 ÷ 2 = 9/12 = 3/4.",
    steps: [
      { stepNumber: 1, title: "Add", explanation: "2/3 + 5/6 = 4/6 + 5/6 = 9/6." },
      { stepNumber: 2, title: "Halve", explanation: "9/6 ÷ 2 = 9/12 = 3/4." },
    ],
    hint: "Midpoint = average of the two values.",
    keyConcepts: ["midpoint", "number line"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "number-line"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "If a recipe uses 2/3 cup of oil for 4 servings, how much oil is needed for 10 servings?",
    answer: "Oil per serving = 2/3 ÷ 4 = 2/12 = 1/6 cup. For 10 servings: 1/6 × 10 = 10/6 = 5/3 = 1⅔ cups.",
    steps: [
      { stepNumber: 1, title: "Per serving", explanation: "2/3 ÷ 4 = 2/12 = 1/6." },
      { stepNumber: 2, title: "For 10", explanation: "1/6 × 10 = 10/6 = 5/3 cups." },
    ],
    hint: "Find oil per serving first, then scale up.",
    keyConcepts: ["proportional reasoning", "fraction operations"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "proportional-reasoning"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which expression equals 3/4?",
    answer: "9/12 = 3/4. Option B.",
    options: ["A) 6/10", "B) 9/12", "C) 4/6", "D) 5/8"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Simplify each", explanation: "9/12: GCF=3; 9/12 = 3/4 ✓." }],
    hint: "Simplify each option to lowest terms.",
    keyConcepts: ["equivalent fractions", "simplification"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "equivalent-fractions"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A drain pipe removes 3/8 of a tank's water in one hour. How many hours to drain 3/4 of the tank?",
    answer: "Hours = (3/4) ÷ (3/8) = 3/4 × 8/3 = 24/12 = 2 hours.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Amount to drain ÷ rate per hour." },
      { stepNumber: 2, title: "Divide", explanation: "3/4 ÷ 3/8 = 3/4 × 8/3 = 2." },
    ],
    hint: "Time = Amount ÷ Rate.",
    keyConcepts: ["fraction division", "rate problems"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "rate"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Is −5/3 closer to −2 or −1? Justify using the number line.",
    answer: "−5/3 ≈ −1.667. Distance from −2: |−5/3 − (−2)| = |1/3| = 1/3. Distance from −1: |−5/3 − (−1)| = |−2/3| = 2/3. Since 1/3 < 2/3, it is closer to −2.",
    steps: [
      { stepNumber: 1, title: "Distance from −2", explanation: "−5/3 + 2 = −5/3 + 6/3 = 1/3." },
      { stepNumber: 2, title: "Distance from −1", explanation: "−5/3 + 1 = −5/3 + 3/3 = −2/3, absolute value 2/3." },
      { stepNumber: 3, title: "Compare", explanation: "1/3 < 2/3 → closer to −2." },
    ],
    hint: "Distance on number line = absolute value of difference.",
    keyConcepts: ["number line distance", "negative rationals"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "number-line"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Priya says: 'If I multiply any rational number by itself, the result is always positive.' Is she correct?",
    answer: "Not always. If the rational number is 0, then 0 × 0 = 0, which is neither positive nor negative. For any non-zero rational: positive × positive = positive, and negative × negative = positive. So Priya is almost correct — 0 is the exception.",
    steps: [
      { stepNumber: 1, title: "Non-zero positive", explanation: "(a/b)² > 0 for any a/b > 0." },
      { stepNumber: 2, title: "Non-zero negative", explanation: "(−a/b) × (−a/b) = a²/b² > 0." },
      { stepNumber: 3, title: "Zero", explanation: "0 × 0 = 0 (not positive)." },
    ],
    hint: "Don't forget zero is a rational number.",
    keyConcepts: ["square of rationals", "sign rules"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: ["Forgetting to check the special case of zero."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "reasoning"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch01-cmp-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A swimming pool is being filled at a rate of 5/6 m³ per hour. How much water enters in 3/4 of an hour?",
    answer: "Volume = rate × time = 5/6 × 3/4 = 15/24 = 5/8 m³.",
    steps: [{ stepNumber: 1, title: "Multiply", explanation: "5/6 × 3/4 = 15/24 = 5/8 m³." }],
    hint: "Volume = rate × time.",
    keyConcepts: ["fraction multiplication", "rate × time"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch01", "real-world"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch01-hot-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove that the sum of a rational number and its additive inverse is always 0, and the product of a non-zero rational number and its multiplicative inverse is always 1.",
    answer: "Part 1: Let r = p/q. Additive inverse = −p/q. Sum: p/q + (−p/q) = (p − p)/q = 0/q = 0. ✓ Part 2: Let r = p/q ≠ 0. Multiplicative inverse = q/p. Product: p/q × q/p = pq/pq = 1. ✓",
    steps: [
      { stepNumber: 1, title: "General rational", explanation: "Let r = p/q where p, q ∈ ℤ, q ≠ 0." },
      { stepNumber: 2, title: "Additive inverse sum", explanation: "p/q + (−p/q) = 0/q = 0." },
      { stepNumber: 3, title: "Multiplicative inverse product", explanation: "p/q × q/p = pq/pq = 1 (since p ≠ 0)." },
    ],
    hint: "Use algebraic form p/q to prove generally.",
    keyConcepts: ["additive inverse", "multiplicative inverse", "proof"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: ["Not starting with the general form p/q — specific examples don't constitute a proof."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "How many rational numbers exist between 1/5 and 2/5? Explain theoretically and provide 5 examples.",
    answer: "Infinitely many rational numbers exist between any two distinct rationals (density property). Theoretical argument: given p/q < r/s, their mean (p/q + r/s)/2 is always rational and lies between them. Repeating this process gives infinitely many. Examples between 1/5 = 2/10 and 2/5 = 4/10: 3/10, 21/100, 22/100, 7/30, 11/50.",
    steps: [
      { stepNumber: 1, title: "Density theorem", explanation: "Between any two rationals, the mean is a new rational between them." },
      { stepNumber: 2, title: "Infinitely many", explanation: "This process never terminates, so infinitely many rationals exist." },
      { stepNumber: 3, title: "Examples", explanation: "1/5 = 20/100, 2/5 = 40/100. Between: 21/100, 25/100=1/4, 30/100=3/10, 35/100=7/20, 39/100." },
    ],
    hint: "The density of rationals means the mean is always between — and this can be repeated forever.",
    keyConcepts: ["density of rationals", "infinite set"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: ["Thinking only finitely many fit because the interval looks small."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "density"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Is the set of rational numbers closed under the operation a ★ b = (a + b)/2? Justify.",
    answer: "Yes. If a and b are rational (a = p/q, b = r/s), then a + b = (ps + qr)/(qs), which is rational. Dividing by 2: (ps + qr)/(2qs), which is still rational since all parts are integers and 2qs ≠ 0. So a ★ b is always rational — closed under ★.",
    steps: [
      { stepNumber: 1, title: "Express generally", explanation: "a = p/q, b = r/s; a + b = (ps+qr)/qs." },
      { stepNumber: 2, title: "Apply operation", explanation: "a ★ b = (ps+qr)/(2qs)." },
      { stepNumber: 3, title: "Is it rational?", explanation: "Numerator and denominator are integers, denominator ≠ 0. Yes, rational." },
    ],
    hint: "Write a and b in p/q form and carry through the operation.",
    keyConcepts: ["closure", "custom operations"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: ["Checking only one example instead of proving generally."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "closure-extension"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If p + q = 0 for rationals p and q, what can you say about their relationship? If p × q = 1, what can you say?",
    answer: "If p + q = 0, then q = −p, meaning q is the additive inverse of p. If p × q = 1, then q = 1/p (p ≠ 0), meaning q is the multiplicative inverse (reciprocal) of p.",
    steps: [
      { stepNumber: 1, title: "Sum = 0", explanation: "p + q = 0 ⟹ q = −p (additive inverses)." },
      { stepNumber: 2, title: "Product = 1", explanation: "p × q = 1 ⟹ q = 1/p (multiplicative inverses)." },
    ],
    hint: "Recall the definitions of additive and multiplicative inverses.",
    keyConcepts: ["additive inverse", "multiplicative inverse"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "inverse-analysis"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Create a real-life scenario where the associative property of multiplication of rational numbers is practically useful. Solve it.",
    answer: "Scenario: A factory produces fabric. Each machine covers 3/4 m² per minute. There are 2/3 as many machines as workers, and 12 workers. How much fabric per minute? Using associative property: (3/4 × 2/3) × 12 = 1/2 × 12 = 6 m²/min. Or: 3/4 × (2/3 × 12) = 3/4 × 8 = 6 m²/min. Both groupings give 6 m²/min, demonstrating associativity simplifies computation.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Rate × machines-per-worker × workers = total rate." },
      { stepNumber: 2, title: "Grouping 1", explanation: "(3/4 × 2/3) × 12 = 1/2 × 12 = 6." },
      { stepNumber: 3, title: "Grouping 2", explanation: "3/4 × (2/3 × 12) = 3/4 × 8 = 6." },
    ],
    hint: "Think of multi-step rate or scaling problems.",
    keyConcepts: ["associativity", "real-world application"],
    conceptsCovered: ["mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: ["Choosing a scenario where grouping actually doesn't matter for the student to see why it's useful."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "create"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "For what value of x is 1/(x − 3) not a rational number? Why?",
    answer: "When x = 3, the expression becomes 1/0, which is undefined (division by zero is not allowed). So 1/(x − 3) is not a rational number (or any number at all) when x = 3.",
    steps: [
      { stepNumber: 1, title: "Condition for rational", explanation: "p/q is rational only when q ≠ 0." },
      { stepNumber: 2, title: "Find when denominator = 0", explanation: "x − 3 = 0 ⟹ x = 3." },
    ],
    hint: "A rational number requires a non-zero denominator.",
    keyConcepts: ["undefined fractions", "denominator = 0"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: ["Saying the expression is zero, not undefined."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "undefined"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Arrange −4/5, 3/−7, −2/3 in descending order without converting to decimals.",
    answer: "Find LCD of 5, 7, 3 = 105. −4/5 = −84/105; −3/7 = −45/105; −2/3 = −70/105. Descending (largest first): −45/105 > −70/105 > −84/105, i.e., −3/7 > −2/3 > −4/5.",
    steps: [
      { stepNumber: 1, title: "Standardise signs", explanation: "3/(−7) = −3/7." },
      { stepNumber: 2, title: "LCD = 105", explanation: "−4/5 = −84/105; −3/7 = −45/105; −2/3 = −70/105." },
      { stepNumber: 3, title: "Order", explanation: "−45 > −70 > −84, so descending: −3/7, −2/3, −4/5." },
    ],
    hint: "Convert to common denominator; for negatives, less negative = larger.",
    keyConcepts: ["ordering negative rationals", "common denominator"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: ["Reversing the order for negative numbers — more negative = smaller."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "ordering"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If p/q and r/s are two rational numbers with ps > qr, which is larger? Justify.",
    answer: "Compare p/q and r/s with positive denominators q, s > 0. p/q > r/s ⟺ ps > qr (cross multiplication, valid since q, s > 0). So p/q is larger when ps > qr.",
    steps: [
      { stepNumber: 1, title: "Cross-multiply", explanation: "p/q compared with r/s: multiply both sides by qs (positive)." },
      { stepNumber: 2, title: "Conclusion", explanation: "p/q > r/s iff ps > qr." },
    ],
    hint: "Cross-multiplication rule for comparing fractions works when denominators are positive.",
    keyConcepts: ["comparing fractions", "cross multiplication"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: ["Cross multiplication reverses if denominators are negative — must ensure positive denominators."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "comparison-proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "A student claims: 'Subtraction of rational numbers is associative because (a − b) − c = a − (b − c)'. Disprove this with a counterexample.",
    answer: "Let a = 1, b = 1/2, c = 1/4. LHS: (1 − 1/2) − 1/4 = 1/2 − 1/4 = 1/4. RHS: 1 − (1/2 − 1/4) = 1 − 1/4 = 3/4. 1/4 ≠ 3/4. The claim is false; subtraction is NOT associative.",
    steps: [
      { stepNumber: 1, title: "Choose values", explanation: "a=1, b=1/2, c=1/4." },
      { stepNumber: 2, title: "LHS", explanation: "(1 − 1/2) − 1/4 = 1/2 − 1/4 = 1/4." },
      { stepNumber: 3, title: "RHS", explanation: "1 − (1/2 − 1/4) = 1 − 1/4 = 3/4." },
      { stepNumber: 4, title: "Conclude", explanation: "1/4 ≠ 3/4 → not associative." },
    ],
    hint: "One counterexample is enough to disprove a general claim.",
    keyConcepts: ["associativity", "counterexample", "subtraction"],
    conceptsCovered: ["mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: ["Trying to prove by algebra instead of using a concrete counterexample."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "disprove"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch01-hot-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Design a table summarising all four properties (closure, commutativity, associativity, distributivity) for all four operations (+, −, ×, ÷) on rational numbers. Mark each cell ✓ or ✗ with one justification.",
    answer: "Table: Closure: +✓, −✓, ×✓, ÷✓(non-zero). Commutativity: +✓, −✗(1−2≠2−1), ×✓, ÷✗(4÷2≠2÷4). Associativity: +✓, −✗((1−2)−3≠1−(2−3)), ×✓, ÷✗((8÷4)÷2≠8÷(4÷2)). Distributivity: × over + ✓ and × over − ✓.",
    steps: [
      { stepNumber: 1, title: "Closure", explanation: "All ops closed (÷ requires non-zero divisor)." },
      { stepNumber: 2, title: "Commutativity", explanation: "+ and × only." },
      { stepNumber: 3, title: "Associativity", explanation: "+ and × only." },
      { stepNumber: 4, title: "Distributivity", explanation: "× distributes over + and −." },
    ],
    hint: "For each ✗, provide a specific numerical counterexample.",
    keyConcepts: ["properties summary", "all four operations"],
    conceptsCovered: ["mth:8:ch01:rational-closure", "mth:8:ch01:rational-commutativity", "mth:8:ch01:rational-associativity", "mth:8:ch01:rational-distributivity"],
    prerequisites: [],
    commonErrors: ["Marking ÷ as non-closed without adding the non-zero divisor caveat."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch01", "summary-table"],
    source: "hots",
  },

  // ── PREVIOUS-YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch01-pyq-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The rational number that is equal to its own additive inverse is:",
    answer: "0. The additive inverse of 0 is −0 = 0 itself.",
    options: ["A) 1", "B) −1", "C) 0", "D) 1/2"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Check", explanation: "0 + 0 = 0; additive inverse of 0 is 0." }],
    hint: "Which number equals its own negative?",
    keyConcepts: ["additive inverse", "zero"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the value of: 2/3 − 3/4 + 5/6.",
    answer: "LCD = 12: 8/12 − 9/12 + 10/12 = 9/12 = 3/4.",
    steps: [
      { stepNumber: 1, title: "LCD = 12", explanation: "2/3=8/12; 3/4=9/12; 5/6=10/12." },
      { stepNumber: 2, title: "Compute", explanation: "8 − 9 + 10 = 9. Result: 9/12 = 3/4." },
    ],
    hint: "Find LCM of 3, 4, 6 = 12.",
    keyConcepts: ["rational arithmetic", "LCD"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State which property is illustrated: 2/7 × (3/5 × 4/9) = (2/7 × 3/5) × 4/9.",
    answer: "Associative property of multiplication of rational numbers. The grouping of the factors changes but the product remains the same.",
    steps: [{ stepNumber: 1, title: "Identify", explanation: "Only the brackets change → associative property." }],
    hint: "What changes between the two sides?",
    keyConcepts: ["associativity", "multiplication"],
    conceptsCovered: ["mth:8:ch01:rational-associativity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find two rational numbers between −1/2 and 1/2.",
    answer: "−1/2 = −2/4 and 1/2 = 2/4. Two rationals: 0 (= 0/4) and 1/4 (between 0 and 2/4).",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "−1/2 = −2/4, 1/2 = 2/4." },
      { stepNumber: 2, title: "Pick two", explanation: "0 and 1/4 both satisfy −1/2 < 0 < 1/4 < 1/2." },
    ],
    hint: "Zero always lies between −1/2 and 1/2.",
    keyConcepts: ["between rationals", "number line"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simplify: −3/4 × 8/9 + 5/4 × 2/3.",
    answer: "First terms: −3/4 × 8/9 = −24/36 = −2/3. Second term: 5/4 × 2/3 = 10/12 = 5/6. Sum: −2/3 + 5/6 = −4/6 + 5/6 = 1/6.",
    steps: [
      { stepNumber: 1, title: "Multiply", explanation: "−3/4 × 8/9 = −2/3; 5/4 × 2/3 = 5/6." },
      { stepNumber: 2, title: "Add", explanation: "−4/6 + 5/6 = 1/6." },
    ],
    hint: "Multiply each pair first, then add the results.",
    keyConcepts: ["rational arithmetic", "BODMAS"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The reciprocal of a negative rational number is:",
    answer: "Negative. The reciprocal of p/q is q/p; if p/q < 0, then q/p also < 0.",
    options: ["A) Always positive", "B) Always negative", "C) Sometimes positive", "D) Zero"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Sign of reciprocal", explanation: "Reciprocal of −a/b is −b/a < 0." }],
    hint: "Reciprocal flips the fraction but keeps the sign.",
    keyConcepts: ["reciprocal", "sign"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find: 4/7 × (−3/8) − 1/2 × (−4/7) + 3/7 × 1/4.",
    answer: "Factor 1/7 from all terms: (1/7)[4 × (−3/8) − 1/2 × (−4) + 3 × 1/4]. Wait, let me compute directly: 4/7×(−3/8) = −12/56 = −3/14; (−1/2)×(−4/7) = 4/14 = 2/7; 3/7×1/4 = 3/28. Sum: −3/14 + 2/7 + 3/28 = −6/28 + 8/28 + 3/28 = 5/28.",
    steps: [
      { stepNumber: 1, title: "Term 1", explanation: "4/7 × (−3/8) = −12/56 = −3/14 = −6/28." },
      { stepNumber: 2, title: "Term 2", explanation: "−1/2 × (−4/7) = 4/14 = 2/7 = 8/28." },
      { stepNumber: 3, title: "Term 3", explanation: "3/7 × 1/4 = 3/28." },
      { stepNumber: 4, title: "Sum", explanation: "−6/28 + 8/28 + 3/28 = 5/28." },
    ],
    hint: "Convert all fractions to LCD = 28 at the end.",
    keyConcepts: ["rational arithmetic", "combined operations"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write the rational number equivalent to 3/5 with denominator 40.",
    answer: "3/5 = 3×8 / 5×8 = 24/40.",
    steps: [{ stepNumber: 1, title: "Scale up", explanation: "40 ÷ 5 = 8; multiply both by 8: 24/40." }],
    hint: "Find what to multiply 5 by to get 40.",
    keyConcepts: ["equivalent fractions"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t2", topicName: "Rational Numbers on Number Line",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Mark 5/3 on a number line and identify between which two consecutive integers it lies.",
    answer: "5/3 ≈ 1.67. It lies between 1 and 2. Divide [1, 2] into 3 equal parts; 5/3 is at the 2nd mark from 1 (i.e., at the mark corresponding to 2/3 of the way from 1 to 2).",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "5/3 = 1 remainder 2 → 1⅔, between 1 and 2." },
      { stepNumber: 2, title: "Mark", explanation: "Divide [1,2] into 3 parts; go 2 parts from 1." },
    ],
    hint: "Convert improper fraction to mixed number.",
    keyConcepts: ["number line", "improper fraction"],
    conceptsCovered: ["mth:8:ch01:density-of-rationals"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Is −3/7 rational? Write its standard form.",
    answer: "Yes, −3/7 is rational (p = −3, q = 7, both integers, q ≠ 0). Standard form: denominator positive, numerator and denominator have no common factor. −3/7 is already in standard form.",
    steps: [
      { stepNumber: 1, title: "Check definition", explanation: "−3/7: p=−3, q=7, GCF(3,7)=1, q>0. Standard form already." },
    ],
    hint: "Standard form: denominator positive, fraction in lowest terms.",
    keyConcepts: ["standard form", "rational definition"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which of the following is NOT a property of rational number multiplication?",
    answer: "Option C: Division by zero gives a rational number — this is NOT a property since division by zero is undefined.",
    options: ["A) Closure", "B) Commutativity", "C) Division by zero gives a rational", "D) Associativity"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Identify false property", explanation: "Division by zero is undefined — not a property." }],
    hint: "Which option describes something impossible?",
    keyConcepts: ["properties of rationals", "undefined operations"],
    conceptsCovered: ["mth:8:ch01:rational-closure"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch01-pyq-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch01", chapterName: "Rational Numbers",
    topicId: "t1", topicName: "Properties of Rational Numbers",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Using the distributive property, simplify: 4/5 × 3/7 − 4/5 × 2/7 + 4/5 × 6/7.",
    answer: "Factor out 4/5: 4/5 × (3/7 − 2/7 + 6/7) = 4/5 × 7/7 = 4/5 × 1 = 4/5.",
    steps: [
      { stepNumber: 1, title: "Factor", explanation: "4/5 is common: 4/5 × (3/7 − 2/7 + 6/7)." },
      { stepNumber: 2, title: "Bracket", explanation: "3/7 − 2/7 + 6/7 = 7/7 = 1." },
      { stepNumber: 3, title: "Multiply", explanation: "4/5 × 1 = 4/5." },
    ],
    hint: "Factor out the common factor before adding/subtracting the fractions.",
    keyConcepts: ["distributivity", "simplification"],
    conceptsCovered: ["mth:8:ch01:rational-distributivity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch01", "PYQ"],
    source: "previous-year",
  },
];
