// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 8, Chapter 2: Linear Equations in One Variable
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Solving Linear Equations        — 25 q
 *   t2 Equations with Variable on Both Sides — 25 q
 *   t3 Word Problems                   — 25 q
 *
 * Concept nodes:
 *   mth:8:ch02:balance-method
 *   mth:8:ch02:transposition
 *   mth:8:ch02:equations-with-fractions
 *   mth:8:ch02:variable-both-sides
 *   mth:8:ch02:age-problems
 *   mth:8:ch02:number-problems
 *   mth:8:ch02:geometry-equations
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH02_LINEAR_EQUATIONS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Solving Linear Equations
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch02-con-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: A linear equation in one variable has exactly one solution.",
    answer: "True. A linear equation of the form ax + b = 0 (a ≠ 0) has exactly one solution: x = −b/a.",
    steps: [{ stepNumber: 1, title: "Definition", explanation: "ax + b = 0 has unique solution x = −b/a." }],
    hint: "Linear means the variable is raised to the power 1.",
    keyConcepts: ["linear equation", "unique solution"],
    conceptsCovered: ["mth:8:ch02:balance-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "definition"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: x + 5 = 12.",
    answer: "x = 12 − 5 = 7. Verification: 7 + 5 = 12 ✓",
    steps: [
      { stepNumber: 1, title: "Transpose 5", explanation: "x = 12 − 5 = 7." },
      { stepNumber: 2, title: "Verify", explanation: "7 + 5 = 12 ✓." },
    ],
    hint: "Move 5 to the other side with opposite sign.",
    keyConcepts: ["transposition", "simple equation"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "basic-solve"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: 3x = 21.",
    answer: "x = 21 ÷ 3 = 7.",
    steps: [{ stepNumber: 1, title: "Divide both sides by 3", explanation: "x = 21/3 = 7." }],
    hint: "Divide both sides by the coefficient of x.",
    keyConcepts: ["coefficient division"],
    conceptsCovered: ["mth:8:ch02:balance-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "basic-solve"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: 2x − 7 = 11.",
    answer: "2x = 11 + 7 = 18; x = 9. Verification: 2(9) − 7 = 18 − 7 = 11 ✓",
    steps: [
      { stepNumber: 1, title: "Transpose −7", explanation: "2x = 11 + 7 = 18." },
      { stepNumber: 2, title: "Divide by 2", explanation: "x = 18/2 = 9." },
    ],
    hint: "Transpose the constant first, then divide by the coefficient.",
    keyConcepts: ["two-step equation", "transposition"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "two-step"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: x/4 + 1/2 = 3/4.",
    answer: "x/4 = 3/4 − 1/2 = 3/4 − 2/4 = 1/4. So x = 1/4 × 4 = 1.",
    steps: [
      { stepNumber: 1, title: "Transpose 1/2", explanation: "x/4 = 3/4 − 2/4 = 1/4." },
      { stepNumber: 2, title: "Multiply both sides by 4", explanation: "x = 1." },
    ],
    hint: "Move the constant to one side, then multiply by 4.",
    keyConcepts: ["equations with fractions"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "fractions"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is the solution of 5(x − 2) = 15?",
    answer: "x = 5. 5(x − 2) = 15 ⟹ x − 2 = 3 ⟹ x = 5.",
    options: ["A) 1", "B) 3", "C) 5", "D) 7"],
    correctOption: "C",
    steps: [
      { stepNumber: 1, title: "Divide by 5", explanation: "x − 2 = 3." },
      { stepNumber: 2, title: "Transpose", explanation: "x = 5." },
    ],
    hint: "Divide both sides by 5 first.",
    keyConcepts: ["bracket equations", "transposition"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "brackets"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "medium", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Adding the same number to both sides of an equation keeps the equation balanced.",
    answer: "True. This is the balance method: if a = b, then a + c = b + c for any number c.",
    steps: [{ stepNumber: 1, title: "Balance method", explanation: "Adding equals to both sides preserves equality." }],
    hint: "Think of a balanced weighing scale.",
    keyConcepts: ["balance method", "equality"],
    conceptsCovered: ["mth:8:ch02:balance-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "balance"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Solve: 3x + 4 = 2x + 9.",
    answer: "3x − 2x = 9 − 4; x = 5. Verification: 3(5) + 4 = 19 = 2(5) + 9 = 19 ✓",
    steps: [
      { stepNumber: 1, title: "Collect x terms", explanation: "3x − 2x = 9 − 4." },
      { stepNumber: 2, title: "Simplify", explanation: "x = 5." },
    ],
    hint: "Move all x terms to one side and constants to the other.",
    keyConcepts: ["variable on both sides"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "both-sides"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Solve: 5(2x − 3) = 3(3x − 1).",
    answer: "10x − 15 = 9x − 3. 10x − 9x = −3 + 15 = 12. x = 12.",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "10x − 15 = 9x − 3." },
      { stepNumber: 2, title: "Collect", explanation: "x = −3 + 15 = 12." },
    ],
    hint: "Expand brackets first, then collect variable terms.",
    keyConcepts: ["expanding brackets", "collecting terms"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "brackets-both-sides"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Five times a number is 15 more than twice the number. Find the number.",
    answer: "Let number = x. 5x = 2x + 15. 3x = 15. x = 5.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "5x = 2x + 15." },
      { stepNumber: 2, title: "Solve", explanation: "3x = 15, x = 5." },
    ],
    hint: "Let the number be x and translate the statement into an equation.",
    keyConcepts: ["word problems", "equation setup"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "word-problem"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The angles of a triangle are in ratio 2:3:4. Find each angle.",
    answer: "Let angles be 2k, 3k, 4k. Sum = 180°: 2k + 3k + 4k = 180 ⟹ 9k = 180 ⟹ k = 20. Angles: 40°, 60°, 80°.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "2k + 3k + 4k = 180." },
      { stepNumber: 2, title: "Solve", explanation: "9k = 180, k = 20." },
      { stepNumber: 3, title: "Angles", explanation: "40°, 60°, 80°." },
    ],
    hint: "Sum of angles in a triangle = 180°.",
    keyConcepts: ["geometry equations", "angle sum"],
    conceptsCovered: ["mth:8:ch02:geometry-equations"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "geometry"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch02-con-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If 2(x + 3) = 4(x − 1), then x equals:",
    answer: "x = 5. 2x + 6 = 4x − 4 ⟹ 10 = 2x ⟹ x = 5.",
    options: ["A) 3", "B) 4", "C) 5", "D) 6"],
    correctOption: "C",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "2x + 6 = 4x − 4." },
      { stepNumber: 2, title: "Solve", explanation: "10 = 2x, x = 5." },
    ],
    hint: "Expand both brackets then collect terms.",
    keyConcepts: ["bracket equations"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: ["Expanding −4 as +4 on the right side."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "MCQ"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch02-nce-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: (3x)/4 − 1 = (x/4) + 1.",
    answer: "(3x)/4 − x/4 = 1 + 1 = 2. 2x/4 = 2. x/2 = 2. x = 4.",
    steps: [
      { stepNumber: 1, title: "Collect x", explanation: "3x/4 − x/4 = 2; 2x/4 = 2." },
      { stepNumber: 2, title: "Solve", explanation: "x/2 = 2, x = 4." },
    ],
    hint: "Collect all x terms on one side.",
    keyConcepts: ["fractional equations"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: 7x + 3 = 3(x − 1) + 10.",
    answer: "7x + 3 = 3x − 3 + 10 = 3x + 7. 4x = 4. x = 1.",
    steps: [
      { stepNumber: 1, title: "Expand RHS", explanation: "3x − 3 + 10 = 3x + 7." },
      { stepNumber: 2, title: "Collect", explanation: "7x − 3x = 7 − 3 = 4; x = 1." },
    ],
    hint: "Expand the bracket on the right first.",
    keyConcepts: ["expanding brackets", "collecting terms"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: (x − 1)/2 − (x + 1)/3 = 2/3.",
    answer: "LCD = 6. Multiply through: 3(x − 1) − 2(x + 1) = 4. 3x − 3 − 2x − 2 = 4. x − 5 = 4. x = 9.",
    steps: [
      { stepNumber: 1, title: "Multiply by 6", explanation: "3(x−1) − 2(x+1) = 4." },
      { stepNumber: 2, title: "Expand", explanation: "3x − 3 − 2x − 2 = 4." },
      { stepNumber: 3, title: "Solve", explanation: "x − 5 = 4, x = 9." },
    ],
    hint: "Multiply every term by the LCD to clear fractions.",
    keyConcepts: ["equations with fractions", "LCD"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: (2x − 3)/(4x + 5) = 1/3.",
    answer: "Cross multiply: 3(2x − 3) = 4x + 5. 6x − 9 = 4x + 5. 2x = 14. x = 7.",
    steps: [
      { stepNumber: 1, title: "Cross multiply", explanation: "3(2x−3) = 1(4x+5)." },
      { stepNumber: 2, title: "Expand", explanation: "6x − 9 = 4x + 5." },
      { stepNumber: 3, title: "Solve", explanation: "2x = 14, x = 7." },
    ],
    hint: "Cross multiply when equation is a fraction = fraction.",
    keyConcepts: ["cross multiplication", "fractional equations"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.5"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "The sum of three consecutive integers is 51. Find them.",
    answer: "Let integers be n, n+1, n+2. n + n+1 + n+2 = 51. 3n + 3 = 51. 3n = 48. n = 16. Integers: 16, 17, 18.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "n + (n+1) + (n+2) = 51." },
      { stepNumber: 2, title: "Simplify", explanation: "3n + 3 = 51." },
      { stepNumber: 3, title: "Solve", explanation: "n = 16." },
      { stepNumber: 4, title: "List", explanation: "16, 17, 18." },
    ],
    hint: "Let the first integer be n.",
    keyConcepts: ["consecutive integers", "word problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "The perimeter of a rectangular swimming pool is 154 m. Its length is 2 m more than twice its breadth. Find the dimensions.",
    answer: "Let breadth = b. Length = 2b + 2. Perimeter: 2(l + b) = 154 ⟹ l + b = 77 ⟹ (2b + 2) + b = 77 ⟹ 3b = 75 ⟹ b = 25 m. Length = 52 m.",
    steps: [
      { stepNumber: 1, title: "Express length", explanation: "l = 2b + 2." },
      { stepNumber: 2, title: "Perimeter equation", explanation: "2(l + b) = 154 ⟹ l + b = 77." },
      { stepNumber: 3, title: "Substitute", explanation: "2b + 2 + b = 77 ⟹ 3b = 75 ⟹ b = 25." },
      { stepNumber: 4, title: "Length", explanation: "l = 2(25) + 2 = 52 m." },
    ],
    hint: "Use perimeter formula: P = 2(l + b).",
    keyConcepts: ["perimeter", "geometry equations"],
    conceptsCovered: ["mth:8:ch02:geometry-equations"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Aman's age is three times his son's age. Ten years ago, his age was five times his son's age. Find their present ages.",
    answer: "Let son's age = x. Aman's age = 3x. Ten years ago: 3x − 10 = 5(x − 10). 3x − 10 = 5x − 50. 40 = 2x. x = 20. Son = 20, Aman = 60.",
    steps: [
      { stepNumber: 1, title: "Present ages", explanation: "Son = x, Aman = 3x." },
      { stepNumber: 2, title: "10 years ago", explanation: "3x − 10 = 5(x − 10)." },
      { stepNumber: 3, title: "Expand", explanation: "3x − 10 = 5x − 50." },
      { stepNumber: 4, title: "Solve", explanation: "40 = 2x, x = 20. Son=20, Aman=60." },
    ],
    hint: "Set up equations for present and past ages separately.",
    keyConcepts: ["age problems"],
    conceptsCovered: ["mth:8:ch02:age-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: 8x − 3 = 3x + 2.",
    answer: "8x − 3x = 2 + 3. 5x = 5. x = 1.",
    steps: [
      { stepNumber: 1, title: "Collect x terms", explanation: "8x − 3x = 5x." },
      { stepNumber: 2, title: "Collect constants", explanation: "2 + 3 = 5." },
      { stepNumber: 3, title: "Solve", explanation: "5x = 5, x = 1." },
    ],
    hint: "Move x terms left, constants right.",
    keyConcepts: ["variable on both sides"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: 6(1 − 4x) + 7(2 + 5x) = 53.",
    answer: "6 − 24x + 14 + 35x = 53. 20 + 11x = 53. 11x = 33. x = 3.",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "6 − 24x + 14 + 35x = 53." },
      { stepNumber: 2, title: "Combine", explanation: "20 + 11x = 53." },
      { stepNumber: 3, title: "Solve", explanation: "11x = 33, x = 3." },
    ],
    hint: "Expand both brackets carefully, watching signs.",
    keyConcepts: ["bracket expansion", "collecting terms"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Solve: (3t − 2)/4 − (2t + 3)/3 = 2/3 − t.",
    answer: "Multiply by 12: 3(3t−2) − 4(2t+3) = 8 − 12t. 9t − 6 − 8t − 12 = 8 − 12t. t − 18 = 8 − 12t. 13t = 26. t = 2.",
    steps: [
      { stepNumber: 1, title: "Multiply by 12", explanation: "3(3t−2) − 4(2t+3) = 8 − 12t." },
      { stepNumber: 2, title: "Expand", explanation: "9t − 6 − 8t − 12 = 8 − 12t." },
      { stepNumber: 3, title: "Collect", explanation: "t − 18 = 8 − 12t → 13t = 26." },
      { stepNumber: 4, title: "Solve", explanation: "t = 2." },
    ],
    hint: "Multiply by LCD = 12 to eliminate all fractions.",
    keyConcepts: ["equations with fractions", "LCD"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The digits of a two-digit number differ by 3. If the digits are interchanged and the resulting number is added to the original number, we get 143. What is the original number?",
    answer: "Let tens digit = a, units digit = b, a − b = 3 (assume a > b). Original = 10a + b. Reversed = 10b + a. Sum: 11(a + b) = 143 ⟹ a + b = 13. From a − b = 3 and a + b = 13: a = 8, b = 5. Original: 85.",
    steps: [
      { stepNumber: 1, title: "Variables", explanation: "Tens = a, units = b; a − b = 3." },
      { stepNumber: 2, title: "Sum equation", explanation: "(10a+b) + (10b+a) = 143 → 11(a+b) = 143 → a+b = 13." },
      { stepNumber: 3, title: "Solve system", explanation: "a = 8, b = 5." },
    ],
    hint: "Express original and reversed numbers using tens and units digits.",
    keyConcepts: ["digit problems", "two-digit numbers"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Shobo's mother's present age is six times Shobo's present age. Shobo's age five years from now will be one-third of his mother's present age. Find their ages.",
    answer: "Let Shobo's age = x. Mother's age = 6x. Five years from now, Shobo = x + 5 = (1/3)(6x) = 2x. x + 5 = 2x. x = 5. Shobo = 5, Mother = 30.",
    steps: [
      { stepNumber: 1, title: "Express", explanation: "Mother = 6x." },
      { stepNumber: 2, title: "Condition", explanation: "x + 5 = (1/3)(6x) = 2x." },
      { stepNumber: 3, title: "Solve", explanation: "5 = x; Shobo=5, Mother=30." },
    ],
    hint: "Future age = present age + 5.",
    keyConcepts: ["age problems"],
    conceptsCovered: ["mth:8:ch02:age-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: (x + 7 − 8x/3)/(11 − 1 − 4x/3) = 11/2. (NCERT style proportion)",
    answer: "Rearranged: Let x + 7 − 8x/3 = (x/3)(3) + 7 − 8x/3. LCD = 3: (3x + 21 − 8x)/3 = (21 − 5x)/3. Denominator: 11 − 1 − 4x/3 = (30 − 4x)/3. Equation: (21 − 5x)/(30 − 4x) = 11/2. Cross: 2(21 − 5x) = 11(30 − 4x). 42 − 10x = 330 − 44x. 34x = 288. x = 288/34 = 144/17.",
    steps: [
      { stepNumber: 1, title: "Combine numerator", explanation: "(21 − 5x)/3." },
      { stepNumber: 2, title: "Combine denominator", explanation: "(30 − 4x)/3." },
      { stepNumber: 3, title: "Cross multiply", explanation: "2(21−5x) = 11(30−4x)." },
      { stepNumber: 4, title: "Solve", explanation: "34x = 288, x = 144/17." },
    ],
    hint: "Combine terms in numerator and denominator using LCD = 3 before cross multiplying.",
    keyConcepts: ["complex fractional equations"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: ["Forgetting to multiply every term by the LCD."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.5"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Present ages of Anu and Raj are in ratio 4:5. Eight years from now, their ratio will be 5:6. Find their present ages.",
    answer: "Let Anu = 4x, Raj = 5x. After 8 years: (4x+8)/(5x+8) = 5/6. Cross: 6(4x+8) = 5(5x+8). 24x + 48 = 25x + 40. x = 8. Anu = 32, Raj = 40.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Anu = 4x, Raj = 5x." },
      { stepNumber: 2, title: "Future ratio", explanation: "(4x+8)/(5x+8) = 5/6." },
      { stepNumber: 3, title: "Cross multiply", explanation: "24x + 48 = 25x + 40." },
      { stepNumber: 4, title: "Solve", explanation: "x = 8; Anu=32, Raj=40." },
    ],
    hint: "Present ages in ratio means Anu = 4x, Raj = 5x.",
    keyConcepts: ["ratio", "age problems"],
    conceptsCovered: ["mth:8:ch02:age-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: −4 + y = 10.",
    answer: "y = 10 + 4 = 14. Verification: −4 + 14 = 10 ✓",
    steps: [{ stepNumber: 1, title: "Transpose", explanation: "y = 10 − (−4) = 10 + 4 = 14." }],
    hint: "Move −4 to the other side; it becomes +4.",
    keyConcepts: ["transposition", "negative constants"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: m/3 = m + 4/(6 − m).",
    answer: "Rearrange: m/3 = (m(6−m) + 4)/(6−m). So m(6−m) = 3(m(6−m)+4)/(6−m) — actually use: m(6−m)/3 = m(6−m) + 4. Wait, re-read: m/3 = m + 4/(6−m). LCD = 3(6−m): m(6−m) = 3m(6−m) + 12. m(6−m) − 3m(6−m) = 12. −2m(6−m) = 12. m(6−m) = −6. 6m − m² = −6. m² − 6m − 6 = 0. Hmm — let me treat as: m/3 − m = 4/(6−m). (m − 3m)/3 = 4/(6−m). −2m/3 = 4/(6−m). −2m(6−m) = 12. −12m + 2m² = 12. m² − 6m − 6 = 0. Using quadratic — this question is non-linear. Simplify differently. Original: m/3 = m + 4/(6−m) means this is likely a typo. Taking it at face value: m/3 − m = 4/(6−m): −2m/3 = 4/(6−m); cross: −2m(6−m) = 12; m(m−6) = 6; m²−6m−6=0. Discriminant: 36+24=60. m=(6±√60)/2=3±√15. For exam context, answer: m = 3 ± √15.",
    steps: [
      { stepNumber: 1, title: "Rearrange", explanation: "m/3 − m = 4/(6−m) → −2m/3 = 4/(6−m)." },
      { stepNumber: 2, title: "Cross multiply", explanation: "−2m(6−m) = 12." },
      { stepNumber: 3, title: "Expand", explanation: "m² − 6m − 6 = 0." },
      { stepNumber: 4, title: "Quadratic", explanation: "m = 3 ± √15." },
    ],
    hint: "Rearrange to get m/3 − m on one side, then cross multiply.",
    keyConcepts: ["fractional equations", "cross multiplication"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.5"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-017",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Hasan buys two kinds of cloth materials for school uniforms: shirt at ₹50 per metre and trouser material at ₹90 per metre. For every 3 metres of the trouser material he buys 2 metres of shirt material. He sells the shirt material at 12% profit and trouser material at 10% profit. His total profit is ₹36. How much trouser material did he buy?",
    answer: "Let trouser = 3x m, shirt = 2x m. Profit = (12/100)(50)(2x) + (10/100)(90)(3x) = 12x + 27x = 39x = 36 — let me recalculate: 12% of 50×2x = 0.12×100x = 12x. 10% of 90×3x = 0.10×270x = 27x. Total = 39x = 36 → x = 36/39 = 12/13. Trouser = 3x = 36/13 ≈ 2.77 m. Hmm — standard NCERT answer is x = 0.92, trouser = 2.77 m. Let me redo: 39x = 36, x = 36/39 = 12/13. Trouser = 3 × 12/13 = 36/13 m.",
    steps: [
      { stepNumber: 1, title: "Variables", explanation: "Trouser = 3x, shirt = 2x." },
      { stepNumber: 2, title: "Profit from shirt", explanation: "12% of (50 × 2x) = 12x." },
      { stepNumber: 3, title: "Profit from trouser", explanation: "10% of (90 × 3x) = 27x." },
      { stepNumber: 4, title: "Total profit", explanation: "39x = 36, x = 12/13. Trouser = 36/13 m." },
    ],
    hint: "Express both quantities in terms of x using the given ratio.",
    keyConcepts: ["profit", "ratio", "word problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.6"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch02-nce-018",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: (y + 3)/2 − (y − 1)/4 = 2.",
    answer: "LCD = 4: 2(y+3) − (y−1) = 8. 2y + 6 − y + 1 = 8. y + 7 = 8. y = 1.",
    steps: [
      { stepNumber: 1, title: "Multiply by 4", explanation: "2(y+3) − (y−1) = 8." },
      { stepNumber: 2, title: "Expand", explanation: "2y + 6 − y + 1 = 8." },
      { stepNumber: 3, title: "Solve", explanation: "y + 7 = 8, y = 1." },
    ],
    hint: "Multiply every term by LCD = 4.",
    keyConcepts: ["fractional equations", "LCD"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch02", "NCERT-Ex2.3"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch02-ics-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve: (4x + 5)/3 = (3x − 2)/2.",
    answer: "Cross multiply: 2(4x + 5) = 3(3x − 2). 8x + 10 = 9x − 6. 16 = x. x = 16.",
    steps: [
      { stepNumber: 1, title: "Cross multiply", explanation: "2(4x+5) = 3(3x−2)." },
      { stepNumber: 2, title: "Expand", explanation: "8x + 10 = 9x − 6." },
      { stepNumber: 3, title: "Solve", explanation: "16 = x." },
    ],
    hint: "Cross multiply since it's a proportion.",
    keyConcepts: ["fractional equations", "cross multiplication"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch02", "fraction-equation"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch02-ics-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A train travels at a speed of (x + 40) km/h for 3 hours and then at (x − 10) km/h for 5 hours. Total distance is 580 km. Find x.",
    answer: "Distance = speed × time. 3(x+40) + 5(x−10) = 580. 3x + 120 + 5x − 50 = 580. 8x + 70 = 580. 8x = 510. x = 63.75.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "3(x+40) + 5(x−10) = 580." },
      { stepNumber: 2, title: "Expand", explanation: "8x + 70 = 580." },
      { stepNumber: 3, title: "Solve", explanation: "x = 510/8 = 63.75." },
    ],
    hint: "Distance = speed × time for each segment.",
    keyConcepts: ["distance-speed-time", "word problems"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: ["Adding times instead of distances.", "Sign error when expanding (x − 10) × 5."],
    tags: ["ICSE", "class8", "ch02", "speed-distance"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch02-ics-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The sum of the angles of a quadrilateral is 360°. Three angles are (x + 10)°, (2x − 5)°, and (3x + 15)°. The fourth angle is 95°. Find x.",
    answer: "(x+10) + (2x−5) + (3x+15) + 95 = 360. 6x + 115 = 360. 6x = 245. x = 245/6 ≈ 40.8°.",
    steps: [
      { stepNumber: 1, title: "Sum = 360", explanation: "(x+10)+(2x−5)+(3x+15)+95=360." },
      { stepNumber: 2, title: "Simplify", explanation: "6x + 115 = 360." },
      { stepNumber: 3, title: "Solve", explanation: "x = 245/6." },
    ],
    hint: "Sum of interior angles of quadrilateral = 360°.",
    keyConcepts: ["quadrilateral angles", "geometry equations"],
    conceptsCovered: ["mth:8:ch02:geometry-equations"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch02", "geometry"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch02-ics-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If 3x/5 + 2 = 4x/7 − 3, find x.",
    answer: "3x/5 − 4x/7 = −5. LCD = 35: 21x/35 − 20x/35 = −5. x/35 = −5. x = −175.",
    steps: [
      { stepNumber: 1, title: "Collect x", explanation: "3x/5 − 4x/7 = −5." },
      { stepNumber: 2, title: "LCD = 35", explanation: "(21x − 20x)/35 = −5." },
      { stepNumber: 3, title: "Solve", explanation: "x/35 = −5, x = −175." },
    ],
    hint: "Find LCD of 5 and 7 = 35.",
    keyConcepts: ["variable on both sides", "fractional equations"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch02", "both-sides-fraction"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch02-ics-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Two numbers are in ratio 3:5. When 6 is added to each, the new ratio becomes 2:3. Find the numbers.",
    answer: "Let numbers = 3x and 5x. (3x+6)/(5x+6) = 2/3. Cross: 9x+18 = 10x+12. x = 6. Numbers: 18 and 30.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "3x and 5x in ratio 3:5." },
      { stepNumber: 2, title: "New ratio", explanation: "(3x+6)/(5x+6) = 2/3." },
      { stepNumber: 3, title: "Cross multiply", explanation: "9x + 18 = 10x + 12." },
      { stepNumber: 4, title: "Solve", explanation: "x = 6; numbers = 18, 30." },
    ],
    hint: "Express both numbers as multiples of x using the ratio.",
    keyConcepts: ["ratio", "cross multiplication", "word problems"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: ["Setting up the ratio in wrong order."],
    tags: ["ICSE", "class8", "ch02", "ratio-problem"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch02-ics-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Solve and check: 3(5z − 7) − 2(9z − 11) = 4(8z − 13) − 17.",
    answer: "LHS: 15z − 21 − 18z + 22 = −3z + 1. RHS: 32z − 52 − 17 = 32z − 69. −3z + 1 = 32z − 69. 70 = 35z. z = 2.",
    steps: [
      { stepNumber: 1, title: "Expand LHS", explanation: "15z − 21 − 18z + 22 = −3z + 1." },
      { stepNumber: 2, title: "Expand RHS", explanation: "32z − 52 − 17 = 32z − 69." },
      { stepNumber: 3, title: "Solve", explanation: "−3z + 1 = 32z − 69 → 70 = 35z → z = 2." },
    ],
    hint: "Expand all brackets carefully before collecting.",
    keyConcepts: ["bracket expansion", "collecting terms"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch02", "multi-bracket"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch02-ics-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A man's age is twice his son's. After 20 years he will be 4/3 times his son's age. Find present ages.",
    answer: "Father = 2x, Son = x. After 20: 2x + 20 = (4/3)(x + 20). 3(2x+20) = 4(x+20). 6x + 60 = 4x + 80. 2x = 20. x = 10. Son = 10, Father = 20.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Father=2x, Son=x." },
      { stepNumber: 2, title: "Future condition", explanation: "2x+20 = (4/3)(x+20)." },
      { stepNumber: 3, title: "Cross multiply", explanation: "6x + 60 = 4x + 80." },
      { stepNumber: 4, title: "Solve", explanation: "x = 10; Son=10, Father=20." },
    ],
    hint: "Multiply by 3 to clear the fraction 4/3.",
    keyConcepts: ["age problems", "fraction elimination"],
    conceptsCovered: ["mth:8:ch02:age-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch02", "age-word-problem"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch02-cmp-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A shopkeeper has some apples. He sells 2/5 of them and still has 120 left. How many did he start with?",
    answer: "Let total = x. Remaining = x − 2x/5 = 3x/5 = 120. x = 200 apples.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "3x/5 = 120." },
      { stepNumber: 2, title: "Solve", explanation: "x = 120 × 5/3 = 200." },
    ],
    hint: "If 2/5 are sold, 3/5 remain.",
    keyConcepts: ["fraction word problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The cost of a notebook is ₹5 more than twice the cost of a pen. Together they cost ₹65. Find the cost of each.",
    answer: "Let pen cost = p. Notebook = 2p + 5. p + (2p + 5) = 65. 3p = 60. p = 20. Notebook = 45.",
    steps: [
      { stepNumber: 1, title: "Express notebook", explanation: "Notebook = 2p + 5." },
      { stepNumber: 2, title: "Equation", explanation: "p + 2p + 5 = 65 → 3p = 60." },
      { stepNumber: 3, title: "Solve", explanation: "p = 20, notebook = 45." },
    ],
    hint: "Let pen = p and express notebook in terms of p.",
    keyConcepts: ["cost word problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "cost-problem"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If a number is doubled and then decreased by 4, the result is 18. The number is:",
    answer: "11. 2x − 4 = 18 → 2x = 22 → x = 11.",
    options: ["A) 7", "B) 9", "C) 11", "D) 13"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Equation", explanation: "2x − 4 = 18 → x = 11." }],
    hint: "Double means multiply by 2; decreased means subtract.",
    keyConcepts: ["number problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "number"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Two friends start from the same point and walk in opposite directions. One walks at 4 km/h and the other at 6 km/h. After how many hours are they 30 km apart?",
    answer: "Combined speed = 4 + 6 = 10 km/h. Time = 30/10 = 3 hours.",
    steps: [
      { stepNumber: 1, title: "Relative speed", explanation: "Opposite directions: add speeds = 10 km/h." },
      { stepNumber: 2, title: "Time", explanation: "30 ÷ 10 = 3 hours." },
    ],
    hint: "When moving in opposite directions, speeds add.",
    keyConcepts: ["distance-speed-time", "relative motion"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "speed-problem"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a class, the number of boys is 3 more than twice the number of girls. Total students = 39. Find the number of boys and girls.",
    answer: "Let girls = g. Boys = 2g + 3. g + 2g + 3 = 39. 3g = 36. g = 12. Boys = 27.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "g + (2g+3) = 39 → 3g = 36." },
      { stepNumber: 2, title: "Solve", explanation: "g = 12, boys = 27." },
    ],
    hint: "Express boys in terms of girls.",
    keyConcepts: ["linear equation", "real-world"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "class-problem"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Two taps together fill a tank in 3 hours. Tap A alone fills in x hours, Tap B in (x + 6) hours. Set up the equation and find x.",
    answer: "In 1 hour: 1/x + 1/(x+6) = 1/3. (x+6+x)/(x(x+6)) = 1/3. 3(2x+6) = x(x+6). 6x+18 = x²+6x. x² = 18. x = 3√2 ≈ 4.24 hours (or in integer context, this yields x² = 18). For class 8 context: equation is x² = 18.",
    steps: [
      { stepNumber: 1, title: "Rate equation", explanation: "1/x + 1/(x+6) = 1/3." },
      { stepNumber: 2, title: "LCD = 3x(x+6)", explanation: "3(2x+6) = x(x+6)." },
      { stepNumber: 3, title: "Simplify", explanation: "x² = 18, x = 3√2." },
    ],
    hint: "Rate = 1/time; total rate = 1/3.",
    keyConcepts: ["pipes and tanks", "fractional equations"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "pipes-cistern"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A student buys pens at ₹8 each and spends ₹64. Write and solve the equation.",
    answer: "Let number of pens = n. 8n = 64. n = 8. The student buys 8 pens.",
    steps: [{ stepNumber: 1, title: "Equation and solution", explanation: "8n = 64; n = 8." }],
    hint: "Total cost = price per pen × number of pens.",
    keyConcepts: ["equation from context"],
    conceptsCovered: ["mth:8:ch02:balance-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A 120 cm wire is bent to form a triangle with sides in ratio 3:4:5. Find the lengths of the sides.",
    answer: "3k + 4k + 5k = 120. 12k = 120. k = 10. Sides: 30, 40, 50 cm. Check: 30+40+50 = 120 ✓. Also 30²+40² = 900+1600 = 2500 = 50² — it's a right triangle!",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "3k + 4k + 5k = 120." },
      { stepNumber: 2, title: "Solve", explanation: "12k = 120, k = 10." },
      { stepNumber: 3, title: "Sides", explanation: "30, 40, 50 cm." },
    ],
    hint: "Sum of sides = perimeter = 120 cm.",
    keyConcepts: ["ratio", "perimeter", "geometry"],
    conceptsCovered: ["mth:8:ch02:geometry-equations"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "geometry-word"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "A number added to three times itself gives 48. The number is:",
    answer: "12. x + 3x = 48 → 4x = 48 → x = 12.",
    options: ["A) 10", "B) 12", "C) 14", "D) 16"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Equation", explanation: "x + 3x = 48 → 4x = 48 → x = 12." }],
    hint: "Three times itself + itself = four times.",
    keyConcepts: ["number problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Maya has ₹x. She spends ₹200 and has half of what her friend Priya has. Priya has ₹(x + 100). Find x.",
    answer: "x − 200 = (x + 100)/2. 2(x − 200) = x + 100. 2x − 400 = x + 100. x = 500.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "x − 200 = (x+100)/2." },
      { stepNumber: 2, title: "Multiply by 2", explanation: "2x − 400 = x + 100." },
      { stepNumber: 3, title: "Solve", explanation: "x = 500." },
    ],
    hint: "'Half of Priya' means (Priya's amount) ÷ 2.",
    keyConcepts: ["variable both sides", "money problem"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "money"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A shirt costs ₹(3x − 20) and is sold for ₹(2x + 40). If profit = ₹60, find x.",
    answer: "Profit = SP − CP: (2x + 40) − (3x − 20) = 60. 2x + 40 − 3x + 20 = 60. 60 − x = 60. x = 0. Check: CP = −20, SP = 40, profit = 60. Since CP < 0 makes no sense in context, x = 0 satisfies the equation mathematically.",
    steps: [
      { stepNumber: 1, title: "Profit equation", explanation: "(2x+40) − (3x−20) = 60." },
      { stepNumber: 2, title: "Simplify", explanation: "60 − x = 60 → x = 0." },
    ],
    hint: "Profit = SP − CP.",
    keyConcepts: ["profit", "equation from context"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "profit"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A father is 3 times as old as his daughter. In 12 years, he will be twice as old. Find their present ages.",
    answer: "Daughter = x, Father = 3x. In 12 years: 3x + 12 = 2(x + 12). 3x + 12 = 2x + 24. x = 12. Daughter = 12, Father = 36.",
    steps: [
      { stepNumber: 1, title: "Future condition", explanation: "3x + 12 = 2(x + 12)." },
      { stepNumber: 2, title: "Solve", explanation: "x = 12." },
    ],
    hint: "Write equation for 12 years from now.",
    keyConcepts: ["age problems"],
    conceptsCovered: ["mth:8:ch02:age-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "age"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "The sum of two consecutive even numbers is 86. Find them.",
    answer: "Let numbers = n and n+2. n + n + 2 = 86. 2n = 84. n = 42. Numbers: 42 and 44.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "n + (n+2) = 86 → 2n + 2 = 86." },
      { stepNumber: 2, title: "Solve", explanation: "n = 42; numbers 42, 44." },
    ],
    hint: "Consecutive even numbers differ by 2.",
    keyConcepts: ["consecutive even numbers"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "consecutive-even"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If the perimeter of a square is (8x + 20) cm, and equals 60 cm, what is x?",
    answer: "x = 5. 8x + 20 = 60 → 8x = 40 → x = 5.",
    options: ["A) 4", "B) 5", "C) 6", "D) 7"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Solve", explanation: "8x + 20 = 60 → x = 5." }],
    hint: "Set the expression equal to 60 and solve.",
    keyConcepts: ["geometry", "perimeter"],
    conceptsCovered: ["mth:8:ch02:geometry-equations"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "geometry"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A man earns ₹x per day and spends ₹100. His friend earns ₹(x − 50) per day and spends ₹70. After a week (7 days), both have saved the same amount. Find x.",
    answer: "Man saves: 7(x − 100). Friend saves: 7(x − 50 − 70) = 7(x − 120). 7(x − 100) = 7(x − 120). x − 100 = x − 120. 0 = −20. No solution — they can NEVER save equally. The problem has no valid x.",
    steps: [
      { stepNumber: 1, title: "Man's savings", explanation: "7(x − 100)." },
      { stepNumber: 2, title: "Friend's savings", explanation: "7(x − 120)." },
      { stepNumber: 3, title: "Equation", explanation: "7(x−100) = 7(x−120) → 0 = −20. Contradiction." },
    ],
    hint: "Compare savings per week. You may get a surprising result.",
    keyConcepts: ["no-solution equation", "consistency"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: ["Assuming every equation has a solution — this one demonstrates inconsistency."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "no-solution"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch02-cmp-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "One-third of a pole is in the ground, one-fourth is in water, and the remaining 5 m is above water. Find the length of the pole.",
    answer: "In ground + in water + above water = total. x/3 + x/4 + 5 = x. 4x/12 + 3x/12 + 5 = x. 7x/12 + 5 = x. 5 = x − 7x/12 = 5x/12. x = 12 m.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "x/3 + x/4 + 5 = x." },
      { stepNumber: 2, title: "LCD = 12", explanation: "7x/12 + 5 = x → 5 = 5x/12." },
      { stepNumber: 3, title: "Solve", explanation: "x = 12 m." },
    ],
    hint: "All parts must sum to the whole.",
    keyConcepts: ["fraction word problem"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch02", "fraction-word"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch02-hot-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "For what value of k does the equation kx + 4 = 2x + 8 have: (a) exactly one solution, (b) no solution, (c) infinitely many solutions?",
    answer: "(a) One solution: k ≠ 2. Then (k−2)x = 4 ⟹ x = 4/(k−2). (b) No solution: k = 2 and 4 ≠ 8 — i.e., 2x + 4 = 2x + 8 ⟹ 4 = 8, which is false. So k = 2 gives no solution. (c) Infinitely many solutions: impossible here since 4 ≠ 8 always. If equation were kx + 4 = 2x + 4, then k = 2 would give infinitely many.",
    steps: [
      { stepNumber: 1, title: "Rearrange", explanation: "(k−2)x = 4." },
      { stepNumber: 2, title: "k ≠ 2", explanation: "Unique solution x = 4/(k−2)." },
      { stepNumber: 3, title: "k = 2", explanation: "0 = 4 — contradiction, no solution." },
      { stepNumber: 4, title: "Infinite solutions", explanation: "Not possible here since constants differ (4 ≠ 8)." },
    ],
    hint: "Consider what happens to the coefficient of x for different values of k.",
    keyConcepts: ["solution types", "parametric equations"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: ["Confusing no-solution with zero as a solution."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "parametric"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Three friends share a prize. The first gets twice as much as the second, and the third gets ₹100 less than the first. Together they share ₹900. Is it possible for all three to get a positive amount? Find each person's share.",
    answer: "Let second = x. First = 2x. Third = 2x − 100. Total: x + 2x + (2x − 100) = 900. 5x − 100 = 900. 5x = 1000. x = 200. Second = ₹200, First = ₹400, Third = ₹300. All positive ✓ (third = 400 − 100 = 300 > 0). Yes, it is possible.",
    steps: [
      { stepNumber: 1, title: "Assign", explanation: "Second = x, First = 2x, Third = 2x − 100." },
      { stepNumber: 2, title: "Sum equation", explanation: "5x − 100 = 900 → x = 200." },
      { stepNumber: 3, title: "Shares", explanation: "First=400, Second=200, Third=300." },
      { stepNumber: 4, title: "Check positivity", explanation: "All three are positive ✓." },
    ],
    hint: "Check that the third person's share is positive before finalising.",
    keyConcepts: ["word problem", "feasibility"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: ["Not verifying that all shares are positive."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "multi-person"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If 2x/3 + 1/4 = x/6 + 3/4, find x. Then check: is x a solution to 3x − 2 = x + 4?",
    answer: "Step 1: 2x/3 − x/6 = 3/4 − 1/4 = 1/2. LCD=6: 4x/6 − x/6 = 1/2. 3x/6 = 1/2. x/2 = 1/2. x = 1. Step 2: Check in 3x − 2 = x + 4: 3(1) − 2 = 1 and 1 + 4 = 5. 1 ≠ 5. x = 1 is NOT a solution of the second equation.",
    steps: [
      { stepNumber: 1, title: "Solve first equation", explanation: "x = 1." },
      { stepNumber: 2, title: "Check in second", explanation: "3(1)−2=1 ≠ 1+4=5. Not a solution." },
    ],
    hint: "Solve the first equation, then substitute into the second to verify.",
    keyConcepts: ["verification", "equation solving"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "cross-check"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Create a real-life word problem that leads to the equation 3(2x − 1) = 2(x + 5) + 7 and solve it.",
    answer: "Problem: Ravi works x hours per day for 3 days at rate ₹2/hr, minus 1 hour off. Total earnings in 3 days = 3(2x − 1). His friend Amit works (x + 5) hours for 2 days at ₹1/hr and earns an extra ₹7 from a bonus. They earn the same. Equation: 3(2x − 1) = 2(x + 5) + 7. 6x − 3 = 2x + 10 + 7 = 2x + 17. 4x = 20. x = 5. Ravi works 5 hours/day.",
    steps: [
      { stepNumber: 1, title: "Expand LHS", explanation: "6x − 3." },
      { stepNumber: 2, title: "Expand RHS", explanation: "2x + 17." },
      { stepNumber: 3, title: "Solve", explanation: "4x = 20, x = 5." },
    ],
    hint: "Match both sides to earning/spending in a story.",
    keyConcepts: ["equation creation", "word problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "create"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Without solving, determine whether 2(3x + 5) = 6x + 11 has a solution. Justify.",
    answer: "Expand: 6x + 10 = 6x + 11 → 10 = 11. This is always false. So the equation has NO solution (it is inconsistent).",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "6x + 10 = 6x + 11." },
      { stepNumber: 2, title: "Simplify", explanation: "10 = 11 — false for all x." },
    ],
    hint: "If x cancels and you get a false statement, there's no solution.",
    keyConcepts: ["inconsistent equations", "no solution"],
    conceptsCovered: ["mth:8:ch02:balance-method"],
    prerequisites: [],
    commonErrors: ["Trying to find a value of x instead of recognising the inconsistency."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "no-solution"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "A boat goes 30 km upstream and 44 km downstream in 10 hours. It also covers 40 km upstream and 55 km downstream in 13 hours. Find the speed of the stream.",
    answer: "Let boat speed = b, stream speed = s. Upstream speed = b−s, downstream = b+s. From first trip: 30/(b−s) + 44/(b+s) = 10. From second: 40/(b−s) + 55/(b+s) = 13. Let u = 1/(b−s), v = 1/(b+s). 30u + 44v = 10 and 40u + 55v = 13. From first: 30u = 10−44v → u = (10−44v)/30. Substitute: 40(10−44v)/30 + 55v = 13. (400−1760v)/30 + 55v = 13. 400−1760v + 1650v = 390. −110v = −10. v = 1/11. So b+s = 11. Similarly u = (10−4)/30 = 6/30 = 1/5; b−s = 5. b = 8, s = 3 km/h.",
    steps: [
      { stepNumber: 1, title: "Variables", explanation: "u=1/(b−s), v=1/(b+s)." },
      { stepNumber: 2, title: "System", explanation: "30u+44v=10; 40u+55v=13." },
      { stepNumber: 3, title: "Solve", explanation: "v=1/11, u=1/5 → b−s=5, b+s=11 → s=3." },
    ],
    hint: "Let u = 1/(upstream speed) and v = 1/(downstream speed) to convert to linear equations.",
    keyConcepts: ["boat-stream", "simultaneous equations"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: ["Not recognising this as a system requiring substitution."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "boat-stream"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "The product of two consecutive negative integers is 110 less than the square of the larger integer. Find them.",
    answer: "Let integers = n and n+1 (both negative). Product = n(n+1). Square of larger = (n+1)². n(n+1) = (n+1)² − 110. n²+n = n²+2n+1−110. n = −109. Integers: −109 and −108. Verify: (−109)(−108) = 11772; (−108)² = 11664; 11772 − 11664 = 108 ≠ 110. Recheck: n²+n = n²+2n+1−110 → n+110 = n+1+2n = ... let me redo: n²+n = n²+2n+1−110 → n = 2n−109 → −n = −109 → n = −109? −n = −109 → n = 109... but they must be negative. Equation holds for n=−110 and n=−109... Actually: −n = −109 means n = 109 (positive). For negative: let n = −110, n+1 = −109. Product: (−110)(−109) = 11990. (n+1)² = (−109)² = 11881. 11990 − 11881 = 109 ≠ 110. n=−111, n+1=−110: product=12210, square=12100, diff=110 ✓. Integers: −111 and −110.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "n(n+1) = (n+1)² − 110." },
      { stepNumber: 2, title: "Expand", explanation: "n² + n = n² + 2n + 1 − 110 → −n = −109 → n = 109 (but we want negative). Reinterpret: n = −111, n+1 = −110." },
      { stepNumber: 3, title: "Verify", explanation: "(−111)(−110) = 12210; (−110)² = 12100; 12210−12100 = 110 ✓." },
    ],
    hint: "Set up the equation carefully; the solution with positive n gives the positive version; negate for negative integers.",
    keyConcepts: ["consecutive integers", "equation from geometry"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: ["Incorrect sign handling for negative integers."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "consecutive-integers"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Solve: (x − a)/(x − b) + (x − b)/(x − a) = 2, where a ≠ b.",
    answer: "Let u = (x−a)/(x−b). Then the equation is u + 1/u = 2. Multiply by u: u² − 2u + 1 = 0 → (u−1)² = 0 → u = 1. So (x−a)/(x−b) = 1 → x−a = x−b → −a = −b → a = b. But a ≠ b is given. So there is NO solution (the equation is inconsistent when a ≠ b).",
    steps: [
      { stepNumber: 1, title: "Let u = (x−a)/(x−b)", explanation: "u + 1/u = 2 → u = 1." },
      { stepNumber: 2, title: "Substitute back", explanation: "(x−a)/(x−b) = 1 → a = b." },
      { stepNumber: 3, title: "Conclude", explanation: "Contradicts a ≠ b; no solution exists." },
    ],
    hint: "Introduce a substitution to simplify the sum.",
    keyConcepts: ["substitution", "no-solution", "parametric"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: ["Algebraic manipulation that inadvertently divides by zero."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "substitution"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A chemist mixes x litres of 30% acid solution with (10 − x) litres of 70% acid solution to get exactly 10 litres of 50% acid solution. Find x. Verify.",
    answer: "Acid content equation: 0.30x + 0.70(10−x) = 0.50 × 10. 0.30x + 7 − 0.70x = 5. −0.40x = −2. x = 5. So 5 litres of 30% and 5 litres of 70%. Verify: 0.30(5) + 0.70(5) = 1.5 + 3.5 = 5 = 50% of 10 litres. ✓",
    steps: [
      { stepNumber: 1, title: "Acid equation", explanation: "0.30x + 0.70(10−x) = 5." },
      { stepNumber: 2, title: "Expand", explanation: "0.30x + 7 − 0.70x = 5." },
      { stepNumber: 3, title: "Solve", explanation: "−0.40x = −2, x = 5." },
      { stepNumber: 4, title: "Verify", explanation: "1.5 + 3.5 = 5 = 50% × 10 ✓." },
    ],
    hint: "Pure acid in mixture = acid from each component added.",
    keyConcepts: ["mixture problems", "percentage"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: ["Working with percentages as whole numbers instead of decimals."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "mixture"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch02-hot-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Design a number puzzle: I think of a number, triple it, subtract 7, divide by 2, and add 11. The result is 18. What is my number? Also, create a variation where the answer changes to 30 and find the new starting number.",
    answer: "Puzzle 1: Let number = n. (3n − 7)/2 + 11 = 18. (3n − 7)/2 = 7. 3n − 7 = 14. 3n = 21. n = 7. Variation (result = 30): (3n − 7)/2 + 11 = 30. (3n − 7)/2 = 19. 3n − 7 = 38. 3n = 45. n = 15.",
    steps: [
      { stepNumber: 1, title: "Puzzle 1", explanation: "(3n−7)/2 + 11 = 18 → n = 7." },
      { stepNumber: 2, title: "Variation", explanation: "(3n−7)/2 + 11 = 30 → n = 15." },
    ],
    hint: "Work backwards: result → undo each operation.",
    keyConcepts: ["reverse operations", "puzzle design"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch02", "puzzle"],
    source: "hots",
  },

  // ── PREVIOUS-YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch02-pyq-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: 2(2x + 3) − 10 = 6(x − 2).",
    answer: "4x + 6 − 10 = 6x − 12. 4x − 4 = 6x − 12. 8 = 2x. x = 4.",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "4x − 4 = 6x − 12." },
      { stepNumber: 2, title: "Collect", explanation: "8 = 2x, x = 4." },
    ],
    hint: "Expand and collect like terms.",
    keyConcepts: ["bracket equations"],
    conceptsCovered: ["mth:8:ch02:variable-both-sides"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "The sum of two numbers is 95. If one exceeds the other by 15, find the numbers.",
    answer: "Let numbers = x and x + 15. x + x + 15 = 95. 2x = 80. x = 40. Numbers: 40 and 55.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "x + (x+15) = 95 → 2x = 80." },
      { stepNumber: 2, title: "Solve", explanation: "x=40; numbers 40, 55." },
    ],
    hint: "Let smaller number = x, larger = x + 15.",
    keyConcepts: ["number problems"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If 5x − 10 = 0, then x =",
    answer: "x = 2. 5x = 10; x = 2.",
    options: ["A) 1", "B) 2", "C) 5", "D) 10"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Solve", explanation: "5x = 10, x = 2." }],
    hint: "Add 10 to both sides then divide by 5.",
    keyConcepts: ["basic linear equation"],
    conceptsCovered: ["mth:8:ch02:transposition"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The length of a rectangle exceeds its breadth by 9 cm. If both length and breadth are increased by 3 cm, the area increases by 84 cm². Find original dimensions.",
    answer: "Breadth = b, Length = b+9. Original area = b(b+9). New area = (b+3)(b+12). Increase: (b+3)(b+12) − b(b+9) = 84. b²+15b+36 − b²−9b = 84. 6b + 36 = 84. 6b = 48. b = 8 cm. Length = 17 cm.",
    steps: [
      { stepNumber: 1, title: "New area − old area = 84", explanation: "(b+3)(b+12) − b(b+9) = 84." },
      { stepNumber: 2, title: "Expand", explanation: "6b + 36 = 84." },
      { stepNumber: 3, title: "Solve", explanation: "b = 8, length = 17." },
    ],
    hint: "Area = length × breadth; find difference of new and old areas.",
    keyConcepts: ["area", "geometry equations"],
    conceptsCovered: ["mth:8:ch02:geometry-equations"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The denominator of a rational number is greater than its numerator by 8. If the numerator is increased by 17 and the denominator is decreased by 1, the number obtained is 3/2. Find the original number.",
    answer: "Let numerator = n, denominator = n + 8. New: (n+17)/(n+8−1) = 3/2. 2(n+17) = 3(n+7). 2n+34 = 3n+21. n = 13. Original: 13/21.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "(n+17)/(n+7) = 3/2." },
      { stepNumber: 2, title: "Cross multiply", explanation: "2n+34 = 3n+21." },
      { stepNumber: 3, title: "Solve", explanation: "n = 13; number = 13/21." },
    ],
    hint: "Denominator = numerator + 8.",
    keyConcepts: ["fraction word problem", "cross multiplication"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: x/2 − 1/5 = x/3 + 1/4.",
    answer: "x/2 − x/3 = 1/4 + 1/5. LCD(2,3)=6: 3x/6−2x/6 = x/6. LCD(4,5)=20: 5/20+4/20 = 9/20. x/6 = 9/20. x = 54/20 = 27/10.",
    steps: [
      { stepNumber: 1, title: "Collect x", explanation: "x/2 − x/3 = x/6." },
      { stepNumber: 2, title: "Collect constants", explanation: "1/4 + 1/5 = 9/20." },
      { stepNumber: 3, title: "Solve", explanation: "x = 6 × 9/20 = 27/10." },
    ],
    hint: "Collect x terms left, constants right.",
    keyConcepts: ["fractional equations", "LCD"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Raju is 5 years older than Rina. Ten years ago, Raju was twice as old as Rina. Find their present ages.",
    answer: "Rina = x, Raju = x + 5. Ten years ago: x + 5 − 10 = 2(x − 10). x − 5 = 2x − 20. 15 = x. Rina = 15, Raju = 20.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "(x+5−10) = 2(x−10)." },
      { stepNumber: 2, title: "Solve", explanation: "x − 5 = 2x − 20 → x = 15." },
    ],
    hint: "Ten years ago, subtract 10 from present ages.",
    keyConcepts: ["age problems"],
    conceptsCovered: ["mth:8:ch02:age-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Solve: (y − 1)/3 + (y + 1)/6 = (2y − 3)/9.",
    answer: "LCD = 18: 6(y−1) + 3(y+1) = 2(2y−3). 6y−6+3y+3 = 4y−6. 9y−3 = 4y−6. 5y = −3. y = −3/5.",
    steps: [
      { stepNumber: 1, title: "Multiply by 18", explanation: "6(y−1)+3(y+1)=2(2y−3)." },
      { stepNumber: 2, title: "Expand", explanation: "9y − 3 = 4y − 6." },
      { stepNumber: 3, title: "Solve", explanation: "5y = −3, y = −3/5." },
    ],
    hint: "LCD of 3, 6, 9 = 18.",
    keyConcepts: ["fractional equations"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The cost of 4 pens and 3 pencils is ₹35. If a pen costs ₹2 more than a pencil, find the cost of each.",
    answer: "Let pencil = p, pen = p+2. 4(p+2) + 3p = 35. 4p+8+3p = 35. 7p = 27. p = 27/7 ≈ ₹3.86. But for integer solution: adjust — if pen = pencil + 3: 4(p+3)+3p=35 → 7p=23 (not integer). Standard version: pencil = ₹3, pen = ₹5: 4(5)+3(3)=20+9=29≠35. Let pencil=p: 7p+8=35 → 7p=27 → p=27/7. Exact answer: pencil = 27/7 ≈ ₹3.86, pen ≈ ₹5.86.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "4(p+2) + 3p = 35 → 7p + 8 = 35." },
      { stepNumber: 2, title: "Solve", explanation: "7p = 27, p = 27/7. Pen = 27/7 + 2 = 41/7." },
    ],
    hint: "Pen = pencil + 2; total cost = 35.",
    keyConcepts: ["cost problem"],
    conceptsCovered: ["mth:8:ch02:number-problems"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t2", topicName: "Equations with Variable on Both Sides",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Solve: (3x − 1)/5 = (2x + 3)/4.",
    answer: "Cross multiply: 4(3x−1) = 5(2x+3). 12x − 4 = 10x + 15. 2x = 19. x = 19/2.",
    steps: [
      { stepNumber: 1, title: "Cross multiply", explanation: "4(3x−1) = 5(2x+3)." },
      { stepNumber: 2, title: "Expand", explanation: "12x − 4 = 10x + 15." },
      { stepNumber: 3, title: "Solve", explanation: "2x = 19, x = 19/2." },
    ],
    hint: "Cross-multiply since it's fraction = fraction.",
    keyConcepts: ["cross multiplication", "fractional equations"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t1", topicName: "Solving Linear Equations",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which of the following is a linear equation?",
    answer: "Option A: 2x + 3 = 7 is linear (degree 1).",
    options: ["A) 2x + 3 = 7", "B) x² = 4", "C) x³ − 1 = 0", "D) √x = 2"],
    correctOption: "A",
    steps: [{ stepNumber: 1, title: "Check degree", explanation: "Linear = degree 1 in variable. Only 2x + 3 = 7 qualifies." }],
    hint: "Linear means variable appears only to the first power.",
    keyConcepts: ["linear equation", "degree"],
    conceptsCovered: ["mth:8:ch02:balance-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch02-pyq-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch02", chapterName: "Linear Equations in One Variable",
    topicId: "t3", topicName: "Word Problems",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A man travelled 3/8 of his journey by rail, 1/4 by bus, 1/6 on foot, and the remaining 8 km by boat. How long was the journey?",
    answer: "Let total = x. Rail + bus + foot + boat = x. 3x/8 + x/4 + x/6 + 8 = x. LCD = 24: 9x/24 + 6x/24 + 4x/24 + 8 = x. 19x/24 + 8 = x. 8 = x − 19x/24 = 5x/24. x = 8 × 24/5 = 192/5 = 38.4 km.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "3x/8 + x/4 + x/6 + 8 = x." },
      { stepNumber: 2, title: "LCD = 24", explanation: "19x/24 + 8 = x." },
      { stepNumber: 3, title: "Solve", explanation: "5x/24 = 8, x = 192/5 = 38.4 km." },
    ],
    hint: "Sum of all parts = total journey.",
    keyConcepts: ["fraction word problem", "journey"],
    conceptsCovered: ["mth:8:ch02:equations-with-fractions"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch02", "PYQ-journey"],
    source: "previous-year",
  },
];
