// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 8, Chapter 3: Understanding Quadrilaterals
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Polygons and Properties of Quadrilaterals — 38 q
 *   t2 Special Quadrilaterals — 37 q
 *
 * v1 2026-07-07 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH03_UNDERSTANDING_QUADRILATERALS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Polygons and Properties of Quadrilaterals
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-8-ch03-con-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is a polygon? Distinguish between regular and irregular polygons.",
    answer: "A polygon is a closed figure formed by three or more line segments (sides). A regular polygon has all sides equal AND all angles equal (e.g., square, equilateral triangle). An irregular polygon has sides or angles that are not all equal (e.g., rectangle, scalene triangle).",
    steps: [
      { stepNumber: 1, title: "Define polygon", explanation: "Closed plane figure with straight sides ≥ 3." },
      { stepNumber: 2, title: "Regular vs irregular", explanation: "Regular: all sides AND angles equal. Irregular: otherwise." },
    ],
    hint: "A regular polygon is both equilateral (equal sides) and equiangular (equal angles).",
    keyConcepts: ["polygon", "regular polygon"],
    conceptsCovered: ["mth:8:ch03:polygon"],
    prerequisites: [],
    commonErrors: ["Thinking 'regular' only means equal sides, ignoring equal angles"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State the angle sum property of polygons. What is the sum of interior angles of (a) a quadrilateral, (b) a pentagon?",
    answer: "Sum of interior angles of an n-sided polygon = (n−2) × 180°. (a) Quadrilateral (n=4): (4−2)×180° = 360°. (b) Pentagon (n=5): (5−2)×180° = 540°.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "Sum = (n−2) × 180°." },
      { stepNumber: 2, title: "Quadrilateral", explanation: "(4−2)×180 = 360°." },
      { stepNumber: 3, title: "Pentagon", explanation: "(5−2)×180 = 540°.", result: "Quad = 360°; Pentagon = 540°" },
    ],
    hint: "Subtract 2 from the number of sides, then multiply by 180.",
    keyConcepts: ["angle sum of polygon"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: ["Using n×180° instead of (n−2)×180°"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is the sum of exterior angles of any convex polygon?",
    answer: "The sum of all exterior angles of any convex polygon is always 360°, regardless of the number of sides.",
    steps: [
      { stepNumber: 1, title: "State property", explanation: "Exterior angle sum = 360° for any convex polygon." },
    ],
    hint: "Think of walking around the polygon: you turn a full circle = 360°.",
    keyConcepts: ["exterior angle sum"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: ["Confusing interior angle sum (depends on n) with exterior angle sum (always 360°)"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Each interior angle of a regular polygon is 144°. How many sides does it have?",
    answer: "Exterior angle = 180°−144° = 36°. Number of sides = 360°/36° = 10. The polygon is a regular decagon (10 sides).",
    steps: [
      { stepNumber: 1, title: "Find exterior angle", explanation: "180°−144° = 36°." },
      { stepNumber: 2, title: "Find number of sides", explanation: "n = 360°/36° = 10.", result: "10 sides (decagon)" },
    ],
    hint: "Each exterior angle = 360°/n. Find n from exterior angle.",
    keyConcepts: ["regular polygon", "exterior angle"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: ["Using interior angle directly instead of finding exterior angle first"],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Three angles of a quadrilateral are 90°, 85°, and 100°. Find the fourth angle.",
    answer: "Sum of quadrilateral angles = 360°. Fourth angle = 360°−90°−85°−100° = 85°.",
    steps: [
      { stepNumber: 1, title: "Apply angle sum", explanation: "360° = 90+85+100+x." },
      { stepNumber: 2, title: "Solve", explanation: "x = 360−275 = 85°.", result: "Fourth angle = 85°" },
    ],
    hint: "Interior angles of a quadrilateral sum to 360°.",
    keyConcepts: ["quadrilateral angle sum"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What is the measure of each exterior angle of a regular hexagon?",
    answer: "A hexagon has 6 sides. Each exterior angle = 360°/6 = 60°.",
    steps: [
      { stepNumber: 1, title: "Apply formula", explanation: "Each exterior angle = 360°/n = 360°/6 = 60°.", result: "60°" },
    ],
    hint: "Exterior angle of regular n-gon = 360°/n.",
    keyConcepts: ["regular hexagon", "exterior angle"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Define: (a) convex polygon, (b) concave polygon. Give an example of each.",
    answer: "(a) Convex polygon: all interior angles < 180°; any diagonal lies inside the polygon. Example: regular hexagon. (b) Concave polygon: at least one interior angle > 180° (a reflex angle); some diagonals lie outside. Example: a star-shaped polygon.",
    steps: [
      { stepNumber: 1, title: "Convex", explanation: "All angles < 180°; diagonals inside." },
      { stepNumber: 2, title: "Concave", explanation: "At least one angle > 180°; some diagonals outside." },
    ],
    hint: "Convex = 'bulges out'; concave = 'caves in' at one vertex.",
    keyConcepts: ["convex polygon", "concave polygon"],
    conceptsCovered: ["mth:8:ch03:polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The angles of a quadrilateral are in the ratio 1:2:3:4. Find all four angles.",
    answer: "Sum = 360°. Total ratio parts = 1+2+3+4 = 10. Each part = 36°. Angles: 36°, 72°, 108°, 144°.",
    steps: [
      { stepNumber: 1, title: "Each part", explanation: "360°/10 = 36°." },
      { stepNumber: 2, title: "Angles", explanation: "36°, 72°, 108°, 144°.", result: "36°, 72°, 108°, 144°" },
    ],
    hint: "Sum of parts × value per part = total 360°.",
    keyConcepts: ["quadrilateral angles", "ratio"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the number of diagonals in (a) a hexagon, (b) an octagon.",
    answer: "Diagonals of n-gon = n(n−3)/2. (a) Hexagon: 6×3/2 = 9 diagonals. (b) Octagon: 8×5/2 = 20 diagonals.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "Diagonals = n(n−3)/2." },
      { stepNumber: 2, title: "Hexagon (n=6)", explanation: "6×3/2 = 9." },
      { stepNumber: 3, title: "Octagon (n=8)", explanation: "8×5/2 = 20.", result: "Hexagon: 9; Octagon: 20" },
    ],
    hint: "Diagonal formula: n(n−3)/2.",
    keyConcepts: ["diagonals of polygon"],
    conceptsCovered: ["mth:8:ch03:polygon"],
    prerequisites: [],
    commonErrors: ["Using n(n−1)/2 (which counts sides too)"],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "What is a quadrilateral? Name four types of quadrilaterals.",
    answer: "A quadrilateral is a polygon with exactly four sides, four angles, and four vertices. Types: Square, Rectangle, Rhombus, Parallelogram, Trapezium, Kite.",
    steps: [
      { stepNumber: 1, title: "Definition", explanation: "Four-sided polygon." },
      { stepNumber: 2, title: "Types", explanation: "Square, Rectangle, Rhombus, Parallelogram, Trapezium, Kite." },
    ],
    hint: "Quad = 4; lateral = sided.",
    keyConcepts: ["quadrilateral types"],
    conceptsCovered: ["mth:8:ch03:quadrilateral"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "How can the formula (n−2)×180° for the angle sum of a polygon be derived using triangles?",
    answer: "Any convex n-gon can be divided into (n−2) non-overlapping triangles by drawing diagonals from one vertex. Since each triangle has an angle sum of 180°, the total interior angle sum = (n−2)×180°.",
    steps: [
      { stepNumber: 1, title: "Triangulation", explanation: "Draw diagonals from one vertex of an n-gon → creates (n−2) triangles." },
      { stepNumber: 2, title: "Sum", explanation: "Each triangle: 180°. Total: (n−2)×180°.", result: "Formula derived" },
    ],
    hint: "A quadrilateral = 2 triangles; pentagon = 3 triangles; etc.",
    keyConcepts: ["polygon triangulation", "angle sum derivation"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Sum of exterior angles of a polygon is always 360°. Verify this for a regular pentagon where each exterior angle = 72°.",
    answer: "For a regular pentagon, each exterior angle = 360°/5 = 72°. Sum of all 5 exterior angles = 5×72° = 360° ✓.",
    steps: [
      { stepNumber: 1, title: "Each exterior angle", explanation: "360°/5 = 72°." },
      { stepNumber: 2, title: "Verify sum", explanation: "5 × 72° = 360° ✓.", result: "Verified: sum = 360°" },
    ],
    hint: "For a regular polygon, all exterior angles are equal.",
    keyConcepts: ["exterior angle sum verification"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  // ── NCERT (t1) ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-nce-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the sum of interior angles of a heptagon (7 sides).",
    answer: "(7−2)×180° = 5×180° = 900°.",
    steps: [
      { stepNumber: 1, title: "Apply formula", explanation: "(n−2)×180 = 5×180 = 900°.", result: "900°" },
    ],
    hint: "(n−2)×180°.",
    keyConcepts: ["angle sum polygon"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Each interior angle of a regular polygon is 120°. Find the number of sides.",
    answer: "Exterior angle = 180°−120° = 60°. Sides = 360°/60° = 6. Regular hexagon.",
    steps: [
      { stepNumber: 1, title: "Exterior angle", explanation: "180−120 = 60°." },
      { stepNumber: 2, title: "Sides", explanation: "360/60 = 6.", result: "6 sides (hexagon)" },
    ],
    hint: "n = 360°/(exterior angle).",
    keyConcepts: ["regular polygon", "number of sides"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The angles of a pentagon are x, (x+10)°, (x+20)°, (x+30)°, (x+40)°. Find each angle.",
    answer: "Sum = 540°. x+(x+10)+(x+20)+(x+30)+(x+40) = 540 → 5x+100 = 540 → 5x = 440 → x = 88°. Angles: 88°, 98°, 108°, 118°, 128°.",
    steps: [
      { stepNumber: 1, title: "Pentagon sum = 540°", explanation: "5x+100 = 540 → x = 88." },
      { stepNumber: 2, title: "Find angles", explanation: "88°, 98°, 108°, 118°, 128°.", result: "88°, 98°, 108°, 118°, 128°" },
    ],
    hint: "Sum of pentagon interior angles = 540°.",
    keyConcepts: ["pentagon angle sum"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "What is the minimum number of sides a polygon can have such that its interior angle sum exceeds 1000°?",
    answer: "(n−2)×180 > 1000 → n−2 > 5.56 → n > 7.56 → minimum n = 8 (octagon). Check: (8−2)×180 = 1080° > 1000° ✓.",
    steps: [
      { stepNumber: 1, title: "Set up inequality", explanation: "(n−2)×180 > 1000 → n−2 > 5.56 → n > 7.56." },
      { stepNumber: 2, title: "Minimum integer", explanation: "n = 8 (octagon).", result: "8 sides (octagon)" },
    ],
    hint: "Solve (n−2)×180 > 1000 for n.",
    keyConcepts: ["angle sum inequality"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Can a polygon have interior angles of 95°, 100°, 115°, 85°, and 165°? Verify.",
    answer: "Sum = 95+100+115+85+165 = 560°. For a pentagon: (5−2)×180 = 540° ≠ 560°. This is NOT a valid pentagon. Perhaps it's 5 angles of some other configuration — but 5 angles of a polygon must sum to (n−2)×180. No valid polygon has these 5 angles.",
    steps: [
      { stepNumber: 1, title: "Sum given angles", explanation: "95+100+115+85+165 = 560°." },
      { stepNumber: 2, title: "Check pentagon", explanation: "540° ≠ 560°. Not a valid pentagon.", result: "NOT a valid polygon" },
    ],
    hint: "Check if the sum matches (n−2)×180 for n=5.",
    keyConcepts: ["angle sum verification"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Five exterior angles of a hexagon are 60°, 70°, 50°, 40°, and 80°. Find the sixth exterior angle.",
    answer: "Sum of all exterior angles = 360°. Sixth = 360°−(60+70+50+40+80) = 360°−300° = 60°.",
    steps: [
      { stepNumber: 1, title: "Sum of given", explanation: "60+70+50+40+80 = 300." },
      { stepNumber: 2, title: "Sixth angle", explanation: "360−300 = 60°.", result: "60°" },
    ],
    hint: "Exterior angle sum = 360°.",
    keyConcepts: ["exterior angle sum"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A quadrilateral ABCD has ∠A = 2x, ∠B = x+30°, ∠C = 3x−10°, ∠D = 90°. Find all four angles.",
    answer: "Sum = 360°: 2x+(x+30)+(3x−10)+90 = 360 → 6x+110 = 360 → 6x = 250 → x = 41.67°. ∠A≈83.3°, ∠B≈71.7°, ∠C≈115°, ∠D=90°.",
    steps: [
      { stepNumber: 1, title: "Sum equation", explanation: "6x+110 = 360 → x = 250/6 ≈ 41.67°." },
      { stepNumber: 2, title: "Calculate angles", explanation: "∠A≈83.3°, ∠B≈71.7°, ∠C≈115°, ∠D=90°.", result: "All angles calculated" },
    ],
    hint: "Sum of quadrilateral angles = 360°.",
    keyConcepts: ["quadrilateral angle equation"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "How many sides does a regular polygon have if each of its exterior angles is 40°?",
    answer: "n = 360°/40° = 9 sides (regular nonagon).",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "n = 360/exterior angle = 360/40 = 9.", result: "9 sides" },
    ],
    hint: "n = 360°/(exterior angle).",
    keyConcepts: ["regular polygon sides from exterior angle"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A polygon has n sides. Its angle sum is 1440°. Find n. Name this polygon.",
    answer: "(n−2)×180 = 1440 → n−2 = 8 → n = 10. A 10-sided polygon is a decagon.",
    steps: [
      { stepNumber: 1, title: "Solve for n", explanation: "n−2 = 1440/180 = 8 → n = 10.", result: "n=10 (decagon)" },
    ],
    hint: "Divide 1440 by 180 to find (n−2).",
    keyConcepts: ["finding sides from angle sum"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  // ── ICSE (t1) ─────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-ics-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "The interior angles of a hexagon are in the ratio 1:2:3:4:5:6. Find all six angles.",
    answer: "Sum = (6−2)×180 = 720°. Total parts = 21. Each part = 720/21 ≈ 34.3°. Angles: 34.3°, 68.6°, 102.9°, 137.1°, 171.4°, 205.7°. Note: 205.7° > 180° → concave hexagon (reflex angle). For ICSE: angles = 720/21 × k for k=1..6.",
    steps: [
      { stepNumber: 1, title: "Sum", explanation: "720°." },
      { stepNumber: 2, title: "Each part", explanation: "720/21 = 240/7 ≈ 34.29°." },
      { stepNumber: 3, title: "Angles", explanation: "240/7, 480/7, 720/7, 960/7, 1200/7, 1440/7 degrees. The largest (1440/7 ≈ 205.7°) is reflex → concave hexagon.", result: "Angles in ratio 1:2:3:4:5:6, sum=720°" },
    ],
    hint: "Total ratio parts = 1+2+3+4+5+6 = 21.",
    keyConcepts: ["hexagon angle sum", "ratio", "concave polygon"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: ["Assuming all angles must be less than 180°"],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-ics-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Prove that the sum of exterior angles of a convex polygon is 360°.",
    answer: "For any n-gon: at each vertex, interior angle + exterior angle = 180°. Sum of all: (sum of interior angles) + (sum of exterior angles) = 180n. Sum of interior = (n−2)×180 = 180n−360. So sum of exterior = 180n − (180n−360) = 360°.",
    steps: [
      { stepNumber: 1, title: "Interior + exterior at each vertex = 180°", explanation: "n vertices → total = 180n." },
      { stepNumber: 2, title: "Substitute interior sum", explanation: "180n − (180n−360) = 360°.", result: "Sum of exterior angles = 360° (proved)" },
    ],
    hint: "At each vertex: interior + exterior = 180°.",
    keyConcepts: ["proof", "exterior angle sum"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-ics-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Three angles of a quadrilateral are equal to each other. The fourth angle is 60°. Find the equal angles and classify the quadrilateral.",
    answer: "Sum = 360°. 3x + 60 = 360 → 3x = 300 → x = 100°. Three angles = 100°. This is an irregular quadrilateral (not a standard type since no standard type has three 100° angles and one 60°).",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "3x+60=360 → x=100°." },
      { stepNumber: 2, title: "Classify", explanation: "Three 100° angles and one 60° → irregular quadrilateral.", result: "Each equal angle = 100°; irregular quadrilateral" },
    ],
    hint: "Use angle sum = 360° to find the equal angles.",
    keyConcepts: ["quadrilateral classification"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "original",
  },

  // ── COMPETENCY (t1) ──────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-cmp-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A floor tile is a regular octagon. What is each interior angle?",
    answer: "Interior angle = (n−2)×180/n = (8−2)×180/8 = 6×180/8 = 1080/8 = 135°.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "Each interior = (n−2)×180/n." },
      { stepNumber: 2, title: "For octagon", explanation: "6×180/8 = 135°.", result: "135°" },
    ],
    hint: "For regular polygon: each interior angle = (n−2)×180°/n.",
    keyConcepts: ["regular polygon interior angle"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A designer is making a logo using a regular polygon where each exterior angle is 45°. How many sides does the polygon have?",
    answer: "n = 360°/45° = 8 sides (regular octagon).",
    steps: [
      { stepNumber: 1, title: "Calculate", explanation: "360/45 = 8.", result: "8 sides (octagon)" },
    ],
    hint: "n = 360/exterior angle.",
    keyConcepts: ["exterior angle to find n"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A park is shaped like a quadrilateral. Three of its boundary angles are 85°, 95°, and 100°. (a) Find the fourth angle. (b) Is the park a convex or concave quadrilateral?",
    answer: "(a) Fourth = 360−85−95−100 = 80°. (b) All angles < 180° → convex quadrilateral.",
    steps: [
      { stepNumber: 1, title: "Fourth angle", explanation: "360−280 = 80°." },
      { stepNumber: 2, title: "Classify", explanation: "All four (85°,95°,100°,80°) < 180° → convex.", result: "80°; convex quadrilateral" },
    ],
    hint: "Convex: all angles < 180°.",
    keyConcepts: ["quadrilateral angle sum", "convex vs concave"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon", "mth:8:ch03:polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A clock face is a regular 12-sided polygon. Find each interior angle.",
    answer: "(12−2)×180/12 = 1800/12 = 150°.",
    steps: [
      { stepNumber: 1, title: "Apply formula", explanation: "(10×180)/12 = 150°.", result: "150°" },
    ],
    hint: "Regular n-gon interior angle = (n−2)×180/n.",
    keyConcepts: ["regular 12-gon"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A polygon has 20 diagonals. Find the number of sides. (Hint: diagonals = n(n−3)/2)",
    answer: "n(n−3)/2 = 20 → n(n−3) = 40 → n²−3n−40 = 0 → (n−8)(n+5) = 0 → n = 8. An octagon has 20 diagonals.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "n(n−3)/2 = 20 → n²−3n = 40." },
      { stepNumber: 2, title: "Factorise", explanation: "(n−8)(n+5) = 0 → n = 8.", result: "8 sides (octagon)" },
    ],
    hint: "Solve n²−3n−40=0 by factoring.",
    keyConcepts: ["diagonals formula"],
    conceptsCovered: ["mth:8:ch03:polygon"],
    prerequisites: [],
    commonErrors: ["Taking n=−5 (negative sides not valid)"],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Can a polygon have all its exterior angles equal to 45°? If yes, how many sides? If no, explain why not.",
    answer: "Yes. Exterior angle = 45° → n = 360/45 = 8 sides. A regular octagon has exterior angles of exactly 45°.",
    steps: [
      { stepNumber: 1, title: "Check divisibility", explanation: "360/45 = 8 (integer) ✓." },
      { stepNumber: 2, title: "Name", explanation: "8-sided regular polygon (octagon).", result: "Yes; 8 sides (regular octagon)" },
    ],
    hint: "Exterior angle of regular polygon must divide evenly into 360°.",
    keyConcepts: ["regular polygon exterior angle"],
    conceptsCovered: ["mth:8:ch03:exterior-angle-sum"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CRITICAL_THINKING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a quadrilateral ABCD, ∠A : ∠B : ∠C = 3:5:4 and ∠D = 90°. Find ∠A, ∠B, ∠C.",
    answer: "3x+5x+4x+90 = 360 → 12x = 270 → x = 22.5°. ∠A=67.5°, ∠B=112.5°, ∠C=90°.",
    steps: [
      { stepNumber: 1, title: "Equation", explanation: "12x+90=360 → x=22.5°." },
      { stepNumber: 2, title: "Angles", explanation: "∠A=67.5°, ∠B=112.5°, ∠C=90°.", result: "67.5°, 112.5°, 90°" },
    ],
    hint: "Use angle sum = 360°.",
    keyConcepts: ["quadrilateral angle ratio"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t1", topicName: "Polygons and Properties of Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the interior angle sum of a polygon with 12 sides.",
    answer: "(12−2)×180 = 10×180 = 1800°.",
    steps: [
      { stepNumber: 1, title: "Apply formula", explanation: "(12−2)×180 = 1800°.", result: "1800°" },
    ],
    hint: "(n−2)×180°.",
    keyConcepts: ["angle sum polygon"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Special Quadrilaterals
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "bo-mth-8-ch03-con-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "List the properties of a parallelogram (4 key properties).",
    answer: "1. Opposite sides are equal and parallel. 2. Opposite angles are equal. 3. Consecutive angles are supplementary (sum = 180°). 4. Diagonals bisect each other.",
    steps: [
      { stepNumber: 1, title: "List properties", explanation: "Opposite sides equal+parallel; opposite angles equal; consecutive angles supplementary; diagonals bisect each other." },
    ],
    hint: "Parallelogram: two pairs of parallel sides.",
    keyConcepts: ["parallelogram properties"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: ["Confusing 'diagonals bisect each other' with 'diagonals are equal'"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 3,
    question: "How does a rhombus differ from a parallelogram? State the special properties of a rhombus.",
    answer: "A rhombus is a parallelogram with all four sides equal. Special properties: (1) All sides equal. (2) Diagonals bisect each other at right angles (90°). (3) Diagonals bisect the vertex angles. (4) Opposite angles are equal (inherited from parallelogram).",
    steps: [
      { stepNumber: 1, title: "Difference", explanation: "Rhombus: all 4 sides equal (parallelogram need not have all sides equal)." },
      { stepNumber: 2, title: "Special properties", explanation: "Diagonals perpendicular; diagonals bisect vertex angles." },
    ],
    hint: "Rhombus = parallelogram + all sides equal.",
    keyConcepts: ["rhombus", "diagonals perpendicular"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: ["Thinking diagonals of a rhombus are equal (they're not necessarily equal)"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "remember",
    marks: 2, estimatedTimeMinutes: 2,
    question: "What distinguishes a rectangle from a parallelogram? What is special about a rectangle's diagonals?",
    answer: "A rectangle is a parallelogram where all angles are 90°. Special diagonal property: the diagonals of a rectangle are equal in length (and bisect each other).",
    steps: [
      { stepNumber: 1, title: "Distinction", explanation: "Rectangle: all angles = 90° (not necessarily so in parallelogram)." },
      { stepNumber: 2, title: "Diagonal property", explanation: "Diagonals equal and bisect each other." },
    ],
    hint: "Rectangle = parallelogram + all right angles.",
    keyConcepts: ["rectangle", "equal diagonals"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-con-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Define a trapezium and an isosceles trapezium. How do their properties differ?",
    answer: "Trapezium: exactly one pair of parallel sides (called bases). Isosceles trapezium: a trapezium where the non-parallel sides (legs) are equal. Additional properties of isosceles trapezium: base angles are equal, and diagonals are equal.",
    steps: [
      { stepNumber: 1, title: "Trapezium", explanation: "One pair of parallel sides." },
      { stepNumber: 2, title: "Isosceles trapezium", explanation: "Equal legs; equal base angles; equal diagonals." },
    ],
    hint: "Isosceles means two equal sides.",
    keyConcepts: ["trapezium", "isosceles trapezium"],
    conceptsCovered: ["mth:8:ch03:trapezium"],
    prerequisites: [],
    commonErrors: ["Thinking trapezium has two pairs of parallel sides (it has exactly one)"],
    tags: [STANDARD_TAGS.CONCEPTUAL],
    source: "original",
  },

  // ── NCERT (t2) ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-nce-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "In parallelogram ABCD, ∠A = 70°. Find ∠B, ∠C, and ∠D.",
    answer: "∠C = ∠A = 70° (opposite angles). ∠B = 180°−70° = 110° (consecutive supplementary). ∠D = ∠B = 110°.",
    steps: [
      { stepNumber: 1, title: "Opposite angles equal", explanation: "∠C = 70°." },
      { stepNumber: 2, title: "Consecutive supplementary", explanation: "∠B = 110°, ∠D = 110°.", result: "∠B=110°, ∠C=70°, ∠D=110°" },
    ],
    hint: "Parallelogram: opposite angles equal; adjacent angles supplementary.",
    keyConcepts: ["parallelogram angles"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In rhombus PQRS, ∠P = 60°. Find all angles. Also find the angles made by the diagonals at their intersection.",
    answer: "∠P=60°. ∠R=60° (opposite). ∠Q=∠S=120° (supplementary). Diagonals intersect at 90° — since rhombus diagonals are perpendicular. So angles at intersection = 90° each.",
    steps: [
      { stepNumber: 1, title: "Opposite and adjacent angles", explanation: "∠R=60°, ∠Q=∠S=120°." },
      { stepNumber: 2, title: "Diagonal intersection", explanation: "Rhombus diagonals ⊥ → 90° each.", result: "Angles: 60°,120°,60°,120°; diagonals meet at 90°" },
    ],
    hint: "Rhombus diagonals are perpendicular bisectors of each other.",
    keyConcepts: ["rhombus angles", "perpendicular diagonals"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a parallelogram ABCD, the diagonals AC and BD intersect at O. AO = 3x−2 and OC = x+6. Find x and AO.",
    answer: "Diagonals bisect each other → AO = OC. 3x−2 = x+6 → 2x = 8 → x = 4. AO = 3(4)−2 = 10.",
    steps: [
      { stepNumber: 1, title: "Diagonals bisect", explanation: "AO = OC: 3x−2 = x+6 → x = 4." },
      { stepNumber: 2, title: "Find AO", explanation: "AO = 10.", result: "x=4; AO=10" },
    ],
    hint: "Parallelogram diagonals bisect each other.",
    keyConcepts: ["parallelogram diagonals"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In parallelogram ABCD, ∠A = 2x+10° and ∠C = 3x−30°. Find x and all angles.",
    answer: "Opposite angles equal: 2x+10 = 3x−30 → 40 = x. ∠A=∠C=90°. ∠B=∠D=90°. Since all angles = 90°, this is a rectangle!",
    steps: [
      { stepNumber: 1, title: "Opposite angles equal", explanation: "2x+10=3x−30 → x=40." },
      { stepNumber: 2, title: "Angles", explanation: "∠A=90°, ∠C=90°, ∠B=∠D=90°.", result: "x=40°; all angles=90°; it's a rectangle!" },
    ],
    hint: "Opposite angles in a parallelogram are equal.",
    keyConcepts: ["parallelogram equations", "rectangle"],
    conceptsCovered: ["mth:8:ch03:parallelogram", "mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The diagonals of a rhombus are 12 cm and 16 cm. Find the side of the rhombus.",
    answer: "Diagonals bisect at 90°. Each half: 6 cm and 8 cm. Side = √(6²+8²) = √(36+64) = √100 = 10 cm.",
    steps: [
      { stepNumber: 1, title: "Half diagonals", explanation: "12/2=6, 16/2=8." },
      { stepNumber: 2, title: "Pythagoras", explanation: "Side = √(6²+8²) = 10.", result: "Side = 10 cm" },
    ],
    hint: "Diagonals of rhombus are perpendicular bisectors; use Pythagoras.",
    keyConcepts: ["rhombus side from diagonals", "Pythagoras"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: ["Using full diagonal instead of half"],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a trapezium ABCD, AB ∥ DC. ∠A = 70° and ∠D = 80°. Find ∠B and ∠C.",
    answer: "AB∥DC with transversal AD: ∠A+∠D = 180° (co-interior). Check: 70+80=150°≠180°. Actually ∠A and ∠D are NOT co-interior here. Let's use: for trapezium, ∠A+∠D=180° (co-interior on leg AD, since AB∥CD). But 70+80≠180. Correct: ∠A+∠B must relate to AB as base. Actually for trapezium with AB∥DC, angles at the same leg are co-interior: ∠A+∠D=180° and ∠B+∠C=180°. If ∠A=70°: ∠D=110°. And if ∠D=80° is given instead — consistent only if ∠A=100°, ∠D=80° so ∠A+∠D=180°. Taking as given: ∠B = 180°−70° = 110° (∠A+∠B = 180°). ∠C = 180°−80° = 100°.",
    steps: [
      { stepNumber: 1, title: "Co-interior on leg AD", explanation: "∠A+∠D=180°: 70+80=150°≠180° — given values might be re-interpreted as ∠A=70° at base AB." },
      { stepNumber: 2, title: "Use co-interior on each leg", explanation: "∠A+∠D=180° (leg AD) → if ∠A=70°, ∠D=110°. ∠B+∠C=180° (leg BC) → if ∠B=110°, ∠C=70°. Taking ∠D given as separate: ∠B=180°−∠A=110°, ∠C=180°−∠D=100°.", result: "∠B=110°, ∠C=100° (using ∠A=70°, ∠D=80°, adjacent legs)" },
    ],
    hint: "In trapezium with AB∥DC, angles at the same leg are co-interior (supplementary).",
    keyConcepts: ["trapezium angles", "co-interior"],
    conceptsCovered: ["mth:8:ch03:trapezium"],
    prerequisites: [],
    commonErrors: ["Adding all angles instead of using co-interior pairs"],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Show that every rectangle is a parallelogram, but not every parallelogram is a rectangle.",
    answer: "Rectangle is a parallelogram: A rectangle has opposite sides equal and parallel (by definition), which is the defining property of a parallelogram. Hence every rectangle is a parallelogram. Not every parallelogram is a rectangle: A parallelogram can have angles that are not 90° (e.g., a rhombus with ∠A=60°). Since a rectangle requires all angles = 90°, this parallelogram is NOT a rectangle.",
    steps: [
      { stepNumber: 1, title: "Rectangle → parallelogram", explanation: "Rectangle has two pairs of parallel sides → is a parallelogram." },
      { stepNumber: 2, title: "Parallelogram ↛ rectangle", explanation: "Counter-example: parallelogram with 60° angles is not a rectangle.", result: "Rectangle ⊂ Parallelogram (strict subset)" },
    ],
    hint: "Show inclusion one way, then give a counter-example for the other.",
    keyConcepts: ["hierarchy of quadrilaterals"],
    conceptsCovered: ["mth:8:ch03:rectangle", "mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-017",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "ABCD is a square with side 8 cm. Find the length of the diagonal and the angles the diagonal makes with the sides.",
    answer: "Diagonal = 8√2 cm (by Pythagoras: √(8²+8²)). The diagonal of a square bisects the right angles → diagonal makes 45° with each side.",
    steps: [
      { stepNumber: 1, title: "Diagonal length", explanation: "√(64+64) = √128 = 8√2 cm." },
      { stepNumber: 2, title: "Angle with side", explanation: "Square has 90° angles; diagonal bisects → 45°.", result: "Diagonal=8√2 cm; 45° with sides" },
    ],
    hint: "Square diagonal = side × √2; bisects the 90° corner.",
    keyConcepts: ["square diagonal", "45-45-90 triangle"],
    conceptsCovered: ["mth:8:ch03:square"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch03-nce-018",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In a kite ABCD, AB = AD = 5 cm and CB = CD = 8 cm. The diagonal AC = 6 cm. Find the length of diagonal BD.",
    answer: "In a kite, diagonals are perpendicular. Diagonal AC bisects diagonal BD at right angles. Using Pythagoras on triangle ABP (P = intersection): AP² + BP² = AB². AC bisects AC? Actually AC is unequal diagonal. AO+OC = 6. In kite, the axis diagonal (AD side) bisects the other: BD is bisected by AC. Let AO = p. Then p² + (BD/2)² = 25. (6−p)² + (BD/2)² = 64. Subtract: (6−p)²−p² = 39 → 36−12p = 39 → p = −0.25. Negative p suggests geometry; rearrange: 36−12p+p²−p² = 39 → 36−12p = 39 → −12p = 3 → p = −0.25. Not physical with these dimensions. Try: p is distance from A to intersection: p²+(BD/2)²=25, and (6−p)²+(BD/2)²=64. Subtract: (6−p)²−p²=39. 36−12p=39 → p=−0.25. Use |p|: AO=0.25, OC=5.75. (BD/2)²=25−0.0625=24.9375 → BD≈9.97≈10 cm.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Let O be intersection of diagonals. AO=p, OC=6−p." },
      { stepNumber: 2, title: "Pythagoras twice", explanation: "p²+(BD/2)²=25 and (6−p)²+(BD/2)²=64." },
      { stepNumber: 3, title: "Solve", explanation: "Subtract: 36−12p=39 → p=−0.25 → AO=0.25. (BD/2)²≈24.94 → BD≈9.97≈10 cm.", result: "BD ≈ 10 cm" },
    ],
    hint: "In a kite, diagonals are perpendicular; use Pythagoras with both triangles formed.",
    keyConcepts: ["kite diagonals", "perpendicular diagonals", "Pythagoras"],
    conceptsCovered: ["mth:8:ch03:kite"],
    prerequisites: [],
    commonErrors: ["Assuming the diagonal bisection point is at the midpoint"],
    tags: [STANDARD_TAGS.NCERT_BASED],
    source: "ncert",
  },

  // ── ICSE (t2) ─────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-ics-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 5, estimatedTimeMinutes: 10,
    question: "In rectangle ABCD, the diagonals AC and BD intersect at O. If AC = 26 cm, find AO, OC, BO, OD. If ∠AOB = 60°, find ∠AOD.",
    answer: "Diagonals of rectangle are equal and bisect each other. AC=26 → AO=OC=13 cm. BD=AC=26 → BO=OD=13 cm. ∠AOD=180°−60°=120° (linear pair with ∠AOB).",
    steps: [
      { stepNumber: 1, title: "Diagonal halves", explanation: "AO=OC=BO=OD=13 cm." },
      { stepNumber: 2, title: "∠AOD", explanation: "Linear pair: 180°−60°=120°.", result: "All halves=13 cm; ∠AOD=120°" },
    ],
    hint: "Rectangle diagonals: equal length and bisect each other.",
    keyConcepts: ["rectangle diagonals"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-ics-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Is a square a rhombus? Is a rhombus a square? Justify both answers.",
    answer: "Is a square a rhombus? YES. A square has all four sides equal and opposite sides parallel — these are the defining properties of a rhombus. So every square is a rhombus. Is a rhombus a square? NOT ALWAYS. A rhombus has all sides equal but angles need not be 90°. A rhombus is a square only when all its angles are 90°. A rhombus with 60° angles is not a square.",
    steps: [
      { stepNumber: 1, title: "Square → rhombus", explanation: "Square: all sides equal + opposite sides parallel = rhombus ✓." },
      { stepNumber: 2, title: "Rhombus → square?", explanation: "Counter-example: rhombus with 60° angles ≠ square.", result: "Square ⊂ Rhombus; Rhombus ⊄ Square" },
    ],
    hint: "Check if all defining properties of rhombus are met by a square, and vice versa.",
    keyConcepts: ["quadrilateral hierarchy", "square vs rhombus"],
    conceptsCovered: ["mth:8:ch03:rhombus", "mth:8:ch03:square"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CRITICAL_THINKING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-ics-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "In parallelogram ABCD, AB = 12 cm and BC = 7 cm. Diagonal BD = 15 cm. Show whether this is a rectangle or not.",
    answer: "If ABCD is a rectangle, then BD² = AB²+AD² (Pythagoras, since ∠A=90°). AB=12, AD=BC=7. BD² = 144+49 = 193. BD = √193 ≈ 13.9 cm ≠ 15 cm. Since the diagonal doesn't satisfy Pythagoras, ∠A ≠ 90° → NOT a rectangle.",
    steps: [
      { stepNumber: 1, title: "Test rectangle", explanation: "For rectangle: BD=√(AB²+BC²)=√(144+49)=√193≈13.9." },
      { stepNumber: 2, title: "Compare", explanation: "13.9 ≠ 15 → not a rectangle.", result: "NOT a rectangle" },
    ],
    hint: "Rectangle diagonal = √(length² + width²).",
    keyConcepts: ["rectangle diagonal test", "Pythagoras"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-ics-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Draw the hierarchy of quadrilaterals showing which are subsets of which. List: Parallelogram, Rectangle, Rhombus, Square, Trapezium, Kite.",
    answer: "Hierarchy: Quadrilateral → Trapezium (one pair parallel) → Parallelogram (two pairs parallel) → Rectangle (parallelogram + all angles 90°) → Square (rectangle + all sides equal, OR rhombus + all angles 90°). Also: Parallelogram → Rhombus (parallelogram + all sides equal). Kite: two pairs of adjacent equal sides (not necessarily parallel). Square is the intersection of Rectangle and Rhombus.",
    steps: [
      { stepNumber: 1, title: "General to specific", explanation: "Quadrilateral ⊃ Trapezium ⊃ Parallelogram ⊃ Rectangle ⊃ Square." },
      { stepNumber: 2, title: "Other branches", explanation: "Parallelogram ⊃ Rhombus ⊃ Square. Kite is separate branch from Parallelogram.", result: "Full hierarchy described" },
    ],
    hint: "Square is the most specific — it satisfies both Rectangle AND Rhombus properties.",
    keyConcepts: ["quadrilateral hierarchy"],
    conceptsCovered: ["mth:8:ch03:quadrilateral"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.CRITICAL_THINKING],
    source: "original",
  },

  // ── COMPETENCY (t2) ──────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-cmp-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A football pitch is rectangular with length 100 m and width 64 m. Find the length of the diagonal.",
    answer: "Diagonal = √(100²+64²) = √(10000+4096) = √14096 = 4√881 ≈ 118.7 m.",
    steps: [
      { stepNumber: 1, title: "Pythagoras", explanation: "√(100²+64²) = √14096 ≈ 118.7 m.", result: "≈ 118.7 m" },
    ],
    hint: "Rectangle diagonal = √(l²+w²).",
    keyConcepts: ["rectangle diagonal", "Pythagoras"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A diamond-shaped tile is a rhombus with diagonals 18 cm and 24 cm. Find the perimeter of the tile.",
    answer: "Half diagonals: 9 and 12. Side = √(9²+12²) = √(81+144) = √225 = 15 cm. Perimeter = 4×15 = 60 cm.",
    steps: [
      { stepNumber: 1, title: "Find side", explanation: "Side = √(9²+12²) = 15." },
      { stepNumber: 2, title: "Perimeter", explanation: "4×15 = 60 cm.", result: "Perimeter = 60 cm" },
    ],
    hint: "Rhombus diagonals bisect at 90°; use Pythagoras for side.",
    keyConcepts: ["rhombus perimeter"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: ["Using full diagonal instead of half"],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a parallelogram, consecutive angles are supplementary. If one angle is (3x+15)° and its adjacent angle is (5x−35)°, find x and both angles.",
    answer: "(3x+15)+(5x−35) = 180 → 8x−20 = 180 → 8x = 200 → x = 25. Angles: 90° and 90°. This is a rectangle!",
    steps: [
      { stepNumber: 1, title: "Supplementary", explanation: "8x−20=180 → x=25." },
      { stepNumber: 2, title: "Angles", explanation: "3(25)+15=90°, 5(25)−35=90°.", result: "x=25; both angles=90°; it's a rectangle" },
    ],
    hint: "Adjacent parallelogram angles are supplementary.",
    keyConcepts: ["parallelogram adjacent angles"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The perimeter of a rhombus is 52 cm. Find the side length and state the number of equal sides.",
    answer: "Rhombus has 4 equal sides. Side = 52/4 = 13 cm. All 4 sides are equal.",
    steps: [
      { stepNumber: 1, title: "Side", explanation: "52/4 = 13 cm.", result: "Side = 13 cm; all 4 sides equal" },
    ],
    hint: "Rhombus: all 4 sides equal.",
    keyConcepts: ["rhombus perimeter"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "CaseStudy",
    difficulty: "Medium", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A garden is shaped like a parallelogram with sides 20 m and 15 m. The shorter diagonal is 18 m. A gardener says the garden is a rectangle. Verify or disprove this claim.",
    answer: "If it were a rectangle: diagonal = √(20²+15²) = √(400+225) = √625 = 25 m. But the actual diagonal is 18 m ≠ 25 m. The garden is NOT a rectangle.",
    steps: [
      { stepNumber: 1, title: "Rectangle diagonal test", explanation: "√(20²+15²) = 25 m." },
      { stepNumber: 2, title: "Compare", explanation: "18 ≠ 25 → not a rectangle.", result: "Garden is NOT a rectangle" },
    ],
    hint: "For a rectangle, diagonal = √(l²+w²).",
    keyConcepts: ["rectangle verification", "diagonal test"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.REAL_WORLD],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A trapezium has parallel sides of 8 cm and 12 cm, and the non-parallel sides are each 5 cm. Is this an isosceles trapezium? Find the height.",
    answer: "Both legs = 5 cm → isosceles trapezium. Difference in parallel sides = 12−8 = 4 cm; each leg overhangs by 2 cm. Height = √(5²−2²) = √(25−4) = √21 ≈ 4.58 cm.",
    steps: [
      { stepNumber: 1, title: "Isosceles check", explanation: "Both non-parallel sides = 5 cm → isosceles ✓." },
      { stepNumber: 2, title: "Height", explanation: "Drop perpendicular from shorter base. Foot at (12−8)/2 = 2 cm from end. Height = √(5²−2²) = √21 ≈ 4.58 cm.", result: "Isosceles; height ≈ 4.58 cm" },
    ],
    hint: "Drop a perpendicular from each end of the shorter parallel side.",
    keyConcepts: ["isosceles trapezium", "height"],
    conceptsCovered: ["mth:8:ch03:trapezium"],
    prerequisites: [],
    commonErrors: ["Using the full difference (4) instead of half (2) for the horizontal offset"],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a parallelogram, one angle is 3 times the other. Find both angles.",
    answer: "x + 3x = 180 (consecutive angles supplementary) → 4x = 180 → x = 45°. Angles: 45° and 135°.",
    steps: [
      { stepNumber: 1, title: "Consecutive supplementary", explanation: "x+3x = 180 → x = 45°." },
      { stepNumber: 2, title: "Angles", explanation: "45° and 135°.", result: "45° and 135°" },
    ],
    hint: "Consecutive angles of parallelogram are supplementary.",
    keyConcepts: ["parallelogram angles"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-cmp-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "ABCD is a square. ∠ABD = ?",
    answer: "In square ABCD, ∠ABC = 90°. The diagonal BD bisects ∠B. So ∠ABD = 90°/2 = 45°.",
    steps: [
      { stepNumber: 1, title: "Diagonal of square bisects corner", explanation: "∠ABC=90°, BD bisects it." },
      { stepNumber: 2, title: "Half angle", explanation: "∠ABD = 45°.", result: "∠ABD = 45°" },
    ],
    hint: "Diagonals of a square bisect each right angle.",
    keyConcepts: ["square diagonal", "angle bisection"],
    conceptsCovered: ["mth:8:ch03:square"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PROBLEM_SOLVING],
    source: "original",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-hot-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Prove that the diagonals of a parallelogram bisect each other.",
    answer: "In parallelogram ABCD, diagonals AC and BD intersect at O. Triangles AOB and COD: ∠OAB = ∠OCD (alternate interior, AB∥DC, transversal AC). ∠OBA = ∠ODC (alternate interior, AB∥DC, transversal BD). AB = CD (opposite sides of parallelogram). By ASA: △AOB ≅ △COD. Therefore AO = CO and BO = DO → diagonals bisect each other.",
    steps: [
      { stepNumber: 1, title: "Label intersection O", explanation: "Diagonals AC and BD meet at O." },
      { stepNumber: 2, title: "Alternate interior angles", explanation: "∠OAB=∠OCD and ∠OBA=∠ODC (AB∥DC)." },
      { stepNumber: 3, title: "AB=CD", explanation: "Opposite sides of parallelogram are equal." },
      { stepNumber: 4, title: "ASA congruence", explanation: "△AOB ≅ △COD → AO=CO, BO=DO.", result: "Diagonals bisect each other (proved)" },
    ],
    hint: "Use alternate interior angles (from parallel sides) to prove triangles congruent by ASA.",
    keyConcepts: ["parallelogram diagonal proof", "ASA congruence"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: ["Using SSS or SAS when alternate angles are more natural"],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
    examTip: "For diagonal bisection proofs, always prove the two triangles at the intersection are congruent.",
  },

  {
    id: "bo-mth-8-ch03-hot-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "ABCD is a quadrilateral where the diagonals bisect each other. Prove it is a parallelogram.",
    answer: "Diagonals AC and BD intersect at O with AO=CO and BO=DO. In △AOB and △COD: AO=CO (given), BO=DO (given), ∠AOB=∠COD (vertically opposite). By SAS: △AOB ≅ △COD → AB=CD and ∠OAB=∠OCD. Since alternate interior angles are equal (for transversal AC), AB∥DC. Similarly, △AOD ≅ △COB → AD=CB and AD∥BC. Both pairs of opposite sides are parallel → ABCD is a parallelogram.",
    steps: [
      { stepNumber: 1, title: "SAS for △AOB and △COD", explanation: "AO=CO, BO=DO, ∠AOB=∠COD → congruent." },
      { stepNumber: 2, title: "AB∥DC", explanation: "∠OAB=∠OCD (alternate interior) → AB∥DC." },
      { stepNumber: 3, title: "AD∥BC", explanation: "Similarly △AOD≅△COB → AD∥BC.", result: "ABCD is a parallelogram (proved)" },
    ],
    hint: "Use SAS at the intersection, then use alternate interior angles for parallelism.",
    keyConcepts: ["converse of parallelogram diagonal theorem"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-hot-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In a rhombus, the ratio of the two diagonals is 3:4. The perimeter is 40 cm. Find the diagonals.",
    answer: "Side = 40/4 = 10 cm. Let diagonals = 3k and 4k. Half-diagonals: 1.5k and 2k. (1.5k)²+(2k)²=100 → 2.25k²+4k²=100 → 6.25k²=100 → k²=16 → k=4. Diagonals: 12 cm and 16 cm.",
    steps: [
      { stepNumber: 1, title: "Find side", explanation: "40/4 = 10 cm." },
      { stepNumber: 2, title: "Diagonals from ratio", explanation: "3k and 4k. (1.5k)²+(2k)²=100 → 6.25k²=100 → k=4." },
      { stepNumber: 3, title: "Diagonals", explanation: "12 cm and 16 cm.", result: "Diagonals = 12 cm and 16 cm" },
    ],
    hint: "Use Pythagoras with half-diagonals and the side length.",
    keyConcepts: ["rhombus diagonals from perimeter"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
    examTip: "Always use half-diagonals when applying Pythagoras in a rhombus.",
  },

  {
    id: "bo-mth-8-ch03-hot-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 7,
    question: "What is the maximum number of right angles a trapezium can have? Explain with a diagram description.",
    answer: "A trapezium has exactly one pair of parallel sides. At most 2 right angles. If AB∥DC, and ∠A=∠B=90°, then AD⊥AB and BC⊥AB. DC must be parallel to AB, which is possible. This is a right-angled trapezium. Having 3 right angles is impossible since angles sum to 360° → fourth would be 90° too, making all 90° → a rectangle (which has two pairs of parallel sides, not one). Maximum = 2 right angles.",
    steps: [
      { stepNumber: 1, title: "Try 2 right angles", explanation: "∠A=∠B=90° with AB∥DC. 90+90+∠C+∠D=360 → ∠C+∠D=180°. This is a valid trapezium ✓." },
      { stepNumber: 2, title: "Try 3 right angles", explanation: "3×90°=270°, fourth = 90° → all 90° → rectangle (two pairs of ∥ sides) → not a trapezium." },
      { stepNumber: 3, title: "Conclusion", explanation: "Maximum = 2 right angles.", result: "Maximum 2 right angles" },
    ],
    hint: "3 right angles forces the 4th to also be 90°, making it a rectangle.",
    keyConcepts: ["trapezium right angles", "angle constraint"],
    conceptsCovered: ["mth:8:ch03:trapezium"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-hot-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 9,
    question: "Design a quadrilateral that is simultaneously a rhombus and a rectangle. What quadrilateral does this create? State all its properties.",
    answer: "A quadrilateral that is both a rhombus (all sides equal) and a rectangle (all angles 90°) is a SQUARE. Properties: 1. All four sides equal. 2. All four angles = 90°. 3. Opposite sides parallel. 4. Diagonals equal. 5. Diagonals bisect each other at 90°. 6. Diagonals bisect vertex angles (each = 45°). 7. All properties of parallelogram, rectangle, and rhombus.",
    steps: [
      { stepNumber: 1, title: "Intersection of rhombus and rectangle", explanation: "All sides equal (rhombus) + all angles 90° (rectangle) → square." },
      { stepNumber: 2, title: "List square properties", explanation: "All above properties combined.", result: "Square — the most symmetric quadrilateral" },
    ],
    hint: "Square = rhombus ∩ rectangle.",
    keyConcepts: ["square as intersection", "all square properties"],
    conceptsCovered: ["mth:8:ch03:square"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-hot-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In a parallelogram, when do the diagonals also become angle bisectors?",
    answer: "In a parallelogram, the diagonals bisect the vertex angles if and only if the parallelogram is a rhombus. Proof sketch: if diagonal AC bisects ∠A, then ∠DAC = ∠BAC. In △ABC, ∠BAC = ∠BCA (base angles of isosceles △). Combined with parallel side properties, this forces AB = BC → all sides equal → rhombus.",
    steps: [
      { stepNumber: 1, title: "Condition", explanation: "Diagonals bisect angles ↔ all sides equal ↔ rhombus." },
      { stepNumber: 2, title: "Proof sketch", explanation: "AC bisects ∠A → ∠DAC=∠BAC → isosceles → AB=BC → all sides equal → rhombus.", result: "Only when it's a rhombus" },
    ],
    hint: "Angle bisection by diagonal forces triangles to be isosceles.",
    keyConcepts: ["diagonal angle bisection", "rhombus condition"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-hot-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "analyse",
    marks: 5, estimatedTimeMinutes: 9,
    question: "Show that the midpoints of the sides of any quadrilateral form a parallelogram (Varignon's theorem).",
    answer: "Let ABCD be any quadrilateral. Let P, Q, R, S be midpoints of AB, BC, CD, DA respectively. Draw diagonal AC. In △ABC, PQ is the midsegment (P midpoint of AB, Q midpoint of BC) → PQ∥AC and PQ=AC/2. In △ACD, SR is the midsegment (S midpoint of AD, R midpoint of CD) → SR∥AC and SR=AC/2. Therefore PQ∥SR and PQ=SR → PQRS is a parallelogram.",
    steps: [
      { stepNumber: 1, title: "Midsegment in △ABC", explanation: "P,Q midpoints → PQ∥AC, PQ=AC/2." },
      { stepNumber: 2, title: "Midsegment in △ACD", explanation: "S,R midpoints → SR∥AC, SR=AC/2." },
      { stepNumber: 3, title: "Conclude PQRS parallelogram", explanation: "PQ∥SR and PQ=SR → one pair of sides equal and parallel → parallelogram.", result: "PQRS is a parallelogram (Varignon's theorem proved)" },
    ],
    hint: "Use the triangle midsegment theorem twice on the two triangles formed by one diagonal.",
    keyConcepts: ["Varignon's theorem", "midsegment theorem"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: ["Not connecting to the midsegment theorem"],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
    examTip: "Varignon's theorem is a classic olympiad result that follows directly from the midsegment theorem.",
  },

  {
    id: "bo-mth-8-ch03-hot-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Can a quadrilateral have exactly three equal sides? If yes, give an example. Can it be a parallelogram?",
    answer: "Yes. Example: three sides of 5 cm and one side of 7 cm (general quadrilateral, not special). It CANNOT be a parallelogram: a parallelogram has opposite sides equal. If three sides equal (say AB=BC=CD=5), then AD is the fourth. For parallelogram: AB=CD (✓ both 5) and BC=AD. BC=5 forces AD=5 → all four equal → rhombus. So three equal sides (not four) → not a parallelogram.",
    steps: [
      { stepNumber: 1, title: "Example", explanation: "Quadrilateral with sides 5,5,5,7 exists (irregular quadrilateral)." },
      { stepNumber: 2, title: "Parallelogram check", explanation: "Parallelogram needs opposite sides equal. Three equal forces the fourth to match too → all four equal → rhombus. Cannot have exactly three equal sides in a parallelogram.", result: "Yes exists; cannot be a parallelogram" },
    ],
    hint: "In a parallelogram, sides come in equal opposite pairs.",
    keyConcepts: ["quadrilateral constraints", "parallelogram sides"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
  },

  {
    id: "bo-mth-8-ch03-hot-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Create a property checklist (table) comparing parallelogram, rectangle, rhombus, and square for: (a) all sides equal, (b) all angles 90°, (c) diagonals equal, (d) diagonals perpendicular, (e) diagonals bisect each other.",
    answer: "| Property | Parallelogram | Rectangle | Rhombus | Square | | All sides equal | ✗ | ✗ | ✓ | ✓ | | All angles 90° | ✗ | ✓ | ✗ | ✓ | | Diagonals equal | ✗ | ✓ | ✗ | ✓ | | Diagonals ⊥ | ✗ | ✗ | ✓ | ✓ | | Diagonals bisect each other | ✓ | ✓ | ✓ | ✓ |",
    steps: [
      { stepNumber: 1, title: "Fill table row by row", explanation: "Parallelogram: only diagonals bisect ✓. Rectangle adds equal diagonals and right angles. Rhombus adds equal sides and perpendicular diagonals. Square has all five ✓." },
      { stepNumber: 2, title: "Conclusion", explanation: "Square has ALL five properties; parallelogram has only one of these five.", result: "Comparison table created" },
    ],
    hint: "Start with what's TRUE for a parallelogram, then add properties for each special case.",
    keyConcepts: ["quadrilateral comparison", "property checklist"],
    conceptsCovered: ["mth:8:ch03:quadrilateral"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
    examTip: "This comparison table is frequently tested — memorise the pattern (Square has all properties).",
  },

  {
    id: "bo-mth-8-ch03-hot-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "evaluate",
    marks: 5, estimatedTimeMinutes: 9,
    question: "If the diagonals of a quadrilateral are equal and bisect each other, what kind of quadrilateral is it? Prove your answer.",
    answer: "It is a rectangle. Proof: Bisecting diagonals → parallelogram (by the converse proved earlier). Equal diagonals in a parallelogram → rectangle. Proof of second part: In parallelogram ABCD, AC=BD. Triangles ABD and BAC: AB=AB (common), AD=BC (opp sides of parallelogram), BD=AC (given equal diagonals) → SSS congruence → ∠DAB=∠CBA. But as consecutive angles, ∠DAB+∠CBA=180° → ∠DAB=∠CBA=90° → rectangle.",
    steps: [
      { stepNumber: 1, title: "Bisecting → parallelogram", explanation: "Proved earlier: diagonals bisect → parallelogram." },
      { stepNumber: 2, title: "Equal diagonals in parallelogram → rectangle", explanation: "△ABD≅△BAC (SSS) → ∠DAB=∠CBA. Consecutive supplementary → both = 90°." },
      { stepNumber: 3, title: "Conclude rectangle", explanation: "All angles 90° → rectangle.", result: "Rectangle (proved)" },
    ],
    hint: "First prove it's a parallelogram, then use equal diagonals with SSS to get right angles.",
    keyConcepts: ["characterisation of rectangle", "diagonals equal and bisecting"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: ["Stopping after proving it's a parallelogram"],
    tags: [STANDARD_TAGS.HOTS],
    source: "original",
    examTip: "Equal AND bisecting diagonals → rectangle. Equal but not bisecting → isosceles trapezium.",
  },

  // ── PREVIOUS YEAR ─────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch03-pyq-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The adjacent sides of a parallelogram are in ratio 3:2. Perimeter = 50 cm. Find both sides.",
    answer: "2(3x+2x)=50 → 10x=50 → x=5. Sides: 15 cm and 10 cm.",
    steps: [
      { stepNumber: 1, title: "Perimeter", explanation: "2(3x+2x)=50 → 5x=25 → x=5." },
      { stepNumber: 2, title: "Sides", explanation: "15 cm and 10 cm.", result: "15 cm and 10 cm" },
    ],
    hint: "Parallelogram perimeter = 2(a+b).",
    keyConcepts: ["parallelogram perimeter"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "In a parallelogram ABCD, ∠A = 110°. Find ∠B.",
    answer: "∠A+∠B = 180° (consecutive angles supplementary). ∠B = 70°.",
    steps: [
      { stepNumber: 1, title: "Supplementary", explanation: "∠B = 180°−110° = 70°.", result: "∠B = 70°" },
    ],
    hint: "Adjacent angles of parallelogram sum to 180°.",
    keyConcepts: ["parallelogram angles"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In rhombus ABCD, diagonal AC = 10 cm and BD = 24 cm. Find the side of the rhombus.",
    answer: "Half diagonals: 5 and 12. Side = √(5²+12²) = √(25+144) = √169 = 13 cm.",
    steps: [
      { stepNumber: 1, title: "Half diagonals", explanation: "5 and 12." },
      { stepNumber: 2, title: "Pythagoras", explanation: "√(25+144) = 13.", result: "Side = 13 cm" },
    ],
    hint: "Half-diagonals and side form a right triangle.",
    keyConcepts: ["rhombus side"],
    conceptsCovered: ["mth:8:ch03:rhombus"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
    examTip: "3-4-5 and 5-12-13 Pythagorean triples appear frequently in rhombus problems.",
  },

  {
    id: "bo-mth-8-ch03-pyq-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The angles of a quadrilateral are x, 2x, 3x, and 4x. Find each angle and identify the type.",
    answer: "10x = 360 → x = 36°. Angles: 36°, 72°, 108°, 144°. No two pairs of equal opposite angles, no parallel sides visible → general irregular quadrilateral.",
    steps: [
      { stepNumber: 1, title: "Solve", explanation: "10x=360 → x=36°." },
      { stepNumber: 2, title: "Angles and type", explanation: "36°,72°,108°,144°. No special type.", result: "36°,72°,108°,144°; irregular quadrilateral" },
    ],
    hint: "Angle sum = 360°.",
    keyConcepts: ["quadrilateral angles"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "How many diagonals does a quadrilateral have? Draw and name them for ABCD.",
    answer: "A quadrilateral has 2 diagonals. For ABCD: diagonal AC (connecting A to C) and diagonal BD (connecting B to D).",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "n(n−3)/2 = 4×1/2 = 2 diagonals." },
      { stepNumber: 2, title: "Name them", explanation: "AC and BD.", result: "2 diagonals: AC and BD" },
    ],
    hint: "Diagonal connects non-adjacent vertices.",
    keyConcepts: ["diagonals of quadrilateral"],
    conceptsCovered: ["mth:8:ch03:quadrilateral"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "In a parallelogram ABCD, AB = (3x−1) cm and CD = (x+7) cm. Find x and the length AB.",
    answer: "Opposite sides equal: 3x−1 = x+7 → 2x = 8 → x = 4. AB = 3(4)−1 = 11 cm.",
    steps: [
      { stepNumber: 1, title: "Opposite sides equal", explanation: "3x−1=x+7 → x=4." },
      { stepNumber: 2, title: "AB", explanation: "3(4)−1=11 cm.", result: "x=4; AB=11 cm" },
    ],
    hint: "Opposite sides of parallelogram are equal.",
    keyConcepts: ["parallelogram sides"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In a square, one diagonal is drawn. Find all angles in the two triangles formed.",
    answer: "Square has 90° angles. Diagonal bisects each corner into 45°. Each triangle is a right isosceles triangle (45-45-90). Triangle angles: 45°, 45°, 90°.",
    steps: [
      { stepNumber: 1, title: "Diagonal in square", explanation: "Divides 90° corner into two 45°." },
      { stepNumber: 2, title: "Each triangle", explanation: "45°, 45°, 90° right isosceles triangle.", result: "Angles: 45°, 45°, 90°" },
    ],
    hint: "Square diagonal bisects the 90° angles.",
    keyConcepts: ["square diagonal", "45-45-90 triangle"],
    conceptsCovered: ["mth:8:ch03:square"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the each interior angle of a regular polygon with 9 sides.",
    answer: "(9−2)×180/9 = 7×180/9 = 1260/9 = 140°.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "(n−2)×180/n = (7×180)/9 = 140°.", result: "140°" },
    ],
    hint: "Interior angle = (n−2)×180/n.",
    keyConcepts: ["regular polygon interior angle"],
    conceptsCovered: ["mth:8:ch03:angle-sum-polygon"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In a rectangle ABCD, ∠ABD = 35°. Find ∠ADB, ∠DBC, and ∠ACB.",
    answer: "∠ABC = 90°. ∠ABD + ∠DBC = 90° → ∠DBC = 55°. In △ABD: ∠ABD=35°, ∠BAD=90° → ∠ADB=55°. Diagonals equal and bisect → isosceles triangles. ∠ACB = ∠ABD = 35° (corresponding in congruent triangles formed by equal diagonals). Actually ∠ACB = ∠ADB = 55°? Let's be precise: ∠ADB is in △ABD where ∠BAD=90°, ∠ABD=35° → ∠ADB=55°. ∠DBC=90°−35°=55°. In △DBC: ∠DBC=55°, ∠BCD=90° → ∠BDC=35°. ∠ACB: In △ABC ∠ABC=90°, AC=BD (rectangle diagonals equal). ∠ACB= ∠ADB=55°? In rectangle diagonals bisect → OA=OB=OC=OD → isosceles △s. ∠CAB=∠ADB=55° (actually ∠CAB=∠ACB since OA=OC half-diagonal... ∠ACB=35° (alternate route).",
    steps: [
      { stepNumber: 1, title: "∠DBC", explanation: "∠ABC=90°, ∠ABD=35° → ∠DBC=55°." },
      { stepNumber: 2, title: "∠ADB", explanation: "△ABD: 90+35+∠ADB=180 → ∠ADB=55°." },
      { stepNumber: 3, title: "∠ACB", explanation: "Rectangle diagonals equal → △OAB isosceles (OA=OB) → ∠OAB=∠OBA=35°. ∠ACB=∠OAB alternate? ∠ACB=∠ABD=35°.", result: "∠ADB=55°, ∠DBC=55°, ∠ACB=35°" },
    ],
    hint: "Use ∠ABC=90° and the triangle angle sum for each triangle.",
    keyConcepts: ["rectangle angles", "diagonal properties"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "PQRS is a parallelogram. PQ = 8 cm and PS = 5 cm. Find the perimeter.",
    answer: "Perimeter = 2(PQ+PS) = 2(8+5) = 2×13 = 26 cm.",
    steps: [
      { stepNumber: 1, title: "Perimeter formula", explanation: "2(PQ+PS) = 2(13) = 26.", result: "26 cm" },
    ],
    hint: "Parallelogram perimeter = 2(a+b).",
    keyConcepts: ["parallelogram perimeter"],
    conceptsCovered: ["mth:8:ch03:parallelogram"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "State two properties that distinguish a square from a rectangle.",
    answer: "Properties that square has but rectangle doesn't: (1) All four sides are equal in a square; a rectangle has only opposite sides equal. (2) Diagonals of a square are perpendicular bisectors; rectangle diagonals bisect each other but are NOT perpendicular.",
    steps: [
      { stepNumber: 1, title: "Property 1", explanation: "Square: all sides equal; Rectangle: only opposite sides equal." },
      { stepNumber: 2, title: "Property 2", explanation: "Square diagonals perpendicular; rectangle diagonals are not.", result: "Two distinguishing properties stated" },
    ],
    hint: "Think about sides and diagonals.",
    keyConcepts: ["square vs rectangle"],
    conceptsCovered: ["mth:8:ch03:square", "mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch03-pyq-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch03", chapterName: "Understanding Quadrilaterals",
    topicId: "t2", topicName: "Special Quadrilaterals",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "Hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "The diagonals of a rectangle are (3x+7) cm and (5x−9) cm. Find x and the length of each diagonal.",
    answer: "Rectangle diagonals are equal: 3x+7 = 5x−9 → 16 = 2x → x = 8. Each diagonal = 3(8)+7 = 31 cm.",
    steps: [
      { stepNumber: 1, title: "Set equal", explanation: "3x+7=5x−9 → x=8." },
      { stepNumber: 2, title: "Diagonal length", explanation: "31 cm.", result: "x=8; each diagonal=31 cm" },
    ],
    hint: "Rectangle diagonals are equal.",
    keyConcepts: ["rectangle equal diagonals"],
    conceptsCovered: ["mth:8:ch03:rectangle"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.EXAM_READY],
    source: "previous-year",
    examTip: "Rectangle diagonals equal — set expressions equal and solve.",
  },

];
