// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 8, Chapter 5: Squares and Square Roots
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Properties of Perfect Squares       — 25 q
 *   t2 Finding Square Roots                — 30 q
 *   t3 Estimating and Applying Square Roots — 20 q
 *
 * Concept nodes:
 *   mth:8:ch05:perfect-square-properties
 *   mth:8:ch05:square-patterns
 *   mth:8:ch05:prime-factorisation-square-root
 *   mth:8:ch05:long-division-square-root
 *   mth:8:ch05:square-root-estimation
 *   mth:8:ch05:pythagorean-application
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH05_SQUARES_AND_SQUARE_ROOTS: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Properties of Perfect Squares
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch05-con-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: The square of an odd number is always odd.",
    answer: "True. If n is odd, n = 2k+1, so n² = 4k²+4k+1 = 2(2k²+2k)+1, which is odd.",
    steps: [{ stepNumber: 1, title: "Proof", explanation: "Odd × odd = odd; e.g. 3²=9, 5²=25." }],
    hint: "Try squaring a few odd numbers.",
    keyConcepts: ["odd squares", "properties of squares"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "odd-squares"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What are the possible unit digits of a perfect square? List all possibilities.",
    answer: "A perfect square can only end in: 0, 1, 4, 5, 6, 9. Numbers ending in 2, 3, 7, 8 cannot be perfect squares.",
    steps: [
      { stepNumber: 1, title: "Square each digit", explanation: "0²=0,1²=1,2²=4,3²=9,4²=16,5²=25,6²=36,7²=49,8²=64,9²=81. Units: 0,1,4,9,6,5,6,9,4,1." },
      { stepNumber: 2, title: "Unique units", explanation: "{0,1,4,5,6,9}." },
    ],
    hint: "Square each digit 0–9 and record the last digit.",
    keyConcepts: ["unit digit of squares"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "unit-digit"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: 2028 could be a perfect square.",
    answer: "False. 2028 ends in 8. Perfect squares cannot end in 2, 3, 7, or 8. So 2028 is NOT a perfect square.",
    steps: [{ stepNumber: 1, title: "Unit digit test", explanation: "Unit digit 8 → cannot be a perfect square." }],
    hint: "Check the unit digit first.",
    keyConcepts: ["unit digit test", "perfect square"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "unit-digit"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the smallest number that must be subtracted from 1000 to make it a perfect square.",
    answer: "√1000 ≈ 31.6. 31² = 961. 1000 − 961 = 39. Subtract 39 from 1000 to get 961 = 31².",
    steps: [
      { stepNumber: 1, title: "Find nearest square", explanation: "31² = 961, 32² = 1024 > 1000." },
      { stepNumber: 2, title: "Subtract", explanation: "1000 − 961 = 39." },
    ],
    hint: "Find the largest perfect square less than or equal to 1000.",
    keyConcepts: ["nearest perfect square", "subtraction"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "nearest-square"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using the pattern of sums of odd numbers, express 49 as a sum of consecutive odd numbers starting from 1.",
    answer: "n² = sum of first n odd numbers. 49 = 7². Sum of first 7 odd numbers: 1+3+5+7+9+11+13 = 49.",
    steps: [
      { stepNumber: 1, title: "Identify n", explanation: "49 = 7², so n = 7." },
      { stepNumber: 2, title: "List", explanation: "1+3+5+7+9+11+13 = 49 ✓." },
    ],
    hint: "n² = sum of first n odd numbers.",
    keyConcepts: ["square patterns", "odd number sum"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "patterns"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Between 100 and 200, how many perfect squares are there?",
    answer: "4. They are 121 (11²), 144 (12²), 169 (13²), 196 (14²).",
    options: ["A) 3", "B) 4", "C) 5", "D) 6"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "List squares", explanation: "11²=121, 12²=144, 13²=169, 14²=196. All between 100 and 200." }],
    hint: "Find which integers squared give results between 100 and 200.",
    keyConcepts: ["counting perfect squares"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "counting-squares"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the smallest number by which 75 must be multiplied to make it a perfect square.",
    answer: "75 = 3 × 5². For a perfect square, all prime factors need even powers. 3¹ needs one more 3. Multiply by 3: 75 × 3 = 225 = 15².",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "75 = 3 × 25 = 3 × 5²." },
      { stepNumber: 2, title: "Make powers even", explanation: "3 has odd power 1; multiply by 3." },
    ],
    hint: "In the prime factorisation, all primes must appear to even powers.",
    keyConcepts: ["prime factorisation", "perfect square"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "smallest-multiplier"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find √144 using prime factorisation.",
    answer: "144 = 2⁴ × 3² = (2² × 3)² = 12². So √144 = 12.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "144 = 2×2×2×2×3×3 = 2⁴×3²." },
      { stepNumber: 2, title: "Square root", explanation: "√(2⁴×3²) = 2²×3 = 12." },
    ],
    hint: "Take half the power of each prime factor.",
    keyConcepts: ["prime factorisation", "square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "prime-factorisation"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find √1764 by prime factorisation.",
    answer: "1764 = 4 × 441 = 4 × 9 × 49 = 2² × 3² × 7². √1764 = 2 × 3 × 7 = 42.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "1764 ÷ 2 = 882; ÷2=441; ÷3=147; ÷3=49; ÷7=7; ÷7=1. So 2²×3²×7²." },
      { stepNumber: 2, title: "Square root", explanation: "2×3×7 = 42." },
    ],
    hint: "Divide by primes until you reach 1.",
    keyConcepts: ["prime factorisation", "square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "prime-factorisation"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find the square root of 2.25.",
    answer: "√2.25 = √(225/100) = √225/√100 = 15/10 = 1.5.",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "2.25 = 225/100." },
      { stepNumber: 2, title: "Take root", explanation: "√225 = 15, √100 = 10. Answer: 1.5." },
    ],
    hint: "Convert decimal to fraction first.",
    keyConcepts: ["square root of decimals"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "decimal-sqrt"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A square has area 196 cm². Find its side length.",
    answer: "Side = √196 = √(4 × 49) = 2 × 7 = 14 cm.",
    steps: [
      { stepNumber: 1, title: "Side = √Area", explanation: "Side = √196." },
      { stepNumber: 2, title: "Factorise", explanation: "196 = 4 × 49 = 2²×7². √196 = 14." },
    ],
    hint: "Side of square = √(Area).",
    keyConcepts: ["square area", "square root application"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "area-application"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch05-con-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Without calculating, determine if 6084 is a perfect square. Justify.",
    answer: "Unit digit 4 — possible (since 2²=4 and 8²=64 both end in 4). Sum of digits: 6+0+8+4=18 → divisible by 9. Actually, to confirm: √6084 ≈ 78. 78² = 6084. Yes, 6084 is a perfect square (78²).",
    steps: [
      { stepNumber: 1, title: "Unit digit test", explanation: "Ends in 4 — possible." },
      { stepNumber: 2, title: "Estimate root", explanation: "78² = 6084 ✓." },
    ],
    hint: "Check unit digit first, then verify by estimation.",
    keyConcepts: ["perfect square check", "unit digit"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "check-square"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch05-nce-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What will be the unit digit of the squares of: (i) 81 (ii) 272 (iii) 799 (iv) 3853?",
    answer: "(i) 81: unit digit 1, 1²=1. (ii) 272: unit digit 2, 2²=4. (iii) 799: unit digit 9, 9²=81, unit digit 1. (iv) 3853: unit digit 3, 3²=9.",
    steps: [{ stepNumber: 1, title: "Square last digit", explanation: "1→1; 2→4; 9→1(from 81); 3→9." }],
    hint: "Only the unit digit of the number determines the unit digit of its square.",
    keyConcepts: ["unit digit of squares"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Write down a Pythagorean triplet whose smallest member is 8.",
    answer: "For even n: triplet is (n, (n²/4)−1, (n²/4)+1). n=8: 8, 15, 17. Verify: 64+225=289=17². ✓",
    steps: [
      { stepNumber: 1, title: "Formula for even n", explanation: "n, (n²/4)−1, (n²/4)+1 when n is even." },
      { stepNumber: 2, title: "Compute", explanation: "8, 64/4−1, 64/4+1 = 8, 15, 17." },
    ],
    hint: "Use the Pythagorean triplet formula for even numbers.",
    keyConcepts: ["Pythagorean triplet"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using the identity (a+b)² = a² + 2ab + b², find 105².",
    answer: "105 = 100 + 5. (100+5)² = 100² + 2×100×5 + 5² = 10000 + 1000 + 25 = 11025.",
    steps: [
      { stepNumber: 1, title: "Split", explanation: "105 = 100 + 5." },
      { stepNumber: 2, title: "Expand", explanation: "10000 + 1000 + 25 = 11025." },
    ],
    hint: "Choose a = 100, b = 5 for easy calculation.",
    keyConcepts: ["algebraic identity", "mental maths"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the smallest number by which 252 must be divided to get a perfect square. Find the square root of the quotient.",
    answer: "252 = 2² × 3² × 7. 7 has odd power. Divide by 7: 252/7 = 36 = 6². √36 = 6.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "252 = 4 × 63 = 4 × 9 × 7 = 2²×3²×7." },
      { stepNumber: 2, title: "Remove odd-power factor", explanation: "Divide by 7; 252/7 = 36." },
      { stepNumber: 3, title: "Square root", explanation: "√36 = 6." },
    ],
    hint: "Find the prime with an odd exponent and divide by it.",
    keyConcepts: ["smallest divisor", "prime factorisation"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find √324 by prime factorisation.",
    answer: "324 = 4 × 81 = 2² × 3⁴. √324 = 2 × 3² = 2 × 9 = 18.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "324 = 2×162 = 2×2×81 = 2²×3⁴." },
      { stepNumber: 2, title: "Square root", explanation: "√(2²×3⁴) = 2×3² = 18." },
    ],
    hint: "Take half the exponent of each prime factor.",
    keyConcepts: ["prime factorisation square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Find √2025 using the long division method.",
    answer: "Group digits: 20|25. Step 1: √20 < 5 (4²=16). Remainder = 20−16=4. Bring down 25: 425. Step 2: Divisor = 2×4=8; find digit d such that 8d×d ≤ 425. d=4: 84×4=336 ≤ 425; d=5: 85×5=425. 85×5=425. Remainder=0. √2025 = 45.",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "20 | 25." },
      { stepNumber: 2, title: "First digit", explanation: "4²=16≤20; quotient digit = 4; remainder = 4." },
      { stepNumber: 3, title: "Bring down", explanation: "425; double quotient = 8; 85×5=425." },
      { stepNumber: 4, title: "Result", explanation: "√2025 = 45." },
    ],
    hint: "Group from right in pairs of two digits.",
    keyConcepts: ["long division square root"],
    conceptsCovered: ["mth:8:ch05:long-division-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Find √7921 by long division method.",
    answer: "Groups: 79|21. √79: 8²=64≤79; digit=8; remainder=79−64=15. Bring 21: 1521. Double 8 = 16; find d: 16d×d ≤ 1521. d=9: 169×9=1521. Remainder=0. √7921 = 89.",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "79|21." },
      { stepNumber: 2, title: "Digit 1 = 8", explanation: "8²=64; rem=15; bring 21 → 1521." },
      { stepNumber: 3, title: "Digit 2 = 9", explanation: "169×9=1521; rem=0." },
      { stepNumber: 4, title: "Result", explanation: "√7921 = 89." },
    ],
    hint: "After each step, double the quotient so far to form the new divisor prefix.",
    keyConcepts: ["long division square root"],
    conceptsCovered: ["mth:8:ch05:long-division-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Observe the pattern and find the value of: 1² + 2² + 3² + ... + 10² using the formula n(n+1)(2n+1)/6.",
    answer: "n = 10. Sum = 10×11×21/6 = 2310/6 = 385.",
    steps: [
      { stepNumber: 1, title: "Apply formula", explanation: "10×11×21/6." },
      { stepNumber: 2, title: "Compute", explanation: "10×11=110; 110×21=2310; 2310/6=385." },
    ],
    hint: "Formula: sum of squares = n(n+1)(2n+1)/6.",
    keyConcepts: ["sum of squares formula"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "pattern"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find √0.0081.",
    answer: "0.0081 = 81/10000. √(81/10000) = √81/√10000 = 9/100 = 0.09.",
    steps: [
      { stepNumber: 1, title: "Write as fraction", explanation: "0.0081 = 81/10000." },
      { stepNumber: 2, title: "Square root", explanation: "9/100 = 0.09." },
    ],
    hint: "Count decimal places: 4 places, so root has 2 places.",
    keyConcepts: ["square root of decimals"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "decimal-sqrt"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find √(16/25) and √(64/225).",
    answer: "√(16/25) = 4/5 = 0.8. √(64/225) = 8/15.",
    steps: [
      { stepNumber: 1, title: "First", explanation: "√16/√25 = 4/5." },
      { stepNumber: 2, title: "Second", explanation: "√64/√225 = 8/15." },
    ],
    hint: "√(a/b) = √a/√b when both are perfect squares.",
    keyConcepts: ["square root of fractions"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "fraction-sqrt"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find √1156.",
    answer: "1156 = 4 × 289 = 2² × 17². √1156 = 2 × 17 = 34.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "1156 = 4×289 = 2²×17²." },
      { stepNumber: 2, title: "Square root", explanation: "2×17 = 34." },
    ],
    hint: "Check: 34² = 1156.",
    keyConcepts: ["prime factorisation square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the smallest square number divisible by each of 6, 9, and 15.",
    answer: "LCM(6,9,15) = 90. 90 = 2×3²×5. For perfect square: 2 and 5 need even powers. Multiply 90 by (2×5) = 10: 900 = 2²×3²×5² = 30². Smallest square divisible by all three is 900.",
    steps: [
      { stepNumber: 1, title: "LCM", explanation: "LCM(6,9,15) = 90." },
      { stepNumber: 2, title: "Factorise LCM", explanation: "90 = 2¹×3²×5¹." },
      { stepNumber: 3, title: "Make perfect square", explanation: "Multiply by 2×5=10: 900 = 30²." },
    ],
    hint: "Find LCM, then make all prime exponents even.",
    keyConcepts: ["LCM", "perfect square"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Find √16129 by long division method.",
    answer: "Groups: 1|61|29. Step 1: 1² = 1 ≤ 1; digit=1; rem=0. Bring 61: 61. Double 1 = 2; 22×2=44 ≤ 61; 23×3=69>61; digit=2; 22×2=44; rem=17. Bring 29: 1729. Double 12=24; 249×? 249×6=1494≤1729; 249×7=1743>1729; digit=6. Wait — 24×? looking for d where (240+d)×d ≤ 1729. d=7: 247×7=1729. rem=0. √16129 = 127.",
    steps: [
      { stepNumber: 1, title: "Groups: 1|61|29", explanation: "Three pairs." },
      { stepNumber: 2, title: "Digit 1", explanation: "1² = 1; rem 0; bring 61." },
      { stepNumber: 3, title: "Digit 2", explanation: "22×2=44 ≤ 61; rem 17; bring 29 → 1729." },
      { stepNumber: 4, title: "Digit 3", explanation: "247×7=1729; rem 0. Answer: 127." },
    ],
    hint: "Three-digit square root requires three pairs of digits.",
    keyConcepts: ["long division square root"],
    conceptsCovered: ["mth:8:ch05:long-division-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "800 students are to stand in equal rows with equal columns for a march-past. Find the number of rows.",
    answer: "For equal rows and columns: rows = columns = √800. 800 = 400×2. Not a perfect square. Add (to make perfect square): 800+? to get 900 (30²). Add 100. OR subtract: 800−256=544 (not square). 800+100=900=30². Rows = 30, but 100 students extra. NCERT answer: smallest addition to make perfect square. Add 100 to get 900: 30 rows of 30. Excess = 800−900 is negative, so ADD 100 to get 900. Answer: 30 rows.",
    steps: [
      { stepNumber: 1, title: "Find √800", explanation: "800 = 2⁵×5². Not a perfect square." },
      { stepNumber: 2, title: "Nearest perfect square ≥ 800", explanation: "30² = 900; need 100 more students, so 30 rows." },
      { stepNumber: 3, title: "Alternatively, subtract", explanation: "28² = 784; 800−784=16 left over. If 784 students: 28 rows. But question says 'equal rows and columns' — standard NCERT asks for excess/deficit." },
    ],
    hint: "Square root of total students = number of rows (if perfect square).",
    keyConcepts: ["square root application", "arrangement"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "application"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 2, estimatedTimeMinutes: 3,
    question: "How many non-perfect-square numbers lie between n² and (n+1)²? Find for n = 12.",
    answer: "Between n² and (n+1)², there are 2n non-perfect-square numbers. For n=12: 2×12 = 24 numbers between 144 and 169.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "Between n² and (n+1)² there are (n+1)² − n² − 1 = 2n numbers." },
      { stepNumber: 2, title: "n=12", explanation: "2×12 = 24." },
    ],
    hint: "(n+1)² − n² = 2n + 1; subtract 1 for the boundary.",
    keyConcepts: ["non-perfect squares", "gap between consecutive squares"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find √4096 by prime factorisation.",
    answer: "4096 = 2¹². √4096 = 2⁶ = 64.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "4096 = 2¹² (since 2¹⁰=1024, 2¹²=4096)." },
      { stepNumber: 2, title: "Square root", explanation: "√2¹² = 2⁶ = 64." },
    ],
    hint: "4096 = 4^6 = (2²)^6 = 2^12.",
    keyConcepts: ["prime factorisation", "square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-017",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The area of a square field is 60025 m². A man cycles along its boundary. How many revolutions must he make to cover 4 km?",
    answer: "Side = √60025. 245² = 60025 (check: 245 = 5×49 = 5×7²; 245² = 25×2401=60025 ✓). Perimeter = 4×245 = 980 m. 4 km = 4000 m. Revolutions = 4000/980 = 200/49 ≈ 4.08, so he needs 5 complete revolutions (or fractionally 200/49).",
    steps: [
      { stepNumber: 1, title: "√60025 = 245", explanation: "245² = 60025." },
      { stepNumber: 2, title: "Perimeter = 980 m", explanation: "4×245." },
      { stepNumber: 3, title: "Revolutions", explanation: "4000/980 = 200/49 ≈ 4.08." },
    ],
    hint: "First find the side using square root, then compute perimeter.",
    keyConcepts: ["application", "square root", "perimeter"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "NCERT-Ex5.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch05-nce-018",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Express 49 − 1 as the product of 2 numbers (using the identity n² − 1² = (n−1)(n+1)).",
    answer: "49 − 1 = 48 = (7−1)(7+1) = 6 × 8. Verify: 6 × 8 = 48 ✓.",
    steps: [{ stepNumber: 1, title: "Identity", explanation: "a²−b²=(a−b)(a+b). 49−1 = 7²−1² = 6×8 = 48." }],
    hint: "a² − b² = (a−b)(a+b).",
    keyConcepts: ["difference of squares", "factorisation"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch05", "identity"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch05-ics-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Using long division, find √529 and √1521.",
    answer: "√529: Groups 5|29. √5<3 (2²=4); rem=1; bring 29→129; 2×2=4; 43×3=129; digit=3. √529=23. √1521: Groups 15|21. √15<4 (3²=9); rem=6; bring 21→621; 2×3=6; 63×? 63×9=567<621; 69×9=621; digit=9. Wait: double 3→6; 69×9=621. √1521=39.",
    steps: [
      { stepNumber: 1, title: "√529=23", explanation: "2²=4≤5; rem 1; 129; 43×3=129; √529=23." },
      { stepNumber: 2, title: "√1521=39", explanation: "3²=9≤15; rem 6; 621; 69×9=621; √1521=39." },
    ],
    hint: "Apply long division method to both numbers.",
    keyConcepts: ["long division square root"],
    conceptsCovered: ["mth:8:ch05:long-division-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch05", "long-division"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch05-ics-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find √(2.56 × 0.0036).",
    answer: "2.56 × 0.0036 = 0.009216. Alternatively: √2.56 × √0.0036 = 1.6 × 0.06 = 0.096.",
    steps: [
      { stepNumber: 1, title: "Separate square roots", explanation: "√(a×b) = √a × √b." },
      { stepNumber: 2, title: "√2.56 = 1.6", explanation: "256/100; √256=16; √100=10; 16/10=1.6." },
      { stepNumber: 3, title: "√0.0036 = 0.06", explanation: "36/10000; 6/100=0.06." },
      { stepNumber: 4, title: "Multiply", explanation: "1.6 × 0.06 = 0.096." },
    ],
    hint: "Split √(a×b) = √a × √b.",
    keyConcepts: ["square root of product", "decimals"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: ["Combining decimals incorrectly in multiplication."],
    tags: ["ICSE", "class8", "ch05", "decimal-product"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch05-ics-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The diagonal of a square is 12√2 cm. Find its side and area.",
    answer: "Diagonal of square = side × √2. Side = 12√2/√2 = 12 cm. Area = 12² = 144 cm².",
    steps: [
      { stepNumber: 1, title: "Diagonal formula", explanation: "d = s√2 → s = d/√2." },
      { stepNumber: 2, title: "Side", explanation: "s = 12√2/√2 = 12 cm." },
      { stepNumber: 3, title: "Area", explanation: "12² = 144 cm²." },
    ],
    hint: "Diagonal of a square = side × √2.",
    keyConcepts: ["diagonal", "square geometry"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch05", "diagonal"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch05-ics-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Evaluate: √(225 × 625) + √(49 × 256).",
    answer: "√(225×625) = √225×√625 = 15×25 = 375. √(49×256) = 7×16 = 112. Sum = 375+112 = 487.",
    steps: [
      { stepNumber: 1, title: "First term", explanation: "15×25=375." },
      { stepNumber: 2, title: "Second term", explanation: "7×16=112." },
      { stepNumber: 3, title: "Sum", explanation: "487." },
    ],
    hint: "√(a×b) = √a × √b when both are perfect squares.",
    keyConcepts: ["square root of product"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch05", "evaluate"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch05-ics-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If a perfect square ends in 6, what must its tens digit be?",
    answer: "Numbers ending in 6 whose square ends in 6: 4 (4²=16), 6 (6²=36), 14 (196 — tens digit 9), 16 (256 — tens digit 5), 24 (576 — tens digit 7), 26 (676 — tens digit 7). The tens digit of n² when n ends in 6 depends on n: it's always odd (1, 3, 5, 7, 9 appear). Actually, tens digit of n² when unit digit is 6 is always even... Let me recalculate: 6²=36(3), 16²=256(5), 26²=676(7), 36²=1296(9), 46²=2116(1). Pattern: tens digit cycles 3,5,7,9,1... all odd. So: when a perfect square ends in 6, its tens digit is always odd.",
    steps: [
      { stepNumber: 1, title: "List squares ending in 6", explanation: "6²=36, 16²=256, 26²=676, 36²=1296, 46²=2116." },
      { stepNumber: 2, title: "Tens digits", explanation: "3, 5, 7, 9, 1 — all odd." },
    ],
    hint: "Systematically square numbers ending in 6 and observe the tens digit.",
    keyConcepts: ["digit patterns", "tens digit of squares"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: ["Not checking enough cases to spot the pattern."],
    tags: ["ICSE", "class8", "ch05", "digit-pattern"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch05-ics-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A right triangle has legs 20 cm and 21 cm. Find the hypotenuse.",
    answer: "Hypotenuse = √(20² + 21²) = √(400 + 441) = √841 = 29 cm.",
    steps: [
      { stepNumber: 1, title: "Pythagoras theorem", explanation: "h² = 20² + 21² = 400 + 441 = 841." },
      { stepNumber: 2, title: "Square root", explanation: "√841 = 29 (since 29²=841)." },
    ],
    hint: "Apply Pythagoras: h² = a² + b².",
    keyConcepts: ["Pythagoras theorem", "hypotenuse"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch05", "pythagoras"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch05-ics-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Find √(36.1201) using the long division method.",
    answer: "Group: 36 | 12 | 01. Step 1: √36 = 6; rem = 0; bring 12 → 012. Step 2: Double 6 = 12; trial digit d: 12d × d ≤ 12. d=0: 120×0=0; rem=12; bring 01→1201. Step 3: Double 60=120; 1200 + d: 1201×? try d=1: 1201×1=1201≤1201. rem=0. √36.1201 = 6.01.",
    steps: [
      { stepNumber: 1, title: "Groups", explanation: "36|12|01 (decimal: place decimal after 6 in answer)." },
      { stepNumber: 2, title: "6²=36; bring 12", explanation: "Digit=6; rem=0; next dividend=1200." },
      { stepNumber: 3, title: "Digit 0", explanation: "120×0=0; rem=12; bring 01→1201." },
      { stepNumber: 4, title: "Digit 1", explanation: "1201×1=1201; rem=0. Answer=6.01." },
    ],
    hint: "For decimals, group digits on each side of the decimal point in pairs.",
    keyConcepts: ["decimal square root", "long division"],
    conceptsCovered: ["mth:8:ch05:long-division-square-root"],
    prerequisites: [],
    commonErrors: ["Misplacing the decimal point in the answer."],
    tags: ["ICSE", "class8", "ch05", "decimal-long-division"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch05-cmp-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A park is square-shaped with area 8100 m². Find the cost of fencing it at ₹25 per metre.",
    answer: "Side = √8100 = 90 m. Perimeter = 4×90 = 360 m. Cost = 360 × 25 = ₹9000.",
    steps: [
      { stepNumber: 1, title: "Side", explanation: "√8100 = 90 m." },
      { stepNumber: 2, title: "Perimeter", explanation: "4×90=360 m." },
      { stepNumber: 3, title: "Cost", explanation: "360×25=₹9000." },
    ],
    hint: "First find the side from the area.",
    keyConcepts: ["area to side", "perimeter", "cost"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which of the following numbers is NOT a perfect square?",
    answer: "Option C: 2028 ends in 8 — cannot be a perfect square.",
    options: ["A) 4096", "B) 1764", "C) 2028", "D) 3136"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Unit digit test", explanation: "2028 ends in 8 → not a perfect square." }],
    hint: "Check unit digits: 2, 3, 7, 8 disqualify a number.",
    keyConcepts: ["unit digit test"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "identify"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A ladder 25 m long reaches a wall. The base is 7 m from the wall. How high up the wall does the ladder reach?",
    answer: "Height² + 7² = 25². h² = 625 − 49 = 576. h = √576 = 24 m.",
    steps: [
      { stepNumber: 1, title: "Pythagoras", explanation: "h² = 25² − 7² = 625 − 49 = 576." },
      { stepNumber: 2, title: "Square root", explanation: "√576 = 24 m." },
    ],
    hint: "Pythagoras theorem: hyp² = leg₁² + leg₂².",
    keyConcepts: ["Pythagoras", "real-world application"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A gardener plants 784 trees in rows, each row having the same number of trees. How many rows are there?",
    answer: "Number of rows = √784 = 28. (Since rows × trees/row = 784, and rows = trees/row ⟹ rows² = 784.)",
    steps: [
      { stepNumber: 1, title: "Equal rows and columns", explanation: "Rows = √784." },
      { stepNumber: 2, title: "√784 = 28", explanation: "28² = 784 ✓." },
    ],
    hint: "Equal rows and columns means rows = √total trees.",
    keyConcepts: ["square root", "arrangement problem"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "arrangement"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "√(1024/576) simplifies to:",
    answer: "32/24 = 4/3. √1024=32, √576=24.",
    options: ["A) 2/3", "B) 3/4", "C) 4/3", "D) 5/4"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Compute", explanation: "√1024=32; √576=24; 32/24=4/3." }],
    hint: "√(a/b) = √a/√b.",
    keyConcepts: ["fraction square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "fraction-root"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Estimate √50 to one decimal place without a calculator.",
    answer: "7² = 49, 8² = 64. √50 is between 7 and 8, closer to 7. Refine: 7.1² = 50.41 > 50; 7.0² = 49 < 50. Try 7.07: 7.07² ≈ 49.98 ≈ 50. √50 ≈ 7.1 (to 1 d.p.).",
    steps: [
      { stepNumber: 1, title: "Bracket", explanation: "7²=49 < 50 < 64=8²." },
      { stepNumber: 2, title: "Test 7.1", explanation: "7.1²=50.41 > 50. So √50 is between 7.0 and 7.1." },
      { stepNumber: 3, title: "Round", explanation: "√50 ≈ 7.1 to 1 d.p." },
    ],
    hint: "Find the two integers it falls between, then test 7.1, 7.2...",
    keyConcepts: ["estimation", "square root approximation"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "estimation"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Is 1 a perfect square? What is its square root?",
    answer: "Yes, 1 is a perfect square: 1 = 1². √1 = 1.",
    steps: [{ stepNumber: 1, title: "Check", explanation: "1² = 1. So 1 is a perfect square; √1=1." }],
    hint: "The smallest perfect square is 1.",
    keyConcepts: ["perfect square", "square root of 1"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "basic"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Find the number of digits in √12321.",
    answer: "12321 has 5 digits. Grouping in pairs from right: 1|23|21 — 3 groups. So √12321 has 3 digits. (Verify: √12321 = 111, which has 3 digits.)",
    steps: [
      { stepNumber: 1, title: "Group digits", explanation: "12321 → 1|23|21 = 3 groups." },
      { stepNumber: 2, title: "Digits in root = groups", explanation: "3 digits in √12321." },
    ],
    hint: "Number of digits in square root = number of groups when digits are paired from right.",
    keyConcepts: ["number of digits in square root"],
    conceptsCovered: ["mth:8:ch05:long-division-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "digit-count"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A square room has floor area 56.25 m². Tiles of side 0.75 m are used. How many tiles are needed?",
    answer: "Side of room = √56.25 = 7.5 m. Number of tiles per side = 7.5/0.75 = 10. Total tiles = 10 × 10 = 100.",
    steps: [
      { stepNumber: 1, title: "Room side", explanation: "√56.25 = √(5625/100) = 75/10 = 7.5 m." },
      { stepNumber: 2, title: "Tiles per side", explanation: "7.5/0.75 = 10." },
      { stepNumber: 3, title: "Total", explanation: "10² = 100 tiles." },
    ],
    hint: "Find room side first, then divide by tile size.",
    keyConcepts: ["tiling", "square root application"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: ["Dividing area by tile area directly instead of using side lengths."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "tiling"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Which number should be added to 680 to make it a perfect square?",
    answer: "√680 ≈ 26.07. 26² = 676; 27² = 729. Add 729 − 680 = 49 to get 729 = 27².",
    steps: [
      { stepNumber: 1, title: "Next perfect square", explanation: "27² = 729 > 680." },
      { stepNumber: 2, title: "Add", explanation: "729 − 680 = 49." },
    ],
    hint: "Find the next perfect square above 680.",
    keyConcepts: ["next perfect square", "addition to perfect square"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "make-perfect-square"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find √(441 × 196).",
    answer: "√441 × √196 = 21 × 14 = 294.",
    steps: [{ stepNumber: 1, title: "Separate and compute", explanation: "√441=21, √196=14; 21×14=294." }],
    hint: "√(a×b) = √a × √b.",
    keyConcepts: ["square root of product"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "product-root"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "√(0.04) equals:",
    answer: "0.2. √(0.04) = √(4/100) = 2/10 = 0.2.",
    options: ["A) 0.02", "B) 0.2", "C) 2", "D) 0.002"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Convert", explanation: "0.04 = 4/100; √4/√100 = 2/10 = 0.2." }],
    hint: "√(0.04) = √(4/100) = 2/10.",
    keyConcepts: ["square root of decimal"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "decimal-root"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using the pattern 1+3=4, 1+3+5=9, find the sum 1+3+5+7+...+21.",
    answer: "Sum of first n odd numbers = n². The odd numbers 1,3,5,...,21 are the first 11 (since 21 = 2×11−1). Sum = 11² = 121.",
    steps: [
      { stepNumber: 1, title: "Find n", explanation: "21 is the 11th odd number: 2×11−1=21." },
      { stepNumber: 2, title: "Sum", explanation: "11² = 121." },
    ],
    hint: "The nth odd number is 2n−1. Find n for 21.",
    keyConcepts: ["sum of odd numbers", "square pattern"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "pattern"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A man walks 24 m north and 7 m east. How far is he from his starting point?",
    answer: "Distance = √(24² + 7²) = √(576 + 49) = √625 = 25 m.",
    steps: [
      { stepNumber: 1, title: "Pythagoras", explanation: "d² = 24² + 7² = 576 + 49 = 625." },
      { stepNumber: 2, title: "Square root", explanation: "d = 25 m." },
    ],
    hint: "North and east directions are perpendicular — use Pythagoras.",
    keyConcepts: ["Pythagoras", "distance"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Meena says 2000 is a perfect square because its square root is about 44.7. Is she correct?",
    answer: "No. 44² = 1936 and 45² = 2025. Since 2000 is between 1936 and 2025, it is NOT a perfect square. The square root of a perfect square must be a whole number. √2000 ≈ 44.7 is NOT a whole number, so 2000 is not a perfect square.",
    steps: [
      { stepNumber: 1, title: "Check neighbouring squares", explanation: "44²=1936, 45²=2025. 2000 lies between them." },
      { stepNumber: 2, title: "Conclude", explanation: "No integer has square 2000 → not a perfect square." },
    ],
    hint: "A perfect square has a whole-number square root.",
    keyConcepts: ["perfect square definition", "critical evaluation"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: ["Confusing approximate square root with exact square root."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "reasoning"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch05-cmp-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find √3969 by prime factorisation.",
    answer: "3969 = 9 × 441 = 3² × 21² = 3² × (3×7)² = 3⁴ × 7². √3969 = 3² × 7 = 9 × 7 = 63.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "3969 = 3⁴×7²." },
      { stepNumber: 2, title: "Square root", explanation: "3²×7 = 63." },
    ],
    hint: "Check: 63² = 3969.",
    keyConcepts: ["prime factorisation square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch05", "prime-factorisation"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch05-hot-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove that the square of any integer ending in 5 always ends in 25.",
    answer: "Let n end in 5: n = 10k + 5. n² = (10k+5)² = 100k² + 100k + 25 = 100k(k+1) + 25. 100k(k+1) ends in 00 (divisible by 100). Adding 25: last two digits = 25. ✓",
    steps: [
      { stepNumber: 1, title: "General form", explanation: "n = 10k + 5 for integer k." },
      { stepNumber: 2, title: "Square", explanation: "n² = 100k² + 100k + 25." },
      { stepNumber: 3, title: "Analyse", explanation: "100k(k+1) is divisible by 100, so last two digits come from 25." },
    ],
    hint: "Write n = 10k + 5 and expand n².",
    keyConcepts: ["algebraic proof", "ending in 5"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: ["Not using algebraic form — specific examples don't prove the general case."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Without computing directly, determine whether √(999999) is rational or irrational.",
    answer: "999999 = 999 × 1001 = 3×333×7×143 = 3×3×37×7×11×13 = 3²×7×11×13×37. Since 7, 11, 13, 37 all appear once (odd powers), 999999 is NOT a perfect square. Therefore √999999 is irrational.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "999999 = 3²×7×11×13×37." },
      { stepNumber: 2, title: "Check powers", explanation: "7, 11, 13, 37 appear with odd power 1 → not a perfect square." },
      { stepNumber: 3, title: "Conclude", explanation: "Not a perfect square → √999999 is irrational." },
    ],
    hint: "If any prime appears with odd exponent in the factorisation, it's not a perfect square.",
    keyConcepts: ["rationality", "prime factorisation"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: ["Assuming large numbers must be perfect squares."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "rationality"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Show that for any positive integer n, (n+1)² − n² = 2n + 1. Use this to find the difference between the squares of 50 and 49.",
    answer: "(n+1)² − n² = n² + 2n + 1 − n² = 2n + 1. For n=49: 50² − 49² = 2(49)+1 = 99. Verify: 2500 − 2401 = 99 ✓.",
    steps: [
      { stepNumber: 1, title: "Algebraic proof", explanation: "(n+1)² − n² = 2n+1." },
      { stepNumber: 2, title: "Apply n=49", explanation: "2(49)+1 = 99." },
    ],
    hint: "Expand (n+1)² and subtract n².",
    keyConcepts: ["difference of consecutive squares", "algebraic identity"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "identity"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Two poles 30 m and 40 m tall stand 24 m apart (measured from their bases). A wire connects their tops. Find the length of the wire.",
    answer: "Height difference = 40 − 30 = 10 m. Horizontal distance = 24 m. Wire = √(10² + 24²) = √(100+576) = √676 = 26 m.",
    steps: [
      { stepNumber: 1, title: "Height difference", explanation: "40 − 30 = 10 m (vertical component)." },
      { stepNumber: 2, title: "Pythagoras", explanation: "Wire² = 10² + 24² = 100 + 576 = 676." },
      { stepNumber: 3, title: "Square root", explanation: "√676 = 26 m." },
    ],
    hint: "The wire forms the hypotenuse of a right triangle.",
    keyConcepts: ["Pythagoras", "real-world"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: ["Using 30+40 instead of 40−30 for the height difference."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "poles-wire"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Generate all Pythagorean triplets (a, b, c) with a < b < c < 30.",
    answer: "(3,4,5), (5,12,13), (6,8,10), (7,24,25), (8,15,17), (9,12,15), (9,40,41)—too large. (10,24,26), (12,16,20), (15,20,25), (20,21,29). Check: all satisfy a²+b²=c².",
    steps: [
      { stepNumber: 1, title: "Primitive triplets (formula)", explanation: "m>n>0: a=m²−n², b=2mn, c=m²+n². m=2,n=1:3,4,5. m=3,n=2:5,12,13. m=4,n=1:15,8,17. m=4,n=3:7,24,25. m=5,n=2:21,20,29." },
      { stepNumber: 2, title: "Multiples", explanation: "2×(3,4,5)=(6,8,10); 3×(3,4,5)=(9,12,15); 4×(3,4,5)=(12,16,20); 5×(3,4,5)=(15,20,25); 2×(5,12,13)=(10,24,26)." },
    ],
    hint: "Use the formula (m²−n², 2mn, m²+n²) for primitive triplets, then include multiples.",
    keyConcepts: ["Pythagorean triplets", "formula"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "generate-triplets"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Find the number to be added to 2352 to make it a perfect square. Also find the square root of the resulting number.",
    answer: "√2352 ≈ 48.5. 48²=2304, 49²=2401. Add 2401−2352=49 to get 2401=49². √2401 = 49.",
    steps: [
      { stepNumber: 1, title: "Next square", explanation: "49²=2401 > 2352." },
      { stepNumber: 2, title: "Add", explanation: "2401−2352=49." },
      { stepNumber: 3, title: "Square root", explanation: "√2401=49." },
    ],
    hint: "Find the next perfect square after 2352.",
    keyConcepts: ["addition to perfect square"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "addition"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Can the sum of two perfect squares be a perfect square? Give an example and a counter-example.",
    answer: "Yes! Example: 9 + 16 = 25 = 5² (Pythagorean triplet 3,4,5). Counter-example: 4 + 16 = 20, which is not a perfect square (√20 is irrational). So the sum of two perfect squares is SOMETIMES a perfect square.",
    steps: [
      { stepNumber: 1, title: "Example", explanation: "3²+4²=5². Sum is a perfect square." },
      { stepNumber: 2, title: "Counter-example", explanation: "2²+4²=4+16=20. Not a perfect square." },
    ],
    hint: "Think about Pythagorean triplets for the example.",
    keyConcepts: ["sum of squares", "counterexample"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: ["Claiming it's always or never possible without evidence for both."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "sum-of-squares"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "A rectangular field is 3 times as long as it is wide. Its diagonal is 20√(10/3) m. Find the dimensions and area.",
    answer: "Let width = w, length = 3w. Diagonal² = w² + (3w)² = w² + 9w² = 10w². Diagonal = w√10 = 20√(10/3). So w = 20√(10/3)/√10 = 20/√3 = 20√3/3 m. Length = 3w = 20√3 m. Area = w × l = (20√3/3) × (20√3) = (20 × 20 × 3)/3 = 400 m².",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "w² + 9w² = 10w² = diagonal²." },
      { stepNumber: 2, title: "Find w", explanation: "w√10 = 20√(10/3) → w = 20/√3." },
      { stepNumber: 3, title: "Length", explanation: "3w = 60/√3 = 20√3." },
      { stepNumber: 4, title: "Area", explanation: "w×l = (20/√3)×20√3 = 400 m²." },
    ],
    hint: "Diagonal² = length² + width² (Pythagoras).",
    keyConcepts: ["rectangle diagonal", "Pythagoras"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: ["Confusing the length:width ratio with 1:3 instead of 3:1."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "rectangle-diagonal"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If √x = 13 and √y = 7, find √(x+y+2√(xy)) without computing x and y individually.",
    answer: "x+y+2√(xy) = (√x)² + (√y)² + 2√x·√y = (√x + √y)². So √(x+y+2√(xy)) = √x + √y = 13 + 7 = 20.",
    steps: [
      { stepNumber: 1, title: "Recognise identity", explanation: "a²+b²+2ab = (a+b)² where a=√x, b=√y." },
      { stepNumber: 2, title: "Apply", explanation: "√(x+y+2√(xy)) = √x + √y = 13+7 = 20." },
    ],
    hint: "Recognize the expression inside as a perfect square.",
    keyConcepts: ["algebraic identity", "square root simplification"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: ["Computing x=169, y=49 first instead of using the identity directly."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "identity-shortcut"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch05-hot-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Design a 'square number puzzle': fill a 3×3 grid with distinct perfect squares such that the sum of every row, column, and diagonal is equal. (Magic square of perfect squares.)",
    answer: "One solution uses the magic square based on 1,9,25,49,81,121,169,225,289 (odd perfect squares). Arrange: 49,1,225; 289,91,... This is known to be very hard in general. A simpler approach: multiply the standard 3×3 magic square (2,7,6/9,5,1/4,3,8) values by a factor and adjust. One known partial answer: 289,169,1; 25,169,225;... but constructing a proper magic square of perfect squares is an open problem for pure squares. Instead: use a magic square with entries that are squares when added: row sums=magic constant. Standard 3×3 magic square ×9: 36,63,54/81,45,9/18,27,72 — but these aren't perfect squares. Acknowledge the difficulty and provide the standard 3×3 magic square as a framework: centre=5, magic sum=15; student fills with understanding of concept.",
    steps: [
      { stepNumber: 1, title: "Standard magic square", explanation: "Centre = (sum)/3. Try small perfect squares." },
      { stepNumber: 2, title: "Framework", explanation: "Use the property that rows/cols/diagonals sum equally." },
      { stepNumber: 3, title: "Challenge", explanation: "Known open problem; student demonstrates understanding of square properties and magic squares as concept extension." },
    ],
    hint: "Start with the standard 3×3 magic square (magic constant 15) and adapt.",
    keyConcepts: ["magic square", "perfect squares", "problem creation"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: ["Assuming it's always possible to create a magic square with arbitrary perfect squares."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch05", "create"],
    source: "hots",
  },

  // ── PREVIOUS-YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch05-pyq-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The square of 35 is:",
    answer: "1225. 35² = (30+5)² = 900+300+25 = 1225.",
    options: ["A) 1025", "B) 1125", "C) 1225", "D) 1325"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Compute", explanation: "35²=1225." }],
    hint: "35 ends in 5, so its square ends in 25.",
    keyConcepts: ["squaring numbers"],
    conceptsCovered: ["mth:8:ch05:square-patterns"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find √729.",
    answer: "729 = 3⁶. √729 = 3³ = 27.",
    steps: [{ stepNumber: 1, title: "Factorise and root", explanation: "729=3⁶; √729=3³=27." }],
    hint: "729 = 27² — check!",
    keyConcepts: ["square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "What least number must be subtracted from 2361 to get a perfect square? Find the square root.",
    answer: "√2361 ≈ 48.6. 48²=2304. Subtract 2361−2304=57. √2304=48.",
    steps: [
      { stepNumber: 1, title: "Largest square ≤ 2361", explanation: "48²=2304." },
      { stepNumber: 2, title: "Subtract", explanation: "2361−2304=57." },
      { stepNumber: 3, title: "Root", explanation: "√2304=48." },
    ],
    hint: "Find the largest perfect square ≤ 2361.",
    keyConcepts: ["subtraction to perfect square"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A square board has area 1.96 m². Find its perimeter.",
    answer: "Side = √1.96 = √(196/100) = 14/10 = 1.4 m. Perimeter = 4×1.4 = 5.6 m.",
    steps: [
      { stepNumber: 1, title: "Side", explanation: "√1.96=1.4 m." },
      { stepNumber: 2, title: "Perimeter", explanation: "4×1.4=5.6 m." },
    ],
    hint: "Side = √(Area), then multiply by 4 for perimeter.",
    keyConcepts: ["area", "perimeter", "square root"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find √5776 by long division method.",
    answer: "Groups: 57|76. √57: 7²=49≤57; digit=7; rem=8. Bring 76→876. Double 7=14; 14d×d≤876: d=5: 145×5=725≤876; d=6: 146×6=876. digit=6; rem=0. √5776=76.",
    steps: [
      { stepNumber: 1, title: "Groups: 57|76", explanation: "Two groups." },
      { stepNumber: 2, title: "Digit 1 = 7", explanation: "7²=49; rem=8; bring 76→876." },
      { stepNumber: 3, title: "Digit 2 = 6", explanation: "146×6=876; rem=0. √5776=76." },
    ],
    hint: "Apply the long division algorithm step by step.",
    keyConcepts: ["long division square root"],
    conceptsCovered: ["mth:8:ch05:long-division-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "previous-year", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Every perfect square number is even.",
    answer: "False. Odd squares are also perfect squares. For example, 9 = 3² and 25 = 5² are odd perfect squares.",
    steps: [{ stepNumber: 1, title: "Counter-example", explanation: "9 = 3² is a perfect square and is odd." }],
    hint: "Consider odd numbers squared.",
    keyConcepts: ["odd perfect squares"],
    conceptsCovered: ["mth:8:ch05:perfect-square-properties"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find √(169/289).",
    answer: "√169/√289 = 13/17.",
    steps: [{ stepNumber: 1, title: "Separate", explanation: "√169=13; √289=17. Answer: 13/17." }],
    hint: "√(a/b) = √a ÷ √b.",
    keyConcepts: ["square root of fraction"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find √(0.000441).",
    answer: "0.000441 = 441/1000000. √(441/1000000) = 21/1000 = 0.021.",
    steps: [
      { stepNumber: 1, title: "Convert", explanation: "441/1000000." },
      { stepNumber: 2, title: "Square root", explanation: "21/1000 = 0.021." },
    ],
    hint: "6 decimal places → 3 decimal places in the root.",
    keyConcepts: ["decimal square root"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t1", topicName: "Properties of Perfect Squares",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the smallest number by which 2058 must be multiplied to make it a perfect square.",
    answer: "2058 = 2 × 1029 = 2 × 3 × 343 = 2 × 3 × 7³. Odd powers: 2¹, 3¹, 7¹ (wait: 7³ has odd exponent). Multiply by 2×3×7 = 42. 2058×42 = 86436. √86436 = 294.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "2058 = 2¹×3¹×7³." },
      { stepNumber: 2, title: "Odd exponents", explanation: "2 (exp 1), 3 (exp 1), 7 (exp 3 — odd). Multiply by 2×3×7=42." },
    ],
    hint: "Identify primes with odd exponents.",
    keyConcepts: ["smallest multiplier", "prime factorisation"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "The hypotenuse of a right triangle is 26 cm and one leg is 10 cm. Find the other leg.",
    answer: "Other leg = √(26² − 10²) = √(676 − 100) = √576 = 24 cm.",
    steps: [
      { stepNumber: 1, title: "Pythagoras", explanation: "leg² = 26² − 10² = 676 − 100 = 576." },
      { stepNumber: 2, title: "Root", explanation: "√576 = 24 cm." },
    ],
    hint: "leg² = hyp² − other_leg².",
    keyConcepts: ["Pythagoras", "finding a leg"],
    conceptsCovered: ["mth:8:ch05:pythagorean-application"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t2", topicName: "Finding Square Roots",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "√(1/16) equals:",
    answer: "1/4. √1=1, √16=4. Answer: 1/4.",
    options: ["A) 1/2", "B) 1/4", "C) 1/8", "D) 1/6"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Compute", explanation: "√1/√16 = 1/4." }],
    hint: "Take square root of numerator and denominator separately.",
    keyConcepts: ["fraction square root"],
    conceptsCovered: ["mth:8:ch05:prime-factorisation-square-root"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch05-pyq-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch05", chapterName: "Squares and Square Roots",
    topicId: "t3", topicName: "Estimating and Applying Square Roots",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A school hall is 50 m long and 40 m wide. 2000 students are to stand in the hall. Each student needs 1 m² of space. Can they all fit? If yes, how many rows of 50 students each can be formed?",
    answer: "Area = 50 × 40 = 2000 m². Each student needs 1 m². 2000 students fit exactly. Rows of 50 students: 2000/50 = 40 rows.",
    steps: [
      { stepNumber: 1, title: "Area check", explanation: "2000 m² = 2000 students × 1 m². Fits exactly." },
      { stepNumber: 2, title: "Rows", explanation: "2000/50 = 40 rows." },
    ],
    hint: "Compare total area with required area per student.",
    keyConcepts: ["area", "arrangement"],
    conceptsCovered: ["mth:8:ch05:square-root-estimation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch05", "PYQ-arrangement"],
    source: "previous-year",
  },
];
