/**
 * Question Bank — Mathematics, Class 8, Chapter 7: Comparing Quantities
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Percentage Increase and Decrease   — 20 q
 *   t2 Discount, Tax, and Simple Interest — 25 q
 *   t3 Compound Interest                  — 30 q
 *
 * Concept nodes:
 *   mth:8:ch07:percentage-increase
 *   mth:8:ch07:percentage-decrease
 *   mth:8:ch07:discount
 *   mth:8:ch07:tax-calculation
 *   mth:8:ch07:simple-interest
 *   mth:8:ch07:compound-interest-formula
 *   mth:8:ch07:ci-vs-si-comparison
 *   mth:8:ch07:half-yearly-quarterly
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH07_COMPARING_QUANTITIES: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Percentage Increase and Decrease
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch07-con-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Percentage increase = (Increase/Original value) × 100.",
    answer: "True. Percentage increase = (New − Original)/Original × 100.",
    steps: [{ stepNumber: 1, title: "Formula", explanation: "% increase = (increase/original)×100." }],
    hint: "The original value is the base for percentage calculations.",
    keyConcepts: ["percentage increase formula"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "percentage-formula"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A price rises from ₹200 to ₹250. Find the percentage increase.",
    answer: "Increase = 250 − 200 = 50. % increase = (50/200) × 100 = 25%.",
    steps: [
      { stepNumber: 1, title: "Find increase", explanation: "250 − 200 = 50." },
      { stepNumber: 2, title: "Percentage", explanation: "(50/200) × 100 = 25%." },
    ],
    hint: "Divide increase by original, not by new value.",
    keyConcepts: ["percentage increase"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "increase"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A population decreased from 50,000 to 45,000. Find the percentage decrease.",
    answer: "Decrease = 50000 − 45000 = 5000. % decrease = (5000/50000)×100 = 10%.",
    steps: [
      { stepNumber: 1, title: "Decrease", explanation: "50000 − 45000 = 5000." },
      { stepNumber: 2, title: "% decrease", explanation: "(5000/50000)×100 = 10%." },
    ],
    hint: "Always divide by the original (initial) value.",
    keyConcepts: ["percentage decrease"],
    conceptsCovered: ["mth:8:ch07:percentage-decrease"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "decrease"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If a shirt costs ₹500 after a 20% discount, what was the original price?",
    answer: "₹625. 80% of original = 500 → original = 500/0.80 = 625.",
    options: ["A) ₹600", "B) ₹620", "C) ₹625", "D) ₹650"],
    correctOption: "C",
    steps: [
      { stepNumber: 1, title: "After 20% discount, 80% remains", explanation: "0.80 × original = 500." },
      { stepNumber: 2, title: "Solve", explanation: "Original = 500/0.80 = 625." },
    ],
    hint: "After 20% off, 80% of original is paid.",
    keyConcepts: ["reverse percentage", "discount"],
    conceptsCovered: ["mth:8:ch07:percentage-decrease"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "reverse-percentage"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A bag has marked price ₹800. A 15% discount is offered. Find the selling price.",
    answer: "Discount = 15% of 800 = 120. Selling price = 800 − 120 = ₹680.",
    steps: [
      { stepNumber: 1, title: "Discount", explanation: "15/100 × 800 = 120." },
      { stepNumber: 2, title: "SP", explanation: "800 − 120 = ₹680." },
    ],
    hint: "Discount = (Discount%) × MP / 100.",
    keyConcepts: ["discount", "selling price"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "discount"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find Simple Interest on ₹5000 at 8% per annum for 3 years.",
    answer: "SI = (P × R × T)/100 = (5000 × 8 × 3)/100 = 120000/100 = ₹1200.",
    steps: [{ stepNumber: 1, title: "Apply formula", explanation: "SI = PRT/100 = 5000×8×3/100 = 1200." }],
    hint: "SI = P × R × T ÷ 100.",
    keyConcepts: ["simple interest"],
    conceptsCovered: ["mth:8:ch07:simple-interest"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "SI"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find Compound Interest on ₹10,000 at 10% p.a. for 2 years.",
    answer: "A = P(1 + R/100)ⁿ = 10000(1.1)² = 10000 × 1.21 = ₹12100. CI = 12100 − 10000 = ₹2100.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "A = 10000 × (1+10/100)² = 10000 × 1.21." },
      { stepNumber: 2, title: "Amount", explanation: "A = 12100." },
      { stepNumber: 3, title: "CI", explanation: "12100 − 10000 = ₹2100." },
    ],
    hint: "CI formula: A = P(1 + R/100)ⁿ.",
    keyConcepts: ["compound interest formula"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "CI"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "understand",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Compound Interest is always greater than or equal to Simple Interest for the same P, R, and T.",
    answer: "True. CI > SI for T > 1 year (when compounded annually). For T = 1 year, CI = SI. For T > 1, CI > SI because interest earns interest.",
    steps: [{ stepNumber: 1, title: "Comparison", explanation: "CI=SI for n=1; CI>SI for n>1." }],
    hint: "Think about whether interest earns more interest.",
    keyConcepts: ["CI vs SI comparison"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "CI-vs-SI"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find CI on ₹6000 at 10% p.a. compounded half-yearly for 1 year.",
    answer: "Half-yearly: R/2 = 5%, n = 2. A = 6000(1.05)² = 6000×1.1025 = ₹6615. CI = 615.",
    steps: [
      { stepNumber: 1, title: "Adjust rate and time", explanation: "R=5%, n=2 half-years." },
      { stepNumber: 2, title: "Amount", explanation: "6000×1.1025=6615." },
      { stepNumber: 3, title: "CI", explanation: "6615−6000=615." },
    ],
    hint: "For half-yearly compounding: halve the rate, double the periods.",
    keyConcepts: ["half-yearly compounding"],
    conceptsCovered: ["mth:8:ch07:half-yearly-quarterly"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "half-yearly"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A TV costs ₹15,000. GST of 18% is applied. Find the final price.",
    answer: "Tax = 18% of 15000 = 2700. Final price = 15000 + 2700 = ₹17700.",
    steps: [
      { stepNumber: 1, title: "Tax amount", explanation: "18/100 × 15000 = 2700." },
      { stepNumber: 2, title: "Final price", explanation: "15000 + 2700 = 17700." },
    ],
    hint: "Tax is added to the original price.",
    keyConcepts: ["tax calculation", "GST"],
    conceptsCovered: ["mth:8:ch07:tax-calculation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "tax"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A shop gives successive discounts of 20% and 10%. Find the effective discount on ₹1000.",
    answer: "After 20%: 1000 × 0.8 = 800. After 10%: 800 × 0.9 = 720. Total discount = 1000 − 720 = 280. Effective discount % = (280/1000)×100 = 28%.",
    steps: [
      { stepNumber: 1, title: "First discount", explanation: "1000×0.8=800." },
      { stepNumber: 2, title: "Second discount", explanation: "800×0.9=720." },
      { stepNumber: 3, title: "Effective", explanation: "(280/1000)×100=28%." },
    ],
    hint: "Apply discounts successively, not by adding percentages.",
    keyConcepts: ["successive discounts"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: ["Adding 20%+10%=30% directly — wrong!"],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "successive-discount"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch07-con-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 1, estimatedTimeMinutes: 2,
    question: "The formula A = P(1 + R/100)ⁿ gives:",
    answer: "Option B: the Amount after compound interest for n years.",
    options: ["A) Simple interest", "B) Amount after CI", "C) Principal only", "D) Discount"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Formula meaning", explanation: "A = P(1+R/100)ⁿ is the compound interest amount formula." }],
    hint: "CI uses exponential growth; SI uses linear growth.",
    keyConcepts: ["CI formula"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "CI-formula"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch07-nce-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A man got a 10% increase in his salary. If his new salary is ₹1,54,000, what was his original salary?",
    answer: "110% of original = 154000. Original = 154000/1.1 = ₹1,40,000.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Original × 1.10 = 154000." },
      { stepNumber: 2, title: "Solve", explanation: "Original = 154000/1.10 = 140000." },
    ],
    hint: "After 10% increase, 110% of original = new salary.",
    keyConcepts: ["reverse percentage", "salary"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "On Sunday 845 people went to a zoo. On Monday only 169 people. Find the % decrease.",
    answer: "Decrease = 845 − 169 = 676. % decrease = (676/845)×100 = 80%.",
    steps: [
      { stepNumber: 1, title: "Decrease", explanation: "845−169=676." },
      { stepNumber: 2, title: "Percentage", explanation: "(676/845)×100 = 80%." },
    ],
    hint: "Divide the decrease by Sunday's count (original).",
    keyConcepts: ["percentage decrease"],
    conceptsCovered: ["mth:8:ch07:percentage-decrease"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Fabina borrows ₹12,500 at 12% per annum for 3 years at simple interest and Radha borrows the same amount for the same period at 10% p.a. compounded annually. Who pays more interest and by how much?",
    answer: "Fabina SI = 12500×12×3/100 = ₹4500. Radha CI: A = 12500(1.1)³ = 12500×1.331 = 16637.50. CI = 4137.50. Fabina pays more: 4500 − 4137.50 = ₹362.50 more.",
    steps: [
      { stepNumber: 1, title: "Fabina SI", explanation: "12500×12×3/100 = 4500." },
      { stepNumber: 2, title: "Radha CI", explanation: "12500×(1.1)³ = 12500×1.331 = 16637.5; CI=4137.5." },
      { stepNumber: 3, title: "Difference", explanation: "4500−4137.5=362.5." },
    ],
    hint: "Calculate both SI and CI separately.",
    keyConcepts: ["SI vs CI comparison"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Find the compound interest on ₹8000 at 15% per annum for 3 years.",
    answer: "A = 8000(1+15/100)³ = 8000×(1.15)³ = 8000×1.520875 = ₹12167. CI = 12167−8000 = ₹4167.",
    steps: [
      { stepNumber: 1, title: "1st year", explanation: "8000×0.15=1200; A₁=9200." },
      { stepNumber: 2, title: "2nd year", explanation: "9200×0.15=1380; A₂=10580." },
      { stepNumber: 3, title: "3rd year", explanation: "10580×0.15=1587; A₃=12167." },
      { stepNumber: 4, title: "CI", explanation: "12167−8000=4167." },
    ],
    hint: "Use year-by-year method or the formula A=P(1+R/100)³.",
    keyConcepts: ["compound interest"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A refrigerator listed at ₹14,000 is available for ₹13,650. Find the discount and discount percent.",
    answer: "Discount = 14000 − 13650 = ₹350. Discount% = (350/14000)×100 = 2.5%.",
    steps: [
      { stepNumber: 1, title: "Discount", explanation: "14000−13650=350." },
      { stepNumber: 2, title: "Discount%", explanation: "(350/14000)×100=2.5%." },
    ],
    hint: "Discount% is always on Marked Price (MP).",
    keyConcepts: ["discount", "discount percent"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Anita takes a loan of ₹5000 at 15% p.a. for 2 years at simple interest. What amount does she pay back?",
    answer: "SI = 5000×15×2/100 = ₹1500. Total = 5000+1500 = ₹6500.",
    steps: [
      { stepNumber: 1, title: "SI", explanation: "5000×15×2/100=1500." },
      { stepNumber: 2, title: "Total", explanation: "5000+1500=6500." },
    ],
    hint: "Total repayment = Principal + SI.",
    keyConcepts: ["simple interest", "loan repayment"],
    conceptsCovered: ["mth:8:ch07:simple-interest"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "What is the compound interest on ₹7500 at 8% p.a. for 3 years? Also find SI and compare.",
    answer: "CI: A = 7500(1.08)³ = 7500×1.259712 = 9447.84. CI = 1947.84. SI = 7500×8×3/100 = 1800. CI > SI by ₹147.84.",
    steps: [
      { stepNumber: 1, title: "CI calculation", explanation: "A = 7500×1.08³ = 9447.84; CI = 1947.84." },
      { stepNumber: 2, title: "SI calculation", explanation: "SI = 7500×8×3/100 = 1800." },
      { stepNumber: 3, title: "Compare", explanation: "CI − SI = 147.84." },
    ],
    hint: "Calculate both and subtract to compare.",
    keyConcepts: ["CI vs SI"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find CI on ₹10,000 at 10% p.a. for 2 years compounded half-yearly.",
    answer: "Half-yearly: R=5%, n=4. A = 10000(1.05)⁴ = 10000×1.21550625 = ₹12155.06. CI = 2155.06 ≈ ₹2155.",
    steps: [
      { stepNumber: 1, title: "Adjust", explanation: "R=5%; n=4 half-years." },
      { stepNumber: 2, title: "Amount", explanation: "10000×(1.05)⁴ = 10000×1.2155 = 12155." },
      { stepNumber: 3, title: "CI", explanation: "12155−10000=2155." },
    ],
    hint: "Halve the rate and double the time for half-yearly.",
    keyConcepts: ["half-yearly compounding"],
    conceptsCovered: ["mth:8:ch07:half-yearly-quarterly"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The price of a washing machine inclusive of 8% VAT is ₹13,500. Find the original price without VAT.",
    answer: "108% of original = 13500. Original = 13500/1.08 = ₹12500.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "Original × 1.08 = 13500." },
      { stepNumber: 2, title: "Solve", explanation: "13500/1.08 = 12500." },
    ],
    hint: "Price with tax = original × (1 + tax%/100).",
    keyConcepts: ["VAT", "reverse tax"],
    conceptsCovered: ["mth:8:ch07:tax-calculation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A machinery worth ₹10,000 depreciates at 10% p.a. Find its value after 3 years.",
    answer: "Depreciation uses CI formula with depreciation rate: V = P(1 − R/100)ⁿ. V = 10000(0.9)³ = 10000×0.729 = ₹7290.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "V = 10000×(1−10/100)³ = 10000×(0.9)³." },
      { stepNumber: 2, title: "Compute", explanation: "0.9³ = 0.729; V = 7290." },
    ],
    hint: "For depreciation, subtract the rate: (1 − R/100).",
    keyConcepts: ["depreciation", "compound decrease"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: ["Using (1 + R/100) instead of (1 − R/100) for depreciation."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.5"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A shopkeeper buys 80 articles for ₹2400 and sells them at a profit of 16%. Find the selling price of each article.",
    answer: "CP each = 2400/80 = ₹30. SP each = 30×1.16 = ₹34.80.",
    steps: [
      { stepNumber: 1, title: "CP per article", explanation: "2400/80=30." },
      { stepNumber: 2, title: "SP", explanation: "30×1.16=34.80." },
    ],
    hint: "Profit% is applied on cost price.",
    keyConcepts: ["profit percent", "selling price"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "At what rate % p.a. will ₹2000 amount to ₹2205 in 2 years compounded annually?",
    answer: "2000(1+R/100)² = 2205. (1+R/100)² = 2205/2000 = 1.1025 = (1.05)². 1+R/100 = 1.05. R = 5%.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "(1+R/100)² = 1.1025." },
      { stepNumber: 2, title: "Solve", explanation: "1+R/100 = 1.05; R = 5%." },
    ],
    hint: "Divide Amount by Principal and take the square root.",
    keyConcepts: ["finding rate in CI"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Meera's loan is ₹20,000 at 12% SI for 6 months. Find the interest.",
    answer: "6 months = 0.5 years. SI = 20000×12×0.5/100 = ₹1200.",
    steps: [{ stepNumber: 1, title: "SI with fractional year", explanation: "20000×12×(1/2)/100 = 1200." }],
    hint: "Convert months to fraction of a year.",
    keyConcepts: ["simple interest", "fraction of year"],
    conceptsCovered: ["mth:8:ch07:simple-interest"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A town has population 200000. It grows at 5% p.a. Find population after 2 years. Also find if it decreases at 5% for 2 years instead.",
    answer: "Growth: 200000×(1.05)² = 200000×1.1025 = 220500. Decrease: 200000×(0.95)² = 200000×0.9025 = 180500.",
    steps: [
      { stepNumber: 1, title: "Growth", explanation: "200000×1.1025=220500." },
      { stepNumber: 2, title: "Decrease", explanation: "200000×0.9025=180500." },
    ],
    hint: "For growth use (1+R/100), for decrease use (1−R/100).",
    keyConcepts: ["population growth", "compound growth/decrease"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.5"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A seller marks an article at ₹500 and sells for ₹400. Find the discount and discount percentage.",
    answer: "Discount = 500−400=₹100. Discount% = (100/500)×100 = 20%.",
    steps: [
      { stepNumber: 1, title: "Discount", explanation: "500−400=100." },
      { stepNumber: 2, title: "Discount%", explanation: "(100/500)×100=20%." },
    ],
    hint: "Discount% is on the Marked Price.",
    keyConcepts: ["discount calculation"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find CI on ₹12,600 for 2 years at 10% compounded annually, then compare with SI.",
    answer: "A = 12600×(1.1)² = 12600×1.21 = ₹15246. CI = 2646. SI = 12600×10×2/100 = 2520. CI−SI = ₹126.",
    steps: [
      { stepNumber: 1, title: "CI", explanation: "12600×1.21=15246; CI=2646." },
      { stepNumber: 2, title: "SI", explanation: "12600×10×2/100=2520." },
      { stepNumber: 3, title: "Difference", explanation: "2646−2520=126." },
    ],
    hint: "The difference CI−SI = P×(R/100)² for 2 years.",
    keyConcepts: ["CI vs SI", "two-year comparison"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-017",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Find CI on ₹15,625 for 1.5 years at 16% compounded half-yearly.",
    answer: "Half-yearly: R=8%, n=3. A = 15625(1.08)³ = 15625×1.259712 = 19683. CI = 19683−15625 = ₹4058.",
    steps: [
      { stepNumber: 1, title: "Adjust", explanation: "R=8% per half-year, n=3 half-years." },
      { stepNumber: 2, title: "Amount", explanation: "15625×(1.08)³ = 15625×1.259712 = 19683." },
      { stepNumber: 3, title: "CI", explanation: "19683−15625=4058." },
    ],
    hint: "1.5 years = 3 half-years; halve annual rate.",
    keyConcepts: ["half-yearly for 1.5 years"],
    conceptsCovered: ["mth:8:ch07:half-yearly-quarterly"],
    prerequisites: [],
    commonErrors: ["Using n=1.5 with annual formula instead of n=3 with half-yearly formula."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "NCERT-Ex7.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch07-nce-018",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A number increases by 5% and then decreases by 5%. What is the net change in %?",
    answer: "Net factor = 1.05 × 0.95 = 0.9975. Net change = −0.25% (a decrease of 0.25%).",
    steps: [
      { stepNumber: 1, title: "Successive factor", explanation: "1.05 × 0.95 = 0.9975." },
      { stepNumber: 2, title: "Net change", explanation: "(0.9975−1)×100 = −0.25%." },
    ],
    hint: "Multiply the factors; don't assume they cancel out.",
    keyConcepts: ["successive percentage change"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: ["Thinking 5% increase and 5% decrease cancel out exactly."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch07", "successive-percent"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch07-ics-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Find CI on ₹20,000 at 10% p.a. for 2½ years compounded annually, and compare with CI when compounded half-yearly.",
    answer: "Annual for 2½ years: A₂ = 20000×(1.1)² = 24200; then 6 months at 10% SI: 24200×0.10×0.5 = 1210; A = 25410; CI = 5410. Half-yearly for 2.5 years = 5 periods at 5%: A = 20000×(1.05)⁵ = 20000×1.27628 = 25525.6; CI = 5525.6. Half-yearly gives more CI by 5525.6−5410=115.6.",
    steps: [
      { stepNumber: 1, title: "Annual 2 years", explanation: "20000×1.21=24200." },
      { stepNumber: 2, title: "Annual + 6-month SI", explanation: "24200+1210=25410; CI=5410." },
      { stepNumber: 3, title: "Half-yearly 5 periods", explanation: "20000×(1.05)⁵=25525.6; CI=5525.6." },
    ],
    hint: "For 2½ years with annual compounding, apply 2 years then 6-month SI.",
    keyConcepts: ["2.5 years CI", "half-yearly vs annual"],
    conceptsCovered: ["mth:8:ch07:half-yearly-quarterly"],
    prerequisites: [],
    commonErrors: ["Applying fractional exponent directly — only valid for continuous compounding."],
    tags: ["ICSE", "class8", "ch07", "2.5-years"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch07-ics-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A shopkeeper gives two successive discounts of 30% and 20% on an article marked ₹3000. Find the selling price.",
    answer: "After 30%: 3000×0.7 = 2100. After 20%: 2100×0.8 = 1680. SP = ₹1680.",
    steps: [
      { stepNumber: 1, title: "First discount", explanation: "3000×0.70=2100." },
      { stepNumber: 2, title: "Second discount", explanation: "2100×0.80=1680." },
    ],
    hint: "Apply each discount sequentially on the reduced price.",
    keyConcepts: ["successive discounts"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch07", "successive-discount"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch07-ics-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In how many years will ₹6250 amount to ₹7290 at 8% p.a. compounded annually?",
    answer: "6250(1.08)ⁿ = 7290. (1.08)ⁿ = 7290/6250 = 1.1664 = (1.08)². So n = 2 years.",
    steps: [
      { stepNumber: 1, title: "Divide", explanation: "(1.08)ⁿ = 7290/6250 = 1.1664." },
      { stepNumber: 2, title: "Recognise power", explanation: "1.08² = 1.1664. So n=2." },
    ],
    hint: "Express the ratio as a power of (1+R/100).",
    keyConcepts: ["finding time in CI"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch07", "find-time"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch07-ics-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A dealer buys a bicycle for ₹1125 and marks it at 30% above cost. He gives a 10% discount. Find profit/loss %.",
    answer: "MP = 1125×1.3 = ₹1462.5. SP = 1462.5×0.9 = ₹1316.25. Profit = 1316.25−1125 = 191.25. Profit% = (191.25/1125)×100 = 17%.",
    steps: [
      { stepNumber: 1, title: "MP", explanation: "1125×1.3=1462.5." },
      { stepNumber: 2, title: "SP", explanation: "1462.5×0.9=1316.25." },
      { stepNumber: 3, title: "Profit%", explanation: "(191.25/1125)×100=17%." },
    ],
    hint: "Profit% is on cost price.",
    keyConcepts: ["mark-up", "discount", "profit percent"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch07", "profit-discount"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch07-ics-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Prices fell by 10% this year after rising by 20% last year. What is the net % change over two years?",
    answer: "Net factor = 1.20×0.90 = 1.08. Net change = 8% increase over two years.",
    steps: [
      { stepNumber: 1, title: "Successive factors", explanation: "1.20 × 0.90 = 1.08." },
      { stepNumber: 2, title: "Net", explanation: "(1.08−1)×100 = 8% increase." },
    ],
    hint: "Multiply the successive percentage change factors.",
    keyConcepts: ["successive percentage changes"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: ["20−10=10% — incorrect; order matters."],
    tags: ["ICSE", "class8", "ch07", "successive-change"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch07-ics-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Find the principal if CI for 2 years at 10% p.a. is ₹2100.",
    answer: "CI = P[(1+R/100)ⁿ − 1] = P[(1.1)² − 1] = P[1.21−1] = 0.21P = 2100. P = 2100/0.21 = ₹10000.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "0.21P = 2100." },
      { stepNumber: 2, title: "Solve", explanation: "P = 10000." },
    ],
    hint: "CI = P × [(1+R/100)ⁿ − 1].",
    keyConcepts: ["finding principal from CI"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch07", "find-principal"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch07-ics-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "CI on ₹4000 for 2 years is ₹840. Find the rate.",
    answer: "4000(1+R/100)² = 4840. (1+R/100)² = 1.21. 1+R/100 = 1.1. R = 10%.",
    steps: [
      { stepNumber: 1, title: "Amount", explanation: "4000+840=4840." },
      { stepNumber: 2, title: "Solve for R", explanation: "(1+R/100)² = 4840/4000 = 1.21 → R=10%." },
    ],
    hint: "Find A/P and take the nth root.",
    keyConcepts: ["finding rate in CI"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch07", "find-rate"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch07-cmp-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A laptop is on sale at 25% off. The sale price is ₹45,000. What was the original price?",
    answer: "75% of original = 45000. Original = 45000/0.75 = ₹60,000.",
    steps: [
      { stepNumber: 1, title: "After 25% off, 75% remains", explanation: "0.75 × original = 45000." },
      { stepNumber: 2, title: "Solve", explanation: "45000/0.75 = 60000." },
    ],
    hint: "If 25% is off, you pay 75%.",
    keyConcepts: ["reverse percentage", "discount"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If 40% of the students in a school are girls and there are 600 girls, how many students are there in total?",
    answer: "1500. 40% of total = 600. Total = 600/0.4 = 1500.",
    options: ["A) 1000", "B) 1200", "C) 1400", "D) 1500"],
    correctOption: "D",
    steps: [{ stepNumber: 1, title: "Solve", explanation: "0.4×T=600; T=1500." }],
    hint: "40% of total = number of girls.",
    keyConcepts: ["percentage", "reverse calculation"],
    conceptsCovered: ["mth:8:ch07:percentage-decrease"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "percentage"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Riya invests ₹5000 in a bank that offers 6% CI annually. How much does she have after 3 years?",
    answer: "A = 5000×(1.06)³ = 5000×1.191016 = ₹5955.08 ≈ ₹5955.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "A=5000×(1.06)³." },
      { stepNumber: 2, title: "Compute", explanation: "1.06³=1.191016; A≈5955." },
    ],
    hint: "Compounded annually: A = P(1+R/100)³.",
    keyConcepts: ["CI", "investment"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "investment"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A mobile phone costs ₹12,000. An 18% GST is charged on it. How much does a customer pay?",
    answer: "GST = 18% of 12000 = 2160. Total = 12000 + 2160 = ₹14,160.",
    steps: [
      { stepNumber: 1, title: "GST", explanation: "0.18×12000=2160." },
      { stepNumber: 2, title: "Total", explanation: "12000+2160=14160." },
    ],
    hint: "Total price = cost + GST.",
    keyConcepts: ["GST", "tax"],
    conceptsCovered: ["mth:8:ch07:tax-calculation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "GST"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Should you prefer 5% SI or 4.5% CI annually for a 2-year deposit of ₹10,000? Calculate both.",
    answer: "SI: 10000×5×2/100 = ₹1000. CI: 10000×((1.045)²−1) = 10000×0.092025 = ₹920.25. SI (₹1000) > CI (₹920.25). Prefer SI in this case.",
    steps: [
      { stepNumber: 1, title: "SI = 1000", explanation: "10000×0.05×2=1000." },
      { stepNumber: 2, title: "CI ≈ 920", explanation: "10000×(1.045²−1)≈920." },
      { stepNumber: 3, title: "Compare", explanation: "SI higher here — prefer 5% SI." },
    ],
    hint: "Higher rate doesn't always mean more return; check actual amounts.",
    keyConcepts: ["comparing investment options"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: ["Automatically preferring CI over SI without calculating."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "decision-making"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A car's value is ₹5,00,000 and it depreciates by 12% per year. What is it worth after 1 year?",
    answer: "Value = 500000×(1−0.12) = 500000×0.88 = ₹4,40,000.",
    steps: [{ stepNumber: 1, title: "Depreciation", explanation: "500000×0.88=440000." }],
    hint: "Depreciation reduces value: multiply by (1 − rate).",
    keyConcepts: ["depreciation", "percentage decrease"],
    conceptsCovered: ["mth:8:ch07:percentage-decrease"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "depreciation"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Rahul borrowed ₹8000 at 9% SI. He pays back ₹9080 in total. For how many years was the loan?",
    answer: "SI = 9080−8000 = 1080. Time = (SI×100)/(P×R) = (1080×100)/(8000×9) = 108000/72000 = 1.5 years.",
    steps: [
      { stepNumber: 1, title: "SI = 1080", explanation: "9080−8000=1080." },
      { stepNumber: 2, title: "Time", explanation: "T = 1080×100/(8000×9) = 1.5 years." },
    ],
    hint: "T = (SI × 100)/(P × R).",
    keyConcepts: ["finding time in SI"],
    conceptsCovered: ["mth:8:ch07:simple-interest"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "SI-find-time"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A school's enrollment grew from 500 to 600. By what percent did it grow?",
    answer: "(100/500)×100 = 20% increase.",
    steps: [{ stepNumber: 1, title: "Percentage increase", explanation: "(600−500)/500×100=20%." }],
    hint: "Increase ÷ original × 100.",
    keyConcepts: ["percentage increase"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "₹1000 is invested at 10% CI for 2 years. The amount is:",
    answer: "₹1210. A = 1000×(1.1)² = 1210.",
    options: ["A) ₹1100", "B) ₹1200", "C) ₹1210", "D) ₹1220"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "A = 1000×1.21=1210", explanation: "CI gives 1210, not 1200 (which would be SI)." }],
    hint: "CI: interest also earns interest in year 2.",
    keyConcepts: ["compound interest"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A shopkeeper offers two deals: Deal A — 40% discount; Deal B — two successive discounts of 25% and 20%. Which is better for the customer on an item marked ₹1000?",
    answer: "Deal A: 1000×0.6 = ₹600. Deal B: 1000×0.75×0.80 = ₹600. Both give ₹600! They are equivalent.",
    steps: [
      { stepNumber: 1, title: "Deal A", explanation: "1000×0.6=600." },
      { stepNumber: 2, title: "Deal B", explanation: "1000×0.75×0.80=600." },
      { stepNumber: 3, title: "Compare", explanation: "Equal — both ₹600." },
    ],
    hint: "Calculate the final selling price for both deals.",
    keyConcepts: ["successive discounts", "comparison"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: ["Thinking 25+20=45% is better than 40%."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "comparison"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A virus spreads and the number of infected doubles every day. If there are 100 infected today, how many after 5 days?",
    answer: "100 × 2⁵ = 100 × 32 = 3200 infected.",
    steps: [
      { stepNumber: 1, title: "Doubling = 100% increase per day", explanation: "CI formula: 100×(1+1)⁵ = 100×32 = 3200." },
    ],
    hint: "Doubling is 100% increase — compound growth.",
    keyConcepts: ["exponential growth", "CI in context"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "exponential"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "At what rate % p.a. will ₹5000 give SI of ₹1500 in 3 years?",
    answer: "10%. R = (1500×100)/(5000×3) = 10%.",
    options: ["A) 8%", "B) 9%", "C) 10%", "D) 12%"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Formula R", explanation: "R=SI×100/(P×T)=1500×100/(5000×3)=10." }],
    hint: "R = (SI × 100)/(P × T).",
    keyConcepts: ["finding rate in SI"],
    conceptsCovered: ["mth:8:ch07:simple-interest"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "find-rate-SI"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A recipe requires 400 g of flour. You decide to make 75% of the recipe. How much flour do you need?",
    answer: "75% of 400 = 0.75 × 400 = 300 g.",
    steps: [{ stepNumber: 1, title: "Calculate", explanation: "0.75×400=300 g." }],
    hint: "75% of 400 = (75/100)×400.",
    keyConcepts: ["percentage of a quantity"],
    conceptsCovered: ["mth:8:ch07:percentage-decrease"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "For CI, what is the difference between interest for year 1 and year 2 if P=₹10,000, R=10%?",
    answer: "Year 1 interest = 10000×0.10 = ₹1000. Year 2 interest = 11000×0.10 = ₹1100. Difference = ₹100. This equals 10% of year 1 interest.",
    steps: [
      { stepNumber: 1, title: "Year 1", explanation: "10000×0.1=1000." },
      { stepNumber: 2, title: "Year 2", explanation: "(10000+1000)×0.1=1100." },
      { stepNumber: 3, title: "Difference", explanation: "1100−1000=100." },
    ],
    hint: "In CI, each year's interest is larger because it's on an increased principal.",
    keyConcepts: ["year-by-year CI", "growing interest"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "CI-year-analysis"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "A moneylender charges 20% SI while a bank charges 12% CI. On ₹10,000 for 3 years, which is cheaper?",
    answer: "SI = 10000×20×3/100 = ₹6000. CI: A = 10000×(1.12)³ = 10000×1.404928 = 14049.28; CI = ₹4049.28. Bank CI (₹4049) < Moneylender SI (₹6000). Bank is cheaper by ₹1950.72.",
    steps: [
      { stepNumber: 1, title: "SI = 6000", explanation: "10000×20×3/100=6000." },
      { stepNumber: 2, title: "CI ≈ 4049", explanation: "10000×1.12³=14049; CI=4049." },
      { stepNumber: 3, title: "Decision", explanation: "CI cheaper by ~1951." },
    ],
    hint: "Calculate total interest in both cases and compare.",
    keyConcepts: ["decision making", "SI vs CI"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "decision"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch07-cmp-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The number of students in a school increased by 15% to 1150. What was the original number?",
    answer: "115% of original = 1150. Original = 1150/1.15 = 1000.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "1.15 × original = 1150." },
      { stepNumber: 2, title: "Solve", explanation: "Original = 1000." },
    ],
    hint: "After 15% increase: 115% of original = new number.",
    keyConcepts: ["reverse percentage"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch07", "reverse"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch07-hot-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove that CI − SI = P(R/100)² for 2 years compounded annually.",
    answer: "SI = 2PR/100. CI: A = P(1+R/100)² = P(1 + 2R/100 + R²/10000). CI = 2PR/100 + PR²/10000. CI − SI = PR²/10000 = P(R/100)². ✓",
    steps: [
      { stepNumber: 1, title: "SI for 2 years", explanation: "SI = 2PR/100." },
      { stepNumber: 2, title: "CI using binomial", explanation: "A = P(1+r)²=P(1+2r+r²) where r=R/100. CI=P(2r+r²)." },
      { stepNumber: 3, title: "Difference", explanation: "CI−SI = Pr² = P(R/100)²." },
    ],
    hint: "Expand (1+R/100)² using the algebraic identity.",
    keyConcepts: ["CI−SI formula", "algebraic proof"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: ["Not simplifying R²/10000 = (R/100)²."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "A sum doubles in 6 years at compound interest. In how many years will it become 8 times?",
    answer: "If sum doubles in 6 years: P×(1+R/100)⁶ = 2P. So (1+R/100)⁶ = 2. For 8 times: (1+R/100)ⁿ = 8 = 2³ = [(1+R/100)⁶]³. So n = 18 years.",
    steps: [
      { stepNumber: 1, title: "Doubling relation", explanation: "(1+R/100)⁶ = 2." },
      { stepNumber: 2, title: "For 8 times", explanation: "(1+R/100)ⁿ = 2³ = [(1+R/100)⁶]³; n=18." },
    ],
    hint: "8 = 2³; if doubling takes 6 years, tripling the doubling takes 18.",
    keyConcepts: ["doubling time", "power of compound growth"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: ["Multiplying 6×3=18 without justification — explain via exponents."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "doubling-time"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If prices increase by p% and then decrease by p%, what is the net % change? Show it's always a decrease.",
    answer: "Net factor = (1+p/100)(1−p/100) = 1−(p/100)² < 1. So the result is always less than the original — a net decrease of (p/100)²×100 = p²/100 %.",
    steps: [
      { stepNumber: 1, title: "Multiply factors", explanation: "(1+p/100)(1−p/100) = 1−p²/10000." },
      { stepNumber: 2, title: "Net change", explanation: "1−p²/10000 < 1 always (since p>0). Decrease = p²/100 %." },
    ],
    hint: "Use difference of squares: (1+a)(1−a) = 1−a².",
    keyConcepts: ["successive percentage", "algebraic analysis"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: ["Assuming equal % increase and decrease cancel out."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "successive-algebraic"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "The CI in 3rd year is ₹1331 and in 2nd year is ₹1210. Find P and R.",
    answer: "Interest in year 3 / interest in year 2 = (1+R/100). 1331/1210 = 1.1. R = 10%. Year 2 interest = P×(1.1)×(0.1) = P×0.11×1.1... Alternatively: I₂ = P(1.1)¹×0.1 = 0.11P×(1.1)°... Let me redo: I₂ = A₁×R/100 = P(1.1)×0.1 = 0.11P×(1.1)... I₂ = interest accrued in year 2 = A₁×(R/100) = P(1+R/100)¹×(R/100). I₃ = P(1.1)²×0.1 = 1210. So P×1.21×0.1=1210 → P×0.121=1210 → P=10000. Verify: I₂=10000×1.1×0.1=1100 (not 1210). There's a discrepancy. Let me reconsider. I₃ = P(1+R/100)²×R/100. If I₃=1331 and I₂=1210: I₃/I₂=(1+R/100)=1331/1210=1.1; R=10%. I₂=P×(1.1)¹×0.1=0.11P=1210 → P=11000. Check I₃: 11000×(1.1)²×0.1=11000×0.121=1331 ✓.",
    steps: [
      { stepNumber: 1, title: "Find R", explanation: "I₃/I₂=(1+R/100)=1331/1210=1.1; R=10%." },
      { stepNumber: 2, title: "Find P", explanation: "I₂=P(1.1)¹×0.1=0.11P=1210; P=11000." },
      { stepNumber: 3, title: "Verify", explanation: "I₃=11000×1.21×0.1=1331 ✓." },
    ],
    hint: "Ratio of consecutive year interests equals (1+R/100).",
    keyConcepts: ["finding P and R from CI", "year-by-year analysis"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: ["Using wrong year's formula for CI."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "find-P-R"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Two banks offer: Bank A: 12% SI; Bank B: 10% CI half-yearly. For ₹10,000 for 2 years, which gives more interest?",
    answer: "Bank A SI: 10000×12×2/100 = ₹2400. Bank B CI half-yearly: R=5%, n=4. A=10000×(1.05)⁴=10000×1.21550625=12155.06; CI=₹2155.06. Bank A SI (₹2400) > Bank B CI (₹2155). Bank A pays more.",
    steps: [
      { stepNumber: 1, title: "Bank A SI", explanation: "2400." },
      { stepNumber: 2, title: "Bank B CI", explanation: "10000×1.05⁴=12155; CI=2155." },
      { stepNumber: 3, title: "Conclusion", explanation: "SI higher." },
    ],
    hint: "Don't assume CI always beats SI — compare actual values.",
    keyConcepts: ["comparing SI and CI", "half-yearly"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: ["Assuming CI always gives more — not true when rate is lower."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "comparison"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "A shopkeeper gives a discount of x% and still makes a 10% profit. If CP is ₹100 and MP is ₹150, find x.",
    answer: "SP = CP × 1.10 = ₹110. Discount = MP − SP = 150 − 110 = ₹40. Discount% = (40/150)×100 = 26.67%.",
    steps: [
      { stepNumber: 1, title: "SP", explanation: "100×1.10=110." },
      { stepNumber: 2, title: "Discount", explanation: "150−110=40." },
      { stepNumber: 3, title: "Discount%", explanation: "40/150×100=26.67%." },
    ],
    hint: "SP must be above CP for profit; discount is on MP.",
    keyConcepts: ["profit with discount", "mark-up and discount"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: ["Calculating discount% on CP instead of MP."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "profit-with-discount"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Design a loan scenario where a borrower is better off with 15% CI than with 18% SI over 4 years. Verify.",
    answer: "Choose P = ₹10,000. SI: 10000×18×4/100 = ₹7200 extra. CI at 15%: A = 10000×(1.15)⁴ = 10000×1.7490 = 17490; CI = ₹7490. Here 15% CI (₹7490) > 18% SI (₹7200) — CI is MORE expensive. Try 2 years: SI=3600, CI=10000×1.15²−10000=2225. CI cheaper. So: 15% CI is cheaper than 18% SI for shorter periods (n≤2) but not for longer. Conclusion: For 1 year, CI=1500 < SI=1800. For 2 years, CI=2225 < SI=3600. Borrower is better off with 15% CI for 1 or 2 years.",
    steps: [
      { stepNumber: 1, title: "Year 1 comparison", explanation: "CI=1500, SI=1800. CI better." },
      { stepNumber: 2, title: "Year 2 comparison", explanation: "CI=2225, SI=3600. CI still better." },
      { stepNumber: 3, title: "Year 3", explanation: "CI=3048, SI=5400. CI better." },
      { stepNumber: 4, title: "Conclusion", explanation: "For all short periods (≤3-4 years), 15% CI is cheaper than 18% SI." },
    ],
    hint: "Compare actual interest amounts, not just rates.",
    keyConcepts: ["creating scenarios", "loan comparison"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: ["Comparing rates directly without computing actual interest."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "design"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "The population of two cities A and B are 2 lakh and 3 lakh respectively. A grows at 10% p.a. and B shrinks at 5% p.a. After how many years will they be equal? (Estimate to the nearest year.)",
    answer: "A: 200000×(1.1)ⁿ = B: 300000×(0.95)ⁿ. (1.1/0.95)ⁿ = 1.5. (1.157...)ⁿ = 1.5. n = ln(1.5)/ln(1.157) ≈ 0.405/0.145 ≈ 2.8 ≈ 3 years. Check n=3: A=266200, B=256987. Close. n=4: A=292820, B=244138. Crossed — so ≈ 3 years.",
    steps: [
      { stepNumber: 1, title: "Set equal", explanation: "200000×(1.1)ⁿ = 300000×(0.95)ⁿ." },
      { stepNumber: 2, title: "Simplify", explanation: "(1.1/0.95)ⁿ = 1.5." },
      { stepNumber: 3, title: "Estimate", explanation: "n≈3 by trial." },
    ],
    hint: "Try successive years and see when A exceeds B.",
    keyConcepts: ["population growth and decline", "intersection"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: ["Using SI formula for population growth."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "population-intersection"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "A bank charges 12% p.a. on a loan. After 2 years, the borrower pays ₹12544. If it was compounded annually, find the principal.",
    answer: "A = P(1.12)² = P×1.2544 = 12544. P = 12544/1.2544 = ₹10,000.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "P×1.2544=12544." },
      { stepNumber: 2, title: "Solve", explanation: "P=10000." },
    ],
    hint: "Reverse the CI formula: P = A / (1+R/100)ⁿ.",
    keyConcepts: ["finding principal from amount"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "reverse-CI"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch07-hot-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Design a 5-year savings plan: invest ₹10,000 annually at the START of each year at 10% CI. Find total value after 5 years.",
    answer: "Each annual deposit grows at 10% CI until end of year 5. Year 1 deposit (invested at start of yr 1) grows for 5 years: 10000×(1.1)⁵=16105.10. Year 2 deposit grows 4 years: 10000×(1.1)⁴=14641. Year 3: 10000×(1.1)³=13310. Year 4: 10000×(1.1)²=12100. Year 5: 10000×1.1=11000. Total = 16105+14641+13310+12100+11000 = ₹67156.",
    steps: [
      { stepNumber: 1, title: "Each deposit's growth", explanation: "Yr1:16105, Yr2:14641, Yr3:13310, Yr4:12100, Yr5:11000." },
      { stepNumber: 2, title: "Sum", explanation: "67156." },
    ],
    hint: "Each deposit grows for a different number of years.",
    keyConcepts: ["annuity", "CI over multiple periods"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: ["Forgetting that different years' deposits grow for different durations."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch07", "annuity"],
    source: "hots",
  },

  // ── PREVIOUS-YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch07-pyq-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find SI on ₹3600 at 12.5% p.a. for 3 years.",
    answer: "SI = 3600×12.5×3/100 = 3600×37.5/100 = ₹1350.",
    steps: [{ stepNumber: 1, title: "Apply formula", explanation: "3600×12.5×3/100=1350." }],
    hint: "SI = PRT/100.",
    keyConcepts: ["simple interest"],
    conceptsCovered: ["mth:8:ch07:simple-interest"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Find CI on ₹16,000 at 15% p.a. for 2 years compounded annually.",
    answer: "A = 16000×(1.15)² = 16000×1.3225 = 21160. CI = 21160−16000 = ₹5160.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "A=16000×1.3225=21160." },
      { stepNumber: 2, title: "CI", explanation: "21160−16000=5160." },
    ],
    hint: "A = P(1+R/100)².",
    keyConcepts: ["compound interest"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "A watch is marked ₹1200 and sold for ₹1080. The discount percent is:",
    answer: "10%. (1200−1080)/1200×100=10%.",
    options: ["A) 8%", "B) 9%", "C) 10%", "D) 12%"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Discount%", explanation: "120/1200×100=10%." }],
    hint: "Discount% = (Discount/MP) × 100.",
    keyConcepts: ["discount percent"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "In what time will ₹5000 amount to ₹6655 at 10% CI p.a.?",
    answer: "5000(1.1)ⁿ = 6655. (1.1)ⁿ = 1.331 = (1.1)³. n = 3 years.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "(1.1)ⁿ = 6655/5000 = 1.331." },
      { stepNumber: 2, title: "Recognise", explanation: "1.1³ = 1.331. So n=3." },
    ],
    hint: "Compute 1.1, 1.21, 1.331... until you reach the ratio.",
    keyConcepts: ["finding time in CI"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The price of petrol increased by 25%. By what % must it be reduced to bring it back to original?",
    answer: "New price = 1.25×original. To reduce to original: reduction = 0.25/1.25 × 100 = 20%.",
    steps: [
      { stepNumber: 1, title: "After 25% rise", explanation: "Price = 1.25P." },
      { stepNumber: 2, title: "Required reduction", explanation: "0.25P/1.25P × 100 = 20%." },
    ],
    hint: "The reduction % is calculated on the increased price, not the original.",
    keyConcepts: ["reverse percentage", "price change"],
    conceptsCovered: ["mth:8:ch07:percentage-decrease"],
    prerequisites: [],
    commonErrors: ["Saying 25% reduction — that's on the original, not the new higher price."],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "The CI on a sum for 2 years at 10% is ₹420. Find the sum.",
    answer: "CI = P[(1.1)² − 1] = P×0.21 = 420. P = 420/0.21 = ₹2000.",
    steps: [
      { stepNumber: 1, title: "CI formula", explanation: "0.21P=420." },
      { stepNumber: 2, title: "Solve", explanation: "P=2000." },
    ],
    hint: "CI = P×[(1+R/100)ⁿ − 1].",
    keyConcepts: ["finding principal from CI"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A shop adds 12% GST on an article priced ₹2500. Find the final price.",
    answer: "GST = 12% of 2500 = 300. Final = 2500+300 = ₹2800.",
    steps: [{ stepNumber: 1, title: "GST + price", explanation: "0.12×2500=300; 2500+300=2800." }],
    hint: "Final price = original + tax.",
    keyConcepts: ["GST", "tax calculation"],
    conceptsCovered: ["mth:8:ch07:tax-calculation"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A scooter costs ₹40,000. After 2 years it depreciates to ₹32,400. Find the rate of depreciation.",
    answer: "40000(1−R/100)² = 32400. (1−R/100)² = 0.81 = (0.9)². 1−R/100 = 0.9. R = 10%.",
    steps: [
      { stepNumber: 1, title: "Set up", explanation: "(1−R/100)² = 32400/40000 = 0.81." },
      { stepNumber: 2, title: "Solve", explanation: "1−R/100 = 0.9; R=10%." },
    ],
    hint: "Depreciation: value = P(1−R/100)ⁿ.",
    keyConcepts: ["depreciation", "finding rate"],
    conceptsCovered: ["mth:8:ch07:compound-interest-formula"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the difference between CI and SI for ₹8000 at 10% for 3 years.",
    answer: "SI = 8000×10×3/100 = 2400. CI: A=8000×(1.1)³=8000×1.331=10648; CI=2648. Difference=2648−2400=₹248.",
    steps: [
      { stepNumber: 1, title: "SI", explanation: "2400." },
      { stepNumber: 2, title: "CI", explanation: "8000×1.331=10648; CI=2648." },
      { stepNumber: 3, title: "Difference", explanation: "248." },
    ],
    hint: "Calculate both and subtract.",
    keyConcepts: ["CI−SI difference"],
    conceptsCovered: ["mth:8:ch07:ci-vs-si-comparison"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t3", topicName: "Compound Interest",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "CI on ₹4800 at 10% half-yearly for 1 year.",
    answer: "Half-yearly: R=5%, n=2. A=4800×(1.05)²=4800×1.1025=5292. CI=492.",
    steps: [
      { stepNumber: 1, title: "Adjust", explanation: "R=5%, n=2." },
      { stepNumber: 2, title: "A=5292", explanation: "CI=492." },
    ],
    hint: "For half-yearly, halve R and double n.",
    keyConcepts: ["half-yearly CI"],
    conceptsCovered: ["mth:8:ch07:half-yearly-quarterly"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t1", topicName: "Percentage Increase and Decrease",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "If 20% of a number is 50, the number is:",
    answer: "250. 0.20 × x = 50 → x = 250.",
    options: ["A) 200", "B) 225", "C) 250", "D) 275"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Solve", explanation: "x=50/0.20=250." }],
    hint: "Divide 50 by 0.20 (= 20%).",
    keyConcepts: ["finding number from percentage"],
    conceptsCovered: ["mth:8:ch07:percentage-increase"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch07-pyq-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch07", chapterName: "Comparing Quantities",
    topicId: "t2", topicName: "Discount, Tax, and Simple Interest",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "A seller lists price at 40% above CP. After giving a 25% discount, find profit/loss %.",
    answer: "Let CP = 100. MP = 140. SP = 140×0.75 = 105. Profit = 105−100 = 5. Profit% = 5%.",
    steps: [
      { stepNumber: 1, title: "MP = 140", explanation: "40% above CP=100." },
      { stepNumber: 2, title: "SP = 105", explanation: "140×0.75=105." },
      { stepNumber: 3, title: "Profit% = 5%", explanation: "5/100×100=5%." },
    ],
    hint: "Profit% is always on CP.",
    keyConcepts: ["markup and discount combined"],
    conceptsCovered: ["mth:8:ch07:discount"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch07", "PYQ"],
    source: "previous-year",
  },
];
