// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 8, Chapter 8: Algebraic Expressions and Identities
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Multiplying Algebraic Expressions — 20 q
 *   t2 Standard Identities               — 35 q
 *   t3 Applying Identities               — 20 q
 *
 * Concept nodes:
 *   mth:8:ch08:monomial-polynomial-multiplication
 *   mth:8:ch08:identity-a-plus-b-sq
 *   mth:8:ch08:identity-a-minus-b-sq
 *   mth:8:ch08:identity-diff-of-sq
 *   mth:8:ch08:identity-a-plus-b-plus-c-sq
 *   mth:8:ch08:identity-application-arithmetic
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH08_ALGEBRAIC_EXPRESSIONS_AND_IDENTITIES: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Multiplying Algebraic Expressions
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch08-con-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: To multiply a monomial by a polynomial, we use the distributive law.",
    answer: "True. Each term of the polynomial is multiplied by the monomial: a(b + c) = ab + ac.",
    steps: [{ stepNumber: 1, title: "Distributive law", explanation: "a(b+c+d) = ab+ac+ad." }],
    hint: "Think of the monomial multiplying every term.",
    keyConcepts: ["distributive law", "monomial-polynomial multiplication"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "monomial-poly"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Multiply: 3xy × 4x²y.",
    answer: "3xy × 4x²y = 12x³y². Multiply coefficients: 3×4=12. Add exponents: x^(1+2)=x³, y^(1+1)=y².",
    steps: [
      { stepNumber: 1, title: "Coefficients", explanation: "3×4=12." },
      { stepNumber: 2, title: "Variables", explanation: "x¹×x²=x³; y¹×y¹=y²." },
    ],
    hint: "Multiply coefficients and add exponents of the same variable.",
    keyConcepts: ["monomial multiplication"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "monomial-multiply"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Expand: 2x(3x + 5y − 7).",
    answer: "2x × 3x + 2x × 5y + 2x × (−7) = 6x² + 10xy − 14x.",
    steps: [
      { stepNumber: 1, title: "Distribute", explanation: "2x×3x=6x²; 2x×5y=10xy; 2x×(−7)=−14x." },
    ],
    hint: "Multiply 2x by each term in the bracket.",
    keyConcepts: ["distributive multiplication"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "expand"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Multiply: (x + 3)(x + 5).",
    answer: "x² + 5x + 3x + 15 = x² + 8x + 15.",
    steps: [
      { stepNumber: 1, title: "Each term of first × each term of second", explanation: "x×x=x²; x×5=5x; 3×x=3x; 3×5=15." },
      { stepNumber: 2, title: "Combine like terms", explanation: "x²+8x+15." },
    ],
    hint: "Use FOIL: First, Outer, Inner, Last.",
    keyConcepts: ["binomial multiplication", "FOIL"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "binomial-multiply"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: (a + b)² = a² + 2ab + b².",
    answer: "True. This is a standard algebraic identity verified by expanding: (a+b)² = (a+b)(a+b) = a² + ab + ba + b² = a² + 2ab + b².",
    steps: [{ stepNumber: 1, title: "Expand", explanation: "(a+b)(a+b)=a²+2ab+b²." }],
    hint: "Square means multiply by itself.",
    keyConcepts: ["(a+b)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "identity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Expand (x + 7)² using the identity.",
    answer: "(x + 7)² = x² + 2(x)(7) + 7² = x² + 14x + 49.",
    steps: [{ stepNumber: 1, title: "Apply (a+b)²", explanation: "a=x, b=7: x²+2(7)x+49=x²+14x+49." }],
    hint: "(a+b)² = a² + 2ab + b².",
    keyConcepts: ["(a+b)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "expand-identity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Expand (2x − 5)² using the identity.",
    answer: "(2x − 5)² = (2x)² − 2(2x)(5) + 5² = 4x² − 20x + 25.",
    steps: [{ stepNumber: 1, title: "Apply (a−b)²", explanation: "a=2x, b=5: 4x²−20x+25." }],
    hint: "(a−b)² = a² − 2ab + b².",
    keyConcepts: ["(a−b)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "identity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using (a + b)(a − b) = a² − b², find (3x + 4)(3x − 4).",
    answer: "(3x)² − 4² = 9x² − 16.",
    steps: [{ stepNumber: 1, title: "Apply identity", explanation: "a=3x, b=4: 9x²−16." }],
    hint: "(a+b)(a−b) = a² − b² — difference of squares.",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "diff-of-squares"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Expand (x + y + z)² using the identity.",
    answer: "(x+y+z)² = x² + y² + z² + 2xy + 2yz + 2zx.",
    steps: [{ stepNumber: 1, title: "Apply identity", explanation: "Sum of squares + 2× each pair product." }],
    hint: "(a+b+c)² = a²+b²+c²+2ab+2bc+2ca.",
    keyConcepts: ["(a+b+c)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "three-term-identity"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 102² using an algebraic identity.",
    answer: "102² = (100 + 2)² = 100² + 2×100×2 + 2² = 10000 + 400 + 4 = 10404.",
    steps: [
      { stepNumber: 1, title: "Split", explanation: "102 = 100 + 2." },
      { stepNumber: 2, title: "Apply (a+b)²", explanation: "10000+400+4=10404." },
    ],
    hint: "Write 102 as 100 + 2.",
    keyConcepts: ["identity application to arithmetic"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "arithmetic-shortcut"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 9.8² using an algebraic identity.",
    answer: "9.8² = (10 − 0.2)² = 100 − 2×10×0.2 + 0.04 = 100 − 4 + 0.04 = 96.04.",
    steps: [
      { stepNumber: 1, title: "Split", explanation: "9.8 = 10 − 0.2." },
      { stepNumber: 2, title: "Apply (a−b)²", explanation: "100−4+0.04=96.04." },
    ],
    hint: "Write 9.8 as 10 − 0.2.",
    keyConcepts: ["identity for decimals"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "decimal-shortcut"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch08-con-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Product of (2a + 3b) and (3a − 2b) is:",
    answer: "6a² − 4ab + 9ab − 6b² = 6a² + 5ab − 6b².",
    options: ["A) 6a² + 5ab − 6b²", "B) 6a² − 5ab + 6b²", "C) 6a² + 5ab + 6b²", "D) 6a² − 5ab − 6b²"],
    correctOption: "A",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "2a×3a=6a²; 2a×(−2b)=−4ab; 3b×3a=9ab; 3b×(−2b)=−6b²." },
      { stepNumber: 2, title: "Combine", explanation: "6a²+5ab−6b²." },
    ],
    hint: "Multiply each term in the first bracket by each term in the second.",
    keyConcepts: ["binomial multiplication"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "MCQ"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch08-nce-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Multiply: (a² − 9) by (4a).",
    answer: "4a × a² − 4a × 9 = 4a³ − 36a.",
    steps: [{ stepNumber: 1, title: "Distribute", explanation: "4a×a²=4a³; 4a×9=36a." }],
    hint: "Multiply the monomial by each term of the binomial.",
    keyConcepts: ["monomial-polynomial multiplication"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the product: (x + y) × (x − y) × (x² + y²).",
    answer: "(x+y)(x−y) = x²−y². Then (x²−y²)(x²+y²) = x⁴−y⁴.",
    steps: [
      { stepNumber: 1, title: "Step 1", explanation: "(x+y)(x−y)=x²−y²." },
      { stepNumber: 2, title: "Step 2", explanation: "(x²−y²)(x²+y²)=x⁴−y⁴." },
    ],
    hint: "Apply (a+b)(a−b)=a²−b² twice.",
    keyConcepts: ["difference of squares", "repeated application"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using identity, expand (3a − 4b)².",
    answer: "(3a)² − 2(3a)(4b) + (4b)² = 9a² − 24ab + 16b².",
    steps: [{ stepNumber: 1, title: "Apply (a−b)²", explanation: "9a²−24ab+16b²." }],
    hint: "(a−b)² = a²−2ab+b². Here a=3a, b=4b.",
    keyConcepts: ["(a−b)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Expand (1.5x − 0.3y)².",
    answer: "(1.5x)² − 2(1.5x)(0.3y) + (0.3y)² = 2.25x² − 0.9xy + 0.09y².",
    steps: [
      { stepNumber: 1, title: "a²", explanation: "(1.5x)²=2.25x²." },
      { stepNumber: 2, title: "2ab", explanation: "2×1.5×0.3×xy=0.9xy." },
      { stepNumber: 3, title: "b²", explanation: "(0.3y)²=0.09y²." },
    ],
    hint: "Apply (a−b)² with decimal coefficients.",
    keyConcepts: ["(a−b)² with decimals"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If x + y = 12 and xy = 32, find x² + y².",
    answer: "(x+y)² = x² + 2xy + y². 144 = x²+y²+64. x²+y² = 80.",
    steps: [
      { stepNumber: 1, title: "Use (x+y)²", explanation: "x²+y² = (x+y)²−2xy = 144−64 = 80." },
    ],
    hint: "x²+y² = (x+y)² − 2xy.",
    keyConcepts: ["identity application", "sum and product"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Evaluate 97 × 103 using an identity.",
    answer: "97×103 = (100−3)(100+3) = 100²−3² = 10000−9 = 9991.",
    steps: [
      { stepNumber: 1, title: "Rewrite", explanation: "97=100−3, 103=100+3." },
      { stepNumber: 2, title: "Apply (a−b)(a+b)", explanation: "10000−9=9991." },
    ],
    hint: "(100−3)(100+3) is the difference of squares pattern.",
    keyConcepts: ["arithmetic using identity"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Evaluate 9.8 × 10.2 using an identity.",
    answer: "(10−0.2)(10+0.2) = 10²−0.2² = 100−0.04 = 99.96.",
    steps: [{ stepNumber: 1, title: "Apply", explanation: "a=10, b=0.2; 100−0.04=99.96." }],
    hint: "9.8 = 10 − 0.2 and 10.2 = 10 + 0.2.",
    keyConcepts: ["difference of squares", "arithmetic"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Expand (2a + 3b + 4c)² using the identity for (x+y+z)².",
    answer: "(2a)²+(3b)²+(4c)²+2(2a)(3b)+2(3b)(4c)+2(4c)(2a) = 4a²+9b²+16c²+12ab+24bc+16ca.",
    steps: [
      { stepNumber: 1, title: "Squares", explanation: "4a²+9b²+16c²." },
      { stepNumber: 2, title: "Cross terms", explanation: "12ab+24bc+16ca." },
    ],
    hint: "(a+b+c)² = a²+b²+c²+2ab+2bc+2ca.",
    keyConcepts: ["(a+b+c)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If a − b = 4 and ab = 21, find a² + b².",
    answer: "(a−b)² = a²−2ab+b². 16 = a²+b²−42. a²+b² = 58.",
    steps: [{ stepNumber: 1, title: "Use (a−b)²", explanation: "a²+b² = (a−b)²+2ab = 16+42=58." }],
    hint: "a²+b² = (a−b)² + 2ab.",
    keyConcepts: ["identity application", "sum of squares"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Multiply (x² + 3x + 2) by (x + 1) and simplify.",
    answer: "x(x²+3x+2) + 1(x²+3x+2) = x³+3x²+2x+x²+3x+2 = x³+4x²+5x+2.",
    steps: [
      { stepNumber: 1, title: "Distribute x", explanation: "x³+3x²+2x." },
      { stepNumber: 2, title: "Distribute 1", explanation: "x²+3x+2." },
      { stepNumber: 3, title: "Combine", explanation: "x³+4x²+5x+2." },
    ],
    hint: "Multiply every term of the trinomial by (x+1) using distribution.",
    keyConcepts: ["polynomial multiplication"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 502² using an identity.",
    answer: "502² = (500+2)² = 500²+2×500×2+4 = 250000+2000+4 = 252004.",
    steps: [{ stepNumber: 1, title: "Apply (a+b)²", explanation: "500²+2000+4=252004." }],
    hint: "Write 502 = 500 + 2.",
    keyConcepts: ["identity for arithmetic"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Verify: (a + b)(a − b) = a² − b² for a = 5, b = 3.",
    answer: "LHS: (5+3)(5−3) = 8×2 = 16. RHS: 5²−3² = 25−9 = 16. LHS = RHS ✓",
    steps: [
      { stepNumber: 1, title: "LHS", explanation: "8×2=16." },
      { stepNumber: 2, title: "RHS", explanation: "25−9=16." },
    ],
    hint: "Substitute values into both sides and compare.",
    keyConcepts: ["identity verification"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "verify"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If x + 1/x = 5, find x² + 1/x².",
    answer: "(x + 1/x)² = x² + 2 + 1/x². 25 = x² + 1/x² + 2. x² + 1/x² = 23.",
    steps: [
      { stepNumber: 1, title: "Square both sides", explanation: "(x+1/x)²=25." },
      { stepNumber: 2, title: "Expand", explanation: "x²+2+1/x²=25." },
      { stepNumber: 3, title: "Solve", explanation: "x²+1/x²=23." },
    ],
    hint: "Use (a+b)² = a²+2ab+b² where a=x, b=1/x.",
    keyConcepts: ["reciprocal identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "reciprocal-identity"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Evaluate 49 × 51 using an identity.",
    answer: "(50−1)(50+1) = 50²−1² = 2500−1 = 2499.",
    steps: [{ stepNumber: 1, title: "Identity", explanation: "49=50−1, 51=50+1; 2500−1=2499." }],
    hint: "Express as (50−1)(50+1).",
    keyConcepts: ["difference of squares in arithmetic"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "NCERT-Ex8.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If a + b + c = 9 and a² + b² + c² = 35, find ab + bc + ca.",
    answer: "(a+b+c)² = a²+b²+c²+2(ab+bc+ca). 81 = 35+2(ab+bc+ca). 2(ab+bc+ca) = 46. ab+bc+ca = 23.",
    steps: [
      { stepNumber: 1, title: "Use identity", explanation: "(a+b+c)²=a²+b²+c²+2(ab+bc+ca)." },
      { stepNumber: 2, title: "Substitute", explanation: "81=35+2(ab+bc+ca)→ab+bc+ca=23." },
    ],
    hint: "Use the (a+b+c)² identity and substitute known values.",
    keyConcepts: ["(a+b+c)² application"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "identity-application"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simplify: (a + b)(a + b) − (a − b)(a − b).",
    answer: "(a+b)²−(a−b)² = (a²+2ab+b²)−(a²−2ab+b²) = 4ab.",
    steps: [
      { stepNumber: 1, title: "Expand each", explanation: "(a+b)²=a²+2ab+b²; (a−b)²=a²−2ab+b²." },
      { stepNumber: 2, title: "Subtract", explanation: "4ab." },
    ],
    hint: "Use both (a+b)² and (a−b)² identities.",
    keyConcepts: ["combining identities"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "combine-identities"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-017",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Expand and simplify: (3p + 4q)² − (3p − 4q)².",
    answer: "(3p+4q)²=9p²+24pq+16q². (3p−4q)²=9p²−24pq+16q². Difference = 48pq.",
    steps: [
      { stepNumber: 1, title: "Expand first square", explanation: "9p²+24pq+16q²." },
      { stepNumber: 2, title: "Expand second square", explanation: "9p²−24pq+16q²." },
      { stepNumber: 3, title: "Subtract", explanation: "(9p²+24pq+16q²)−(9p²−24pq+16q²)=48pq." },
    ],
    hint: "Expand both, then subtract term by term.",
    keyConcepts: ["combining identities", "simplification"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "simplify"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch08-nce-018",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 83² − 17² using an identity.",
    answer: "(83+17)(83−17) = 100 × 66 = 6600.",
    steps: [{ stepNumber: 1, title: "a²−b²=(a+b)(a−b)", explanation: "100×66=6600." }],
    hint: "Use the difference of squares factorisation.",
    keyConcepts: ["a²−b² in arithmetic"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch08", "arithmetic"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch08-ics-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If x − y = 3 and x + y = 7, find x² − y² and xy.",
    answer: "x²−y² = (x+y)(x−y) = 7×3 = 21. x = (7+3)/2=5, y = (7−3)/2=2. xy=10.",
    steps: [
      { stepNumber: 1, title: "x²−y²", explanation: "(x+y)(x−y)=7×3=21." },
      { stepNumber: 2, title: "x and y", explanation: "x=5, y=2; xy=10." },
    ],
    hint: "x²−y² = (x+y)(x−y); find x and y by solving simultaneously.",
    keyConcepts: ["difference of squares", "simultaneous approach"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch08", "sum-difference"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch08-ics-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If x + 1/x = 6, find x² − 1/x² given x > 1.",
    answer: "(x+1/x)²=36 → x²+1/x²=34. x²−1/x²=(x+1/x)(x−1/x). Need x−1/x: (x−1/x)²=x²+1/x²−2=32; x−1/x=√32=4√2 (since x>1). x²−1/x² = 6×4√2 = 24√2.",
    steps: [
      { stepNumber: 1, title: "x²+1/x²=34", explanation: "(x+1/x)²=36; subtract 2." },
      { stepNumber: 2, title: "x−1/x=4√2", explanation: "(x−1/x)²=34−2=32." },
      { stepNumber: 3, title: "x²−1/x²=24√2", explanation: "(x+1/x)(x−1/x)=6×4√2." },
    ],
    hint: "Use (a+b)(a−b)=a²−b² with a=x, b=1/x.",
    keyConcepts: ["reciprocal identities", "chained application"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: ["Confusing x+1/x with x²+1/x²."],
    tags: ["ICSE", "class8", "ch08", "reciprocal"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch08-ics-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Multiply (2x² − 3x + 1) by (x² + 2x − 3) and collect like terms.",
    answer: "= 2x⁴+4x³−6x²−3x³−6x²+9x+x²+2x−3 = 2x⁴+x³−11x²+11x−3.",
    steps: [
      { stepNumber: 1, title: "Distribute 2x²", explanation: "2x⁴+4x³−6x²." },
      { stepNumber: 2, title: "Distribute −3x", explanation: "−3x³−6x²+9x." },
      { stepNumber: 3, title: "Distribute +1", explanation: "x²+2x−3." },
      { stepNumber: 4, title: "Combine", explanation: "2x⁴+(4−3)x³+(−6−6+1)x²+(9+2)x−3=2x⁴+x³−11x²+11x−3." },
    ],
    hint: "Multiply each term of the first polynomial by each term of the second.",
    keyConcepts: ["polynomial multiplication"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: ["Sign errors when distributing negative terms."],
    tags: ["ICSE", "class8", "ch08", "polynomial-product"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch08-ics-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Evaluate 305 × 295 using an identity.",
    answer: "(300+5)(300−5) = 300²−5² = 90000−25 = 89975.",
    steps: [{ stepNumber: 1, title: "Apply (a+b)(a−b)", explanation: "90000−25=89975." }],
    hint: "305=300+5 and 295=300−5.",
    keyConcepts: ["difference of squares", "arithmetic"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch08", "arithmetic"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch08-ics-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Show that (a+b)² − (a−b)² = 4ab.",
    answer: "(a+b)² = a²+2ab+b². (a−b)² = a²−2ab+b². Difference = (a²+2ab+b²)−(a²−2ab+b²) = 4ab. ✓",
    steps: [
      { stepNumber: 1, title: "Expand both", explanation: "(a+b)²=a²+2ab+b²; (a−b)²=a²−2ab+b²." },
      { stepNumber: 2, title: "Subtract", explanation: "4ab." },
    ],
    hint: "Expand each square and subtract.",
    keyConcepts: ["identity proof", "difference of squares-type"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch08", "proof"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch08-ics-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find (a + b)² if a − b = 5 and ab = 14.",
    answer: "(a+b)² = (a−b)²+4ab = 25+56 = 81. So a+b = ±9.",
    steps: [
      { stepNumber: 1, title: "Identity", explanation: "(a+b)²=(a−b)²+4ab." },
      { stepNumber: 2, title: "Substitute", explanation: "25+56=81; a+b=±9." },
    ],
    hint: "(a+b)² = (a−b)² + 4ab.",
    keyConcepts: ["relating (a+b)² and (a−b)²"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch08", "identity-relation"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch08-ics-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If a + b = 10 and a − b = 4, find a² + b² and 4ab.",
    answer: "(a+b)²=100; (a−b)²=16. a²+b²=((a+b)²+(a−b)²)/2=(100+16)/2=58. 4ab=(a+b)²−(a−b)²=100−16=84.",
    steps: [
      { stepNumber: 1, title: "a²+b²", explanation: "=(100+16)/2=58." },
      { stepNumber: 2, title: "4ab", explanation: "100−16=84." },
    ],
    hint: "Use a²+b² = ((a+b)²+(a−b)²)/2 and 4ab = (a+b)²−(a−b)².",
    keyConcepts: ["sum and product from sum/difference"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch08", "sum-difference-application"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch08-cmp-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A square garden has side (x + 5) m. Write its area as an expanded polynomial.",
    answer: "Area = (x+5)² = x² + 10x + 25 m².",
    steps: [{ stepNumber: 1, title: "Apply (a+b)²", explanation: "x²+10x+25." }],
    hint: "Area of square = side².",
    keyConcepts: ["identity in geometry"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Using identity, 201 × 199 = ?",
    answer: "(200+1)(200−1) = 40000−1 = 39999.",
    options: ["A) 39998", "B) 39999", "C) 40001", "D) 40000"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Apply", explanation: "200²−1²=39999." }],
    hint: "201=200+1 and 199=200−1.",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A rectangular room has dimensions (x + 4) m and (x − 4) m. Find the area.",
    answer: "Area = (x+4)(x−4) = x² − 16 m².",
    steps: [{ stepNumber: 1, title: "Apply (a+b)(a−b)", explanation: "x²−16." }],
    hint: "(a+b)(a−b) = a²−b².",
    keyConcepts: ["difference of squares", "geometry"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A rectangle has length (2x + 1) cm and breadth (x − 3) cm. Find its area.",
    answer: "Area = (2x+1)(x−3) = 2x²−6x+x−3 = 2x²−5x−3 cm².",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "2x×x=2x²; 2x×(−3)=−6x; 1×x=x; 1×(−3)=−3." },
      { stepNumber: 2, title: "Combine", explanation: "2x²−5x−3." },
    ],
    hint: "Area = length × breadth. Expand using FOIL.",
    keyConcepts: ["binomial multiplication", "geometry"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 998² using an identity.",
    answer: "(1000−2)² = 1000²−2×1000×2+4 = 1000000−4000+4 = 996004.",
    steps: [{ stepNumber: 1, title: "Apply (a−b)²", explanation: "1000000−4000+4=996004." }],
    hint: "Write 998 = 1000 − 2.",
    keyConcepts: ["identity for large numbers"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "arithmetic"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A student expands (x + 5)² = x² + 25. Find and correct the error.",
    answer: "Error: the middle term 2×x×5 = 10x is missing. Correct: (x+5)² = x² + 10x + 25.",
    steps: [
      { stepNumber: 1, title: "Identify error", explanation: "2ab = 2×x×5 = 10x was omitted." },
      { stepNumber: 2, title: "Correct", explanation: "x²+10x+25." },
    ],
    hint: "(a+b)² always has THREE terms.",
    keyConcepts: ["common error correction", "identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "error-correction"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The speed of a car is (3x + 2) km/h and it travels for (x + 1) hours. Find the distance.",
    answer: "Distance = speed × time = (3x+2)(x+1) = 3x²+3x+2x+2 = 3x²+5x+2 km.",
    steps: [{ stepNumber: 1, title: "Multiply", explanation: "3x²+5x+2." }],
    hint: "Distance = speed × time.",
    keyConcepts: ["algebraic multiplication", "real-world"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which identity helps compute 48 × 52 most efficiently?",
    answer: "(a+b)(a−b) = a²−b². 48×52=(50−2)(50+2)=2500−4=2496.",
    options: ["A) (a+b)²", "B) (a−b)²", "C) (a+b)(a−b)", "D) (a+b+c)²"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Identify", explanation: "48=50−2, 52=50+2: difference of squares." }],
    hint: "Recognise the symmetric structure around 50.",
    keyConcepts: ["choosing the right identity"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "choose-identity"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Is (a + b)² always greater than a² + b²? Justify with an example where they are equal and where they differ.",
    answer: "No. (a+b)² = a²+2ab+b². (a+b)² > a²+b² iff 2ab > 0 iff ab > 0 (both positive or both negative). If ab = 0, they are equal. If ab < 0, (a+b)² < a²+b². Example equal: a=2, b=0: (2+0)²=4=4+0. Example (a+b)²>a²+b²: a=1,b=1: 4>2. Example (a+b)²<a²+b²: a=3,b=−1: (2)²=4 < 9+1=10.",
    steps: [
      { stepNumber: 1, title: "Formula", explanation: "(a+b)²−(a²+b²)=2ab." },
      { stepNumber: 2, title: "Cases", explanation: "ab>0: greater; ab=0: equal; ab<0: less." },
    ],
    hint: "The difference is 2ab — its sign determines the comparison.",
    keyConcepts: ["comparison", "identity insight"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: ["Assuming (a+b)² is always larger."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "critical-thinking"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the area of a square whose side is (2a + 3b) cm.",
    answer: "Area = (2a+3b)² = 4a²+12ab+9b² cm².",
    steps: [{ stepNumber: 1, title: "Apply (a+b)²", explanation: "(2a)²+2×2a×3b+(3b)²=4a²+12ab+9b²." }],
    hint: "Area = side², then apply the identity.",
    keyConcepts: ["geometry and algebra"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "geometry"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Evaluate: 35² − 25² using an identity.",
    answer: "(35+25)(35−25) = 60×10 = 600.",
    steps: [{ stepNumber: 1, title: "a²−b²=(a+b)(a−b)", explanation: "60×10=600." }],
    hint: "Use the difference of squares identity directly.",
    keyConcepts: ["arithmetic using a²−b²"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "arithmetic"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Expand (x + 2y − 3z)² using the (a+b+c)² identity.",
    answer: "x²+(2y)²+(3z)²+2(x)(2y)+2(2y)(−3z)+2(−3z)(x) = x²+4y²+9z²+4xy−12yz−6xz.",
    steps: [{ stepNumber: 1, title: "Apply identity", explanation: "x²+4y²+9z²+4xy−12yz−6xz." }],
    hint: "Be careful with signs when one term is negative.",
    keyConcepts: ["(a+b+c)² with negative term"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "three-terms"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Using identities, find the value of (a² + b²) when a + b = 6 and a − b = 2.",
    answer: "a = 4, b = 2. But using identity: a²+b² = ((a+b)²+(a−b)²)/2 = (36+4)/2 = 20.",
    steps: [{ stepNumber: 1, title: "Formula", explanation: "a²+b²=((a+b)²+(a−b)²)/2=(36+4)/2=20." }],
    hint: "a²+b² = ((a+b)²+(a−b)²)/2.",
    keyConcepts: ["deriving sum of squares"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "sum-of-squares"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which is the correct expansion of (x − 3)(x + 3)?",
    answer: "x² − 9.",
    options: ["A) x² + 9", "B) x² − 9", "C) x² − 6x + 9", "D) x² + 6x − 9"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Apply (a+b)(a−b)", explanation: "x²−3²=x²−9." }],
    hint: "(a+b)(a−b) = a²−b².",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Can you use the identity (a + b)² to expand (x² + 3x + 2)²? Show the first step.",
    answer: "Yes. Write x²+3x+2 as a sum: let a = x²+3x and b = 2 (or other groupings). (x²+3x+2)² = ((x²+3x)+2)² = (x²+3x)²+2(x²+3x)(2)+4 = (x⁴+6x³+9x²)+4x²+12x+4 = x⁴+6x³+13x²+12x+4.",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "Let a=x²+3x, b=2." },
      { stepNumber: 2, title: "Apply (a+b)²", explanation: "a²+2ab+b² = (x²+3x)²+4(x²+3x)+4." },
      { stepNumber: 3, title: "Expand (x²+3x)²", explanation: "x⁴+6x³+9x²." },
      { stepNumber: 4, title: "Final", explanation: "x⁴+6x³+13x²+12x+4." },
    ],
    hint: "Group part of the expression as one term 'a'.",
    keyConcepts: ["strategic grouping", "identity extension"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: ["Trying to expand without grouping, leading to sign errors."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "extend-identity"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch08-cmp-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 4.9² using an identity.",
    answer: "(5−0.1)² = 25−2×5×0.1+0.01 = 25−1+0.01 = 24.01.",
    steps: [{ stepNumber: 1, title: "Apply (a−b)²", explanation: "25−1+0.01=24.01." }],
    hint: "4.9 = 5 − 0.1.",
    keyConcepts: ["decimal squaring using identity"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch08", "decimal"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch08-hot-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove that a³ + b³ = (a + b)(a² − ab + b²) by expanding the RHS.",
    answer: "RHS = a×a²−a×ab+a×b²+b×a²−b×ab+b×b² = a³−a²b+ab²+a²b−ab²+b³ = a³+b³. ✓",
    steps: [
      { stepNumber: 1, title: "Expand (a+b)(a²−ab+b²)", explanation: "Distribute a: a³−a²b+ab²; distribute b: a²b−ab²+b³." },
      { stepNumber: 2, title: "Add", explanation: "a³+(−a²b+a²b)+(ab²−ab²)+b³=a³+b³." },
    ],
    hint: "Multiply each term of (a+b) by each term of (a²−ab+b²) and simplify.",
    keyConcepts: ["sum of cubes proof"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: ["Sign error on −a²b term."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If x + y + z = 0, prove that x² + y² + z² = −2(xy + yz + zx).",
    answer: "(x+y+z)² = x²+y²+z²+2(xy+yz+zx). Since x+y+z=0: 0=x²+y²+z²+2(xy+yz+zx). Therefore x²+y²+z² = −2(xy+yz+zx). ✓",
    steps: [
      { stepNumber: 1, title: "Use (a+b+c)²", explanation: "(x+y+z)²=x²+y²+z²+2(xy+yz+zx)." },
      { stepNumber: 2, title: "Substitute x+y+z=0", explanation: "0=x²+y²+z²+2(xy+yz+zx)." },
      { stepNumber: 3, title: "Rearrange", explanation: "x²+y²+z²=−2(xy+yz+zx)." },
    ],
    hint: "Square both sides of x+y+z=0.",
    keyConcepts: ["identity proof", "condition application"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "proof-from-condition"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If a + b = p and ab = q, express a³ + b³ in terms of p and q.",
    answer: "a³+b³=(a+b)(a²−ab+b²)=(a+b)((a+b)²−3ab)=p(p²−3q)=p³−3pq.",
    steps: [
      { stepNumber: 1, title: "Sum of cubes", explanation: "a³+b³=(a+b)(a²−ab+b²)." },
      { stepNumber: 2, title: "Express a²+b²", explanation: "a²+b²=(a+b)²−2ab=p²−2q." },
      { stepNumber: 3, title: "Substitute", explanation: "a²−ab+b²=(p²−2q)−q=p²−3q." },
      { stepNumber: 4, title: "Final", explanation: "p(p²−3q)=p³−3pq." },
    ],
    hint: "Use a²+b² = (a+b)²−2ab to substitute.",
    keyConcepts: ["sum of cubes", "substitution"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: ["Forgetting to subtract 3ab (not 2ab) in the sum of cubes factor."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "substitution"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Find the value of (a + b + c)² − (b + c − a)² − (a + c − b)² − (a + b − c)².",
    answer: "Let A=a+b+c, B=b+c−a, C=a+c−b, D=a+b−c. A²−B²−C²−D². A²=(a+b+c)²=a²+b²+c²+2ab+2bc+2ca. B²=(b+c−a)²=a²+b²+c²−2ab+2bc−2ca. C²=(a+c−b)²=a²+b²+c²+2ac−2ab−2bc. D²=(a+b−c)²=a²+b²+c²+2ab−2bc−2ca. A²−B²=(2ab+2bc+2ca)−(−2ab+2bc−2ca)=4ab+4ca. A²−B²−C²=(4ab+4ca)−(2ac−2ab−2bc)=6ab+2ac+2bc. A²−B²−C²−D²=(6ab+2ac+2bc)−(2ab−2bc−2ca)=4ab+4ac+4bc=4(ab+bc+ca).",
    steps: [
      { stepNumber: 1, title: "Expand all four squares", explanation: "Each is (±a±b±c)²." },
      { stepNumber: 2, title: "Subtract step by step", explanation: "After subtraction: 4(ab+bc+ca)." },
    ],
    hint: "Expand each square carefully and track signs.",
    keyConcepts: ["expanding multiple squares", "algebraic simplification"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: ["Sign errors when expanding negative sums."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "complex-simplification"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Create a three-digit multiplication problem solvable by identity and solve it.",
    answer: "Example: 106 × 94 = (100+6)(100−6) = 10000−36 = 9964. Identity used: (a+b)(a−b) = a²−b². Creative context: a market sells 106 items on Monday and 94 on Tuesday. Total revenue if each costs ₹1 = 106×94 = 9964.",
    steps: [
      { stepNumber: 1, title: "Choose numbers", explanation: "106=100+6, 94=100−6: symmetric around 100." },
      { stepNumber: 2, title: "Apply", explanation: "100²−6²=9964." },
    ],
    hint: "Look for pairs that are equidistant from a round number.",
    keyConcepts: ["identity creation", "multiplication shortcut"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "create"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "For real numbers a and b, when does (a−b)² = (b−a)²? Explain and give an algebraic justification.",
    answer: "Always! (a−b)² = (b−a)² for all real a, b. Proof: b−a = −(a−b). So (b−a)² = (−1)²(a−b)² = (a−b)². They are always equal because squaring removes the sign.",
    steps: [
      { stepNumber: 1, title: "Note", explanation: "b−a = −(a−b)." },
      { stepNumber: 2, title: "Square", explanation: "(b−a)² = (−(a−b))² = (a−b)²." },
    ],
    hint: "Think about what happens when you square a negative number.",
    keyConcepts: ["symmetry of squares", "algebraic insight"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: ["Thinking (a−b)² ≠ (b−a)² because the expressions look different."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "symmetry"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "If x − y = 1, prove that x³ − y³ − 3xy = 1.",
    answer: "x³−y³=(x−y)(x²+xy+y²)=1×(x²+xy+y²). Need to show x²+xy+y²−3xy=1. x²+xy+y²−3xy = x²−2xy+y² = (x−y)²=1. So x³−y³=x²+xy+y²=3xy+1 → x³−y³−3xy=1. ✓",
    steps: [
      { stepNumber: 1, title: "Factorise x³−y³", explanation: "=(x−y)(x²+xy+y²)=(x²+xy+y²)." },
      { stepNumber: 2, title: "Rearrange", explanation: "x³−y³−3xy = (x²+xy+y²)−3xy = x²−2xy+y² = (x−y)²=1." },
    ],
    hint: "Use x³−y³ = (x−y)(x²+xy+y²) and the given x−y=1.",
    keyConcepts: ["difference of cubes", "proof from condition"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: ["Not simplifying x²+xy+y²−3xy = (x−y)²."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Evaluate 1² − 2² + 3² − 4² + 5² − 6² + ... + 99² − 100².",
    answer: "Group in pairs: (1²−2²)+(3²−4²)+...+(99²−100²). Each pair: n²−(n+1)²=(n−(n+1))(n+(n+1))=−(2n+1). For pairs starting at 1,3,5,...,99: n=1,3,...,99 (50 pairs). Each gives −(2n+1): −3,−7,−11,...,−199. Sum = −3−7−...−199 = −50×(3+199)/2 = −50×101 = −5050.",
    steps: [
      { stepNumber: 1, title: "Group pairs", explanation: "50 pairs: (1²−2²),(3²−4²),...,(99²−100²)." },
      { stepNumber: 2, title: "Each pair = −(2n+1)", explanation: "Sequence: −3,−7,...,−199." },
      { stepNumber: 3, title: "Sum of AP", explanation: "50×(−3+(−199))/2=50×(−101)=−5050." },
    ],
    hint: "Group consecutive pairs and use the difference of squares identity.",
    keyConcepts: ["difference of squares", "series summation"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: ["Not recognising that each pair uses a²−b²=(a+b)(a−b)."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "series"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Show that the expression a² + b² + c² − ab − bc − ca ≥ 0 for all real a, b, c.",
    answer: "a²+b²+c²−ab−bc−ca = ½[(a²−2ab+b²)+(b²−2bc+c²)+(c²−2ca+a²)] = ½[(a−b)²+(b−c)²+(c−a)²] ≥ 0 since each square ≥ 0.",
    steps: [
      { stepNumber: 1, title: "Multiply by 2", explanation: "2(a²+b²+c²−ab−bc−ca)=(a−b)²+(b−c)²+(c−a)²." },
      { stepNumber: 2, title: "Each square ≥ 0", explanation: "Sum of squares ≥ 0 ⟹ original ≥ 0." },
    ],
    hint: "Multiply by 2 and recognise it as a sum of squares.",
    keyConcepts: ["non-negativity proof", "sum of squares"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: ["Not seeing the factor of ½."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "non-negative"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch08-hot-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Using algebraic identities only (no direct multiplication), evaluate: (a) 999² (b) 1001 × 999 (c) 1001² − 999².",
    answer: "(a) (1000−1)²=1000000−2000+1=998001. (b) (1000+1)(1000−1)=1000²−1=999999. (c) 1001²−999²=(1001+999)(1001−999)=2000×2=4000.",
    steps: [
      { stepNumber: 1, title: "(a)", explanation: "999=(1000−1); (1000−1)²=998001." },
      { stepNumber: 2, title: "(b)", explanation: "(1000+1)(1000−1)=999999." },
      { stepNumber: 3, title: "(c)", explanation: "(1001+999)(1001−999)=2000×2=4000." },
    ],
    hint: "Choose 1000 as the anchor value for all three parts.",
    keyConcepts: ["multiple identity applications"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch08", "multi-part"],
    source: "hots",
  },

  // ── PREVIOUS-YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch08-pyq-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "(a − b)² equals:",
    answer: "a² − 2ab + b².",
    options: ["A) a² + 2ab + b²", "B) a² − 2ab + b²", "C) a² − b²", "D) a² + b²"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Identity", explanation: "(a−b)²=a²−2ab+b²." }],
    hint: "The sign of the middle term depends on the sign inside the bracket.",
    keyConcepts: ["(a−b)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-minus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 1002² using an identity.",
    answer: "(1000+2)² = 1000000+4000+4 = 1004004.",
    steps: [{ stepNumber: 1, title: "Apply (a+b)²", explanation: "1000²+2×1000×2+4=1004004." }],
    hint: "1002 = 1000 + 2.",
    keyConcepts: ["arithmetic using identity"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Expand (2x + 3y)².",
    answer: "4x² + 12xy + 9y².",
    steps: [{ stepNumber: 1, title: "Apply (a+b)²", explanation: "(2x)²+2×2x×3y+(3y)²=4x²+12xy+9y²." }],
    hint: "(a+b)² = a²+2ab+b².",
    keyConcepts: ["(a+b)² with coefficients"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find (5a + 4b)(5a − 4b).",
    answer: "(5a)² − (4b)² = 25a² − 16b².",
    steps: [{ stepNumber: 1, title: "Apply (a+b)(a−b)", explanation: "25a²−16b²." }],
    hint: "(a+b)(a−b) = a²−b².",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If x² + y² = 41 and xy = 20, find (x+y) and (x−y).",
    answer: "(x+y)² = x²+2xy+y² = 41+40 = 81. x+y = ±9. (x−y)² = x²−2xy+y² = 41−40 = 1. x−y = ±1.",
    steps: [
      { stepNumber: 1, title: "(x+y)²", explanation: "41+2(20)=81; x+y=±9." },
      { stepNumber: 2, title: "(x−y)²", explanation: "41−2(20)=1; x−y=±1." },
    ],
    hint: "(x+y)²=x²+2xy+y²; (x−y)²=x²−2xy+y².",
    keyConcepts: ["identity reverse application"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Multiply: 5xy(2x + 3y).",
    answer: "10x²y + 15xy².",
    steps: [{ stepNumber: 1, title: "Distribute", explanation: "5xy×2x=10x²y; 5xy×3y=15xy²." }],
    hint: "Multiply monomial by each term of the binomial.",
    keyConcepts: ["monomial × binomial"],
    conceptsCovered: ["mth:8:ch08:monomial-polynomial-multiplication"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Expand (a + 2b + 3c)² using the identity.",
    answer: "a²+4b²+9c²+4ab+12bc+6ca.",
    steps: [{ stepNumber: 1, title: "Apply (p+q+r)²", explanation: "a²+(2b)²+(3c)²+2a(2b)+2(2b)(3c)+2(3c)a=a²+4b²+9c²+4ab+12bc+6ca." }],
    hint: "(a+b+c)² = a²+b²+c²+2ab+2bc+2ca.",
    keyConcepts: ["(a+b+c)² identity"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t3", topicName: "Applying Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find 104 × 96 using an identity.",
    answer: "(100+4)(100−4) = 10000−16 = 9984.",
    steps: [{ stepNumber: 1, title: "Apply", explanation: "(100+4)(100−4)=9984." }],
    hint: "104=100+4, 96=100−4.",
    keyConcepts: ["arithmetic with identity"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "If m − n = 5 and m + n = 15, find m² − n².",
    answer: "m²−n² = (m+n)(m−n) = 15×5 = 75.",
    steps: [{ stepNumber: 1, title: "Apply identity", explanation: "(m+n)(m−n)=15×5=75." }],
    hint: "m²−n² = (m+n)(m−n) directly.",
    keyConcepts: ["difference of squares application"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t1", topicName: "Multiplying Algebraic Expressions",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Find the product of (x + y + z) and (x + y − z).",
    answer: "((x+y)+z)((x+y)−z) = (x+y)²−z² = x²+2xy+y²−z².",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "Let a=x+y, b=z: (a+b)(a−b)=a²−b²." },
      { stepNumber: 2, title: "Expand a²", explanation: "(x+y)²=x²+2xy+y²." },
      { stepNumber: 3, title: "Final", explanation: "x²+2xy+y²−z²." },
    ],
    hint: "Treat (x+y) as a single term 'a'.",
    keyConcepts: ["grouping", "difference of squares"],
    conceptsCovered: ["mth:8:ch08:identity-diff-of-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Value of (101)² − (99)² is:",
    answer: "400. (101+99)(101−99) = 200×2 = 400.",
    options: ["A) 200", "B) 300", "C) 400", "D) 500"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "a²−b²=(a+b)(a−b)", explanation: "200×2=400." }],
    hint: "(a+b)(a−b) = a²−b².",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch08:identity-application-arithmetic"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch08-pyq-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch08", chapterName: "Algebraic Expressions and Identities",
    topicId: "t2", topicName: "Standard Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If a + b + c = 0, find a² + b² + c².",
    answer: "(a+b+c)² = 0² = 0. So a²+b²+c²+2(ab+bc+ca)=0 → a²+b²+c²=−2(ab+bc+ca). Without knowing ab+bc+ca, we can't simplify further unless additional information is given.",
    steps: [
      { stepNumber: 1, title: "Square both sides", explanation: "(a+b+c)²=a²+b²+c²+2(ab+bc+ca)=0." },
      { stepNumber: 2, title: "Result", explanation: "a²+b²+c²=−2(ab+bc+ca)." },
    ],
    hint: "Use the (a+b+c)² identity.",
    keyConcepts: ["(a+b+c)² with condition"],
    conceptsCovered: ["mth:8:ch08:identity-a-plus-b-plus-c-sq"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch08", "PYQ"],
    source: "previous-year",
  },
];
