/**
 * Question Bank — Mathematics, Class 8, Chapter 13: Factorisation
 *
 * 75 curated questions — types: concept (12), ncert (18), icse (7), competency (16), hots (10), previous-year (12)
 * Board: Both (CBSE + ICSE) | Category: major | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Factorisation by Common Factor     — 18 q
 *   t2 Factorisation by Grouping          — 17 q
 *   t3 Factorisation Using Identities     — 25 q
 *   t4 Division of Polynomials            — 15 q
 *
 * Concept nodes:
 *   mth:8:ch13:common-factor-method
 *   mth:8:ch13:grouping-method
 *   mth:8:ch13:factorisation-by-identity
 *   mth:8:ch13:polynomial-division
 *   mth:8:ch13:error-finding-in-division
 *
 * v1 2026-07-06 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";
import { STANDARD_TAGS } from "../../../tagging";

export const CH13_FACTORISATION: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Factorisation by Common Factor
  // ═══════════════════════════════════════════════════════════════════════════

  // ── CONCEPT ─────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch13-con-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "concept", questionFormat: "TrueOrFalse",
    difficulty: "easy", bloomsLevel: "remember",
    marks: 1, estimatedTimeMinutes: 2,
    question: "True or False: Factorisation is the reverse process of expansion.",
    answer: "True. Expansion multiplies out brackets; factorisation writes an expression as a product of its factors. For example: x²+2x = x(x+2) reverses the expansion x(x+2)=x²+2x.",
    steps: [{ stepNumber: 1, title: "Relationship", explanation: "Expand: a(b+c)=ab+ac. Factorise: ab+ac=a(b+c)." }],
    hint: "Think of factorisation as 'undoing' expansion.",
    keyConcepts: ["factorisation definition", "reverse of expansion"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "definition"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 12a²b + 18ab².",
    answer: "HCF of 12a²b and 18ab² is 6ab. 12a²b+18ab² = 6ab(2a+3b).",
    steps: [
      { stepNumber: 1, title: "Find HCF", explanation: "HCF(12,18)=6; HCF(a²,a)=a; HCF(b,b²)=b. HCF=6ab." },
      { stepNumber: 2, title: "Factor out", explanation: "6ab(2a+3b)." },
    ],
    hint: "Find the HCF of all terms and factor it out.",
    keyConcepts: ["HCF", "common factor"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "common-factor"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 7x² − 14x.",
    answer: "7x(x − 2).",
    steps: [{ stepNumber: 1, title: "HCF = 7x", explanation: "7x²=7x×x; 14x=7x×2. So 7x(x−2)." }],
    hint: "Take out the HCF of 7x from both terms.",
    keyConcepts: ["common monomial factor"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "monomial-factor"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Factorise by grouping: ax + ay + bx + by.",
    answer: "Group: (ax+ay)+(bx+by) = a(x+y)+b(x+y) = (x+y)(a+b).",
    steps: [
      { stepNumber: 1, title: "Group pairs", explanation: "(ax+ay)+(bx+by)." },
      { stepNumber: 2, title: "Factor each group", explanation: "a(x+y)+b(x+y)." },
      { stepNumber: 3, title: "Factor common bracket", explanation: "(x+y)(a+b)." },
    ],
    hint: "Group terms so each group has a common factor.",
    keyConcepts: ["grouping method"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "grouping"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: x² + 10x + 25.",
    answer: "(x + 5)². Using (a+b)² = a²+2ab+b²: a=x, b=5 since 2×5=10 and 5²=25.",
    steps: [{ stepNumber: 1, title: "Recognise pattern", explanation: "x²+10x+25=(x+5)²." }],
    hint: "Check if it matches a²+2ab+b² form.",
    keyConcepts: ["perfect square trinomial"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "perfect-square"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 4x² − 9.",
    answer: "(2x)² − 3² = (2x+3)(2x−3).",
    steps: [{ stepNumber: 1, title: "Difference of squares", explanation: "(2x+3)(2x−3)." }],
    hint: "Use a²−b² = (a+b)(a−b) with a=2x, b=3.",
    keyConcepts: ["difference of squares factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "diff-of-squares"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Divide: (x² + 7x + 12) ÷ (x + 3).",
    answer: "Factorise numerator: (x+3)(x+4). Divide: (x+3)(x+4)/(x+3) = x+4.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "x²+7x+12=(x+3)(x+4)." },
      { stepNumber: 2, title: "Cancel", explanation: "(x+3) cancels; answer = x+4." },
    ],
    hint: "Factorise the numerator and cancel common factors.",
    keyConcepts: ["polynomial division", "factorisation"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "division"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 6x²y − 8xy² + 4xy.",
    answer: "HCF = 2xy. 2xy(3x − 4y + 2).",
    steps: [
      { stepNumber: 1, title: "HCF = 2xy", explanation: "HCF(6,8,4)=2; common variables=xy." },
      { stepNumber: 2, title: "Factor out", explanation: "2xy(3x−4y+2)." },
    ],
    hint: "Find HCF of all three terms.",
    keyConcepts: ["three-term common factor"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "three-term"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 9y² − 6y + 1.",
    answer: "(3y − 1)². Matches (a−b)²=a²−2ab+b²: a=3y, b=1.",
    steps: [{ stepNumber: 1, title: "Recognise (a−b)²", explanation: "(3y−1)²." }],
    hint: "Check: (3y)²=9y², 2×3y×1=6y, 1²=1 ✓.",
    keyConcepts: ["perfect square trinomial", "factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "perfect-square"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Factorise: p² − pq + 2p − 2q.",
    answer: "Group: (p²−pq)+(2p−2q) = p(p−q)+2(p−q) = (p−q)(p+2).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "(p²−pq)+(2p−2q)." },
      { stepNumber: 2, title: "Factor each", explanation: "p(p−q)+2(p−q)." },
      { stepNumber: 3, title: "Common factor", explanation: "(p−q)(p+2)." },
    ],
    hint: "Look for a common binomial factor after grouping.",
    keyConcepts: ["grouping method"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "grouping"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "concept", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Divide: (4x² − 12x) ÷ (2x).",
    answer: "4x²/2x − 12x/2x = 2x − 6.",
    steps: [{ stepNumber: 1, title: "Divide each term", explanation: "4x²÷2x=2x; 12x÷2x=6. Answer: 2x−6." }],
    hint: "Divide each term of the polynomial by the monomial.",
    keyConcepts: ["polynomial ÷ monomial"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "poly-by-monomial"],
    source: "concept",
  },

  {
    id: "bo-mth-8-ch13-con-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "concept", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Factorise: x² − 16.",
    answer: "(x + 4)(x − 4). Difference of squares: x² − 4² = (x+4)(x−4).",
    options: ["A) (x−4)²", "B) (x+4)²", "C) (x+4)(x−4)", "D) (x+2)(x−8)"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "a²−b²=(a+b)(a−b)", explanation: "x²−16=(x+4)(x−4)." }],
    hint: "16 = 4². Use difference of squares.",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "MCQ"],
    source: "concept",
  },

  // ── NCERT ────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch13-nce-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 2a³b + 4a²b² + 6ab.",
    answer: "HCF = 2ab. 2ab(a²+2ab+3).",
    steps: [{ stepNumber: 1, title: "HCF and factor", explanation: "2ab×a²=2a³b; 2ab×2ab=4a²b²; 2ab×3=6ab. → 2ab(a²+2ab+3)." }],
    hint: "HCF of 2,4,6 is 2; common variable part is ab.",
    keyConcepts: ["HCF factorisation"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Factorise: x³ − x² + x − 1.",
    answer: "(x³−x²)+(x−1) = x²(x−1)+1(x−1) = (x−1)(x²+1).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "(x³−x²)+(x−1)." },
      { stepNumber: 2, title: "Factor each", explanation: "x²(x−1)+1(x−1)." },
      { stepNumber: 3, title: "Common", explanation: "(x−1)(x²+1)." },
    ],
    hint: "Group first two terms and last two terms.",
    keyConcepts: ["grouping with cubic"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise: 4p² + 20pq + 25q².",
    answer: "(2p)²+2×2p×5q+(5q)² = (2p+5q)².",
    steps: [{ stepNumber: 1, title: "Recognise (a+b)²", explanation: "a=2p, b=5q; (2p+5q)²." }],
    hint: "Check if middle term = 2×√(first term)×√(last term).",
    keyConcepts: ["perfect square trinomial"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 49x² − 64.",
    answer: "(7x)²−8² = (7x+8)(7x−8).",
    steps: [{ stepNumber: 1, title: "Difference of squares", explanation: "7x+8)(7x−8)." }],
    hint: "49=7² and 64=8².",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Divide: (x² + 5x + 6) ÷ (x + 2).",
    answer: "x²+5x+6 = (x+2)(x+3). Divide: (x+2)(x+3)/(x+2) = x+3.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "x²+5x+6 = (x+2)(x+3)." },
      { stepNumber: 2, title: "Cancel", explanation: "x+3." },
    ],
    hint: "Find two numbers that multiply to 6 and add to 5: 2 and 3.",
    keyConcepts: ["polynomial division", "quadratic factorisation"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Find the error in the division: (x² + 5x + 6) ÷ (x + 2) = x + 6. Correct it.",
    answer: "Error: the student wrote x + 6 but the correct answer is x + 3. Checking: (x+2)(x+6) = x²+8x+12 ≠ x²+5x+6. Correct factorisation: x²+5x+6=(x+2)(x+3); quotient = x+3.",
    steps: [
      { stepNumber: 1, title: "Verify student answer", explanation: "(x+2)(x+6)=x²+8x+12≠x²+5x+6." },
      { stepNumber: 2, title: "Correct factorisation", explanation: "(x+2)(x+3)=x²+5x+6. Answer=x+3." },
    ],
    hint: "Multiply (divisor × student's answer) and compare with dividend.",
    keyConcepts: ["error detection in division"],
    conceptsCovered: ["mth:8:ch13:error-finding-in-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 5x² + 15xy.",
    answer: "5x(x + 3y).",
    steps: [{ stepNumber: 1, title: "HCF = 5x", explanation: "5x(x+3y)." }],
    hint: "Common factor of 5x² and 15xy is 5x.",
    keyConcepts: ["common factor"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Factorise: ab − a − b + 1.",
    answer: "Group: (ab−a)+(−b+1) = a(b−1)−1(b−1) = (b−1)(a−1).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "(ab−a)+(1−b)." },
      { stepNumber: 2, title: "Factor", explanation: "a(b−1)−(b−1)=(b−1)(a−1)." },
    ],
    hint: "Factor out 'a' from first pair; factor out −1 from second pair.",
    keyConcepts: ["grouping with negative"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: ["Incorrect sign when factoring −1 from (1−b)."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.1"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: x² − 8x + 16.",
    answer: "(x − 4)². Pattern: a²−2ab+b² with a=x, b=4.",
    steps: [{ stepNumber: 1, title: "Recognise", explanation: "x²−2×x×4+4²=(x−4)²." }],
    hint: "Middle term = 2×x×4 = 8x ✓.",
    keyConcepts: ["(a−b)² factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Divide (y³ + y² + y + 1) by (y² + y + 1).",
    answer: "y³+y²+y+1 = y(y²+y+1)+1(y²+y+1)... wait, check: y(y²+y+1)=y³+y²+y. y³+y²+y+1=y(y²+y+1)+1. But 1/(y²+y+1) is not a polynomial. Let me re-check: y³+y²+y+1 ÷ (y²+y+1). Long division: y³+y²+y+1 = y(y²+y+1)+0×y+0+1... Hmm: y×(y²+y+1)=y³+y²+y. Remainder: (y³+y²+y+1)−(y³+y²+y)=1. So quotient=y, remainder=1. Check: NCERT Ex 13.3 — let me try differently: (y+1)(y²+1)=y³+y²+y+1. So (y³+y²+y+1)÷(y²+y+1): divide using long division. Actually y+1 with remainder? Let me do: y³÷y²=y. y×(y²+y+1)=y³+y²+y. Subtract: (y³+y²+y+1)−(y³+y²+y)=1. Quotient=y, remainder=1. So quotient is y with remainder 1.",
    steps: [
      { stepNumber: 1, title: "Long divide", explanation: "y³÷y²=y; y(y²+y+1)=y³+y²+y." },
      { stepNumber: 2, title: "Subtract", explanation: "y³+y²+y+1−(y³+y²+y)=1." },
      { stepNumber: 3, title: "Result", explanation: "Quotient=y, Remainder=1." },
    ],
    hint: "Divide the leading term and continue.",
    keyConcepts: ["polynomial long division"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 25a² − 40ab + 16b².",
    answer: "(5a)²−2×5a×4b+(4b)² = (5a−4b)².",
    steps: [{ stepNumber: 1, title: "Apply (a−b)²", explanation: "(5a−4b)²." }],
    hint: "Check: 2×5a×4b=40ab ✓.",
    keyConcepts: ["perfect square trinomial"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Find the error: (3x² + 4x) ÷ x = 3x + 4x = 7x. Correct it.",
    answer: "Error: 4x ÷ x = 4, NOT 4x. Also 3x² ÷ x = 3x, not 3x². Correct: (3x²+4x) ÷ x = 3x + 4.",
    steps: [
      { stepNumber: 1, title: "Identify error", explanation: "Student wrote 4x but should be 4 (dividing 4x by x gives 4)." },
      { stepNumber: 2, title: "Correct", explanation: "3x²÷x=3x; 4x÷x=4. Answer: 3x+4." },
    ],
    hint: "Each term must be divided by x.",
    keyConcepts: ["error in division", "monomial division"],
    conceptsCovered: ["mth:8:ch13:error-finding-in-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.4"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 4,
    question: "Factorise: m² + 2mn + n² − p².",
    answer: "= (m+n)² − p² = (m+n+p)(m+n−p).",
    steps: [
      { stepNumber: 1, title: "Group first three", explanation: "(m+n)²=m²+2mn+n²." },
      { stepNumber: 2, title: "Difference of squares", explanation: "(m+n)²−p²=(m+n+p)(m+n−p)." },
    ],
    hint: "Recognise m²+2mn+n² as (m+n)², then apply a²−b².",
    keyConcepts: ["grouping + identity"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.2"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: a(a+1) − b(b+1).",
    answer: "= a²+a−b²−b = (a²−b²)+(a−b) = (a−b)(a+b)+(a−b) = (a−b)(a+b+1).",
    steps: [
      { stepNumber: 1, title: "Expand", explanation: "a²+a−b²−b." },
      { stepNumber: 2, title: "Group", explanation: "(a²−b²)+(a−b)=(a−b)(a+b)+(a−b)." },
      { stepNumber: 3, title: "Factor (a−b)", explanation: "(a−b)(a+b+1)." },
    ],
    hint: "Expand, then group and factorise.",
    keyConcepts: ["expand then factorise"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "expand-factorise"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise: 9 − x²/4.",
    answer: "3² − (x/2)² = (3 + x/2)(3 − x/2) = (6+x)(6−x)/4.",
    steps: [
      { stepNumber: 1, title: "Rewrite", explanation: "9=3²; x²/4=(x/2)²." },
      { stepNumber: 2, title: "Difference of squares", explanation: "(3+x/2)(3−x/2)." },
    ],
    hint: "Express both terms as perfect squares.",
    keyConcepts: ["difference of squares with fraction"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "fraction-factorisation"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "ncert", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 6,
    question: "Divide (5x² − 30x + 45) by (x − 3).",
    answer: "5x²−30x+45 = 5(x²−6x+9) = 5(x−3)². Divide by (x−3): 5(x−3)² ÷ (x−3) = 5(x−3) = 5x−15.",
    steps: [
      { stepNumber: 1, title: "Factor out 5", explanation: "5(x²−6x+9)." },
      { stepNumber: 2, title: "Perfect square", explanation: "5(x−3)²." },
      { stepNumber: 3, title: "Divide", explanation: "5(x−3)=5x−15." },
    ],
    hint: "First factor out any common number, then recognise the perfect square.",
    keyConcepts: ["division with factorisation"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.3"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-017",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 16x⁴ − y⁴.",
    answer: "((4x²)²−(y²)²) = (4x²+y²)(4x²−y²) = (4x²+y²)(2x+y)(2x−y).",
    steps: [
      { stepNumber: 1, title: "First factor", explanation: "(4x²+y²)(4x²−y²)." },
      { stepNumber: 2, title: "Second factor further", explanation: "(4x²−y²)=(2x+y)(2x−y)." },
    ],
    hint: "Apply difference of squares twice — the result factors further.",
    keyConcepts: ["repeated difference of squares"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Stopping after first application of identity."],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "repeated-factorisation"],
    source: "ncert",
  },

  {
    id: "bo-mth-8-ch13-nce-018",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "ncert", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Find the error: (2y+6)/2 = y+6. Correct it.",
    answer: "Error: only the first term (2y) was divided by 2; the constant 6 was not divided. Correct: (2y+6)/2 = y+3.",
    steps: [
      { stepNumber: 1, title: "Both terms must be divided", explanation: "2y÷2=y; 6÷2=3. Answer: y+3." },
    ],
    hint: "Every term in the numerator must be divided by the denominator.",
    keyConcepts: ["division error correction"],
    conceptsCovered: ["mth:8:ch13:error-finding-in-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.NCERT_BASED, "class8", "ch13", "NCERT-Ex13.4"],
    source: "ncert",
  },

  // ── ICSE ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch13-ics-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise completely: 12x² − 27y².",
    answer: "3(4x²−9y²) = 3((2x)²−(3y)²) = 3(2x+3y)(2x−3y).",
    steps: [
      { stepNumber: 1, title: "Common factor", explanation: "3(4x²−9y²)." },
      { stepNumber: 2, title: "Difference of squares", explanation: "3(2x+3y)(2x−3y)." },
    ],
    hint: "First take out the common numeric factor, then apply identity.",
    keyConcepts: ["combined factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Forgetting to factor out 3 first."],
    tags: ["ICSE", "class8", "ch13", "complete-factorisation"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch13-ics-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise: x² + 5x + 6 by splitting the middle term.",
    answer: "Find two numbers that multiply to 6 and add to 5: 2 and 3. x²+2x+3x+6 = x(x+2)+3(x+2) = (x+2)(x+3).",
    steps: [
      { stepNumber: 1, title: "Split middle term", explanation: "5x = 2x + 3x." },
      { stepNumber: 2, title: "Group", explanation: "(x²+2x)+(3x+6)." },
      { stepNumber: 3, title: "Factor", explanation: "x(x+2)+3(x+2)=(x+2)(x+3)." },
    ],
    hint: "Find two numbers with product = constant term and sum = coefficient of x.",
    keyConcepts: ["splitting middle term"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch13", "split-middle"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch13-ics-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise: a⁴ − b⁴ completely.",
    answer: "(a²+b²)(a²−b²) = (a²+b²)(a+b)(a−b).",
    steps: [
      { stepNumber: 1, title: "First factorisation", explanation: "(a²)²−(b²)²=(a²+b²)(a²−b²)." },
      { stepNumber: 2, title: "Further", explanation: "(a²−b²)=(a+b)(a−b)." },
    ],
    hint: "Note that a²+b² cannot be factorised further over integers.",
    keyConcepts: ["repeated factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Stopping at (a²+b²)(a²−b²) without factorising further."],
    tags: ["ICSE", "class8", "ch13", "complete-factor"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch13-ics-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "icse", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Divide (2x³ − 3x² − 2x) by (x − 2).",
    answer: "2x³−3x²−2x = x(2x²−3x−2) = x(2x+1)(x−2). Divide by (x−2): x(2x+1).",
    steps: [
      { stepNumber: 1, title: "Factor out x", explanation: "x(2x²−3x−2)." },
      { stepNumber: 2, title: "Factorise 2x²−3x−2", explanation: "2x²−4x+x−2=2x(x−2)+1(x−2)=(x−2)(2x+1)." },
      { stepNumber: 3, title: "Cancel (x−2)", explanation: "x(2x+1)." },
    ],
    hint: "Factor completely, then cancel the divisor.",
    keyConcepts: ["polynomial division", "cubic factorisation"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch13", "cubic-division"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch13-ics-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise: x² + y² + z² + 2xy − 2xz − 2yz.",
    answer: "= (x + y − z)². Check: (x+y−z)²=x²+y²+z²+2xy−2xz−2yz ✓.",
    steps: [
      { stepNumber: 1, title: "Use (a+b+c)² template", explanation: "a=x, b=y, c=−z: (x+y+(−z))²." },
      { stepNumber: 2, title: "Expand to verify", explanation: "x²+y²+z²+2xy−2xz−2yz ✓." },
    ],
    hint: "Try (x + y − z)² and verify.",
    keyConcepts: ["three-term identity factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Not considering negative values for a, b, c in the identity."],
    tags: ["ICSE", "class8", "ch13", "three-term-factor"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch13-ics-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise: x³ + 3x² + 2x + 6.",
    answer: "Group: (x³+3x²)+(2x+6) = x²(x+3)+2(x+3) = (x+3)(x²+2).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "(x³+3x²)+(2x+6)." },
      { stepNumber: 2, title: "Factor each", explanation: "x²(x+3)+2(x+3)." },
      { stepNumber: 3, title: "Common factor", explanation: "(x+3)(x²+2)." },
    ],
    hint: "Group the first two and last two terms.",
    keyConcepts: ["grouping with cubic"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch13", "cubic-grouping"],
    source: "icse",
  },

  {
    id: "bo-mth-8-ch13-ics-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "ICSE",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "icse", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "If (x² − 4x + k) is exactly divisible by (x − 2), find k.",
    answer: "Divisible by (x−2) means x=2 is a root. Substitute: 4−8+k=0. k=4.",
    steps: [
      { stepNumber: 1, title: "Factor theorem", explanation: "If (x−2) divides, then f(2)=0." },
      { stepNumber: 2, title: "Substitute x=2", explanation: "4−8+k=0 → k=4." },
    ],
    hint: "Use the factor theorem: if (x−a) divides f(x), then f(a) = 0.",
    keyConcepts: ["factor theorem", "finding k"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: ["ICSE", "class8", "ch13", "factor-theorem"],
    source: "icse",
  },

  // ── COMPETENCY ───────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch13-cmp-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A square field has area (9x² − 24x + 16) m². Express the side as a factored expression.",
    answer: "9x²−24x+16 = (3x−4)². Side = (3x−4) m.",
    steps: [{ stepNumber: 1, title: "Factorise", explanation: "(3x)²−2×3x×4+4²=(3x−4)²." }],
    hint: "Area = side². Factorise to find side.",
    keyConcepts: ["perfect square", "geometry application"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Factorise: x² − 36.",
    answer: "(x+6)(x−6).",
    options: ["A) (x−6)²", "B) (x+6)²", "C) (x+6)(x−6)", "D) (x+6)(x+6)"],
    correctOption: "C",
    steps: [{ stepNumber: 1, title: "Difference of squares", explanation: "x²−6²=(x+6)(x−6)." }],
    hint: "36 = 6².",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "The area of a rectangle is (x² + 7x + 10) cm² and width is (x + 2). Find the length.",
    answer: "Factorise: x²+7x+10=(x+2)(x+5). Length = (x+5) cm.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "(x+2)(x+5)." },
      { stepNumber: 2, title: "Divide", explanation: "Length = x+5." },
    ],
    hint: "Length = Area ÷ Width.",
    keyConcepts: ["division", "geometry"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "real-world"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 15p²q³ − 25p³q².",
    answer: "5p²q²(3q − 5p).",
    steps: [{ stepNumber: 1, title: "HCF = 5p²q²", explanation: "5p²q²(3q−5p)." }],
    hint: "HCF of 15 and 25 is 5; common variables are p²q².",
    keyConcepts: ["HCF factorisation"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "common-factor"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "analyse",
    marks: 2, estimatedTimeMinutes: 4,
    question: "A student divides (x² − 9) by (x − 3) and gets x. Is this correct?",
    answer: "No. x²−9=(x+3)(x−3). Divide by (x−3): x+3 (not x). The student forgot to factorise the dividend.",
    steps: [
      { stepNumber: 1, title: "Correct factorisation", explanation: "(x+3)(x−3)÷(x−3)=x+3." },
    ],
    hint: "Factorise the numerator first, then cancel.",
    keyConcepts: ["error correction", "difference of squares"],
    conceptsCovered: ["mth:8:ch13:error-finding-in-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "error-check"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Factorise: 2x² + 6x + x + 3.",
    answer: "2x(x+3)+1(x+3) = (x+3)(2x+1).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "(2x²+6x)+(x+3)." },
      { stepNumber: 2, title: "Factor", explanation: "2x(x+3)+1(x+3)=(x+3)(2x+1)." },
    ],
    hint: "The middle term has already been split — just group and factor.",
    keyConcepts: ["grouping from split form"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "grouping"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 81 − a².",
    answer: "9² − a² = (9+a)(9−a).",
    steps: [{ stepNumber: 1, title: "Difference of squares", explanation: "(9+a)(9−a)." }],
    hint: "Write 81 = 9².",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "numerical-diff-sq"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "A polynomial (6x² + 18x) represents the area of a rectangle. Factor it to find possible dimensions.",
    answer: "6x(x + 3). Dimensions could be 6x and (x+3), or 2x and 3(x+3)=3x+9, etc.",
    steps: [
      { stepNumber: 1, title: "HCF = 6x", explanation: "6x(x+3)." },
    ],
    hint: "Factor out the HCF to express as a product of two factors.",
    keyConcepts: ["factorisation and geometry"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "geometry"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Show algebraically that any integer of the form (n² − 1) can always be factorised as a product of two consecutive integers.",
    answer: "n²−1 = (n+1)(n−1). These are consecutive integers on either side of n. For example, n=5: 25−1=24=(6)(4), and 4,6 are not consecutive... They are n−1 and n+1 which differ by 2. Note: (n−1) and (n+1) are not consecutive (differ by 2); they are two integers with n between them. Correction: n²−1=(n−1)(n+1). These are separated by 2, not consecutive. But if n is even, then n−1 and n+1 are both odd; if n is odd, both are even. The key fact: n²−1 = (n−1)(n+1) always factors as product of two integers.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "n²−1=(n+1)(n−1)." },
      { stepNumber: 2, title: "Note", explanation: "These two factors are n−1 and n+1, always both positive for n>1." },
    ],
    hint: "a²−b² = (a+b)(a−b); use a=n, b=1.",
    keyConcepts: ["difference of squares", "number theory"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "number-theory"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Divide (x³ − 8) by (x − 2).",
    answer: "x³−8=(x−2)(x²+2x+4). So (x³−8)÷(x−2) = x²+2x+4.",
    steps: [
      { stepNumber: 1, title: "Recognise difference of cubes", explanation: "x³−2³=(x−2)(x²+2x+4)." },
      { stepNumber: 2, title: "Cancel", explanation: "x²+2x+4." },
    ],
    hint: "a³−b³ = (a−b)(a²+ab+b²).",
    keyConcepts: ["difference of cubes", "division"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "diff-of-cubes"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Factorise by grouping: 6xy − 4x + 3y − 2.",
    answer: "(6xy−4x)+(3y−2) = 2x(3y−2)+1(3y−2) = (3y−2)(2x+1).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "2x(3y−2)+(3y−2)." },
      { stepNumber: 2, title: "Factor", explanation: "(3y−2)(2x+1)." },
    ],
    hint: "Group first two and last two.",
    keyConcepts: ["grouping"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "grouping"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "competency", questionFormat: "MCQ",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Which is fully factorised form of 2x² − 8?",
    answer: "2(x+2)(x−2).",
    options: ["A) 2(x²−4)", "B) (2x+4)(x−2)", "C) 2(x+2)(x−2)", "D) (x+2)(2x−4)"],
    correctOption: "C",
    steps: [
      { stepNumber: 1, title: "Common factor", explanation: "2(x²−4)." },
      { stepNumber: 2, title: "Difference of squares", explanation: "2(x+2)(x−2)." },
    ],
    hint: "First take out 2, then apply difference of squares.",
    keyConcepts: ["complete factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "MCQ"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-013",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: (x+2)² + 3(x+2).",
    answer: "Let u = x+2. u² + 3u = u(u+3) = (x+2)(x+5).",
    steps: [
      { stepNumber: 1, title: "Common factor (x+2)", explanation: "(x+2)[(x+2)+3]=(x+2)(x+5)." },
    ],
    hint: "Treat (x+2) as a single entity and factor it out.",
    keyConcepts: ["common factor with bracket"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "bracket-factor"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-014",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Divide: (a² − 5a + 6) ÷ (a − 2).",
    answer: "(a−2)(a−3)÷(a−2) = a−3.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "a²−5a+6=(a−2)(a−3)." },
      { stepNumber: 2, title: "Divide", explanation: "a−3." },
    ],
    hint: "Find two numbers with product 6 and sum −5: −2 and −3.",
    keyConcepts: ["polynomial division"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "division"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-015",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Factorise: x⁴ − 10x² + 9.",
    answer: "Let u=x². u²−10u+9=(u−1)(u−9)=(x²−1)(x²−9)=(x+1)(x−1)(x+3)(x−3).",
    steps: [
      { stepNumber: 1, title: "Substitution", explanation: "u=x²: u²−10u+9=(u−1)(u−9)." },
      { stepNumber: 2, title: "Substitute back", explanation: "(x²−1)(x²−9)." },
      { stepNumber: 3, title: "Factor further", explanation: "(x+1)(x−1)(x+3)(x−3)." },
    ],
    hint: "Let u = x² to reduce to a quadratic in u.",
    keyConcepts: ["substitution", "bi-quadratic factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Not factorising (x²−1) and (x²−9) further."],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "bi-quadratic"],
    source: "competency",
  },

  {
    id: "bo-mth-8-ch13-cmp-016",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "competency", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Factorise: a² + ab − a − b.",
    answer: "(a²+ab)+(−a−b) = a(a+b)−1(a+b) = (a+b)(a−1).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "a(a+b)−(a+b)." },
      { stepNumber: 2, title: "Factor (a+b)", explanation: "(a+b)(a−1)." },
    ],
    hint: "Group first two and last two terms, factor each.",
    keyConcepts: ["grouping"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.COMPETENCY_BASED, "class8", "ch13", "grouping"],
    source: "competency",
  },

  // ── HOTS ─────────────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch13-hot-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Prove that n² − n is always divisible by 2 for any positive integer n.",
    answer: "n²−n = n(n−1). This is the product of two consecutive integers n and n−1. Among any two consecutive integers, one must be even. Therefore n(n−1) is always even, i.e., divisible by 2. ✓",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "n²−n=n(n−1)." },
      { stepNumber: 2, title: "Consecutive integers", explanation: "n and n−1 are consecutive. One of them is always even." },
      { stepNumber: 3, title: "Conclude", explanation: "Product of consecutive integers is always even → divisible by 2." },
    ],
    hint: "Factor n²−n first, then think about the properties of consecutive integers.",
    keyConcepts: ["divisibility", "factorisation proof"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: ["Proving only with specific examples — must show for general n."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "divisibility-proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Factorise: x² + 2xy + y² − z².",
    answer: "(x+y)² − z² = (x+y+z)(x+y−z).",
    steps: [
      { stepNumber: 1, title: "Recognise (x+y)²", explanation: "x²+2xy+y²=(x+y)²." },
      { stepNumber: 2, title: "Difference of squares", explanation: "(x+y)²−z²=(x+y+z)(x+y−z)." },
    ],
    hint: "Combine the first three terms as a perfect square, then apply difference of squares.",
    keyConcepts: ["combined factorisation", "strategic grouping"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "combined-identity"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "If P(x) = x² + kx + 12 is divisible by (x + 4), find k and the other factor.",
    answer: "P(−4) = 0: 16 − 4k + 12 = 0 → 28 = 4k → k = 7. So P(x) = x²+7x+12 = (x+4)(x+3). Other factor = (x+3).",
    steps: [
      { stepNumber: 1, title: "Factor theorem", explanation: "P(−4) = 16 − 4k + 12 = 0." },
      { stepNumber: 2, title: "Solve for k", explanation: "28 = 4k; k = 7." },
      { stepNumber: 3, title: "Other factor", explanation: "(x+3)." },
    ],
    hint: "If (x+4) is a factor, then x = −4 is a root.",
    keyConcepts: ["factor theorem", "finding k"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "factor-theorem"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Using factorisation, prove that for integers m and n: m⁴ − n⁴ is always divisible by m − n (when m ≠ n).",
    answer: "m⁴−n⁴ = (m²+n²)(m²−n²) = (m²+n²)(m+n)(m−n). Since (m−n) is a factor, m⁴−n⁴ is always divisible by m−n. ✓",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "(m²+n²)(m+n)(m−n)." },
      { stepNumber: 2, title: "(m−n) is a factor", explanation: "Therefore divisible by (m−n)." },
    ],
    hint: "Apply the difference of squares identity repeatedly.",
    keyConcepts: ["divisibility", "repeated factorisation", "proof"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Claiming m⁴−n⁴=(m−n)⁴ — this is false."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "divisibility-proof"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Create a trinomial that is a perfect square and has 6x as its middle term. Show that it factors.",
    answer: "For middle term 6x = 2ab where a=x: 2(x)(b)=6x → b=3. Trinomial: x²+6x+9 = (x+3)². Another option: 2(3x)(1)=6x → (3x)²+6x+1=9x²+6x+1=(3x+1)².",
    steps: [
      { stepNumber: 1, title: "Match middle term", explanation: "2ab=6x; if a=x, b=3: trinomial x²+6x+9=(x+3)²." },
      { stepNumber: 2, title: "Verify", explanation: "(x+3)²=x²+6x+9 ✓." },
    ],
    hint: "Middle term 2ab = 6x; choose a and b accordingly.",
    keyConcepts: ["reverse identity", "creating perfect squares"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "create"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "A student says: 'If (a−b) divides (aⁿ−bⁿ) for all positive integers n.' Verify for n=1,2,3 and state whether this claim is valid.",
    answer: "n=1: a−b = (a−b)×1. ✓. n=2: a²−b²=(a+b)(a−b). ✓. n=3: a³−b³=(a²+ab+b²)(a−b). ✓. The claim is valid: (a−b) always divides (aⁿ−bⁿ) for any positive integer n. This follows from the factorisation aⁿ−bⁿ=(a−b)(aⁿ⁻¹+aⁿ⁻²b+...+bⁿ⁻¹).",
    steps: [
      { stepNumber: 1, title: "n=1,2,3 verified", explanation: "All divisible by (a−b)." },
      { stepNumber: 2, title: "General result", explanation: "aⁿ−bⁿ=(a−b)×(sum of terms), valid for all n." },
    ],
    hint: "Factor each case and look for (a−b) as a common factor.",
    keyConcepts: ["divisibility", "generalisation", "factorisation pattern"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: ["Not providing a general justification — examples alone don't prove for all n."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "generalise"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 4, estimatedTimeMinutes: 8,
    question: "Factorise completely: x⁶ − y⁶.",
    answer: "x⁶−y⁶ = (x³)²−(y³)² = (x³+y³)(x³−y³) = (x+y)(x²−xy+y²)(x−y)(x²+xy+y²).",
    steps: [
      { stepNumber: 1, title: "Difference of squares", explanation: "(x³+y³)(x³−y³)." },
      { stepNumber: 2, title: "Sum of cubes", explanation: "x³+y³=(x+y)(x²−xy+y²)." },
      { stepNumber: 3, title: "Difference of cubes", explanation: "x³−y³=(x−y)(x²+xy+y²)." },
    ],
    hint: "First apply difference of squares, then sum/difference of cubes.",
    keyConcepts: ["complete factorisation", "sum and difference of cubes"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Stopping after one step."],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "complete-factor-x6"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "evaluate",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Factorise: x² − (a+b)x + ab.",
    answer: "x² − ax − bx + ab = x(x−a) − b(x−a) = (x−a)(x−b).",
    steps: [
      { stepNumber: 1, title: "Split middle term", explanation: "−(a+b)x = −ax−bx." },
      { stepNumber: 2, title: "Group", explanation: "(x²−ax)+(−bx+ab)=x(x−a)−b(x−a)." },
      { stepNumber: 3, title: "Factor", explanation: "(x−a)(x−b)." },
    ],
    hint: "Split −(a+b)x into −ax−bx and apply grouping.",
    keyConcepts: ["general quadratic factorisation", "splitting middle term"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "general-quadratic"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "hots", questionFormat: "ShortAnswer",
    difficulty: "hard", bloomsLevel: "analyse",
    marks: 3, estimatedTimeMinutes: 6,
    question: "Show that (x+y+z)² − (x²+y²+z²) = 2(xy+yz+zx) and deduce a condition for x+y+z to equal zero.",
    answer: "(x+y+z)² = x²+y²+z²+2(xy+yz+zx). So (x+y+z)²−(x²+y²+z²) = 2(xy+yz+zx). If x+y+z=0: 0²−(x²+y²+z²)=2(xy+yz+zx) → x²+y²+z² = −2(xy+yz+zx). This means for x+y+z=0, xy+yz+zx ≤ 0.",
    steps: [
      { stepNumber: 1, title: "Expand (x+y+z)²", explanation: "x²+y²+z²+2(xy+yz+zx)." },
      { stepNumber: 2, title: "Subtract x²+y²+z²", explanation: "2(xy+yz+zx)." },
      { stepNumber: 3, title: "Condition for x+y+z=0", explanation: "x²+y²+z²=−2(xy+yz+zx)." },
    ],
    hint: "Use the (a+b+c)² identity and rearrange.",
    keyConcepts: ["identity deduction", "condition analysis"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "deduction"],
    source: "hots",
  },

  {
    id: "bo-mth-8-ch13-hot-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "hots", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "create",
    marks: 5, estimatedTimeMinutes: 10,
    question: "Design a problem where a polynomial must be divided by a binomial to find a missing side of a geometric shape. Solve it.",
    answer: "Problem: The volume of a rectangular box is (2x³+11x²+17x+6) cm³. The height is (x+1) cm and the length is (2x+3) cm. Find the width. Solution: Width = Volume/(height×length). First divide 2x³+11x²+17x+6 by (x+1). 2x³+11x²+17x+6 ÷ (x+1): 2x²(x+1)=2x³+2x²; rem=9x²+17x+6. 9x(x+1)=9x²+9x; rem=8x+6. 8(x+1)=8x+8; rem=−2. Hmm: let me try (2x+3)(x+1)(x+2)=2x³+7x²+7x+6... Let me recompute with (2x+3)(x+1)=2x²+5x+3. (2x²+5x+3)(x+2)=2x³+4x²+5x²+10x+3x+6=2x³+9x²+13x+6. Not matching. Revised problem: Volume=(2x³+9x²+13x+6), height=(x+1), length=(2x+3). Width=(2x³+9x²+13x+6)/((x+1)(2x+3))=(x+2).",
    steps: [
      { stepNumber: 1, title: "Problem setup", explanation: "Volume=(2x³+9x²+13x+6), h=(x+1), l=(2x+3)." },
      { stepNumber: 2, title: "h×l=(x+1)(2x+3)=2x²+5x+3", explanation: "Divide volume by 2x²+5x+3." },
      { stepNumber: 3, title: "Divide", explanation: "2x³+9x²+13x+6÷(2x²+5x+3): x(2x²+5x+3)=2x³+5x²+3x; rem=4x²+10x+6=2(2x²+5x+3). Quotient=x+2." },
    ],
    hint: "Design volume as a product of three linear factors, then divide.",
    keyConcepts: ["polynomial division", "geometric application"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.HOTS, "class8", "ch13", "design-problem"],
    source: "hots",
  },

  // ── PREVIOUS-YEAR ────────────────────────────────────────────────────────────

  {
    id: "bo-mth-8-ch13-pyq-001",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 14m⁵n⁴p² − 42m⁷n³p.",
    answer: "HCF = 14m⁵n³p. 14m⁵n³p(n p − 3m²) = 14m⁵n³p(np − 3m²).",
    steps: [{ stepNumber: 1, title: "HCF = 14m⁵n³p", explanation: "14m⁵n³p(np−3m²)." }],
    hint: "HCF of 14 and 42 is 14; take lowest power of each variable.",
    keyConcepts: ["HCF factorisation"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-002",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 100 − 49y².",
    answer: "10² − (7y)² = (10+7y)(10−7y).",
    steps: [{ stepNumber: 1, title: "Difference of squares", explanation: "(10+7y)(10−7y)." }],
    hint: "100 = 10², 49y² = (7y)².",
    keyConcepts: ["difference of squares"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-003",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 4,
    question: "Factorise: 10ab + 4a + 5b + 2.",
    answer: "Group: (10ab+4a)+(5b+2) = 2a(5b+2)+1(5b+2) = (5b+2)(2a+1).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "2a(5b+2)+(5b+2)." },
      { stepNumber: 2, title: "Factor", explanation: "(5b+2)(2a+1)." },
    ],
    hint: "Group first two and last two.",
    keyConcepts: ["grouping"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-004",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Divide: (x² − 9x + 20) ÷ (x − 4).",
    answer: "x²−9x+20=(x−4)(x−5). Quotient = x−5.",
    steps: [
      { stepNumber: 1, title: "Factorise", explanation: "(x−4)(x−5)." },
      { stepNumber: 2, title: "Divide", explanation: "x−5." },
    ],
    hint: "Find two numbers with product 20 and sum −9: −4 and −5.",
    keyConcepts: ["polynomial division"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-005",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "Factorise: x² + 6x + 9.",
    answer: "(x + 3)².",
    options: ["A) (x+9)(x+1)", "B) (x+3)(x+3)", "C) (x−3)²", "D) (x+3)(x−3)"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "(x+3)²=x²+6x+9", explanation: "(x+3)(x+3)." }],
    hint: "Perfect square trinomial: 2×3=6, 3²=9 ✓.",
    keyConcepts: ["perfect square"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-006",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Simplify: (x² − 25)/(x − 5).",
    answer: "(x+5)(x−5)/(x−5) = x+5 (for x ≠ 5).",
    steps: [{ stepNumber: 1, title: "Factorise and cancel", explanation: "(x+5)(x−5)÷(x−5)=x+5." }],
    hint: "Factorise the numerator first.",
    keyConcepts: ["rational expression simplification"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-007",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t1", topicName: "Factorisation by Common Factor",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 3x³y − 6x²y² + 9xy³.",
    answer: "3xy(x² − 2xy + 3y²).",
    steps: [{ stepNumber: 1, title: "HCF = 3xy", explanation: "3xy(x²−2xy+3y²)." }],
    hint: "HCF of 3,6,9 = 3; minimum variable powers: x¹, y¹.",
    keyConcepts: ["common factor"],
    conceptsCovered: ["mth:8:ch13:common-factor-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-008",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t2", topicName: "Factorisation by Grouping",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 2a + 2b + a² + ab.",
    answer: "Group: (2a+2b)+(a²+ab) = 2(a+b)+a(a+b) = (a+b)(2+a) = (a+b)(a+2).",
    steps: [
      { stepNumber: 1, title: "Group", explanation: "2(a+b)+a(a+b)." },
      { stepNumber: 2, title: "Factor", explanation: "(a+b)(a+2)." },
    ],
    hint: "Both groups share (a+b).",
    keyConcepts: ["grouping"],
    conceptsCovered: ["mth:8:ch13:grouping-method"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-009",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 3, estimatedTimeMinutes: 5,
    question: "Divide (2x³ + x² − 5x + 2) by (x − 1).",
    answer: "Check f(1)=2+1−5+2=0. So (x−1) divides. (2x³+x²−5x+2)÷(x−1). 2x²(x−1)=2x³−2x²; rem=3x²−5x+2. 3x(x−1)=3x²−3x; rem=−2x+2. −2(x−1)=−2x+2; rem=0. Quotient: 2x²+3x−2.",
    steps: [
      { stepNumber: 1, title: "Verify f(1)=0", explanation: "2+1−5+2=0 ✓." },
      { stepNumber: 2, title: "Divide", explanation: "2x²+3x−2." },
    ],
    hint: "If f(1)=0, (x−1) is a factor. Then perform long division.",
    keyConcepts: ["long division", "factor theorem"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-010",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "previous-year", questionFormat: "ShortAnswer",
    difficulty: "medium", bloomsLevel: "apply",
    marks: 2, estimatedTimeMinutes: 3,
    question: "Factorise: 4x² + 12xy + 9y².",
    answer: "(2x + 3y)².",
    steps: [{ stepNumber: 1, title: "Recognise (a+b)²", explanation: "(2x)²+2×2x×3y+(3y)²=(2x+3y)²." }],
    hint: "Check: 2×2x×3y=12xy ✓.",
    keyConcepts: ["perfect square trinomial"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-011",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t4", topicName: "Division of Polynomials",
    questionType: "previous-year", questionFormat: "MCQ",
    difficulty: "easy", bloomsLevel: "apply",
    marks: 1, estimatedTimeMinutes: 2,
    question: "(6x² + 5x) ÷ x = ?",
    answer: "6x + 5.",
    options: ["A) 6x + 5x", "B) 6x + 5", "C) 6 + 5x", "D) 11x"],
    correctOption: "B",
    steps: [{ stepNumber: 1, title: "Divide each term", explanation: "6x²÷x=6x; 5x÷x=5. Answer: 6x+5." }],
    hint: "Divide every term by x.",
    keyConcepts: ["monomial division"],
    conceptsCovered: ["mth:8:ch13:polynomial-division"],
    prerequisites: [],
    commonErrors: [],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ"],
    source: "previous-year",
  },

  {
    id: "bo-mth-8-ch13-pyq-012",
    schemaVersion: 2, classNum: 8, subject: "Mathematics", board: "Both",
    chapterId: "ch13", chapterName: "Factorisation",
    topicId: "t3", topicName: "Factorisation Using Identities",
    questionType: "previous-year", questionFormat: "LongAnswer",
    difficulty: "hard", bloomsLevel: "apply",
    marks: 4, estimatedTimeMinutes: 7,
    question: "Factorise: a⁴ + 4b⁴ (Sophie Germain identity).",
    answer: "a⁴+4b⁴ = a⁴+4a²b²+4b⁴−4a²b² = (a²+2b²)²−(2ab)² = (a²+2b²+2ab)(a²+2b²−2ab).",
    steps: [
      { stepNumber: 1, title: "Add and subtract 4a²b²", explanation: "a⁴+4a²b²+4b⁴−4a²b²=(a²+2b²)²−(2ab)²." },
      { stepNumber: 2, title: "Difference of squares", explanation: "(a²+2b²+2ab)(a²+2b²−2ab)." },
    ],
    hint: "Sophie Germain trick: add and subtract 4a²b² to complete the pattern.",
    keyConcepts: ["Sophie Germain identity", "advanced factorisation"],
    conceptsCovered: ["mth:8:ch13:factorisation-by-identity"],
    prerequisites: [],
    commonErrors: ["Not knowing to add and subtract the same term."],
    tags: [STANDARD_TAGS.PREVIOUS_YEAR, "class8", "ch13", "PYQ-advanced"],
    source: "previous-year",
  },
];
