// @ts-nocheck
/**
 * Question Bank — Mathematics, Class 8, Chapter 10 (bank ch14): Visualising Solid Shapes
 *
 * 75 curated questions — difficulty: Easy 40% (30), Medium 40% (30), Hard 20% (15)
 * Board: Both (CBSE + ICSE) | Category: standard | Schema: QuestionV2
 *
 * Topic coverage:
 *   t1 Views of 3D Shapes (Front, Side, Top)   — 25 q (10E / 10M / 5H)
 *   t2 Euler's Formula and Polyhedra            — 25 q (10E / 10M / 5H)
 *   t3 Cross-Sections, Mapping and Applications — 25 q (10E / 10M / 5H)
 *
 * Note: NCERT Class 8 Chapter 10; placed as ch14 in the bank numbering to avoid
 * conflict with the existing ch10-exponents-and-powers file.
 *
 * v1 2026-07-07 — Initial authoring (StudyAI authoring team)
 */

import type { QuestionV2 } from "../../../types";

export const CH14_VISUALISING_SOLID_SHAPES_CL8: QuestionV2[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t1 — Views of 3D Shapes  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-8-ch14-001", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What are the three standard views used to represent a 3D solid on paper?", answer:"Front view (elevation), side view (side elevation), and top view (plan view). Together these three views give a complete description of the 3D shape.", steps:[{stepNumber:1,title:"Three views",explanation:"Front, side (left/right), and top. Used in engineering and architecture to represent solids."}], hint:"Think of looking at an object from three different directions.", keyConcepts:["front view","side view","top view"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-002", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What does the top view of a cube look like?", answer:"A square. Looking directly down at a cube, you see a square face.", steps:[{stepNumber:1,title:"Cube top view",explanation:"Looking from directly above → square (the top face of the cube)."}], hint:"Look at a dice from directly above — what shape do you see?", keyConcepts:["cube","top view","square"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-003", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What does the front view of a cone look like?", answer:"An isosceles triangle. Looking at a cone from the front, you see a triangular outline with the apex at the top and the circular base appearing as a straight line at the bottom.", steps:[{stepNumber:1,title:"Cone front view",explanation:"Front view = isosceles triangle."}], hint:"Look at an ice cream cone from the front — it looks like a triangle.", keyConcepts:["cone","front view","isosceles triangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-004", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What does the top view of a cone look like?", answer:"A circle with a dot in the centre. The circle is the base, and the dot represents the apex projected downward.", steps:[{stepNumber:1,title:"Cone top view",explanation:"Looking down on a cone: outer circle = base edge. Centre dot = apex (directly below the top point)."}], hint:"Look at an ice cream cone from directly above.", keyConcepts:["cone","top view","circle with dot"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-005", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What does the front view of a cylinder look like?", answer:"A rectangle. The two sides are the vertical edges (height of cylinder) and the top and bottom are horizontal lines (the circular faces appear as lines in the front view).", steps:[{stepNumber:1,title:"Cylinder front view",explanation:"Looking at a cylinder from the front → rectangle. Height = height of cylinder; width = diameter."}], hint:"Look at a tin can from the front — it looks like a rectangle.", keyConcepts:["cylinder","front view","rectangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-006", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What is the top view of a cylinder?", answer:"A circle. Looking directly down at a cylinder, you see the circular top face.", steps:[{stepNumber:1,title:"Cylinder top view",explanation:"Looking from above → circle (the top circular face)."}], hint:"Look at a tin can from directly above.", keyConcepts:["cylinder","top view","circle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-007", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"What is the front view of a sphere?", answer:"A circle. A sphere looks like a circle from every direction.", steps:[{stepNumber:1,title:"Sphere front view",explanation:"A sphere has perfect symmetry — every view gives a circle."}], hint:"From any direction, a ball looks like a circle.", keyConcepts:["sphere","front view","circle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-008", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"TrueOrFalse", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"True or False: The top view and front view of a cube are always the same shape.", answer:"True (when the cube is in a standard upright position). Both the top view and front view of a cube are squares.", steps:[{stepNumber:1,title:"Cube views",explanation:"Top view = square; front view = square. Same shape but represent different faces."}], hint:"A cube has square faces in all orientations.", keyConcepts:["cube","views same shape","square"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-009", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"What are the three views of a triangular prism (with rectangular bases vertical)?", answer:"Front view: rectangle. Side view: triangle. Top view: rectangle (the top rectangular face).", steps:[{stepNumber:1,title:"Front view",explanation:"Rectangular side face → rectangle."},{stepNumber:2,title:"Side view",explanation:"Triangular end face → triangle."},{stepNumber:3,title:"Top view",explanation:"Looking down → rectangle (top face of prism).",result:"Front: rectangle; Side: triangle; Top: rectangle"}], hint:"Think about which face you see from each direction.", keyConcepts:["triangular prism views","rectangle triangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-010", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"What is the front view of a square pyramid?", answer:"An isosceles triangle. The front view shows two triangular faces meeting at the apex, with the base appearing as a horizontal line.", steps:[{stepNumber:1,title:"Square pyramid front",explanation:"Front view = isosceles triangle (apex at top, base as bottom line)."}], hint:"Look at an Egyptian pyramid from the front — triangle shape.", keyConcepts:["square pyramid","front view","isosceles triangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-011", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A solid is made by placing a cone on top of a cylinder (both with the same diameter). Describe its front view, side view, and top view.", answer:"Front view: rectangle (cylinder) with a triangle (cone) on top — looks like a house shape. Side view: same as front view (by symmetry). Top view: circle with a dot in the centre (the circle is the cylinder's top = cone's base edge; dot = cone apex).", steps:[{stepNumber:1,title:"Front/side view",explanation:"Rectangle (cylinder) + triangle (cone) on top = house shape."},{stepNumber:2,title:"Top view",explanation:"Circle (base of cone) with centre dot (apex).",result:"Front/Side: house shape; Top: circle with dot"}], hint:"Think of a rocketship or house shape.", keyConcepts:["composite solid views","cylinder + cone"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-012", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A solid block is made of two unit cubes placed side by side (2×1×1). Describe all three views.", answer:"Front view: two squares side by side (2×1 rectangle). Side view: one square (1×1). Top view: two squares side by side (2×1 rectangle).", steps:[{stepNumber:1,title:"Front",explanation:"2 squares wide, 1 tall → 2×1 rectangle."},{stepNumber:2,title:"Side",explanation:"1 square wide, 1 tall → 1×1 square."},{stepNumber:3,title:"Top",explanation:"2 squares long, 1 wide → 2×1 rectangle.",result:"Front: 2×1 rect; Side: 1×1 sq; Top: 2×1 rect"}], hint:"Look at two cubes glued together from each of three directions.", keyConcepts:["unit cubes","three views","2×1×1"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-013", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Two different 3D shapes have the same front view and top view. Does this prove they are the same shape?", answer:"No. Two different solids can have identical front and top views but be different in 3D. For example, a cylinder and a cone can both show a circle from the top — but they are different shapes. All three views (plus side view) are needed to uniquely identify most solids, and even then ambiguity can remain.", steps:[{stepNumber:1,title:"Counter-example",explanation:"Cylinder top view = circle. Cone top view = circle. Different shapes, same top view."},{stepNumber:2,title:"Conclusion",explanation:"Same 2 views ≠ same shape necessarily.",result:"No — all three views together still may not uniquely determine a solid"}], hint:"Can you think of two different shapes that look the same from the top?", keyConcepts:["ambiguity of views","three views needed","counter-example"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-014", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"An L-shaped structure is made of 3 unit cubes arranged as: 2 cubes in a row at the bottom and 1 cube on top of the left cube. Describe the front view, side view, and top view.", answer:"Front view: L-shape (2 wide at bottom, 1 tall on left). Side view: 2 squares stacked (2 tall on left, 1 tall on right — shows the depth). Top view: 2×1 rectangle (the 2 bottom cubes).", steps:[{stepNumber:1,title:"Front",explanation:"Looks like an L: 2 cubes wide at bottom, 1 cube extra tall on left."},{stepNumber:2,title:"Side",explanation:"From side: 2 cubes tall on one side, 1 cube on the other."},{stepNumber:3,title:"Top",explanation:"Looking down: 2 cubes in a row = 2×1 rectangle.",result:"Front: L-shape; Side: step shape; Top: 1×2 rectangle"}], hint:"Draw each view by projecting the cubes onto a flat surface.", keyConcepts:["L-shaped structure","three views"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-015", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Why do engineers draw all three views (front, side, top) of a design rather than just one?", answer:"One view gives only 2D information. Two objects can look the same from one angle but be completely different. Three standard views together give enough information to reconstruct the 3D shape unambiguously for most practical purposes, ensuring accurate manufacturing or construction.", steps:[{stepNumber:1,title:"Reason",explanation:"One view is a 2D projection — it loses depth information. Three views restore 3D understanding.",result:"Three views needed for unambiguous 3D reconstruction"}], hint:"What information does a single view NOT tell you about the object?", keyConcepts:["three-view engineering drawing","depth information","orthographic projection"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-016", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A solid made of 5 unit cubes: 3 along the bottom in a row, 1 on top of the left cube, 1 on top of the right cube. State the front, side, and top views.", answer:"Front view: step pattern — tall (2) on left, short (1) in centre, tall (2) on right. Side view: 2 units tall (some cubes have depth). Top view: 3×1 row (bottom cubes project from above).", steps:[{stepNumber:1,title:"Front",explanation:"Left column=2 high, middle=1, right=2 → M or step shape."},{stepNumber:2,title:"Top",explanation:"3 cubes in a row → 3×1 rectangle.",result:"Front: step/M shape; Top: 3×1 rectangle"}], hint:"Project each cube onto the front and top planes.", keyConcepts:["unit cube arrangement","front top views"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-017", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"The front view of a solid is a circle and the top view is also a circle. What could the solid be?", answer:"It could be a sphere (all views are circles) or a cylinder oriented differently (end-on). A hemisphere also fits. Multiple solids can have this combination of views.", steps:[{stepNumber:1,title:"Front = circle, Top = circle",explanation:"Sphere: all views are circles. Cylinder standing on its end: front = circle (end face), top = circle (top face). Multiple answers possible.",result:"Sphere or cylinder lying on its side, or hemisphere"}], hint:"Which 3D shape always looks circular from any direction?", keyConcepts:["identify from views","sphere cylinder ambiguity"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-018", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Describe how a cross-section of a cube differs from a view of a cube.", answer:"A view (projection) shows the outline of the solid from a particular direction without cutting it — you see the shadow-like 2D shape. A cross-section requires actually cutting through the solid and looking at the cut surface. Views and cross-sections can give different shapes for the same solid.", steps:[{stepNumber:1,title:"View",explanation:"No cutting — project the solid outline onto a plane."},{stepNumber:2,title:"Cross-section",explanation:"Cut the solid and examine the exposed face.",result:"View = projection; Cross-section = internal cut face"}], hint:"Does a view require cutting the solid? Does a cross-section?", keyConcepts:["view vs cross-section","projection","cut"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-019", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A solid has: front view = triangle, side view = triangle, top view = triangle. What solid could this be?", answer:"A tetrahedron (triangular pyramid). All three views of a regular tetrahedron can appear as triangles.", steps:[{stepNumber:1,title:"All views triangular",explanation:"Tetrahedron: 4 triangular faces — from any standard view angle, the outline is triangular.",result:"Tetrahedron (triangular pyramid)"}], hint:"Which solid has all triangular faces?", keyConcepts:["tetrahedron","triangular views","identify"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-020", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Describe the side view of a square pyramid when viewed from directly beside one triangular face.", answer:"An isosceles triangle — the same as the front view. All four side views of a square pyramid are identical isosceles triangles.", steps:[{stepNumber:1,title:"Side view",explanation:"Viewing a square pyramid from beside any face gives an isosceles triangle. The square base appears as a straight line at the bottom.",result:"Isosceles triangle (same as front view)"}], hint:"A square pyramid has 4 identical triangular faces.", keyConcepts:["square pyramid side view","isosceles triangle","symmetry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-021", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"A step-shaped solid is made of 3 layers of unit cubes: bottom layer = 3×1, middle = 2×1, top = 1×1. All centred. State all three views.", answer:"Front view: staircase (step shape) — 3 wide at bottom, 2 wide in middle, 1 at top. Side view: staircase — 3 tall on right descending by 1 each step left. Top view: 1×1 square (top cube only, which covers the outline from above — but the steps below are also projected, showing a 3×1 rectangle).", steps:[{stepNumber:1,title:"Front",explanation:"Step shape: bottom 3 wide, middle 2, top 1."},{stepNumber:2,title:"Side",explanation:"From side: see the stepping going back → staircase."},{stepNumber:3,title:"Top",explanation:"Looking down: see 3×1 bottom outline → 3×1 rectangle.",result:"Front/Side: staircase; Top: 3×1 rectangle"}], hint:"Project each layer onto the viewing plane for each view.", keyConcepts:["staircase solid","three views","projection"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-022", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Given front view = rectangle and top view = circle, identify the solid. Then, if front view = triangle and top view = circle, identify the solid.", answer:"Front=rectangle, top=circle → Cylinder. Front=triangle, top=circle → Cone.", steps:[{stepNumber:1,title:"Rectangle front + circle top",explanation:"Cylinder: front looks like rectangle (height × diameter); top looks like circle."},{stepNumber:2,title:"Triangle front + circle top",explanation:"Cone: front looks like triangle (apex to circular base); top looks like circle (base).",result:"Cylinder and Cone"}], hint:"What 3D shape has a circular top view?", keyConcepts:["identify from views","cylinder cone"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-023", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"create", marks:4, estimatedTimeMinutes:7, question:"Create a solid using unit cubes such that: front view is a square (2×2), top view is a 1×4 rectangle. Describe the arrangement.", answer:"One arrangement: 4 unit cubes in a 1×4 row, all at the same height, all 2 deep. This gives: front view = 2×2 square (if 2 cubes tall and 2 deep). Another: an L-shape arrangement. The key requirement is front = 2×2 and top = 1×4. A valid arrangement: 2 cubes in a row, each 2 tall, making a 2×2 front view and 1×4 top view when viewed properly.", steps:[{stepNumber:1,title:"Requirements",explanation:"Front = 2×2 square; Top = 1×4 rectangle."},{stepNumber:2,title:"Design",explanation:"Place 2 unit cubes in a 1×2 row. Stack 2 layers → front = 2×2. From top: 1×2. Hmm, need 1×4 top. Revise: 4 cubes in a row, 1×4, each 2 tall. Front = 2 tall × 1 wide = 2×1... Need to reconsider. Actually: 2 tall × 2 side-by-side cubes, 4 cubes making a 2×2 front, but seen from top as 1×2. This problem has multiple solutions — students explore.",result:"Multiple valid arrangements possible; explore by building"}], hint:"Start with the top view (1×4 rectangle) and build upward.", keyConcepts:["unit cube design","given views","creative thinking"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-024", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"An engineer gives only the front view (rectangle) and top view (rectangle) of a solid and says it is a cuboid. Is this sufficient information to determine the cuboid's dimensions?", answer:"Only partially. The front view gives height and width; the top view gives length and width. These two together give height, width, and length — enough to determine the dimensions. However, without scale, only proportions are known. The side view (rectangle) confirms depth. In practice, all three views with scale markings are needed for full specification.", steps:[{stepNumber:1,title:"Front view",explanation:"Gives height (h) and width (w)."},{stepNumber:2,title:"Top view",explanation:"Gives length (l) and width (w) — confirms width."},{stepNumber:3,title:"Conclusion",explanation:"Two views give h, w, l — sufficient for dimensions if scale is given.",result:"Yes, but all three views with scale are standard engineering practice"}], hint:"What dimension does each view provide?", keyConcepts:["engineering views","cuboid dimensions","orthographic projection"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-025", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t1", topicName:"Views of 3D Shapes", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:3, estimatedTimeMinutes:5, question:"Match the solid to its three views: (a) Sphere: all circles (b) Cylinder: circle (top), rectangle (front) (c) Cone: circle (top), triangle (front) (d) Cube: square (all views). State if this matching is correct and fill in any errors.", answer:"All four matchings are correct. (a) Sphere → all circles ✓. (b) Cylinder → top=circle, front=rectangle ✓. (c) Cone → top=circle, front=triangle ✓. (d) Cube → all three views = squares ✓.", steps:[{stepNumber:1,title:"Verify each",explanation:"All four matchings match the standard views for these solids.",result:"All correct ✓"}], hint:"Check each solid's standard views from memory.", keyConcepts:["matching views","sphere cylinder cone cube"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t2 — Euler's Formula and Polyhedra  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-8-ch14-026", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"State Euler's formula for polyhedra.", answer:"F + V − E = 2, where F = faces, V = vertices, E = edges. Equivalently: F + V = E + 2.", steps:[{stepNumber:1,title:"Euler's formula",explanation:"F + V − E = 2 (or F + V = E + 2). Valid for all convex polyhedra."}], hint:"Named after Leonhard Euler; relates faces, vertices, and edges.", keyConcepts:["Euler's formula","F+V-E=2","polyhedra"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-027", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is a polyhedron?", answer:"A polyhedron is a 3D solid whose faces are all flat polygons. Examples: cube, cuboid, prisms, pyramids. Spheres, cones, and cylinders are NOT polyhedra because they have curved surfaces.", steps:[{stepNumber:1,title:"Polyhedron definition",explanation:"All faces must be flat (plane) polygons. Curved surfaces disqualify a solid from being a polyhedron."}], hint:"Think of shapes made entirely of flat polygonal faces.", keyConcepts:["polyhedron","flat faces","no curved surfaces"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Thinking a cylinder is a polyhedron",correction:"A cylinder has curved faces → not a polyhedron."}], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-028", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"TrueOrFalse", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"True or False: Euler's formula applies to a sphere.", answer:"False. A sphere is not a polyhedron (it has no flat faces, edges, or vertices), so Euler's formula for polyhedra does not apply to it.", steps:[{stepNumber:1,title:"Sphere",explanation:"Sphere: no faces (F), no edges (E), no vertices (V). It is not a polyhedron. Euler's formula only applies to polyhedra."}], hint:"Euler's formula is only for polyhedra — shapes with flat faces.", keyConcepts:["Euler's formula limitation","sphere not polyhedron"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-029", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"Verify Euler's formula for a cube.", answer:"Cube: F=6, V=8, E=12. F+V−E = 6+8−12 = 2. ✓", steps:[{stepNumber:1,title:"Cube properties",explanation:"F=6, V=8, E=12."},{stepNumber:2,title:"Apply formula",explanation:"6+8−12=2. ✓",result:"Euler's formula verified"}], hint:"F+V−E must equal 2.", keyConcepts:["cube","Euler verification","6+8-12=2"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-030", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"Verify Euler's formula for a triangular pyramid (tetrahedron): F=4, V=4, E=6.", answer:"F+V−E = 4+4−6 = 2. ✓", steps:[{stepNumber:1,title:"Apply",explanation:"4+4−6=2. ✓",result:"Verified"}], hint:"F+V−E=2.", keyConcepts:["tetrahedron","Euler's formula","4+4-6=2"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-031", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A polyhedron has F=5, E=8. Find V using Euler's formula.", answer:"F+V−E=2 → 5+V−8=2 → V=5.", steps:[{stepNumber:1,title:"Euler's formula",explanation:"5+V−8=2 → V=5.",result:"V=5 (square pyramid)"}], hint:"Rearrange F+V−E=2 to find V.", keyConcepts:["find V","Euler's formula","square pyramid"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-032", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A polyhedron has V=6, E=9. Find F using Euler's formula.", answer:"F+V−E=2 → F+6−9=2 → F=5 (triangular prism).", steps:[{stepNumber:1,title:"Euler's formula",explanation:"F+6−9=2 → F=5.",result:"F=5"}], hint:"F = E − V + 2.", keyConcepts:["find F","Euler's formula","triangular prism"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-033", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A polyhedron has F=7, V=10. Find E.", answer:"F+V−E=2 → 7+10−E=2 → E=15.", steps:[{stepNumber:1,title:"Euler's formula",explanation:"17−E=2 → E=15.",result:"E=15"}], hint:"E = F + V − 2.", keyConcepts:["find E","Euler's formula","E=F+V-2"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-034", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What is the difference between a convex polyhedron and a non-convex (concave) polyhedron?", answer:"A convex polyhedron has no 'dents' — all interior angles point inward and any line segment between two surface points stays inside the solid. A non-convex polyhedron has at least one 'dent' or indented part (like a star-shaped solid). Euler's formula applies to convex polyhedra.", steps:[{stepNumber:1,title:"Convex",explanation:"No dents — any two points connected by a straight line inside the solid."},{stepNumber:2,title:"Non-convex",explanation:"Has at least one concave indentation.",result:"Euler's formula: convex only"}], hint:"A convex shape looks 'puffed out'; a concave shape has at least one indentation.", keyConcepts:["convex","non-convex","Euler's formula scope"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-035", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"Name the five Platonic solids (regular convex polyhedra).", answer:"Tetrahedron (4 equilateral triangles), Cube/Hexahedron (6 squares), Octahedron (8 equilateral triangles), Dodecahedron (12 regular pentagons), Icosahedron (20 equilateral triangles).", steps:[{stepNumber:1,title:"Platonic solids",explanation:"Exactly 5 regular convex polyhedra — each with identical regular polygon faces and identical vertex arrangements."}], hint:"There are exactly 5 — tetra, hexa, octa, dodeca, icosa.", keyConcepts:["Platonic solids","5 regular polyhedra"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-036", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Can a polyhedron have: (a) 3 triangular faces, 0 other faces? (b) 4 faces each an equilateral triangle?", answer:"(a) No — 3 triangles alone cannot form a closed polyhedron (you need a base). The minimum is 4 faces (tetrahedron). (b) Yes — a tetrahedron has exactly 4 equilateral triangular faces.", steps:[{stepNumber:1,title:"3 faces",explanation:"3 triangles cannot close to form a solid — minimum is 4."},{stepNumber:2,title:"4 equilateral triangles",explanation:"Tetrahedron: valid polyhedron. ✓",result:"(a) No; (b) Yes — tetrahedron"}], hint:"Try closing 3 triangles without a base — can you form a solid?", keyConcepts:["minimum faces","tetrahedron","polyhedron validity"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-037", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"An octahedron has 8 faces (all equilateral triangles). Find E and V using Euler's formula. Verify.", answer:"For octahedron: each of 8 triangles contributes 3 edges, but each edge is shared by 2 faces → E = 8×3/2 = 12. V: F+V−E=2 → 8+V−12=2 → V=6. Verify: all vertices where 4 triangles meet → 6 vertices ✓.", steps:[{stepNumber:1,title:"Find E",explanation:"8 triangular faces × 3 edges / 2 (shared) = 12 edges."},{stepNumber:2,title:"Find V",explanation:"8+V−12=2 → V=6."},{stepNumber:3,title:"Verify",explanation:"F+V−E=8+6−12=2. ✓",result:"E=12, V=6"}], hint:"Each edge is shared by exactly 2 faces.", keyConcepts:["octahedron","Euler's formula","E=8×3/2"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-038", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A polyhedron has F=20, V=12. Find E. What solid might this be?", answer:"E = F+V−2 = 20+12−2 = 30. This is a regular dodecahedron (12 pentagonal faces) or icosahedron — actually a regular icosahedron has F=20, V=12, E=30. ✓", steps:[{stepNumber:1,title:"E = F+V−2",explanation:"E=20+12−2=30."},{stepNumber:2,title:"Identify",explanation:"Regular icosahedron: F=20, V=12, E=30.",result:"E=30; icosahedron"}], hint:"E = F + V − 2.", keyConcepts:["icosahedron","Euler's formula","E=30"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-039", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"For any prism with an n-gon base, derive a general formula for F, E, V.", answer:"F = n + 2 (n lateral rectangles + 2 n-gon bases). E = 3n (n base edges + n top edges + n vertical edges). V = 2n (n bottom + n top vertices). Verify: F+V−E = (n+2)+(2n)−3n = n+2+2n−3n = 2. ✓", steps:[{stepNumber:1,title:"Faces",explanation:"n lateral + 2 bases = n+2."},{stepNumber:2,title:"Edges",explanation:"3n."},{stepNumber:3,title:"Vertices",explanation:"2n."},{stepNumber:4,title:"Euler check",explanation:"n+2+2n−3n=2. ✓",result:"F=n+2, E=3n, V=2n"}], hint:"Count faces, edges, and vertices systematically for an n-gon prism.", keyConcepts:["prism formula","general formula","Euler verify"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-040", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"For any pyramid with an n-gon base, derive a general formula for F, E, V.", answer:"F = n + 1 (n triangular faces + 1 n-gon base). E = 2n (n base edges + n slant edges). V = n + 1 (n base vertices + 1 apex). Verify: F+V−E = (n+1)+(n+1)−2n = 2n+2−2n = 2. ✓", steps:[{stepNumber:1,title:"Faces",explanation:"n triangles + 1 base = n+1."},{stepNumber:2,title:"Edges",explanation:"n base + n slant = 2n."},{stepNumber:3,title:"Vertices",explanation:"n base + 1 apex = n+1."},{stepNumber:4,title:"Euler",explanation:"n+1+n+1−2n=2. ✓",result:"F=n+1, E=2n, V=n+1"}], hint:"Count each component for a pyramid with n-sided base.", keyConcepts:["pyramid formula","F=n+1 E=2n V=n+1","Euler verify"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-041", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"Is it possible to have a polyhedron with 10 faces, 20 edges, and 15 vertices?", answer:"Check: F+V−E = 10+15−20 = 5 ≠ 2. NOT a valid polyhedron. Such a solid cannot exist.", steps:[{stepNumber:1,title:"Apply Euler's formula",explanation:"10+15−20=5≠2."},{stepNumber:2,title:"Conclusion",explanation:"Invalid — no such polyhedron exists.",result:"Not a valid polyhedron"}], hint:"F+V−E must equal 2 for any polyhedron.", keyConcepts:["validity check","Euler's formula","not polyhedron"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-042", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"Prove that a polyhedron cannot have fewer than 4 faces.", answer:"Suppose F < 4, i.e., F ≤ 3. With 3 faces, E ≥ 3 (one face has at least 3 edges). Also V must be ≥ 3. Then F+V−E ≤ 3+3−3 = 3, but F+V−E must equal 2. We cannot form a closed solid with only 1 or 2 faces (you cannot enclose 3D space). With 3 faces you get a degenerate form. Minimum closed polyhedron = tetrahedron with F=4.", steps:[{stepNumber:1,title:"Try F=3",explanation:"Three faces cannot close into a 3D solid without sharing edges → not a polyhedron."},{stepNumber:2,title:"Minimum",explanation:"F=4 (tetrahedron) is the minimum closed polyhedron.",result:"Minimum F = 4; cannot be less"}], hint:"Try to close a solid with only 3 faces — can you do it?", keyConcepts:["minimum faces","proof","tetrahedron minimum"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-043", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A polyhedron has all faces as quadrilaterals. If it has 6 quadrilateral faces, find E and V, and identify the shape.", answer:"If all faces are quadrilaterals: 6×4 = 24 edge-face incidences, each edge shared by 2 faces → E = 24/2 = 12. V = E − F + 2 = 12 − 6 + 2 = 8. This is a cube (or cuboid).", steps:[{stepNumber:1,title:"Count E",explanation:"6 faces × 4 edges = 24; /2 = 12 edges."},{stepNumber:2,title:"Find V",explanation:"V=12−6+2=8."},{stepNumber:3,title:"Identify",explanation:"F=6, E=12, V=8 → cube or cuboid.",result:"E=12, V=8; cube/cuboid"}], hint:"Each edge is shared by 2 faces. Use edge-face incidence counting.", keyConcepts:["all quadrilateral faces","edge counting","cube"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-044", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"Verify Euler's formula for all five Platonic solids.", answer:"Tetrahedron: F=4,V=4,E=6 → 4+4−6=2 ✓. Cube: F=6,V=8,E=12 → 2 ✓. Octahedron: F=8,V=6,E=12 → 8+6−12=2 ✓. Dodecahedron: F=12,V=20,E=30 → 12+20−30=2 ✓. Icosahedron: F=20,V=12,E=30 → 20+12−30=2 ✓.", steps:[{stepNumber:1,title:"All five",explanation:"Tetra:2✓. Cube:2✓. Octa:2✓. Dodeca:2✓. Icosa:2✓.",result:"All five Platonic solids satisfy F+V−E=2"}], hint:"Use the known F, V, E for each Platonic solid.", keyConcepts:["Platonic solids","Euler verification","all five"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-045", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t2", topicName:"Euler's Formula and Polyhedra", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"A student says: 'Since F+V=E+2, if I add one face and one vertex to a polyhedron, the number of edges stays the same.' Is the student correct?", answer:"Not necessarily. Adding one face and one vertex could require adding edges too (to connect the new vertex to the existing solid and to bound the new face). The formula F+V−E=2 tells us that if F increases by 1 and V increases by 1, then E must also increase by 1+1−0 = 2 for the formula to still hold (ΔF + ΔV − ΔE = 0 → 1+1−ΔE=0 → ΔE=2). So edges would increase by 2, not stay the same.", steps:[{stepNumber:1,title:"Differential Euler",explanation:"For the formula to hold after changes: ΔF+ΔV=ΔE. ΔF=1, ΔV=1 → ΔE=2."},{stepNumber:2,title:"Conclusion",explanation:"Edges increase by 2, not stay the same.",result:"Student is incorrect — edges increase by 2"}], hint:"Apply the formula to the changes: ΔF + ΔV − ΔE = 0.", keyConcepts:["differential Euler's formula","changes in F V E"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },

  // ═══════════════════════════════════════════════════════════════════════════
  // TOPIC t3 — Cross-Sections, Mapping and Applications  (10E / 10M / 5H)
  // ═══════════════════════════════════════════════════════════════════════════

  { id:"bo-mth-8-ch14-046", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"remember", marks:1, estimatedTimeMinutes:2, question:"What is a cross-section of a solid?", answer:"A cross-section is the 2D shape obtained by cutting a 3D solid with a flat plane. The cut exposes a flat face called the cross-section.", steps:[{stepNumber:1,title:"Definition",explanation:"Cut the solid with a flat plane → the exposed cut surface is the cross-section."}], hint:"Slicing a loaf of bread gives circular cross-sections.", keyConcepts:["cross-section","flat plane cut","2D shape"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-047", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What cross-section do you get when you cut a cube parallel to one of its faces?", answer:"A square (congruent to the face).", steps:[{stepNumber:1,title:"Parallel cut",explanation:"Cutting parallel to a square face gives a square cross-section of the same size."}], hint:"The cut is parallel to the face — so the cross-section matches the face shape.", keyConcepts:["cube","parallel cut","square cross-section"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-048", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What cross-section do you get when you cut a sphere with any flat plane?", answer:"A circle. Any flat cross-section of a sphere is a circle (the maximum being the great circle through the centre).", steps:[{stepNumber:1,title:"Sphere cross-section",explanation:"Any flat plane intersects a sphere in a circle."}], hint:"Think about cutting an orange in any direction.", keyConcepts:["sphere","circle cross-section"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-049", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What cross-section do you get when you cut a cylinder perpendicular to its axis?", answer:"A circle.", steps:[{stepNumber:1,title:"Cylinder perpendicular cut",explanation:"Cutting perpendicular to the axis (horizontal cut) gives a circular cross-section."}], hint:"Cut across a can of food horizontally.", keyConcepts:["cylinder","perpendicular cut","circle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-050", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"What cross-section do you get when you cut a cylinder parallel to its axis?", answer:"A rectangle.", steps:[{stepNumber:1,title:"Cylinder parallel cut",explanation:"Cutting along the length (parallel to axis) gives a rectangular cross-section."}], hint:"Slice a can of food along its length — what shape is exposed?", keyConcepts:["cylinder","parallel cut","rectangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-051", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A map has scale 1 cm = 25 km. If two towns are 8 cm apart on the map, what is their actual distance?", answer:"8 × 25 = 200 km.", steps:[{stepNumber:1,title:"Apply scale",explanation:"8 × 25 = 200 km.",result:"200 km"}], hint:"Multiply map distance by scale factor.", keyConcepts:["map scale","actual distance"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-052", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"On a map with scale 1 cm = 5 km, a forest is 3 cm × 4 cm. Find the actual dimensions of the forest.", answer:"3×5=15 km and 4×5=20 km. Actual dimensions: 15 km × 20 km.", steps:[{stepNumber:1,title:"Scale both dimensions",explanation:"3×5=15km; 4×5=20km.",result:"15km × 20km"}], hint:"Apply scale to each dimension.", keyConcepts:["area on map","actual dimensions"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-053", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:1, estimatedTimeMinutes:2, question:"What cross-section do you get when you cut a square pyramid with a horizontal plane (parallel to the base)?", answer:"A square (smaller than the base, at that height).", steps:[{stepNumber:1,title:"Horizontal cut of pyramid",explanation:"A horizontal cut parallel to the square base gives a smaller square cross-section."}], hint:"Cutting horizontally through a pyramid gives a similar shape to the base.", keyConcepts:["pyramid","horizontal cut","smaller square"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-054", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"understand", marks:1, estimatedTimeMinutes:2, question:"In what professions is the ability to visualise 3D shapes from 2D drawings essential?", answer:"Architecture (reading blueprints), engineering (mechanical/civil design), medicine (interpreting MRI/CT scans), graphic design (3D modelling), geography (map reading), and construction.", steps:[{stepNumber:1,title:"Professions",explanation:"Any profession involving design, construction, or spatial analysis requires 3D visualisation skills."}], hint:"Think of who uses blueprints or 3D models.", keyConcepts:["applications","professions","3D visualisation"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-055", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Easy", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:3, question:"A loaf of bread is cylindrical. What shape is each slice when you slice it perpendicular to its length?", answer:"A circle (or oval/ellipse depending on the exact cross-section angle). If cut straight across (perpendicular to the length), the slice is a circle.", steps:[{stepNumber:1,title:"Cylindrical bread",explanation:"Perpendicular cross-section of a cylinder = circle.",result:"Circle"}], hint:"A cylindrical loaf cut straight across.", keyConcepts:["real-world cross-section","cylinder","bread"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-056", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"What cross-sections are possible when cutting a cone? Name at least four.", answer:"(1) Circle — horizontal cut parallel to base. (2) Ellipse — angled cut not through apex. (3) Parabola — cut parallel to the slant edge. (4) Hyperbola — steep cut through both halves of the double cone. (5) Triangle — vertical cut through the apex.", steps:[{stepNumber:1,title:"Conic sections",explanation:"Circle, ellipse, parabola, hyperbola (conic sections) + triangle (through apex).",result:"5 types of cross-sections"}], hint:"These are called conic sections — a key concept in higher mathematics.", keyConcepts:["conic sections","cone","circle ellipse parabola hyperbola triangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-057", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A map uses scale 1:50,000. Two points are 3 cm apart on the map. What is their actual distance in metres?", answer:"1:50,000 means 1 cm = 50,000 cm = 500 m. Actual distance = 3 × 500 = 1500 m = 1.5 km.", steps:[{stepNumber:1,title:"Scale meaning",explanation:"1:50,000 → 1 cm on map = 50,000 cm = 500 m in reality."},{stepNumber:2,title:"Actual distance",explanation:"3 × 500 = 1500 m = 1.5 km.",result:"1500 m (1.5 km)"}], hint:"Convert the ratio scale to a usable unit scale first.", keyConcepts:["ratio scale","1:50000","actual distance"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Forgetting to convert cm to m",correction:"50,000 cm = 500 m."}], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-058", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"A solid sphere of radius r is cut by a plane at distance d from the centre (where d < r). What is the radius of the circular cross-section?", answer:"Radius of cross-section = √(r² − d²) (by Pythagoras, the cut creates a circle at distance d from centre).", steps:[{stepNumber:1,title:"Pythagoras",explanation:"The centre, the cut point, and the circle edge form a right triangle: r² = d² + ρ², where ρ = radius of cross-section."},{stepNumber:2,title:"ρ = √(r²−d²)",explanation:"Cross-section radius = √(r²−d²).",result:"ρ = √(r²−d²)"}], hint:"Draw a right triangle from the centre to the edge of the cross-section.", keyConcepts:["sphere cross-section radius","Pythagoras","√(r²-d²)"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-059", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A CT scan produces cross-sectional images of the human body. Which 3D shape does the human trunk approximately resemble, and what cross-section do CT scans typically produce?", answer:"The human trunk is approximately cylindrical. CT scans taken perpendicular to the body's axis produce roughly circular (or oval) cross-sections showing the arrangement of organs, bones, and tissue at each level.", steps:[{stepNumber:1,title:"Shape",explanation:"Trunk ≈ cylinder (approximately)."},{stepNumber:2,title:"Cross-section",explanation:"Perpendicular cut → circular/oval cross-section → CT scan image.",result:"Cylinder-like; circular/oval cross-sections"}], hint:"Think of a CT scan as a series of horizontal slices through the body.", keyConcepts:["CT scan","cross-section","real-world","cylinder"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-060", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A rectangular room is 8m × 6m. The scale drawing on paper is 4cm × 3cm. What is the scale?", answer:"Scale: 8m → 4cm means 1cm = 2m. Verify: 6m → 3cm = 6/2 ✓. Scale: 1 cm = 2 m (or 1:200).", steps:[{stepNumber:1,title:"Find scale",explanation:"8m/4cm = 2m/cm. Verify: 6m/3cm = 2m/cm ✓.",result:"1 cm = 2 m (scale 1:200)"}], hint:"Divide actual length by map length.", keyConcepts:["scale from drawing","room plan","1:200"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-061", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"What cross-section does a vertical plane through the apex of a cone produce?", answer:"An isosceles triangle. The vertical cut through the apex and the base centre divides the cone into two equal halves, each showing an isosceles triangle cross-section.", steps:[{stepNumber:1,title:"Vertical cut through apex",explanation:"The cross-section is bounded by two slant edges and the diameter of the base → isosceles triangle.",result:"Isosceles triangle"}], hint:"Cut a cone along its height from apex to base centre.", keyConcepts:["cone","vertical apex cut","isosceles triangle"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-062", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A hexagonal prism is cut with a plane perpendicular to its axis. What is the cross-section?", answer:"A regular hexagon (same shape as the base).", steps:[{stepNumber:1,title:"Perpendicular cut",explanation:"Cutting perpendicular to the axis of a prism gives a cross-section identical to the base polygon → regular hexagon.",result:"Regular hexagon"}], hint:"The cross-section is the same shape as the prism's base when you cut perpendicular to the axis.", keyConcepts:["hexagonal prism","perpendicular cut","hexagon cross-section"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-063", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Why do we use shadows or outlines (silhouettes) to represent 3D objects in 2D drawings?", answer:"A silhouette captures the outermost boundary of a 3D object from a given direction — this is equivalent to the view (projection) from that direction. It gives a quick understanding of shape and size without needing full details, and is the basis for orthographic projection used in engineering drawings.", steps:[{stepNumber:1,title:"Silhouette = projection",explanation:"The outline (shadow) of a 3D object on a flat surface from a given direction is its view/projection from that direction."}], hint:"A shadow is a 2D projection of a 3D object.", keyConcepts:["silhouette","projection","view","shadow"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-064", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A scale model of a building has scale 1:100. If the model is 30 cm tall and 15 cm wide, what are the actual dimensions?", answer:"Actual height = 30 × 100 = 3000 cm = 30 m. Actual width = 15 × 100 = 1500 cm = 15 m.", steps:[{stepNumber:1,title:"Apply scale",explanation:"1:100 → multiply model dimensions by 100."},{stepNumber:2,title:"Convert",explanation:"Height: 3000cm=30m. Width: 1500cm=15m.",result:"30 m × 15 m"}], hint:"1:100 scale → actual = model × 100.", keyConcepts:["scale model","1:100","actual size"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-065", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"Describe how cross-sections of the Earth relate to the concept of latitude lines.", answer:"Latitude lines are the intersections of horizontal planes with the (approximately spherical) Earth. Each plane cuts the Earth perpendicular to its axis (north-south axis), producing a circular cross-section. The equator is the largest circle (great circle through the centre); latitude lines closer to the poles are smaller circles.", steps:[{stepNumber:1,title:"Horizontal planes",explanation:"Each latitude = a horizontal plane cutting through the sphere."},{stepNumber:2,title:"Cross-section",explanation:"Each cut produces a circle (smaller as you move toward poles).",result:"Latitudes = circular cross-sections of the Earth"}], hint:"Think of latitude lines as horizontal slices through the Earth.", keyConcepts:["latitude","Earth cross-section","spherical geometry"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-066", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A cube of side 6 cm is cut diagonally from one edge to the opposite edge (through a diagonal of a face). What cross-section shape is produced?", answer:"A rectangle. The diagonal cut through a square face produces a rectangular cross-section (6 cm × 6√2 cm), since it cuts from one edge to the diagonally opposite edge, creating a rectangle where one dimension is the edge length and the other is the face diagonal.", steps:[{stepNumber:1,title:"Identify the cut",explanation:"The plane passes through one edge and the opposite parallel edge (diagonal of face)."},{stepNumber:2,title:"Cross-section",explanation:"The cut surface is a rectangle with dimensions 6 cm (height of cube) × 6√2 cm (face diagonal). Wait — actually if the cut goes through one vertical edge and the parallel opposite vertical edge diagonally: the cross-section is a rectangle 6×6√2 cm. If through a face diagonal horizontally, it's a rectangle 6 × 6√2. In any case, the shape is a rectangle.",result:"Rectangle (6 cm × 6√2 cm)"}], hint:"Find two opposite parallel edges and slice through them.", keyConcepts:["diagonal cut cube","rectangular cross-section","face diagonal"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-067", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"analyse", marks:4, estimatedTimeMinutes:6, question:"A cube is cut by a plane through the midpoints of 6 non-adjacent edges. What is the cross-section?", answer:"A regular hexagon. This is the most symmetric cross-section of a cube — cutting through the midpoints of 6 edges that form a 'belt' around the cube produces a regular hexagonal cross-section.", steps:[{stepNumber:1,title:"6 midpoints cut",explanation:"Cutting through midpoints of a symmetric set of 6 edges of a cube traces a hexagonal path."},{stepNumber:2,title:"Regular hexagon",explanation:"By symmetry, all 6 sides are equal and all interior angles are 120°.",result:"Regular hexagon"}], hint:"This is the widest possible cross-section of a cube — think about cutting 'diagonally' through the body of the cube.", keyConcepts:["cube","hexagonal cross-section","midpoint cut"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-068", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"create", marks:4, estimatedTimeMinutes:7, question:"Design a situation in architecture where knowledge of cross-sections and views is critical. Describe the problem and the solution.", answer:"Example: An architect designs a domed concert hall. The dome is hemispherical. To design the supporting beams, the architect must know the cross-sections at various heights — each cross-section is a circle of decreasing radius as you go higher (r_cross = √(R² − h²) where R = dome radius and h = height above base). The front and side views show a semicircle. By analysing these cross-sections, engineers determine where structural supports are needed and calculate material quantities.", steps:[{stepNumber:1,title:"Problem",explanation:"Hemispherical dome — where to place supports?"},{stepNumber:2,title:"Cross-sections",explanation:"At height h: cross-section radius = √(R²−h²)."},{stepNumber:3,title:"Views",explanation:"Front/side view = semicircle; top view = circle.",result:"Cross-sections guide structural support placement"}], hint:"Think of famous domed buildings like the Pantheon or Gol Gumbaz.", keyConcepts:["architecture","dome","hemispherical cross-section","application"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-069", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A student claims that every cross-section of a cube is a square. Is this true?", answer:"False. A cube can produce many cross-section shapes: square (parallel to a face), rectangle (slightly angled), triangle (through three corners), hexagon (through midpoints of 6 edges), and other polygons. The student's claim is incorrect.", steps:[{stepNumber:1,title:"Square cross-section",explanation:"Parallel cut to face → square."},{stepNumber:2,title:"Other shapes",explanation:"Diagonal cuts → rectangle, triangle, hexagon."},{stepNumber:3,title:"Conclusion",explanation:"Not every cross-section is a square.",result:"False — multiple cross-section shapes are possible"}], hint:"Try cutting a cube at different angles and see what shapes appear.", keyConcepts:["cube cross-sections","not always square","multiple shapes"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Thinking only squares are possible",correction:"Cubes can produce squares, rectangles, triangles, hexagons."}], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-070", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"concept", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"analyse", marks:2, estimatedTimeMinutes:4, question:"What is the difference between a map and a plan? Give an example of each.", answer:"A map represents a large area (e.g., a country, city) at a much reduced scale, showing roads, rivers, and landmarks. A plan is a top-view technical drawing of a smaller area (e.g., a room, building floor) at a larger scale, showing precise dimensions. Example — map: road map of Delhi at 1:50,000 scale. Plan: architect's floor plan of a flat at 1:100 scale.", steps:[{stepNumber:1,title:"Map",explanation:"Large area, small scale, less detail — e.g., country map."},{stepNumber:2,title:"Plan",explanation:"Small area, larger scale, precise dimensions — e.g., floor plan.",result:"Map = large area; Plan = small area detailed drawing"}], hint:"Think about the scale and level of detail.", keyConcepts:["map vs plan","scale","level of detail"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-071", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A school playground is 120 m × 80 m. Draw it to scale on paper using 1 cm = 20 m. What are the dimensions on paper?", answer:"120/20 = 6 cm and 80/20 = 4 cm. Draw a 6 cm × 4 cm rectangle.", steps:[{stepNumber:1,title:"Scale dimensions",explanation:"120÷20=6cm; 80÷20=4cm.",result:"6 cm × 4 cm rectangle on paper"}], hint:"Divide actual dimension by scale factor.", keyConcepts:["scale drawing","playground","1 cm = 20 m"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-072", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"ncert", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"A rectangular swimming pool is 50 m × 25 m. On a site plan with scale 1 cm = 5 m, what area (in cm²) does the pool occupy on the plan?", answer:"Plan: 50/5=10 cm and 25/5=5 cm. Area on plan = 10×5 = 50 cm².", steps:[{stepNumber:1,title:"Scale dimensions",explanation:"10 cm × 5 cm."},{stepNumber:2,title:"Area",explanation:"10×5=50 cm².",result:"50 cm²"}], hint:"Find plan dimensions first, then multiply.", keyConcepts:["plan area","scale","swimming pool"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"ncert" },

  { id:"bo-mth-8-ch14-073", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"competency", questionFormat:"ShortAnswer", difficulty:"Medium", bloomsLevel:"apply", marks:2, estimatedTimeMinutes:4, question:"An archaeologist digs a trench that is 3m × 2m × 1.5m. She wants to draw the cross-section of the trench on paper at scale 1 cm = 0.5 m. What are the paper dimensions of: (a) the top opening, (b) the cross-section (front face)?", answer:"(a) Top: 3m×2m → 6cm×4cm. (b) Front face cross-section: 3m wide × 1.5m deep → 6cm × 3cm.", steps:[{stepNumber:1,title:"Scale factor",explanation:"1 cm = 0.5 m → multiply by 2."},{stepNumber:2,title:"Top opening",explanation:"3×2=6cm×4cm."},{stepNumber:3,title:"Front cross-section",explanation:"3m×1.5m → 6cm×3cm.",result:"Top: 6×4cm; Cross-section: 6×3cm"}], hint:"Divide each actual measurement by 0.5 (or multiply by 2).", keyConcepts:["trench","cross-section drawing","scale"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-074", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"hots", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:4, estimatedTimeMinutes:6, question:"A river appears as 0.8 cm wide on a map with scale 1:25,000. What is the actual width of the river in metres? If the river floods and becomes 3 times wider, how wide will it appear on the same map?", answer:"Actual width: 0.8 cm × 25,000 = 20,000 cm = 200 m. Flooded width: 200 × 3 = 600 m → on map: 600 m / 250 = 2.4 cm.", steps:[{stepNumber:1,title:"Actual width",explanation:"0.8 × 25000 = 20000 cm = 200 m."},{stepNumber:2,title:"Flooded width on map",explanation:"600 m / 250 m per cm = 2.4 cm.",result:"200 m actual; 2.4 cm on map when flooded"}], hint:"1:25,000 means 1 cm = 25,000 cm = 250 m.", keyConcepts:["ratio scale","river width","two-step map problem"], conceptsCovered:[], prerequisites:[], commonErrors:[{error:"Forgetting 25,000 cm = 250 m",correction:"Convert cm to m: 25,000 cm = 250 m."}], tags:[], source:"original" },

  { id:"bo-mth-8-ch14-075", schemaVersion:2, classNum:8, subject:"Mathematics", board:"Both", chapterId:"ch14", chapterName:"Visualising Solid Shapes", topicId:"t3", topicName:"Cross-Sections, Mapping and Applications", questionType:"previous-year", questionFormat:"ShortAnswer", difficulty:"Hard", bloomsLevel:"evaluate", marks:3, estimatedTimeMinutes:5, question:"Summarise: for each of the five common solids (cube, cylinder, cone, sphere, square pyramid), state: (a) whether it is a polyhedron, (b) its cross-section when cut parallel to the base.", answer:"Cube: polyhedron; cross-section = square. Cylinder: not polyhedron (curved face); cross-section = circle. Cone: not polyhedron; cross-section = circle. Sphere: not polyhedron; cross-section = circle. Square pyramid: polyhedron; cross-section = square (smaller). Table summary: Cube✓sq; Cylinder✗circle; Cone✗circle; Sphere✗circle; Sq.Pyramid✓sq.", steps:[{stepNumber:1,title:"Polyhedra",explanation:"Cube, square pyramid: yes. Cylinder, cone, sphere: no (curved faces)."},{stepNumber:2,title:"Cross-sections (parallel to base)",explanation:"Cube→square. Cylinder→circle. Cone→circle. Sphere→circle. Sq. Pyramid→square.",result:"Summary table as above"}], hint:"Polyhedra have only flat faces. Parallel cut to circular base → circle.", keyConcepts:["summary","polyhedron check","cross-section by shape"], conceptsCovered:[], prerequisites:[], commonErrors:[], tags:[], source:"previous-year" },
];
